- reference/3.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
- reference/docs-conceptual/whats-new/What-s-New-in-Windows-PowerShell-50.md
> Fix links for "Supporting Online Help"

- reference/6/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md
- reference/6/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md
> Update to ExperimentalFeatures cmdlets based on code PR review

- reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md
> Fixes #3385 - Typo

- reference/5.0/PowershellGet/Find-Command.md
- reference/5.1/PowershellGet/Find-Command.md
- reference/6/PowerShellGet/Find-Command.md
> Describe the MaximumVersion parameter for the Find-Command cmdlet

- reference/5.0/PowershellGet/Register-PSRepository.md
- reference/5.1/PowershellGet/Register-PSRepository.md
- reference/6/PowerShellGet/Register-PSRepository.md
> Update different aspects of the Register-PSRepository cmdlet

- reference/5.1/PowershellGet/Find-Module.md
- reference/5.1/PowershellGet/Find-Script.md
- reference/5.1/PowershellGet/Get-InstalledModule.md
- reference/5.1/PowershellGet/Get-InstalledScript.md
- reference/5.1/PowershellGet/Install-Module.md
- reference/5.1/PowershellGet/Install-Script.md
- reference/5.1/PowershellGet/Save-Module.md
- reference/5.1/PowershellGet/Save-Script.md
- reference/5.1/PowershellGet/Uninstall-Module.md
- reference/5.1/PowershellGet/Uninstall-Script.md
- reference/5.1/PowershellGet/Update-Module.md
- reference/5.1/PowershellGet/Update-Script.md
- reference/6/PowerShellGet/Find-Module.md
- reference/6/PowerShellGet/Find-Script.md
- reference/6/PowerShellGet/Get-InstalledModule.md
- reference/6/PowerShellGet/Get-InstalledScript.md
- reference/6/PowerShellGet/Install-Module.md
- reference/6/PowerShellGet/Install-Script.md
- reference/6/PowerShellGet/Save-Module.md
- reference/6/PowerShellGet/Save-Script.md
- reference/6/PowerShellGet/Uninstall-Module.md
- reference/6/PowerShellGet/Uninstall-Script.md
- reference/6/PowerShellGet/Update-Module.md
- reference/6/PowerShellGet/Update-Script.md
> Add description to the AllowPrerelease for all affected cmdlets

- reference/docs-conceptual/getting-started/cookbooks/Sorting-Objects.md
* Added two examples about using hash tables
* Added level 2 headers
> Add "Sorting Objects" examples using hash tables

- reference/docs-conceptual/getting-started/cookbooks/Sorting-Objects.md
Not fundamental but useful tips.
> Add "Sorting Objects" tips

- appveyor.yml
Added files to the list that will trigger a build.
> Adding files to only_commits.files to trigger build job

- reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
> fix #3413 - irm -usebasicparsing description error

- .openpublishing.redirection.json
- reference/5.0/Microsoft.PowerShell.Core/About/about_windows_powershell_5.0.md
- reference/docs-conceptual/learn/Getting-Detailed-Help-Information.md
- reference/docs-conceptual/toc.yml
Fixing some broken links and missing redirection
> Merge latest changes to live

- reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
- reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
- reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
> Update doc about '-Header' to 'ConvertFrom-Csv'

- reference/docs-conceptual/whats-new/breaking-changes-ps6.md
closes #3090
re: PowerShell/PowerShell#4534
> Include details about MaximumRedirection behavior change

- .openpublishing.redirection.json
- reference/5.1/Microsoft.PowerShell.Core/About/about_Logging.md
- reference/6/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
- reference/6/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
Combine 5.1 into 6.0 about_logging topic
- Also, split into windows and non-windows topic to make them more manageable
> Combine 5.1 into 6.0 about_logging topic

- reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
> Add about_PowerShell_Config

- reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md
Fix https://github.com/PowerShell/PowerShell-Docs/issues/3030
> add about_experimental_features.md

- .openpublishing.redirection.json
- gallery/readme.md
fix the build warning of redirect file
> fix the build warning of redirect file

- reference/3.0/Microsoft.PowerShell.Utility/Format-Custom.md
- reference/3.0/Microsoft.PowerShell.Utility/Format-List.md
- reference/3.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/3.0/Microsoft.PowerShell.Utility/Format-Wide.md
- reference/4.0/Microsoft.PowerShell.Utility/Format-Custom.md
- reference/4.0/Microsoft.PowerShell.Utility/Format-List.md
- reference/4.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/4.0/Microsoft.PowerShell.Utility/Format-Wide.md
- reference/5.0/Microsoft.PowerShell.Utility/Format-Custom.md
- reference/5.0/Microsoft.PowerShell.Utility/Format-List.md
- reference/5.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/5.0/Microsoft.PowerShell.Utility/Format-Wide.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Custom.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-List.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Table.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Wide.md
- reference/6/Microsoft.PowerShell.Utility/Format-Custom.md
- reference/6/Microsoft.PowerShell.Utility/Format-List.md
- reference/6/Microsoft.PowerShell.Utility/Format-Table.md
- reference/6/Microsoft.PowerShell.Utility/Format-Wide.md
> Fix #3451 - formatting problems with parameter blocks

- reference/docs-conceptual/learn/Writing-Portable-Modules.md
Fix https://github.com/PowerShell/PowerShell-Docs/issues/1401
> added writing-portable-modules.md

- reference/docs-conceptual/learn/Writing-Portable-Modules.md
> CompatiblePSEditions not avail prior to v5

- reference/6/Microsoft.PowerShell.Host/Start-Transcript.md
- reference/docs-conceptual/toc.yml
> Document `UseMinimalHeader` switch on `Start-Transcript`

- reference/3.0/Microsoft.PowerShell.Management/Restart-Service.md
- reference/4.0/Microsoft.PowerShell.Management/Restart-Service.md
- reference/4.0/PSDesiredStateConfiguration/Start-DscConfiguration.md
- reference/5.0/Microsoft.PowerShell.Management/Restart-Service.md
- reference/5.0/PSDesiredStateConfiguration/Start-DscConfiguration.md
- reference/5.1/Microsoft.PowerShell.Management/Restart-Service.md
- reference/5.1/PSDesiredStateConfiguration/Start-DscConfiguration.md
- reference/6/Microsoft.PowerShell.Management/Restart-Service.md
1/ Update Name Parameter to indicate it can take wildcards - fixes issue #3468 
2/ Changed code fencing to PowerShell
- [x ] Impacts 6 document
- [ x] Impacts 4.0 document
- [x ] Impacts 3.0 document
> update restart-service Name Parameter

- reference/3.0/Microsoft.PowerShell.Management/Register-WmiEvent.md
- reference/4.0/Microsoft.PowerShell.Management/Register-WmiEvent.md
- reference/5.0/Microsoft.PowerShell.Management/Register-WmiEvent.md
- reference/5.1/Microsoft.PowerShell.Management/Register-WmiEvent.md
> Fix minor space issues in Register-WmiEvent.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_scopes.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_scopes.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_scopes.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md
> Fixes #3490 - fixed syntax examples for scope modifier

- reference/5.0/Microsoft.PowerShell.Core/About/about_Enum.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Enum.md
- reference/6/Microsoft.PowerShell.Core/About/about_Enum.md
> Fix #3455 - add example to test for flag value

- developer/cmdlet/cmdlet-overview.md
> Removing duplicated text

- reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
> Fix #2229 - fixed $psversiontable

- dsc/tutorials/bootstrapDsc.md
Hello, @bobbytreed,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
> C59287: Removing "> "

- reference/3.0/Microsoft.PowerShell.Management/Test-Connection.md
- reference/4.0/Microsoft.PowerShell.Management/Test-Connection.md
- reference/5.0/Microsoft.PowerShell.Management/Test-Connection.md
- reference/5.1/Microsoft.PowerShell.Management/Test-Connection.md
- reference/6/Microsoft.PowerShell.Management/Test-Connection.md
> Fix #1504 -  describe TTL as hops not seconds

- reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
- reference/3.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
- reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/3.0/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
- reference/4.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
- reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/4.0/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
- reference/5.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
- reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/5.0/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
- reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/5.1/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
- reference/6/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
- reference/6/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/6/Microsoft.PowerShell.Utility/Import-Csv.md
> Parameter and link corrections in CSV documents

- reference/docs-conceptual/components/ise/Introducing-the-Windows-PowerShell-ISE.md
> spelling errors fixed

- reference/6/Microsoft.PowerShell.Core/Update-Help.md
* Cleanup file & examples
* Change prompt style to `PS>`
* Update syntax diagrams
* Add -Scope parameter that was introduced in 6.1
Fixes #2168. There are a couple additional things mentioned in the linked issue that I'm not sure if I should look at as well, or if you guys would rather do that yourselves. 😄 
> Update-Help: Add new -Scope parameter

- developer/cmdlet/how-to-support-transactions.md
Follow-up to #3503
* Omit the **[?view=\<view-name>]** portion of the URL
* Improve link title
> Revise link - Follow-up #3503

- dsc/reference/resources/windows/fileResource.md
> Closes #2823 - Update File Resource to specify credential usage.

- dsc/reference/resources/windows/fileResource.md
> fixing broken link

- reference/docs-conceptual/samples/Manipulating-Items-Directly.md
if **regsitry** entries were items -> if **registry** entries were items
> Fix typo in Manipulating-Items-Directly.md

- dsc/resources/authoringResourceClass.md
> Closes #3482 - Updates class based resource guide

- dsc/tutorials/dscCiCd.md
> closes #3326 Fixing link

- reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
> Fix #3543 - PSv5+ will autojoin lines in example 3

- dsc/resources/authoringResourceMOF.md
> Adding resource reboot logic

- reference/6/Microsoft.PowerShell.Utility/Measure-Object.md
> closes #3034 - document new v6 features of Measure-Object

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Add Debian 8 EOL information
- Also do edits to make document a little less formal and more consistent
> Add Debian 8 EOL information

- reference/3.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
> Closes #3510 closes #3509 closes #3046 - update regex docs

- reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
> Closes #3080 - document character ranges

- reference/docs-conceptual/samples/Working-with-Registry-Entries.md
> Closes #3528 - add example of setting a registry value

- developer/cmdlet/types-of-cmdlet-output.md
Fixed broken link, removed duplicate text, added section headings, style changes, and copyedits.
Original version: 76
Updated version: 90
> Closes #3560 - Fixed broken link, removed duplicate text, added section headings

- reference/5.0/PowershellGet/Install-Module.md
- reference/5.1/PowershellGet/Install-Module.md
- reference/6/PowerShellGet/Install-Module.md
> Correct the description of the AllowClobber parameter

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
> Update PowerShell lifecycles with additional EOL info

- reference/6/Microsoft.PowerShell.Management/Test-Path.md
This is a proposition of remark. But I don't know if referring to a Github issue and/or mentioning a possible future change is compliant with the current DOCS rules. Please update if necessary, or I can do it if you say me what to change...
> Added a remark paragraph according to issue #8607

- reference/6/Microsoft.PowerShell.Core/Enable-PSRemoting.md
Fixed formatting while waiting for #3436 to be fixed.
> fix style and formatting

- reference/3.0/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/4.0/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/5.0/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md
Related to Issue #2000 and PR #3590
> Updated Export-Clixml YAML for Encoding parameter Accepted values and minor copyedits

- wmf/overview.md
> Added Windows Server 2019 to the matrix

- dsc/tutorials/DSCAutomationHostEnabled.md
- dsc/tutorials/bootstrapDsc.md
> Closes #3620 - add registry key information

- reference/3.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/4.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/5.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/5.1/Microsoft.PowerShell.Management/Get-Content.md
- reference/6/Microsoft.PowerShell.Management/Get-Content.md
Related to Issue #2000 
Updated Encoding parameter and YAML for Get-Content
Style updates
Paragraph reflows
Fixed links
Acrolinx score: 93
> Updated Encoding parameter and YAML for Get-Content

- dsc/pull-server/pullServer.md
Also noticed that Import-DSCResource -ModuleName PSDesiredStateConfiguration was missing as well, which streamlines the configuration file and reduces warnings to configuration folks. Thanks!
> Update pullServer.md to also include modules

- developer/cmdlet/parameter-attribute-declaration.md
> Remove Duplicate "Remarks" Point

- reference/3.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/6/PowerShellGet/Publish-Script.md
> fix #3647 - clarify positional parameters 

- reference/5.0/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/6/Microsoft.PowerShell.Utility/Format-Hex.md
> Fixed broken link for about_Quoting_Rules

- reference/docs-conceptual/install/Installing-Windows-PowerShell.md
> Installing-Windows-PowerShell.md: grammar

- reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md
You can use legacy constrained delegation (not resource-based) to make the second hop, by configuring Kerberos Constrained delegation, with option “Use any authentication protocol” to allow Protocol Transition.
Ref.case 119011419545284
> Clarifications about KCD

- reference/6/Microsoft.PowerShell.Utility/Add-Member.md
> Grammar fix

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> Clarify 18.10 community support

- reference/3.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Parameters.md
> Fix #3582 - add colon syntax

- reference/5.0/Microsoft.PowerShell.Archive/Compress-Archive.md
- reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md
- reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md
> fix #3680 - update output information

- reference/3.0/Microsoft.PowerShell.Core/Export-ModuleMember.md
- reference/4.0/Microsoft.PowerShell.Core/Export-ModuleMember.md
- reference/5.0/Microsoft.PowerShell.Core/Export-ModuleMember.md
- reference/5.1/Microsoft.PowerShell.Core/Export-ModuleMember.md
- reference/6/Microsoft.PowerShell.Core/Export-ModuleMember.md
Close https://github.com/PowerShell/PowerShell/issues/8883.
> Fix typo Get-Test -> New-Test.

- build.ps1
Improve logging of the build script.
@adityapatwardhan Please review
> Move logging to catch block rather than end of script

- reference/5.0/CimCmdlets/CimCmdlets.md
- reference/5.1/CimCmdlets/CimCmdlets.md
Fixed download links for CimCmdlets module for v5.0/5.1
> fix CIM help links

- reference/3.0/Microsoft.PowerShell.Core/About/About.md
- reference/3.0/Microsoft.PowerShell.Security/Get-Credential.md
- reference/3.0/PSWorkflowUtility/Invoke-AsWorkflow.md
- reference/4.0/Microsoft.PowerShell.Core/About/About.md
- reference/4.0/Microsoft.PowerShell.Security/Get-Credential.md
- reference/4.0/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md
- reference/4.0/PSWorkflowUtility/Invoke-AsWorkflow.md
- reference/5.0/Microsoft.PowerShell.Core/About/About.md
- reference/5.0/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.md
- reference/5.0/Microsoft.PowerShell.Security/Get-Credential.md
- reference/5.0/PSScheduledJob/Register-ScheduledJob.md
- reference/5.0/PSScheduledJob/Set-ScheduledJob.md
- reference/5.0/PSWorkflowUtility/Invoke-AsWorkflow.md
- reference/5.1/Microsoft.PowerShell.Core/About/About.md
- reference/5.1/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.md
- reference/5.1/Microsoft.PowerShell.Security/Get-Credential.md
- reference/5.1/PSScheduledJob/Register-ScheduledJob.md
- reference/5.1/PSScheduledJob/Set-ScheduledJob.md
- reference/5.1/PSWorkflowUtility/Invoke-AsWorkflow.md
- reference/6/Microsoft.PowerShell.Core/About/About.md
- reference/6/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.md
- reference/6/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/6/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md
- reference/6/Microsoft.PowerShell.Core/Start-Job.md
- reference/6/Microsoft.PowerShell.Security/Get-Credential.md
Part 2 - adding more missing placeholder
> adding missing placeholder text for #3741

- reference/3.0/Microsoft.PowerShell.Utility/Get-Random.md
- reference/4.0/Microsoft.PowerShell.Utility/Get-Random.md
- reference/5.0/Microsoft.PowerShell.Utility/Get-Random.md
- reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md
- reference/6/Microsoft.PowerShell.Utility/Get-Random.md
> Fix #3699 remove improper notes about 64-bit computers

- reference/3.0/Microsoft.PowerShell.Utility/Set-Alias.md
- reference/4.0/Microsoft.PowerShell.Utility/Set-Alias.md
- reference/5.0/Microsoft.PowerShell.Utility/Set-Alias.md
- reference/5.1/Microsoft.PowerShell.Utility/Set-Alias.md
- reference/6/Microsoft.PowerShell.Utility/Set-Alias.md
Original version: 85
Closes #3619
Copyedits, style changes.
> Closes #3619, copyedits, style changes

- developer/cmdlet/how-to-write-a-simple-cmdlet.md
Fixes #3785 typo in comment.
Style format.
> Fixes #3785, typo in comment

- developer/cmdlet/validating-parameter-input.md
* Remove redundant descriptions "For more information, ..."
* Fix formatting
> Update "Validating Parameter Input"

- reference/3.0/Microsoft.PowerShell.Core/About/about_For.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_For.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_For.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_For.md
- reference/6/Microsoft.PowerShell.Core/About/about_For.md
> Fixes #3708 - add multiple assignment and format documents

- reference/docs-conceptual/install/Installing-Windows-PowerShell.md
The link for /powershell/azure/install-azurerm-ps?view=azps-1.4.0 no longer works after the move to Az. Updated link to reflect new address /powershell/azure/install-azurerm-ps
- [] Impacts 6.next document
- [x ] Impacts 6 document
- [x ] Impacts 4.0 document
- [x ] Impacts 3.0 document
- [x ] This issue only shows up in version (list version(s) here) of the document
> Update download link for Azure Powershell Scripts

- dsc/pull-server/pullServer.md
> Fixes #3793 - update supported versions, and reformat

- reference/5.0/PackageManagement/Install-Package.md
> Fix #3817 - incorrect parameter name

- reference/docs-conceptual/whats-new/breaking-changes-ps6.md
> Fix #3816 - add note about *-EventLog cmdlets

- jea/role-capabilities.md
- Visbible -> Visible
- becuase -> because
- malicous -> malicious
- permisisons -> permissisons
> fix: jea/role-capabilities.md

- gallery/concepts/publishing-guidelines.md
- enviroment -> environment
- intepretation -> interpretation
> fix: gallery/concepts/publishing-guidelines.md

- dsc/tutorials/bootstrapDsc.md
> typo: intial -> initial

- dsc/reference/resources/windows/waitForAnyResource.md
- dsc/reference/resources/windows/waitForSomeResource.md
> typo: WaitForSome, WaitForAny

- reference/5.0/PackageManagement/Find-Package.md
- reference/5.0/PackageManagement/Get-Package.md
- reference/5.0/PowershellGet/Find-Module.md
- reference/5.0/PowershellGet/Install-Module.md
- reference/5.1/PackageManagement/Install-Package.md
- reference/5.1/PowershellGet/Find-Module.md
- reference/5.1/PowershellGet/Install-Module.md
- reference/6/PackageManagement/Install-Package.md
- reference/6/PowerShellGet/Find-Module.md
- reference/6/PowerShellGet/Install-Module.md
Find-Module Acrolinx scores:
Original: 91
Updated: 96
Closes #3878
Find-Module - Copyedits, paragraph reflows, style changes
Fixes review comments from PR #3822
Fixes a typo in Install-Module
Removed placeholders: 
5.0\PackageManagement\Find-Package.md
5.0\PackageManagement\Get-Package.md
5.1\PackageManagement\Install-Package.md
6\PackageManagement\Install-Package.md
> Closes #3878, Copyedits and fixed placeholders

- reference/3.0/Microsoft.PowerShell.Utility/Get-Unique.md
- reference/4.0/Microsoft.PowerShell.Utility/Get-Unique.md
- reference/5.0/Microsoft.PowerShell.Utility/Get-Unique.md
- reference/5.1/Microsoft.PowerShell.Utility/Get-Unique.md
- reference/6/Microsoft.PowerShell.Utility/Get-Unique.md
> Fix #3879 - fix formatting issues

- developer/format/label-element-for-tablecolumnheader-for-tablecontrol-format.md
- developer/format/width-element-for-tablecolumnheader-for-tablecontrol-format.md
- developer/format/wrap-element-for-tablerowentry-for-tablecontrl-format.md
- Tabl -> Table
- Tble -> Table
> typo: Tabble -> Table

- developer/cmdlet/cmdlet-sets.md
> typo: chracters -> characters

- reference/3.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md
- wmf/5.0/psget_modulecmdlets.md
- Multiple spaces after hash on atx style heading
- List indenting
- Convert NOTE
- Use list for Related Links
> fix: MD019/no-multiple-space-atx

- reference/3.0/Microsoft.PowerShell.Utility/Start-Sleep.md
- reference/4.0/Microsoft.PowerShell.Utility/Start-Sleep.md
- reference/5.0/Microsoft.PowerShell.Utility/Start-Sleep.md
- reference/5.1/Microsoft.PowerShell.Utility/Start-Sleep.md
- reference/6/Microsoft.PowerShell.Utility/Start-Sleep.md
> Fixes #3757 - Add Ctrl+C note

- reference/docs-conceptual/components/web-access/install-and-use-windows-powershell-web-access.md
- Toolsfor -> Tools for
- Capitalization of "Manager" in bookmark causing openbuild warning
> fix: reference/docs-conceptual/components/web-access/install-and-use-windows-powershell-web-access.md

- reference/docs-conceptual/whats-new/What-s-New-in-Windows-PowerShell-50.md
- Header joined with paragram
- Spacing around headers
> fix: improvements-to-existing-core-cmdlets-and-providers

- .openpublishing.redirection.json
- developer/TOC.yml
- developer/format/creating-a-table-view.md
- developer/format/format-schema-xml-reference.md
- developer/format/tablecolumnheader-element-format.md
- developer/format/tablerowentry-element-for-tablerowentroes-for-tablecontrol-format.md
- developer/format/wrap-element-for-tablerowentry-for-tablecontrol-format.md
> typo: Contrl -> Control

- developer/format/typename-element-for-types-format.md
Looks like a string pasted in another
> typo: Defining Sets of Object inserted

- developer/hosting/remoterunspace01-sample.md
- Opertation -> Operation
- Connaction -> Connection
- Remove empty See also
> fix: developer/hosting/remoterunspace01-sample.md

- developer/webservices/public-resource-schema.md
- publc -> public
- hshows -> shows
- Assocation -> Association
> fix: developer/webservices/public-resource-schema.md

- developer/cmdlet/stopprocesssample03-sample.md
- Acess -> Access
- parametr -> parameter
> fix: developer/cmdlet/stopprocesssample03-sample.md

- developer/hosting/runspace11-sample.md
- inital -> initial
- Languge -> Language
> fix: developer/hosting/runspace11-sample.md

- developer/hosting/windows-powershell-host-quickstart.md
- ruspace -> runspace
- Mirosoft -> Microsoft
> fix: developer/hosting/windows-powershell-host-quickstart.md

- developer/module/installing-a-powershell-module.md
- Technolgies -> Technologies
- Miminum -> Minimum
> fix: developer/module/installing-a-powershell-module.md

- developer/cmdlet/getprocesssample05-sample.md
- developer/prog-guide/getproc05-vb-net-sample-code.md
- whehter -> whether
- identofier -> identifier
> typo: serach -> search

- developer/scheduling-jobs-with-the-windows-powershell-api.md
- requiried -> required
- Sheduled -> Scheduled
- Invication -> Invocation
- manully -> manually
- Adpater -> Adapter
- Triggerobject -> Trigger object
> fix: developer/scheduling-jobs-with-the-windows-powershell-api.md

- developer/webservices/deploying-a-management-odata-web-service.md
- requred -> required
- retrive -> retrieve
- paramater -> parameter
- Indent sample code
> fix: developer/webservices/deploying-a-management-odata-web-service.md

- developer/workflow/scheduling-jobs-with-the-windows-powershell-api.md
- Adpater -> Adapter
- Trim trailing space
> fix: developer/workflow/scheduling-jobs-with-the-windows-powershell-api.md

- developer/cmdlet/stopprocesssample04-sample.md
- reference/3.0/CimCmdlets/New-CimSession.md
- reference/4.0/CimCmdlets/New-CimSession.md
- reference/5.0/CimCmdlets/New-CimSession.md
- reference/5.1/CimCmdlets/New-CimSession.md
This might a product bug rather than typo
> bug?: prameter -> parameter

- developer/webservices/implementing-custom-authorization-for-a-management-odata-web-service.md
- llustration -> illustration
- Customauthorization.Authorizeuser* -> CustomAuthorization.AuthorizeUser
- Customauthorization.Getmembershipid* -> CustomAuthorization.GetMembershipId
- Customauthorization -> CustomAuthorization
- managemnet -> management
- configuratin -> configuration
- instace -> instance
> fix: developer/webservices/implementing-custom-authorization-for-a-management-odata-web-service.md

- developer/cmdlet/creating-a-cmdlet-to-access-a-data-store.md
- consistancy -> consistency
- perfored -> performed
- represens -> represents
- notmatch -> not match
- explude -> exclude
- Specifiy -> Specify
- thedefault -> the default
> fix: developer/cmdlet/creating-a-cmdlet-to-access-a-data-store.md

- developer/hosting/host03-sample.md
- Remve -> Remove
- runtimw -> runtime
> fix: developer/hosting/host03-sample.md

- developer/hosting/host06-sample.md
- enetered -> entered
- Seperator -> Separator
> fix: developer/hosting/host06-sample.md

- developer/help/autogenerated-elements-of-comment-based-help.md
> Fix headers: "Autogenerated Elements of Comment-Based Help"

- reference/3.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/4.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/5.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/6/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
> Reformatting examples for readability and flow

- developer/prog-guide/how-to-create-a-windows-powershell-provider.md
The command should be **PS>get-help about_providers**
> Modify get-help code line

- reference/docs-conceptual/whats-new/breaking-changes-ps6.md
> Fixes #4028 - add *-computer cmdlets to breaking changes

- gallery/concepts/publishing-guidelines.md
A short description with the tagging recommendations of the new OS Filters and GitHub shields.
> PS Gallery- Adds mention of New OS Filters

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
> Document support patch timeline

- reference/3.0/Microsoft.PowerShell.Core/Out-Host.md
- reference/4.0/Microsoft.PowerShell.Core/Out-Host.md
- reference/5.0/Microsoft.PowerShell.Core/Out-Host.md
- reference/5.1/Microsoft.PowerShell.Core/Out-Host.md
- reference/6/Microsoft.PowerShell.Core/Out-Host.md
- reference/docs-conceptual/learn/Understanding-the-PowerShell-Pipeline.md
> Fix #3963 - note Paging is not supported by ISE

- reference/3.0/Microsoft.PowerShell.Management/Get-EventLog.md
- reference/4.0/Microsoft.PowerShell.Management/Get-EventLog.md
- reference/5.0/Microsoft.PowerShell.Management/Get-EventLog.md
- reference/5.1/Microsoft.PowerShell.Management/Get-EventLog.md
Original version: 94
Updated version: 94
> Fixes #4018, Fixes #4019. Updated Description and ComputerName parameter for Get-EventLog.

- dsc/pull-server/pullServer.md
> Grammar Change

- reference/6/Microsoft.PowerShell.Core/Disable-PSSessionConfiguration.md
- reference/6/Microsoft.PowerShell.Core/Enable-PSSessionConfiguration.md
- reference/6/Microsoft.PowerShell.Core/Get-PSSessionConfiguration.md
- reference/6/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/6/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md
- reference/6/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md
- reference/6/Microsoft.PowerShell.Core/Test-PSSessionConfigurationFile.md
- reference/6/Microsoft.PowerShell.Core/Unregister-PSSessionConfiguration.md
First pass at fixing the *-PSSessionConfiguration* documents. Starting with v6. Once this is merged I will copy changes to other versions.
> editorial and formatting fixes

- reference/6/Microsoft.PowerShell.Core/Start-Job.md
Partially fix #4003 for the change in PowerShell/PowerShell#9128
The change in the other issue is not included in 6.2.0 release, so will not be committed to this branch.
> Update the doc for Start-Job

- reference/6/Microsoft.PowerShell.Core/About/about_CommonParameters.md
> Update DebugPreference description and style changes

- reference/6/Microsoft.PowerShell.Core/Disable-PSRemoting.md
> Update Disable-PSRemoting cmdlet document for PSCore6

- reference/3.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md
Fixes #3906 code sample, copyedits, style
about_Wildcards Acrolinx scores
Updated version: 90
> Fixes #3906 code sample, copyedits, style

- reference/4.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
Fixes missed code change in #4085
> Fixing code sample

- reference/3.0/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
- reference/6/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
> Fix #4088 - fix example and styles

- reference/3.0/Microsoft.PowerShell.Core/About/About.md
- reference/4.0/Microsoft.PowerShell.Core/About/About.md
- reference/5.0/Microsoft.PowerShell.Core/About/About.md
- reference/5.1/Microsoft.PowerShell.Core/About/About.md
- reference/6/Microsoft.PowerShell.Core/About/About.md
> remove blank lines from About.md

- dsc/reference/resources/windows/scriptResource.md
> invalid character in examples

- reference/3.0/Microsoft.PowerShell.Utility/Write-Debug.md
- reference/4.0/Microsoft.PowerShell.Utility/Write-Debug.md
- reference/5.0/Microsoft.PowerShell.Utility/Write-Debug.md
- reference/5.1/Microsoft.PowerShell.Utility/Write-Debug.md
- reference/6/Microsoft.PowerShell.Utility/Write-Debug.md
> Fix #4093 - explain how -Debug changes preference variable

- reference/3.0/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Variables.md
> Fix #3907 - added missing hyperlinks

- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md
> Fix #4121 - add breaking change

- dsc/configurations/write-compile-apply-configuration.md
> Small typo

- reference/docs-conceptual/samples/Creating-a-Graphical-Date-Picker.md
* Refactoring by using `New-Object -Property`
* "CenterScreen" -> CenterScreen enum
* StartingPosition -> StartPosition
> Update sample: Graphical Date Picker

- reference/6/Microsoft.PowerShell.Utility/Sort-Object.md
Update Sort-Object docs for new -Stable parameter.
> Fix #3246 - document Stable sorts

- reference/6/Microsoft.PowerShell.Utility/Select-Object.md
> Fixed small space typo

- reference/6/Microsoft.PowerShell.Utility/Start-Sleep.md
> Fix #4144 - seconds is now [double]

- reference/7/Microsoft.PowerShell.Core/About/about_numeric_literals.md
@vexx32 Please review my changes. I welcome all feedback.
> Fix #4143 - add binary and bigint formats

- developer/cmdlet/adding-non-terminating-error-reporting-to-your-cmdlet.md
Heading, line breaks, typo, links, etc.
> Update "Adding Non-Terminating Error"

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions.md
> Fix #4168 - clarify $input

- reference/3.0/Microsoft.PowerShell.Management/Start-Service.md
- reference/4.0/Microsoft.PowerShell.Management/Start-Service.md
- reference/5.0/Microsoft.PowerShell.Management/Start-Service.md
- reference/5.1/Microsoft.PowerShell.Management/Start-Service.md
- reference/6/Microsoft.PowerShell.Management/Start-Service.md
> Fix #4176 - example 4 format errors

- reference/7/Microsoft.PowerShell.Core/About/about_numeric_literals.md
I noticed a couple small issues as I was skimming through this again, bit of contradiction here and there because of the changes between versions, and one or two tidbits that could be added for completeness.
> Update numeric literals documentation

- reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md
- reference/4.0/Microsoft.PowerShell.Management/Get-ChildItem.md
- reference/5.0/Microsoft.PowerShell.Management/Get-ChildItem.md
- reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
- reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md
> Fix #4163 - add link to mode attributes

- .openpublishing.publish.config.json
> Remove specified package version after bug fix

- reference/3.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/3.0/Microsoft.PowerShell.Utility/Export-PSSession.md
- reference/3.0/Microsoft.PowerShell.Utility/Import-Clixml.md
- reference/4.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/4.0/Microsoft.PowerShell.Utility/Export-PSSession.md
- reference/4.0/Microsoft.PowerShell.Utility/Import-Clixml.md
- reference/5.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/5.0/Microsoft.PowerShell.Utility/Export-PSSession.md
- reference/5.0/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/5.0/Microsoft.PowerShell.Utility/Import-Clixml.md
- reference/5.1/Microsoft.PowerShell.Management/Get-Content.md
- reference/5.1/Microsoft.PowerShell.Utility/Export-PSSession.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/5.1/Microsoft.PowerShell.Utility/Import-Clixml.md
This updates the encoding information per issue #4155. The changes are broken into 4 PRs for easier review.
> fix encoding - part 2

- reference/3.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/3.0/Microsoft.PowerShell.Management/New-Item.md
- reference/3.0/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/4.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/4.0/Microsoft.PowerShell.Management/New-Item.md
- reference/4.0/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/5.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/5.0/Microsoft.PowerShell.Management/New-Item.md
- reference/5.0/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/5.0/Microsoft.PowerShell.Utility/import-powershelldatafile.md
- reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/5.1/Microsoft.PowerShell.Management/New-Item.md
- reference/5.1/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/5.1/Microsoft.PowerShell.Utility/Import-PowerShellDataFile.md
This updates the encoding information per issue #4155. The changes are broken into 4 PRs for easier review.
> fix encoding - part 3

- reference/3.0/Microsoft.PowerShell.Management/Set-Content.md
- reference/3.0/Microsoft.PowerShell.Utility/Out-File.md
- reference/3.0/Microsoft.PowerShell.Utility/Select-String.md
- reference/3.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/4.0/Microsoft.PowerShell.Management/Set-Content.md
- reference/4.0/Microsoft.PowerShell.Utility/Out-File.md
- reference/4.0/Microsoft.PowerShell.Utility/Select-String.md
- reference/4.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/5.0/Microsoft.PowerShell.Management/Set-Content.md
- reference/5.0/Microsoft.PowerShell.Utility/Out-File.md
- reference/5.0/Microsoft.PowerShell.Utility/Select-String.md
- reference/5.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/5.1/Microsoft.PowerShell.Management/Set-Content.md
- reference/5.1/Microsoft.PowerShell.Utility/Out-File.md
- reference/5.1/Microsoft.PowerShell.Utility/Select-String.md
- reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
This updates the encoding information per issue #4155. The changes are broken into 4 PRs for easier review.
Fixes #4155
> Fixes #4155 - fix encoding - part 4

- reference/3.0/Microsoft.PowerShell.Core/About/about_Data_Sections.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Data_Sections.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Data_Sections.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Data_Sections.md
- reference/6/Microsoft.PowerShell.Core/About/about_Data_Sections.md
> Fix #648 - update syntax

- reference/6/Microsoft.PowerShell.Management/Add-Content.md
- reference/6/Microsoft.PowerShell.Management/Get-Content.md
- reference/6/Microsoft.PowerShell.Management/Set-Content.md
- reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/6/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/6/Microsoft.PowerShell.Utility/Export-PSSession.md
- reference/6/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/6/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/6/Microsoft.PowerShell.Utility/Out-File.md
- reference/6/Microsoft.PowerShell.Utility/Select-String.md
- reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
> Fix #4191, Fix #4192 - Update accepted values on -Encoding

- reference/3.0/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md
- reference/4.0/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md
- reference/5.0/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md
- reference/5.1/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md
- reference/6/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md
> Fix #4213 - fix typo and style clean up

- reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md
- reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md
> Fix #813 - Add ListEntry to ListControl

- reference/5.0/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/6/Microsoft.PowerShell.Utility/Format-Hex.md
> Fix #2955, Fix #1940 - update Format-Hex

- ci.yml
- daily.yml
> Fix triggers for CI

- developer/hosting/windows-powershell-host-quickstart.md
Fixed links, line breaks, etc.
> Update "Host Quickstart"

- reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
> Fix #4224 - default encoding to ASCII

- reference/3.0/Microsoft.PowerShell.Utility/Add-Member.md
- reference/4.0/Microsoft.PowerShell.Utility/Add-Member.md
- reference/5.0/Microsoft.PowerShell.Utility/Add-Member.md
- reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md
- reference/6/Microsoft.PowerShell.Utility/Add-Member.md
> Fixes #4220 - Fix Example 6 (Copy Property)

- reference/3.0/Microsoft.PowerShell.Utility/Group-Object.md
- reference/4.0/Microsoft.PowerShell.Utility/Group-Object.md
- reference/5.0/Microsoft.PowerShell.Utility/Group-Object.md
- reference/5.1/Microsoft.PowerShell.Utility/Group-Object.md
- reference/6/Microsoft.PowerShell.Utility/Group-Object.md
> Updating Group-Object cmdlet

- reference/3.0/Microsoft.PowerShell.Core/Out-Default.md
- reference/4.0/Microsoft.PowerShell.Core/Out-Default.md
- reference/5.0/Microsoft.PowerShell.Core/Out-Default.md
- reference/5.1/Microsoft.PowerShell.Core/Out-Default.md
- reference/6/Microsoft.PowerShell.Core/Out-Default.md
> Fix #3673 - explain Out-Default

- reference/3.0/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
- reference/4.0/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
- reference/5.0/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
- reference/5.1/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
- reference/6/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
> Fix #4231 - Correct digit and other markdown cleanup

- developer/format/scriptblock-element-for-groupby-format.md
* Fix the broken link "PropertyName"
> Update "ScriptBlock Element for GroupBy"

- jea/role-capabilities.md
> Document workaround for tab function completion

- dsc/resources/get-test-set.md
Indicate what LCM is an abbreviation for before starting to use the abbreviation
> Indicate what LCM is an abbreviation

- reference/6/Microsoft.PowerShell.Management/Remove-Service.md
> Fix #4262 - remove service

- reference/3.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
> Fix #4268 - add note about hyphen

- developer/hosting/writing-a-windows-powershell-host-application.md
Fix incomplete sentence in `writing-a-windows-powershell-host-application.md`.
> Fix incomplete sentence

- reference/3.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/6/Microsoft.PowerShell.Core/About/about_Continue.md
> Fixes #3709 - rewrite about_Continue for clarity

- .openpublishing.publish.config.json
> Disable incremental build temporary for powershell reference build issue

- reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/3.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
> Add note about javascript might run

- reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md
> Fixed broken md around url

- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/6/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
> Fixes #3604, Fixes #3603 - Document ArgumentCompleter

- reference/7/Microsoft.PowerShell.Core/About/about_pwsh.md
Do not merge until https://github.com/PowerShell/PowerShell/pull/9528 gets merged
> add -l for pwsh

- reference/5.0/PackageManagement/Get-Package.md
- reference/5.1/PackageManagement/Get-Package.md
- reference/6/PackageManagement/Get-Package.md
> Get-Package - copyedits, updated placeholders, and style

- reference/6/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
> Irmprove wording, fix example that returns ServiceController

- reference/5.0/PowershellGet/Get-InstalledModule.md
- reference/5.1/PowershellGet/Get-InstalledModule.md
- reference/6/PowerShellGet/Get-InstalledModule.md
>  Fix #4348 - diff from Get-Module

- reference/3.0/Microsoft.PowerShell.Utility/Get-Variable.md
- reference/4.0/Microsoft.PowerShell.Utility/Get-Variable.md
- reference/5.0/Microsoft.PowerShell.Utility/Get-Variable.md
- reference/5.1/Microsoft.PowerShell.Utility/Get-Variable.md
- reference/6/Microsoft.PowerShell.Utility/Get-Variable.md
> Fixes #3525 - Clarifies Get-Variable return values

- wmf/whats-new/class-overview.md
Fixed spelling, minor style and paragraph reflows.
> Fixes #4346 - Spelling correction

- reference/3.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_CommonParameters.md
> fixes #4337 Clarify description of Out-Variable

- reference/6/Microsoft.PowerShell.Utility/Join-String.md
> Fixing spelling typo

- reference/3.0/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/6/Microsoft.PowerShell.Core/About/about_Switch.md
> Fixes #3512 Clarify switch script block conditions

- reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md
> Fixes #3456 Update powershell 6 to NewtonSoftJson note

- reference/3.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_CommonParameters.md
> Fixes #3782 - Clarify outbuffer description

- reference/3.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/4.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/5.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/5.1/Microsoft.PowerShell.Management/Get-Content.md
- reference/6/Microsoft.PowerShell.Management/Get-Content.md
> Fixes #3213 Add byte stream example

- reference/3.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
> Fixes #3788 Added exception example for Invoke-WebRequest

- reference/3.0/Microsoft.PowerShell.Core/About/about_Alias_Provider.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Function_Provider.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Alias_Provider.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Function_Provider.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Alias_Provider.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Function_Provider.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Alias_Provider.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Function_Provider.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Alias_Provider.md
- reference/6/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/6/Microsoft.PowerShell.Core/About/about_Function_Provider.md
- reference/6/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/6/Microsoft.PowerShell.Core/About/about_Variables.md
> fixes #3343 address content provider syntax

- developer/module/how-to-write-a-powershell-script-module.md
Minor style edits and fixed backticks.
> fix #4389 - fix backticks in code sample

- developer/module/how-to-write-a-powershell-script-module.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/6/Microsoft.PowerShell.Core/About/about_Object_Creation.md
> Fixes #3209, Fixes #3210 rewrite about_Object_creation

- reference/docs-conceptual/samples/Working-with-Software-Installations.md
Added warning, style edits, and updated example to use CimCmdlets.
> Fix #4388 - add warning about win32_product

- reference/6/Microsoft.PowerShell.Core/About/about_Split.md
Documentation for feature (https://github.com/PowerShell/PowerShell/pull/8960).
> Feature docs for reverse -split operation

- reference/6/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
> "C" in CSV is "Character"

- .openpublishing.publish.config.json
> Enable incremental build

- reference/3.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
> Fix #3721 - change -matches to -match

- developer/prog-guide/windows-powershell-concepts.md
Fixes #4408 
- Fixed broken links
- Changed link text
> Fixes #4408 - Fixed broken links and changed link text

- reference/7/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/7/Microsoft.PowerShell.Core/Get-Command.md
Dependent on https://github.com/PowerShell/PowerShell/pull/9872 being merged
> add TEMP: drive and -UseAbbreviationExpansion

- reference/3.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/4.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/5.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Table.md
- reference/6/Microsoft.PowerShell.Utility/Format-Table.md
> Copy changes from #4435 to other versions

- developer/cmdlet/writing-a-windows-powershell-cmdlet.md
Fixes [AB#1556587](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1556587)
> Fix #4438 - fix obsolete link

- reference/3.0/Microsoft.PowerShell.Core/About/about_For.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_For.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_For.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_For.md
- reference/6/Microsoft.PowerShell.Core/About/about_For.md
> Fixes #4441 - Change operator in for loop

- reference/3.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md
- reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md
Fixes [AB#1557200](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1557200)
> Fix #4444 - table formatting and other cleanup

- developer/hosting/creating-an-initialsessionstate.md
* Remove namespace for readability
* Links, indentation, some minor wording changes
> Update "Creating an InitialSessionState"

- reference/docs-conceptual/learn/more-powershell-learning.md
Updated links to blogs and MVA content.
Fixes [AB#1557953](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1557953)
> Fix #4452 - update links

- reference/6/Microsoft.PowerShell.Core/About/about_pwsh.md
- reference/7/Microsoft.PowerShell.Core/About/about_pwsh.md
> fix pwsh parameters

- reference/3.0/Microsoft.PowerShell.Diagnostics/Get-Counter.md
- reference/4.0/Microsoft.PowerShell.Diagnostics/Get-Counter.md
- reference/5.0/Microsoft.PowerShell.Diagnostics/Get-Counter.md
- reference/5.1/Microsoft.PowerShell.Diagnostics/Get-Counter.md
Get-Counter Acrolinx scores
- Fixes #4430
- Fixed parameter descriptions for MaxSamples and SampleInterval
- Rewrote all the examples and restructured all the content
- Copyedits, style, links
- Fixes [AB#1555485](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1555485)
> Fixes #4430, rewrote examples and parameters

- reference/5.0/Microsoft.PowerShell.Management/Clear-RecycleBin.md
- reference/5.1/Microsoft.PowerShell.Management/Clear-RecycleBin.md
Clear-RecycleBin Acrolinx scores
- Fixes [AB#1557963](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1557963)
- Fixes #4451 - Incomplete sentence
> Fixes #4451 - Incomplete sentence

- reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
- reference/7/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
Fix [AB#1562985](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1562985)
> continuation of #4482 and style edits

- reference/6/Microsoft.PowerShell.Utility/Get-Uptime.md
- reference/7/Microsoft.PowerShell.Utility/Get-Uptime.md
Fixes [AB#1564043](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1564043)
> Fixes #4487 - add docs for Get-Uptime

- reference/3.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/4.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/5.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/7/Microsoft.PowerShell.Utility/Send-MailMessage.md
Send-MailMessage.md Acrolinx scores
- Fixes [AB#1562853](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1562853)
- Fixes #4485
- Fixed ParameterSet spacing
- Added powershell tag to code samples
- PS 7 doc - changed Subject to required based on ParameterSet
> Fixes #4485, Minor content changes

- reference/5.0/PowershellGet/Publish-Module.md
- reference/5.1/PowershellGet/Publish-Module.md
- reference/6/PowerShellGet/Publish-Module.md
- Fixes [AB#1564524](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1564524)
- Related to #3740
- Added content to empty parameters
- Style, paragraph reflows
> Publish-Module - Fixed empty parameters, style

- reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/6/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/7/Microsoft.PowerShell.Core/About/about_Requires.md
Fixes [AB#1565413](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1565413)
> Fix #4508 - update docs for -ShellId

- dsc/configurations/crossNodeDependencies.md
- dsc/reference/resources/windows/waitForAllResource.md
- dsc/reference/resources/windows/waitForAnyResource.md
- dsc/reference/resources/windows/waitForSomeResource.md
> adding Winrm update to waitforxx resources

- reference/7/PowerShellGet/Update-Module.md
> Fixes #4529 - added Scope parameter to PS7 Update-Module

- reference/6/ThreadJob/Start-ThreadJob.md
- reference/6/ThreadJob/ThreadJob.md
- reference/7/ThreadJob/Start-ThreadJob.md
- reference/7/ThreadJob/ThreadJob.md
- reference/README.md
Fixes #4521
Fixes [AB#1568582](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1568582)
> Fixes #4521 - add missing ThreadJob module

- reference/6/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/7/Microsoft.PowerShell.Utility/Import-Csv.md
- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
Fixes [AB#1569539](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1569539)
Fixes #3112
> Fixes #3112 - add support for W3C ELF

- reference/docs-conceptual/whats-new/breaking-changes-ps6.md
Fixes #3069
Fixes [AB#1570157](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1570157)
> Fix #3069 - update breaking changes

- reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md
- reference/3.0/PSWorkflow/New-PSWorkflowExecutionOption.md
- reference/3.0/PSWorkflow/New-PSWorkflowSession.md
- reference/4.0/PSWorkflow/About/about_Foreach-Parallel.md
- reference/4.0/PSWorkflow/New-PSWorkflowExecutionOption.md
- reference/4.0/PSWorkflow/New-PSWorkflowSession.md
- reference/5.0/PSWorkflow/About/about_Foreach-Parallel.md
- reference/5.0/PSWorkflow/New-PSWorkflowExecutionOption.md
- reference/5.0/PSWorkflow/New-PSWorkflowSession.md
- reference/5.1/PSWorkflow/About/about_Foreach-Parallel.md
- reference/5.1/PSWorkflow/New-PSWorkflowExecutionOption.md
- reference/5.1/PSWorkflow/New-PSWorkflowSession.md
Fixes #4542 - fix broken link + style fixes
Fixes [AB#1569283](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1569283)
>  Fixes #4542 - fix broken link + style fixes

- reference/3.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/4.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/5.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/7/Microsoft.PowerShell.Core/New-ModuleManifest.md
New-ModuleManifest Acrolinx scores
Original version: 87
Updated version: 93
- Fixes [AB#1569560](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1569560)
- Fixes #3098
- Style, paragraph reflows, and minor copyedits
> Fixes #3098 - added encoding info to Notes section

- reference/5.1/PSDesiredStateConfiguration/Update-DscConfiguration.md
> simplify example

- reference/3.0/Microsoft.PowerShell.Management/Set-Service.md
- reference/4.0/Microsoft.PowerShell.Management/Set-Service.md
- reference/5.0/Microsoft.PowerShell.Management/Set-Service.md
- reference/5.1/Microsoft.PowerShell.Management/Set-Service.md
- reference/6/Microsoft.PowerShell.Management/Set-Service.md
- reference/7/Microsoft.PowerShell.Management/Set-Service.md
Set-Service Acrolinx scores
- Updated these versions similar to PR #4578
> Set-Service - Paragraph reflows, copyedits, style

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
- reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
- Fixes [AB#1573337](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1573337)
- Fixes #4576
- Removed the Ubuntu 14.04 section, links, and references
- Paragraph reflows, minor copyedits, style
Acrolinx score
SSH-Remoting-in-PowerShell-Core
- To resolve build errors, updated links and header in SSH-Remoting-in-PowerShell-Core to redirect to Ubuntu 1604 section in Installing-PowerShell-Core-on-Linux.
- Paragraph reflows in Overview and Authentication sections.
- Corrected a typo.
> Fixes #4576 - Removed the Ubuntu 14.04 section, links, and references

- reference/3.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/4.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/5.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/7/Microsoft.PowerShell.Core/New-ModuleManifest.md
- Fixes [AB#1574540](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1574540)
- Fixes #4584
- Copyedits
- Updated the Example 1 output for versions 5.1 and 6
> Fixes #4584 - Fixed New-ModuleManifest Example 3

- reference/3.0/Microsoft.PowerShell.Core/Remove-Job.md
- reference/4.0/Microsoft.PowerShell.Core/Remove-Job.md
- reference/5.0/Microsoft.PowerShell.Core/Remove-Job.md
- reference/5.1/Microsoft.PowerShell.Core/Remove-Job.md
- reference/6/Microsoft.PowerShell.Core/Remove-Job.md
- reference/7/Microsoft.PowerShell.Core/Remove-Job.md
Remove-Job Acrolinx scores
- Fixes [AB#1575601](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1575601)
- Fixes #3659
- Added content to the Notes section about job processes
> Fixes #3659 - Added content to the Notes section about job processes

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Installing PowerShell Core on Linux
PowerShell Core Support Lifecycle
- Fixes [AB#1578936](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1578936)
- Fixes #4599
- Added Ubuntu 19.04 section to the installation document
- Added Ubuntu 19.04 to the table in supported platforms of lifecycle document
- Paragraph reflows, minor copyedits
> Fixes #4599 - Ubuntu interim releases are community supported

- developer/cmdlet/required-development-guidelines.md
https://docs.microsoft.com/en-us/powershell/developer/cmdlet/required-development-guidelines
> Typo "|\|backslash|"→"|\\|backslash|"

- developer/cmdlet/cmdlet-dynamic-parameters.md
- developer/cmdlet/cmdlet-error-reporting.md
Cmdlet Dynamic Parameters
- Fixes [AB#1579208](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1579208)
- Fixes #4605
- Corrected case for IDynamicParameters and GetDynamicParameters
- Paragraph reflows, style, minor copyedits
- Acrolinx score: original 90, updated 93
Cmdlet Error Reporting
- Fixes [AB#1579209](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1579209)
- Fixes #4607
- Corrected case for ErrorCategory and ThrowTerminatingError
- Paragraph reflows, style, minor copyedits
- Acrolinx score: original 81, updated 85
> Fixes #4605, Fixes #4607 - Corrected case

- reference/5.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md
- reference/6/Microsoft.PowerShell.Core/Enable-PSRemoting.md
- reference/7/Microsoft.PowerShell.Core/Enable-PSRemoting.md
Fixes #4616 
Fixes [AB#1580732](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1580732) 
> Fix #4616 - update firewall rule name

- gallery/concepts/publishing-guidelines.md
- reference/6/PowerShellGet/Install-Module.md
- reference/7/Microsoft.PowerShell.Core/About/About.md
- reference/7/Microsoft.PowerShell.Core/About/about_Telemetry.help.md
- reference/7/Microsoft.PowerShell.Core/About/about_Telemetry.md
- reference/7/PowerShellGet/Install-Module.md
> Add Module Dependency Management Documentation

- reference/3.0/Microsoft.PowerShell.Core/Start-Job.md
- reference/4.0/Microsoft.PowerShell.Core/Start-Job.md
- reference/5.0/Microsoft.PowerShell.Core/Start-Job.md
- reference/5.1/Microsoft.PowerShell.Core/Start-Job.md
- reference/6/Microsoft.PowerShell.Core/Start-Job.md
- reference/7/Microsoft.PowerShell.Core/Start-Job.md
- Fixes [AB#1581473](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1581473)
- Fixes #4003 for v7
- All versions: copyedits, style, paragraph reflows
> Fixes #4003 - updated RunAs32 for v7 document

- reference/3.0/Microsoft.PowerShell.Management/Get-ComputerRestorePoint.md
- reference/4.0/Microsoft.PowerShell.Management/Get-ComputerRestorePoint.md
- reference/5.0/Microsoft.PowerShell.Management/Get-ComputerRestorePoint.md
- reference/5.1/Microsoft.PowerShell.Management/Get-ComputerRestorePoint.md
Original version: 93
- Fixes [AB#1583321](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1583321)
- Fixes #4632
- Updated the examples
> Fixes #4632 - Fixed the code sample in Example 5

- reference/7/Microsoft.PowerShell.Core/About/about_pwsh.md
> Add pwsh -Login to docs

- reference/4.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md
- reference/5.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md
- reference/5.1/PSDesiredStateConfiguration/Stop-DscConfiguration.md
- Fixes [AB#1585065](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1585065)
- Fixes #4643
> Fixes #4643 - Fixed broken link

- reference/3.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/7/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Fixes #4654 
Fixes [AB#1586348](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1586348)
> Fixes #4654 - removed ReportErrorShow* variables

- reference/3.0/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/6/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/7/Microsoft.PowerShell.Core/About/about_Trap.md
Fixes #4611 
Fixes [AB#1584825](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1584825)
> Fixes #4611 - explain the scope of traps

- reference/3.0/Microsoft.PowerShell.Utility/Get-Random.md
- reference/4.0/Microsoft.PowerShell.Utility/Get-Random.md
- reference/5.0/Microsoft.PowerShell.Utility/Get-Random.md
- reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md
- reference/6/Microsoft.PowerShell.Utility/Get-Random.md
- reference/7/Microsoft.PowerShell.Utility/Get-Random.md
Fixes #4515 
Fixes #4658
Fixes [AB#1586765](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1586765)
Fixes [AB#1586767](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1586767)
> Fixes #4515 Fixes #4658 - fix example and seed

- reference/3.0/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/4.0/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/5.0/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/5.1/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/6/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/7/Microsoft.PowerShell.Core/Set-PSDebug.md
- Fixes [AB#1586163](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1586163)
- Fixes #4653
- Style, paragraph reflows, copyedits
> Fixes #4653 - Debug features are Off by default

- reference/5.0/Microsoft.PowerShell.Utility/Debug-Runspace.md
- reference/5.1/Microsoft.PowerShell.Utility/Debug-Runspace.md
- reference/6/Microsoft.PowerShell.Utility/Debug-Runspace.md
- reference/6/Microsoft.PowerShell.Utility/Get-Random.md
- reference/7/Microsoft.PowerShell.Utility/Debug-Runspace.md
- reference/7/Microsoft.PowerShell.Utility/Get-Random.md
Fixes #4660 - fix formatting of example
Fixes [AB#1586860](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1586860)
Also, fixed example for Get-Random that was specific to v7 as a follow up to PR #4661
> Fixes #4660 - fix formatting of example

- reference/3.0/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/4.0/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/5.0/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/6/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/7/Microsoft.PowerShell.Core/Invoke-Command.md
Fixes #4548
Fixes [AB#1586997](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1586997)
> Fixes #4548 - fix comment on scope and style edits

- reference/3.0/Microsoft.WsMan.Management/Enable-WSManCredSSP.md
- reference/4.0/Microsoft.WsMan.Management/Enable-WSManCredSSP.md
- reference/5.0/Microsoft.WsMan.Management/Enable-WSManCredSSP.md
- reference/5.1/Microsoft.WsMan.Management/Enable-WSManCredSSP.md
- reference/6/Microsoft.WSMan.Management/Enable-WSManCredSSP.md
- reference/7/Microsoft.WSMan.Management/Enable-WSManCredSSP.md
Original version: 94
- Fixes [AB#1586164](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1586164)
- Fixes #4646
- Copyedits, paragraph reflows, style
> Fixes #4646 - DelegateComputer parameter accepts wildcards

- developer/cmdlet/extending-properties-for-objects.md
- developer/provider/provider-types.md
extending-properties-for-objects.md
- Fixes [AB#1586171](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1586171)
- Fixes #4633 - Changed property name to **Mode**, fixed broken links
---------
provider-types.md
- Fixes [AB#1586170](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1586170)
- Fixes #4649 - Fixed duplicate link and link text
- Removed redundant links
Original version: 97
> Fixes #4633, Fixes #4649 - Fixed a property name, fixed broken links

- reference/7/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
- reference/7/Microsoft.PowerShell.Utility/Export-Csv.md
Fixes #3900 
Fixes [AB#1588231](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1588231)
> Fixes #3900 - add new parameters to CSV cmdlets

- reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/7/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fixes #4674 - update URI to avoid redirection
Fixes [AB#1588496](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1588496)
Also fixed style and formatting issues.
> Fixes #4674 - update URI to avoid redirection

- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
- reference/7/Microsoft.PowerShell.Core/Get-Help.md
Original version: 87
- Fixes [AB#1588117](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1588117)
- Fixes #4672
- Fixed links
> Fixes #4672 - Updated Example 11

- reference/3.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/4.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/5.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/5.1/Microsoft.PowerShell.Management/Get-Content.md
- reference/6/Microsoft.PowerShell.Management/Get-Content.md
- reference/7/Microsoft.PowerShell.Management/Get-Content.md
- Fixes [AB#1588748](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1588748)
- Fixes #4681
- Fixed parameter set spacing
> Fixes #4681 - Fixed Example 4

- reference/3.0/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/3.0/Microsoft.PowerShell.Core/Set-StrictMode.md
- reference/4.0/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/4.0/Microsoft.PowerShell.Core/Set-StrictMode.md
- reference/5.0/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/5.0/Microsoft.PowerShell.Core/Set-StrictMode.md
- reference/5.1/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/5.1/Microsoft.PowerShell.Core/Set-StrictMode.md
- reference/6/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/6/Microsoft.PowerShell.Core/Set-StrictMode.md
- reference/7/Microsoft.PowerShell.Core/Set-PSDebug.md
- reference/7/Microsoft.PowerShell.Core/Set-StrictMode.md
Fixes #4609 - clarify scope of settings
Fixes [AB#1588768](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1588768)
> Fixes #4609 - clarify scope of settings

- developer/cmdlet/how-to-import-cmdlets-using-modules.md
- Fixes [AB#1590650](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1590650)
- Fixes #3670
- Copyedits, paragraph reflows, style
Updated version: 100
> Fixes #3670 - Added a step about the module manifest

- gallery/concepts/publishing-guidelines.md
- Fixes [AB#1591224](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1591224)
- Fixes #1899
- Paragraph reflows, style, minor copyedits
- Fixed links, added missing links
Original version: 76
Updated version: 86
> Fixes #1899 - Added content to section: Sign your code

- gallery/how-to/working-with-packages/manual-download.md
- Fixes [AB#1591103](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1591103)
- Fixes #4276
Updated version: 100
> Fixes #4276 - Added link to section that lists NuGet-specific elements

- developer/cmdlet/defining-default-methods-for-objects.md
- Fixes [AB#1591022](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1591022)
- Fixes #4634
- Correction in Code methods section: changed **ConvertLargeIntegerToInt64** to **ToString**
- Fixed link text
- Paragraph reflows, style
> Fixes #4634 - Corrected a method name

- reference/6/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
Change instances of `get-process` to `Get-Process`.
> Change casing in example

- reference/docs-conceptual/samples/Changing-Computer-State.md
Added CIM method for shutdown for users who do not use WMI
> Added Shutdown cmd with CIM method

- reference/4.0/Microsoft.PowerShell.Core/About/about_desiredstateconfiguration.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_desiredstateconfiguration.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_desiredstateconfiguration.md
Fixes #4732 - fix code formatting
Fixes [AB#1593346](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1593346)
> Fixes #4732 - fix code formatting

- reference/3.0/Microsoft.PowerShell.Security/Get-Credential.md
- reference/4.0/Microsoft.PowerShell.Security/Get-Credential.md
- reference/5.0/Microsoft.PowerShell.Security/Get-Credential.md
- reference/5.1/Microsoft.PowerShell.Security/Get-Credential.md
- reference/6/Microsoft.PowerShell.Security/Get-Credential.md
- reference/7/Microsoft.PowerShell.Security/Get-Credential.md
Fixes #4758
Fixes [AB#1595741](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1595741)
Corrects Example 4.
> Fixes #4758 - Remove that a backslash is added for local accounts

- gallery/docfx.json
Trying to fix inclusion of Gallery readme.md file.
> Fixing gallery readme inclusion

- wmf/setup/install-configure.md
- wmf/whats-new/release-notes.md
- Fixes [AB#1596068](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596068)
- Fixes #4466
- release-notes.md: Added note about WMF 3.0 on Server 2008 and Windows 7
- install-configure.md: Moved prerequisites section before install instructions for WMF 5.1 on Server 2008 and Windows 7
- Style, minor copyedits, paragraph reflows
> Fixes #4466 - Added note about WMF 3.0 on Server 2008 and Windows 7

- reference/6/Microsoft.PowerShell.Management/Add-Content.md
+ even smaller correction to example 1.
> Minor grammar rework of example 2.

- reference/3.0/Microsoft.PowerShell.Core/Start-Job.md
- reference/7/Microsoft.PowerShell.Core/Start-Job.md
> Add documentation for WorkingDirectory parameter of Start-Job

- reference/docs-conceptual/samples/Creating-Get-WinEvent-queries-with-FilterHashtable.md
Fixes #4689 - search for keyword in eventdata
Fixes [AB#1598508](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1598508)
> Fixes #4689 - search for keyword in eventdata

- developer/format/tablecolumnitem-element-for-tablecolumnitems-for-tablecontrol-format.md
Fixes #4362 
Fixes [AB#1598870](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1598870)
> Fixes #4362 - Add FormatString to XML syntax block example

- reference/3.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/4.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/5.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/6/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/7/Microsoft.PowerShell.Utility/Compare-Object.md
- Fixes [AB#1599724](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1599724)
- Fixes #4543
- Added an example with the ExcludeDifferent parameter
> Fixes #4543 - Updated the ExcludeDifferent description

- reference/5.1/Microsoft.PowerShell.Management/Set-TimeZone.md
- reference/6/Microsoft.PowerShell.Management/Set-TimeZone.md
- reference/7/Microsoft.PowerShell.Management/Set-TimeZone.md
Fixes #4803 - explain diff between Id and Name
Fixes [AB#1600699](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1600699)
> Fixes #4803 - explain diff between Id and Name

- gallery/installing-psget.md
- Fixes [AB#1600647](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1600647)
- Fixes #4801
> Fixes #4801 - Removed link to the PackageManagement MSI

- reference/6/Microsoft.PowerShell.Utility/Test-Json.md
- reference/7/Microsoft.PowerShell.Utility/Test-Json.md
Fixes #4809 - style cleanup
Fixes [AB#1601270](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1601270)
> Fixes #4809 - style cleanup

- reference/3.0/Microsoft.PowerShell.Core/Receive-Job.md
- reference/4.0/Microsoft.PowerShell.Core/Receive-Job.md
- reference/5.0/Microsoft.PowerShell.Core/Receive-Job.md
- reference/5.1/Microsoft.PowerShell.Core/Receive-Job.md
- reference/6/Microsoft.PowerShell.Core/Receive-Job.md
- reference/7/Microsoft.PowerShell.Core/Receive-Job.md
Fixes #4822 
Fixes [AB#1602762](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1602762)
> Fixes #4822 - Corrected typo

- gallery/how-to/publishing-packages/publishing-a-package.md
> Clarify DSC abbreviation.

- reference/3.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/4.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/5.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/6/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/7/Microsoft.PowerShell.Utility/Compare-Object.md
- Fixes [AB#1605980](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1605980)
- Fixes #4838
> Fixes #4838 - Fixed typo in examples

- reference/3.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md
- reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md
- reference/7/Microsoft.PowerShell.Core/About/about_Profiles.md
Fixes #4837 - fix profile paths for Windows PS
Fixes [AB#1606022](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1606022)
> Fixes #4837 - fix profile paths for Windows PS

- reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
- Fixes [AB#1607572](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1607572)
- Fixes #4820
- Updated link text and links
> Fixes #4820 - Updated Windows SSH configuration instructions

- reference/6/Microsoft.PowerShell.Utility/Get-Uptime.md
- reference/7/Microsoft.PowerShell.Utility/Get-Uptime.md
Fixes [AB#1609300](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1609300)
Fixes #4487 - Get-UpTime shows incorrect boot time
> Fixes #4487 - Get-UpTime shows incorrect boot time

- reference/5.0/PowershellGet/Publish-Module.md
- reference/5.1/PowershellGet/Publish-Module.md
- reference/6/PowerShellGet/Publish-Module.md
- reference/7/PowerShellGet/Publish-Module.md
Fixes [AB#1610071](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1610071)
Fixes #1378 - link to manifest UI mapping
> Fixes #1378 - link to manifest UI mapping

- reference/3.0/Microsoft.PowerShell.Management/Rename-Item.md
- reference/4.0/Microsoft.PowerShell.Management/Rename-Item.md
- reference/5.0/Microsoft.PowerShell.Management/Rename-Item.md
- reference/5.1/Microsoft.PowerShell.Management/Rename-Item.md
- reference/6/Microsoft.PowerShell.Management/Rename-Item.md
- reference/7/Microsoft.PowerShell.Management/Rename-Item.md
Fixes [AB#1610025](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1610025)
Fixes #4874 - Add Note to Example 4 About Case Sensitivity
> Fixes #4874 - Add Note About Case Sensitivity

- reference/6/Microsoft.PowerShell.Core/About/about_Return.md
> Minor formatting fixes

- reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
> fixes #4877 - fix spelling error

- reference/6/Microsoft.PowerShell.Management/Remove-Service.md
- reference/7/Microsoft.PowerShell.Management/Remove-Service.md
- reference/docs-conceptual/how-to-use-docs.md
Fix #4510 - add note about released in v6
Fixes [AB#1610731](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1610731)
> Fix #4510 - add note about released in v6

- reference/3.0/Microsoft.PowerShell.Core/About/about_Prompts.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Prompts.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Prompts.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Prompts.md
- reference/6/Microsoft.PowerShell.Core/About/about_Prompts.md
- reference/7/Microsoft.PowerShell.Core/About/about_Prompts.md
Closes #1582 - style cleanup
Fixes [AB#1610734](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1610734)
> Closes #1582 - style cleanup

- reference/3.0/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/4.0/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/5.0/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/5.1/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/6/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/7/Microsoft.PowerShell.Management/Restart-Computer.md
Fix #2652 - add WinRM/WMI requirement note
Fixes [AB#1610733](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1610733)
> Fix #2652 - add WinRM/WMI requirement note

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
powershell/powershell#10059
powershell/powershell#10255
powershell/powershell#10632
Fixes #4737
> Add docs for new distros

- .github/PULL_REQUEST_TEMPLATE.md
- reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/7/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
Added note about support of JSON with comments.
Fixes #4915 - add info about comments
Fixes [AB#1613469](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1613469)
and followed the style and process guidelines
> Fixes #4915 - add info about comments

- reference/3.0/Microsoft.PowerShell.Management/Test-Connection.md
- reference/4.0/Microsoft.PowerShell.Management/Test-Connection.md
- reference/5.0/Microsoft.PowerShell.Management/Test-Connection.md
- reference/5.1/Microsoft.PowerShell.Management/Test-Connection.md
- reference/6/Microsoft.PowerShell.Management/Test-Connection.md
- reference/7/Microsoft.PowerShell.Management/Test-Connection.md
- Fixes [AB#1611811](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1611811)
- Fixes #4902
Scores
and followed the style and process guidelines
> Fixes #4902 - Added info about -Quiet parameter's Boolean array

- reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/7/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
Add note about Execution Policies on Server Core and Nano for PS6/7. Some other minor edits. Synced changes to other versions.
Fixes #2440 - add note about core/nano
Fixes [AB#1613607](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1613607)
and followed the style and process guidelines
> Fixes #2440 - add note about core/nano

- reference/docs-conceptual/gallery/how-to/getting-support/troubleshooting-cmdlets.md
Fixes #1465 - add network endpoints
Fixes [AB#1613935](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1613935)
Added list of network endpoints used by the PowerShell Gallery.
> Fixes #1465 - add network endpoints

- .github/PULL_REQUEST_TEMPLATE.md
- reference/docs-conceptual/toc.yml
This is a continuation of PR #4923 and update PR template
> Fix SDK TOC

- reference/docs-conceptual/dsc/overview/decisionMaker.md
- Fixes [AB#1613963](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1613963)
- Fixes #4921
Scores
Original version: 77
> Fixes #4921 - Changed "premise" to "premises"

- reference/docs-conceptual/whats-new/breaking-changes-ps6.md
A customer brought up that they would like to leverage workflow checkpoints with PSCore6 (https://github.com/PowerShell/PowerShell/issues/10806).  Since PSCore6 doesn't support workflow, recommendation is to leverage Task Scheduler.
> add text on how to workaround lack of workflow checkpoints

- reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/6/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/7/Microsoft.PowerShell.Core/Invoke-Command.md
- Fixes [AB#1615867](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1615867)
- Fixes #4913
- Added Example 11 for the `Param` keyword
- Added Example 12 for the `$args` automatic variable
Scores
> Fixes #4913 - Added examples for Param keyword and $args variable

- reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
Change section on `-File` from discussing command and command arguments to file path and script parameters, since `-File` is for scripts, not commands.
> Update about_PowerShell_exe.md to match .exe help

- reference/5.1/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/6/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/7/Microsoft.PowerShell.Management/New-PSDrive.md
- Fixes [AB#1619886](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1619886)
- Fixes #3787
Scores
> Fixes #3787 - Added Credentials parameter to Example 4

- reference/6/Microsoft.PowerShell.Core/Start-Job.md
- reference/7/Microsoft.PowerShell.Core/Start-Job.md
- Fixes [AB#1620505](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1620505)
- Fixes #4965
- Added Example 2 for the ampersand (`&`) background operator
- Rewrote PS 7 example for **WorkingDirectory**: corrected the syntax and description
Original version: 98
> Fixes #4965 - Added information about the ampersand (&) background operator

- reference/docs-conceptual/dsc/pull-server/partialConfigs.md
The location was adding confusion.
N/A
> Fixed location of second partial mof file in example

- reference/5.1/PSScheduledJob/Register-ScheduledJob.md
- Fixes [AB#1626314](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1626314)
- Fixes #4983
- Fixed code samples to eliminate scrolling
> Fixes #4983 - Fixed typo in Example 2

- reference/5.1/PSScheduledJob/Register-ScheduledJob.md
- Related to Issue #4983 and PR #4998 
- Updated code samples
> Register-ScheduledJob - updated code samples

- reference/7/Microsoft.PowerShell.Management/Clear-RecycleBin.md
Fixes #5005 - add Clear-RecycleBin to v7 docs
Fixes [AB#1630775](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1630775)
> Fixes #5005 - add Clear-RecycleBin to v7 docs

- reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/6/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/7/Microsoft.PowerShell.Utility/Compare-Object.md
- Fixes #4568 - explain PassThru better
- Fixes #4468 
- Fixes [AB#1637064](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1637064)
> Fixes #4568 - explain PassThru better

- reference/6/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md
- reference/6/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md
- reference/6/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.md
- reference/6/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/6/Microsoft.PowerShell.Utility/Get-Culture.md
- reference/6/Microsoft.PowerShell.Utility/Join-String.md
- reference/7/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md
- reference/7/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md
- reference/7/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.md
- reference/7/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/7/Microsoft.PowerShell.Utility/Get-Culture.md
- reference/7/Microsoft.PowerShell.Utility/Join-String.md
> Cmdlets and parameters introduced in PS 6.2 (part 2)

- reference/docs-conceptual/components/vscode/using-vscode.md
- Fixes [AB#1641799](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1641799)
- Fixes #5053
- Updated header levels, changed H4 and H5 to H3.
Original version: 83
Updated version: 94
> Fixes #5053 - Corrected a typo for a command prompt's response

- reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/7/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- Fixes [AB#1643798](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1643798)
- Fixes #4594 for PS7 code change that affects `$PSCulture` in runspaces
- Updates the `$PSCulture` description for PS 5.1 , 6, and 7 
- Requested @iSazonov  to review this PR.
> Fixes #4594 - Updates $PSCulture description for PS7

- reference/docs-conceptual/components/vscode/understanding-file-encoding.md
> Add better example to encoding doc

- reference/docs-conceptual/whats-new/breaking-changes-ps6.md
Fixes #3044 - add note about UTF-8 in web cmdlets
Fixes [AB#1647335](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1647335)
> Fixes #3044 - add note about UTF-8 in web cmdlets

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Instructions were missing on how to install the msix package
> Add instructions to install MSIX

- reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/5.1/Microsoft.PowerShell.Utility/Tee-Object.md
- reference/6/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/6/Microsoft.PowerShell.Utility/Tee-Object.md
- reference/7/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/7/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/7/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/7/Microsoft.PowerShell.Utility/Tee-Object.md
- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Fixes [AB#1648022](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1648022) Fixes #5109 - Mention Stack Overflow as a community resource
Fixes [AB#1648023](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1648023) Fixes #5111 - Link from about_Classes to about_Hidden is missing
Fixes [AB#1648024](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1648024) Fixes #5112 - -EscapeHandling parameter description either needs to list the permissible enumeration
Fixes [AB#1648025](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1648025) Fixes #5113 - "Writing a PowerShell Module" link doesn't resolve
Fixes [AB#1648026](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f …
> Fix several reported issues

- reference/7/Microsoft.PowerShell.Core/About/about_Operators.md
Fixes [AB#1648139](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1648139) Fixes #5118 - link to "about_Pipeline_Chain_Operators"
> Fixes #5118 - link about_Pipeline_Chain_Operators

- reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/7/Microsoft.PowerShell.Core/About/about_Operators.md
Fixes [AB#1648193](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1648193) Fixes #5120 - use member access terminology
> Fixes #5120 - use member access terminology

- .openpublishing.publish.config.json
- reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
- reference/6/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
- reference/7/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
Fixes #3111 - add SuppressHashFilter info
Fixes [AB#1649071](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1649071)
> Fixes #3111 - add SuppressHashFilter info

- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Fixes #3288 - Add ValidateTrustedData
Fixes [AB#1649828](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1649828)
> Fixes #3288 - Add ValidateTrustedData

- reference/docs-conceptual/developer/module/how-to-write-a-powershell-script-module.md
- Fixes [AB#1649760](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1649760)
- Fixes #5122
- Changed header levels
Original version: 77
> Fixes #5122 - Use the same name for module script and directory

- reference/docs-conceptual/samples/Using-Format-Commands-to-Change-Output-View.md
Update coded character in command to reflect * in description
- Update coded character in command to reflect * in description
> (AzureCXP) Update coded character in command

- reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
- reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/6/Microsoft.PowerShell.Core/Import-Module.md
- reference/7/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/7/Microsoft.PowerShell.Core/Import-Module.md
Fixes #5178 - add examples for Import-Module
Fixes [AB#1652451](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1652451)
Fixes #5154 - explain grouping operator
Fixes [AB#1652333](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1652333)
> Fixes #5154 - explain grouping operator Fixes #5178 - add examples

- reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/7/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/7/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- Fixes [AB#1650166](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1650166)
- Fixes #4724
- Adds `-SkipHttpErrorCheck` and `-StatusCodeVariable` parameters to PowerShell 7 `Invoke-RestMethod`.
- Adds `-SkipHttpErrorCheck` parameter to PowerShell 7 `Invoke-WebRequest`.
- Fixes #4798 - adds link **Notes** for Accessing the Internet Through a Proxy.
- Adds link to **Notes** for `Invoke-WebRequest` output type.
- Copyedits, style, paragraph reflows for PS6 and PS7 versions.
Invoke-RestMethod Acrolinx scores:
Original version: 84
Updated version: 89
Invoke-WebRequest Acrolinx scores:
Updated version: 88
- If the PR is work in …
> Fixes #4724, Fixes #4798 - Adds parameters to PS7 web cmdlets and adds link to proxy information

- reference/5.1/Microsoft.PowerShell.Utility/Out-Printer.md
- reference/7/Microsoft.PowerShell.Utility/Out-Printer.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
- Fixes [AB#1653259](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1653259)
- Fixes #5173 - Adds link to Debian 10 section in `Installing-PowerShell-Core-on-Linux`
- Fixes [AB#1652479](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1652479)
- Fixes #5184 - Fixes typo in `Out-Printer` Example 1
> Fixes #5173, Fixes #5184 - Adds link and fixes typo

- reference/docs-conceptual/getting-started/Starting-Windows-PowerShell.md
- Fixes [AB#1653983](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1653983)
- Fixes #5093
- Adds H2 section: **PowerShell Core has renamed binary**
- Adds links to PowerShell 7 documents
Original version: 91
Updated version: 94
> Fixes #5093 - PowerShell Core binary renamed to pwsh

- reference/docs-conceptual/install/Windows-PowerShell-System-Requirements.md
- Fixes [AB#1654254](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1654254)
- Fixes #5197
- Fixes typos and broken links
- Adds H3 headers and tables
> Fixes #5197 - Fixes typo and broken links

- reference/5.1/Microsoft.PowerShell.Core/Start-Job.md
- reference/6/Microsoft.PowerShell.Core/Start-Job.md
- reference/7/Microsoft.PowerShell.Core/Start-Job.md
- Fixes [AB#1654984](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1654984)
- Fixes #4944
- Adds example to specify an array using the **ArgumentList** parameter
> Fixes #4944 - Updates the ArgumentList parameter's description

- reference/7/Microsoft.PowerShell.Utility/Select-String.md
> Add more information about Culture parameter in Select-String cmdlet

- reference/docs-conceptual/dsc/getting-started/winGettingStarted.md
- reference/docs-conceptual/dsc/quickstarts/website-quickstart.md
Adds not about updating WinRm configuration prior to using DSC
Fixes #5168 
Fixes [AB#1655020](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1655020)
> [Fixes #5168]Add info for WinRm config with DSC

- reference/7/CimCmdlets/CimCmdlets.md
- reference/7/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md
- reference/7/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md
- reference/7/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.md
- reference/7/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.md
- reference/7/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.md
- reference/7/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md
- reference/7/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
- reference/7/Microsoft.WSMan.Management/Microsoft.WSMan.Management.md
- reference/7/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md
- reference/7/PSDiagnostics/PSDiagnostics.md
- reference/7/PSReadLine/PSReadLine.md
- reference/7/PackageManagement/PackageManagement.md
- reference/7/PowerShellGet/PowerShellGet.md
- reference/7/ThreadJob/ThreadJob.md
Fixes [AB#1655838](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1655838)
> Update Help Version number for each module in v7

- reference/docs-conceptual/dsc/configurations/compositeConfigs.md
- reference/docs-conceptual/dsc/resources/authoringResourceComposite.md
Adds information about nesting configurations and composite resources
Fixes #4719 
Fixes [AB#1655902](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1655902)
> [Fixes#4719] Adds nested config information

- reference/7/Microsoft.PowerShell.Management/Test-Connection.md
Update Test-Connection cmdlet to reflect new changes per #4987.
Resolves #4987 
> (#4987) Update Test-Connection docs

- reference/5.1/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md
Adds Output for Get-DscLocalConfigurationManager and a link to documentation explaining the attributes of the output. 
Fixes #4432 
Fixes [AB#1656379](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1656379)
- [x Version 5.1 content
- [x I have read the [contributors guide](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/CONTRIBUTING.md) and followed the style and process guidelines
- [x PR has a meaningful title
- [x All relevant versions updated
- [x Includes content related to issues and PRs - see [Closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords).
- If the PR is work in progress, …
> Fixes #44342 Adds Get-DscLocalConfigurationManager Output

- reference/docs-conceptual/gallery/how-to/working-with-local-psrepositories.md
- reference/docs-conceptual/toc.yml
Issue 1200 reports issues with trying to set up a repo in Azure Artifacts and using hosted Private PowerShell Repositories?
Fixes #1200 
Fixes [AB#1656903](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1656903)
- [x ] Gallery articles
- [x ] I have read the [contributors guide](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/CONTRIBUTING.md) and followed the style and process guidelines
- [x ] PR has a meaningful title
- [x ] PR is targeted at the _staging_ branch
- [x ] All relevant versions updated
- [x ] Includes content related to issues and PRs - see [Closing issues using …
> Fixes 1200 Adds Section for Hosted Private PowerShell Repos

- reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/7/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/7/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Fixes #4283 - add new ActionPreference.Break
Fixes [AB#1658193](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658193) - also includes some style cleanup and clarifications around **Suspend**
> Fixes #4283 - add new ActionPreference.Break

- reference/5.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/6/ThreadJob/Start-ThreadJob.md
- reference/7/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/7/ThreadJob/Start-ThreadJob.md
Fixes #5223 - addresses feedback
Fixes [AB#1658247](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658247)
Also updated `Start-ThreadJob` to properly format braces. This is related to confusion described in #5229.
> Fixes #5223 - addresses feedback

- reference/5.1/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md
- reference/5.1/PSDesiredStateConfiguration/Disable-DscDebug.md
- reference/5.1/PSDesiredStateConfiguration/Enable-DscDebug.md
- reference/5.1/PSDesiredStateConfiguration/Get-DscConfiguration.md
- reference/5.1/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md
- reference/5.1/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md
- reference/5.1/PSDesiredStateConfiguration/Invoke-DscResource.md
- reference/5.1/PSDesiredStateConfiguration/New-DSCCheckSum.md
- reference/5.1/PSDesiredStateConfiguration/Publish-DscConfiguration.md
- reference/5.1/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md
- reference/5.1/PSDesiredStateConfiguration/Restore-DscConfiguration.md
- reference/5.1/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md
- reference/5.1/PSDesiredStateConfiguration/Test-DscConfiguration.md
- reference/5.1/PSDesiredStateConfiguration/Update-DscConfiguration.md
- reference/6/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md
- reference/6/PSDesiredStateConfiguration/New-DSCCheckSum.md
- reference/6/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md
- reference/7/PSDesiredStateConfiguration/About/about_Classes_and_DSC.md
- reference/7/PSDesiredStateConfiguration/New-DSCCheckSum.md
- reference/7/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md
Fixes [AB#1658912](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658912) - Cleanup FWLinks in DSC
> Fixes AB#1658912 - Cleanup FWLinks in DSC

- reference/6/ThreadJob/ThreadJob.md
- reference/7/CimCmdlets/CimCmdlets.md
- reference/7/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md
- reference/7/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md
- reference/7/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.md
- reference/7/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.md
- reference/7/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.md
- reference/7/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md
- reference/7/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
- reference/7/Microsoft.WSMan.Management/Microsoft.WSMan.Management.md
- reference/7/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md
- reference/7/PSDiagnostics/PSDiagnostics.md
- reference/7/PSReadLine/PSReadLine.md
- reference/7/PackageManagement/PackageManagement.md
- reference/7/PowerShellGet/PowerShellGet.md
- reference/7/ThreadJob/ThreadJob.md
Fixes [AB#1655933](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1655933) - update helpuri for modules
> Fixes AB#1655933 - update helpuri for modules

- reference/5.1/Microsoft.PowerShell.Utility/Select-String.md
- reference/6/Microsoft.PowerShell.Utility/Select-String.md
- reference/7/Microsoft.PowerShell.Utility/Select-String.md
Fixes #5108 - add notes about SimpleMatch
Fixes [AB#1658944](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658944)
> Fixes #5108 - add notes about SimpleMatch

- reference/5.1/Microsoft.PowerShell.Core/New-PSSession.md
- reference/6/Microsoft.PowerShell.Core/New-PSSession.md
- reference/7/Microsoft.PowerShell.Core/New-PSSession.md
Fixes #5095 - Get-Container?
Fixes [AB#1658979](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658979)
> Fixes #5095 - Get-Container?

- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-62.md
Fixing code syntax for Powershell command
This proposed file change comes from a contributor in this PR https://github.com/MicrosoftDocs/powerShell-Docs.pt-br/pull/5 .
> CC166661: Fixing code syntax

- reference/docs-conceptual/components/ise/object-model/Purpose-of-the-Windows-PowerShell-ISE-Scripting-Object-Model.md
- reference/docs-conceptual/components/ise/object-model/The-ISE-Object-Model-Hierarchy.md
- reference/docs-conceptual/components/ise/object-model/The-ISEAddOnTool-Object.md
- reference/docs-conceptual/components/ise/object-model/The-ISEAddOnToolCollection-Object.md
- reference/docs-conceptual/components/ise/object-model/The-ISEEditor-Object.md
- reference/docs-conceptual/components/ise/object-model/The-ISEFile-Object.md
- reference/docs-conceptual/components/ise/object-model/The-ISEFileCollection-Object.md
- reference/docs-conceptual/components/ise/object-model/The-ISEMenuItem-Object.md
- reference/docs-conceptual/components/ise/object-model/The-ISEMenuItemCollection-Object.md
- reference/docs-conceptual/components/ise/object-model/The-ISEOptions-Object.md
- reference/docs-conceptual/components/ise/object-model/The-ISESnippetCollection-Object.md
Refreshing the ISE Conceptual docs for current formatting. Part 1 of two
Doesn't have any fixes for this one but will be fixed in Pt2
> Formatting Refresh for ISE conceptual docs Pt1

- reference/docs-conceptual/dsc/configurations/flow-control-in-configurations.md
Customer pointed out that there are some grammar and formatting issues with this article. Please review to ensure correct grammar and formatting practices.
Fixes #5271 
Fixes [AB#1661310](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1661310)
> [Fixes 5271] Refresh for grammar and formatting

- reference/7/Microsoft.PowerShell.Core/New-ModuleManifest.md
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5275
Update RequireLicenseAcceptance example value.
> Update RequireLicenseAcceptance example value

- reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md
Completes Formatting refresh for New-LocalUser Doc
Fixes #5277 
Fixes [AB#1661835](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1661835)
> [Fixes # 5277] Formatting refresh for New-LocalUser

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Update references to version 6.2.0 to 7 or 7.0.0 depending on how it's being used.  Also update install instructions for Kali.
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5273
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5212
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5206
> Update references to version from 6.2 to 7

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Update support table for PS7 based on .NET Core 3.1 support
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5129
> Updated support of 7 for RHEL8 and CentOS8

- reference/7.0/Microsoft.PowerShell.Core/Invoke-Command.md
fixes https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5255
Adds the `-JobName` to ssh parameter sets and also fixes a few issues platyPS picked up.
PowerShell PR: https://github.com/PowerShell/PowerShell/pull/11444
> Update Invoke-Command doc for -JobName and misc other changes

- reference/7.0/Microsoft.PowerShell.Management/Get-ChildItem.md
- reference/7.0/Microsoft.PowerShell.Management/Get-Item.md
Add an additional example which shows how the output looks for Get-Item and Get-ChildItem when the unixstat experimental feature is enabled.
> Updates to item cmdlets to describe output for Unix stat experimental feature

- reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
Fixes #4925
Add documentation for `??` `??=` `?.` and `?[]` operators. 
> Null coalescing and null conditional operators

- reference/7.0/Microsoft.PowerShell.Utility/Unblock-File.md
add note about macOS support
add note about macOS support
Issue #5148 
> Update Unblock-File.md to include macOS support

- reference/docs-conceptual/developer/cmdlet/cmdlet-parameters.md
Correcting `Discuses the names, recommended data type, and functionality of standard parameters.` to `Discusses the names, recommended data type, and functionality of standard parameters.`
> fixing typo - Discuses -> Discusses

- reference/7.0/Microsoft.PowerShell.Core/About/about_Update_Notifications.md
First pass draft of fixing #4881, would like to get @daxian-dbw 's review before we merge (I'm sure I missed something important).
> First draft of about_Update_Notifications

- reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md
Resolves https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4991.
> Add information on configuring pwsh as a login shell

- reference/docs-conceptual/learn/Writing-Portable-Modules.md
Added content on how PS7 handles native library loading based on RID folders
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5196
> Add information on how PS7 does native lib loading

- reference/5.1/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/6/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/7.0/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/7.1/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/docs-conceptual/dsc/pull-server/pullServer.md
Updates Information `Format-Hex` in PowerShell 7 and formatting for other versions. 
Fixes #4532 
Fixes [AB#1662338](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1662338)
> Updates Information Format-Hex in PowerShell 7 

- reference/5.1/CimCmdlets/Invoke-CimMethod.md
- reference/6/CimCmdlets/Invoke-CimMethod.md
- reference/7.0/CimCmdlets/Invoke-CimMethod.md
- reference/7.1/CimCmdlets/Invoke-CimMethod.md
Fixes #5336 - remove Ex#3 - style cleanup
Fixes [AB#1667152](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1667152)
> Fixes #5336 - remove Ex#3 - style cleanup

- reference/docs-conceptual/learn/remoting/jea/role-capabilities.md
Fixes #5312 - clarify location of PSRC file
Fixes [AB#1667679](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1667679)
> Fixes #5312 - clarify location of PSRC file

- reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Scopes.md
Fixes #5340 - modules have scope
Fixes [AB#1668174](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1668174)
> Fixes #5340 - modules have scope

- reference/7.1/Microsoft.PowerShell.Management/Stop-Computer.md
Fixes #5171 - Stop-Computer for non-Win machines
Fixes [AB#1668625](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1668625)
> Fixes #5171 - Stop-Computer for non-Win machines

- reference/6/Microsoft.PowerShell.Management/Set-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Set-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Set-Location.md
Fixes #5360 - Fixes [AB#1669215](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669215) update +/- for cd
Fixes #5361 - Fixes [AB#1669216](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669216)
> Fixes #5360 -fix +/- notes for cd

- reference/6/ThreadJob/Start-ThreadJob.md
- reference/7.0/ThreadJob/Start-ThreadJob.md
- reference/7.1/ThreadJob/Start-ThreadJob.md
Fixes #5246 - ThrottleLimit
Fixes [AB#1670135](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1670135)
> Fixes #5246 - ThrottleLimit

- reference/5.1/Microsoft.PowerShell.Utility/Format-Hex.md
Fixes #5367 - fix Raw param for v5.1
Fixes [AB#1670655](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1670655)
> Fixes #5367 - fix Raw param for v5.1

- reference/5.1/Microsoft.PowerShell.Core/About/about_Using.md
- reference/6/Microsoft.PowerShell.Core/About/about_Using.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Using.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Using.md
Fixes #3277 - using assembly
Fixes [AB#1670360](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1670360)
> Fixes #3277 - using assembly

- reference/docs-conceptual/dsc/pull-server/pullServer.md
> add recommendation for scaling pull services

- reference/5.1/Microsoft.PowerShell.Core/About/about_Using.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/5.1/Microsoft.PowerShell.Utility/Get-FormatData.md
- reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md
- reference/6/Microsoft.PowerShell.Core/About/about_Using.md
- reference/6/Microsoft.PowerShell.Management/Set-Location.md
- reference/6/Microsoft.PowerShell.Utility/Get-FormatData.md
- reference/6/Microsoft.PowerShell.Utility/Measure-Command.md
- reference/6/ThreadJob/Start-ThreadJob.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Using.md
- reference/7.0/Microsoft.PowerShell.Management/Set-Location.md
- reference/7.0/Microsoft.PowerShell.Utility/Get-FormatData.md
- reference/7.0/Microsoft.PowerShell.Utility/Measure-Command.md
- reference/7.0/ThreadJob/Start-ThreadJob.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Using.md
- reference/7.1/Microsoft.PowerShell.Management/Set-Location.md
- reference/7.1/Microsoft.PowerShell.Utility/Get-FormatData.md
- reference/7.1/Microsoft.PowerShell.Utility/Measure-Command.md
- reference/7.1/ThreadJob/Start-ThreadJob.md
- reference/docs-conceptual/dsc/pull-server/pullServer.md
Publishing latest changes to live
> Publish to live

- reference/docs-conceptual/toc.yml
- reference/docs-conceptual/whats-new/cmdlet-versions.md
Fixes #2270 
Fixes [AB#1671239](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1671239)
Created table of modules and cmdlets to note the version of PowerShell and OS platform that is supported.
> Add list of cmdlets and modules

- reference/docs-conceptual/developer/module/importing-a-powershell-module.md
Minor typo fix and formatting updates
Fixes #5395 
> [Fixes #5395] Fixes typo

- reference/5.1/PowershellGet/Install-Module.md
- reference/6/PowerShellGet/Install-Module.md
- reference/7.0/PowerShellGet/Install-Module.md
- reference/7.1/PowerShellGet/Install-Module.md
Improve wording for the help of Install-Module. The parameters MinimumVersion and MaximumVersion left it unclear whether they were inclusive or exclusive.
- [ x] I have read the [contributors guide](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/CONTRIBUTING.md) and followed the style and process guidelines
- [x ] PR has a meaningful title
- [x ] PR is targeted at the _staging_ branch
- [x ] All relevant versions updated
- [x ] This PR is ready to merge and is not **Work in Progress**
> Improve wording for Maximum- and MinimumVersion

- reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/6/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/7.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/7.1/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/docs-conceptual/whats-new/cmdlet-versions.md
Adds example for nested tracking and information for **SourceId** parameter.
Fixes #5049 
> [Fixes 5049] Updates Write-Progress

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Update support and EOL information
- EOL Windows 7 and 2008 R2
- EOL OpenSUSE 42.3
- EOL Fedora 28
- Remove Fedora 29 (never became officially supported by PowerShell)
- Update Ubuntu Interim release information
> Update support and EOL information

- reference/7.0/PSReadLine/About/about_PSReadLine.md
- reference/7.0/PSReadLine/PSReadLine.md
- reference/7.1/PSReadLine/About/about_PSReadLine.md
- reference/7.1/PSReadLine/PSReadLine.md
Fixes #4659 - Add note about NVDA
Fixes [AB#1674883](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1674883)
> Fixes #4659 - Add note about NVDA

- reference/docs-conceptual/dsc/troubleshooting/troubleshooting.md
> Sysprep issue

- reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalUser.md
Fixes #5429 - fix parameter name
Fixes [AB#1674957](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1674957)
> Fixes #5429 - fix parameter name

- reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md
- reference/6/Microsoft.PowerShell.Management/Copy-Item.md
- reference/7.0/Microsoft.PowerShell.Management/Copy-Item.md
- reference/7.1/Microsoft.PowerShell.Management/Copy-Item.md
Updates Copy-Item to correct example Information
Fixes #2230 
Fixes [AB#1675123](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1675123)
> [Fixes #2230] Updates Copy-Item

- reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md
Fixes #5441 - remove duplicate code
Fixes [AB#1676422](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1676422)
> Fixes #5441 - remove duplicate code

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
Updates for formatting and adds example for function that shouldn't have output
Fixes #4612 
Fixes [AB#1677042](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1677042)
> [Fixes #4612] Updates about_Functions_OutputTypeAttribute

- reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
Title says it all
Fixes #5454 
Fixes [AB#1678250](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1678250)
> Fixes Typos in Invoke-RestMethod

- reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
Fixes #5374 - clarify non-Win behavior
Fixes [AB#1678922](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1678922)
- If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title and remove the prefix when the PR is ready.
> Fixes #5374 - clarify non-Win behavior

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Fixes #5456 - add release history
Fixes [AB#1679450](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1679450)
> Fixes #5456 - add release history

- reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md
- reference/5.1/Microsoft.PowerShell.Archive/Expand-Archive.md
- reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md
- reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md
- reference/7.0/Microsoft.PowerShell.Archive/Compress-Archive.md
- reference/7.0/Microsoft.PowerShell.Archive/Expand-Archive.md
- reference/7.1/Microsoft.PowerShell.Archive/Compress-Archive.md
- reference/7.1/Microsoft.PowerShell.Archive/Expand-Archive.md
Fixes #5450 - add note about UTF8
Fixes [AB#1679482](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1679482)
> Fixes #5450 - add note about UTF8

- reference/docs-conceptual/samples/Creating-a-Custom-Input-Box.md
- reference/docs-conceptual/samples/Creating-a-Graphical-Date-Picker.md
- reference/docs-conceptual/samples/Selecting-Items-from-a-List-Box.md
User noticed inconsistent formatting in documented example scripts. Updated for suggested best practice.
Fixes #5467 
Fixes [AB#1680014](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1680014)
> [Fixes 5467] Updates Sample Scripts

- reference/docs-conceptual/learn/remoting/jea/register-jea.md
Customer noticed broken link leading to DSC documentation
Fixes #5473 
Fixes [AB#1680383](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1680383)
> [Fixes 5473] Fixes Broken Link in Registering JEA Configurations

- reference/7.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
Updated the high-level document that describes PowerShell Group Policy settings.
Partially addresses issue #4216 
> WIP: Make about_Group_Policy_Settings.md up to date

- reference/7.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
Copied updated GP info from 7.0 to 7.1
Updated the high-level document that describes PowerShell Group Policy settings.
Partially addresses issue #4216
> Copied updated Group Policy info from 7.0 to 7.1

- reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
- reference/6/Microsoft.PowerShell.Core/Import-Module.md
- reference/7.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md
- reference/7.1/Microsoft.PowerShell.Core/Import-Module.md
Fixes #2730 - explain module scopes better
Fixes [AB#1680697](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1680697)
> Fixes #2730 - explain module scopes better

- reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
> document env vars for module analysis cache

- reference/docs-conceptual/dsc/resources/resources.md
Update information to better communicate resources type and availability.
Fixes #5260 
Fixes [AB#1682540](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1682540)
> [Fixes #5260] Updates DSC Resources Article

- reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md
- reference/6/Microsoft.PowerShell.Core/About/about_Break.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Break.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Break.md
Example needed to be updated for clarification and formatting for doc
Fixes #5505 
Fixes [AB#1686435](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1686435)
> [Fixes 5505] Updates about_Break

- reference/docs-conceptual/install/PowerShell-in-Docker.md
- reference/docs-conceptual/toc.yml
> Add Docker article

- reference/docs-conceptual/dsc/pull-server/pullServer.md
> Pull server number of nodes reference

- reference/5.1/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/6/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/7.0/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/7.1/Microsoft.PowerShell.Management/New-PSDrive.md
While there is already information about running the command in a script and ensuring the drive persists, it could be clarified under the examples as well. 
Fixes #5477 
Fixes [AB#1683205](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1683205)
> [Fixes 5477] Updates New-PSDrive

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
> fixed typo in Installing-PS-Core-on-Windows

- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md
There are a few places that tripped me up while reading the What's New in PowerShell 7.
These changes should improve readability and clarity.
Not applicable.
> Fix small grammar issues in v7 What's New

- reference/7.0/Microsoft.PowerShell.Utility/Out-GridView.md
- reference/7.1/Microsoft.PowerShell.Utility/Out-GridView.md
- reference/docs-conceptual/whats-new/cmdlet-versions.md
Fixes #5523 - OGV is Windows only - Fixes [AB#1687589](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1687589)
Fixes #5522 - Mention GraphicalTools module - Fixes [AB#1687588](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1687588)
> Fixes #5522 - OGV is Windows only

- reference/5.1/CimCmdlets/New-CimSessionOption.md
- reference/6/CimCmdlets/New-CimSessionOption.md
- reference/7.0/CimCmdlets/New-CimSessionOption.md
- reference/7.1/CimCmdlets/New-CimSessionOption.md
Fixes #5524 - fix protocol values
Fixes [AB#1687594](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1687594)
> Fixes #5524 - fix protocol values

- reference/7.0/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md
Fixes #5520 - throw out the "throw"
Fixes [AB#1687598](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1687598)
> Fixes #5520 - throw out the "throw"

- reference/5.1/Microsoft.PowerShell.Core/Get-PSSession.md
- reference/5.1/Microsoft.PowerShell.Core/Remove-PSSession.md
- reference/6/Microsoft.PowerShell.Core/Get-PSSession.md
- reference/6/Microsoft.PowerShell.Core/Remove-PSSession.md
- reference/7.0/Microsoft.PowerShell.Core/Get-PSSession.md
- reference/7.0/Microsoft.PowerShell.Core/Remove-PSSession.md
- reference/7.1/Microsoft.PowerShell.Core/Get-PSSession.md
- reference/7.1/Microsoft.PowerShell.Core/Remove-PSSession.md
Fixes #5544 - no Get-Container
Fixes [AB#1688094](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1688094)
> Fixes #5544 - no Get-Container

- reference/docs-conceptual/samples/Working-with-Printers.md
Fixes #5532 - setdefaultprinter CimMethod
Fixes [AB#1688107](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1688107)
> Fixes #5532 - setdefaultprinter CimMethod

- reference/docs-conceptual/gallery/how-to/getting-support/bootstrapping-nuget.md
Fixes #4477 - add import step to bootstrap
Fixes [AB#1688117](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1688117)
> Fixes #4477 - add import step to bootstrap

- reference/5.1/Microsoft.PowerShell.Core/About/about_History.md
- reference/6/Microsoft.PowerShell.Core/About/about_History.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_History.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_History.md
Fixes #5559 - update key bindings
Fixes [AB#1689391](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1689391)
> Fixes #5559 - update key bindings

- reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/5.1/PowershellGet/Install-Module.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/6/PowerShellGet/Install-Module.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/7.0/PowerShellGet/Install-Module.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/7.1/PowerShellGet/Install-Module.md
Addition to PR #5533  to add example using GetFolderPath method.
> Based on PR#5533 - show GetFolderPath method

- reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Updates about_Regular_Expressions for multiple issues (listed below)
Fixes #5416
FIxes #5568 
Fixes [AB#1683292](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1683292)
Fixes [AB#1690343](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1690343)
> Updates about_Regular_Expressions

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Fixes #5575 - remove preview example
[AB#1693657](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1693657)
> Fixes #5575 - remove preview example

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
With the release of PowerShell 7, the support lifecycle has changed in major ways. This PR updates docs to reflect current information.
Fixes #5549 
Fixes #5551 
Fixes [AB#1689188](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1689188)
> Updates PowerShell Life cycle doc

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Fixes #4177 - update example for IoT
Fixes [AB#1696163](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1696163)
> Fixes #4177 - update example for IoT

- reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fixes #5530 - proxy support
Fixes [AB#1696305](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1696305)
> Fixes #5530 - proxy support

- reference/docs-conceptual/how-to-use-docs.md
PowerShell 7 preivew language was still available in how-to-use-docs.md
Fixes #5590 
Fixes [AB#1696609](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1696609)
> Fixes # 5590 Removes PowerShell 7 oreview language

- reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
- reference/6/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Pwsh.md
Updates information about PowerShell.exe and pwsh.exe command line tools
Fixes #4964 
Fixes [AB#1696384](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1696384)
> Fixes #4964 about_powershell_exe and about_pwsh

- reference/docs-conceptual/components/vscode/using-vscode.md
Fixes https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5576
Freshens up a lot of the content in the Using-vscode.md doc.
cc @SydneyhSmith @rjmholt 
> Freshen up VS Code doc a bit

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
Fixes #5398 - explain dotnet tool install results
[AB#1677900](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1677900)
> Fixes #5398 - explain dotnet tool install results

- reference/5.1/Microsoft.PowerShell.Utility/New-TemporaryFile.md
- reference/6/Microsoft.PowerShell.Utility/New-TemporaryFile.md
- reference/7.0/Microsoft.PowerShell.Utility/New-TemporaryFile.md
- reference/7.1/Microsoft.PowerShell.Utility/New-TemporaryFile.md
Fixes #5598 - explain TEMP folder
Fixes [AB#1697323](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1697323)
> Fixes #5598 - explain TEMP folder

- reference/7.1/Microsoft.PowerShell.Security/Get-CmsMessage.md
- reference/7.1/Microsoft.PowerShell.Security/Protect-CmsMessage.md
- reference/7.1/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md
- reference/docs-conceptual/whats-new/cmdlet-versions.md
Fixes #5422 - add cms cmdlets for Linux/macOS
Fixes [AB#1699003](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699003)
> Fixes #5422 - add cms cmdlets for Linux/macOS

- reference/5.1/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Variables.md
Fixes #5067 - introduce remote variables
Fixes [AB#1699101](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699101)
> Fixes #5067 - introduce remote variables

- reference/5.1/Microsoft.PowerShell.Utility/Disable-RunspaceDebug.md
- reference/5.1/Microsoft.PowerShell.Utility/Enable-RunspaceDebug.md
- reference/5.1/Microsoft.PowerShell.Utility/Get-RunspaceDebug.md
- reference/6/Microsoft.PowerShell.Utility/Disable-RunspaceDebug.md
- reference/6/Microsoft.PowerShell.Utility/Enable-RunspaceDebug.md
- reference/6/Microsoft.PowerShell.Utility/Get-RunspaceDebug.md
- reference/7.0/Microsoft.PowerShell.Utility/Disable-RunspaceDebug.md
- reference/7.0/Microsoft.PowerShell.Utility/Enable-RunspaceDebug.md
- reference/7.0/Microsoft.PowerShell.Utility/Get-RunspaceDebug.md
- reference/7.1/Microsoft.PowerShell.Utility/Disable-RunspaceDebug.md
- reference/7.1/Microsoft.PowerShell.Utility/Enable-RunspaceDebug.md
- reference/7.1/Microsoft.PowerShell.Utility/Get-RunspaceDebug.md
Fixes #4353 - add notes and examples
Fixes [AB#1699151](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699151)
> Fixes #4353 - add notes and examples

- reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/5.1/Microsoft.PowerShell.Core/Where-Object.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/6/Microsoft.PowerShell.Core/Where-Object.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/7.0/Microsoft.PowerShell.Core/Where-Object.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/7.1/Microsoft.PowerShell.Core/Where-Object.md
Fixes #3357 - add boolean discussion
Fixes [AB#1699312](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699312)
> Fixes #3357 - add boolean discussion

- reference/5.1/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/7.0/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-Expression.md
Fixes #4914 - introduce remote variables
Fixes [AB#1699107](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699107)
> Fixes #4914 - add note about scope

- reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md
- reference/6/Microsoft.PowerShell.Core/About/about_Type_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Type_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Type_Operators.md
Fixes #3193 - note datetime conversion
Fixes [AB#1699468](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699468)
> Fixes #3193 - note datetime conversion

- reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md
- reference/6/Microsoft.PowerShell.Utility/Get-Random.md
Fixes #4658 - remove invalid example
Fixes [AB#1699509](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699509)
> Fixes #4658 - remove invalid example

- reference/5.1/Microsoft.PowerShell.Utility/Sort-Object.md
- reference/6/Microsoft.PowerShell.Utility/Sort-Object.md
- reference/7.0/Microsoft.PowerShell.Utility/Sort-Object.md
- reference/7.1/Microsoft.PowerShell.Utility/Sort-Object.md
Fixes [AB#1699519](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699519)
Fixes #5615 - fix example 8
> Fixes #5615 - fix example 8

- reference/docs-conceptual/components/vscode/using-vscode.md
Originally mentioned here: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3536#issuecomment-514765707
This adds a small pointer to VS Code's docs on settings management so folks know how to use settings.
cc @SydneyhSmith @rjmholt 
> Add VS Code settings pointer

- reference/7.0/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md
Fixes #5621 - link to compat list - Fixes [AB#1699695](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699695)
Fixes #5623 - update examples and fix grammar -  Fixes [AB#1699704](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1699704)
> Fixes #5621 - link to compat list

- reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md
- reference/6/Microsoft.PowerShell.Management/Copy-Item.md
- reference/7.0/Microsoft.PowerShell.Management/Copy-Item.md
- reference/7.1/Microsoft.PowerShell.Management/Copy-Item.md
Fixes #5619 - add example using -Container
Fixes [AB#1700423](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1700423)
> Fixes #5619 - add example using -Container

- reference/docs-conceptual/dsc/configurations/add-parameters-to-a-configuration.md
Fixes #5630 - fix example
Fixes [AB#1700671](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1700671)
> Fixes #5630 - fix example

- reference/5.1/Microsoft.PowerShell.Security/Get-Acl.md
- reference/6/Microsoft.PowerShell.Security/Get-Acl.md
- reference/7.0/Microsoft.PowerShell.Security/Get-Acl.md
- reference/7.1/Microsoft.PowerShell.Security/Get-Acl.md
Fixes #5634 - update output types
Fixes [AB#1700833](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1700833)
> Fixes #5634 - update output types

- reference/5.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/docs-conceptual/samples/Sample-Scripts-for-Administration.yml
Fixes #5637 - add info about ADMX files and sync
Fixes [AB#1700975](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1700975)
> Fixes #5637 - add info about ADMX files and sync

- reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
> [wip]Migrating from Windows PowerShell 5.1 to PowerShell 7

- reference/6/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Pwsh.md
Fixes #5643 - fix chsh example
Fixes [AB#1701877](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1701877)
> Fixes #5643 - fix chsh example

- reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md
Fixes #5644 - fix interface example
Fixes [AB#1701878](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1701878)
> Fixes #5644 - fix interface example

- reference/5.1/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
- reference/5.1/Microsoft.PowerShell.Management/Get-Item.md
- reference/6/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md
- reference/6/Microsoft.PowerShell.Management/Get-Item.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/7.0/Microsoft.PowerShell.Management/Get-ChildItem.md
- reference/7.0/Microsoft.PowerShell.Management/Get-Item.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md
- reference/7.1/Microsoft.PowerShell.Management/Get-Item.md
Fixes #5641 - add output type info
Fixes [AB#1701873](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1701873)
> Fixes #5641 - add output type info

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Fixes [AB#1701856](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1701856)
> Edits for OKR-CSAT

- reference/5.1/PowershellGet/Publish-Script.md
- reference/6/PowerShellGet/Publish-Script.md
- reference/7.0/PowerShellGet/Publish-Script.md
- reference/7.1/PowerShellGet/Publish-Script.md
Fixes #5649 - fix formatting
Fixes [AB#1701980](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1701980)
> Fixes #5649 - fix formatting

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Modify package name.
Some packages for Linux distributions are added "lts" on those package name.
Packages name are fixed correctly on this PR.
> Correct package name

- reference/docs-conceptual/community/community-support.md
> Fix broken link (community-support.md)

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Unify to capitalization (.NET "C"ore).
This is important for translation.
Some localized pages, at least on Japanese version, this make confusion of machine translation and cause over-translate.
> Unify to capitalization (PowerShell-Support-Lifecycle.md)

- reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
> Fix broken annotation. (Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md)

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
- Modify PKG file name to latest version (v7).
- Modify TAR binary file name to latest version (v7).
- Modify some path which including version.
> Update file name and install path to v7.0.0

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Update "Supports" description to match the article.
> Update "Supports" description to match the article. (Installing-PowerShell-Core-on-Linux.md)

- reference/5.1/Microsoft.PowerShell.Management/New-Service.md
- reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md
- reference/5.1/Microsoft.PowerShell.Management/Set-Service.md
- reference/5.1/Microsoft.PowerShell.Utility/Wait-Debugger.md
- reference/6/Microsoft.PowerShell.Utility/Wait-Debugger.md
- reference/7.0/Microsoft.PowerShell.Utility/Wait-Debugger.md
- reference/7.1/Microsoft.PowerShell.Utility/Wait-Debugger.md
- reference/docs-conceptual/developer/installing-the-windows-powershell-sdk.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Fixes [AB#1702393](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702393) - Fixes #5661 - fix dead link
Fixes [AB#1702376](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702376) - Fixes #5666 - fix AutomaticDelayedStart
Fixes [AB#1702375](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702375) - Fixes #5661 - replace spam URL
Fixes [AB#1702419](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702419) - Fixes #5663 - update Wait-Debugger
Fixes [AB#1702421](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702421) - Fixes #5655 - fix Raspbian example
**Cmdlet reference & about_ …
> Fix multiple issues

- reference/5.1/Microsoft.PowerShell.Core/About/about_Logging.md
- reference/6/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
- reference/6/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
Fixes [AB#1702468](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702468) - Fixes #3349 - add link to SEIM
> Fixes #3349 - add link to SEIM

- reference/docs-conceptual/components/vscode/using-vscode.md
Remove "Core" because title of each link target pages have been modified with the release of PowerShell 7.
> Remove "Core" from link caption

- reference/6/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/7.0/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/7.1/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/docs-conceptual/dsc/overview/authoringAdvanced.md
Fixes [AB#1702506](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702506) - Fixes #4869 - update SSH parameters
Fixes [AB#1702549](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702549) - Fixes #5672 - typo
> Fixes #4869 - update SSH parameters

- reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/6/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md
Fixes [AB#1702573](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702573) - Fixes #4963 - stop-parsing is for Windows
> Fixes #4963 - stop-parsing is for Windows

- reference/docs-conceptual/components/vscode/using-vscode.md
Added some videos from PSSummit and PSConf EU - waiting to add PSConf Asia's talk that @rjmholt did... its not published yet.
Organized useful resources.
> Add videos and move blog posts under a Useful Resources

- reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Type_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Type_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Type_Operators.md
Fixes [AB#1702627](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702627) - Fixes #4524 - explain derived class better
> Fixes #4524 - explain derived class better

- reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md
- reference/6/Microsoft.PowerShell.Utility/Get-Date.md
- reference/7.0/Microsoft.PowerShell.Utility/Get-Date.md
- reference/7.1/Microsoft.PowerShell.Utility/Get-Date.md
Fixes [AB#1702885](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1702885) - Fixes #5680 - fix -Uformat example
> Fixes #5680 - fix -Uformat example

- reference/5.1/Microsoft.WsMan.Management/New-WSManInstance.md
- reference/6/Microsoft.WSMan.Management/New-WSManInstance.md
- reference/7.0/Microsoft.WSMan.Management/New-WSManInstance.md
- reference/7.1/Microsoft.WSMan.Management/New-WSManInstance.md
Fixes [AB#1703021](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1703021) - Fixes #5687 - update example 1
> Fixes #5687 - update example 1

- reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md
Related to #5656 - use real web service in example
> Related to #5656 - use real web service in example

- reference/7.0/PSDesiredStateConfiguration/Invoke-DscResource.md
- reference/7.1/PSDesiredStateConfiguration/Invoke-DscResource.md
Fixes [AB#1703287](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1703287) - Fixes #5695 - add experimental note
> Fixes #5695 - add experimental note

- reference/docs-conceptual/gallery/how-to/publishing-packages/unlisting-packages.md
Fixed readability and grammar issues, such as changing "...an package..." to "...a package..."
> fixing typos and grammar issues

- reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Special_Characters.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Special_Characters.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md
Fixes [AB#1704424](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1704424) - Fixes #5710 - explain CR character
> Fixes #5710 - explain CR character

- reference/docs-conceptual/components/vscode/using-vscode.md
Fixes [AB#1704579](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1704579) - Fixes #5706 - clarify vscode configuration
> Fixes #5706 - clarify vscode configuration

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
- reference/docs-conceptual/install/PowerShell-Core-on-ARM.md
Update Installing Powershell instructions for Windows 10 IoT
> Update Installing Powershell for Windows 10 IoT

- reference/5.1/Microsoft.PowerShell.Management/Remove-Item.md
- reference/6/Microsoft.PowerShell.Management/Remove-Item.md
- reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md
- reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md
Fixes [AB#1704580](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1704580) - Fixes #5717 - confirm docs
> Fixes #5717 - confirm docs

- reference/7.1/Microsoft.PowerShell.Utility/Get-Date.md
Fixes [AB#1705451](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1705451) - Fixes #5727 - add FromUnixTime
> Fixes #5727 - add FromUnixTime

- reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md
- reference/6/Microsoft.PowerShell.Utility/Get-Random.md
- reference/7.0/Microsoft.PowerShell.Utility/Get-Random.md
- reference/7.1/Microsoft.PowerShell.Utility/Get-Random.md
Fixes [AB#1705801](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1705801) - Fixes #3104 - random output types
> Fixes #3104 - random output types

- reference/docs-conceptual/components/vscode/How-To-Replicate-the-ISE-Experience-In-VSCode.md
- reference/docs-conceptual/toc.yml
Fixes [AB#1705773](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1705773) - Fixes #3552 - disable debug console and editorial
> Fixes #3552 - disable debug console and editorial

- reference/5.1/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/7.0/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-Expression.md
Fixes #4897 - caution use of IEX
Fixes #2679 
Fixes [AB#1705840](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1705840)
> Fixes #4897 - caution use of IEX

- reference/docs-conceptual/community/contributing/get-started-writing.md
- reference/docs-conceptual/community/contributing/powershell-style-guide.md
> Fixed typos

- reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md
Fixes [AB#1706144](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706144) - Fixes #3028 - add info about Tuple
> Fixes #3028 - add info about Tuple

- reference/5.1/Microsoft.PowerShell.Utility/Get-Runspace.md
- reference/6/Microsoft.PowerShell.Utility/Get-Runspace.md
- reference/7.0/Microsoft.PowerShell.Utility/Get-Runspace.md
- reference/7.1/Microsoft.PowerShell.Utility/Get-Runspace.md
Fixes [AB#1706169](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706169) - Fixes #3646 - add examples
> Fixes #3646 - add examples

- reference/5.1/Microsoft.PowerShell.Core/Set-StrictMode.md
- reference/6/Microsoft.PowerShell.Core/Set-StrictMode.md
- reference/7.0/Microsoft.PowerShell.Core/Set-StrictMode.md
- reference/7.1/Microsoft.PowerShell.Core/Set-StrictMode.md
Fixes [AB#1706244](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706244) - Fixes #4042 - latest strict mode
> Fixes #4042 - latest strict mode

- reference/5.1/Microsoft.PowerShell.LocalAccounts/Add-LocalGroupMember.md
Fixes [AB#1706323](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706323) - Fixes #3555 - add note about domain users
> Fixes #3555 - add note about domain users

- reference/5.1/PSReadline/Set-PSReadlineOption.md
- reference/6/PSReadLine/Set-PSReadlineOption.md
- reference/7.0/PSReadLine/Set-PSReadlineOption.md
- reference/7.1/PSReadLine/Set-PSReadlineOption.md
Fixes [AB#1706332](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706332) - Fixes #3553 - editmode
> Fixes #3553 - editmode

- reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Fixes [AB#1706522](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706522) - Fixes #5755 - correct output
> Fixes #5755 - correct output

- reference/5.1/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
- reference/5.1/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
- reference/6/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
- reference/6/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
- reference/7.0/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
- reference/7.0/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
- reference/7.1/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
- reference/7.1/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
Fixes [AB#1706503](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706503) - Fixes #3408 - content must be unicode
> Fixes #3408 - content must be unicode

- reference/docs-conceptual/developer/module/writing-help-for-windows-powershell-modules.md
Fixes [AB#1706538](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706538) - Fixes #3745 - add link to schemas
> Fixes #3745 - add link to schemas

- reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/5.1/Microsoft.PowerShell.Utility/Write-Error.md
- reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/6/Microsoft.PowerShell.Utility/Write-Error.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/7.0/Microsoft.PowerShell.Utility/Write-Error.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/7.1/Microsoft.PowerShell.Utility/Write-Error.md
Fixes [AB#1706581](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706581) - Fixes #3102 - write-error $?
> Fixes #3102 - write-error $?

- reference/docs-conceptual/gallery/getting-started.md
Fixes [AB#1706571](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706571) - Fixes #3592 - add dns names for gallery
> Fixes #3592 - add dns names for gallery

- reference/docs-conceptual/components/workflows-guide.md
Fixes [AB#1706721](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706721) - Fixes #5762 - update links and clarify support
> Fixes #5762 - update links and clarify support

- reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md
Fixes [AB#1706778](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706778) - Fixes #5765 - Inheriting interfaces in PS Classes
Fixes [AB#1706901](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706901) - Fixes #3115
> Fixes #5765 - Inheriting interfaces in PS Classes

- reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_PSModulePath.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_PSModulePath.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md
Fixes [AB#1706915](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706915) - Fixes #2419 - improve PSModulePath docs
> Fixes #2419 - improve PSModulePath docs

- reference/5.1/Microsoft.PowerShell.Core/About/about_History.md
- reference/5.1/Microsoft.PowerShell.Core/Invoke-History.md
- reference/6/Microsoft.PowerShell.Core/About/about_History.md
- reference/6/Microsoft.PowerShell.Core/Invoke-History.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_History.md
- reference/7.0/Microsoft.PowerShell.Core/Invoke-History.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_History.md
- reference/7.1/Microsoft.PowerShell.Core/Invoke-History.md
Fixes [AB#1707500](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1707500) - Fixes #5778 - document `#<tab>` history search
Fixes [AB#1707433](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1707433) - Fixes #5775 - clarify pattern match
> Fixes #5775 - clarify pattern match

- reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/7.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/7.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
Fixes [AB#1707723](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1707723) - Fixes #3583 - link to gallery requirements
> Fixes #3583 - link to gallery requirements

- reference/5.1/Microsoft.PowerShell.Core/About/about_Prompts.md
- reference/6/Microsoft.PowerShell.Core/About/about_Prompts.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Prompts.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Prompts.md
Fixes [AB#1707923](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1707923) - Fixes #5787 - fix prompt code
> Fixes #5787 - fix prompt code

- reference/5.1/Microsoft.PowerShell.Core/Enter-PSHostProcess.md
- reference/5.1/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.md
- reference/5.1/Microsoft.PowerShell.Security/Get-Credential.md
- reference/5.1/Microsoft.PowerShell.Security/Get-PfxCertificate.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Html.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/6/Microsoft.PowerShell.Security/Get-Credential.md
- reference/6/Microsoft.PowerShell.Security/Get-PfxCertificate.md
- reference/6/Microsoft.PowerShell.Utility/ConvertTo-Html.md
- reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/7.0/Microsoft.PowerShell.Security/Get-Credential.md
- reference/7.0/Microsoft.PowerShell.Security/Get-PfxCertificate.md
- reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Html.md
- reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/7.1/Microsoft.PowerShell.Security/Get-Credential.md
- reference/7.1/Microsoft.PowerShell.Security/Get-PfxCertificate.md
- reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Html.md
- reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md
Fixes [AB#1708197](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1708197) - editorial cleanup
> Fixes AB#1708197 - editorial cleanup

- reference/docs-conceptual/community/contributing/editing-cmdlet-ref.md
- reference/docs-conceptual/community/contributing/editorial-checklist.md
- reference/docs-conceptual/community/contributing/powershell-style-guide.md
I changed a few rules and clarified some formatting that was not previously mentioned.
> Update Style Guide

- reference/5.1/Microsoft.PowerShell.Core/Update-Help.md
- reference/6/Microsoft.PowerShell.Core/Update-Help.md
- reference/7.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/7.1/Microsoft.PowerShell.Core/Update-Help.md
Change wording - you can't use update-help on non-connected computers and the docs said 'can'.
> Update-Help fix type

- reference/docs-conceptual/components/web-access/authorization-rules-and-security-features-of-windows-powershell-web-access.md
Updates related to [User Story 1708364](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1708364)
Updates related to [User Story 1708364](https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1708364)
> 1708364, removed unnecessary TM tag '&trade;' from content

- reference/5.1/Microsoft.PowerShell.Utility/Start-Sleep.md
Fixes [AB#1709338](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1709338) - Fixes #5803 - error in alias
> Fixes #5803 - error in alias

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions.md
Fixes [AB#1709350](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1709350) - Fixes #5804 - fix H2 nav
> Fixes #5804 - fix H2 nav

- reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md
- reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/6/Microsoft.PowerShell.Host/Start-Transcript.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/7.0/Microsoft.PowerShell.Host/Start-Transcript.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/7.1/Microsoft.PowerShell.Host/Start-Transcript.md
Fixes [AB#1710568](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1710568) - Fixes #5817 - add $Transcript to pref vars
> Fixes #5817 - add $Transcript to pref vars

- reference/5.1/PowershellGet/Set-PSRepository.md
- reference/6/PowerShellGet/Set-PSRepository.md
- reference/7.0/PowerShellGet/Set-PSRepository.md
- reference/7.1/PowerShellGet/Set-PSRepository.md
Fixes [AB#1710597](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1710597) - Fixes #5814 - clarify scope of settings
> Fixes #5814 - clarify scope of settings

- reference/7.0/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md
Fixes [AB#1710630](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1710630) - Fixes #5724 - document new noclobber feature
> Fixes #5724 - document new noclobber feature

- reference/5.1/Microsoft.PowerShell.Utility/Wait-Event.md
- reference/6/Microsoft.PowerShell.Utility/Wait-Event.md
- reference/7.0/Microsoft.PowerShell.Utility/Wait-Event.md
- reference/7.1/Microsoft.PowerShell.Utility/Wait-Event.md
Fixes [AB#1711221](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1711221) - Fixes #5813 - update example 3
> Fixes #5813 - update example 3

- reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/6/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/7.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/7.1/Microsoft.PowerShell.Utility/Compare-Object.md
Fixes [AB#1711226](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1711226) - Fixes #5824 - compare-object example
> Fixes #5824 - compare-object example

- reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
Fixes [AB#1711458](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1711458) - Fixes #5830 - add note about path to pwsh
> Fixes #5830 - add note about path to pwsh

- reference/docs-conceptual/dsc/configurations/add-parameters-to-a-configuration.md
Fixes [AB#1711462](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1711462) - Fixes #5828 - fix array type
> Fixes #5828 - fix array type

- reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
- reference/6/Microsoft.PowerShell.Management/Start-Process.md
- reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
- reference/7.1/Microsoft.PowerShell.Management/Start-Process.md
Fixes [AB#1711467](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1711467) - Fixes #5774 - update UseNewEnvironment
> Fixes #5774 - update UseNewEnvironment

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Fixes [AB#1711587](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1711587) - Fixes #5836 - explain zips
> Fixes #5836 - explain zips

- reference/5.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
Continuation of PR#5840 - adds changes to other versions
> Fixes #5840 - continuation of previous PR

- reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
- reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
Fixes [AB#1711778](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1711778) - Fixes #5842 - add note about location of pwsh for different installs
Fixes [AB#1711779](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1711779) - Fixes #5841 - add mention of `Get-Verb`
> Fixes #5842 - Fixes #5841

- reference/7.0/PackageManagement/Get-PackageProvider.md
Typo "****"→"** **"
https://docs.microsoft.com/en-us/powershell/module/packagemanagement/get-packageprovider?view=powershell-7
> Typo "****"→"** **"

- reference/5.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
- reference/5.1/Microsoft.PowerShell.Utility/Get-TypeData.md
- reference/5.1/Microsoft.PowerShell.Utility/Remove-TypeData.md
- reference/5.1/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/6/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/6/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
- reference/6/Microsoft.PowerShell.Utility/Get-TypeData.md
- reference/6/Microsoft.PowerShell.Utility/Remove-TypeData.md
- reference/6/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
- reference/7.0/Microsoft.PowerShell.Utility/Get-TypeData.md
- reference/7.0/Microsoft.PowerShell.Utility/Remove-TypeData.md
- reference/7.0/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
- reference/7.1/Microsoft.PowerShell.Utility/Get-TypeData.md
- reference/7.1/Microsoft.PowerShell.Utility/Remove-TypeData.md
- reference/7.1/Microsoft.PowerShell.Utility/Update-TypeData.md
Fixes [AB#1712143](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1712143) - Fixes #3091 - explain how objects get members
> Fixes #3091 - explain how objects get members

- reference/docs-conceptual/toc.yml
- reference/docs-conceptual/whats-new/experimental-features.md
Fixes [AB#1712857](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1712857) - Fixes #5848 - add docs for experimental features
Closes #4989
> Fixes #5848 - add docs for experimental features

- reference/5.1/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md
- reference/docs-conceptual/developer/cmdlet/how-to-validate-parameter-input.md
- reference/docs-conceptual/dsc/overview/DscForEngineers.md
Customer had some confusion about what would happen if multiple meta mofs were available to apply to a machine. Documentation was updated for MD formatting and to add a note to address issue
Fixes #5783 
Fixes [AB#1713210](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1713210)
> FIXES #5783 Multiple meta mofs

- reference/5.1/Microsoft.PowerShell.Diagnostics/Export-Counter.md
Fixes [AB#1713476](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1713476) - Fixes #5858 - fix maxsize unit scale
> Fixes #5858 - fix maxsize unit scale

- .openpublishing.redirection.json
Fixes [AB#1715009](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1715009) - Fixes #5866 - add redirects to about_pwsh
> Fixes #5866 - add redirects to about_pwsh

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Fixes [AB#1715030](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1715030) - Fixes #5862 - fix Fedora install
> Fixes #5862 - fix Fedora install

- reference/5.1/Microsoft.PowerShell.Core/About/about_CimSession.md
- reference/6/Microsoft.PowerShell.Core/About/about_CimSession.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_CimSession.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_CimSession.md
Fixes [AB#1715045](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1715045) - Fixes #5701 - add link to CDXML docs
> Fixes #5701 - add link to CDXML docs

- .openpublishing.redirection.json
- reference/docs-conceptual/community/2020-Q1.md
- reference/docs-conceptual/community/2020-Q2.md
- reference/docs-conceptual/community/community-support.md
- reference/docs-conceptual/community/community-update.yml
- reference/docs-conceptual/community/hall-of-fame.md
- reference/docs-conceptual/toc.yml
- reference/docs-conceptual/whats-new/experimental-features.md
Fixes [AB#1713286](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1713286)
> [WIP] Update monthly community pages

- reference/5.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
Fixes [AB#1717782](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1717782) - Fixes #5882 - add new operators
> Fixes #5882 - add new operators

- reference/5.1/Microsoft.PowerShell.Management/Get-EventLog.md
> Adding Note that Get-EventLog is deprecated

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Fixes [AB#1718008](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1718008) - Fixes #5885 - add note about simple syntax
> Fixes #5885 - add note about simple syntax

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Clarify the boolean argument defaults.
> Updates to PR5885

- reference/module/index.md
Fixes [AB#1718828](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1718828)
> Updating quick filters for Module Browser

- reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md
Fixes [AB#1719055](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1719055) - Fixes #5903 - fix typo
> Fixes #5903 - fix typo

- reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/7.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/7.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
Fixes [AB#1719466](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1719466) - Fixes #5908 - add warning
> Fixes #5908 - add warning

- reference/docs-conceptual/developer/hosting/creating-remote-runspaces.md
Small typo fix for Uri class name.
> Change Uri class name

- reference/5.1/Microsoft.PowerShell.Core/About/about_CimSession.md
- reference/6/Microsoft.PowerShell.Core/About/about_CimSession.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_CimSession.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_CimSession.md
Fixes [AB#1720265](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1720265) - Fixes #5700 - throttle limits for CDXML
> Fixes #5700 - throttle limits for CDXML

- reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md
Fixes [AB#1720528](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1720528) Fixes #5861 - update kerberos 2-hop doc
> Fixes #5861 - update kerberos 2-hop doc

- reference/docs-conceptual/toc.yml
> Update TOC for SDK content

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
- reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
Minor typos found in two files. Fixes Typos
Fixes #5924 
Fixes #5925 
Fixes [AB#1721103](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1721103)
> Fixes Typos

- reference/7.1/PSReadLine/Set-PSReadlineOption.md
Sync docs changes from source repo
> Update Set-PSReadlineOption for predictions

- reference/7.1/PSReadLine/About/about_PSReadLine.md
- reference/7.1/PSReadLine/Get-PSReadlineKeyHandler.md
Pulled in the changes from latest update by @daxian-dbw
> Sync doc changes from PSReadLine source code

- reference/7.1/PSReadLine/About/about_PSReadLine.md
- reference/7.1/PSReadLine/Get-PSReadlineKeyHandler.md
- reference/7.1/PSReadLine/Set-PSReadlineOption.md
Update PSReadLine docs with the most recent changes.
This is a follow-up PR to #5931
> Update PSReadLine docs

- reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md
- reference/6/Microsoft.PowerShell.Utility/Get-FileHash.md
- reference/7.0/Microsoft.PowerShell.Utility/Get-FileHash.md
- reference/7.1/Microsoft.PowerShell.Utility/Get-FileHash.md
Fixes [AB#1721386](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1721386) - Fixes #5939 - fix incorrect hash value
> Fixes #5939 - fix incorrect hash value

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Remove intent to service information
> Remove intent to service information

- reference/5.1/Microsoft.PowerShell.Core/Get-Job.md
- reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md
- reference/6/Microsoft.PowerShell.Core/Get-Job.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Telemetry.md
- reference/7.0/Microsoft.PowerShell.Core/Get-Job.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Telemetry.md
- reference/7.1/Microsoft.PowerShell.Core/Get-Job.md
- reference/docs-conceptual/developer/cmdlet/parameter-attribute-declaration.md
- reference/docs-conceptual/developer/cmdlet/validatecount-attribute-declaration.md
- reference/docs-conceptual/developer/cmdlet/validatelength-attribute-declaration.md
- reference/docs-conceptual/developer/cmdlet/validaterange-attribute-declaration.md
- reference/docs-conceptual/developer/format/defining-conditions-for-displaying-data.md
- reference/docs-conceptual/developer/format/defining-selection-sets.md
- reference/docs-conceptual/developer/provider/accessdbprovidersample01.md
- reference/docs-conceptual/developer/provider/accessdbprovidersample02.md
- reference/docs-conceptual/developer/provider/accessdbprovidersample03.md
- reference/docs-conceptual/developer/provider/accessdbprovidersample05.md
- reference/docs-conceptual/developer/provider/accessdbprovidersample06.md
- reference/docs-conceptual/developer/webservices/creating-a-management-odata-web-service.md
- reference/docs-conceptual/gallery/how-to/getting-support/bootstrapping-nuget.md
> fix: MD005/list-indent

- .markdownlint.json
- reference/5.1/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md
- reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Troubleshooting.md
- reference/6/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
- reference/docs-conceptual/developer/format/how-to-create-a-formatting-file-format-ps1xml.md
- reference/docs-conceptual/dsc/resources/authoringResourceClass.md
- reference/docs-conceptual/dsc/resources/authoringResourceMOF.md
- reference/docs-conceptual/dsc/resources/resources.md
- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md
> fix: MD033/no-inline-html

- reference/7.1/PSReadLine/About/about_PSReadLine.md
Update the key bindings in about topic for PSReadLine.
> Update the about topic of PSReadLine

- reference/docs-conceptual/gallery/installing-psget.md
Fixes [AB#1722591](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1722591) - Fixes #5915 - psget for PS3/4
> Fixes #5915 - psget for PS3/4

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> Updated url to 7.0.1, for installing generic linux binaries

- reference/7.1/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
Fixes [AB#1723365](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1723365) - Fixes #5972 - signed hex literals
> Fixes #5972 - signed hex literals

- reference/7.1/Microsoft.PowerShell.Utility/Get-Date.md
Fixes [AB#1723370](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1723370) - Fixes #5976 - add -AsUTC to Get-Date
> Fixes #5976 - add -AsUTC to Get-Date

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
Fixes [AB#1723433](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1723433) - Fixes #5995 - update install for 7.0.1 release
> Fixes #5995 - update install for 7.0.1 release

- reference/7.0/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/7.1/Microsoft.PowerShell.Utility/Format-Hex.md
Multiple Changes:
- Fixes Formatting in Example 2
- Updates Example 3 to include Boolean
- Corrects information about `-Encoding`
- Adds **BigEndianUTF32** to 7.1 `-Encoding`
Fixes #5977 
Fixes [AB#1723493](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1723493)
> Fixes #5977 Updates Format-Hex

- reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/7.0/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/7.1/Microsoft.PowerShell.Utility/Export-Clixml.md
Fixes [AB#1723557](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1723557) - Fixes #5997 - securestring encoding in CLIXML
> Fixes #5997 - securestring encoding in CLIXML

- reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/6/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Switch.md
Fixes [AB#1723728](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1723728) - Fixes #6001 - use closed regex
> Fixes #6001 - use closed regex

- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md
A minor update to improve readability and correct a typo.
- [] Fundamental conceptual articles
- [ x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ x] PR has a meaningful title
- [ x] PR is targeted at the _staging_ branch
- [ x] All relevant versions updated
- [ x] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [ x] This PR is ready to merge and is not **Work in Progress**
[contrib]: https://docs.microsoft.com/powershell/scripting/community/contribu …
> Minor update to What's new in PowerSHell 7

- .github/ISSUE_TEMPLATE/Documentation_Issue.md
- .github/ISSUE_TEMPLATE/New_Document_Request.md
- .openpublishing.redirection.json
- reference/docs-conceptual/install/Installing-PowerShell.md
Fixes [AB#1723991](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1723991) - Fixes #6015 - broken links in redirection
Fixes [AB#1723992](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1723992) - Fixes #6016 - broken links in redirection
> Fixes #6015 - broken links in redirection

- reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
Fixes [AB#1669514](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669514) - Fixes #6013 - add Math.Round
> Fixes #6013 - add Math.Round

- .openpublishing.redirection.json
> Bypass redirects to directories, etc

- ci-steps.yml
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Updates instructions to update powershell. Previous command would update all packages available to update. New command will only update powershell
Fixes #6014 
Fixes [AB#1724908](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1724908)
> Fixes #6014 Updates upgrade powershell instructions in linux

- reference/5.1/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md
- reference/6/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md
- reference/7.0/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md
- reference/7.1/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md
Example in Get-ItemPropertyValue cuase faulty output. Wrap input in quotes to fix.
Fixes #6035 
Fixes [AB#1724862](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1724862)
> Fixes #6035 updates Get-ItemProperty

- reference/docs-conceptual/dsc/reference/resources/windows/registryResource.md
The existing example said it was creating a key, but the example creates a key and also creates a value. Reworded the example to better describe what it does. Then added an example that only creates a key.
> Corrected and added another example for Registry resource

- reference/docs-conceptual/learn/deep-dives/everything-about-exceptions.md
Fixes [AB#1729454](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1729454) - Fixes #6060 - approved verb
> Fixes #6060 - approved verb

- reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fixes [AB#1730279](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1730279) - Fixes #5653 - OutFile is literal path
> Fixes #5653 - OutFile is literal path

- reference/5.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/6/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/7.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/7.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
Fixes [AB#1730325](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1730325) - Fixes #6059 - update dynamic params
Removed Certificate provider parameters from v6/v7
- DNSName
- DocumentEncryptionCert
- EKU
- ExpiringInDays
- SSLServerAuthentication
These were added back in v7.1.
> Fixes #6059 - update dynamic params

- reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/6/Microsoft.PowerShell.Core/About/about_Break.md
- reference/6/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/6/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Break.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Break.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Trap.md
Fixes [AB#1730586](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1730586) - Fixes #5991 - `trap` and `switch` are missing
Fixes [AB#1730587](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1730587) - Fixes #5992 - `trap` is missing as a statement to which `break` applies; `trap`-related example is flawed
Fixes [AB#1730588](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1730588) - Fixes #5994 - Warn of the pitfalls of `break` and `continue` uses outside constructs that directly support them
- If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of …
> Explain break/continue behavior

- reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
> Sync changes from PR#6073

- reference/5.1/Microsoft.PowerShell.Management/Test-Path.md
- reference/6/Microsoft.PowerShell.Management/Test-Path.md
- reference/7.0/Microsoft.PowerShell.Management/Test-Path.md
- reference/7.1/Microsoft.PowerShell.Management/Test-Path.md
**LiteralPath** parameter info is updated for clarity. 
Fixes #6081 
Fixes [AB#1731402](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1731402)
> FIXES 6081 - Updates Test-Path

- reference/module/index.md
Current version of AzPS module was updated and quick filter link was not showing due to the out of date version in the metadata.
No issues linked
> Update Moduel Browser Page Quick Filter

- .openpublishing.redirection.json
Title says it all. 
No linked issues
> Adds redirect for COmmunity digital art

- reference/5.1/Microsoft.PowerShell.Core/About/about_Splatting.md
- reference/6/Microsoft.PowerShell.Core/About/about_Splatting.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Splatting.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Splatting.md
Fixes Typo and updates formatting for a note
Fixes #6107 
Fixes [AB#1733245](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1733245)
> FIXES #6107

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/docs-conceptual/community/community-update.yml
- reference/docs-conceptual/developer/cmdlet/cmdlet-overview.md
- reference/docs-conceptual/learn/Glossary.md
- reference/docs-conceptual/learn/more-powershell-learning.md
Fixes [AB#1733081](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1733081) - Fixes #6105 - Official definition of `cmdlet`
> Fixes #6105 - Official definition of `cmdlet`

- reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md
This change addresses Issue #5770.
These changes are for ForEach-Object -Parallel and affect both 7.0 and 7.1 versions.
> Add terminating and non-terminating error information to ForEach-Object -Parallel parameter set

- reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md
- reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md
Minor edits and sync changes to v7.
> Sync changes from PR#6118

- reference/docs-conceptual/dsc/managing-nodes/metaConfig.md
Customer noticed, that information in note about bahavior in resetting the **ConfigurationModeFrequescyMins**. Clarifies behavior. 
Updates for formatting issues.
Fixes #6127 
Fixes [AB#1736821](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1736821)
> FIXES #6127 - Updates metaConfig

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
adding 
- PSReleaseTools by Jeff Hicks
- WinGet
> More installations methods for PowerShell 7 / Preview

- reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Corrected duplicate word typo
Conceptual doc
> Corrected typo

- reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
- reference/6/Microsoft.PowerShell.Management/Start-Process.md
- reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
- reference/7.1/Microsoft.PowerShell.Management/Start-Process.md
Fixes [AB#1738149](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1738149) - Fixes #6141 - update WorkingDirectory
> Fixes #6141 - update WorkingDirectory

- reference/6/Microsoft.PowerShell.Management/New-Item.md
- reference/7.0/Microsoft.PowerShell.Management/New-Item.md
- reference/7.1/Microsoft.PowerShell.Management/New-Item.md
Fixes [AB#1738167](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1738167) - Fixes #6143 - symlinks to folders
> Fixes #6143 - symlinks to folders

- reference/7.1/Microsoft.PowerShell.Utility/Test-Json.md
Document `SchemaFile` parameter for the `Test-Json` cmdlet.
See https://github.com/PowerShell/PowerShell/pull/11934 for details
Fixes #6134 
> Test-Json: document SchemaFile parameter

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Fixes [AB#1738546](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1738546) - Fixes #6161 - update to 7.0.2.
> Fixes #6161 - update to 7.0.2

- reference/docs-conceptual/learn/ps101/01-getting-started.md
Fixes [AB#1738532](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1738532) - Fixes #6158 - fix broken link
> Fixes #6158 - fix broken link

- reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Html.md
clarified short description to be a bit more specific
> fix v7.0 explanation of what ConvertTo-Html does

- reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
- reference/6/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
Fixes [AB#1738357](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1738357) - Fixes #6153 - explain parameter help comments
> Fixes #6153 - explain parameter help comments

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
> Additional info to HelpMessage Parameter Attribute RE interaction with Comment Based Help

- reference/5.1/Microsoft.PowerShell.Security/Set-Acl.md
- reference/6/Microsoft.PowerShell.Security/Set-Acl.md
- reference/7.0/Microsoft.PowerShell.Security/Set-Acl.md
- reference/7.1/Microsoft.PowerShell.Security/Set-Acl.md
Add 2 new examples to Set-Acl. One example to show how to disable inheritance, and one example to show how to give a group permissions.
> Add additional examples to Set-Acl

- reference/docs-conceptual/learn/ps101/01-getting-started.md
Added about_Hash_Tables to recommended reading section based on feedback.
conceptual doc update
> Added about hash tables to recommended reading

- reference/5.1/Microsoft.PowerShell.Security/Set-Acl.md
- reference/6/Microsoft.PowerShell.Security/Set-Acl.md
- reference/7.0/Microsoft.PowerShell.Security/Set-Acl.md
- reference/7.1/Microsoft.PowerShell.Security/Set-Acl.md
Updates Set-Acl doc for current md formatting and style guidelines.
no linked issues
> Updates formatting for Set-Acl

- reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md
- reference/docs-conceptual/learn/deep-dives/everything-about-if.md
- reference/docs-conceptual/samples/Multiple-selection-List-Boxes.md
- reference/docs-conceptual/windows-powershell/Starting-the-Windows-PowerShell-2.0-Engine.md
Fixing broken links from OPS report
> Fixing OPS broken links

- reference/7.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
> Grammar update about_Hash_Tables.md

- reference/docs-conceptual/dsc/configurations/write-compile-apply-configuration.md
Fixes [AB#1739212](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1739212) - Fixes #6176 - add note to compile step
> Fixes #6176 - add note to compile step

- reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md
Translator has reported possible source content issue. 
Affected Line: 955
Description: "depreciated" should be "deprecated"
> M50835 - Fixing Typo

- reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
Fixes [AB#1739549](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1739549) - Fixes #6180 - fix description of pattern
> Fixes #6180 - fix description of pattern

- reference/module/index.md
Updated PowerShell module browser to Az PowerShell version 4.3.0
Not a reference doc update.
> Updated module browser to Az PowerShell 4.3.0

- reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
Updates SSH Remoting in PowerShell Core for multiple information items
Fixes #6112 
Fixes [AB#1733550](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1733550)
> Fixes #6112 - Updates SSH-Remoting-in-PowerShell-Core

- reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md
Translator has reported possible source content issue. 
Affected Line: 662
Description: "operation" should be "operator"
> M50834 - Fixing Typo

- reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/6/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/7.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/7.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
Fixes [AB#1740372](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1740372) - Fixes #6194 - fix session name variables
> Fixes #6194 - fix session name variables

- reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md
Update for #6056 - how to use . notation
> Update for #6056 - how to use . notation

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Fixes [AB#1687590](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1687590) - Fixes #5519 - add note that MSIX not supported
> Fixes #5519 - add note that MSIX not supported

- reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fixes [AB#1741220](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1741220) - update proxy info
> Fixes AB#1741220 - update proxy info

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
Fixes [AB#1741244](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1741244) - Fixes #6202 - add notes to install articles
> Fixes #6202 - add notes to install articles

- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fixes [AB#1741565](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1741565) - Fixes #6208 - update example 6
> Fixes #6208 - update example 6

- reference/docs-conceptual/dev-cross-plat/Writing-Portable-Modules.md
Documentation should not contain cmdlet aliases
Fixes #6207 
Fixes [AB#1741606](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1741606)
> change replace alias

- reference/5.1/PSReadLine/Set-PSReadLineOption.md
Fixes [AB#1741792](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1741792) - Fixes #6212 - replace escape character in examples
> Fixes #6212 - replace escape character in examples

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md
Replace "[inbox](https://www.dictionary.com/browse/inbox?s=t)" and "in-box". For a very long time, I thought "inbox modules" were modules for managing Microsoft Messaging Services, and Microsoft Outlook! As it turns out, these words are Microsoft-speak for what the rest of the English-speaking world calls "[built-in](https://www.dictionary.com/browse/built-in?s=t)". And while Microsoft software products are no longer sold in boxes, they are still compiled and [built](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/build).
- If the PR is work in progress, please add the prefix `WIP:` or …
> Replaced misleading words

- reference/5.1/PSWorkflow/About/about_Checkpoint-Workflow.md
- reference/5.1/PSWorkflow/About/about_Foreach-Parallel.md
- reference/5.1/PSWorkflow/About/about_InlineScript.md
- reference/5.1/PSWorkflow/About/about_Sequence.md
- reference/5.1/PSWorkflow/About/about_Suspend-Workflow.md
- reference/5.1/PSWorkflow/About/about_Workflows.md
Fixes [AB#1741929](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1741929) - fix broken link per report
> Fixes AB#1741929 - fix broken link per report

- reference/5.1/PSReadLine/Get-PSReadLineOption.md
- reference/5.1/PSReadLine/Set-PSReadLineOption.md
- reference/6/PSReadLine/Get-PSReadlineOption.md
- reference/6/PSReadLine/Set-PSReadlineOption.md
- reference/7.0/PSReadLine/Get-PSReadLineOption.md
- reference/7.0/PSReadLine/Set-PSReadLineOption.md
- reference/7.1/PSReadLine/Get-PSReadLineOption.md
- reference/7.1/PSReadLine/Set-PSReadLineOption.md
Fixes [AB#1742464](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1742464) - Fixes #6219 - fix escapes and switchparameters
> Fixes #6219 - fix escapes and switchparameters

- reference/docs-conceptual/community/2020-Q2.md
- reference/docs-conceptual/community/hall-of-fame.md
Fixes [AB#1741882](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1741882) - June update to whats new
> Fixes AB#1741882 - June update to whats new

- reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md
Fixes [AB#1744405](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1744405) - Fixes #6242 - return index not value
> Fixes #6242 - return index not value

- reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md
- reference/index.yml
Fixes [AB#1745830](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1745830) - Fixes #6246 - update Hub page links
> Fixes #6246 - update Hub page links

- reference/5.1/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
- reference/5.1/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
- reference/6/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
- reference/6/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
- reference/7.0/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
- reference/7.0/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
- reference/7.1/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
- reference/7.1/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
This command decrypts encrypted strings. Accordingly, it must be given the same keys that were used to encrypt them.  The length of a secure string is measured in code points, not in bytes.  I also mentioned Read-Host.  I added a note about problematic characters in passwords; if accepted, it should be copied to ConvertFrom as well because it is even more relevant there.  Backport pending acceptance.
[contrib]: https://docs.microsoft.com/powershell/scripting/community/contrib …
> Correct the description of key parameters

- reference/docs-conceptual/dsc/resources/authoringResource.md
- reference/docs-conceptual/dsc/resources/authoringResourceClass.md
- reference/docs-conceptual/dsc/resources/authoringResourceComposite.md
- reference/docs-conceptual/dsc/resources/authoringResourceMOF.md
- reference/docs-conceptual/dsc/resources/authoringResourceMofCS.md
- reference/docs-conceptual/dsc/resources/authoringResourceMofDesigner.md
- reference/docs-conceptual/dsc/resources/get-test-set.md
- reference/docs-conceptual/dsc/resources/resourceAuthoringChecklist.md
- reference/docs-conceptual/dsc/resources/resources.md
- reference/docs-conceptual/dsc/resources/singleInstance.md
Updates formatting for DSC resource authoring section
Formatting was updated for different issue that was cut. No sense in wasting the formatting work done. 
No Links
> Updates formatting for DSC resource authoring section

- reference/docs-conceptual/developer/ets/errors-exceptions.md
- reference/docs-conceptual/developer/ets/members.md
- reference/docs-conceptual/developer/ets/membersets.md
- reference/docs-conceptual/developer/ets/methods.md
- reference/docs-conceptual/developer/ets/overview.md
- reference/docs-conceptual/developer/ets/properties.md
- reference/docs-conceptual/developer/ets/typeconverters.md
- reference/docs-conceptual/toc.yml
Fixes [AB#1098052](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1098052) - Fixes #1208 - add ETS docs
> Fixes #1208 - add ETS docs

- reference/docs-conceptual/learn/deep-dives/everything-about-string-substitutions.md
> remove redundant word

- reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
I removed examples for the **cast notation** from the section describing the **cast operator** and added examples for the **cast operator**.  I added a note about **cast notation**.
> Improve documentation about the cast operator.

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Customer noticed that the winget installation instructions didn't work as written. This PR remedies this.
Fixes #6262 
Fixes [AB#1747715](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1747715)
> Fixes #6262] Updates installing PowerShell with Winget

- reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
> Minor: Punctuation fix

- reference/7.1/Microsoft.PowerShell.Management/Split-Path.md
Fixes [AB#1748433](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1748433) - Fixes #6273 - update parameter sets
> Fixes #6273 - update parameter sets

- reference/6/Microsoft.PowerShell.Core/Update-Help.md
- reference/7.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/7.1/Microsoft.PowerShell.Core/Update-Help.md
Fixes [AB#1748315](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1748315) - Fixes #6271 - add note about UICulture
> Fixes #6271 - add note about UICulture

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
Fixes [AB#1748442](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1748442) - Fixes #6270 - add note about MacPorts
> Fixes #6270 - add note about MacPorts

- reference/module/index.md
Updated azps quick filter version to 4.4.0
> Updated azps quick filter version to 4.4.0

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
fixes syntax for installing powershell with winget. Updated syntax works more consistently. 
Fixes #6285 
Fixes [AB#1749460](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1749460)
> Updates syntax for winget

- reference/5.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md
- reference/6/Microsoft.PowerShell.Core/Enable-PSRemoting.md
- reference/7.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md
- reference/7.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md
Fixes [AB#1749520](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1749520) - Fixes #6132 - add note about FW rule name in Ex3
> Fixes #6132 - add note about FW rule name in Ex#3

- reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-applyconfiguration.md
- reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-disabledebugconfiguration.md
- reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager.md
- reference/docs-conceptual/dsc/reference/resources/packagemanagement/PackageManagementDscResource.md
- reference/docs-conceptual/dsc/reference/resources/packagemanagement/PackageManagementSourceDscResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/archiveResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/environmentResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/fileResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/groupResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/groupSetResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/logResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/packageResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/processSetResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/registryResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/serviceResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/serviceSetResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/userResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/waitForAllResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/waitForAnyResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/waitForSomeResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/windowsFeatureSetResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/windowsOptionalFeatureResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/windowsOptionalFeatureSetResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/windowsPackageCabResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/windowsProcessResource.md
- reference/docs-conceptual/dsc/reference/resources/windows/windowsfeatureResource.md
Working Item to Update DSC reference Content
> Updates first set of DSC Reference Content

- reference/5.1/Microsoft.PowerShell.Archive/Expand-Archive.md
- reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md
- reference/7.0/Microsoft.PowerShell.Archive/Expand-Archive.md
- reference/7.1/Microsoft.PowerShell.Archive/Expand-Archive.md
Fixes [AB#1750075](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1750075) - Fixes #6295 - update destinationpath
> Fixes #6295 - update destinationpath

- reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
Fixes [AB#1750083](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1750083) - Fixes #6294 - fix typo in example
> Fixes #6294 - fix typo in example

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Fixes [AB#1750296](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1750296) - Fixes #6302 - update winget instructions
> Fixes #6302 - update winget instructions

- reference/7.0/Microsoft.WSMan.Management/Test-WSMan.md
> Removes empty bullet in Test-WSMAN Doc

- ci-steps.yml
> Remove Pester 5 if it exists

- .openpublishing.publish.config.json
Preview page: https://review.docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/New-Object?view=powershell-6&branch=qinezh-patch-1#parameters
> Update openpublishing config

- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
- reference/7.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/7.1/Microsoft.PowerShell.Core/Get-Help.md
Describe how `Get-Help` handles command aliases.
I believe handling command aliases is a known and supported feature and it has not been documented.
> About help for command aliases

- reference/5.1/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/5.1/Microsoft.PowerShell.Management/Stop-Computer.md
- reference/6/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/6/Microsoft.PowerShell.Management/Stop-Computer.md
- reference/7.0/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/7.0/Microsoft.PowerShell.Management/Stop-Computer.md
- reference/7.1/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/7.1/Microsoft.PowerShell.Management/Stop-Computer.md
Adds information about privilege requirements for stop and start-computer
Fixes #6335 
Fixes [AB#1751942](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1751942)
> [Fixes #6335] Updates Restart-Computer and Stop-Computer

- reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md
- reference/6/Microsoft.PowerShell.Core/About/about_Redirection.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Redirection.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Redirection.md
Fixes [AB#1752013](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1752013) - Fixes #6326 - add note about Action preferences
> Fixes #6326 - add note about Action preferences

- reference/5.1/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
- reference/6/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
> Not all language statements have separate articles

- reference/5.1/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
- reference/6/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
Fixes [AB#1752481](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1752481) - Address concerns in #6347
> Address concerns in #6347

- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
- reference/7.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/7.1/Microsoft.PowerShell.Core/Get-Help.md
Document that `Get-Help` may be used to search for any text, not necessarily a word.
The current documentation implies that you can only search for words in article content, like there were some index of words to speed up searching.  This is not the case: search is slow but any text works.
In particular, the following call gives you the desired result:
```powershell
HELP "`nEXIT`r" -S
````
[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overv …
> Get-Help: you can search for any text

- .openpublishing.redirection.json
Replaces urls with site relative links in redirect json
No links
> Replaces URLs with SIte relative links

- reference/7.0/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
- reference/7.1/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
Fixes [AB#1753665](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1753665) - Fixes #6367 -  new parameter added in v7
> Fixes #6367 -  new parameter added in v7

- reference/7.1/Microsoft.PowerShell.Utility/Register-EngineEvent.md
The code is so wide that GitHub needs a horizontal scroller.
> Wrap wide example code

- reference/5.1/Microsoft.PowerShell.Management/Pop-Location.md
- reference/5.1/Microsoft.PowerShell.Management/Push-Location.md
- reference/6/Microsoft.PowerShell.Management/Pop-Location.md
- reference/6/Microsoft.PowerShell.Management/Push-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Pop-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Push-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Pop-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Push-Location.md
- Add empty lines between list items for PlatyPS to render them correctly
- Bring  `Push-Location` and `Pop-Location` **Notes** sections to consistency
> Fix formatting issues in Push-Location.md and Pop-Location.md

- reference/docs-conceptual/samples/Working-With-Files-Folders-and-Registry-Keys.md
Fixes improper character encoding and updates example to be more relevant.
Fixes #6373 
Fixes [AB#1754149](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1754149)
> [Fixes #6373] Updates Working-with-files-folders-and-registry-keys

- reference/7.1/Microsoft.PowerShell.Core/About/about_Pwsh.md
Fixes [AB#1754501](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1754501) - Fixes #6386 -  update -inp parameter
> Fixes #6386 -  update -inp parameter

- reference/docs-conceptual/how-to-use-docs.md
Fixes [AB#1754483](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1754483) - Fixes #6384 - add link to syntax article
> Fixes #6384 - add link to syntax article

- reference/docs-conceptual/samples/Working-With-Files-Folders-and-Registry-Keys.md
> Build report cleanup for 2020-07-29

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
Fixes [AB#1754986](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1754986) - Fixes #6392 - update versions in setup docs
> Fixes #6392 - update versions in setup docs

- reference/7.0/Microsoft.PowerShell.Core/About/about_If.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_If.md
Add more complex example for the ternary operator in about_If.md.
> Add more complex example for the ternary operator

- reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
- reference/6/Microsoft.PowerShell.Core/About/about_Signing.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md
Fixes [AB#1755608](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1755608) - Fixes #6402 - add UTF-8 encoding requirement
> Fixes #6402 - add UTF-8 encoding requirement

- reference/5.1/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
- reference/6/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
1. Removed a lot of stuff regarding `ForEach` and `ForEach-Object` that does not belong here at all.
2. Fixed incorrect and misleading terminology.
3. Improved presentation.
4. Added an example of a method call.
5. Added a very relevant link.
> Remove irrelevant stuff, improve wording

- reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
- reference/6/Microsoft.PowerShell.Management/Start-Process.md
- reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
- reference/7.1/Microsoft.PowerShell.Management/Start-Process.md
Clarifies **ArgumentList** parameter behavior
Fixes #6410 
Fixes [AB#1756109](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1756109)
> [Fixes #6410] Updates Start-Process

- reference/5.1/Microsoft.PowerShell.Management/Pop-Location.md
- reference/5.1/Microsoft.PowerShell.Management/Push-Location.md
- reference/6/Microsoft.PowerShell.Management/Pop-Location.md
- reference/6/Microsoft.PowerShell.Management/Push-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Pop-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Push-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Pop-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Push-Location.md
- Make **StackName** parameter name bold
- Remove quotes around "stack" in Push-Location.md (as it is in Pop-Location.md)
- Break a long line.
- Remove duplicate `PowerShell lets you store provider locations in location stacks.` sentence.
- Remove boldness from **Location** in Pop-Location.md (as it is in Push-Location.md)
- Add links to **about_Aliases.md** and **about_Providers.md** …
> Fix Push-Location.md and Pop-Location.md

- reference/5.1/PowershellGet/Install-Module.md
- reference/6/PowerShellGet/Install-Module.md
- reference/7.0/PowerShellGet/Install-Module.md
- reference/7.1/PowerShellGet/Install-Module.md
Related to https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6414
> Update output type

- reference/docs-conceptual/samples/Appendix-1---Compatibility-Aliases.md
Fixes [AB#1756490](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1756490) - Fixes #6423 - add echo to list of aliases
> Fixes #6423 - add echo to list of aliases

- reference/docs-conceptual/samples/Working-with-Registry-Entries.md
> Fix fragment in Working-with-Registry-Entries.md

- reference/5.1/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/6/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
> Remove obsolete section about PowerShell ISE

- reference/5.1/Microsoft.PowerShell.Core/Update-Help.md
- reference/6/Microsoft.PowerShell.Core/Update-Help.md
- reference/7.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/7.1/Microsoft.PowerShell.Core/Update-Help.md
The previous information was self-contradictory.
> Improve the information about updating off-line

- reference/5.1/Microsoft.PowerShell.Management/Pop-Location.md
- reference/5.1/Microsoft.PowerShell.Management/Push-Location.md
- reference/6/Microsoft.PowerShell.Management/Pop-Location.md
- reference/6/Microsoft.PowerShell.Management/Push-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Pop-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Push-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Pop-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Push-Location.md
- Add `about_Aliases` and `about_Providers` links to `Related Links` section
- Enclose empty string (`""`) in backticks 
- Reformat long lines
> Add links to the Related Links and formatting fixes in Push-Location.md and Pop-Location.md

- reference/5.1/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/6/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
Fixes [AB#1756919](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1756919) - Editorial clean up of about topic and a few minor corrections.
> Editorial cleanup

- reference/docs-conceptual/community/contributing/pull-requests.md
- reference/docs-conceptual/dev-cross-plat/resolving-dependency-conflicts.md
- reference/docs-conceptual/dev-cross-plat/vscode/How-To-Replicate-the-ISE-Experience-In-VSCode.md
- reference/docs-conceptual/dev-cross-plat/vscode/Using-VSCode-for-Remote-Editing-and-Debugging.md
- reference/docs-conceptual/dev-cross-plat/vscode/using-vscode.md
- reference/docs-conceptual/developer/cmdlet/cmdlet-parameter-sets.md
- reference/docs-conceptual/dsc/configurations/import-dscresource.md
- reference/docs-conceptual/dsc/overview/authoringAdvanced.md
- reference/docs-conceptual/dsc/pull-server/enactingConfigurations.md
- reference/docs-conceptual/dsc/pull-server/package-upload-resources.md
- reference/docs-conceptual/dsc/pull-server/secureMOF.md
- reference/docs-conceptual/dsc/resources/get-test-set.md
- reference/docs-conceptual/dsc/resources/resources.md
- reference/docs-conceptual/gallery/concepts/publishing-guidelines.md
- reference/docs-conceptual/gallery/faqs.md
- reference/docs-conceptual/gallery/how-to/managing-profile/creating-APIkeys.md
- reference/docs-conceptual/gallery/how-to/managing-profile/managing-account.md
- reference/docs-conceptual/gallery/how-to/working-with-packages/manual-download.md
- reference/docs-conceptual/how-to-use-docs.md
- reference/docs-conceptual/learn/ps101/01-getting-started.md
- reference/docs-conceptual/samples/Creating-Get-WinEvent-queries-with-FilterHashtable.md
- reference/docs-conceptual/windows-powershell/wmf/whats-new/DSC-improvements.md
Fixes [AB#1757084](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1757084) - update alt-text for images
> update alt-text for images

- reference/docs-conceptual/how-to-use-docs.md
- Remove `v` from `Windows PowerShell v5.1`.
- Update `$PSVersionTable.PSVersion` output to current (Windows 10 2004) version.
- Break a log line.
> Small fixes to how-to-use-docs.md

- reference/module/index.md
Updated Az PowerShell module quick filter to reflect most recent version.
> Updated azps quick filter to latest version

- reference/docs-conceptual/dev-cross-plat/vscode/understanding-file-encoding.md
Fixes [AB#1757594](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1757594) - Fixes #6442 - encoding clarifications
> Fixes #6442 - encoding clarifications

- reference/6/Microsoft.PowerShell.Utility/Add-Type.md
- reference/7.0/Microsoft.PowerShell.Utility/Add-Type.md
- reference/7.1/Microsoft.PowerShell.Utility/Add-Type.md
Fixes [AB#1757873](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1757873) - Fixes #6422 - no GAC in PS Core
> Fixes #6422 - no GAC in PS Core

- reference/5.1/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
- reference/6/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
Fixes [AB#1758146](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1758146) - Fixes #3383 - create about_calculated_properties
> Fixes #3383 - create about_calculated_properties

- reference/7.1/Microsoft.PowerShell.Security/Get-Credential.md
Reverts the change made in #6355 
The code change that were documented in #6355 were backed out.
> Reverts #6355 - remove changes

- reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Updates Variable casings and minor formatting
Fixes #6460 
Fixes [AB#1758868](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1758868)
> Updates and formatting

- reference/5.1/Microsoft.PowerShell.Management/Set-Location.md
- reference/6/Microsoft.PowerShell.Management/Set-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Set-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Set-Location.md
Bring **Set-Location.md** Common Parameters section to the common format as of #6462.
> Bring Set-Location.md Common Parameters section to the common format

- reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
Clarifies bahavior when execution plicies in all scopes are set to undefined.
Fixes #6456 
Fixes [AB#1758949](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1758949)
> [Fixes #6456] Updates about_Execution_Policies

- reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
The purpose of alias prefixes (hopefully) explained.
> About alias prefixes

- reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/6/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md
There are more things that are parsed in expression mode: not just strings and numbers but also unary operators, variable references and commands.
`$a = 2+2` is a statement, not a command, so I removed it from the examples.
I provided some more information about special characters and added a few additional illustrative examples.
I changed `echo(2+2)` to point out that tokenisation is not what the reader thinks it is.
I replaced `Write-Output` with `echo` so as not to distract the reader.
title and remove the prefix when …
> Parsing: Commands in expression mode and other clarifications

- reference/5.1/Microsoft.PowerShell.Management/Get-Location.md
- reference/6/Microsoft.PowerShell.Management/Get-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Get-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Get-Location.md
Update `Get-Location` **PSDrive** and **PSProvider** parameters description.
> Update Get-Location parameters description.

- reference/5.1/Microsoft.PowerShell.Management/Set-Location.md
- reference/6/Microsoft.PowerShell.Management/Set-Location.md
- reference/7.0/Microsoft.PowerShell.Management/Set-Location.md
- reference/7.1/Microsoft.PowerShell.Management/Set-Location.md
> Fix Set-Location examples.

- reference/5.1/CimCmdlets/New-CimSession.md
- reference/7.0/CimCmdlets/New-CimSession.md
- reference/7.1/Microsoft.PowerShell.Management/Split-Path.md
Corrected invalid code fence labels
> Corrected invalid code fence labels

- reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md
- reference/6/Microsoft.PowerShell.Utility/Select-Object.md
- reference/7.0/Microsoft.PowerShell.Utility/Select-Object.md
- reference/7.1/Microsoft.PowerShell.Utility/Select-Object.md
Minor grammatical errors in Select-Object
Fixes #6508 
Fixes [AB#1761807](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1761807)
> Fixes #6508 - Fixes Minor Issues in Select-Object

- reference/5.1/Microsoft.PowerShell.Core/About/about_Splatting.md
- reference/6/Microsoft.PowerShell.Core/About/about_Splatting.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Splatting.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Splatting.md
1. Fix obvious mistakes.
2. Improve code layout.
3. The code does not involve using an array *subexpression*, so remove the term.
> Fix mistakes in the description of ArgumentList

- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/7.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/7.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
Note about JSON comments being accepted by `ConvertFrom-Json` is updated for clarity
Fixes #6503 
Fixes [AB#1761416](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1761416)
> Clarifies note about json notes

- reference/docs-conceptual/dev-cross-plat/create-standard-library-binary-Module.md
Changed "pf" to "of" in create-standard-library-binary-module.md
> Fixed typo in create-standard-library-binary-module.md

- reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
Moves information to make common information more easily available and cohesive
Fixes #6527 
Fixes [AB#1763012](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1763012)
> Fixes #6527 - Updates about_Environment_Variables

- reference/docs-conceptual/learn/remoting/Running-Remote-Commands.md
Updates remoting information for PowerShell versions.
Fixes #6522 
Fixes [AB#1763409](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1763409)
> Fixes #6522 - Updates Running-Remote-Commands

- reference/module/index.md
Updated PowerShell module browser quick filter for Azure PowerShell to the current version (4.6.0).
> Updated azps quick filter to latest version 4.6.0

- reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md
- reference/6/Microsoft.PowerShell.Management/Copy-Item.md
- reference/7.0/Microsoft.PowerShell.Management/Copy-Item.md
- reference/7.1/Microsoft.PowerShell.Management/Copy-Item.md
Customer noticed that the current example headers could cause confusion and these are the suggested changes for clarity. 
Fixes #6550 
Fixes [AB#1764492](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1764492)
> [Fixes #6650] - Updates Copy-Item

- reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md
Updates about_Arrays to slarify single item array creation and array sub-expression operator
Fixes #6504 
Fixes [AB#1761600](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1761600)
> Fixes #6504 - Updates about_Arrays

- reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md
Customer Noticed Script Resource example didn't work. 
Fixes #6563 
Fixes [AB#1765335](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1765335)
> Fixes #6563 - Updates ScriptResource

- reference/docs-conceptual/dsc/reference/resources/windows/windowsOptionalFeatureResource.md
windowsOptionalFeatureResource DSC Resource doesn't work for WIndows Server. it only works on clients. THis adds a note to clarify that. 
Fixes #6566 
Fixes [AB#1765581](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1765581)
> [Fixes #6566] Updated windowsOptionalFeatureResource

- reference/module/index.md
Updated the PowerShell module browser quick filter for the Az PowerShell module to version 4.6.1.
> Updated module browser quick filter to latest azps

- reference/docs-conceptual/learn/deep-dives/write-progress-across-multiple-threads.md
Fixing broken links in OPS report.
> OPS Broken Links - 2020-09-02

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Customer noted incorrect information in about_functionsadvanced__parameters.
Fixes #6578 
Fixes [AB#1766936](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1766936)
> Fixes #6578 - Updates about_Functions_Advanced_parameters

- reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
New Value available in Invoke-RestMethod and Invoke-WebRequest SslProtocol
Fixes #6481 
Fixes [AB#1767800](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1767800)
> Fixes #6481 - Updates Invoke-WebRequest/ Invoke-RestMethod

- reference/6/Microsoft.PowerShell.Utility/Add-Type.md
- reference/7.0/Microsoft.PowerShell.Utility/Add-Type.md
- reference/7.1/Microsoft.PowerShell.Utility/Add-Type.md
Updates required versions of Add-Type for **OutputType** behavior
Fixes #6499 
Fixes [AB#1766604](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1766604)
> Fixes #6499 - Updates Add-Type

- reference/5.1/Microsoft.PowerShell.Core/ForEach-Object.md
- reference/6/Microsoft.PowerShell.Core/ForEach-Object.md
- reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md
- reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md
Customer noticed Typo in Foreach-Object docs
Fixes #6603 
Fixes [AB#1769082](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1769082)
> [Fixes #6603] - Updates Foreach-Object

- reference/5.1/Microsoft.PowerShell.Utility/Write-Output.md
- reference/6/Microsoft.PowerShell.Utility/Write-Output.md
- reference/7.0/Microsoft.PowerShell.Utility/Write-Output.md
- reference/7.1/Microsoft.PowerShell.Utility/Write-Output.md
Updates Write-Output for some clarity on usage. 
Fixes #6598 
Fixes [AB#1769024](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1769024)
> [Fixes #6598] - Updates Write-Output

- reference/5.1/Microsoft.PowerShell.Utility/Write-Host.md
- reference/6/Microsoft.PowerShell.Utility/Write-Host.md
- reference/7.0/Microsoft.PowerShell.Utility/Write-Host.md
- reference/7.1/Microsoft.PowerShell.Utility/Write-Host.md
Mulitple updates to Write-Host
Fixes #6599 
Fixes [AB#1769062](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1769062)
> [Fixes #6599] - Updates Write-Host 

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Fixes [AB#1771249](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1771249) - Fixes #6589 - add regkey info for MSI package
> Fixes #6589 - add regkey info for MSI package

- reference/6/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Modules.md
Fixes [AB#1771781](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1771781) - Fixes #6622 - update module path name
> Fixes #6622 - update module path name

- reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/6/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md
Adds information to about_Parsing about the default verb behavior.
Fixes #6576 
Fixes [AB#1771719](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1771719)
> [Fixes #6576] - Updates about_Parsing

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Updates for validation attributes
Fixes #6584 
Fixes [AB#1771717](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1771717)
> Fixes #6584 - Updates about_Functions_Advanced_Paramters

- reference/5.1/Microsoft.PowerShell.Management/Stop-Process.md
- reference/6/Microsoft.PowerShell.Management/Stop-Process.md
- reference/7.0/Microsoft.PowerShell.Management/Stop-Process.md
- reference/7.1/Microsoft.PowerShell.Management/Stop-Process.md
Replace Get-WMIObject with Get-CimInstance
> Replace Get-WMIObject with Get-CimInstance

- reference/5.1/Microsoft.PowerShell.Utility/Out-File.md
- reference/6/Microsoft.PowerShell.Utility/Out-File.md
- reference/7.0/Microsoft.PowerShell.Utility/Out-File.md
- reference/7.1/Microsoft.PowerShell.Utility/Out-File.md
Multiple updates to Out-File
Fixes #6600 
Fixes [AB#1772570](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1772570)
> Fixes #6600 - Updates Out-File

- reference/5.1/Microsoft.PowerShell.Management/Get-Clipboard.md
- reference/7.0/Microsoft.PowerShell.Management/Get-Clipboard.md
- reference/7.1/Microsoft.PowerShell.Management/Get-Clipboard.md
Fixes [AB#1774068](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1774068) - Fixes #6655 - improve description of -Raw
> Fixes #6655 - improve description of -Raw

- reference/5.1/Microsoft.PowerShell.Management/Get-Clipboard.md
- reference/5.1/Microsoft.PowerShell.Utility/Out-File.md
- reference/6/Microsoft.PowerShell.Utility/Out-File.md
- reference/7.0/Microsoft.PowerShell.Management/Get-Clipboard.md
- reference/7.0/Microsoft.PowerShell.Utility/Out-File.md
- reference/7.1/Microsoft.PowerShell.Management/Get-Clipboard.md
- reference/7.1/Microsoft.PowerShell.Utility/Out-File.md
- reference/docfx.json
> 9/21 PM Publish

- reference/5.1/Microsoft.PowerShell.Utility/Write-Verbose.md
- reference/6/Microsoft.PowerShell.Utility/Write-Verbose.md
- reference/7.0/Microsoft.PowerShell.Utility/Write-Verbose.md
- reference/7.1/Microsoft.PowerShell.Utility/Write-Verbose.md
Removes reference to debuggin in verbose command and formats for current standards
Fixes #6644 
Fixes [AB#1774079](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1774079)
> Fixes #6644 - Updates Write-Verbose

- reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
Clarifies example description
Fixes #6661 
Fixes [AB#1774383](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1774383)
> Fixes #6661 - Updates about_Environment_Variables

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
`brew cask upgrade` is deprecated and will receive an error if run. Updated to use `brew upgrade --cask`
Fixes #6664 
Fixes [AB#1774577](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1774577)
> Fixes #6664 - Updates upgrade method for macOs

- reference/5.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/6/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md
Various updates to about_Object_Creation
Fixes #6652 
Fixes [AB#1774451](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1774451)
> Fixes #6652 - Updates about_Object_Creation

- reference/5.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md
- reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
> 9/23 PM Publish

- reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
> Updates Homebrew upgrade method

- reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md
- reference/6/Microsoft.PowerShell.Utility/Select-Object.md
- reference/7.0/Microsoft.PowerShell.Utility/Select-Object.md
- reference/7.1/Microsoft.PowerShell.Utility/Select-Object.md
Fixes [AB#1775972](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1775972) - Fixes #6673 - Fix typo in example 5
> Fixes #6673 - Fix typo in example 5

- reference/5.1/Microsoft.PowerShell.Utility/Out-String.md
- reference/6/Microsoft.PowerShell.Utility/Out-String.md
- reference/7.0/Microsoft.PowerShell.Utility/Out-String.md
- reference/7.1/Microsoft.PowerShell.Utility/Out-String.md
Updates Out-String 
Fixes #6674 
Fixes [AB#1776239](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1776239)
> Fixes #6674 - Updates Out-String

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Added comprehensive examples for the `User:` drive and `ValidateUserDrive`
> Comprehensive examples for User: drive

- reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md
Fixes [AB#1777349](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1777349) - Closes #6685 - explain limitations of fixed arrays
> Closes #6685 - explain limitations of fixed arrays

- reference/5.1/Microsoft.PowerShell.Utility/Out-String.md
- reference/6/Microsoft.PowerShell.Utility/Out-String.md
- reference/7.0/Microsoft.PowerShell.Utility/Out-String.md
- reference/7.1/Microsoft.PowerShell.Utility/Out-String.md
Multiple updates to `Out-String`
Fixes #6679 
Fixes [AB#1776689](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1776689)
> Fixes #6679 - Updates Out-String

- reference/5.1/Microsoft.PowerShell.Utility/Out-String.md
- reference/6/Microsoft.PowerShell.Utility/Out-String.md
- reference/7.0/Microsoft.PowerShell.Utility/Out-String.md
- reference/7.1/Microsoft.PowerShell.Utility/Out-String.md
Updates `Out-String` Synopsis
Fixes #6689 
Fixes [AB#1777598](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1777598)
> Fixes #6689 - Updates Out-String

- reference/module/index.md
Updated PowerShell module browser quick filter to Az PowerShell version 4.7.0
> Updated quick filter to latest AzPS version

- reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Pwsh.md
Fixes [AB#1779055](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1779055) - Fixes #6548 - update pwsh help
Fixes [AB#1779056](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1779056) - Fixes #6702 - add sshs to pwsh help
Related to https://github.com/PowerShell/PowerShell/pull/13748
[key]: …
> Updates pwsh help output

- reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md
Fixes [AB#1779626](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1779626) - Fixes #6699 - Count to check property existence
> Fixes #6699 - Count to check property existence

- reference/5.1/Microsoft.PowerShell.Core/Get-History.md
- reference/6/Microsoft.PowerShell.Core/Get-History.md
- reference/7.0/Microsoft.PowerShell.Core/Get-History.md
- reference/7.1/Microsoft.PowerShell.Core/Get-History.md
Fixes [AB#1779737](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1779737) - Fixes #6709 - fix example 3 title
> Fixes #6709 - fix example 3 title

- reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/docs-conceptual/gallery/concepts/package-manifest-affecting-ui.md
Fixes [AB#1780131](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1780131) - Fixes #6695 - update icon size to 85x85
> Fixes #6695 - update icon size to 85x85

- reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/6/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/6/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/6/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Pwsh.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Scripts.md
Fixes [AB#1779760](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1779760) - Fixes #6559 - add details about exit codes
> Fixes #6559 - add details about exit codes

- reference/5.1/Microsoft.PowerShell.Core/About/About.md
- reference/6/Microsoft.WSMan.Management/About/about_WS-Management_Cmdlets.md
- reference/7.0/Microsoft.WSMan.Management/About/about_WS-Management_Cmdlets.md
- reference/7.1/Microsoft.WSMan.Management/About/about_WS-Management_Cmdlets.md
- reference/docs-conceptual/learn/remoting/Running-Remote-Commands.md
Fixing broken links per OPS. As `about_ws-management_cmdlets` is archived:
- The about index was updated to remove the entry.
- The other instance was updated with the link to the archive location.
> OPS Broken Links: 2020-10-07

- README.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
Fixes [AB#1781355](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1781355) - Fixes #6724 - update operator precedence info
> Fixes #6724 - update operator precedence info

- reference/module/index.md
Updated PowerShell module browser quick filter to Az PowerShell module version 4.8.0
> Updated module browser quickfilter to AzPS 4.8.0

- reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Type_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Type_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Type_Operators.md
Fixes [AB#1784067](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1784067) - Fixes #6756 - fix typos
> Fixes #6756 - fix typos

- reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Fixes [AB#1784270](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1784270) - Fixes #6759 - fix typo
> Fixes #6759 - fix typo

- reference/7.1/Microsoft.PowerShell.Core/Get-PSSubsystem.md
- reference/docs-conceptual/learn/experimental-features.md
Fixes [AB#1783969](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1783969) - Fixes #6754 - add info for PSSubsystemPluginModel
> Fixes #6754 - add info for PSSubsystemPluginModel

- reference/docs-conceptual/developer/module/installing-a-powershell-module.md
> Removed Duplicate '('

- reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
Fixes [AB#1785133](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1785133) - Fixes #6769 - Proper command to restart ssh
> Fixes #6769 - Proper command to restart ssh

- reference/docs-conceptual/developer/help/how-to-add-notes-to-a-cmdlet-help-topic.md
Fixes [AB#1785419](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1785419) - Fixes #6776 - fix alertset xml
> Fixes #6776 - fix alertset xml

- reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
I removed a comma that interrupted an otherwise helpful sentence
No context necessary
> Remove a poorly placed comma

- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/7.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/7.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
Fixes [AB#1785199](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1785199) - Fixes #6597 - add note about datetime conversion
> Fixes #6597 - add note about datetime conversion

- reference/5.1/Microsoft.PowerShell.Core/About/about_Character_Encoding.md
- reference/6/Microsoft.PowerShell.Core/About/about_Character_Encoding.md
- reference/7.0/Microsoft.PowerShell.Core/About/about_Character_Encoding.md
- reference/7.1/Microsoft.PowerShell.Core/About/about_Character_Encoding.md
Fixes [AB#1657739](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1657739) - Fixes #3190 - add about_Character_Encoding article
> Fixes #3190 - add about_Character_Encoding article
