MicrosoftDocs/PowerShell-Docs

reference/6/Microsoft.PowerShell.Core/Get-Command.md
Don't merge until https://github.com/PowerShell/PowerShell/pull/8458 gets merged
=> Doc `-UseFuzzyMatching` switch added to `Get-Command`

reference/3.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Modules.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Modules.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Modules.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/6/Microsoft.PowerShell.Core/About/about_Modules.md, reference/docs-conceptual/components/web-access/authorization-rules-and-security-features-of-windows-powershell-web-access.md, reference/docs-conceptual/components/web-access/install-and-use-windows-powershell-web-access.md, reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md, reference/docs-conceptual/learn/remoting/WSMan-Remoting-in-PowerShell-Core.md
This is the first of several PRs to change references to environment variables from `%variablename%` to `$env:variablename`.
=> removing %-style environment variables and other cleanup

reference/docs-conceptual/overview.md
I've noticed multiple usage of `COM` in the following doc page, but wasn't sure what this abbreviation represented until having to lookup. I feel like it would be nice for new readers like me to be able to know the full title of `COM`.
Also noticed similar pattern in the other files so this can keep the consistency.
=> Add full title before using COM abbreviations in the overview doc.

reference/3.0/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/3.0/Microsoft.PowerShell.Management/New-EventLog.md, reference/3.0/Microsoft.PowerShell.Management/Push-Location.md, reference/4.0/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/4.0/Microsoft.PowerShell.Management/New-EventLog.md, reference/4.0/Microsoft.PowerShell.Management/Push-Location.md, reference/5.0/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/5.0/Microsoft.PowerShell.Management/New-EventLog.md, reference/5.0/Microsoft.PowerShell.Management/Push-Location.md, reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/5.1/Microsoft.PowerShell.Management/New-EventLog.md, reference/5.1/Microsoft.PowerShell.Management/Push-Location.md, reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/6/Microsoft.PowerShell.Management/Push-Location.md
This is the first of several PRs to change references to environment variables from `%variablename%` to `$env:variablename`.
=> Fixes #3559 - removing %-style environment variables and other cleanup

reference/3.0/Microsoft.PowerShell.Utility/Select-String.md, reference/4.0/Microsoft.PowerShell.Utility/Select-String.md, reference/5.0/Microsoft.PowerShell.Utility/Select-String.md, reference/5.1/Microsoft.PowerShell.Utility/Select-String.md, reference/6/Microsoft.PowerShell.Utility/Select-String.md
`"idle, svchost"` is just a string. It should be an array like `idle, svchost`.
=> Fix Example 7 in Select-String.md

reference/3.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/4.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md
Related to Issue #2000 . Updated Encoding parameter info for all Export-Clixml. 
Style updates, paragraph reflows, fixed links.
=> Related to Issue #2000. Updated Encoding parameter info for all Export-Clixml

reference/docs-conceptual/components/vscode/using-vscode.md
This adds instructions for installing the PowerShell extension in VSCode when a group policy requires PowerShell Editor Services to be manually approved to run on a system.
=> Adding Instructions for Installing VSCode with Group Policy

dsc/configurations/configDataCredentials.md
Hello, @sdwheeler ,
Description: unescaped @ is breaking localized pages content  
=> C62586: Escaping @ character to avoid issues in localized pages

reference/3.0/Microsoft.PowerShell.Management/Copy-Item.md, reference/4.0/Microsoft.PowerShell.Management/Copy-Item.md, reference/5.0/Microsoft.PowerShell.Management/Copy-Item.md, reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md, reference/6/Microsoft.PowerShell.Management/Copy-Item.md
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3409
Correct example to copy the contents and not the folder itself
=> fix example so that it copies the contents and not the folder

developer/docfx.json, reference/docfx.json, reference/docs-conceptual/docfx.json
Issue #3636 mentioned the **Product feedback** link is not working.  Looks like it needs pointing back to the PowerShell repo and the choose option after the repo migration.
=> Fixing product feedback link

developer/cmdlet/tutorials-for-writing-cmdlets.md
* The "In this section" content was all duplicated for whatever reason. Removed duplicate text.
* The 2nd "Get-Process" link pointed to an msn.com URL instead of the correct Microsoft Docs. Removed as it was part of the duplicate text.
=> Fixed bad link and duplicate text.

reference/6/PowerShellGet/Publish-Script.md
A carriage return is missing after the Test-ScriptFileInfo command output, which makes the example difficult to understand.
=> Carriage return missing

reference/5.0/Microsoft.PowerShell.Utility/Format-Hex.md, reference/5.1/Microsoft.PowerShell.Utility/Format-Hex.md, reference/6/Microsoft.PowerShell.Utility/Format-Hex.md
Related to Issue #2000
Updated Encoding parameter for Format-Hex
Style updates
Paragraph reflows
Fixed links
Updated version: 93
=> Updated Encoding parameter and YAML for Format-Hex

reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalUser.md
As per the sentence above this section, and as per-testing, Get-LocalUser *does* in fact accept wildcard characters
=> adjusted "accept wildcard characters" to 'True'

reference/6/Microsoft.PowerShell.Management/Add-Content.md, reference/6/Microsoft.PowerShell.Management/Get-Content.md, reference/6/Microsoft.PowerShell.Management/Set-Content.md, reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/6/Microsoft.PowerShell.Utility/Export-Csv.md, reference/6/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/6/Microsoft.PowerShell.Utility/Format-Hex.md, reference/6/Microsoft.PowerShell.Utility/Import-Csv.md, reference/6/Microsoft.PowerShell.Utility/Out-File.md, reference/6/Microsoft.PowerShell.Utility/Select-String.md, reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
Corrected a typo and spacing in Encoding parameter (UTF8NoBOM rather than UF8NoBOM)
Fixed parameter reflows
=> Fixed typo in Encoding parameter

dsc/configurations/import-dscresource.md
There has been inconsistency for this requirement between compiling in the service which always requires new lines, and local compilation where this is a best practice but not hard requirement.  Updating documentation to follow the best practice which will also avoid issues compiling in the service.
=> Each module name on a new line

reference/3.0/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/6/Microsoft.PowerShell.Core/About/about_Splatting.md
Clarify that hash tables can only address parameters by name, even if they are positional parameters.
Addresses #3713 
=> Update about_splatting.md to clarify parameter types supported by hash tables

dsc/configurations/import-dscresource.md
Believe it should be `$pshome` rather than `$phsome` in DSC docs.
=> Fix typo in docs

reference/6/CimCmdlets/Get-CimInstance.md
I tried to fix the formatting errors without changing any of the content.  While I was there I also modified the file to be compatible with markdown formatting standards
=> Fix formatting issues in get-ciminstance for version 6

developer/cmdlet/activity-parameters.md, developer/cmdlet/date-and-time-parameters.md, developer/cmdlet/format-parameters.md, developer/cmdlet/property-parameters.md, developer/cmdlet/quantity-parameters.md, developer/cmdlet/resource-parameters.md, developer/cmdlet/security-parameters.md
The original articles in MSDN were formatted as a table. Recreated the tables here.
=> Fix #3777 - reformat as table

reference/docs-conceptual/components/vscode/understanding-file-encoding.md, reference/docs-conceptual/components/vscode/using-vscode.md, reference/docs-conceptual/toc.yml
From https://github.com/PowerShell/vscode-powershell/pull/1761.
=> Add documentation for configuring encoding with VSCode and PowerShell

reference/6/Microsoft.PowerShell.Core/Debug-Job.md, reference/6/Microsoft.PowerShell.Core/Get-Job.md, reference/6/Microsoft.PowerShell.Core/Receive-Job.md, reference/6/Microsoft.PowerShell.Core/Remove-Job.md, reference/6/Microsoft.PowerShell.Core/Start-Job.md, reference/6/Microsoft.PowerShell.Core/Stop-Job.md, reference/6/Microsoft.PowerShell.Core/Wait-Job.md
`Resume-Job` and `Suspend-Job` are not supported since v6 (see [the comment](https://github.com/PowerShell/PowerShell/issues/2122#issuecomment-332258023)).
=> Remove Resume-Job and Suspend-Job links in v6

gallery/concepts/module-prerelease-support.md, gallery/concepts/script-prerelease-support.md
These may have been in the product since the example was from a beta
=> typo: Uninnstall -> Uninstall

reference/3.0/CimCmdlets/Register-CimIndicationEvent.md, reference/4.0/CimCmdlets/Register-CimIndicationEvent.md, reference/5.0/CimCmdlets/Register-CimIndicationEvent.md, reference/5.1/CimCmdlets/Register-CimIndicationEvent.md, reference/6/CimCmdlets/Register-CimIndicationEvent.md
=> fix typo in example

developer/module/how-to-set-helpinfo-xml-version-numbers.md, developer/module/updatable-help-overview.md
Their ulrs are `Update-Help` but texts are not.
=> Fix links: not Update-Help

reference/3.0/PSWorkflow/About/about_Checkpoint-Workflow.md, reference/4.0/PSWorkflow/About/about_Checkpoint-Workflow.md, reference/4.0/PSWorkflow/About/about_Parallel.md, reference/5.0/PSWorkflow/About/about_Checkpoint-Workflow.md, reference/5.0/PSWorkflow/About/about_Parallel.md, reference/5.1/PSWorkflow/About/about_Checkpoint-Workflow.md, reference/5.1/PSWorkflow/About/about_Parallel.md
- "How to Add Checkpoints to a Workflow" appears to be dead
=> fix: Escapped markdown links

reference/docs-conceptual/samples/Using-Format-Commands-to-Change-Output-View.md
* Add missing pipeline `|`
* Add output
* Filter cmdlets by `-Verb`
* Fix formatting
=> Fix example: "Controlling Format-Wide Display with Column"

reference/3.0/Microsoft.PowerShell.Core/Get-Command.md, reference/4.0/Microsoft.PowerShell.Core/Get-Command.md, reference/5.0/Microsoft.PowerShell.Core/Get-Command.md, reference/5.1/Microsoft.PowerShell.Core/Get-Command.md, reference/6/Microsoft.PowerShell.Core/Get-Command.md
=> Fix typo; remove wrong word

reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
Doc updates are for https://github.com/PowerShell/PowerShell/pull/8961, which makes the -subject parameter no longer a required field of the Send-MailMessage command.
=> Updated Send-MailMessage to say that -subject is no longer required

reference/docs-conceptual/components/vscode/understanding-file-encoding.md
The TFS branding changed to Azure DevOps.
=> fix branding of TFS

reference/3.0/Microsoft.PowerShell.Utility/Set-Variable.md, reference/4.0/Microsoft.PowerShell.Utility/Set-Variable.md, reference/5.0/Microsoft.PowerShell.Utility/Set-Variable.md, reference/5.1/Microsoft.PowerShell.Utility/Set-Variable.md, reference/6/Microsoft.PowerShell.Utility/Set-Variable.md
I also changed the formatting of the last bullet point to match the first few. Addresses issue #4004
=> Add private scopes to PS6 Set-Variable docs

reference/6/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md, reference/6/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
=> add note to reflect that .Net Core doesn't encrypt contents of securestring

reference/6/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md, reference/6/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
Looking at the corefx source code, it appears that on Windows, SecureString is still encrypted so added clarification that unencrypted only applies to non-Windows systems.
Related PSCore6 PR https://github.com/PowerShell/PowerShell/pull/9199
=> updated to reflect that SecureString is only not encrypted on non-Windows systems

reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
fixes https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3736
This adds docs for the newly added parameter on `ConvertFrom-Json` called `-Depth`.
=> Add docs for Depth on ConvertFrom-Json

reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
@sdwheeler informed me that there should not be a newline after synopsis.
=> delete newline after synopsis

reference/6/Microsoft.PowerShell.Management/Test-Path.md
=> Add description and example about null paths for `Test-Path`

reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/6/Microsoft.PowerShell.Management/Get-Item.md
=> Document how to get hardlink information #3665

reference/3.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4041
Makes sense to change .txt to .log whereas .gif to .jpg wouldn't work unless they were misnamed originally.
=> fix example text to match PowerShell example

reference/6/Microsoft.PowerShell.Core/About/about_pwsh.md, reference/6/Microsoft.PowerShell.Core/Enter-PSHostProcess.md
fixes #3755
In https://github.com/PowerShell/PowerShell/pull/8889 we add the `-CustomPipeName` parameter on `pwsh` and `Enter-PSHostProcess`. This issue is to track documenting that feature.
=> update docs for -CustomPipeName

reference/docs-conceptual/PowerShell-Support-Lifecycle.md
=> document how experimental features are supported

reference/6/Microsoft.PowerShell.Management/Add-Content.md, reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/6/Microsoft.PowerShell.Management/Remove-Item.md
=> Fix the default formatting for FileSystemInfo object

reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/3.0/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/3.0/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/4.0/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/4.0/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/5.0/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/5.0/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/5.1/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/6/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
Set-ExecutionPolicy Acrolinx scores
Get-ExecutionPolicy Acrolinx scores
Original version: 87
- Closes #4005. Added info to Set-ExecutionPolicy for non-Windows platforms
- Copyedits, style, rewrote examples for the following documents:
- Set-ExecutionPolicy
- Get-ExecutionPolicy
- about_Execution_Policies
=> Closes #4005. Added info to Set-ExecutionPolicy for non-Windows platforms

reference/5.0/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.md, reference/5.1/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.md, reference/6/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.md
=> fix formatting and add examples

gallery/how-to/working-with-packages/social-media-feedback.md
This adds an important note that LiveFyre is no longer a supported service and as a result will no longer be available on the Gallery starting 05/01/2019.
=> Update social-media-feedback.md to indictate LiveFyre is out of Suppport 

reference/6/Microsoft.PowerShell.Utility/Write-Output.md
=> Update Write-Output to reflect change in behavior in 6.2 to align with WinPS

reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
=> Added docs for ReplyTo parameter in Send-MailMessage

reference/6/Microsoft.PowerShell.Utility/Get-Culture.md
FIx https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3025
=> Update `get-culture` doc for new parameters

reference/6/Microsoft.PowerShell.Core/New-PSSession.md
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3299
=> add note about -skipcacheck and -skipcncheck for non-Windows

developer/prog-guide/how-to-create-a-windows-powershell-provider.md, gallery/concepts/module-psedition-support.md, reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md, reference/6/Microsoft.PowerShell.Core/Get-Module.md, reference/6/Microsoft.PowerShell.Core/Import-Module.md
Resolves https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3433.
Adds documentation for the `-SkipEditionCheck` parameter on `Import-Module` and `Get-Module` and updates information about the `CompatiblePSEditions` field in documentation.
=> Add SkipEditionCheck switch docs, update CompatiblePSEditions docs

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
The download links can be hard to find for newcomers, or if there are just a lot of Release Notes present to scroll though.  Since a direct link to the Assets section isn't available, I added verbiage to make it slearer where the customer shoul look.
=> Clarifying where precisely to find the download links

reference/3.0/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
=> fix #4083 - fix typos and terms

reference/3.0/CimCmdlets/Get-CimAssociatedInstance.md, reference/3.0/CimCmdlets/Get-CimSession.md, reference/3.0/CimCmdlets/Invoke-CimMethod.md, reference/3.0/CimCmdlets/Remove-CimInstance.md, reference/3.0/ISE/ISE.md, reference/3.0/ISE/Import-IseSnippet.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/3.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/3.0/Microsoft.PowerShell.Core/About/about_PSSnapins.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Properties.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/3.0/Microsoft.PowerShell.Core/About/about_WMI.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Windows_RT.md, reference/3.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md, reference/3.0/Microsoft.PowerShell.Core/Get-Module.md, reference/3.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/3.0/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/3.0/Microsoft.PowerShell.Core/Receive-PSSession.md, reference/3.0/Microsoft.PowerShell.Management/Get-WmiObject.md, reference/3.0/Microsoft.PowerShell.Security/Set-Acl.md, reference/3.0/Microsoft.PowerShell.Utility/Get-Alias.md, reference/3.0/Microsoft.PowerShell.Utility/Select-Object.md, reference/3.0/PSWorkflow/About/about_ActivityCommonParameters.md, reference/3.0/PSWorkflow/About/about_Checkpoint-Workflow.md, reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md, reference/3.0/PSWorkflow/About/about_Parallel.md
=> remove highbit chars

reference/6/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
Added a section on how to use `$_` and `$PSItem` within a `catch` block to access information about the error that was thrown.
=> Documentation for accessing errors in catch block

reference/3.0/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md, reference/6/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
This is a continuation of #4107. Adding same information to other versions.
=> add explantion to other versions

reference/5.0/PackageManagement/Find-Package.md, reference/5.0/PackageManagement/Get-PackageSource.md, reference/5.1/PackageManagement/Find-Package.md, reference/5.1/PackageManagement/Get-PackageSource.md, reference/6/PackageManagement/Find-Package.md, reference/6/PackageManagement/Get-PackageSource.md
=> Updated the examples in Find-Package, Get-PackageSource

reference/docs-conceptual/samples/Using-Format-Commands-to-Change-Output-View.md
For non Windows PowerShell users:
`Get-Process -Name powershell` -> `Get-Command -Verb Format`
=> Update example: "Using Format-Wide"

reference/3.0/Microsoft.PowerShell.Management/Remove-Computer.md, reference/4.0/Microsoft.PowerShell.Management/Remove-Computer.md, reference/5.0/Microsoft.PowerShell.Management/Remove-Computer.md, reference/5.1/Microsoft.PowerShell.Management/Remove-Computer.md
=> fix #4102 - remove duplicate text and style edits

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md
=> Fix #4119 - add missing link

reference/docs-conceptual/samples/Changing-Computer-State.md, reference/docs-conceptual/samples/Collecting-Information-About-Computers.md, reference/docs-conceptual/samples/Creating-.NET-and-COM-Objects--New-Object-.md, reference/docs-conceptual/samples/Creating-Get-WinEvent-queries-with-FilterHashtable.md, reference/docs-conceptual/samples/Managing-Current-Location.md, reference/docs-conceptual/samples/Managing-Windows-PowerShell-Drives.md, reference/docs-conceptual/samples/Manipulating-Items-Directly.md, reference/docs-conceptual/samples/Performing-Networking-Tasks.md, reference/docs-conceptual/samples/Redirecting-Data-with-Out---Cmdlets.md, reference/docs-conceptual/samples/Removing-Objects-from-the-Pipeline--Where-Object-.md, reference/docs-conceptual/samples/Using-Format-Commands-to-Change-Output-View.md, reference/docs-conceptual/samples/Using-Static-Classes-and-Methods.md, reference/docs-conceptual/samples/Working-With-Files-Folders-and-Registry-Keys.md, reference/docs-conceptual/samples/Working-with-Files-and-Folders.md, reference/docs-conceptual/samples/Working-with-Printers.md, reference/docs-conceptual/samples/Working-with-Registry-Entries.md, reference/docs-conceptual/samples/Working-with-Registry-Keys.md, reference/docs-conceptual/samples/Working-with-Software-Installations.md
Fixed the markdownlint(MD001) "Heading levels should only increment by one level at a time"
=> Fix heading levels: samples directory

reference/3.0/Microsoft.PowerShell.Core/About/about_profiles.md, reference/4.0/Microsoft.PowerShell.Core/About/about_profiles.md, reference/5.0/Microsoft.PowerShell.Core/About/about_profiles.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md
=> Fix #4128 - fix path typo in v3-v51

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
=> Fix #4063 - fix Ubuntu 18.04 setup steps & PS vers

reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
=> update package names for macOS

reference/3.0/Microsoft.PowerShell.Core/About/about_numeric_literals.md, reference/4.0/Microsoft.PowerShell.Core/About/about_numeric_literals.md, reference/5.0/Microsoft.PowerShell.Core/About/about_numeric_literals.md, reference/5.1/Microsoft.PowerShell.Core/About/about_numeric_literals.md, reference/6/Microsoft.PowerShell.Core/About/about_numeric_literals.md
=> Fix #2695 - add info about numeric literals

wmf/5.0/feedback_symbolic.md
=> Fix: capitalisation

.gitignore, build.ps1
@sdwheeler requested if we can parallelize the building of maml help to reduce CI time.  Not clear to me how much benefit will be achieved as I believe the AzDevOps images are single core.  Anyways, the fix here is to run the scriptblock that produces the updatable help to run in a ThreadJob rather than serially.  Had to make some modifications as platyPS seems to use the current directory to produce temp files so having multiple instances run meant creating temp folders for each to use and setting the location to that path prior to using platyPS.
Other changes would be capturing the verbose output and seeing if the ThreadJob produced errors or failed outright.
There was also a typo in .gitignore for the folder of the result so fixed that.
=> Enable parallel runs of platyPS per version

reference/6/Microsoft.PowerShell.Management/Add-Content.md, reference/6/Microsoft.PowerShell.Management/Get-Content.md, reference/6/Microsoft.PowerShell.Management/Set-Content.md, reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/6/Microsoft.PowerShell.Utility/Export-Csv.md, reference/6/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/6/Microsoft.PowerShell.Utility/Format-Hex.md, reference/6/Microsoft.PowerShell.Utility/Import-Csv.md, reference/6/Microsoft.PowerShell.Utility/Out-File.md, reference/6/Microsoft.PowerShell.Utility/Select-String.md, reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
=> Fix #2937 - add Encoding param codepage support

reference/5.0/PowershellGet/Unregister-PSRepository.md, reference/5.1/PowershellGet/Unregister-PSRepository.md, reference/6/PowerShellGet/Unregister-PSRepository.md
=> Fix #4118 - remove invalid statement

reference/6/PSReadLine/Set-PSReadlineOption.md
Fixes #4185
This change only applies to the latest version of PSReadLine.
=> Fix #4185 - add example

reference/3.0/Microsoft.PowerShell.Management/Show-ControlPanelItem.md, reference/4.0/Microsoft.PowerShell.Management/Show-ControlPanelItem.md, reference/5.0/Microsoft.PowerShell.Management/Show-ControlPanelItem.md, reference/5.1/Microsoft.PowerShell.Management/Show-ControlPanelItem.md
=> Fix #4172 - name of firewall cpl changed

reference/6/Microsoft.PowerShell.Management/Add-Content.md, reference/6/Microsoft.PowerShell.Management/Get-Content.md, reference/6/Microsoft.PowerShell.Management/Set-Content.md, reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/6/Microsoft.PowerShell.Utility/Export-Csv.md, reference/6/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/6/Microsoft.PowerShell.Utility/Format-Hex.md, reference/6/Microsoft.PowerShell.Utility/Import-Csv.md, reference/6/Microsoft.PowerShell.Utility/Out-File.md, reference/6/Microsoft.PowerShell.Utility/Select-String.md, reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
=> Fix #4191 Fix #4192 - correct encoding

reference/3.0/Microsoft.PowerShell.Management/Add-Content.md, reference/3.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md, reference/4.0/Microsoft.PowerShell.Management/Add-Content.md, reference/4.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md, reference/5.0/Microsoft.PowerShell.Management/Add-Content.md, reference/5.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md, reference/5.1/Microsoft.PowerShell.Management/Add-Content.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
This updates the encoding information per issue #4155. The changes are broken into 4 PRs for easier review.
=> fix encoding - part 1

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
The libicu57 pkg name on the ftp server has changed.  Updated to one that works.
=> update libicu pkg name

reference/docs-conceptual/samples/Sample-Scripts-for-Administration.md
=> Fix #4236 - Reword

reference/3.0/Microsoft.PowerShell.Utility/Set-Date.md, reference/4.0/Microsoft.PowerShell.Utility/Set-Date.md, reference/5.0/Microsoft.PowerShell.Utility/Set-Date.md, reference/5.1/Microsoft.PowerShell.Utility/Set-Date.md, reference/6/Microsoft.PowerShell.Utility/Set-Date.md
=> Updating Set-Date

reference/3.0/Microsoft.PowerShell.Utility/New-TimeSpan.md, reference/4.0/Microsoft.PowerShell.Utility/New-TimeSpan.md, reference/5.0/Microsoft.PowerShell.Utility/New-TimeSpan.md, reference/5.1/Microsoft.PowerShell.Utility/New-TimeSpan.md, reference/6/Microsoft.PowerShell.Utility/New-TimeSpan.md
=> Updating New-TimeSpan

dsc/troubleshooting/troubleshooting.md
where the certificate common name is different than the DNS name.  
fyi @Austinm2559
=> Add known troubleshooting case for Pull Server

developer/cmdlet/cmdlet-overview.md
* Replace the broken link  "Windows PowerShell Transactions" with "How to Support Transactions"
* Convert lists to headers
=> Update "Cmdlet Overview"

developer/cmdlet/events01-sample.md
* Fix the link "System.IO.FileSystemWatcher"
* Fix format
=> Update "Events01 Sample"

reference/6/Microsoft.PowerShell.Utility/Trace-Command.md
The `Show-Command` cmdlet is not supported since v6
=> Remove Show-Command link in v6 doc

developer/module/how-to-write-a-powershell-binary-module.md, developer/module/writing-a-windows-powershell-module.md
Fix the URL in order to forward to the [new page](https://docs.microsoft.com/en-us/powershell/developer/module/how-to-write-a-powershell-module-manifest), not to the [old page](https://docs.microsoft.com/en-us/previous-versions//dd878297(v=vs.85)).
=> Fix links for "How to Write a PowerShell Module Manifest"

dsc/managing-nodes/metaConfig.md
=> Add information about http proxy

reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md, reference/4.0/Microsoft.PowerShell.Utility/Get-Date.md, reference/5.0/Microsoft.PowerShell.Utility/Get-Date.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md, reference/6/Microsoft.PowerShell.Utility/Get-Date.md
The table is derived from the [Windows PowerShell Language Specification Version 3.0](https://www.microsoft.com/en-us/download/details.aspx?id=36389).
It seems appropriate that the table should be in the UFormat parameters section, not in the NOTES as a list.
=> Add UFormat specifiers table

reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
ASCIIEncoding -> UTF8Encoding since v6
=> Fix $OutputEncoding default value v6

developer/hosting/windows-powershell-host-quickstart.md
The following example passes both the `Name` and `Id` parameters to `Get-Process`:
```
PowerShell.Create().AddCommand("Get-Process")
.AddParameter("Name", "PowerShell")
.AddParameter("Id", "12768")
.Invoke();
```
However, both of those parameters do not appear to be supported simultaneously.
I've replaced the example with the following one:
```
PowerShell.Create().AddCommand("Get-ChildItem")
.AddParameter("Path", @"c:\Windows")
.AddParameter("Filter", "*.exe")
.Invoke();
```
=> Replace example with working one

reference/3.0/Microsoft.PowerShell.Utility/Format-List.md, reference/4.0/Microsoft.PowerShell.Utility/Format-List.md, reference/5.0/Microsoft.PowerShell.Utility/Format-List.md, reference/5.1/Microsoft.PowerShell.Utility/Format-List.md, reference/6/Microsoft.PowerShell.Utility/Format-List.md
=> Fixes #3391 - Correct Format-List Property values

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Parameters.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Parameters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Parameters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Parameters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
=> Fixes #3014 - Clarify delay bind script blocks

reference/4.0/Microsoft.PowerShell.Core/Start-Job.md, reference/5.0/Microsoft.PowerShell.Core/Start-Job.md, reference/5.1/Microsoft.PowerShell.Core/Start-Job.md, reference/6/Microsoft.PowerShell.Core/Start-Job.md
=> Clarify automatic variable usage in Microsoft.PowerShell.Core\Start-Job -ScriptBlock

developer/cmdlet/validatelength-attribute-declaration.md
The link *How to Declare Input Validation Rules* under Remarks, bullet point #1 was pointing to a dead link. I have modified it to point to the most relevant reference page I could find on that topic.
=> Fixing Dead Link

.github/ISSUE_TEMPLATE.md
The template version list should be updated to reflect the fact that there will be no 6.x releases, and the next version of PowerShell is the 7.0 release.
=> Change 6.next to 7 for issue template

.github/PULL_REQUEST_TEMPLATE.md
The template version list should be updated to reflect the fact that there will be no 6.x releases, and the next version of PowerShell is the 7.0 release.
=> Replace 6.x version with 7

reference/docs-conceptual/components/vscode/using-vscode.md
A while ago @rkeithhill added this new feature for adding additional PowerShell exes. This is to document that and also have a place to point people to on how to access the session menu.
I plan on sending a PR to the Azure Functions docs as well pointing this out since folks seem to have a hard time discovering the session menu there.
cc @rjmholt @SydneyhSmith
=> Update docs on how to add your own powershell executables

dsc/configurations/runAsUser.md
=> Fixes #4306 - Update runasuser with SeInteractiveLogonRight qualifier

developer/installing-the-windows-powershell-sdk.md, developer/windows-powershell.md
Specifically, there's a link to "Installing the Windows PowerShell SDK" that still points to MSDN instead of the local article.  Lets fix that.
=> Migration from MSDN missed a spot

reference/3.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/6/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
=> Fix #4105 - explain wildcard execution (globbing)

reference/3.0/Microsoft.PowerShell.Management/Get-HotFix.md, reference/4.0/Microsoft.PowerShell.Management/Get-HotFix.md, reference/5.0/Microsoft.PowerShell.Management/Get-HotFix.md, reference/5.1/Microsoft.PowerShell.Management/Get-HotFix.md
Get-HotFix Acrolinx scores
Updated version: 91
Fixes #4311
Updated style, format, and copyedited
=> Fixes #4311, copyedits, style, format

reference/6/Microsoft.PowerShell.Core/New-PSSession.md
There was a missing quote mark making the example invalid, and also messing up the syntax highlighting when viewing the document.
=> Fixing syntax issue - missing quote mark

README.md
=> Update the README to point to current CI builds

reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Reference: https://docs.microsoft.com/dotnet/api/system.management.automation.validaterangekind?view=pscore-6.2.0
=> Fixes #4341 - Corrected ValidateRangeKind Enum

reference/docs-conceptual/samples/Working-with-Printers.md
Parameter `-ComputerName` in example is without any parameter specified therefore copy&paste of the code block causes syntax error when pasted to PowerShell window.
=> Remove -ComputerName from example code block

reference/5.1/PowershellGet/Find-Script.md, reference/5.1/PowershellGet/Install-Script.md, reference/6/PowerShellGet/Find-Script.md, reference/6/PowerShellGet/Install-Script.md
=> Corrects a logically-reversed word in 2 script cmdlet example titles

reference/5.1/PowershellGet/Find-RoleCapability.md, reference/6/PowerShellGet/Find-RoleCapability.md
Find-RoleCapability Acrolinx scores:
Original version: 93
- Replaced empty parameter placeholders with content
- Copyedits and style
=> Find-RoleCapability - fixed empty parameter placeholders, copyedits

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
=> C90810: Adding missing "releases" in brackets "[]" and new blank line after 172nd line

reference/6/Microsoft.PowerShell.Core/About/about_Jobs.md, reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
=> Clean up documentation for the `&` background operator

reference/6/Microsoft.PowerShell.Utility/Format-Table.md
When -Properties is not used, the command uses the first object in a hash table to decide on headers to show. If this first object doesn't contain properties of subsequent objects (e.g Object1 has two properties and Object2 has three properties), only headers for the first object's properties will be shown.
=> Added clarification on default header behaviour.

reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md
Looks like in PowerShell v6 a, docs got changed and now doesn't reflect what we see in the console `Get-Help Get-ChildItem`. `-Filter` parameter is (as it was in v5.1 and probably previously) positional on position 1.
**NOTE**: I wasn't able to find folder for v7 documentation so I only edited v6. If anything else is needed, feel free to point me the right file.
First noticed by me [on StackOverflow](https://stackoverflow.com/a/56632955/9902555).
=> Update Get-ChildItem -Filter position

reference/6/Microsoft.PowerShell.Utility/New-Alias.md
There was an empty point in the Notes section. Moved the `delete alias` to it and added some formatting to the first one.
=> Fixed empty bullet and formatting

developer/cmdlet/writing-a-windows-powershell-cmdlet.md
Remove the link for "Writing Formatting Files for Cmdlet Output", which is not under this category.
=> Update "Writing a Windows PowerShell Cmdlet"

reference/3.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/4.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/5.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md, reference/6/Microsoft.PowerShell.Core/Invoke-Command.md, reference/7/Microsoft.PowerShell.Core/Invoke-Command.md
Minor fixes of **AsJob** parameter, working much like `Start-Job`.
=> Update Invoke-Command AsJob param

reference/3.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
#4496 Corrected operator precedence for the binary forms of -split and -join string operators, which is less than the operator precedence for the unary forms of these operators.  -split (binary) and -join (binary) would belong at the same level as type and comparison operators.  Applies to all Powershell versions.
=> Corrected operator precedence split, join (binary)

reference/3.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/3.0/Microsoft.PowerShell.Utility/Register-ObjectEvent.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/4.0/Microsoft.PowerShell.Utility/Register-ObjectEvent.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/5.0/Microsoft.PowerShell.Utility/Register-ObjectEvent.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/5.1/Microsoft.PowerShell.Utility/Register-ObjectEvent.md, reference/6/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/6/Microsoft.PowerShell.Utility/Register-ObjectEvent.md, reference/7/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/7/Microsoft.PowerShell.Utility/Register-ObjectEvent.md
- Completes #4496
- Fixes [AB#1564528](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1564528)
- Cleanup copy/paste error in PR#4489
=> Fixes #4496 - error in operator precedence

reference/7/PowerShellGet/Publish-Module.md
PS 7 
- Fixes #4504
- Added SkipAutomaticTags parameter description to PS 7. Refer to PowerShell/PowerShellGet repo PR 452.
- Added content to empty parameters
- Style, paragraph reflows
=> Fixes #4504 - Added SkipAutomaticTags parameter to PS 7 Publish-Module

reference/5.0/Microsoft.PowerShell.Utility/New-Object.md
Updated Example 4 to bring it in line with the quality of PowerShell 6 and 7 documents. (It is not urgent to update 6 and 7 documents.) A lot of white spaces are removed from this example. The reason is **NOT** saving a few bytes. It is to improve readability. We admins actually use these documents in our PowerShell instances. Screen property isn't exactly unlimited.
=> Minor update to one example

reference/5.0/PowershellGet/Save-Module.md, reference/5.0/PowershellGet/Uninstall-Module.md, reference/5.1/PowershellGet/Save-Module.md, reference/5.1/PowershellGet/Save-Script.md, reference/5.1/PowershellGet/Uninstall-Module.md, reference/5.1/PowershellGet/Uninstall-Script.md, reference/6/PowerShellGet/Save-Module.md, reference/6/PowerShellGet/Save-Script.md, reference/6/PowerShellGet/Uninstall-Module.md, reference/6/PowerShellGet/Uninstall-Script.md, reference/7/PowerShellGet/Save-Module.md, reference/7/PowerShellGet/Save-Script.md, reference/7/PowerShellGet/Uninstall-Module.md, reference/7/PowerShellGet/Uninstall-Script.md
Save-Script: original version: 95, updated version: 98
Uninstall-Module: original version: 93, updated version: 97
Uninstall-Script: original version: 94, updated version: 97
- Fixes [AB#1565976](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1565976)
- Related to #3740
- Added content to empty parameter descriptions
- Revised the Save-Module parameter descriptions: MaximumVersion, MinimumVersion, and Path
=> Fixed empty parameters, copyedits

reference/5.1/PowershellGet/New-ScriptFileInfo.md, reference/5.1/PowershellGet/Update-ModuleManifest.md, reference/5.1/PowershellGet/Update-Script.md, reference/5.1/PowershellGet/Update-ScriptFileInfo.md, reference/6/PowerShellGet/New-ScriptFileInfo.md, reference/6/PowerShellGet/Update-ModuleManifest.md, reference/6/PowerShellGet/Update-Script.md, reference/6/PowerShellGet/Update-ScriptFileInfo.md, reference/7/PowerShellGet/New-ScriptFileInfo.md, reference/7/PowerShellGet/Update-ModuleManifest.md, reference/7/PowerShellGet/Update-Script.md, reference/7/PowerShellGet/Update-ScriptFileInfo.md
Update-Script Acrolinx scores: original version: 93, updated version: 98
Update-ScriptFileInfo Acrolinx scores: original version: 91, updated version: 96
- Fixes [AB#1568182](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1568182)
- Related to #3740
- Added content to empty parameters
- Fixed ms.date and Path description for New-ScriptFileInfo
- Fixed markdown style for one variable in the example description for Update-ModuleManifest
=> Added content to empty parameters, copyedits

reference/5.0/PowershellGet/Find-Command.md, reference/5.0/PowershellGet/Find-DscResource.md, reference/5.0/PowershellGet/Find-Module.md, reference/5.0/PowershellGet/Install-Module.md, reference/5.0/PowershellGet/Publish-Module.md, reference/5.1/PowershellGet/Find-Command.md, reference/5.1/PowershellGet/Find-DscResource.md, reference/5.1/PowershellGet/Find-Module.md, reference/5.1/PowershellGet/Find-RoleCapability.md, reference/5.1/PowershellGet/Install-Module.md, reference/5.1/PowershellGet/Publish-Module.md, reference/6/PowerShellGet/Find-Command.md, reference/6/PowerShellGet/Find-DscResource.md, reference/6/PowerShellGet/Find-Module.md, reference/6/PowerShellGet/Find-RoleCapability.md, reference/6/PowerShellGet/Install-Module.md, reference/6/PowerShellGet/Publish-Module.md, reference/7/PowerShellGet/Find-Command.md, reference/7/PowerShellGet/Find-DscResource.md, reference/7/PowerShellGet/Find-Module.md, reference/7/PowerShellGet/Find-RoleCapability.md, reference/7/PowerShellGet/Install-Module.md, reference/7/PowerShellGet/Publish-Module.md
- Corrected the parameter set spacing and YAML header ms.date
- Related to updates for #3740
Find-Command
Find-DscResource
Find-Module
Install-Module
Find-RoleCapability
Publish-Module
=> PowerShellGet docs - corrected parameter set spacing and YAML date format

reference/5.0/PackageManagement/Find-Package.md, reference/5.0/PackageManagement/Get-Package.md, reference/5.0/PackageManagement/Get-PackageSource.md, reference/5.0/PackageManagement/Install-Package.md, reference/5.0/PackageManagement/Register-PackageSource.md, reference/5.1/PackageManagement/Find-Package.md, reference/5.1/PackageManagement/Get-Package.md, reference/5.1/PackageManagement/Get-PackageSource.md, reference/5.1/PackageManagement/Install-Package.md, reference/5.1/PackageManagement/Register-PackageSource.md, reference/6/PackageManagement/Find-Package.md, reference/6/PackageManagement/Get-Package.md, reference/6/PackageManagement/Get-PackageSource.md, reference/6/PackageManagement/Install-Package.md, reference/6/PackageManagement/Register-PackageSource.md, reference/7/PackageManagement/Find-Package.md, reference/7/PackageManagement/Get-Package.md, reference/7/PackageManagement/Get-PackageSource.md, reference/7/PackageManagement/Install-Package.md, reference/7/PackageManagement/Register-PackageSource.md
- Corrected the parameter set spacing and YAML header ms.date
- Related to updates for #3740
Find-Package
Get-Package
Get-PackageSource
Install-Package
Register-PackageSource
=> PackageManagement docs - corrected parameter set spacing and YAML date format

reference/5.0/PackageManagement/Save-Package.md, reference/5.0/PackageManagement/Set-PackageSource.md, reference/5.0/PackageManagement/Uninstall-Package.md, reference/5.0/PackageManagement/Unregister-PackageSource.md, reference/5.1/PackageManagement/Save-Package.md, reference/5.1/PackageManagement/Set-PackageSource.md, reference/5.1/PackageManagement/Uninstall-Package.md, reference/5.1/PackageManagement/Unregister-PackageSource.md, reference/6/PackageManagement/Save-Package.md, reference/6/PackageManagement/Set-PackageSource.md, reference/6/PackageManagement/Uninstall-Package.md, reference/6/PackageManagement/Unregister-PackageSource.md, reference/7/PackageManagement/Save-Package.md, reference/7/PackageManagement/Set-PackageSource.md, reference/7/PackageManagement/Uninstall-Package.md, reference/7/PackageManagement/Unregister-PackageSource.md
- Corrected the parameter set spacing and YAML header ms.date
- Related to updates for #3740
- Fixes [AB#1568843](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1568843)
Save-Package
Set-PackageSource
Uninstall-Package
Unregister-PackageSource
=> PackageManagement docs part 2 - corrected parameter set spacing and YAML date format

reference/3.0/Microsoft.PowerShell.Core/About/about_Line_Editing.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Line_Editing.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Line_Editing.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Line_Editing.md, reference/6/Microsoft.PowerShell.Core/About/about_Line_Editing.md, reference/7/Microsoft.PowerShell.Core/About/about_Line_Editing.md
about_Line_Editing Acrolinx score
Updated version: 100
- Fixes [AB#1565857](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1565857)
- Added about_PSReadline link to v5.0 - 7
=> Fixes #4512 - Add line and link to about_PSReadline

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Raspbian Buster was released alongside the Raspberry Pi 4. Buster does not include libssl1.0, which is a prerequisite for .NET Core 2.x. As a result, PowerShell Core 6.x would fail. Therefore, libssl1.0 is added as a prerequisite with care to not select libssl1.0-dev. Also, a step was added to update package lists prior to package installation, and the -y flag on the apt-get install command prevents a confirmation prompt.
Note that libssl1.0 is not required for PowerShell 7 because PS7 runs on .NET Core 3.x, which does not have the dependency.
=> Updating Raspbian installation for Raspbian Buster

reference/6/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7/Microsoft.PowerShell.Host/Start-Transcript.md
Fixes [AB#1569991](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1569991)
Fixes #4551 
=> Fix #4551 - added version info to parameter

reference/7/Microsoft.PowerShell.Management/Set-Service.md
Set-Service Acrolinx scores
- Fixes [AB#1572750](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1572750)
- Fixes #4562
=> Fixes #4562 - Set-Service, Add the StartType alias to StartupType parameter for PS7

reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/7/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
about_Remote_Variables Acrolinx scores
Updated version: 91
- Fixes [AB#1574501](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1574501)
- Fixes #4545
=> Fixes #4545 - Added a splatting example

reference/3.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
about_Automatic_Variables Acrolinx scores
Original version: 91
Updated version: 94
- Fixes [AB#1575941](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1575941)
- Fixes #4589
- Corrected variable name in `$PROFILE` section (`$PSHOME` > `$PROFILE`)
- Corrected table for each version's output from `$PSVersionTable`
- Minor copyedits and style changes, paragraph reflows.
=> Fixes #4589 - Corrected variable name

dsc/pull-server/publishConfigs.md
Publish to a Pull Server using Configuration IDs (v4/v5)
Original version: 89
Updated version: 92
- Fixes [AB#1579117](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1579117)
- Fixes #4604
- Paragraph reflows, style, minor copyedits
=> Fixes #4604 - Correction for ConfigurationPath and ModulePath

reference/3.0/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/6/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7/Microsoft.PowerShell.Core/About/about_Special_Characters.md
- Fixes [AB#1579650](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1579650)
- Fixes #4602
=> Fixes #4602 - special characters not in PS3/4/5

reference/3.0/Microsoft.PowerShell.Core/About/about_Debuggers.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Debuggers.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Debuggers.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Debuggers.md, reference/6/Microsoft.PowerShell.Core/About/about_Debuggers.md, reference/7/Microsoft.PowerShell.Core/About/about_Debuggers.md
- Added link to about_Prompts
- Removed references to Workflows in v6 and v7
Fixes #4601 
Fixes [AB#1580816](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1580816)
=> Fixes #4601 - link to about_Prompts

reference/3.0/Microsoft.PowerShell.Core/Out-Host.md, reference/4.0/Microsoft.PowerShell.Core/Out-Host.md, reference/5.0/Microsoft.PowerShell.Core/Out-Host.md, reference/5.1/Microsoft.PowerShell.Core/Out-Host.md, reference/6/Microsoft.PowerShell.Core/Out-Host.md, reference/7/Microsoft.PowerShell.Core/Out-Host.md
Original version: 93
- Fixes [AB#1580988](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1580988)
- Fixes #4567
- Paragraph reflows, style, copyedits
=> Fixes #4567 - Added paragraph about ANSI to the description

reference/3.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- Fixes [AB#1583317](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1583317)
- Fixes #4629
- Corrected the variable name: $PSBoundParameterValues > $PSBoundParameters
- Fixed the $PSBoundParameters example
=> Fixes #4629 - Corrected the variable name $PSBoundParameters

dsc/resources/singleInstance.md
- Removes the use of `SupportsShouldProcess` as it could be seen that it is best practice to use it when actually DSC/LCM cannot use an interactive function.
=> Updates Writing a single-instance DSC resource (best practice) (singleInstance.md)

reference/3.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/3.0/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/4.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/4.0/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/5.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.0/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.1/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7/Microsoft.PowerShell.Utility/Import-Clixml.md
Export-Clixml Acrolinx scores
Original version: 91
Import-Clixml Acrolinx scores
- Fixes [AB#1584227](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1584227)
- Fixes #4614 - Added note that exported encrypted credentials is Windows only
- Fixes [AB#1584808](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1584808)
- Fixes #4641 - Added CLI definition to Description
- Fixed parameter set spacing between parameters
=> Fixes #4614, Fixes #4641 - Export-Clixml and Import-Clixml

dsc/pull-server/pullServer.md, reference/3.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/3.0/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/4.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/4.0/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/4.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md, reference/5.0/Microsoft.PowerShell.Core/About/About_Using.md, reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md, reference/5.0/Microsoft.PowerShell.Core/Import-Module.md, reference/5.0/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.0/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/5.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md, reference/5.1/Microsoft.PowerShell.Core/About/About_Using.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/5.1/Microsoft.PowerShell.Core/Import-Module.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.1/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/5.1/PSDesiredStateConfiguration/Stop-DscConfiguration.md, reference/6/Microsoft.PowerShell.Core/About/About_Using.md, reference/6/Microsoft.PowerShell.Core/About/about_Classes.md, reference/6/Microsoft.PowerShell.Core/Import-Module.md, reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7/Microsoft.PowerShell.Core/About/About_Using.md, reference/7/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7/Microsoft.PowerShell.Core/Import-Module.md, reference/7/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7/Microsoft.PowerShell.Utility/Import-Clixml.md
Classes and `using` were introduced in v5.0. 
Fixes #4630 
Fixes [AB#1585254](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1585254)
=>  Fixes #4630 - PS classes only imported by using statement

reference/3.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/4.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/5.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/6/Microsoft.PowerShell.Utility/Import-Csv.md, reference/7/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/7/Microsoft.PowerShell.Utility/Import-Csv.md
Fixes #4676 - update parameter sets for v6.2
Fixes [AB#1588398](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1588398)
Also fixed output in Example 3 of ConvertTo-Csv.md for all versions and removed invalid parameter set per https://github.com/PowerShell/PowerShell/pull/10425
=> Fixes #4676 - update parameter sets for v6.2

dsc/configurations/import-dscresource.md, dsc/resources/get-test-set.md
Media links were absolute for some reason, which doesn't work on docs.microsoft.com. Per Contributing, links should be relative.
=> Fixed broken links to media folder in DSC docs

reference/6/Microsoft.PowerShell.Utility/Add-Type.md, reference/7/Microsoft.PowerShell.Utility/Add-Type.md
- Fixes [AB#1593782](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1593782)
- Fixes #4585
=> Fixes #4585 - Added content about .NET assemblies to ReferencedAssemblies parameter

reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/4.0/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/5.0/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7/Microsoft.PowerShell.Management/Get-ChildItem.md
Fixes typo in Get-ChildItem references
=> Fixes typo in Get-ChildItem references

reference/3.0/Microsoft.PowerShell.Utility/Select-String.md, reference/4.0/Microsoft.PowerShell.Utility/Select-String.md, reference/5.0/Microsoft.PowerShell.Utility/Select-String.md, reference/5.1/Microsoft.PowerShell.Utility/Select-String.md, reference/6/Microsoft.PowerShell.Utility/Select-String.md, reference/7/Microsoft.PowerShell.Utility/Select-String.md
- Fixes [AB#1593065](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1593065)
- Fixes #4709
- Updated `-List` parameter with content from [PowerShell/PowerShell #10442](https://github.com/PowerShell/PowerShell/issues/10442)
- Minor copyedits, fixed spacing in parameter sets
=> Fixes #4709 - Updated the description for List parameter

reference/docs-conceptual/samples/Appendix-1---Compatibility-Aliases.md
Original version: 81 (85 without the table)
Updated version: 87 (100 without the table)
- Fixes [AB#1595450](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1595450)
- Fixes #3752
=> Fixes #3752 - Alias names are available across PS versions

reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md, reference/6/Microsoft.PowerShell.Core/About/about_Requires.md, reference/7/Microsoft.PowerShell.Core/About/about_Requires.md
=> Added documentation for MaximumVersion key used with #Requires

reference/3.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- Fixes [AB#1597326](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1597326)
- Fixes #4624 for PS 7
- All versions: copyedits, style, paragraph reflows
- Version 6 and 7: removed `$MaximumAliasCount`, `$MaximumDriveCount`, `$MaximumErrorCount`, `$MaximumFunctionCount`, and `$MaximumVariableCount`
- No default values in v6 and v7
- Variables were removed, refer to: PowerShell/PowerShell PR 2363 and PowerShell/PowerShell Issue 2221
=> Fixes #4624 - Removed references to Suspend for PS7

reference/7/Microsoft.PowerShell.Core/ForEach-Object.md
=> Update ForEach-Object doc to include new Parallel parameter set

reference/5.0/Microsoft.PowerShell.Core/Get-Command.md, reference/5.1/Microsoft.PowerShell.Core/Get-Command.md, reference/6/Microsoft.PowerShell.Core/Get-Command.md, reference/7/Microsoft.PowerShell.Core/Get-Command.md
* `Get-Command -ShowCommandInfo` was [introduced in v5.0](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-windows-powershell-50), not v3.0
* "For more information..." and "In Windows PowerShell 2.0..." are meaningless copy/paste texts from `-All` param
=> Fix Get-Command -ShowCommandInfo

build.ps1, tools/build-updatedhelp.ps1, tools/make-updatedhelp.ps1
Updated build to use Pandoc 2.7.3
Added tools/build-updatedhelp.ps1 - This script can be used to build the updateable help for a single version folder. Using this script, a user could build and install any version of help they need.
Usage:
1. Clone the docs respository
```
cd C:\temp
git clone https://github.com/MicrosoftDocs/PowerShell-Docs.git
```
2. Run build-updatedhelp.ps1 for the version folder you want to build
```
.\build-updatedhelp.ps1 -sourceFolder C:\temp\PowerShell-Docs\reference\5.1 -Verbose
```
3. Run Update-Help  to install the newly built help
```
Update-Help -SourcePath c:\temp\updatablehelp\5.1 -Recurse -Force
```
=> Update build to use Pandoc 2.7.3

reference/7/Microsoft.PowerShell.Core/About/about_If.md, reference/7/Microsoft.PowerShell.Core/About/about_Operators.md
Fixes #4648 - ternary operator
Fixes [AB#1600440](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1600440)
=> Fixes #4648 - ternary operator

reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7/Microsoft.PowerShell.Core/About/about_If.md, reference/7/Microsoft.PowerShell.Core/About/about_Operators.md
Add missing $parameterName argument to ArgumentCompleter attribute example.
Without this argument, the sample doesn't work.
=> Fix ArgumentCompleter attribute example

dsc/reference/resources/windows/registryResource.md
Underscores are correct, and escapes are not needed here inside backticks.
=> DSC Registry note hive formatting

reference/3.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/4.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/5.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md, reference/6/Microsoft.PowerShell.Core/Invoke-Command.md, reference/7/Microsoft.PowerShell.Core/Invoke-Command.md
There is no need of placing command within ticks symbols if it's already placed in the code block. It breaks the output on the web page.
It's a cosmetic change. 
=> Removed unrequited ticks in the code example

reference/5.0/PSReadline/Set-PSReadlineOption.md, reference/5.1/PSReadline/Set-PSReadlineOption.md, reference/6/PSReadLine/Set-PSReadlineOption.md, reference/7/PSReadLine/Set-PSReadlineOption.md
- Fixes [AB#1601255](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1601255)
- Fixes #4804
=> Fixes #4804 - Syntax for PSReadLine colors

reference/3.0/Microsoft.PowerShell.Management/Get-WmiObject.md, reference/4.0/Microsoft.PowerShell.Management/Get-WmiObject.md, reference/5.0/Microsoft.PowerShell.Management/Get-WmiObject.md, reference/5.1/Microsoft.PowerShell.Management/Get-WmiObject.md
Fixes #4843 - credential not allowed for localhost
Fixes [AB#1607226](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1607226)
=> Fixes #4843 - credential not allowed for localhost

reference/7/PSReadLine/Set-PSReadlineOption.md
- Add the **ViModeChangeHandler** parameter's description and example to Set-PSReadLineOption for PowerShell 7.
- Fixes [AB#1607245](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1607245)
- Fixes #4848
=> Fixes #4848 - Added ViModeChangeHandler parameter description

reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/5.0/PSReadline/About/about_PSReadline.md, reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/5.1/PSReadline/About/about_PSReadline.md, reference/6/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/6/PSReadLine/About/about_PSReadLine.md, reference/7/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/7/PSReadLine/About/about_PSReadLine.md
Fixes #4765 - new multiline continuation support
- about_pipelines
- added note about pasting
- cleaned up style, grammar, Acrolinx (86/96) for all versions
- added v7 changes
- about_PSReadLine.md
- added note about pasting to all versions
Fixes [AB#1607250](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1607250)
=> Fixes #4765 - new multiline continuation support

reference/7/Microsoft.PowerShell.Utility/Get-Random.md
- Fixes #4859
- PS7 `Get-Random` **InputObject** parameter accepts arrays with `$null` or empty string (`''`).
- Added Example 13.
Original version: 97
=> Fixes #4859 - PS7 Get-Random InputObject parameter accepts null or empty string

reference/3.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Split.md, reference/6/Microsoft.PowerShell.Core/About/about_Split.md, reference/7/Microsoft.PowerShell.Core/About/about_Split.md
=> Add the bold tag to 'IgnorePatternWhitespace' in about_Split

reference/3.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- Fixes [AB#1610243](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1610243)
- Related to #4877
- Fixed spelling error in 3.0, 4.0, 5.0, 5.1, and 7
- Copyedits, style, paragraph reflows in all versions
=> Related to #4877 - Fixed spelling error

reference/7/Microsoft.PowerShell.Core/About/about_Operators.md
=> Add is and isnot operators to comparison operators section

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Instructs to run `pwsh-terminal` if a PowerShell Preview release was installed.
Related issue: https://github.com/PowerShell/PowerShell/issues/10713
This could also be mentioned in a documentation block for a preview version for each supported OS (see [Snap instructions](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md#snap-package) for example.)
=> Add terminal command for a Preview release

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
It was already present in the list further down; this merely adds it to the header.
Unsure about the "version(s)" info below - I honestly don't understand how that part works. (I can't see any separate branches for these versions, so maybe there's some other magic going on here... 😄) 
=> Add Debian 8 to list of supported versions

reference/3.0/Microsoft.PowerShell.Utility/Add-Member.md, reference/4.0/Microsoft.PowerShell.Utility/Add-Member.md, reference/5.0/Microsoft.PowerShell.Utility/Add-Member.md, reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md, reference/6/Microsoft.PowerShell.Utility/Add-Member.md, reference/7/Microsoft.PowerShell.Utility/Add-Member.md
Fixes #4938 - fix MemberType enum value name
Fixes [AB#1616303](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1616303)
=> Fixes #4938 - fix MemberType enum value name

reference/5.1/Microsoft.PowerShell.Management/Get-EventLog.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md, reference/5.1/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/5.1/Microsoft.PowerShell.Utility/Import-Csv.md, reference/5.1/Microsoft.PowerShell.Utility/Out-File.md, reference/5.1/Microsoft.PowerShell.Utility/Set-Alias.md, reference/5.1/Microsoft.PowerShell.Utility/Sort-Object.md, reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/6/Microsoft.PowerShell.Utility/Export-Csv.md, reference/6/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/6/Microsoft.PowerShell.Utility/Out-File.md, reference/6/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md, reference/7/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/7/Microsoft.PowerShell.Utility/Out-File.md, reference/7/Microsoft.PowerShell.Utility/Set-Alias.md
Part 1 of 2 to fix ParameterSet spacing.
- Related to [AB#1617150](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1617150)
- Related to #4954
=> Issue #4954 - Fixed cmdlet ParameterSet spacing part 1

reference/5.1/Microsoft.PowerShell.Core/Update-Help.md, reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/5.1/Microsoft.PowerShell.Management/Add-Content.md, reference/5.1/Microsoft.PowerShell.Management/Set-Content.md, reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/6/Microsoft.PowerShell.Core/Update-Help.md, reference/6/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/6/Microsoft.PowerShell.Management/Add-Content.md, reference/6/Microsoft.PowerShell.Management/Set-Content.md, reference/6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7/Microsoft.PowerShell.Core/Start-Job.md, reference/7/Microsoft.PowerShell.Core/Update-Help.md, reference/7/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/7/Microsoft.PowerShell.Management/Add-Content.md, reference/7/Microsoft.PowerShell.Management/Set-Content.md, reference/7/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
Part 2 of 2 to fix ParameterSet spacing.
- Fixes [AB#1617150](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1617150)
- Fixes #4954
- Related PR: #4960
=> Fixes #4954 - Fixed cmdlet ParameterSet spacing part 2

reference/6/Microsoft.PowerShell.Management/Remove-Service.md, reference/6/Microsoft.PowerShell.Utility/Get-Uptime.md, reference/6/Microsoft.PowerShell.Utility/Remove-Alias.md, reference/7/Microsoft.PowerShell.Management/Remove-Service.md, reference/7/Microsoft.PowerShell.Utility/Get-Uptime.md, reference/7/Microsoft.PowerShell.Utility/Remove-Alias.md
- Fixes [AB#1620501](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1620501)
- Fixes #4969
- `Get-Uptime` and `Remove-Service`: updated description that cmdlet was added in PS 6.0
`Remove-Alias` Acrolinx Scores
=> Fixes #4969 - Updated description, Remove-Alias was added in PS 6.0

reference/6/Microsoft.PowerShell.Core/Start-Job.md, reference/7/Microsoft.PowerShell.Core/Start-Job.md
Add link to to `ThreadJob` module in `Start-Job` docs. `ThreadJob` module reference was only added in v6/7 docs, hence why only those docs are changed.
=> Add link to to ThreadJob module

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/7/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
- Fixes [AB#1620502](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1620502)
- Fixes #4966
- minor Copyedits, style, paragraph reflows
- Removed the `[!NOTE]` about `Get-Help` from the section: **Position argument**
- `Register-ArgumentCompleter`: updated parameter name to `$fakeBoundParameters`, minor copyedits
about_Functions_Advanced_Parameters scores
=> Fixes #4966 - Updated the ArgumentCompleter attribute content

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
Fixes #5024 - use 8.3 name instead of hardlink
Fixes [AB#1638206](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1638206)
=> Fixes #5024 - use 8.3 name instead of hardlink

contributing/6-UPDATING-REFERENCE.md
Fix a few sentences in Contributing - Update reference doc
=> Fix a few sentences in contributing docs

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Per our conversation in shiproom, Kali and Arch are unsupported (not just experimental) and community-owned, and we should be clear as such. 
=> Make it clear on install docs that Kali and Arch are unsupported community packages

reference/6/Microsoft.PowerShell.Core/About/about_Jobs.md, reference/6/Microsoft.PowerShell.Management/Get-Service.md, reference/6/Microsoft.PowerShell.Management/Set-Service.md, reference/6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7/Microsoft.PowerShell.Core/About/about_Jobs.md, reference/7/Microsoft.PowerShell.Management/Get-Service.md, reference/7/Microsoft.PowerShell.Management/Set-Service.md, reference/7/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
- Partial set of the documents with changes introduced in PS 6.0
- Minor copyedits and style changes
=> Cmdlets and parameters with updates introduced in PS 6.0

reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/6/Microsoft.PowerShell.Management/Split-Path.md, reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/6/Microsoft.PowerShell.Utility/Out-String.md, reference/6/Microsoft.PowerShell.Utility/Sort-Object.md, reference/7/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7/Microsoft.PowerShell.Management/Split-Path.md, reference/7/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7/Microsoft.PowerShell.Utility/Out-String.md, reference/7/Microsoft.PowerShell.Utility/Sort-Object.md
=> Parameters introduced in PS 6.0 (part 1)

reference/6/Microsoft.PowerShell.Management/Start-Process.md, reference/6/Microsoft.PowerShell.Management/Test-Connection.md, reference/6/Microsoft.PowerShell.Security/Get-Credential.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Html.md, reference/6/Microsoft.PowerShell.Utility/Get-Verb.md, reference/7/Microsoft.PowerShell.Management/Start-Process.md, reference/7/Microsoft.PowerShell.Management/Test-Connection.md, reference/7/Microsoft.PowerShell.Security/Get-Credential.md, reference/7/Microsoft.PowerShell.Utility/ConvertTo-Html.md, reference/7/Microsoft.PowerShell.Utility/Get-Verb.md
=> Parameters introduced in PS 6.0 (part 2)

reference/6/Microsoft.PowerShell.Security/Get-PfxCertificate.md, reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Markdown.md, reference/6/Microsoft.PowerShell.Utility/Show-Markdown.md, reference/7/Microsoft.PowerShell.Security/Get-PfxCertificate.md, reference/7/Microsoft.PowerShell.Utility/ConvertFrom-Markdown.md, reference/7/Microsoft.PowerShell.Utility/Show-Markdown.md
=> Cmdlets and parameters introduced in PS 6.1

reference/6/Microsoft.PowerShell.Core/About/about_pwsh.md, reference/6/Microsoft.PowerShell.Core/Enter-PSHostProcess.md, reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md, reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7/Microsoft.PowerShell.Core/About/about_pwsh.md, reference/7/Microsoft.PowerShell.Core/Enter-PSHostProcess.md, reference/7/Microsoft.PowerShell.Utility/ConvertFrom-Json.md, reference/7/Microsoft.PowerShell.Utility/ConvertTo-Json.md, reference/7/Microsoft.PowerShell.Utility/Send-MailMessage.md
=> Parameters introduced in PS 6.2 (part 1)

reference/docs-conceptual/dsc/resources/authoringResourceComposite.md
Fixes #5025 
Updates example to show multiple VM renaming
docs-conceptual folder
=> Fixes #5025 - Adds example to show multiple VM creation

reference/6/Microsoft.PowerShell.Core/Enter-PSHostProcess.md, reference/7/Microsoft.PowerShell.Core/Enter-PSHostProcess.md
- Added parameter descriptions for **AppDomainName** and **HostProcessInfo**
=> Enter-PSHostProcess available on non-Windows platforms in PS 6.2

reference/5.1/Microsoft.PowerShell.Core/Start-Job.md, reference/6/Microsoft.PowerShell.Core/Start-Job.md, reference/7/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7/Microsoft.PowerShell.Core/Start-Job.md, reference/7/ThreadJob/Start-ThreadJob.md
Fixes #5012 - update info about working dir
Fixes [AB#1641775](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1641775)
- Start-Job
- Start-ThreadJob
- ForEach-Object -Parallel
=> Fixes #5012 - update info about working dir

reference/7/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/7/Microsoft.PowerShell.Management/Set-Clipboard.md
Wait for https://github.com/PowerShell/PowerShell/pull/10340 to be merged
=> Add back content for clipboard cmdlets

reference/7/Microsoft.PowerShell.Diagnostics/Get-Counter.md
Update note about limitation on `-ListSet` parameter for v7.
=> update limitations of ListSet

reference/docs-conceptual/dsc/getting-started/lnxGettingStarted.md
https://github.com/Microsoft/omi#configuring-omi-server has the correct path. This was also the correct path on my RHEL distro.
Updated a file path mentioned in a NOTE to the correct path.
=> Updating OMI Server config file path

reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/7/Microsoft.PowerShell.Archive/Compress-Archive.md
- Fixes [AB#1641675](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1641675)
- Fixes #5008
- Rewrote all the existing examples
- Added new examples for **Path** wildcards and using the pipeline
Original version: 98
=> Fixes #5008 - Rewrote the examples, added examples for Path and pipeline

reference/5.1/Microsoft.PowerShell.Utility/Select-String.md, reference/6/Microsoft.PowerShell.Utility/Select-String.md, reference/7/Microsoft.PowerShell.Utility/Select-String.md
- Fixes [AB#1643795](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1643795)
- Fixes #4479
- Added new PS 7 parameter: **NoEmphasis**
- Updated parameter sets and fixed typos in all versions
=> Fixes #4479 - Added the NoEmphasis parameter to PS7 document

reference/5.1/Microsoft.PowerShell.Management/Test-Path.md, reference/6/Microsoft.PowerShell.Management/Test-Path.md, reference/7/Microsoft.PowerShell.Management/Test-Path.md
Fixes  #5078 - update example 8
Fixes [AB#1644935](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1644935)
=> Fixes  #5078 - update example 8

reference/5.1/PowershellGet/Save-Module.md, reference/6/PowerShellGet/Save-Module.md, reference/7/PowerShellGet/Save-Module.md
Fixes #5081 - add instruction for install
Fixes [AB#1644934](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1644934)
=> Fixes #5081 - add instruction for install

reference/5.1/Microsoft.PowerShell.Utility/Update-List.md, reference/7/Microsoft.PowerShell.Utility/Update-List.md
Fixes #5009 - Add Update-List to v7
Fixes [AB#1637102](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1637102)
- Added doc to v7 folder
- Changed example to a scenario that works in v5.1 and v7.
=> Fixes #5009 - Add Update-List to v7

reference/5.1/Microsoft.PowerShell.Management/Test-Connection.md, reference/6/Microsoft.PowerShell.Management/Test-Connection.md, reference/7/Microsoft.PowerShell.Management/Test-Connection.md
Fixes #5086 - incorrect parameter name
Fixes [AB#1645587](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1645587)
=> Fixes #5086 - incorrect parameter name

reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md, reference/6/Microsoft.PowerShell.Utility/Select-Object.md, reference/7/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7/Microsoft.PowerShell.Utility/Select-Object.md
Fixes #3113 -  update not about excludeproperty
Fixes [AB#1648258](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1648258)
=> Fixes #3113 -  update not about excludeproperty

reference/6/Microsoft.PowerShell.Utility/Set-Alias.md
Indicates that hyphens are allowed, too. If more characters are allowed, they should also be specified.
=> Specify other allowed name characters

reference/docs-conceptual/developer/module/modifying-the-psmodulepath-installation-path.md
Update PSModulePath docs to also work for non-Windows systems (Path separators are colons and not semicolons on Unix, therefore using a generic API that will work on both Windows and Unix) and not be specific to Windows PowerShell any more. Some more tidying as well.
=> Update PSModulePath docs to also work for non-Windows systems and not be specific to Windows PowerShell any more

reference/5.1/Microsoft.PowerShell.Core/About/about_Function_Provider.md, reference/5.1/Microsoft.PowerShell.Management/Set-Item.md, reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md, reference/6/Microsoft.PowerShell.Core/About/about_Function_Provider.md, reference/6/Microsoft.PowerShell.Management/Set-Item.md, reference/6/Microsoft.PowerShell.Utility/Compare-Object.md, reference/7/Microsoft.PowerShell.Core/About/about_Function_Provider.md, reference/7/Microsoft.PowerShell.Management/Set-Item.md, reference/7/Microsoft.PowerShell.Utility/Compare-Object.md
Fixes #5031 - remove unnecessary $() example
Fixes [AB#1652216](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1652216)
=> Fixes #5031 - remove unnecessary $() example

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7/Microsoft.PowerShell.Core/About/about_Arrays.md
Fixes #5186  - qualify ForEach() and Where() syntax
Fixes [AB#1653248](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1653248)
=> Fixes #5186 - qualify ForEach() and Where() syntax

reference/5.1/Microsoft.PowerShell.Utility/Group-Object.md, reference/6/Microsoft.PowerShell.Utility/Group-Object.md, reference/7/Microsoft.PowerShell.Utility/Group-Object.md
- Fixes [AB#1650163](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1650163)
- Fixes #5079
- PowerShell 7:
- Create case-sensitive hash tables using the parameters **CaseSensitive** and **AsHashtable**.
- Adds Example 7 for case-sensitive hash table.
- Copyedits, style, paragraph reflows for PS 5.1, 6, and 7.
=> Fixes #5079 - PowerShell 7 Group-Object case-sensitive hash tables

reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/6/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7/Microsoft.PowerShell.Core/About/about_Redirection.md
Fixes #5164 - can only redirect to stream 1
Fixes [AB#1653089](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1653089)
=> Fixes #5164 - can only redirect to stream 1

reference/7/Microsoft.PowerShell.Utility/Select-String.md
- Fixes [AB#1650161](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1650161)
- Fixes #5090
=> Fixes #5090 - Add Culture parameter to PowerShell 7 Select-String

build.ps1
Enable build for powershell 7 docs
=> Enable builds for PowerShell v7

reference/5.1/Microsoft.PowerShell.Utility/Out-String.md, reference/6/Microsoft.PowerShell.Utility/Join-String.md, reference/6/Microsoft.PowerShell.Utility/Out-String.md, reference/7/Microsoft.PowerShell.Utility/Join-String.md, reference/7/Microsoft.PowerShell.Utility/Out-String.md
- Fixes [AB#1655090](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1655090)
- Copyedits, style, paragraph reflows for all versions
`Join-String`
- Adds H2 descriptions and content to examples.
- Adds the **UseCulture** parameter description that was missing from the document.
Original version: 80
`Out-String`
- Adds content to update the examples
Original version: 91
=> Copyedits for Join-String and Out-String

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md, reference/6/Microsoft.PowerShell.Management/Start-Process.md, reference/7/Microsoft.PowerShell.Management/Start-Process.md
Updated **Example 6: Using different verbs to start a process** for `Start-Process` so that the `$startExe.verbs` output properly matches the behavior documented in the **Parameters -Verb** section and observed within the shell.
=> Updated Start-Process Example 6 to Include 'runasuser' for Verb Availability

reference/7/Microsoft.PowerShell.Utility/Add-Type.md
Fixes #4301 - Block type update in Add-Type cmdlet
Fixes [AB#1658247](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658247)
=> Fixes #4301 - Block type update in Add-Type cmdlet

reference/docs-conceptual/whats-new/breaking-changes-ps6.md
Fixes #5200 - New-WebServiceProxy removed in v6
Fixes [AB#1658293](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658293)
=> Fixes #5200 - New-WebServiceProxy removed in v6

reference/5.1/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/6/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/7/Microsoft.PowerShell.Core/About/about_Splatting.md
$args automatic variable doesn't exist inside advanced function and that wasn't clear in about_Splatting article. 
Fixes #5227 
Fixes [AB#1658294](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658294)
-->
=> Fixes 5227. Adds context for $args in splatting in advanced functions

reference/6/ThreadJob/Start-ThreadJob.md, reference/7/ThreadJob/Start-ThreadJob.md
Fixes #5106 - clarify use of scriptblock and input
Fixes [AB#1658371](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658371)
=> Fixes #5106 - clarify use of scriptblock and input

reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/6/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7/Microsoft.PowerShell.Core/About/about_Special_Characters.md
Fixes #5120 - clarify language of escape sequences
Fixes [AB#1658645](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658645)
=> Fixes #5120 - clarify language of escape sequences

reference/docs-conceptual/components/ise/Accessibility-in-Windows-PowerShell-ISE.md
Customer pointed out that the structure of information didn't flow well for accessibility with debugging help.
Fixes #1818 
Fixes [AB#1658580](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658580)
=> [Fixes #1818] Restructures Information for Clarity on Debugging cmdlets

reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md, reference/6/Microsoft.PowerShell.Core/About/about_Trap.md, reference/7/Microsoft.PowerShell.Core/About/about_Trap.md
Trap statements work within specific scopes and needs more information for dot sourced scripts
Fixes #3067
Fixes [AB#1658896](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1658896)
=> [Fixes 3067] Adds more info on trap scoping

reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md
Example 1 doesn't even address -NoPassword and Windows 10 1909 with PowerShell 5.1 doesn't support the -PrincipalSource property at all.
=> Updated Comments

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7/Microsoft.PowerShell.Core/About/about_Functions.md
Adds clarity to `Important` note about `Begin`, `Process`, and `End` blocks
Fixes #5245 
Fixes [AB#1660248](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1660248)
=> [Fixes #5245] Clarity for function blocks

reference/5.1/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/6/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/7/Microsoft.PowerShell.Utility/Export-PSSession.md
Typo in a PowerShell example. Misnamed variable that would cause the example code not to work.
Fixes #5262 
Fixes [AB#1660588](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1660588)
=> [Fixes #5262] Typo in example

reference/docs-conceptual/dsc/pull-server/pullServer.md
Updates links to tooling that were no longer valid.
Formatting refresh
Fixes #5283 
Fixes [AB#1662319](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1662319)
=> [Fixes #5283]Updates links for correct tooling scripts

.gitignore
Help out mac users by ignoring .DS_Store files
=> Add .DS_Store to gitignore for Mac users

reference/7.0/Microsoft.PowerShell.Core/About/about_If.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md, reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md
Removed notes about ternary and chain operators, and foreach-object -parallel being experimental.
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5287
=> Remove note about Experimental features that are no longer experimental

reference/7.0/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
Documents the new `-AsPlainText` parameter on `ConvertFrom-SecureString`.
`-AsPlainText` was added to `ConvertFrom-SecureString` in https://github.com/PowerShell/PowerShell/pull/11142.
=> Add ConvertFrom-SecureString -AsPlainText documentation

reference/6/Microsoft.PowerShell.Core/Enable-PSRemoting.md
These changes update the Enable-PSRemoting help file to remove unneeded references to older versions of Windows PowerShell, and to add content that explains new behavior for PowerShell Core.
Issue #3109
=> Update Enable-PSRemoting help for PowerShell 6

.openpublishing.redirection.json
After this change:
+ https://review.docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/clear-host?branch=qinezh%2Fredirect will be redirected to https://review.docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/clear-host?branch=qinezh%2Fredirect&view=powershell-7
+ https://review.docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-verb?branch=qinezh%2Fredirect will be redirected to https://review.docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-verb?branch=qinezh%2Fredirect&view=powershell-5.1
while these two links are not working in live site:
+ https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/clear-host
+ https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.cor …
=> Remove confused entry from redirection file

reference/6/Microsoft.PowerShell.Management/Set-Location.md, reference/7.0/Microsoft.PowerShell.Management/Set-Location.md, reference/7.1/Microsoft.PowerShell.Management/Set-Location.md
Updates `Set-Location` documentation with an exaple for using `-`/`+` as the **Path** parameter Value as well as updates for formatting.
Fixes #5332 
Fixes [AB#1667146](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1667146)
=> Adds new example, minor updates, and formatting.

reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md, reference/6/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Switch.md
Updates About_Switch for to remove table, add examples and information.
Fixes #5073 
Fixes #5096 
Fixes [AB#1667615](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1667615)
=> [Fixes 5073 and 5096] - clarify behavior of switch statement

reference/5.1/Microsoft.PowerShell.Utility/Out-String.md, reference/6/Microsoft.PowerShell.Utility/Out-String.md, reference/7.0/Microsoft.PowerShell.Utility/Out-String.md, reference/7.1/Microsoft.PowerShell.Utility/Out-String.md
Fixes type in Out-String
Fixes #5354 
Fixes [AB#1668657](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1668657)
=> [Fixes 5354] Fixes Typo in Out-String

reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md, reference/6/Microsoft.PowerShell.Utility/Measure-Command.md, reference/7.0/Microsoft.PowerShell.Utility/Measure-Command.md, reference/7.1/Microsoft.PowerShell.Utility/Measure-Command.md
Fixes #5345 - scope of Measure-Command
Fixes [AB#1668647](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1668647)
=> Fixes #5345 - scope of Measure-Command

reference/5.1/Microsoft.PowerShell.Utility/Get-FormatData.md, reference/6/Microsoft.PowerShell.Utility/Get-FormatData.md, reference/7.0/Microsoft.PowerShell.Utility/Get-FormatData.md, reference/7.1/Microsoft.PowerShell.Utility/Get-FormatData.md
Fixes #5076 - doc version behavior
Fixes [AB#1669589](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669589)
=> Fixes #5076 - doc version behavior

reference/7.0/Microsoft.PowerShell.Utility/Get-Error.md, reference/7.1/Microsoft.PowerShell.Utility/Get-Error.md
Fix relative link from Get-Error to about_Try_Catch_Finally (link assumed target is in same module folder as Microsoft.PowerShell.Utility/Get-Error, but it's in Microsoft.PowerShell.Core/About/
=> Fix relative link from Get-Error to about_Try_Catch_Finally

reference/docs-conceptual/gallery/getting-started.md
Missing Update-Module and Update-Script links were added as named references with appropriate URL.
=> Fixed broken links on PSGallery Getting Started document

reference/docs-conceptual/samples/Getting-WMI-Objects--Get-CimInstance-.md
`Get-WmiObject` isn't in PS7, so doesn't belong in the docs. Most references had already been changed to use cim cmdlets, but a couple had been missed, notably the title.
There have been a couple of related issues for this, but there don't appear to be any open or referencing this page, so none to link.
=> Swap references to Get-WmiObject to CIM cmdlets

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
Changes double quotes to single quotes to show best practice and adds note about expaning vars in regular expressions. 
Fixes #5417 
Fixes [AB#1673539](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1673539)
=> [Fixes #5417] Updates about_Regular_Expressions

reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
Update to reflect code changes in behavior to construction of PSModulePath in PS7 and also modification of PSModulePath when starting WinPS or ISE
Fix https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5378
=> Update behavior of PSModulePath in PS7

reference/7.0/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md
=> Add info about WinCompat deny list

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
Under Available Authentication Options, Bearer and OAuth both stated 'Will send and RFC 6750'.
This has been updated to read as: 'Will send an RFC 6750'
docs: Fix syntax under **Authentication**
Under Available Authentication Options, **Bearer** and **OAuth** both stated 'Will send and RFC 6750'.
This has been updated to read as: 'Will send an RFC 6750'
=> docs: Fix syntax under Authentication

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
Fixes #5406 - add about_parameter_sets
Fixes [AB#1675509](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1675509)
=> Fixes #5406 - add about_parameter_sets

reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/6/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
Clarify Command precedence for not-loaded commands
fixes #4976 
Clarify that PowerShell-native commands
only take precedence over external executables
when their associated modules have been loaded.
If no external executable is found, it will
try to auto-load modules.
Clarify for PS 6 and above that it can be any native executable,
not only native Windows commands
=> Clarify Command precedence for not-loaded commands

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Scopes.md
Change "is alway the local scope" → "is always the local scope".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoftdocs/powershell-docs/5448)
=> Microsoft.PowerShell.Core/*/About/about_Scopes: Minor spelling correction

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Adding information for `$ErrorActionPreference` values
Fixes #5452 
Fixes [AB#1678680](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1678680)
=> Updates for accuracy and added information

reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/6/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/7.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/7.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
Fixes #5393  
I replaced the existing examples with my proposed improvements as described in the issue.
I also updated the parameter details for the -Native parameter set.
In the 5.1 version of the document, I fixed the example for -CommandName too, as I discovered it was clearly flawed. I tested this example on Windows PowerShell 5.1 and can confirm it works.
I tested the new pwsh 6+ examples too, and can confirm they work as intended.
=> Fix parameter names for Register-ArgumentCompleter -Native

reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/6/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/7.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/7.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
Adds Note about `Get-WinEvent` Windows API Limit and workaround
Fixes #5481 
Fixes [AB#1681492](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1681492)
=> [Fixes 5481] Updates Get-WinEvent

reference/5.1/PowershellGet/Get-InstalledModule.md, reference/6/PowerShellGet/Get-InstalledModule.md, reference/7.0/PowerShellGet/Get-InstalledModule.md, reference/7.1/PowerShellGet/Get-InstalledModule.md
Documented Output Type is incorrect.
Fixes #5487 
Fixes [AB#1682010](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1682010)
=> [Fixes 5487] Get-InstalledModule

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
Fix Issue #5498: about_regular_Expressions: fix "the the", "When"
In about_regular_Expressions the "note" on the anchor tag section " WHen defining a regex containing an $ anchor, be sure to enclose the regex using single quotes (') instead of double quotes (") or PowerShell will expand the the expression as a variable." has the word when with a capital 'h' and the word 'the' twice.
Fixed all versions of about_regular_Expressions
- [ x] This PR is ready to merge and is not **Work in Progress**
=> Issue 5498: about_regular_Expressions: fix "the the", "When"

reference/5.1/Microsoft.PowerShell.Utility/Write-Output.md, reference/6/Microsoft.PowerShell.Utility/Write-Output.md, reference/7.0/Microsoft.PowerShell.Utility/Write-Output.md, reference/7.1/Microsoft.PowerShell.Utility/Write-Output.md
Adds information about  known bug with **NoEnumerate** parameter in Write-Output.
Fixes #5376 
Fixes [AB#1682665](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1682665)
=> [Fixes 5376] Updates Write-Output

reference/6/Microsoft.PowerShell.Management/Remove-Service.md, reference/7.0/Microsoft.PowerShell.Management/Remove-Service.md, reference/7.1/Microsoft.PowerShell.Management/Remove-Service.md
Typo for -InputObject description. Should say "remove" not "stop".
Simple typo in the description of the -InputObject parameter. It should say "remove" instead of "stop"
=> Update Remove-Service.md - Typo in param desc

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/5.1/PowershellGet/Install-Module.md, reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Modules.md, reference/6/PowerShellGet/Install-Module.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.0/PowerShellGet/Install-Module.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.1/PowerShellGet/Install-Module.md, reference/docs-conceptual/developer/module/modifying-the-psmodulepath-installation-path.md
Customer noticed that the information about creation of $PSModule path. 
Fixes #5517 
Fixes [AB#1687126](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1687126)
=> [Fixes 5517] Adds information about $PSModulePath

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md
about_Classes and about_Automatic were missing information about $this and it's use in PowerShell Classes
Fixes #5548
Fixes [AB#1688124](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1688124)
=> [Fixes 5548] Adds information about $this automatic variable

reference/5.1/Microsoft.PowerShell.Management/New-Item.md, reference/6/Microsoft.PowerShell.Management/New-Item.md, reference/7.0/Microsoft.PowerShell.Management/New-Item.md, reference/7.1/Microsoft.PowerShell.Management/New-Item.md
Fixes #5552 - explain Path as LiteralPath
Fixes [AB#1688434](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1688434)
=> Fixes #5552 - explain Path as LiteralPath

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Customer noticed that two linux distros were not updated from powershell 7 previews. 
Fixes #5562 
Fixes #5343
Fixes [AB#1689396](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1689396)
=> [Fixes 5562] Updates Installing PowerShell Core on Linux

reference/5.1/Microsoft.PowerShell.Core/Out-Default.md, reference/6/Microsoft.PowerShell.Core/Out-Default.md, reference/7.0/Microsoft.PowerShell.Core/Out-Default.md, reference/7.1/Microsoft.PowerShell.Core/Out-Default.md
Removing link to external article about Out-Default behavior
Fixes #5132 
Fixes [AB#1693869](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1693869)
=> [Fixes 5132] Updates Out-Default

reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
Current about_Remote_Variables content does not specifically state that use of $Using:var is not assignable from the remote session. I added the clarifying statement (that a local variable cannot be re-assigned, modified from the remote session) and example code just after introduction of the concept of using a local variable in a remote session.
Fixes #5070
=> Added clarifying statement and example in about_Remote_Variables

reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md
Customer noticed that the current documentation suggested that `ConvertTo-XML` and `Export-Clixml` were essentially the same with the difference being in-memory vs to a file. 
This is not the case as `Export-Clixml` outputs a CLI XML schema XML document and is reimported as `System.Object`'s whereas, `ConvertTo-Xml` creates an in-memory XML document representation of all the objects passed to it. 
Fixes #3310 
Fixes [AB#1694055](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1694055)
=> Fixes #3310 - Updates ConvertTo-XML

reference/5.1/Microsoft.PowerShell.Management/Convert-Path.md, reference/5.1/Microsoft.PowerShell.Management/Get-Location.md, reference/5.1/Microsoft.PowerShell.Management/Resolve-Path.md, reference/6/Microsoft.PowerShell.Management/Convert-Path.md, reference/6/Microsoft.PowerShell.Management/Get-Location.md, reference/6/Microsoft.PowerShell.Management/Resolve-Path.md, reference/7.0/Microsoft.PowerShell.Management/Convert-Path.md, reference/7.0/Microsoft.PowerShell.Management/Get-Location.md, reference/7.0/Microsoft.PowerShell.Management/Resolve-Path.md, reference/7.1/Microsoft.PowerShell.Management/Convert-Path.md, reference/7.1/Microsoft.PowerShell.Management/Get-Location.md, reference/7.1/Microsoft.PowerShell.Management/Resolve-Path.md
Fixes #2626 - cmdlet only work on existing paths
Fixes [AB#1696272](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1696272)
=> Fixes #2626 - cmdlet only work on existing paths

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Fixes #3194 - impact of culture on parameters
Fixes [AB#1696218](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1696218)
=> Fixes #3194 - impact of culture on parameters

reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
Adds link to about_Scopes to expand on the `Using` scope modifier
Fixes #5068 
Fixes [AB#1696312](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1696312)
=> adds link to about_scopes

reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Experimental_Features.md
Fixes #5561 - clarify naming convention
Fixes [AB#1696562](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1696562)
=> Fixes #5561 - clarify naming convention

reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
Passing an explicit boolean value is not possible in the PowerShell.exe command line tools. 
Fixes #4964
=> Chasewilson ghi4964

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
The "Installing PowerShell on Linux" has a wrong name of the alpine package. The PR corrects it.
The change is minor, but the current state of documentation led me to incorrect docker-container, that I had to debug for a while.
=> Update alpine package name in installation guide

reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Remote_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Scopes.md
Replaces PR #5497 - I had to close this PR because the branch was too stale.
Fixes #5068
@PaulHigin @Jawz84 @mklement0 I made some changes based on the feedback. Let me know how this looks.
=> Add more information about 'using' scope modifier

reference/7.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Split.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md
Fixes #5631 - support for negative number added in PS7
Fixes [AB#1700648](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1700648)
=> Fixes #5631 - support for negative number added in PS7

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Added documentation to support apt-get for Debian 10.  This is the preferred method for Debian 9, this will provide the same process for users of Debian 10.
Fixes #5624
=> Added apt-get commands for Debian 10

reference/7.0/Microsoft.PowerShell.Utility/Get-Date.md
Get-Date -Uformat %s returns an string formatted with 0 decimals (string formatted as "{0:0}"). In Windows PowerShell the stated example of 1150451174.95705 was correct. A correct example for PowerShell 7 would be 1150451174.
Fixes issue #5680 
=> Update Get-Date -UFormat %s Example

reference/docs-conceptual/install/PowerShell-in-Docker.md
`docker rmi` command removes an image not a container.
=> Fix a typo

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/6/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md
edited About_Language_Mode.md for all versions and removed "PS> " from code examples. 
Fixes #5705
=> removed command prompt "PS> " from examples

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/6/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
Fixes [AB#1705676](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1705676) - Fixes #4516 - correct behavior of -debug
=> Fixes #4516 - correct behavior of -debug

reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
Update OpenSSL instructions
The required version of OpenSSL was removed for brew and renames in MacPorts
=> Update OpenSSL instructions

reference/5.1/Microsoft.PowerShell.Core/About/about_Methods.md, reference/6/Microsoft.PowerShell.Core/About/about_Methods.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Methods.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Methods.md
Fixes [AB#1705926](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1705926) - Fixes #4871 - using overloaded methods
=> Fixes #4871 - using overloaded methods

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/6/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md
Fixes [AB#1706172](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706172) - Fixes #4497 - stream output in classes
=> Fixes #4497 - stream output in classes

reference/5.1/Microsoft.PowerShell.Core/ForEach-Object.md, reference/6/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md
Fixes [AB#1706195](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1706195) - Fixes #4513 - multiple script blocks ForEach-Object
=> Fixes #4513 - multiple script blocks ForEach-Object

reference/5.1/Microsoft.PowerShell.Utility/Write-Host.md
The explanation for sample suppression of Write-Host is incorrect.
=> Update incorrect usage explanation for Write-Host

reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
Description: Unescaped @ is breaking correct rendering on LOC pages.
=> C200435,200436 - Escaping @ character to avoid localization content

reference/7.1/Microsoft.PowerShell.Core/About/about_Prompts.md
We either need a backtick at the end of the line, or to collapse the following line.
```powershell
elseif($principal.IsInRole([Security.Principal.WindowsBuiltInRole]  
```
becomes
```powershell
elseif($principal.IsInRole([Security.Principal.WindowsBuiltInRole] `
```
or
```powershell
elseif($principal.IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { "[ADMIN]: " }
```
[key]: …
=> Sample code as written produces an error.

reference/7.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
If the assignment value contains less elements than variables, all the remaining elements are not assigned any values. For example, the following command contains three variables and two values:
```powershell
$a, $b, $c = 1, 2
```
Therefore, PowerShell assigns the value 1 to the $a variable and
the value 2 to the $b variable. It will not assign any value to the $c
variable.
=> PS isn't assigning multiple vars to single value

reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md, reference/6/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Pwsh.md
Added a scenario to the `-File` parameter for `PowerShell.exe` and `Pwsh.exe` which clarifies that when using Batch scripts, you cannot use `.\` or `$PSScriptRoot` to represent the current working/execution directory and instead have to use `%~dp0`.
=> Updated About_Pwsh and About_PowerShell_exe for -File Parameter with Batch Scripts

reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md
In PowerShell 7, a new runspace is created for every loop iteration when running Foreach-Object -Parallel. In PowerShell 7.1 preview release 2, in the same scenario, loops reuse runspaces from a runspace pool unless you specify you want to create new runspaces using the `-UseNewRunspace` switch parameter. 
Fixes #5609 
Fixes [AB#1714575](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1714575)
[key]: …
=> FIXES #5609 - Adds information about new runspace behavior in Foreach -Parallel in 7.1

reference/5.1/Microsoft.PowerShell.Management/New-Item.md, reference/6/Microsoft.PowerShell.Management/New-Item.md, reference/7.0/Microsoft.PowerShell.Management/New-Item.md, reference/7.1/Microsoft.PowerShell.Management/New-Item.md, reference/docs-conceptual/samples/Working-with-Files-and-Folders.md
Customer noted that there was inadequate documentation about creating folders with `New-Item` and the **Force** parameter. This this should add clarity for future reference.
Fixes #4870 
Fixes [AB#1715078](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1715078)
=> FIXES 4870 - Updates New-Item 

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md, reference/6/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md
Customer noted that there was not official doc about Type Accelerators in PowerShell. This new doc addresses that issue.
Fixes #5474 
Fixes [AB#1715056](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1715056)
=> Fixes #5474 Adds New Conceptual Doc: about_Type_Accelerators

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/6/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md
Customer thought it would be good to have an example of importing class modules. However, after discussion, this is beyond the scope of this doc and may be added to another later on, but adding a link to the about_Using article will be helpful. 
Fixes #4292 
Fixes [AB#1718348](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1718348)
=> FIXES #4292 Adds link to about_Using

reference/docs-conceptual/components/console/PowerShell.exe-Command-Line-Help.md
Fixes [AB#1718827](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1718827)
=> Fixes #5897 - Sets powershell.exe to always 5.1 content

reference/5.1/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.0/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.1/Microsoft.PowerShell.Management/Set-Clipboard.md
There is behavior in the .NET framework clipboard that could cause the clipboard to be flushed when being set a high number of times rapidly like in a loop. Adds, this information as well as a mitigation in the notes section.
Fixes #5896 
Fixes [AB#1718616](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1718616)
=> FIXES #5896 - Updates Set-Clipboard

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Fixes #5906 by adding a placeholder for eventual Ubuntu 20.04 support and details that 20.04 is not a currently supported release
There is no information on Ubuntu 20.04 support (or current lack of it) & therefore it makes sense to add at least some information so that users understand the current situation for this distribution
=> Add details on Ubuntu 20.04 support to fix #5906

reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md
Added more concise example for using parameters in Script resource in addition to the existing example 2.
=> Add example for using parameters and variables in Script resource

reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Html.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Html.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Html.md, reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md, reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md, reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Html.md, reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md, reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md
Customer noticed that phrasing in some `ConvertTo- `  cmdlets had verbage for Microsoft .NET Framework which isn't platform agnostic. This PR addresses that issue by changing verbage to ".NET" which is platform agnostic as well as adds that verbage to some of the docs to make it more consistent accross the similar docs. 
Fixes #5932 
Fixes [AB#1721204](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1721204)
[key]: …
=> FIXES #5932 - Rephrase for Convertto-(JSON, CML, HTML, CSV) cmdlets to .NET

reference/6/Microsoft.PowerShell.Security/Get-Credential.md, reference/7.0/Microsoft.PowerShell.Security/Get-Credential.md, reference/7.1/Microsoft.PowerShell.Security/Get-Credential.md
Removes language in PowerShell 6.x + about the dialog box as it's no longer available in powershell core
Fixes #5943 
Fixes [AB#1721587](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1721587)
=> Fixes 5943 - Updates Get-Credential

reference/7.0/Microsoft.PowerShell.Utility/Measure-Command.md
In Example 3: Piping input to Measure-Command, in the code it misses the ";" and the "$" when calling the $i variable, so if you execute the command, it will throw sintax error
The command should be:
10, 20, 50 | Measure-Command -Expression {for ($i=0; $i -lt $_; $i++) {$i}}
=> incorrect_code.md

reference/6/Microsoft.PowerShell.Management/Restart-Computer.md, reference/6/Microsoft.PowerShell.Management/Stop-Computer.md, reference/7.0/Microsoft.PowerShell.Management/Restart-Computer.md, reference/7.0/Microsoft.PowerShell.Management/Stop-Computer.md, reference/7.1/Microsoft.PowerShell.Management/Restart-Computer.md, reference/docs-conceptual/whats-new/cmdlet-versions.md
`Restart-Computer` and `Start-Computer` now work in PowerShell 7.1. This removed some misinformation on `Stop-Computer` in PowerShell V 7 docs. 
Fixes #5979 
=> Fixes #5979 - Updates Start/Restart-Computer

reference/7.1/Microsoft.PowerShell.Management/Add-Content.md, reference/7.1/Microsoft.PowerShell.Management/Get-Content.md, reference/7.1/Microsoft.PowerShell.Management/Set-Content.md, reference/7.1/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.1/Microsoft.PowerShell.Utility/Export-Csv.md, reference/7.1/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/7.1/Microsoft.PowerShell.Utility/Format-Hex.md, reference/7.1/Microsoft.PowerShell.Utility/Import-Csv.md, reference/7.1/Microsoft.PowerShell.Utility/Out-File.md, reference/7.1/Microsoft.PowerShell.Utility/Select-String.md, reference/7.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
As of PowerShell 7.1, Amny cmdlets with **Encoding** parameters now have `BigEndianUTF32` as an option. This updates multiple cmdlet docs in PowerShell 7.1
Fixes #5975 
=> Fixes $5975 - Adds Support for BigEndianUTF32 support for pwsh 7.1 Cmdlets

reference/7.1/PSReadLine/About/about_PSReadLine.md
Update the default bindings and bindable functions.
`ViBackwardChar` and `ViForwardChar` are now made public.
=> Update the default bindings and bindable functions

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
Changed "a" to "an" before "SQL" in about_Functions_CmdletBindingAttribute
=> Fix some grammar (specifically, "a" to "an" before "SQL")

README.md, reference/docs-conceptual/install/Installing-PowerShell.md
'Installing Windows PowerShell' link is broken and returns '404 - Content Not Found' error. I updated the link with the correct path:
reference/docs-conceptual/windows-powershell/install/Installing-Windows-PowerShell.md
jea/ and wmf/ links have outdated paths on the PowerShell-Docs/README.md and return '404 - Content Not Found' errors. I updated both links with the correct path.
=> Update broken paths on README.md and Installing-PowerShell.md

reference/5.1/Microsoft.PowerShell.Utility/Read-Host.md, reference/6/Microsoft.PowerShell.Utility/Read-Host.md, reference/7.0/Microsoft.PowerShell.Utility/Read-Host.md, reference/7.1/Microsoft.PowerShell.Utility/Read-Host.md
Fixes [AB#1730300](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1730300) - Fixes #5021 - add MaskInput parameter
=> Fixes #5021 - add MaskInput parameter

reference/5.1/PackageManagement/Install-PackageProvider.md, reference/6/PackageManagement/Install-PackageProvider.md, reference/7.0/PackageManagement/Install-PackageProvider.md, reference/7.1/PackageManagement/Install-PackageProvider.md
Noticed that the word tag was missing from th description
=> Install-PackageProvider docs missing the word tag in description

reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Updated the PSEdition property description of the PSVersionTable variable.
The previous description implied that full featured Windows editions could not have a 'Core' value.
=> Updated PSEdition description.

reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/5.1/Microsoft.PowerShell.Utility/Export-FormatData.md, reference/5.1/Microsoft.PowerShell.Utility/Update-FormatData.md, reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/6/Microsoft.PowerShell.Utility/Export-FormatData.md, reference/6/Microsoft.PowerShell.Utility/Get-FormatData.md, reference/6/Microsoft.PowerShell.Utility/Update-FormatData.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/7.0/Microsoft.PowerShell.Utility/Export-FormatData.md, reference/7.0/Microsoft.PowerShell.Utility/Get-FormatData.md, reference/7.0/Microsoft.PowerShell.Utility/Update-FormatData.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/7.1/Microsoft.PowerShell.Utility/Export-FormatData.md, reference/7.1/Microsoft.PowerShell.Utility/Get-FormatData.md, reference/7.1/Microsoft.PowerShell.Utility/Update-FormatData.md
There are multiple updates pertaining to format.ps1xml including about topics, and `*-FormatData` cmdlets.
Fixes #2341 
=> FIXES #2341 - Updates PowerShell formatting information

reference/docs-conceptual/learn/ps101/04-pipelines.md
the example code doesn't work. ">>" needs to be removed to make it work
- [x ] Script sample articles
=> wrong code example ">>" needs to be removed

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
Customer noticed some parameter documentation was referencing `Invoke-WebRequest` and needed to be changed to `Invoke-RestMethod`
Fixes #6108 
Fixes [AB#1733236](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1733236)
=> FIXES #6108 Updates Invoke-RestMethod

.openpublishing.redirection.json
Fixes [AB#1733320](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1733320) - Fixes #6114 - fix redir for about_powershell_exe
The intent is that if you are on **about_PowerShell_exe** in version moniker `powershell-5.1` and then switch to a newer version, it should redirect to **about_pwsh**.
This may not work depending now how the version selection control works.
=> Fixes #6114 - fix redir for about_powershell_exe

reference/5.1/Microsoft.PowerShell.Management/Test-Connection.md
Adds not to clarify parameter rename in `Test-Connection` in PowerShell v 5.1
No link
=> Adds note to Test-Connection for param rename

reference/docs-conceptual/gallery/how-to/working-with-local-psrepositories.md
Pasting secrets in plain text into the console is bad and with most versions of PSReadline, the command will get logged as plaint text into the unprotected PowerShell history file.
=> working-with-local-psrepositories.md: Don't encourage users to paste secrets in plain-text into the console

reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
Hombrew's brew tap method is supported for Stable and LTS versions of PowerShell releases. This PR adds that information and updates for formatting.
Fixes #6121 
Fixes [AB#1736849](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1736849)
=> Fixes #6121 - Adds support for brew tap method

reference/7.1/Microsoft.PowerShell.Management/Split-Path.md
Replaces positional parameter value for **Qualifier** parameter yaml block. 
Updates formatting for doc. 
Fixes #6144 
Fixes [AB#1738195](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1738195)
=> Fixes #6144 - update syntax for Qualifier parameter

reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md, reference/6/Microsoft.PowerShell.Utility/Compare-Object.md, reference/7.0/Microsoft.PowerShell.Utility/Compare-Object.md, reference/7.1/Microsoft.PowerShell.Utility/Compare-Object.md
Fixes [AB#1738428](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1738428) - Fixes #6155 - clarify how objects are compared
=> Fixes #6155 - clarify how objects are compared

reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
fix version number in docs about 5.1
=> Fix version number in docs about 5.1

reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md
Customer notices that our documentation had a valued copied from the later versions and it wasnt' available in the 5.1 version. 
Fixes #6168 
Fixes [AB#1738659](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1738659)
=> Fixes #6168 Bad UFormat Value in v 5.1 Get-Date 

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Customer noticed there was a misleading sentence in about_comparison_operators
My Solution was to remove the misleading sentence entirely. I don't believe it adds anything and the surrounding material is informationally complete.
Fixes #6187 
Fixes [AB#1739706](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1739706)
[key]: …
=> Fixes #6187 - Updates about_Comparison_Operators

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Fixes [AB#1740908](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1740908) - Fixes #6198 - ValidateScript throws on $null value
Closes https://github.com/PowerShell/PowerShell/issues/12557
=> Fixes #6198 - ValidateScript throws on $null value

reference/docs-conceptual/dsc/resources/authoringResourceMOF.md
Make it clear that Get-TargetResource is often called by Set-TargetResource and Test-TargetResource.
It wasn't obvious to me from this doc how to implement `Test-ResourceTarget` and I found out by looking at a few DSC Resources on github that `Get-ResourceTarget` is often used to drive `Set-ResourceTarget` and for comparison in `Test-ResourceTarget`. I think adding this to the page gives the user a clue 
(I do not know what other versions this affects, I am in an archaic development environment :D)
[contrib]: …
=> add calls to Get-TargetResource

reference/5.1/Microsoft.PowerShell.Utility/Read-Host.md, reference/6/Microsoft.PowerShell.Utility/Read-Host.md, reference/7.0/Microsoft.PowerShell.Utility/Read-Host.md, reference/7.1/Microsoft.PowerShell.Utility/Read-Host.md
That is what you need to save the password for later use, so I think it is relevant.  The be backported if accepted.
Add a link to `ConvertFrom-SecureString` as a related link for `Read-Host`.
=> Read-Host: Add a link to ConvertFrom-SecureString

reference/docs-conceptual/windows-powershell/ise/Keyboard-Shortcuts-for-the-Windows-PowerShell-ISE.md
F11 on Step Out got double wrapped in `<kbd></kbd>`.
=> Clean up double wrapped keyboard shortcut

reference/docs-conceptual/dsc/resources/resourceAuthoringChecklist.md
Remove section that is not longer considered best practiced
Fixes #6191 
Fixes [AB#1746923](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1746923)
=> Remove section that is no longer considered best practice

reference/docs-conceptual/developer/ets/errors-exceptions.md, reference/docs-conceptual/developer/ets/members.md, reference/docs-conceptual/developer/ets/membersets.md, reference/docs-conceptual/developer/ets/methods.md, reference/docs-conceptual/developer/ets/overview.md, reference/docs-conceptual/developer/ets/properties.md, reference/docs-conceptual/developer/ets/typeconverters.md, reference/docs-conceptual/dsc/resources/authoringResource.md, reference/docs-conceptual/dsc/resources/authoringResourceClass.md, reference/docs-conceptual/dsc/resources/authoringResourceComposite.md, reference/docs-conceptual/dsc/resources/authoringResourceMOF.md, reference/docs-conceptual/dsc/resources/authoringResourceMofCS.md, reference/docs-conceptual/dsc/resources/authoringResourceMofDesigner.md, reference/docs-conceptual/dsc/resources/get-test-set.md, reference/docs-conceptual/dsc/resources/resourceAuthoringChecklist.md, reference/docs-conceptual/dsc/resources/resources.md, reference/docs-conceptual/dsc/resources/singleInstance.md, reference/docs-conceptual/toc.yml
Publishing latest changes to live
=> Publish to live

reference/7.0/Microsoft.PowerShell.Core/About/about_Throw.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Throw.md
- Update to reflect changes in PowerShell 7 as to how errors are handled or displayed
- Update mention of ".NET Framework"; PowerShell 7.x is based on .NET Core 3.x, and if I am not mistaken, will soon adopt .NET 5.0.
- Apply proper list style to a list
=> Update, to reflect changes in PowerShell 7

reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
Customer noticed, there was a missing verb and this PR fixes that
Fixes #6298
Fixes [AB#1750311](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1750311)
=> [FIXES #6298] Adds Missing Verb to approved verbs list

reference/docs-conceptual/windows-powershell/wmf/whats-new/informationstream-overview.md
Fix `OutputGusher` function call, because it is a function name and not a folder.
=> Fix OutputGusher function call

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md, reference/6/Microsoft.PowerShell.Management/Start-Process.md, reference/7.0/Microsoft.PowerShell.Management/Start-Process.md, reference/7.1/Microsoft.PowerShell.Management/Start-Process.md
Fixes [AB#1750721](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1750721)
- Fixes #6236 - clarify non-Windows behavior
- Fixes #3013
=> Fixes #6236 - clarify non-Windows behavior

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
Fix casing issues and typos in about_Operators.md
=> Fix casing issues and typos in about_Operators.md

reference/5.1/Microsoft.PowerShell.Utility/Remove-Variable.md, reference/6/Microsoft.PowerShell.Utility/Remove-Variable.md, reference/7.0/Microsoft.PowerShell.Utility/Remove-Variable.md, reference/7.1/Microsoft.PowerShell.Utility/Remove-Variable.md
Customer noticed that the **Name** Parameter in `Remove-Variable` accepted wildcards while the documentation stated that it did not. 
also updates formatting for doc
Fixes #6317 
Fixes [AB#1751248](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1751248)
=> [FIXES #6317] Updates Remove-Variable

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
Adds link to about_operator_precedence in about_Operatoers
Fixes #6321 
Fixes [AB#1751265](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1751265)
=> [FIXES #6321] Updates about_Operators

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
Fixes to '&' operators in about_Operators.md
- Replace errors with a new default concise view in 7.0 and 7.1
- Add space between `&` and its argument for consistency 
- Remove second `$job = Get-Process -Name pwsh &` from examples. It is not needed as it is the continuation of the examples.
- Add example for multiple `&` operators in single line
[key]: …
=> Fixes to '&' operators in about_Operators.md

reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/6/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Redirection.md
Remove extra *the* in about_Redirection.md
=> Remove extra *the* in about_Redirection.md

reference/5.1/Microsoft.PowerShell.Core/About/about_DesiredStateConfiguration.md, reference/5.1/PSDesiredStateConfiguration/Get-DscResource.md, reference/6/PSDesiredStateConfiguration/Get-DscResource.md, reference/7.0/PSDesiredStateConfiguration/Get-DscResource.md, reference/7.1/PSDesiredStateConfiguration/Get-DscResource.md, reference/docs-conceptual/dsc/resources/resources.md
Adds information about `Get-DscResource` working/not working with Class based resources in different versions.
Fixes #4992 
Fixes [AB#1752340](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1752340)
=> [FIXES #4992] Adds information Get-DscResource

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
Fixes for pipeline and range operators in about_Operators.md.
- Changed example in pipeline operator part, because `Get-PSSnapin` doesn't exist in PowerShell 6+
- Also changed in 5.1 for consistency
- Refactored range operator section
- Also removed the `PowerShell matches the case of the boundary characters automatically` line, because this is not technically correct.
[key]: …
=> Fixes for pipeline and range operators in about_Operators.md

reference/7.1/Microsoft.PowerShell.Security/Get-Credential.md
In PowerShell 7.1 a **ConfirmPassowrd** parameter in `Get-Credential`.
Fixes #6034 
Fixes [AB#1752681](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1752681)
=> [FIXES #6034] Updates Get-Credential

reference/docs-conceptual/learn/experimental-features.md
Adds information about new **Runspace** parameter in `*-PSBreakpoint` cmdlets to experimental features article.
Fixes #6259 
Fixes [AB#1752475](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1752475)
=> [FIXES #6259] Updates Experimental Features Article

reference/7.1/PSReadLine/About/about_PSReadLine.md
Related to https://github.com/PowerShell/PSReadLine/pull/1658
When using PSReadLine in VI-Mode, using <kbd>d</kbd><kbd>d</kbd> currently deletes the entire buffer, which seems wrong when using multiline input. This PR updates the documentation for the `DeleteLine` command, in light of the changes made to address [the corresponding issue](https://github.com/PowerShell/PSReadLine/issues/1657) in the PSReadLine repo. …
=> Updated documentation for PSReadLine’s 'DeleteLine' command in light of better handling multiline buffers.

reference/7.1/PSReadLine/About/about_PSReadLine.md
Related to https://github.com/PowerShell/PSReadLine/pull/1692.
Fixes #6357.
When using PSReadLine in VI-Mode, using <kbd>d</kbd><kbd>G</kbd> deletes lines up to the end of the multiline buffer. This PR includes the documentation for the new `DeleteEndOfBuffer` command that was introduced to support the [changes made](https://github.com/PowerShell/PSReadLine/issues/1689) to the PSReadLine repo.
=> Added documentation for new user-facing PSReadLine’s DeleteEndOfBuffer function

reference/5.1/Microsoft.PowerShell.Management/Get-Location.md, reference/5.1/Microsoft.PowerShell.Management/Set-Location.md, reference/6/Microsoft.PowerShell.Management/Get-Location.md, reference/6/Microsoft.PowerShell.Management/Set-Location.md, reference/7.0/Microsoft.PowerShell.Management/Get-Location.md, reference/7.0/Microsoft.PowerShell.Management/Set-Location.md, reference/7.1/Microsoft.PowerShell.Management/Get-Location.md, reference/7.1/Microsoft.PowerShell.Management/Set-Location.md
It seems that PlatyPS combines different list items that span several lines into one paragraph:
```
To manage location stacks, use the PowerShellLocation cmdlets, as follows.
- To add a location to a location stack, use the `Push-Location` cmdlet.
- To get a location from a location stack, use the `Pop-Location` cmdlet.
- To display the locations in the current location stack, use the Stack parameter of the   `Get-Location` cmdlet. To display the locations in a named location stack, use the StackName parameter of the `Get-Location` cmdlet. - To create a new location stack, use the StackName parameter of the `Push-Location` cmdlet.   If you specify a stack that does not exist, `Push-Location` creates the stack. - To make a location stack the current location stack, use the StackName …
```
=> Fix list formatting issues in Get-Location.md and Set-Location.md

reference/5.1/Microsoft.PowerShell.Management/Pop-Location.md, reference/5.1/Microsoft.PowerShell.Management/Push-Location.md, reference/6/Microsoft.PowerShell.Management/Pop-Location.md, reference/6/Microsoft.PowerShell.Management/Push-Location.md, reference/7.0/Microsoft.PowerShell.Management/Pop-Location.md, reference/7.0/Microsoft.PowerShell.Management/Push-Location.md, reference/7.1/Microsoft.PowerShell.Management/Pop-Location.md, reference/7.1/Microsoft.PowerShell.Management/Push-Location.md
- Bring `Push-Location` and `Pop-Location` cmdlets **-StackName** parameter description to consistency
- Fix a typo
- Remove **Windows** from **Windows PowerShell**
=> Fix issues in Push-Location.md and Pop-Location.md

reference/5.1/Microsoft.PowerShell.Utility/Sort-Object.md, reference/6/Microsoft.PowerShell.Utility/Sort-Object.md, reference/7.0/Microsoft.PowerShell.Utility/Sort-Object.md, reference/7.1/Microsoft.PowerShell.Utility/Sort-Object.md
I indicated where the default sorting properties come from and what happens if there are still none.  Fixes #6382.
=> Sort-Object: more about default properties

reference/7.1/PSReadLine/About/about_PSReadLine.md
Fixes #6361.
In order to better handle multiline buffer in PSReadLine’s VI mode, I introduced a PR to handle command <kbd>d</kbd><kbd>j</kbd> to delete the current logical line and the next _n_ requested logical lines in a multiline buffer.
A new function `DeleteNextLines` supports this behaviour.
=> [WIP] Document PSRL DeleteNextLines function

reference/5.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md, reference/6/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md, reference/7.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md, reference/7.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
The example did not work as intended.
=> Fix Certificate Provider example for .NotAfter

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
Member operator: member names may be expressions,  I think it should be explicitly said because it is quite uncommon, as far as scripting languages are concerned.
=> Member operator: member names may be expressions

reference/5.1/Microsoft.PowerShell.Management/Get-Location.md, reference/5.1/Microsoft.PowerShell.Management/Pop-Location.md, reference/5.1/Microsoft.PowerShell.Management/Push-Location.md, reference/5.1/Microsoft.PowerShell.Management/Set-Location.md, reference/6/Microsoft.PowerShell.Management/Get-Location.md, reference/6/Microsoft.PowerShell.Management/Pop-Location.md, reference/6/Microsoft.PowerShell.Management/Push-Location.md, reference/6/Microsoft.PowerShell.Management/Set-Location.md, reference/7.0/Microsoft.PowerShell.Management/Get-Location.md, reference/7.0/Microsoft.PowerShell.Management/Pop-Location.md, reference/7.0/Microsoft.PowerShell.Management/Push-Location.md, reference/7.0/Microsoft.PowerShell.Management/Set-Location.md, reference/7.1/Microsoft.PowerShell.Management/Get-Location.md, reference/7.1/Microsoft.PowerShell.Management/Pop-Location.md, reference/7.1/Microsoft.PowerShell.Management/Push-Location.md, reference/7.1/Microsoft.PowerShell.Management/Set-Location.md
- Fix a typo.
- Separate and highlight `*-Location`.
- Unify notes among `Get-`, `Set-`, `Push-` and `Pop-Location`.
*PS. I'm not sure why github marked Windows PowerShell 5.1 Set-Location.md and Pop-Location.md like this.*
=> Fix *-Location.md

reference/5.1/Microsoft.PowerShell.Management/Get-Location.md, reference/5.1/Microsoft.PowerShell.Management/Set-Location.md, reference/6/Microsoft.PowerShell.Management/Get-Location.md, reference/6/Microsoft.PowerShell.Management/Set-Location.md, reference/7.0/Microsoft.PowerShell.Management/Get-Location.md, reference/7.0/Microsoft.PowerShell.Management/Set-Location.md, reference/7.1/Microsoft.PowerShell.Management/Get-Location.md, reference/7.1/Microsoft.PowerShell.Management/Set-Location.md
`Get-Location`:
- Change `Certificate:` to `Cert:`, because there is no `Certificate:` drive, it is a provider.
- Amend `-Stack` parameter description
- Change *`Set-Location` parameter* to *`Set-Location` cmdlet*
- Fix `Get-Location` return type
`Set-Location`:
- Amend `+` and `-` **Path** parameter values description
- Enclose empty string (`""`) in backticks
[key]: …
=> Fix Get-Location.md and Set-Location.md

reference/7.1/PSReadLine/About/about_PSReadLine.md
Fixes #6451.
In order to better handle multiline buffer in PSReadLine’s VI mode, I introduced a PR to handle command <kbd>d</kbd><kbd>k</kbd> to delete the previous _n_ requested logical lines and the current logical line in a multiline buffer.
A new function `DeletePreviousLines` supports this behaviour.
=> Fix #6451 - Added documentation for PSRL 'DeletePreviousLines' function.

.vscode/settings.json, reference/docs-conceptual/learn/deep-dives/write-progress-across-multiple-threads.md, reference/docs-conceptual/toc.yml
There has been no article for how to write progress when using multithreading. 
Fixes #6160 
Fixes [AB#1753592](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1753592)
=> [Fixes #6160] Adds article for Write-Progress while multithreading

reference/5.1/Microsoft.PowerShell.Management/Get-Location.md, reference/6/Microsoft.PowerShell.Management/Get-Location.md, reference/7.0/Microsoft.PowerShell.Management/Get-Location.md, reference/7.1/Microsoft.PowerShell.Management/Get-Location.md
=> Fix Get-Location examples.

reference/5.1/Microsoft.PowerShell.Core/Get-Verb.md, reference/6/Microsoft.PowerShell.Utility/Get-Verb.md, reference/7.0/Microsoft.PowerShell.Utility/Get-Verb.md, reference/7.1/Microsoft.PowerShell.Utility/Get-Verb.md
The link to Approved Verbs was broken.
=> Fix the link to Approved Verbs

reference/7.0/PSDesiredStateConfiguration/Invoke-DscResource.md, reference/7.1/PSDesiredStateConfiguration/Invoke-DscResource.md, reference/docs-conceptual/dsc/managing-nodes/directCallResource.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md
Windows PowerShell 7 and up, `Invoke-DscResource` no longer supports WMI DSC resources. This is not apparent in the documentation. 
Fixes #6476 
Fixes [AB#1759435](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1759435)
=> FIXES #6476 - Updates to Invoke-DscResource

reference/7.1/Microsoft.PowerShell.Utility/Get-Date.md
https://github.com/PowerShell/PowerShell/pull/13084
Make the following changes to the reference of the `Get-Date` command.
- Add `-UnixTimeSeconds` parameter
- Remove `-FromUnixTime` parameter
- Change parameter sets
Close #6263
=> Add the UnixTimeSeconds parameter to the Get-Date command and removes the FromUnixTime parameter

reference/docs-conceptual/gallery/installing-psget.md
Amends and corrects the instructions for installing / updating the PackageManagement and PowerShellGet modules on computers running Windows PowerShell v3 and v4.
* Clarifications re `Save-Module` use and what "PackageManagement Preview" refers to.
* Streamlining of the commands to provide a higher degree of automation.
* Added required command for v3 to ensure that the modules are auto-loaded.
* Minor copy-editing.
[contrib]: …
=> Fix for #6469

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
Fix bitwise operators casing in about_Operators.md.
=> Fix bitwise operators casing.

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Clarifies behavior about value behavior in `$input` automatice variable. 
Fixes #6488 
Fixes [AB#1760778](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1760778)
=> [Fixes #6488] Updates about_Automatic_Variables

reference/7.1/Microsoft.PowerShell.Core/Get-Help.md
Adds information about new **Paged** parameter in Get-Help Powershell 7.1
Fixes #6448 
Fixes [AB#1763421](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1763421)
=> [Fixes #6448] Updates Get-Help 7.1

reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md, reference/6/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.0/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.1/Microsoft.PowerShell.Utility/Get-Date.md
Customer noted that the example for `Get-Date -UFormat %u` was confusing
The UFormat value `%u` shows the numbered day of the week and our current example is: `Monday = 1`. The current example could cause the assumption that if Monday = 1 then Sunday = 7, but in reality, Sunday = 0. 
This PR updates the example to show Sunday = 0 to clarify the count.
Fixes #6546 
Fixes AB#
[key]: …
=> FIxes #6546 - Updates Get-Date

reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
The latest release of .NET core now requires macOS 10.13 or higher. This affects PowerShell as well. 
Fixes #6519 
Fixes [AB#1762940](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1762940)
=> Fixes #6519 - Updates installing PowerShell on macOs

.openpublishing.redirection.json
- `.yml` redirections with document_id are not supported in v2, they are exactly the same as setting to `false` .
- In order not to change the generated document_id during migration, they need to be turned to `false`. 
- However, the redirect_document_id: true will be supported after migrated to `docfx-v3`.
=> fix redirection rules

reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Fixes https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6551.
Adding a note, clarifying that PS5.1 is supported effectively indefinitely
Frequent confusion about Windows PowerShell support cycle when higher numbers are going out of support.
=> Adding note on 5.1 Support Lifecycle

reference/docs-conceptual/learn/experimental-features.md
PSNativePSPathResolution is being moved out of experimental features in PowerShell 7.1
Fixes #6557 
Fixes [AB#1765414](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1765414)
=> [Fixes #6557] Updates Experimental-Features

reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md
Output for examples mentioned in about_trap help file for 5.1 are actually from PowerSehll 7.x with new error view.
Fix for #6580
=> Correct output in examples in abput_trap for PS 5.1 as it isof 7.x type

reference/7.1/Microsoft.PowerShell.Core/Get-Help.md
**Paged** parameter has been backed out of `Get-Help` in PowerShell 7.1
Fixes #6556 
Fixes [AB#1767661](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1767661)
=> Fixes #6556 Updates Get-Help

reference/7.1/PSReadLine/About/about_PSReadLine.md
Fixes #6497.
Supports a new `DeleteRelativeLines` method for PSReadLine to implement the <kbd>d</kbd>, <kbd>g</kbd>,<kbd>g</kbd>Vi command.
=> Fixes #6497 - Document new PSRL method DeleteRelativeLines.

reference/7.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/docs-conceptual/learn/experimental-features.md
Fixes [AB#1770917](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1770917) - PSNullConditionalOperators
Fixes [AB#1770916](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1770916) - update fir $?
=> Fixes AB#1770917 - PSNullConditionalOperators

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/6/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md
Fixes [AB#1772245](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1772245) - Fixes #6630 - fix typo in new() method
=> Fixes #6630 - fix typo in new() method

reference/docfx.json
This PR is dependent on https://github.com/MicrosoftDocs/DocsMedia/pull/284
Do not merge until the dependent PR is merged.
=> Fixes #6639 - add social image url metadata

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
Adds information about escaping curly braces when using formatting operators
Fixes #6667 
Fixes [AB#1775143](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1775143)
=> Fixes #6667 - Updates about_Operators

reference/7.1/PSReadLine/Set-PSReadLineOption.md
Rename `PredictionColor` to `InlinePredictionColor` to make the color setting unambiguous.
We will have a couple more color settings for the list view, so rename `PredictionColor` to make it more specific.
Make the PR a draft for now. Will move it out of draft after the corresponding PR https://github.com/PowerShell/PSReadLine/pull/1860 gets merged.
[key]: …
=> Rename 'PredictionColor' to 'InlinePredictionColor'

reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
- Copyedit the document to eliminate verbosity and tortured language. Most changes are the recommendations of [Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/).
- Eliminate self-contradictions
- **Approved Verbs for PowerShell Commands:**
- Change "Microsoft .NET Framework classes" to ".NET classes", not just for brevity, but also because this document encompasses .NET Core and the future .NET 5 as well.
- Move the example to the end of the paragraph for cohesion's sake.
- Use active voice along "we" and "you" instead of passive voice
- **Verb Naming Rules:**
- Rename to "Verb Naming Recommendations" because the section repeatedly said that its items are guidelines, not rules
- Change the topic sentence to say that the items listed herein help ensure …
=> Copyediting and overhaul

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
1. Clarification about unary `,`.
2. Sourced scripts can take parameters too.
=> About passing parameters to sourced scripts

reference/7.0/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/7.0/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.1/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/7.1/Microsoft.PowerShell.Management/Set-Clipboard.md
* Add missing "`>`"
* Move to Description (Get-Clipboard)
<del>- [ ] Includes content related to issues and PRs - see Closing issues using keywords.</del>
=> Fix NOTE in Get/Set-Clipboard

reference/5.1/Microsoft.PowerShell.Core/Set-StrictMode.md, reference/6/Microsoft.PowerShell.Core/Set-StrictMode.md, reference/7.0/Microsoft.PowerShell.Core/Set-StrictMode.md, reference/7.1/Microsoft.PowerShell.Core/Set-StrictMode.md
1. PowerShell 7 has changed the way the error messages are displayed. This PR reflects that change in the examples of this cmdlet. I've updated the appropriate doc pages for versions 7 and 7.1.
2. Enforce [the correct way of comparing with `$null` in examples](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/RuleDocumentation/PossibleIncorrectComparisonWithNull.md). This PR has effected this change in the appropriate doc pages for versions 5.1, 6, 7, and 7.1.
- If the PR is a work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the …
=> Set-StrictMode: Rewrite output to match PowerShell 7 and later

reference/docs-conceptual/whats-new/breaking-changes-ps6.md
The "Create-WinEvent" cmdlet does not exist. It seems the author intended to call out the New-WinEvent cmdlet instead.
The PowerShell 6.x breaking changes doc recommends "Create-WinEvent" as an alternative to the EventLog cmdlets. That cmdlet doesn't exist and was most likely intended to be "New-WinEvent"
=> Recommend New-WinEvent instead of Create-WinEvent

reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md
Added 'Important' note block to raise awareness that the list of specifiers available in Windows PowerShell is not the same as with PowerShell 6 and newer.
=> Important note about UFormat specifiers

reference/docs-conceptual/dsc/configurations/add-parameters-to-a-configuration.md
Removing errant comma from example.
Sample provided would not have compiled with errant comma.
=> Remove errant comma from add-parameters-to-a-configuration.md

reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md
I'm not totally sure if this is correct. But as far as I can tell, $WhatIf doesn't exist, and it should be $WhatIfPreference. This was really confusing when reading this doc, so I'm submitting this as a typo PR, but hopefully someone can fact check this.
The doc/article incorrectly uses `$WhatIf` when it should be `$WhatIfPreference`
[key]: …
=> Incorrect variable name

reference/docs-conceptual/developer/hosting/adding-and-invoking-commands.md
Correct code example for calling PowerShell in C#
Example uses `Get-Process` cmdlet with `Name` and `Id` parameters together which is not possible as they both are Mandatory parameter from two different parameter sets.
=> Correct code example for calling PowerShell in C#

reference/docs-conceptual/toc.yml, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-62.md, reference/docs-conceptual/whats-new/breaking-changes-ps6.md, reference/docs-conceptual/whats-new/known-issues-ps6.md
Restore v6 release notes
- V6 release notes contain breaking changes from PS5.1 - need these notes for historical reference
=> Restore v6 release notes

reference/7.2/PSReadLine/About/about_PSReadLine.md
Related to [PSReadLine#2001](https://github.com/PowerShell/PSReadLine/pull/2001).
Fixes #6958.
Using <kbd>d</kbd><kbd>^</kbd> currently deletes the entire selection from the first non blank character in the buffer up to the cursor position. However, when using multiline input, it should delete only from the first non blank character in the current logical line instead.
The PSReadLine’s `DeleteLineToFirstChar` is changed to better reflect the new behaviour. Accordingly, the text for the documention is updated.
title and …
=> Updated doc for PSRL DeleteLineToFirstChar to better reflect changes

reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/7.0/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/7.1/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.2/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Random.md
Fixed typo, `ForEach-Object` instead of `For-EachObject`
=> Fixed Typo

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Redirection.md
**I re-wrote the `about_Comparison_Operators` completely.** As such, it would be futile to look at the diff; this new version is 99% different.
The current `about_Comparison_Operators` page suffers from several problems, some of which you can see in the screenshots below. These problems include:
1. TOC not being practically useful.
1. The first table is too long because it contains orphaned rows and empty rows.
1. Examples that confuse and make no sense, e.g. an unused function called "get-parms" (sic.)
1. Outright incorrect sentences, e.g. "Returns true when _reference value_ contained in a collection" (must be "Returns true when _test value_ contained in a collection";)
1. Out of context information snippets that are unlikely to be seen when this page is used as a reference, e.g. the …
=> Rewrote the whole about_Comparison_Operators document from top to bottom

reference/5.1/Microsoft.PowerShell.Core/About/about_Continue.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Continue.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Continue.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Continue.md
Fixed typo in About_Continue for all release3d
Resolves #7401
- [x ] Version 7.1 content
- [x ] Version 7.0 content
- [x ] Version 5.1 content
- [x ] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x ] PR has a meaningful title
- [x ] PR is targeted at the _staging_ branch
- [ x] All relevant versions updated
- [x ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [x ] This PR is ready to merge and is not **Work in Progress**
title and …
=> Fix typo in about_Continue

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- add IEquatable example
- fix incorrect interface name System.IComparable -> System.IEquatable\<T>
=> add IEquatable example in about_Comparison_Operators

reference/7.0/Microsoft.PowerShell.Management/Add-Content.md, reference/7.0/Microsoft.PowerShell.Management/Clear-Content.md, reference/7.0/Microsoft.PowerShell.Management/Get-Content.md, reference/7.0/Microsoft.PowerShell.Management/Get-Item.md, reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md, reference/7.0/Microsoft.PowerShell.Management/Set-Content.md, reference/7.1/Microsoft.PowerShell.Management/Add-Content.md, reference/7.1/Microsoft.PowerShell.Management/Clear-Content.md, reference/7.1/Microsoft.PowerShell.Management/Get-Content.md, reference/7.1/Microsoft.PowerShell.Management/Get-Item.md, reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md, reference/7.1/Microsoft.PowerShell.Management/Set-Content.md, reference/7.2/Microsoft.PowerShell.Management/Add-Content.md, reference/7.2/Microsoft.PowerShell.Management/Clear-Content.md, reference/7.2/Microsoft.PowerShell.Management/Get-Content.md, reference/7.2/Microsoft.PowerShell.Management/Get-Item.md, reference/7.2/Microsoft.PowerShell.Management/Remove-Item.md, reference/7.2/Microsoft.PowerShell.Management/Set-Content.md
Recreation of [PR by @kyanha](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6648) to move the changes to the correct version.
Thank you @kyanha for the contribution here!
Fixes #7063
Fixes [AB#1802936](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1802936)
=> Fixes #7063 - Updates Add-Content + 5 more

reference/5.1/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Data_Sections.md
Fix inconsistent case of fictive function Format-Xml. The function was spelled Format-XML in one place and Format-Xml in another.
=> Fix inconsistent case of fictive function Format-Xml

reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md
} 3>&1 2>&1 > P:\Temp\redirection.log
correct is
} 3>&1 2>&1 > C:\Temp\redirection.log
=> line 101: typo in path name (disk name)

reference/docs-conceptual/PowerShell-Support-Lifecycle.md
Add PowerShell 6.1 and 6.2 release dates to Release History. Fix incorrect .NET Core version for 6.0 release.
Change is to /docs-conceptual folder.
=> Add PowerShell 6.1 and 6.2, fix .NET Core version in Version History table

reference/docs-conceptual/install/PowerShell-Core-on-ARM.md
Updated to map PowerShell 7.0 to .NET Core 3.1 and PowerShell 7.1 to .NET 5
Updated Windows 10 Client to be 1703+ instead of 1607+
Update .NET Core 5.0 to .NET 5
=> fixes typo in #6930, change .NET Core 5.0 to .NET 5

reference/5.1/Microsoft.PowerShell.Management/Write-EventLog.md
Fixes [AB#1809053](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1809053) - Fixes #7135 - not all event logs require admin
=> Fixes #7135 - not all event logs require admin

reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.0/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.1/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.2/Microsoft.PowerShell.Host/Start-Transcript.md
Adds information about default encoding behavior in ``Start-Transcript`` for different versions of PowerShell
Fixes #7175
Fixes [AB#1811023](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1811023)
=> Fixes #7175 - Updates Start-Transcript

reference/7.2/Microsoft.PowerShell.Core/Get-ExperimentalFeature.md
Updates 7.2 doc for `Get-ExperimentalFeature` to full type name for output.
Fixes #7174
Fixes [AB#1811192](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1811192)
=> Fixes #7174 - Updates Get-ExperimentalFeature

reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
=> Fix inconsistent variable casing

reference/7.2/Microsoft.PowerShell.Utility/Get-Date.md
Update Get-Date -UFormat documentation to match the new (corrected) behavior in #7180 
=> New (fixed) Get-Date -UFormat %u behavior

reference/7.2/PSReadLine/About/about_PSReadLine.md
Update PSReadLine about doc for predictive intellisense and dynamic help.
The dynamic help content is moved to the `Miscellaneous functions` section because they belong to that group.
Prediction functions were added but not added to the about-* doc.
=> Update PSReadLine about doc for predictive intellisense and dynamic help

reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Html.md
Example 3 had an erroneous set of backticks inside the fenced code-block. Hope this helps.
- [?] All relevant versions updated
=> Remove format bug in example 3

reference/5.1/PSReadLine/Set-PSReadLineKeyHandler.md, reference/7.0/PSReadLine/Set-PSReadLineKeyHandler.md, reference/7.1/PSReadLine/Set-PSReadLineKeyHandler.md, reference/7.2/PSReadLine/Set-PSReadLineKeyHandler.md
Adds info to **Chord** parameter in `Set-PSReadLineKeyHandler`.
Fixes #7255
Fixes [AB#1817823](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1817823)
=> Fixes #7255 - Updates Set-PSReadLineKeyHandler

reference/7.2/PSReadLine/About/about_PSReadLine.md
Fix #7259
The bind-able function `SelectCommandArgument` was added to PSReadLine, as well as the default key binding `Alt+a` to it for the `Windows` and `Emacs` edit modes. Update the `about` doc for 'SelectCommandArgument'.
=> Add doc for 'SelectCommandArgument'

reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md
Adds example to highlight variable behavior in 7.1 and 7
Fixes #5436
Fixes [AB#1818623](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1818623)
=> Fixes #5436 - Updates ForEach-Object

reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Troubleshooting.md
Incorrect command used in example.
N/A
=> Fix incorrect command used in doc example

reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md
Executing with `properties` results in an error: "A parameter cannot be found that matches parameter name 'Properties'."
=> Correct property name

reference/docs-conceptual/developer/cmdlet/how-to-invoke-scripts-within-a-cmdlet.md
A very minor correction.
Please check the page https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/how-to-invoke-scripts-within-a-cmdlet?view=powershell-7.1. The second code snippet  hint's the language is `C` although it should be `C#`.
- [] Learning PowerShell
- [ x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ x] PR has a meaningful title
- [x ] PR is targeted at the _staging_ branch
- [x ] This PR is ready to merge and is not **Work in Progress** …
=> Fix incorrect language hint for a code snippet

reference/5.1/Microsoft.PowerShell.Utility/Read-Host.md, reference/7.0/Microsoft.PowerShell.Utility/Read-Host.md, reference/7.1/Microsoft.PowerShell.Utility/Read-Host.md, reference/7.2/Microsoft.PowerShell.Utility/Read-Host.md
Adds note about input limit in `Read-Host`
Fixes #7307
Fixes [AB#1822500](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1822500)
=> Fixes #7307 - Updates Read-Host

reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md
Correct a typo (there were two examples numbered 9.)
=> Fix example numbering in Get-ChildItem.md

reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md
Adds note about `PipelineVariable` variables not being supported in `Foreach-Object -Parallel` scenarios.
Fixes #7380
Fixes [AB#1830264](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1830264)
=> Fixes #7380 - Updates ForEach-Object

reference/5.1/Microsoft.PowerShell.Utility/Get-TypeData.md, reference/7.0/Microsoft.PowerShell.Utility/Get-TypeData.md, reference/7.1/Microsoft.PowerShell.Utility/Get-TypeData.md, reference/7.2/Microsoft.PowerShell.Utility/Get-TypeData.md
* "\*Eventing\*" type data is not found. It should be replaced with basic type data.
* Using `-TypeName` parameter explicitly instead of pipeline to make it easier to understand
* (x) types -> (o) type data
=> Update Get-TypeData Example 2

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Adds information about `` automatic variable being available in `switch` statement.
Fixes #7383
Fixes [AB#1830333](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1830333)
=> Fixes #7383 - Updates about_Automatic_Variables

reference/5.1/Microsoft.PowerShell.Core/About/about_Split.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Split.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Split.md
Fixes [AB#1830928](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1830928) - Fixes #7393 - clarify max-strings behavior
=> Fixes #7393 - clarify max-strings behavior

reference/5.1/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7.0/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7.1/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7.2/Microsoft.PowerShell.Utility/Set-Alias.md
Updates `Set-Alias` for flag-based enumeration parameters.
Fixes #7418
Fixes [AB#1831787](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1831787)
=> Fixes #7418 - Updates Set-Alias

reference/5.1/Microsoft.PowerShell.Utility/New-Alias.md, reference/7.0/Microsoft.PowerShell.Utility/New-Alias.md, reference/7.1/Microsoft.PowerShell.Utility/New-Alias.md, reference/7.2/Microsoft.PowerShell.Utility/New-Alias.md
Updates `New-Alias` for flag-based enumeration parameters.
Fixes #7416
Fixes [AB#1832031](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832031)
=> Fixes #7416 - Updates New-Alias

reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Updates `Invoke-WebRequest` for flag-based enumeration parameters.
@sdwheeler PowerShhell 5.1 doc is just reformatting, no flag enumeration changes.
Fixes #7412
Fixes [AB#1832566](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832566)
=> Fixes #7412 - Updates Invoke-WebRequest

reference/5.1/Microsoft.PowerShell.Core/Get-Command.md, reference/7.0/Microsoft.PowerShell.Core/Get-Command.md, reference/7.1/Microsoft.PowerShell.Core/Get-Command.md, reference/7.2/Microsoft.PowerShell.Core/Get-Command.md
Updates `Get-Command` for flag-based enumeration parameters.
Fixes #7413
Fixes [AB#1832552](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832552)
=> Fixes #7413 - Updates Get-Command

reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
Updates `Invoke-RestMethod` for flag-based enumeration parameters.
@sdwheeler. If you can double check the changes to the authentication parameter to make sure my info is correct, it just looked like it wasn't right.
Fixes #7411
Fixes [AB#1832680](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832680)
[key]: …
=> Fixes #7411 - Updates Invoke-RestMethod

reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Updates information about ``$ErrorView`` **ConciseView** option. In PowerShell 7.2, if an error is thrown from a script module, it is now a single line error. There is no more location data and if you want to see that you will use ``Get-Error``.
Fixes #7301
Fixes [AB#1834385](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1834385)
[key]: …
=> Fixes #7301 - Updates about_Preference_Variables

reference/7.2/Microsoft.PowerShell.Core/Enter-PSSession.md, reference/7.2/Microsoft.PowerShell.Core/Invoke-Command.md, reference/7.2/Microsoft.PowerShell.Core/New-PSSession.md
Adds ``-ConnectingTimeout`` parameter information in PowerShell 7.2 docs.
Fixes #7464
Fixes [AB#1836019](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836019)
=> Fixes #7464 - Updates Enter-PSSession + 2 more

reference/5.1/Microsoft.PowerShell.Utility/Out-String.md, reference/7.0/Microsoft.PowerShell.Utility/Out-String.md, reference/7.1/Microsoft.PowerShell.Utility/Out-String.md, reference/7.2/Microsoft.PowerShell.Utility/Out-String.md
- Replace "strings" with "string" in **Synopsis**
- Replace "_and_ array of strings" with "_an_ array of strings" in **Description**
- Replace "rather concatenating" with "rather _than_ concatenating" in **Example 2**
=> fix: Fix minor typos & grammatical errors in `Out-String.md`

reference/docs-conceptual/windows-powershell/ise/Exploring-the-Windows-PowerShell-ISE.md
Tooltip title says "Clear Console Pane", not Output Pane (powershell v5.1.19041.x), so even though we understand what this is, just wanting to be as accurate as possible when having any type of documentation  reference real world software and what the user exactly sees.
=> update menubar titles and their description

reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md
`uninstall` needs to come before the `--cask` flag. otherwise it gives: `Error: Unknown command: --cask`
=> fix: uninstall command

reference/docs-conceptual/dev-cross-plat/performance/module-authoring-considerations.md, reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md, reference/docs-conceptual/toc.yml
Fixes [AB#1840690](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1840690) - Migrate perf docs from Windows docset
=> Migrate perf docs from Windows docset

reference/docs-conceptual/install/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
Fix small typo in final NOTE section of the file Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
=> Fix typo in final NOTE section

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.0/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md
Clarifies **Include** and **Exclude** parameter behavior in `Get-ChildItem`.
Fixes #7579
Fixes [AB#1843738](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1843738)
=> Fixes #7579 - Updates Get-ChildItem

reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md
-GetCredential is not a parameter for Read-Host. -AsSecureString is.
=> Correct wrong parameter for Read-Host example

reference/docs-conceptual/lang-spec/chapter-01.md, reference/docs-conceptual/lang-spec/chapter-02.md, reference/docs-conceptual/lang-spec/chapter-03.md, reference/docs-conceptual/lang-spec/chapter-04.md, reference/docs-conceptual/lang-spec/chapter-05.md, reference/docs-conceptual/lang-spec/chapter-08.md, reference/docs-conceptual/lang-spec/chapter-09.md, reference/docs-conceptual/lang-spec/chapter-10.md, reference/docs-conceptual/lang-spec/chapter-11.md, reference/docs-conceptual/lang-spec/chapter-12.md, reference/docs-conceptual/lang-spec/chapter-14.md
=> Fix links to cmdlets

reference/docs-conceptual/learn/deep-dives/everything-about-null.md
Updates null article to highligh "empty $null" behavior when passed to a function parameter.
Fixes #7652
Fixes [AB#1847849](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1847849)
=> Fixes #7652 - Updates everything-about-null

reference/5.1/Microsoft.PowerShell.Management/Get-Content.md, reference/7.0/Microsoft.PowerShell.Management/Get-Content.md, reference/7.1/Microsoft.PowerShell.Management/Get-Content.md, reference/7.2/Microsoft.PowerShell.Management/Get-Content.md
Fixes #7715 - Example 4 gets last line instead of first and last.
=> Fixes #7715 - example 4 gets last line

reference/5.1/Microsoft.PowerShell.Core/About/about_Enum.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Enum.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Enum.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Enum.md
Fixes [AB#1853880](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1853880) - Fixes #7722 - clarify enum method behavior
=> Fixes #7722 - clarify enum method behavior

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Updates information about ``$Matches`` automatic variable behavior.
Fixes #7776
Fixes [AB#1857552](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1857552)
=> Fixes #7776 - Updates about_Automatic_Variables + 1 more

reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Updates to about_Comparison_Operators to cover when $Matches is NOT set.
This is just for `Preview` until I get the wording correct.  Then I'll propagate it back to the previous versions.
Address issue #7776 
=> WIP: Correct the description of when $Matches is set for -not/match operators

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Finishes work for #7776
Applies the changes made to 7.2 in PR #7783 to 7.1, 7.0 and 5.1.
=> Migrate changes in PR 7783 back to previous versions

reference/5.1/Microsoft.PowerShell.Management/Rename-ItemProperty.md, reference/7.0/Microsoft.PowerShell.Management/Rename-ItemProperty.md, reference/7.1/Microsoft.PowerShell.Management/Rename-ItemProperty.md, reference/7.2/Microsoft.PowerShell.Management/Rename-ItemProperty.md
Fix two issues in `Rename-ItemProperty` existing documentation:
* Documentation states that the `Path` parameter specifies: _"the path of the item to rename"_. This is incorrect, as the cmdlet does not rename the item, but a property of the item.
* Documentation states that the `LiteralPath` parameter specifies _"a path to one or more locations"_. This is incorrect, only a single location may be specified.
- [NA] Includes content related to issues and PRs - see [Closing issues using keywords][key].
[key]: …
=> Fix `Rename-ItemProperty` `-Path` and `-LiteralPath` sections

reference/7.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_CommonParameters.md
Adds information about ``break`` as an acceptable value for common action parameters
Fixes #7798
Fixes [AB#1858646](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1858646)
=> Fixes #7798 - Updates about_CommonParameters

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Corrects language around case-sensitive comparison operators
Fixes #7803
Fixes [AB#1859239](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1859239)
=> Fixes #7803 - Updates about_Comparison_Operators

reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
Updates about_Intrinsic_Members to add Properties section and **Count** and **Length** properties
Fixes #7795
Fixes [AB#1858676](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1858676) 1858922
=> Fixes #7795 - Updates about_Intrinsic_Members

reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Adds **ArgumentCompletions** attribute to about_Functions_Advanced_Parameters
Fixes #7767
Fixes [AB#1858438](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1858438)
=> Fixes #7767 - Updates about_Functions_Advanced_Parameters

reference/docs-conceptual/whats-new/differences-from-windows-powershell.md, reference/docs-conceptual/whats-new/unix-support.md, reference/includes/product-terms.md
Fixes [AB#1860549](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1860549) - Remove "Core" from branding in release notes
=> Remove "Core" from branding in release notes

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
The original version of the [about_Preference_Variables](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables) page is hard to browse:
It is a large bulk of prose without linking from the heading table to each of the preference variables in the documentation. So it's very cumbersome and time-consuming to find parameter value information fast.
Thus, for version `7.0`, `7.1`, and `7.2`, I ...
1. added hyperlinks reaching from the heading default value table to each of the preference variable documentation sections in the file,
2. added references to corresponding enumeration values from `System.Management.Automation` namespace to each of the preference variable documentation sections in the file,
3. cleaned up the default value heading …
=> Reference hyperlinks added to `about_Preference_Variables`

reference/5.1/Microsoft.PowerShell.Utility/Sort-Object.md, reference/7.0/Microsoft.PowerShell.Utility/Sort-Object.md, reference/7.1/Microsoft.PowerShell.Utility/Sort-Object.md, reference/7.2/Microsoft.PowerShell.Utility/Sort-Object.md
Updates Sort-Object to clarify hashtable and scriptblock in ``-Property`` parameter. Updates for formatting
Fixes #7854
Fixes [AB#1862205](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862205)
=> Fixes #7854 - Updates Sort-Object

reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md
Removed small typo in `PSBoundParameters` section.
Only text, cmdlets were not changed.
=> Removed PSBoundParameters duplicate variable

reference/7.2/Microsoft.PowerShell.Utility/Write-Error.md, reference/docs-conceptual/learn/experimental-features.md
- Updates write-error positional
- fixes broken link in experimental features
Fixes #6771
Fixes [AB#1864082](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1864082)
=> Fixes #6771 - Updates Write-Error + 1 more

reference/5.1/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.0/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.1/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.2/Microsoft.PowerShell.Management/Set-Clipboard.md
Adds ``-PassThru`` parameter to PowerShell 7.2 docs and formats headers for all versions
Fixes #6690
Fixes [AB#1777598](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1777598) 1864106
=> Fixes #6690 - Updates Set-Clipboard

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Adds ``$ErrorView`` information for all versions
Fixes #7910
Fixes [AB#1864464](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1864464)
=> Fixes #7910 - Updates about_Automatic_Variables

reference/5.1/Microsoft.PowerShell.Utility/Write-Output.md, reference/7.0/Microsoft.PowerShell.Utility/Write-Output.md, reference/7.1/Microsoft.PowerShell.Utility/Write-Output.md, reference/7.2/Microsoft.PowerShell.Utility/Write-Output.md
Fixes [AB#1866922](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1866922) - Fixes #7882 - Clarify NoEnumerate behavior
=> Fixes #7882 - Clarify NoEnumerate behavior

reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md
Updates behavior for **File** param on windows in PowerShell 7.2
Fixes #7904
Fixes [AB#1867221](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1867221)
=> Fixes #7904 - Updates about_Pwsh

reference/5.1/Microsoft.PowerShell.Core/Debug-Job.md, reference/5.1/Microsoft.PowerShell.Utility/Debug-Runspace.md, reference/5.1/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md, reference/5.1/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md, reference/5.1/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md, reference/5.1/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.md, reference/5.1/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md, reference/7.0/Microsoft.PowerShell.Core/Debug-Job.md, reference/7.0/Microsoft.PowerShell.Utility/Debug-Runspace.md, reference/7.0/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md, reference/7.0/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md, reference/7.0/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md, reference/7.0/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.md, reference/7.0/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md, reference/7.1/Microsoft.PowerShell.Core/Debug-Job.md, reference/7.1/Microsoft.PowerShell.Utility/Debug-Runspace.md, reference/7.1/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md, reference/7.1/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md, reference/7.1/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md, reference/7.1/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.md, reference/7.1/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md, reference/7.2/Microsoft.PowerShell.Core/Debug-Job.md, reference/7.2/Microsoft.PowerShell.Utility/Debug-Runspace.md, reference/7.2/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md, reference/7.2/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md, reference/7.2/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md, reference/7.2/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.md, reference/7.2/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md, reference/docs-conceptual/learn/experimental-features.md
Fixes [AB#1869268](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1869268) - Fixes #6560 - PSManageBreakpointsInRunspace no longer experimental
=> Fixes #6560 - PSManageBreakpointsInRunspace no longer experimental

reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.0/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md
Fixes [AB#1869583](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1869583) - Fixes #7988 - Fix PS5.1 PSModulePath location
=> Fixes #7988 - Fix PS5.1 PSModulePath location

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
Fix: The command to create the symbolic link needs to be fully enclosed in the single quotes to escape the $pshome variable, otherwise bash messes with it.
=> Fix symlink creation command for Raspbian

reference/docs-conceptual/developer/format/creating-a-list-view.md
The final code example closed a `[` with a `}`. This PR fixes that.
=> Fix mismatched brackets.

reference/docs-conceptual/lang-spec/chapter-07.md
I discovered two sentence fragments in the specification and corrected them. 
/docs-conceptual 
=> Fix two sentence fragments in spec chapter 7.

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Fixes [AB#1873499](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1873499) - Fixes #8048 - fix OutputRendering
=> Fixes #8048 - fix OutputRendering

reference/5.1/Microsoft.PowerShell.Core/About/about_Scripts.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Scripts.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Scripts.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Scripts.md
This PR adds a missing link to the referenced about_Requires article to about_Scripts docs.
=> about_Scripts: adding missing link to about_Requires

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
Update Parsing and Quoting articles
- Fixes [AB#1873625](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1873625) - Fixes #6149
- Fixes [AB#1873626](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1873626) - Fixes #3440
- Fixes [AB#1873627](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1873627) - Fixes #2361
[contrib]: …
=> Update Parsing and Quoting articles

reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- Addressing confusion in https://github.com/PowerShell/PowerShell/issues/15884
- Adding explicitly the fact that switch parameters aren't positional.
- Removing the incorrect claim that switch parameters, when specified, can only be $true
Applies to all versions. I didn't check out the code, so I missed changing the old versions. I will be happy to merge this back to those after someone reviews and OKs it.
[contrib]: …
=> WIP: Update documentation about switch parameter

reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md, reference/7.0/Microsoft.PowerShell.Utility/Write-Progress.md, reference/7.1/Microsoft.PowerShell.Utility/Write-Progress.md, reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md
Specify that `-Id` does not allow negative values. Id parameter is listed as Int32, but PS5.1 (at least) enforces that it must also be non-negative.
Specify that `Write-Progress` `-Id` parameter does not allow negative values.
=> Write-Progress -Id must be non-negative

reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md
Fixes [AB#1879670](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1879670) - Fixes #7320 - Use PSObject() constructor in stead of AsPSObject
=> Fixes #7320 - Use PSObject() constructor instead of AsPSObject

reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md
Use AsPSObject() to avoid nesting PSObjects - related to #7320 
=> Use AsPSObject() to avoid nesting PSObjects

reference/5.1/Microsoft.PowerShell.Core/About/about_Booleans.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Windows_Powershell_5.1.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Booleans.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Booleans.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Booleans.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
Fixes [AB#1880792](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1880792) - Fixes #2939 - Add online URL to all about topics
=> Fixes #2939 - Add online URL to all about topics

reference/docs-conceptual/developer/provider/provider-types.md
Remove redundant and less informative qualifiers for readability.
case 1: `System.Management.Automation.Provider.DriveCmdletProvider` class
* 1st occurrence -> `System.Management.Automation.Provider.DriveCmdletProvider` (full)
* 2nd occurrence -> `DriveCmdletProvider` (no qualifier)
case 2: `System.Management.Automation.Provider.DriveCmdletProvider.InitializeDefaultDrives` method
When it is easy to understand the method's class name in context, write `InitializeDefaultDrives` (no qualifier).
=> Remove redundant qualifiers: Provider types

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-centos.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-fedora.md, reference/docs-conceptual/install/install-raspbian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md
Fixes [AB#1890978](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1890978) - Fixes #8293 - Update for rc.1 and remove Ubuntu 21.04
=> Fixes #8293 - Update for rc.1 and remove Ubuntu 21.04

reference/docs-conceptual/developer/prog-guide/creating-a-windows-powershell-container-provider.md
Remove code blocks and retain links.
I did not remove several code blocks that were different from links because I did not know why they were.
=> Remove duplicates: container provider sample

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
As PowerShell's [support](https://docs.microsoft.com/powershell/scripting/install/powershell-support-lifecycle) is linked to the .NET support policy, current versions stay in support for 6 months: https://dotnet.microsoft.com/platform/support/policy/dotnet-core#cadence
This PR updates this historic artefact/left-over. the table [here](https://docs.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.2#powershell-end-of-support-dates) already uses 6 months as the policy.
https://twitter.com/Steve_MSFT/status/1457775246698631175
- If the PR is work in progress, please add the …
=> Fix PowerShell-Support-Lifecycle.md: Current releases are supported for 6 and not 3 months after a subsequent Current or LTS release

reference/docs-conceptual/learn/security-features.md
Fixes [AB#1893173](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1893173) - Fixes #8205 - Add information about SBOM
=> Fixes #8205 - Add information about SBOM

reference/7.0/Microsoft.PowerShell.Utility/Format-Table.md, reference/7.1/Microsoft.PowerShell.Utility/Format-Table.md, reference/7.2/Microsoft.PowerShell.Utility/Format-Table.md
Fixes [AB#1893470](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1893470) - Fixes #8330 - Add note about when parameter was added
=> Fixes #8330 - Add note about when parameter was added

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
Fixes [AB#1893581](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1893581) - Fixes #8333 - Clarify the performance of Out-Null
=> Fixes #8333 - Clarify the performance of Out-Null

reference/docs-conceptual/gallery/how-to/working-with-packages/deploy-to-azure-automation.md
Fixes [AB#1893584](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1893584) - Fixes #8273 - Add note about sovereign clouds
=> Fixes #8273 - Add note about sovereign clouds

reference/5.1/Microsoft.PowerShell.Management/Test-Path.md, reference/7.0/Microsoft.PowerShell.Management/Test-Path.md, reference/7.1/Microsoft.PowerShell.Management/Test-Path.md, reference/7.2/Microsoft.PowerShell.Management/Test-Path.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/learn/security-features.md
Grammar: add missing conjunction
=> Add missing conjunction in Test-Path.md

reference/7.0/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Experimental_Features.md
Fixes [AB#1894349](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1894349) - Fixes #8351 - Document module metadata for experimental features
=> Fixes #8351 - Document module metadata for experimental features

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
Fixes [AB#1894374](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1894374) - Fixes #8347 - Update MS Store appx limitations
=> Fixes #8347 - Update MS Store appx limitations

reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
Fixes [AB#1894392](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1894392) - Fixes #8346 - Document PATHEXT environment var behavior in PS
=> Fixes #8346 - Document PATHEXT environment var behavior in PS

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
I find it frustrating to see a cast and having to evaluate its value, so I decided to provide explicit results.
Also, fun with hexadecimal strings (&incare; [BaseNumberConverter](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.basenumberconverter.convertfrom)).
=> Add more examples to about_Operators

reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
Fix: the result of unary operator `-` is not always negative.
About unary operator `+`.
Addition and subtraction of enumerated values.
Minor editing corrections.
=> Add examples for + and minus, fix unary -

.github/ISSUE_TEMPLATE/New_Document.yml, .github/ISSUE_TEMPLATE/New_Feature.yml, .github/ISSUE_TEMPLATE/New_Issue.yml
Add needs-triage label to templates
=> Add needs-triage label to templates

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
Fixes [AB#1906386](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1906386) - Fixes #8451 - Add performance examples for string addition
[key]: https://help.github.com/en/articles/closing-issues-using-keywo …
=> Fixes #8451 - Add performance examples for string addition

reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md, reference/7.0/Microsoft.PowerShell.Management/Copy-Item.md, reference/7.1/Microsoft.PowerShell.Management/Copy-Item.md, reference/7.2/Microsoft.PowerShell.Management/Copy-Item.md, reference/7.3/Microsoft.PowerShell.Management/Copy-Item.md
The second example can have undesired side effects if the target folder does not exist. The result will be to copy all the files from the source into a single file. It seems Copy-Item assumes that if the path does not exist the intended target is a file.
[contrib]: https://docs.microsoft.com/powershell/scripting/community/contri …
=> Update note for Example 2

reference/7.2/PSReadLine/About/about_PSReadLine.md, reference/7.3/PSReadLine/About/about_PSReadLine.md
Fix mismatching key bindings for PSReadLine 2.2.
Also, copy the content about "Behavior of the OnIdle event" to 7.2 about doc.
PSReadLine 2.2 doesn't ship along with PowerShell 7.2. It will reach GA mid next month. So, I think we should get the 7.2 about doc up to date.
[key]: …
=> Fix mismatching key bindings for PSReadLine 2.2

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_CommonParameters.md
Fixes [AB#1911275](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1911275) - Fixes #8508 - Clarify PipelineVariable behavior
=> Fixes #8508 - Clarify PipelineVariable behavior

reference/5.1/Microsoft.PowerShell.Core/About/about_Prompts.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Prompts.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Prompts.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Prompts.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Prompts.md
Fixes [AB#1912421](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1912421) - Fixes #8526 - Fix $NestedPromptLevel value
=> Fixes #8526 - Fix $NestedPromptLevel value

reference/docs-conceptual/dev-cross-plat/resolving-dependency-conflicts.md
Fix #8481
Update the sample code about using ALC.
=> Update the sample code about using ALC

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Scopes.md
Fixes [AB#1913694](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1913694) - Fixes #8541 - Remove confusing statement about multiple scopes
[key]: …
=> Fixes #8541 - Remove confusing statement about multiple scopes

reference/5.1/Microsoft.PowerShell.Core/Enter-PSHostProcess.md, reference/7.0/Microsoft.PowerShell.Core/Enter-PSHostProcess.md, reference/7.1/Microsoft.PowerShell.Core/Enter-PSHostProcess.md, reference/7.2/Microsoft.PowerShell.Core/Enter-PSHostProcess.md, reference/7.3/Microsoft.PowerShell.Core/Enter-PSHostProcess.md
The existing code block contained not only "code" but also regular text, I've added the code block delimiters to ensure that regular text is outside a code block.
=> Split code block from regular text

reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Fixes [AB#1915030](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1915030) - Fixes #8561 - Fix typo
=> Fixes #8561 - Fix typo

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md
This adds a missing angle bracket in all versions of the class syntax block in about_Classes.md
=> Insert missing angle bracket in class syntax block

reference/docs-conceptual/developer/cmdlet/activity-parameters.md, reference/docs-conceptual/developer/help/comment-based-help-keywords.md
Fixes [AB#1915036](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1915036) 
- Fixes #8560 - Add no-loc metadata to avoid over-translation
- Fixes #8562 - Add no-loc metadata to avoid over-translation …
=> Fixes #8562 - Add no-loc metadata to avoid over-translation

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Add spaces and period in `about_Comparison_Operators`
=> Add spaces and period in `about_Comparison_Operators`

reference/5.1/PSReadLine/About/about_PSReadLine.md, reference/7.0/PSReadLine/About/about_PSReadLine.md, reference/7.1/PSReadLine/About/about_PSReadLine.md, reference/7.2/PSReadLine/About/about_PSReadLine.md, reference/7.3/PSReadLine/About/about_PSReadLine.md
Fixes [AB#1920219](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1920219) - Fixes #8595 - Add note about WordDelimiters property
=> Fixes #8595 - Add note about WordDelimiters property

reference/5.1/Microsoft.PowerShell.Core/About/about_Hidden.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Hidden.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Hidden.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Hidden.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Hidden.md
This commit passes over the `about_Hidden` topic, ensuring that the formatting in the document matches standard styling for PowerShell and clarifying/improving language where needed.
Fixes #8630. 
[key]: …
=> (GH-8630) Update style/grammar in about_Hidden

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
This commit updates the `about_Language_Keywords` document across all supported versions of PowerShell to downcase and wrap in backticks the keywords, per standard style guidelines. This also ensures more effective localization for the document as many of these keywords are also common words (such as `for`, `do`, `while`).
Fixes #8633
the PR is …
=> (GH-8633) Standardize style in about_Language_Keywords

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
This PR updates the documentation for `about_PSCustomObject` and `about_Arrays` in Windows PowerShell 5.1 to note the divergent behavior of objects created by casting a hashtable to `[pscustomobject]` which returns `$null` for the automatic **Count** and **Length** properties.
- Fixes #8628 
[contrib]: …
=> (GH-8628) Note PSCustomObject Count Behavior

reference/7.3/Microsoft.PowerShell.Utility/Measure-Object.md
This commit adds a note to the `Measure-Object` cmdlet reference documentation for PowerShell 7.3 to clarify that it now only returns an argument error when an object is missing the to-measure property in **StrictMode** to pair with the updated implementation from PowerShell/PowerShell#16589.
- Resolves #8618
[contrib]: …
=> (GH-8618) Add note to Measure-Object in 7.3

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Prior to this PR, the `$PSModuleAutoloadingPreference` section of the `about_Preference_Variables` document explained how to use the variable in the list item for the **All** setting and did not explicitly indicate PowerShell's behavior when the variable is not set.
This PR updates the `$PSModuleAutoloadingPreference` section of the `about_Preference_Variables` document to clarify that the variable is not instantiated automatically but the behavior is still the described default of **All**.
It also moves the behavior explanation from the list item for the **All** setting into the opening paragraph to improve clarity.
Finally, this PR moves the note on using `Import-Module` to import modules regardless of the variable's setting into its own paragraph.
- Fixes #8645
Check the boxes below to …
=> (GH-8645) Add PSModuleAutoloadingPreference note

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Methods.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Properties.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Methods.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Properties.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Methods.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Properties.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Methods.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Properties.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Methods.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Properties.md, reference/docs-conceptual/learn/Glossary.md
This PR adds the new `about_Member-Access_Enumeration` topic to explain the convenience feature _member-access enumeration_ in detail.
- Resolves #8437
When changing **cmdlet reference** or **about_ topics**, the changes should be copied to all relevant versions. Check the boxes below to indicate the versions affected by this change.
=> (GH-8437) Document member-access enumeration

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-71.md, reference/docs-conceptual/whats-new/differences-from-windows-powershell.md
Fixes AB#1931278 - Fixes #8671 - Add .NET 5 breaking change for string comparisons
=> Fixes #8671 - Add .NET 5 breaking change for string comparisons

reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.2/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.3/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
This PR corrects the per-user portion of the path created when using the **MountUserDrive**
option for a PSSession configuration file.
For Windows PowerShell, it ensures the string represents what is actually written by
placing the environment variables in backticks; the prior description would not actually
map to the correct value as PowerShell would incorrectly see the variable as `USERDOMAIN_`.
For PowerShell, the option actually creates a folder for the domain and places a folder
per-user inside of that one.
Resolves #8583 - Closes AB#1923612
When changing **cmdlet reference** or **about_ topics**, the changes …
=> (GH-8583) Correct MountUserDrive path

reference/5.1/Microsoft.PowerShell.Management/Set-TimeZone.md, reference/7.0/Microsoft.PowerShell.Management/Set-TimeZone.md, reference/7.1/Microsoft.PowerShell.Management/Set-TimeZone.md, reference/7.2/Microsoft.PowerShell.Management/Set-TimeZone.md, reference/7.3/Microsoft.PowerShell.Management/Set-TimeZone.md
Standardizes the examples for `Set-TimeZone` to use UTC.
=> (MAINT) Standardize on UTC in `Set-TimeZone`

reference/5.1/Microsoft.PowerShell.Management/Set-TimeZone.md, reference/7.0/Microsoft.PowerShell.Management/Set-TimeZone.md, reference/7.1/Microsoft.PowerShell.Management/Set-TimeZone.md, reference/7.2/Microsoft.PowerShell.Management/Set-TimeZone.md, reference/7.3/Microsoft.PowerShell.Management/Set-TimeZone.md
UTC is an "Id" not a Name.
The correct "Name" for UTC is "Co-ordinated Universal Time" with a hyphen.
Both given examples currently published throw an error.
=> both UTC date changes examples are incorrect

reference/7.3/Microsoft.PowerShell.Management/Set-Service.md
This PR updates the help for the SecurityDescriptorSddl parameter
of Set-Service to clarify the necessary permissions for using it.
- Resolves #8443
=> (GH-8443) Update help for the SecurityDescriptorSddl parameter of `Set-Service`

reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Module_Manifest.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Module_Manifest.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
Adds the `about_Module_Manifests` topic.
- Resolves #8503 
=> (GH-8503) Add about_Module_Manifests

reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md
Added a leading space on line 35 to match the new line formatting on lines 21 and 28.  I expect this to result in better formatting when this document is rendered in a browser.
- Fixes #8707
[key]: …
=> Update ForEach-Object.md - ParallelParameterSet UseNewRunSpace syntax formatting

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
Prior to this PR, the `about_Environment_Variables` topic included misleading examples that would error if run in sequence. Additionally, the organization and content of the document hid some useful information in later sections, was difficult to follow, and lacked output examples.
This PR is a rewrite and restructuring of the document. The documents new flow explains, in order:
1. The most important information about environment variables in the long description
2. How to use/change environment variables
3. How to persist changes to environment variables
4. What environment variables PowerShell adds and uses
This PR resolves #8706.
**Cmdlet reference & …
=> (GH-8706) Clarify `about_Environment_Variables`

reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md
Fixes AB#1936862 - Fixes #8716 - Explain the effect of runspaces on script methods and properties
=> Fixes #8716 - Explain the effect of runspaces on script methods and properties
