MicrosoftDocs/PowerShell-Docs

- dsc/configurations.md
- dsc/overview.md
- dsc/resources.md
In the future, we can add a page to describe modules and reference the
gallery, etc.
> See Also links and Modules start-in

- .openpublishing.build.mdproj
- .openpublishing.publish.config.json
- wmf/Helloworld.md
- wmf/TOC.md
- wmf/docfx.json
Added partial config topic to TOC
Added infrastructure for WMF docs
> Merging latest updates from master into live

- wmf/limitation_overview.md
- wmf/sil_overview.md
Updates to sil_overview and limitation_overview
> Formatting and Minor Corrections to WMF Relnotes

- wmf/install.md
- wmf/limitation_dsc.md
- wmf/limitation_overview.md
- wmf/releasenotes.md
- wmf/requirements.md
- wmf/uninstall.md
adding all references to Client OSes and updating Known Issues
> adding Client OS references to WMF docset

- wmf/feedback.md
- wmf/install.md
- wmf/releasenotes.md
- wmf/requirements.md
Fixes to releasenotes, feedback, requirements, install
> Updates and fixes to WMF docset

- wmf/TOC.md
- wmf/psget_module_overview.md
- wmf/psget_modulecmdlets.md
- wmf/psget_moduledependency.md
- wmf/psget_modulesxsinstall.md
- wmf/psget_psrepository.md
- wmf/psget_script_overview.md
- wmf/psget_scriptcmdlets.md
- wmf/wmf5scenarios.md
final bulk formatting fixes to the WMF docset.
finished formatting PSGet sectino pages.
Also updating the wmf5scenarios.md to a links page and added to TOC
> formatting revisions to WMF docset

- wmf/TOC.md
> spelling fix in TOC

- wmf/releasenotes.md
adding note regarding WMF 5 RTM removal from Download Center on 12/23/2015
> Update to releasenotes.md for WMF 5 Status

- wmf/releasenotes.md
Update to releasenotes.md for WMF 5 Status
> Update for WMF 5 RTM Status

- README.md
Tweaked the language for clarity and added some relevant hyperlinks.
> Edit README.md to improve clarity

- CONTRIBUTING.md
This PR corrects the New Issue tagging suggestion as noted in #141
> Updated Contributing.md to correct Issue Labeling text - Fixes #141

- wmf/install.md
> Update install.md formatting

- .localization-config
update the configuration file to use new transformer
> update configuration file to use new transformer

- wmf/TOC.md
> fixed typo

- dsc/pullServer.md
Added detailed information on registration keys and setup.
> Add more detail to Pull Server setup.

- dsc/partialConfigs.md
Changed Start-DscConfigurationxt to Start-DscConfiguration
> Fixed typo in partialConfigs.md

- dsc/secureMOF.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/265)
> Updated secureMOF.md

- .openpublishing.publish.config.json
- dsc/reportServer.md
- scripting/docfx.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/266)
> Merging recent changes into live

- dsc/pullServer.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/267)
> changed report server link to correct topic

- dsc/TOC.md
- dsc/reportServer.md
- dsc/singleInstance.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/271)
> Created single instance topic and updated report server topic

- dsc/TOC.md
- dsc/whitepapers.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/274)
> Release Pipeline whitepaper

- dsc/secureMOF.md
This PR clarifies the section on Creating The Certificate in SecureMOF.md that were raised here:
https://github.com/PowerShell/PowerShell-Docs/commit/941d9840629dea298ae50e744fca18776783f2e3#commitcomment-17029413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/283)
> Clarified 'Creating the Certificate' section to resolve questions on installing Cert to root

- dsc/TOC.md
- dsc/msft-dsclocalconfigurationmanager-applyconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-disabledebugconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-enabledebugconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-getconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-getconfigurationresultoutput.md
- dsc/msft-dsclocalconfigurationmanager-getconfigurationstatus.md
- dsc/msft-dsclocalconfigurationmanager-getmetaconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-performrequiredconfigurationchecks.md
- dsc/msft-dsclocalconfigurationmanager-removeconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-resourceget.md
- dsc/msft-dsclocalconfigurationmanager-resourceset.md
- dsc/msft-dsclocalconfigurationmanager-resourcetest.md
- dsc/msft-dsclocalconfigurationmanager-rollback.md
- dsc/msft-dsclocalconfigurationmanager-sendconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-sendconfigurationapply.md
- dsc/msft-dsclocalconfigurationmanager-sendconfigurationapplyasync.md
- dsc/msft-dsclocalconfigurationmanager-sendmetaconfigurationapply.md
- dsc/msft-dsclocalconfigurationmanager-stopconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-testconfiguration.md
- dsc/msft-dsclocalconfigurationmanager.md
- scripting/Topic/Windows-PowerShell-Integrated-Scripting-Environment--ISE-.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/293)
> Added MOF reference topics, updated content with new info

- dsc/partialConfigs.md
missed this update in an earlier PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/299)
> Syntax error in partialconfiguration sample

- wmf/feedback_clipboard.md
- wmf/feedback_fileinfo.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/306)
> made changes to two wmf files to address customer issues

- dsc/groupResource.md
- dsc/pullClientConfigNames.md
- dsc/secureMOF.md
- wmf/feedback_clipboard.md
- wmf/feedback_fileinfo.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/307)
> meging recent changes ino live

- dsc/md.style
- scripting/md.style
- wmf/md.style
Add these configuration files, so OP will run the validation to detect extra new lines in markdown content. Like: 
\`test
code inline.\`
With the extra new lines in MD content, one segment may break into multiple segments in XLIF file. This extra new lines should be deleted from source content.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/310)
> Openablelocalizationvalidation

- scripting/TOC.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/316)
> Update TOC.md--fix bad link

- dsc/TOC.md
- dsc/nanoDsc.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/320)
> Added DSC on Nano topic

- dsc/TOC.md
- dsc/configHelp.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/323)
> adding writing help for configs topic

- dsc/runAsUser.md
Plus some spacing fixes :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/326)
> Changed configuration to resource for RunAs

- dsc/secureMOF.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/330)
> Remove note about Nano Server requiring CertOC.exe - Fixes #327

- wmf/class_newtype.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/332)
> Removed older prerelease attributes

- wmf/dsc_classbasedresource.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/333)
> Removing quote for propert rendering

- dsc/secureMOF.md
- wmf/class_newtype.md
- wmf/dsc_classbasedresource.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/334)
> Merging latest changes

- dsc/pullServer.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/335)
> Fixing the configuration name and its usage typo (and other spacing/quoting nits)

- wmf/limitation_dsc.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/341)
> Clarified that Import-DscResource issue is with class-based resources only

- wmf/limitation_overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/343)
> Updated the sysprep workaround to match rest of the document formatting

- wmf/limitation_dsc.md
- wmf/limitation_overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/344)
> Merging latest to live

- dsc/authoringResourceMOF.md
Fix: .ps1 replaced by .psm1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/352)
> Fix small error

- dsc/pullClientConfigID.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/351)
> Added missing '

- dsc/authoringResourceMofCS.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/350)
> Added psd1 file as it is required

- dsc/authoringResourceMOF.md
Update folder structure (remove space)
Improve MOF schema description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/353)
> Improve MOF schema description

- scripting/setup/Windows-PowerShell-System-Requirements.md
Updating customer request to avoid a complex merge from Pull Request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/356)
> Technet port

- scripting/getting-started/fundamental/About-Windows-PowerShell.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/357)
> Cmdlets should be camel case & setup Get-Member

- scripting/setup/Windows-PowerShell-System-Requirements.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/359)
> Cleaning up extra character before "registered" symbol and added missing spacing in the end.

- dsc/msft-dsclocalconfigurationmanager-getconfigurationresultoutput.md
- dsc/msft-dsclocalconfigurationmanager-getconfigurationstatus.md
- dsc/msft-dsclocalconfigurationmanager-performrequiredconfigurationchecks.md
- dsc/msft-dsclocalconfigurationmanager-removeconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-resourceget.md
- dsc/msft-dsclocalconfigurationmanager-resourceset.md
- dsc/msft-dsclocalconfigurationmanager-resourcetest.md
- dsc/msft-dsclocalconfigurationmanager-rollback.md
- dsc/msft-dsclocalconfigurationmanager-sendconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-sendconfigurationapply.md
- dsc/msft-dsclocalconfigurationmanager-sendconfigurationapplyasync.md
- dsc/msft-dsclocalconfigurationmanager-sendmetaconfigurationapply.md
- dsc/msft-dsclocalconfigurationmanager-stopconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-testconfiguration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/378)
> fixed metadata for MOF reference

- dsc/msft-dsclocalconfigurationmanager-applyconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-disabledebugconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-enabledebugconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-getconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-getmetaconfiguration.md
- dsc/msft-dsclocalconfigurationmanager.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/380)
> completing metadata injection

- dsc/metaConfig.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/385)
> Adding missing links and line spacing.

- .gitignore
- dsc/partialConfigs.md
Resolves #367. Hopefully I've selected the correct branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/384)
> Added Example Partial Configs

- dsc/partialConfigs.md
Addressing point made by @ArieHein in issue #389.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/390)
> Update partialConfigs.md to change Node block names

- dsc/partialConfigs.md
- scripting/whats-new/What-s-New-in-Windows-PowerShell-50.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/391)
> Merging edit to partialConfigs.md

- wmf/TOC.md
- wmf/productincompat.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/392)
> Restructing the product compatible topic and adding Sharepoint to compatible applications

- wmf/productincompat.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/394)
> Moving Exchange to incompatible list

- wmf/productincompat.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/395)
> Merging to live

- scripting/core-powershell/Running-Remote-Commands.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/396)
> Fixed incomplete command (tested locally)

- dsc/reportServer.md
- scripting/core-powershell/Running-Remote-Commands.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/400)
> Merging recent PRs into live

- dsc/pullServer.md
Fixed typo in pullServer.md (OutputPath instead of OutpuPath)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/399)
> Fixed typo in pullServer.md

- dsc/reportServer.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/401)
> Merging typo fix from @NGPixel

- wmf/overview.md
- wmf/productincompat.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/402)
> Added Lync/Skype Server to incompatible list

- dsc/reportServer.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/403)
> Merging changes to live

- dsc/partialConfigs.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/406)
> added examples for confignames to partialConfigs topic

- dsc/partialConfigs.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/407)
> merging update to address issue #389

- .openpublishing.publish.config.json
- jea/docfx.json
- jea/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/411)
> new docset

- dsc/authoringResourceComposite.md
Removing a space on the `DSCResources` folder structure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/418)
> Updating authoringResourceComposite.md

- scripting/setup/Installing-Windows-PowerShell.md
MotoWilliams reported a broken link in PowerShell-Docs / scripting / setup / Installing-Windows-PowerShell.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/422)
> Broken link fixed

- dsc/TOC.md
As they are applicable to both built-in and custom resources. @eslesar do you agree?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/425)
> Moving resource direct call and debugging one level up

- scripting/setup/Starting-the-32-Bit-Version-of-Windows-PowerShell.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/424)
> Add 32-Bit PowerShell executables file system locations

- wmf/limitation_dsc.md
This issue has been reported by many people:
https://twitter.com/guitarrapc_tech/status/743161769850376192?cn=cmVwbHk%3D&refsrc=email
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13703175-get-psdrive-abnormal-i-o#comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/428)
> Adding known issue on registry resource taking long time.

- dsc/configHelp.md
This addresses #435
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/436)
> Fixing typo on PowerShell code comment

- scripting/getting-started/cookbooks/Managing-Current-Location.md
A couple used code blocks while one used fixed width, this looked strange on the page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/438)
> Update cd alternates for consistency

- scripting/PowerShell-Scripting.md
- scripting/core-powershell/core-powershell.md
All broken links fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/446)
> Juanpablojofre patch 2

- dsc/troubleshooting.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/448)
> updated troubleshooting to remove todo

- .openpublishing.publish.config.json
- reference/docfx.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/455)
> Adding new docset "reference"

- wmf/5.1/community-resources.md
- wmf/5.1/compatibility.md
- wmf/5.1/features-scenarios-cache/oneget-improvement.md
- wmf/5.1/features-scenarios-cache/template.md
- wmf/5.1/install-configure.md
- wmf/5.1/known-issues-cache/template.md
- wmf/5.1/known-issues.md
- wmf/5.1/release-notes.md
- wmf/5.1/scenarios-features.md
- wmf/TOC.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/458)
> 5.1 content ported from DonGill's work

- wmf/5.1/scenarios-features.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/461)
> J omergeanalysisitem

- wmf/5.0/dsc_classbasedresource.md
- wmf/5.0/dsc_confighelp.md
- wmf/5.0/dsc_directaccess.md
- wmf/5.0/dsc_freqnomultiple.md
- wmf/5.0/dsc_getconfigurationstatus.md
- wmf/5.0/dsc_metaconfiguration.md
- wmf/5.0/dsc_nodeid.md
- wmf/5.0/dsc_partialconfig.md
- wmf/5.0/dsc_refreshmode.md
- wmf/5.0/dsc_reporting.md
- wmf/5.0/dsc_repository.md
- wmf/5.0/dsc_resourcedebugging.md
- wmf/5.0/dsc_runas.md
- wmf/5.0/dsc_sxsresource.md
- wmf/5.0/dsc_waitfor.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/462)
> fixing broken links due to relative folder change

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/490)
> Update internal links instructions

- wmf/5.1/features-scenarios-cache/using-module.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/481)
> Add release notes about 'using module' in WMF 5.1 notes

- wmf/5.1/scenarios-features.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/492)
> Jaimeo wmf51 76

- wmf/5.1/features-scenarios-cache/PesterUpdates.md
Hoping this is stylistically OK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/498)
> Adds brief Pester info to release notes.

- dsc/fileResource.md
@HemantMahawar Addresses #491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/499)
> updating FileResource topic to clarify behavior of MatchSource property

- wmf/5.1/scenarios-features.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/500)
> Add a note in WMF 5.1 release notes about fixed connect issue

- wmf/5.1/features-scenarios-cache/ps-engine-enhancements.md
as it was appearing ok on the GitHub preview, but was actually rendering wrong on the actual web page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/502)
> fixed your table

- wmf/5.1/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/504)
> Temporary overview topic explaining the preview WMF 5.1 content

- wmf/5.1/features-scenarios-cache/ps-engine-enhancements.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/505)
> stripped out personal names

- wmf/5.1/install-configure.md
- wmf/5.1/release-notes.md
To avoid confusion, added note to Installation topic that it is a placeholder, and the links go to old executables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/507)
> Jkeithb wmf51

- wmf/5.1/features-scenarios-cache/DSCPartialConfigNaming.md
- wmf/5.1/features-scenarios-cache/DSCRunAsCredentialCompositeResources.md
- wmf/5.1/features-scenarios-cache/DSCSigningValidations_1.md
- wmf/5.1/features-scenarios-cache/DSCSigningValidations_2.md
- wmf/5.1/features-scenarios-cache/Improved-PullServer-Registration.md
- wmf/5.1/features-scenarios-cache/Improved-dsc-classresource.md
- wmf/5.1/features-scenarios-cache/Improved-dsc-resourcedebugging.md
- wmf/5.1/features-scenarios-cache/PesterUpdates.md
- wmf/5.1/features-scenarios-cache/catalog-cmdlets.md
- wmf/5.1/features-scenarios-cache/improved-pullclient-security.md
- wmf/5.1/features-scenarios-cache/using-module.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/510)
> added files recovered from dongill repo

- wmf/5.1/DSC-improvements.md
- wmf/5.1/engine-improvements.md
- wmf/5.1/package-management-improvements.md
- wmf/5.1/scenarios-features.md
- wmf/TOC.md
Fixed relative image paths. Added Package Improvements topic. Updated TOC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/518)
> fixed image links

- wmf/5.1/features-scenarios-cache/DSCSigningValidations_1.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/522)
> Fixed some typos, broken hyperlinks in DSCSigningValidations_1.md

- wmf/5.1/install-configure.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/528)
> Removed WMF 5.0 URL links

- wmf/5.1/install-configure.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/533)
> Incorporate security update required for new Catalog cmdlets on win7

- wmf/5.1/install-configure.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/540)
> Adding instructions related to .Net framework 4.6

- wmf/5.1/install-configure.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/541)
> merging update into live

- jea/README.md
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/534)
> Small Typo Update

- wmf/5.1/features-scenarios-cache/jea-improvements.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/538)
> Added JEA updates for WMF 5.1

- wmf/5.1/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/542)
> Changed "upcoming 5.1" to be current 5.1

- dsc/debugResource.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/547)
> Fix typo #2

- wmf/5.1/install-configure.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/548)
> Added package URLs and .NET 4.6 dependency note

- wmf/5.1/known-issues-cache/NetworkingSwitchCmdletInput.md
- wmf/5.1/release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/551)
> Added known issues docuement and updates to release notes main page

- gallery/readme.md
Updated the href for GettingStarted page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/553)
> Updated the href for GettingStarted page.

- gallery/readme.md
Current content came from welcome page of Gallery, so starts with "Welcome to...", which is inappropriate for MSDN docs for the Gallery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/566)
> Change topic title to be appropriate for MSDN

- gallery/TOC.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/571)
> Fix broken links in gallery/TOC.md

- scripting/setup/Installing-the-Windows-PowerShell-SDK.md
Replaced raw XML with proper Markdown formatting as close as possible to original page on TechNet: https://technet.microsoft.com/en-us/library/ff458115.aspx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/570)
> Update Installing-the-Windows-PowerShell-SDK.md. Fixes #519.

- wmf/5.1/engine-improvements.md
Please be so kind to review this fix for issue #543.
Thanks very much
Daniel Krebs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/569)
> Fixes #543. Bad link [analysis_cache.md]()

- wmf/5.1/release-notes.md
Minor update: requirement should have read .NET 4.6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/575)
> Jkeithb relnotes

- gallery/TOC.md
- gallery/psget/psget_cmdlets_troubleshooting.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/579)
> Add troubleshooting page

- dsc/partialConfigs.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/581)
> Corrected inconsistent examples and references

- gallery/psget/psget_cmdlets_troubleshooting.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/580)
> changed formatting of example to code block

- gallery/psget/psget_cmdlets_troubleshooting.md
Updated -RequiredVersion to -MinimumVersion to ensure that users will get the latest version of NuGet provider.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/585)
> Updated -RequiredVersion to -MinimumVersion

- .localization-config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/587)
> Need to update loc config to add uper case MD files

- scripting/PowerShell-Scripting.md
- scripting/TOC.md
- scripting/core-powershell/core-modules.md
- scripting/core-powershell/core-powershell.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/588)
> Core replaced with common

- scripting/getting-started/fundamental/Using-Windows-PowerShell.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/591)
> removed apparently invalid character

- dsc/lnxGettingStarted.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/597)
> corrected directory of log files in linux getting started

- scripting/PowerShell-Scripting.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/598)
> Updating landing page to anounce PowerShell in GitHub

- scripting/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/603)
> Removing OPS text file 'index.md'

- wmf/5.1/features-scenarios-cache/catalog-cmdlets.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/605)
> Added explanation for proper use of Path and CatalogFilePath.

- jea/README.md
There is no such cmdlet New-PSSessionCapabilityFile... New-PSSessionConfigurationFile is what is intended. Additionally, I added links to the relevant cmdlet doc pages. 
@rpsqrd (JEA PM)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/606)
> Corrected New-PSSessionCapabilityFile to New-PSSessionConfigurationFile.

- gallery/TOC.md
So that it shows up in the MSDN pages.
> Task:8511260:Add powershell gallery status pages to table of contents.

- gallery/psget/module/modulewithpseditionsupport.md
Adding Update-ModuleManifest in More details.
> Adding Update-ModuleManifest in More details.

- dsc/troubleshooting.md
> Update dsc/troubleshooting.md to fix #616

- dsc/authoringResourceClass.md
I was having hard time running the sample provided in this example. To make it work I need to change the modules folder. I was trying to make it run under c:\users\<username>\My Documents\WindowsPowerShell\Modules instead of $env:ProgramFiles\WindowsPowerShell\Modules. Hence I am submitting this change (line#29) to save time of others. Thanks!
> Updated authoringResourceClass.md

- dsc/authoringResourceClass.md
- dsc/authoringResourceMOF.md
Similar to #653, updating for MOF resources as well
> Updating MOF resource authoring to have ProgramFIles module path

- common-modules/readme.md
We're opening a new docset to host the reference content for all 'Common Modules'.
Need this PR to be merged onto Staging, so the process can start and the content will have place to live.
> Jpjofre common modules reference documentation

- scripting/setup/Starting-Windows-PowerShell.md
Removed additional UTF-8 Â character
> Remove additional UTF-8 Â character

- scripting/setup/Starting-the-32-Bit-Version-of-Windows-PowerShell.md
Removed additional UTF-8 Â character
Inserted ® characters
> Remove additional UTF-8 Â  and insert ® character

- scripting/setup/Starting-Windows-PowerShell-on-Earlier-Versions-of-Windows.md
Remove additional UTF-8 Â  and insert ® character
> Fixing characters

- scripting/core-powershell/core-modules/PSScriptAnalyzer-Module.md
- scripting/core-powershell/core-modules/PackageManagement-Module.md
- scripting/core-powershell/core-modules/Windows-PowerShell-Core-About-Topics.md
- scripting/core-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md
- scripting/core-powershell/ise/The-ISEFile-Object.md
- scripting/core-powershell/ise/The-ISEMenuItemCollection-Object.md
- scripting/core-powershell/ise/The-ObjectModelRoot-Object.md
- scripting/core-powershell/ise/The-Windows-PowerShell-ISE-Scripting-Object-Model.md
- scripting/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md
- scripting/core-powershell/ise/Windows-PowerShell-ISE-Object-Model-Reference.md
- scripting/getting-started/fundamental/Exploring-the-Windows-PowerShell-ISE.md
- scripting/getting-started/fundamental/Using-Windows-PowerShell.md
- scripting/setup/Installing-the-Windows-PowerShell-2.0-Engine.md
- scripting/whats-new/What-s-New-in-Windows-PowerShell-50.md
> replaced unwanted chars

- scripting/setup/Installing-Windows-PowerShell.md
Removed [PS] from Start Windows PowerShell link in See Also section
Add line break to seperate the links in See Also section
> Fixed See Also section

- scripting/whats-new/What-s-New-With-PowerShell.md
Removed reference to Windows Server Technical Preview
Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86
> Removed reference to Windows Server Technical Preview

- dsc/DSCAutomationHostEnabled.md
In response to http://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/some-settings-are-managed-by-your-organization-on/7d0e0fa3-50e2-4a56-8e91-8539b5fbe648?auth=1.
> Documenting DSCAutomationHostEnabled registry key

- scripting/whats-new/What-s-New-With-PowerShell.md
Unfortunately, I couldn't find a fwdlink that pointed to WMF 5.0, but hopefully this is still better than a broken link.
> Update link to WMF

- scripting/whats-new/What-s-New-in-Windows-PowerShell-50.md
SkyEye feedback shows user issues finding the download link
> Emphasizing how to acquire PS 5

- .gitignore
- appveyor.ps1
- appveyor.yml
- reference/5.0/PowershellGet/Find-DscResource.md
Don't merge this quite yet. I want to do a manual build to make sure that it's working first.
> Add Appveyor CI to build MAML and CABs

- reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
Update Register-AugumentCompleter per work item 69310. 
Changes to example section and input and output sections.
> Register-AugumentCompleter per work item 69310.

- reference/3.0/Microsoft.PowerShell.Utility/Get-Culture.md
- reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
> Fix some platyPS errors in markdown

- reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
Plaintext was being included in codeblocks
> fix overaggressive codeblocks

- reference/4.0/Microsoft.PowerShell.Utility/Get-Culture.md
- reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
- reference/5.0/Microsoft.PowerShell.Utility/Get-Culture.md
- reference/5.0/Microsoft.PowerShell.Utility/Get-Runspace.md
- reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
- reference/5.1/Microsoft.PowerShell.Utility/Get-Culture.md
Split of #812 into two PRs
This one contains everything except ConvertFrom-String
> Fix platyPS schema problems in reference/ folder

- reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-String.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md
Fix header levels for EXAMPLES in ConvertFrom-String
Split of #812 into two PRs
This one contains ConvertFrom-String
> Fix platyPS schema in ConvertFrom-String

- reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
Reverts PowerShell/PowerShell-Docs#810
> Revert "fix overaggressive codeblocks"

- appveyor.ps1
This is a part of #798
We want to fail the build, if there are platyPS errors.
Example: #820
> Make AppVeyor build fail on platyPS errors

- wmf/5.1/known-issues.md
> Update release note with DSC-Known issue.

- dsc/bootstrapDsc.md
- Split long paragraphs into multilines
- Added powershell code syntax
> Formatting fix

- wmf/5.0/dsc_resourcedebugging.md
- wmf/5.0/networkswitch_overview.md
> Removing 'preview' from WMF 5.0 release notes

- reference/3.0/Microsoft.PowerShell.Core/About/about_Job_Details.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Job_Details.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Job_Details.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Job_Details.md
> Fixing the prompt to say PS instead of CPS

- reference/5.1/PowershellGet/Save-Module.md
Reformatted the example code block in **Save-Module.md** to include the missing new lines before the shell prompt.
> Updated example in Save-Module.md

- reference/5.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Table.md
Grabbed correct values from earlier help.
> Fix valid keys of Property parameter of Format-Table

- reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
> Fixing first sample in Invoke-RestMethod

- wmf/README.md
@JKeithB  ... does it looks good?
> Update to uber WMF matrix

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
Code was very hard to read without formatting.
> Added formatting for code snippets

- reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
Clean up formatting, warn of potentially confusing Verbose behavior.
> Invoke-RestMethod.md Body parameter update

- gallery/psget/module/modulewithpseditionsupport.md
1. Fixed an incorrect example - 2nd example, the Test-ManifoldManifest's path parameter had an incorrect value.
2. Changed casing for two statements and uppercased 'DLL' (not dll).
Minor changes!
> Update modulewithpseditionsupport.md - minor edit and correction

- reference/5.1/Microsoft.PowerShell.Utility/Import-PowerShellDataFile.md
> Added example for import-PowerShellDataFile

- reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md
Updated example header, it was.... confusing.
> Fixed Example 1 Type

- reference/3.0/Microsoft.PowerShell.Management/Rename-Item.md
This is a little useful for novice users (like me), who are starting to work on powershell.
> Providing prefixing entries example

- dsc/enactingConfigurations.md
> clarified refresh and compliance frequency in pull mode section

- reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md
Fixing a code example. Thanks!
> Fix about_Requires example

- appveyor.ps1
- reference/5.1/Microsoft.PowerShell.Management/Push-Location.md
- Also added bunch of comments in the code :)
> Made New-ExternalHelp cmdlet warnings into terminating errors

- reference/5.1/PowershellGet/Update-ModuleManifest.md
Missing space character in Example 1 between parameter and string.
> Update to Update-ModuleManifest.md

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
More work would be appropriate for turning certain pieces of text into hyperlinks
> Fix all formatting according to Markdown format

- dsc/partialConfigs.md
Hi @eslesar,
Localization team found an incomplete sentence "Note: The user running the".
I've placed a comment in article to indicate the location.
Please help to reply what the full sentence should be in this PR or let me know if you will fix in another PR.
Thank you,
Jason
> Please fix incomplete sentence

- dsc/lnxUserResource.md
> removed mode property from Linux UserResource syntax

- wmf/5.1/compatibility.md
Added links to WMF 5.1 DLC on the column header
> Added links to WMF 5.1 DLC on the column header

- dsc/authoringResourceComposite.md
> fixed metadata in composite resource topic

- wmf/5.1/release-notes.md
Completing the change to .Net 4.5.2, which is the current release of .Net 4.5.x.
> Changed .Net 4.5 reference to 4.5.2

- dsc/bootstrapDsc.md
- dsc/configurations.md
- dsc/pullServer.md
> made changes to fix build warnings in dsc topics

- reference/5.1/Microsoft.PowerShell.Utility/Add-Type.md
- reference/5.1/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
Made a change in Synopsis for Add-Type in version 5.1 docs.
> Changed Synopsis for Add-Type in Version 5.1

- dsc/metaConfig.md
I have changed some misspellings of 'server' from 'sever' to 'server'.
> Spell checking

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
@eslesar @juanpablojofre @zjalexander can you take a look at it. /cc @joeyaiello 
Will add an issue template as well.
> Adding PR and ISSUE templates

- appveyor.yml
Experimenting with deploying to staging and production for staging and live branches.
> Update yml to have staging and live deploy

- wmf/5.1/install-configure.md
Minor change to reflect .NET version requirements in additional section of page.
> reference to .net ver in prereq section

- dsc/partialConfigs.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
Reverts PowerShell/PowerShell-Docs#1009
> Revert the last change to resolve merge conflicts

- reference/3.0/Microsoft.PowerShell.Core/About/about_Job_Details.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Throw.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Job_Details.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Throw.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Job_Details.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Throw.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Job_Details.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Throw.md
Found the correct files for some of those which were missing in previous PR.
> Adds links into "SEE ALSO" section for about_Job_Details/Language_Modes/Throw topics

- dsc/troubleshooting.md
add remoting requirements as first step for troubleshooting
> Add remoting requirements

- wmf/5.1/known-issues-cache/NetworkingSwitchCmdletInput.md
Let's see if I understood that error message correctly
> Trying to fix #936

- reference/3.0/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
- wmf/5.1/known-issues-cache/NetworkingSwitchCmdletInput.md
> Enhances "SEE ALSO" section in about_Session_Configurations topics

- dsc/partialConfigs.md
> fixed partialConfigs topic to address #1006

- reference/4.0/Microsoft.PowerShell.Core/About/about_Foreach.md
This is in the Reference folder.
> Fixing 4.0 About_ForEach.md reported Issue #959

- reference/3.0/Microsoft.PowerShell.Core/About/about_Foreach.md
This is in the Reference folder.
> Fixing 3.0 About_ForEach.md reported Issue #959

- reference/5.0/Microsoft.PowerShell.Core/About/about_Foreach.md
This is in the Reference folder.
> Fixing 5.0 About_ForEach.md reported Issue #959

- reference/3.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
> Fixing about_Comparison_Operators.md Issue #1000

- wmf/README.md
@JKeithB & @KrishnaV-MSFT Looks good??
> Adding release notes link for WMF 4, WMF 3 as well

- reference/3.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md
- reference/4.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md
- reference/5.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md
- reference/5.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md
> Fix Enable-PsRemoting

- reference/5.0/Microsoft.PowerShell.Utility/import-powershelldatafile.md
introduced in PowerShell 5, fixed in 5.1. Backporting fix.
> address issue #960

- reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
- reference/5.0/Microsoft.PowerShell.Core/Functions/Clear-Host.md
- reference/5.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Environment-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Function-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Registry-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Variable-Provider.md
- reference/5.0/Microsoft.PowerShell.Security/providers/certificate-provider.md
- reference/5.0/Microsoft.WsMan.Management/providers/wsman-provider.md
> Remove dash-style example headers- resolve #1063 for PS 5.0

- reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
- reference/5.1/Microsoft.PowerShell.Core/Functions/Clear-Host.md
- reference/5.1/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Environment-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Function-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Registry-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Variable-Provider.md
- reference/5.1/Microsoft.PowerShell.Security/Providers/Certificate-Provider.md
- reference/5.1/Microsoft.WsMan.Management/Providers/WSMan-Provider.md
> Remove dash-style example headers- resolve #1063 for PS 5.1

- jea/overview.md
- jea/prerequisites.md
- jea/role-capabilities.md
- jea/security-considerations.md
- jea/session-configurations.md
Corrected and clarified information regarding virtual accounts on domain controllers and the search order for role capabilities.
> Updated JEA documentation

- jea/overview.md
added gMSA reference to benefits of JEA
> updated with reference to gMSA

- STYLE.md
Proposal to address issues #15, #1018, #1038.
Related to https://github.com/PowerShell/platyPS/issues/264
> Style guide

- README.md
> Correcting release notes link

- reference/3.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
> Fix links in about_Hash_Tables topic. Resolves #1074

- dsc/DscForEngineers.md
- dsc/TOC.md
- dsc/configurations.md
- dsc/decisionMaker.md
- dsc/overview.md
- dsc/quickStart.md
> created quick start and reorganized overview section

- reference/3.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/3.0/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/3.0/Microsoft.PowerShell.Utility/Import-Clixml.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/4.0/Microsoft.PowerShell.Core/Save-Help.md
- reference/4.0/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/4.0/Microsoft.PowerShell.Utility/Import-Clixml.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/5.0/Microsoft.PowerShell.Core/Save-Help.md
- reference/5.0/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/5.0/Microsoft.PowerShell.Utility/Import-Clixml.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/5.1/Microsoft.PowerShell.Core/Save-Help.md
- reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/5.1/Microsoft.PowerShell.Utility/Import-Clixml.md
> Fix case for Import-Clixml and Export-Clixml. Augments PR 1058 and 1059.

- gallery/psgallery/psgallery_status.md
- gallery/psgallery/psgalleryint_status.md
> merging to address PSGallery issue

- gallery/psgallery/psgallery_faqs.md
1. Fixes links to Ed's blog
2. Replaces HTTP with HTTPS where supported.
> Small hyperlinks tuning in PSGallery FAQ

- README.md
> Fix link to STYLE.md in README.md

- reference/3.0/PSWorkflow/About/about_InlineScript.md
- reference/4.0/PSWorkflow/About/about_InlineScript.md
- reference/5.0/PSWorkflow/About/about_InlineScript.md
- reference/5.1/PSWorkflow/About/about_InlineScript.md
- [ x] Impacts 5.1 document
- [ x] Impacts 4.0 document
- [x ] Impacts 3.0 document
All impacted versions fixed
> Fixed formating issues that prevented rendering

- dsc/TOC.md
- dsc/compositeConfigs.md
- dsc/configData.md
> added topic on composite configurations

- reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
> Update Invoke-RestMethod and -WebRequest to reflect -NoProxy use

- dsc/overview.md
The file overview.md was missing a few parenthesis to correctly reference other files in the project.
> Fix link ref in overview.md

- reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
When consulting this document it was unclear whether files included in -FileList would be published along with the other module files when pushed to a PSRepository. They are, hence the clarification update.
- [X ] Impacts 5.1 document
- [ X] Impacts 5.0 document
- [ X] Impacts 4.0 document
- [ X] Impacts 3.0 document
> Clarify -FileList parameter

- reference/5.1/Microsoft.PowerShell.Management/Get-Service.md
> Remove blank lines.

- gallery/psgallery/psgallery_status.md
> Updating the item in the status page to show issue is closed

- gallery/psgallery/psgallery_status.md
- reference/3.0/Microsoft.PowerShell.Utility/Write-Error.md
- reference/4.0/Microsoft.PowerShell.Utility/Write-Error.md
- reference/5.0/Microsoft.PowerShell.Utility/Write-Error.md
- reference/5.1/Microsoft.PowerShell.Utility/Write-Error.md
- reference/6/Microsoft.PowerShell.Utility/Write-Error.md
@eslesar,
Adding Keith's PR to live.
> Updating LIve with latest Gallery updates

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
we added v6 to the repo but didn't update the templates to match!
> templates - include ps 6

- reference/5.1/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
> Corrected the help URL

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/6/About/about_Functions_Advanced_Parameters.md
* Fix code formatting and headers in about_Functions_Advanced_Parameters.md for 5.1 and 6.0 (harmonized with 3.0, 4.0, and 5.0)
* Fix typo in code formatting for 3.0, 4.0, and 5.0
> Update 3.0, 4.0, 5.0, 5.1, 6 about_Functions_Advanced_Parameters.md

- STYLE.md
> address #1175

- reference/4.0/PSDesiredStateConfiguration/Start-DscConfiguration.md
- reference/5.0/PSDesiredStateConfiguration/Start-DscConfiguration.md
- reference/5.1/PSDesiredStateConfiguration/Start-DscConfiguration.md
- [x ] Impacts 4.0 document
- [x ] The documented feature was introduced in version 4.0 of PowerShell (and is not currently included in version 6)
> clarifying force param of start-dscconfiguration description

- .gitignore
- reference/3.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Update-Help.md
- reference/6/Microsoft.PowerShell.Core/Update-Help.md
> Customer requested more visibility to admin privileges required to use Update-Help

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/6/About/about_Functions_Advanced_Methods.md
* Format section headings
* Add inline code formatting
* Add code formatting to Begin, Process, End example
> Update about_Functions_Advanced_Methods all version

- dsc/decisionMaker.md
I wanted to [create instructions](http://www.brianbunke.com/blog/2017/05/12/github-pr/) to send potential new contributors to this repo, and had to pick out a [contentious typo](http://grammarglitchcentral.com/2011/03/premise-or-premises-there-is-a-difference/) as an example. 🙂
Since I'm pointing people in your direction, if you'd like me to change any instructions, please let me know! Thanks!
> Update premise to premises

- gallery/psgallery/psgalleryint_status.md
Should this be Publish-Script not Publish-Scirpt
> Spelling Mistake Scirpt to Script

- reference/3.0/Microsoft.PowerShell.Management/Set-Content.md
- reference/4.0/Microsoft.PowerShell.Management/Set-Content.md
- reference/5.0/Microsoft.PowerShell.Management/Set-Content.md
- reference/5.1/Microsoft.PowerShell.Management/Set-Content.md
- reference/6/Microsoft.PowerShell.Management/Set-Content.md
> Fixed Doc error on Set-Content, across all versions

- gallery/TOC.md
- gallery/psgallery/Creating-and-Publishing-an-item.md
- gallery/psgallery/psgallery-PublishingGuidelines.md
- gallery/psgallery/psgallery-SocialMediaFeedback.md
- gallery/psgallery/psgallery_creating_an_account.md
@eslesar @juanpablojofre @bmanikm @KrishnaV-MSFT please review, adding new gallery content
> Updating Gallery TOC & adding new contributing docs

- reference/6/Microsoft.WSMan.Management/Test-WSMan.md
> Update PowerShell 6 Test-WSMan to address #1201

- reference/5.1/Microsoft.WsMan.Management/Test-WSMan.md
> Update PowerShell 5.1 Test-WSMan to address #1201

- reference/5.0/Microsoft.WsMan.Management/Test-WSMan.md
> Update PowerShell 5.0 Test-WSMan to address #1201

- reference/5.1/Microsoft.PowerShell.Core/New-PSSession.md
> Update New-PSSession -RunAsAdministrator for v5.1 to address #1209

- reference/6/Microsoft.PowerShell.Core/New-PSSession.md
> Update New-PSSession -RunAsAdministrator for v6 to address #1209

- reference/5.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/6/About/about_Automatic_Variables.md
This documents properties introduced in 5.0, 5.1, and 6
> Jpjofre i595

- dsc/authoringResourceClass.md
- dsc/authoringResourceComposite.md
- dsc/authoringResourceMOF.md
- dsc/runAsUser.md
> added info about using  in custom resources

- dsc/scriptResource.md
as referenced in https://github.com/PowerShell/PowerShell-Docs/issues/1207
> Fix Typo in Script Resource Example 2 Code

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/6/About/about_Functions_CmdletBindingAttribute.md
- add headings for arguments
- add code formatting
> Improve about_Functions_CmdletBindingAttribute.md

- STYLE.md
Correcting "C:\ PS>" to "PS C:\>" & added some correct or incorrect examples
> Updated Style.md

- wmf/5.0/dsc_importdscresource.md
> Fix typo in dsc_importdscresource.md

- gallery/TOC.md
Add psget/get_psget_module.md to TOC
> add get powershellget module to toc

- reference/3.0/Microsoft.PowerShell.Management/Stop-Process.md
- reference/4.0/Microsoft.PowerShell.Management/Stop-Process.md
- reference/5.0/Microsoft.PowerShell.Management/Stop-Process.md
- reference/5.1/Microsoft.PowerShell.Management/Stop-Process.md
- reference/6/Microsoft.PowerShell.Management/Stop-Process.md
> Default for stop-process is not to prompt.  Fixed doc.

- reference/6/Microsoft.PowerShell.Utility/Measure-Command.md
> Updated Measure-Command.md for 6.0 #1233 #1259

- reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md
> Updated Measure-Command.md for 5.1 #1233 #1259

- reference/3.0/Microsoft.PowerShell.Utility/Measure-Command.md
> Updated Measure-Command.md for 3.0 #1233 #1259

- reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md
> Updated Measure-Command.md for 4.0 #1233 #1259

- reference/5.0/Microsoft.PowerShell.Utility/Measure-Command.md
> Updated Measure-Command.md for 5.0 #1233 #1259

- reference/3.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md
Hi, guys.
A few remarks to this contribution to Powershell help:
1. Regarding example below:
**-- Add an Add-PsSnapin command to add any Windows PowerShell snap-ins that
you use.**
Actually we have header for example, but actual code example is missed.
I've deleted **-- Add an Add-PsSnapin command to add any Windows PowerShell snap-ins that
you use.** as it doesn't make sense without proper example code.
2. **Regarding example function "Customize your console"**
function Color-Console
{
$Host.ui.rawui.backgroundcolor = "white"
$Host.ui.rawui.foregroundcolor = "black"
$hosttime = (Get-ChildItem -Path $pshome\PowerShell.exe).CreationTime
$hostversion="$($Host.Version.Major)`.$($Host.Version.Minor)"
$Host.UI.RawUI.WindowTitle = "Windows PowerShell $hostversion ($hosttime)"
Clear-Host
} …
> Minor changes for about_Profiles

- reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md
> Updated about_pipelines.md for PowerShell 3.0

- reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md
> Updated about_pipelines.md for PowerShell 4.0

- reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md
> Updated about_pipelines.md for PowerShell 5.0

- reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md
> Updated about_pipelines.md for PowerShell 5.1

- reference/6/About/about_pipelines.md
> Updated about_pipelines.md for PowerShell 6.0

- reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
> Updated about_Comment_Based_Help.md for 3.0

- reference/4.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
> Updated about_Comment_Based_Help.md for 4.0

- reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
> Updated about_Comment_Based_Help.md for 5.0

- reference/6/About/about_Comment_Based_Help.md
> Updated about_Comment_Based_Help.md for 6.0

- reference/3.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/6/About/about_Hash_Tables.md
OrderedDictiory -> OrderedDictionary
> Fix typo in about_Hash_Tables.md

- reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
> Fixed a typo

- reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
> Updated about_Execution_Policies.md for 3.0

- reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
> Updated about_Execution_Policies.md for 4.0

- reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
> Updated about_Execution_Policies.md for 5.0

- reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
Fixed the formatting instead to make it consistent with other PR for 3.0, 4.0, 5.0 and 6.0.
> Updated about_Execution_Policies.md for 5.1

- reference/6/About/about_Execution_Policies.md
> Updated about_Execution_Policies.md for 6.0

- reference/3.0/Microsoft.PowerShell.Core/About/about_History.md
> Updated about_History.md for 3.0

- reference/4.0/Microsoft.PowerShell.Core/About/about_History.md
> Updated about_History.md for 4.0

- reference/5.0/Microsoft.PowerShell.Core/About/about_History.md
> Updated about_History.md for 5.0

- reference/5.1/Microsoft.PowerShell.Core/About/about_History.md
> Updated about_History.md for 5.1

- reference/6/About/about_History.md
> Updated about_History.md for 6.0

- reference/3.0/Microsoft.PowerShell.Core/About/about_Data_Sections.md
> Updated about_Data_Sections.md for 3.0

- reference/4.0/Microsoft.PowerShell.Core/About/about_Data_Sections.md
> Updated about_Data_Sections.md for 4.0

- reference/5.0/Microsoft.PowerShell.Core/About/about_Data_Sections.md
> Updated about_Data_Sections.md for 5.0

- reference/6/About/about_Data_Sections.md
> Updated about_Data_Sections.md for 6.0

- reference/5.1/Microsoft.PowerShell.Core/About/about_Data_Sections.md
Fixed Formatting to be consistent across 3.0, 4.0, 5.0, 6.0
> Updated about_Data_Sections.md for 5.1

- reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md
> Updated Get-Date.md for 3.0

- reference/4.0/Microsoft.PowerShell.Utility/Get-Date.md
> Updated Get-Date.md for 4.0

- reference/5.0/Microsoft.PowerShell.Utility/Get-Date.md
Fixed Formatting Issue and included the fix in #1324
> Updated Get-Date.md for 5.0

- reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md
> Updated Get-Date.md for 5.1

- reference/6/Microsoft.PowerShell.Utility/Get-Date.md
Fixed Formatting Issue and included the fix in #1324
> Updated Get-Date.md for 6.0

- reference/5.1/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
> Edited FileSystem-Provider.md

- reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
> Fix Formatting on Invoke-RestMethod.md for 3.0

- reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
> Fix Formatting on Invoke-RestMethod.md for 4.0

- reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
> Fix Formatting on Invoke-RestMethod.md for 5.0

- reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
> Fix Formatting on Invoke-RestMethod.md for 5.1

- reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
> Fix Formatting on Invoke-RestMethod.md for 6.0

- reference/3.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/6/About/about_Continue.md
> Edited about-Continue.md

- reference/6/Microsoft.PowerShell.Core/Providers/ToC.md
> Updated Providers ToC.md for 6.0

- reference/5.1/Microsoft.PowerShell.Core/Providers/ToC.md
> Updated Providers ToC.md for 5.1

- reference/5.0/Microsoft.PowerShell.Core/Providers/ToC.md
> Updated Providers ToC.md for 5.0

- reference/4.0/Microsoft.PowerShell.Core/Providers/ToC.md
> Updated Providers ToC.md for 4.0

- reference/5.1/Microsoft.PowerShell.Core/ToC.md
> Updated Microsoft.PowerShell.Core ToC.md for 5.1

- reference/5.0/Microsoft.PowerShell.Core/ToC.md
> Updated Microsoft.PowerShell.Core ToC.md for 5.0

- reference/4.0/Microsoft.PowerShell.Core/ToC.md
> Updated Microsoft.PowerShell.Core ToC.md for 4.0

- reference/4.0/ToC.md
> Updated ToC.md for 4.0

- reference/5.0/ToC.md
> Updated ToC.md for 5.0

- reference/5.1/ToC.md
> Updated ToC.md for 5.1

- reference/3.0/ToC.md
> Updated ToC.md for 3.0

- reference/3.0/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
> Updated FileSystem-Provider.md for 3.0

- reference/4.0/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
> Updated FileSystem-Provider.md for 4.0

- reference/5.0/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
> Updated FileSystem-Provider.md for 5.0

- reference/5.1/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
> Updated FileSystem-Provider.md for 5.1

- reference/6/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
> Updated FileSystem-Provider.md for 6.0

- gallery/psgallery/psgallery-PublishingGuidelines.md
> a few typos and formatting changes

- reference/3.0/Microsoft.PowerShell.Management/Rename-Item.md
- reference/4.0/Microsoft.PowerShell.Management/Rename-Item.md
- reference/5.0/Microsoft.PowerShell.Management/Rename-Item.md
- reference/5.1/Microsoft.PowerShell.Management/Rename-Item.md
- reference/6/Microsoft.PowerShell.Management/Rename-Item.md
> Making Rename-Item Example 4 more precise.

- dsc/registryResource.md
There are some special cases in the Registry resource that need to be documented.
> Adding details to Registry parameters

- dsc/registryResource.md
- dsc/windowsOptionalFeatureResource.md
- dsc/windowsOptionalFeatureSetResource.md
> fixed error in WindowsOptionalFeature resources

- reference/5.0/Microsoft.PowerShell.Utility/Convert-String.md
- reference/5.1/Microsoft.PowerShell.Utility/Convert-String.md
Fixed #1257 Convert-String has incorrect example
> jpjofre-I1257A fixed #1257 Convert-String has incorrect example

- gallery/psgallery/psgallery-PublishingGuidelines.md
> Add missing word

- gallery/psgallery/psgallery_gettingstarted.md
> Some updates

- reference/3.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/3.0/Microsoft.PowerShell.Core/Providers/Environment-Provider.md
- reference/3.0/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
- reference/3.0/Microsoft.PowerShell.Core/Providers/Function-Provider.md
- reference/3.0/Microsoft.PowerShell.Core/Providers/Registry-Provider.md
- reference/3.0/Microsoft.PowerShell.Core/Providers/Variable-Provider.md
- reference/4.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/4.0/Microsoft.PowerShell.Core/Providers/Environment-Provider.md
- reference/4.0/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
- reference/4.0/Microsoft.PowerShell.Core/Providers/Function-Provider.md
- reference/4.0/Microsoft.PowerShell.Core/Providers/Registry-Provider.md
- reference/4.0/Microsoft.PowerShell.Core/Providers/Variable-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Environment-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Function-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Registry-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Variable-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Environment-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Function-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Registry-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Variable-Provider.md
- reference/6/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/6/Microsoft.PowerShell.Core/Providers/Environment-Provider.md
- reference/6/Microsoft.PowerShell.Core/Providers/FileSystem-Provider.md
- reference/6/Microsoft.PowerShell.Core/Providers/Function-Provider.md
- reference/6/Microsoft.PowerShell.Core/Providers/Registry-Provider.md
- reference/6/Microsoft.PowerShell.Core/Providers/Variable-Provider.md
> Edited 'Environment-Provider', 'Variable-Provider' & Final corrections for '*-Provider'

- reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/6/About/about_Requires.md
ref #1260 
- [X ] Impacts 6 document
- [X ] Impacts 5.1 document
- [X ] Impacts 5.0 document
- [X ] Impacts 4.0 document
- [X ] Impacts 3.0 document
Calrifying -RunAsAdministrator switch.
> Updating about_requires

- reference/6/About/about_Escape_Characters.md
- reference/6/About/about_Special_Characters.md
This PR is tied to the acceptance of the PR https://github.com/PowerShell/PowerShell/pull/3958.
> Address feedback on new escape characters.

- dsc/pullServer.md
> corrected the resource name

- dsc/configDataCredentials.md
- gallery/psgallery/psgallery_status.md
- gallery/psget/repository/bootstrapping_nuget_proivder_and_exe.md
- reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Enum.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Enum.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/6/About/about_Enum.md
- scripting/core-powershell/ise/How-to-Use-Profiles-in-Windows-PowerShell-ISE.md
- scripting/core-powershell/ise/The-ISEAddOnToolCollection-Object.md
- scripting/core-powershell/ise/The-ISEEditor-Object.md
- wmf/5.0/class_base.md
- wmf/5.0/class_baseconstructor.md
- wmf/5.0/class_basemethod.md
- wmf/5.0/class_interface.md
- wmf/5.0/dsc_testconfiguration.md
- wmf/5.0/dsc_updateconfig.md
- wmf/5.0/feedback_archive.md
- wmf/5.0/feedback_formathex.md
- wmf/5.0/feedback_moduleversionranges.md
- wmf/5.0/feedback_nonewline.md
- wmf/5.1/DSC-improvements.md
- wmf/5.1/catalog-cmdlets.md
- wmf/5.1/known-issues.md
- wmf/5.1/scenarios-features.md
> Replace ```PowerShell  with ```powershell code tag

- reference/3.0/Microsoft.PowerShell.Core/About/about_Break.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Do.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_For.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Foreach.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Break.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Do.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_For.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Foreach.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Break.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Do.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_For.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Foreach.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Continue.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Do.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_For.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Foreach.md
- reference/6/About/about_Break.md
- reference/6/About/about_Continue.md
- reference/6/About/about_Do.md
- reference/6/About/about_For.md
- reference/6/About/about_Foreach.md
Updated formatting and MD styles for:
- about_Break.md    
- about_Continue.md 
- about_Do.md       
- about_For.md      
- about_Foreach.md  
Bug ID | Title
-- | --
1024156 | about_break review format and rendering
1024165 | about_continue review format and rendering
1024170 | about_do review format and rendering
1024177 | about_for review format and rendering
1024178 | about_foreach review format and rendering
> freshen format of about docs

- dsc/pullServer.md
Fix a few minor spelling and grammar issues and list numbering
> Spelling and grammar in pullServer.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Throw.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Throw.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Throw.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Throw.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
- reference/6/About/about_Throw.md
- reference/6/About/about_Trap.md
- reference/6/About/about_Try_Catch_Finally.md
BugID | Title
-- | --
1024260 | about_throw review format and rendering
1024262 | about_trap review format and rendering
1024263 | about_try_catch_finally review format and rendering
> reformatting about topics - last of flow topics

- gallery/psgallery/psgallery-PublishingGuidelines.md
- wmf/5.1/install-configure.md
- wmf/5.1/release-notes.md
Modifications to WMF 5.1 requirements and Gallery Publishing guidelines, closing doc issues 1369,1210.
- [X ] Impacts 5.1 document
- [X ] The documented feature was introduced in version 5.1 of PowerShell, and WMF 5.1
> Minor fixes for doc issues 1369, 1210

- reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/5.1/PowershellGet/Update-ModuleManifest.md
- reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md
- reference/6/PowerShellGet/Update-ModuleManifest.md
Fixed New-ModuleManifest.md and Update-ModuleManifest.md (resolved #1087)
> Fix descriptions for the CompatiblePSEditions parameter

- README.md
We have two license files and need to clarify the relative scope of each.
> Clarified licenses

- reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md
- reference/6/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/6/Microsoft.PowerShell.Core/New-PSSession.md
Added documentation for new SSHHost parameter set in Enter-PSSession.
There are three cmdlets that have been updated for SSH base remoting:
Enter-PSSession
New-PSSession
Invoke-Command
> Added new SSH parameter set info to Enter-PSSession cmdlet

- reference/3.0/Microsoft.PowerShell.Core/Get-Job.md
- reference/3.0/Microsoft.PowerShell.Core/Resume-Job.md
- reference/3.0/Microsoft.PowerShell.Core/Stop-Job.md
- reference/3.0/Microsoft.PowerShell.Core/Suspend-Job.md
- reference/3.0/Microsoft.PowerShell.Core/Wait-Job.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Job.md
- reference/4.0/Microsoft.PowerShell.Core/Resume-Job.md
- reference/4.0/Microsoft.PowerShell.Core/Stop-Job.md
- reference/4.0/Microsoft.PowerShell.Core/Suspend-Job.md
- reference/4.0/Microsoft.PowerShell.Core/Wait-Job.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Job.md
- reference/5.0/Microsoft.PowerShell.Core/Resume-Job.md
- reference/5.0/Microsoft.PowerShell.Core/Stop-Job.md
- reference/5.0/Microsoft.PowerShell.Core/Suspend-Job.md
- reference/5.0/Microsoft.PowerShell.Core/Wait-Job.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Job.md
- reference/5.1/Microsoft.PowerShell.Core/Resume-Job.md
- reference/5.1/Microsoft.PowerShell.Core/Stop-Job.md
- reference/5.1/Microsoft.PowerShell.Core/Suspend-Job.md
- reference/5.1/Microsoft.PowerShell.Core/Wait-Job.md
- reference/6/Microsoft.PowerShell.Core/Get-Job.md
- reference/6/Microsoft.PowerShell.Core/Stop-Job.md
- reference/6/Microsoft.PowerShell.Core/Wait-Job.md
Fixed url, formatting and minor differences in wording.
> Fix link for JobState Enumeration

- reference/5.0/Microsoft.PowerShell.Utility/Import-LocalizedData.md
- reference/5.1/Microsoft.PowerShell.Utility/Import-LocalizedData.md
- reference/6/Microsoft.PowerShell.Utility/Import-LocalizedData.md
> Add a related link to Import-PowerShellDataFile

- dsc/quickStart.md
Replace `[Desired State Configuration Overview for Decision Makers](DscForEngineers.md)` to `[Desired State Configuration Overview for Decision Makers](decisionMaker.md)` to fix #1485
> Replace the link with the correct link

- reference/mapping/monikerMapping.json
> updates monikermapping to latest

- .openpublishing.redirection.json
> updating broken redirections

- .openpublishing.redirection.json
> fix about topic broken redirections

- reference/3.0/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/4.0/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/5.0/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/5.1/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/6/Microsoft.PowerShell.Management/Get-PSDrive.md
Fixed the followings:
* Inconsistency between the output and the description
* Output order, capitalization, and line break
> Fix the Example 1 of Get-PSDrive

- .openpublishing.redirection.json
- appveyor.ps1
- reference/3.0/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/4.0/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/5.0/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/5.1/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/6/Microsoft.PowerShell.Management/Get-PSDrive.md
- wmf/5.1/Index.md
- wmf/5.1/release-notes.md
> Merging into live

- reference/3.0/Microsoft.PowerShell.Utility/Add-Member.md
- reference/3.0/Microsoft.PowerShell.Utility/Get-Member.md
- reference/3.0/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/4.0/Microsoft.PowerShell.Utility/Add-Member.md
- reference/4.0/Microsoft.PowerShell.Utility/Get-Member.md
- reference/4.0/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/5.0/Microsoft.PowerShell.Utility/Add-Member.md
- reference/5.0/Microsoft.PowerShell.Utility/Get-Member.md
- reference/5.0/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md
- reference/5.1/Microsoft.PowerShell.Utility/Get-Member.md
- reference/5.1/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/6/Microsoft.PowerShell.Utility/Add-Member.md
- reference/6/Microsoft.PowerShell.Utility/Get-Member.md
- reference/6/Microsoft.PowerShell.Utility/Update-TypeData.md
Fixed url, formatting and minor differences in wording.
> Fix link for PSMemberTypes Enumeration

- reference/3.0/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/4.0/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/5.0/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/5.0/Microsoft.PowerShell.Management/Stop-Computer.md
- reference/5.0/Microsoft.PowerShell.Management/Test-Connection.md
- reference/5.1/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/5.1/Microsoft.PowerShell.Management/Stop-Computer.md
- reference/5.1/Microsoft.PowerShell.Management/Test-Connection.md
- reference/6/Microsoft.PowerShell.Management/Restart-Computer.md
- reference/6/Microsoft.PowerShell.Management/Stop-Computer.md
- reference/6/Microsoft.PowerShell.Management/Test-Connection.md
> Fix link for AuthenticationLevel Enumeration

- reference/docfx.json
> adding config for cmdlet browser

- gallery/docfx.json
> Update docfx.json for gallery

- reference/docs-conceptual/core-powershell/Running-Remote-Commands.md
Fix a missing parameter name and a casing for a property name.
> Fix parameter name

- gallery/docfx.json
> update docfx.json , fix breadcrumb file

- gallery/psgallery/psgallery-PublishingGuidelines.md
Updating the PSGallery publishing guidelines with info on testing to a local repo.
> Jkeithb fixes08

- reference/3.0/Microsoft.PowerShell.Management/Get-Process.md
- reference/4.0/Microsoft.PowerShell.Management/Get-Process.md
- reference/5.0/Microsoft.PowerShell.Management/Get-Process.md
- reference/5.1/Microsoft.PowerShell.Management/Get-Process.md
- reference/6/Microsoft.PowerShell.Management/Get-Process.md
> Fix link for Process Properties

- reference/3.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
- reference/3.0/Microsoft.PowerShell.Utility/Select-Xml.md
- reference/4.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
- reference/4.0/Microsoft.PowerShell.Utility/Select-Xml.md
- reference/5.0/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
- reference/5.0/Microsoft.PowerShell.Utility/Select-Xml.md
- reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
- reference/5.1/Microsoft.PowerShell.Utility/Select-Xml.md
- reference/6/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
- reference/6/Microsoft.PowerShell.Utility/Select-Xml.md
> Fix link for XPath Reference, Event Selection, and Query Schema

- reference/3.0/Microsoft.PowerShell.Management/Debug-Process.md
- reference/4.0/Microsoft.PowerShell.Management/Debug-Process.md
- reference/5.0/Microsoft.PowerShell.Management/Debug-Process.md
- reference/5.1/Microsoft.PowerShell.Management/Debug-Process.md
- reference/6/Microsoft.PowerShell.Management/Debug-Process.md
Fixed formatting and minor differences in wording.
> Fix link for AttachDebugger method

- reference/3.0/Microsoft.PowerShell.Utility/Select-Object.md
- reference/4.0/Microsoft.PowerShell.Utility/Select-Object.md
- reference/5.0/Microsoft.PowerShell.ODataUtils/Export-ODataEndpointProxy.md
- reference/5.0/Microsoft.PowerShell.Utility/Select-Object.md
- reference/5.1/Microsoft.PowerShell.ODataUtils/Export-ODataEndpointProxy.md
- reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md
- reference/6/Microsoft.PowerShell.Utility/Select-Object.md
> Fix link for Strongly Encouraged Development Guidelines

- reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md
- reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md
- reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md
- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md
> Fix link for Regex.Unescape Method

- reference/5.0/PowershellGet/Publish-Module.md
- reference/5.1/PowershellGet/Publish-Module.md
- reference/6/PowerShellGet/Publish-Module.md
* Removed 'PS C:> '
* cmdlet, \*\*cmdlet\*\* -> \`cmdlet\`
> Fix code style of Publish-Module

- gallery/bread/toc.yml
- gallery/docfx.json
- jea/bread/toc.yml
- jea/docfx.json
- reference/bread/toc.yml
- reference/docfx.json
- wmf/bread/toc.yml
- wmf/docfx.json
> adding JEA bread

- reference/3.0/Microsoft.PowerShell.Utility/Sort-Object.md
- reference/4.0/Microsoft.PowerShell.Utility/Sort-Object.md
- reference/5.0/Microsoft.PowerShell.Utility/Sort-Object.md
- reference/5.1/Microsoft.PowerShell.Utility/Sort-Object.md
- reference/6/Microsoft.PowerShell.Utility/Sort-Object.md
> Fix link for ServiceControllerStatus Enumeration

- reference/3.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/4.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/5.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/6/Microsoft.PowerShell.Utility/Write-Progress.md
> Fix link for ProgressRecord Class

- reference/3.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
> Fix scrambled table

- reference/3.0/Microsoft.PowerShell.Core/Get-Module.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Module.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Module.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Module.md
- reference/6/Microsoft.PowerShell.Core/Get-Module.md
Fixed formatting and minor differences in wording.
> Fix link for PSModuleInfo Properties

- reference/3.0/Microsoft.PowerShell.Security/Get-Acl.md
- reference/3.0/Microsoft.PowerShell.Security/Set-Acl.md
- reference/4.0/Microsoft.PowerShell.Security/Get-Acl.md
- reference/4.0/Microsoft.PowerShell.Security/Set-Acl.md
- reference/5.0/Microsoft.PowerShell.Security/Get-Acl.md
- reference/5.0/Microsoft.PowerShell.Security/Set-Acl.md
- reference/5.1/Microsoft.PowerShell.Security/Get-Acl.md
- reference/5.1/Microsoft.PowerShell.Security/Set-Acl.md
- reference/6/Microsoft.PowerShell.Security/Get-Acl.md
- reference/6/Microsoft.PowerShell.Security/Set-Acl.md
Fixed link text, formatting, and minor differences in wording.
> Fix link for Dynamic Access Control

- reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md
> Remove details about InformationVariable and -InformationAction as they are common parameters.

- reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/3.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/4.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/5.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
- reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md
> Fix link for JavaScriptSerializer Class

- reference/3.0/Microsoft.PowerShell.Core/New-PSSessionOption.md
- reference/4.0/Microsoft.PowerShell.Core/New-PSSessionOption.md
- reference/5.0/Microsoft.PowerShell.Core/New-PSSessionOption.md
- reference/5.1/Microsoft.PowerShell.Core/New-PSSessionOption.md
- reference/6/Microsoft.PowerShell.Core/New-PSSessionOption.md
> Fix link for ProxyAccessType Enumeration

- reference/5.0/Microsoft.PowerShell.Core/About/about_desiredstateconfiguration.md
- reference/5.0/PowershellGet/Find-DscResource.md
- reference/5.0/PowershellGet/Find-Module.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_desiredstateconfiguration.md
- reference/5.1/PowershellGet/Find-DscResource.md
- reference/5.1/PowershellGet/Find-Module.md
- reference/6/PowerShellGet/Find-DscResource.md
- reference/6/PowerShellGet/Find-Module.md
Fixed formatting and minor differences in wording.
> Fix link for PowerShell Gallery

- reference/3.0/Microsoft.PowerShell.Management/Write-EventLog.md
- reference/4.0/Microsoft.PowerShell.Management/Write-EventLog.md
- reference/5.0/Microsoft.PowerShell.Management/Write-EventLog.md
- reference/5.1/Microsoft.PowerShell.Management/Write-EventLog.md
Fixed formatting, and minor differences in wording.
> Fix link for EventLogEntryType Enumeration

- reference/3.0/Microsoft.PowerShell.Management/Start-Process.md
- reference/4.0/Microsoft.PowerShell.Management/Start-Process.md
- reference/5.0/Microsoft.PowerShell.Management/Start-Process.md
- reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
- reference/6/Microsoft.PowerShell.Management/Start-Process.md
> Fix link for Process.Start Method

- reference/5.0/Microsoft.PowerShell.Management/Get-PSDrive.md
Fixed the Example 2 and 3 in version 5.0 of Get-PSDrive cmdlet.
The Example 1, 4, and 5 are already fixed. (See #1489, #1545, #1468)
> Fix #958 (Get-PSDrive v5.0)

- reference/3.0/Microsoft.PowerShell.Management/Set-WmiInstance.md
- reference/4.0/Microsoft.PowerShell.Management/Set-WmiInstance.md
- reference/5.0/Microsoft.PowerShell.Management/Set-WmiInstance.md
- reference/5.1/Microsoft.PowerShell.Management/Set-WmiInstance.md
- reference/6/CimCmdlets/Get-CimInstance.md
- reference/6/CimCmdlets/New-CimInstance.md
- reference/6/CimCmdlets/Remove-CimInstance.md
- reference/6/CimCmdlets/Set-CimInstance.md
Fixed formatting and PascalCase.
> Fix link for Set-CimInstance and New-CimInstance

- dsc/docfx.json
- gallery/docfx.json
- jea/docfx.json
- reference/docfx.json
- wmf/docfx.json
> Add UHF and Powershell version picker 

- reference/mapping/monikerMapping.json
> change from toc.md to toc.yml in mapping file

- reference/docs-conceptual/setup/Installing-Windows-PowerShell.md
> Spelling fix on the  powershell command

- gallery/psgallery/psgallery-PublishingGuidelines.md
SemVer has [] but no corresponding (). Fix'd. @JKeithB
> Fix broken link in PS Gallery dfocs

- reference/3.0/Microsoft.PowerShell.Core/About/about_PSSnapins.md
- reference/3.0/Microsoft.PowerShell.Core/Add-PSSnapin.md
- reference/3.0/Microsoft.PowerShell.Core/Get-PSSnapin.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_PSSnapins.md
- reference/4.0/Microsoft.PowerShell.Core/Add-PSSnapin.md
- reference/4.0/Microsoft.PowerShell.Core/Get-PSSnapin.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_PSSnapins.md
- reference/5.0/Microsoft.PowerShell.Core/Add-PSSnapin.md
- reference/5.0/Microsoft.PowerShell.Core/Get-PSSnapin.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_PSSnapins.md
- reference/5.1/Microsoft.PowerShell.Core/Add-PSSnapin.md
- reference/5.1/Microsoft.PowerShell.Core/Get-PSSnapin.md
- reference/6/Microsoft.PowerShell.Core/About/about_PSSnapins.md
> Fix link for How to Snap-in

- reference/3.0/Microsoft.PowerShell.Management/Add-Computer.md
- reference/4.0/Microsoft.PowerShell.Management/Add-Computer.md
- reference/5.0/Microsoft.PowerShell.Management/Add-Computer.md
- reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md
> Fix link for JoinDomainOrWorkgroup and NetJoinDomain

- reference/3.0/Microsoft.PowerShell.Utility/Update-List.md
- reference/4.0/Microsoft.PowerShell.Utility/Update-List.md
- reference/5.0/Microsoft.PowerShell.Utility/Update-List.md
- reference/5.1/Microsoft.PowerShell.Utility/Update-List.md
> Fix link for Get-Mailbox

- reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
> Add missing web cmdlets parameters.

- gallery/readme.md
> Remove TP5 from Windows 2016

- reference/3.0/Microsoft.PowerShell.Utility/Show-Command.md
- reference/4.0/Microsoft.PowerShell.Utility/Show-Command.md
- reference/5.0/Microsoft.PowerShell.Utility/Show-Command.md
- reference/5.1/Microsoft.PowerShell.Utility/Show-Command.md
x about_PSDefaultParameterValues
o about_Parameters_Default_Values
> Fix link for "about_PSDefaultParameterValues"

- reference/3.0/Microsoft.PowerShell.Core/New-PSSessionOption.md
- reference/4.0/Microsoft.PowerShell.Core/New-PSSessionOption.md
- reference/5.0/Microsoft.PowerShell.Core/New-PSSessionOption.md
- reference/5.1/Microsoft.PowerShell.Core/New-PSSessionOption.md
- reference/6/Microsoft.PowerShell.Core/New-PSSessionOption.md
> Fix link for Setspn Overview

- reference/3.0/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/6/Microsoft.PowerShell.Core/About/about_Parsing.md
> Fix table format of about_Parsing.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/6/Microsoft.PowerShell.Core/About/about_Providers.md
> Fix built-in providers table format

- reference/3.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md
* Filled missing cells
* Shortened descriptions
* Fixed format
> Fix table of about_Wildcards.md

- dsc/authoringResourceMofCS.md
> Fix authoringResourceMofCS.md title

- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
> Fix ValidatePattern code block in about_Functions_Advanced_Parameters.md

- reference/3.0/Microsoft.PowerShell.Utility/Add-Type.md
- reference/4.0/Microsoft.PowerShell.Utility/Add-Type.md
- reference/5.0/Microsoft.PowerShell.Utility/Add-Type.md
- reference/5.1/Microsoft.PowerShell.Utility/Add-Type.md
- reference/6/Microsoft.PowerShell.Utility/Add-Type.md
> Fix link for ShowWindowAsync function

- reference/6/Microsoft.PowerShell.Core/Get-Help.md
> Remove -showwindow from get-help

- reference/6/Microsoft.PowerShell.Management/Split-Path.md
> Add Extension and LeafBase parameter.

- reference/3.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/6/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
Fixed heading level, PascalCase, link, etc.
> Fix formatting: about_Script_Blocks.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
Fixed heading level, code block, link, etc.
> Fix formatting: about_Environment_Variables.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
- reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
Fixed heading level, table, link, etc.
> Fix formatting: about_Execution_Policies.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md
- reference/6/Microsoft.PowerShell.Core/About/about_Modules.md
Fixed heading level, code block, link, etc.
> Fix formatting: about_Modules.md

- gallery/readme.md
> Fix PowerShellGet functions' link in The PowerShell Gallery readme.md

- gallery/psgallery/psgallery_gettingstarted.md
> Fix PowerShellGet functions' link in psgallery_gettingstarted.md

- reference/3.0/Microsoft.PowerShell.Core/Receive-PSSession.md
- reference/4.0/Microsoft.PowerShell.Core/Receive-PSSession.md
- reference/5.0/Microsoft.PowerShell.Core/Receive-PSSession.md
- reference/5.1/Microsoft.PowerShell.Core/Receive-PSSession.md
- reference/6/Microsoft.PowerShell.Core/Receive-PSSession.md
> Fix example number from 5 to 6 in Receive-PSSession.md

- reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
Reflects changes in PSCore6 and aligns with the built in help
> updated powershell.exe help to reflect current PSCore6 behavior

- reference/6/CimCmdlets/CimCmdlets.md
- reference/6/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md
- reference/6/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md
- reference/6/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.md
- reference/6/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.md
- reference/6/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.md
- reference/6/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md
- reference/6/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
- reference/6/Microsoft.WSMan.Management/Microsoft.WsMan.Management.md
- reference/6/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md
- reference/6/PSDiagnostics/PSDiagnostics.md
- reference/6/PSReadLine/PSReadline.md
- reference/6/PackageManagement/PackageManagement.md
- reference/6/PowerShellGet/PowerShellGet.md
> Updated landing pages with fwlinks

- reference/3.0/Microsoft.PowerShell.Core/About/about_Objects.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Objects.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Objects.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Objects.md
- reference/6/Microsoft.PowerShell.Core/About/about_Objects.md
Fixed heading level, code block, link, etc.
> Fix formatting: about_Objects.md

- gallery/psgallery/psgallery_status.md
> Updating Gallery Status for issue on 10/10/2017

- reference/3.0/Microsoft.PowerShell.Management/Start-Process.md
- reference/4.0/Microsoft.PowerShell.Management/Start-Process.md
- reference/5.0/Microsoft.PowerShell.Management/Start-Process.md
- reference/6/Microsoft.PowerShell.Management/Start-Process.md
Wraps up remaining changes needed for #1699.
> Update Start-Process.md WorkingDirectory details

- reference/3.0/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/6/Microsoft.PowerShell.Core/About/about_Parsing.md
Fixed heading level, code block, etc.
> Fix formatting: about_Parsing.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Core_Commands.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Core_Commands.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Core_Commands.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Core_Commands.md
- reference/6/Microsoft.PowerShell.Core/About/about_Core_Commands.md
> Fix formatting: about_Core_Commands.md

- jea/security-considerations.md
> Fix spelling

- reference/3.0/Microsoft.PowerShell.Core/About/about_PSSession_Details.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_PSSession_Details.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_PSSession_Details.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_PSSession_Details.md
- reference/6/Microsoft.PowerShell.Core/About/about_PSSession_Details.md
Fixed heading level, code block, etc.
> Fix formatting: about_PSSession_Details.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_PSSessions.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_PSSessions.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_PSSessions.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_PSSessions.md
- reference/6/Microsoft.PowerShell.Core/About/about_PSSessions.md
Fixed heading level, code block, link, etc.
> Fix formatting: about_PSSessions.md

- dsc/waitForSomeResource.md
User-reported issues with DSC Wait For some
> bug fixes to DSC WaitForSome

- reference/3.0/Microsoft.PowerShell.Core/About/about_Aliases.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Aliases.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Aliases.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Aliases.md
- reference/6/Microsoft.PowerShell.Core/About/about_Aliases.md
> Fix formatting: about_Aliases.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md
Fixed heading level, code block, etc.
> Fix formatting: about_Remote_Disconnected_Sessions.md

- dsc/TOC.md
- dsc/metaConfig.md
- dsc/metaConfig4.md
Updates LCM pages to ensure the service in Azure and on-premises options are both explained well.
Also modifies the TOC page by putting both LCM pages at the same level, with a top level folder rather than the top level item being a standalone page.
Attention: @Indhukrishna @OaaSTeam @eslesar
> Mgreenegit patch 1

- dsc/lnxGettingStarted.md
correct link and link text from dn407379).aspx to dn407379.aspx)
please help to review and merge it, thanks.
> Correct link in lnxGettingStarted.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_History.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_History.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_History.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_History.md
- reference/6/Microsoft.PowerShell.Core/About/about_History.md
Added ghy, history, and ihy. And fixed formatting.
> Add aliases to history cmdlets table

- reference/3.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
To make it clear which is the expression and which is the result.
> Add "Result" column to bitwise operators table

- reference/docs-conceptual/core-powershell/Running-Remote-Commands.md
v5.1 urls are "online version" metadata url.
> Update v2.0 cmdlet url with v5.1 in Running-Remote-Commands.md

- reference/6/CimCmdlets/CimCmdlets.md
- reference/6/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md
- reference/6/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md
- reference/6/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.md
- reference/6/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.md
- reference/6/Microsoft.PowerShell.LocalAccounts/Microsoft.PowerShell.LocalAccounts.md
- reference/6/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.md
- reference/6/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md
- reference/6/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
- reference/6/Microsoft.WSMan.Management/Microsoft.WSMan.Management.md
- reference/6/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md
- reference/6/PSDiagnostics/PSDiagnostics.md
- reference/6/PSReadLine/PSReadLine.md
- reference/6/PackageManagement/PackageManagement.md
- reference/6/Pester/Pester.md
- reference/6/PowerShellGet/PowerShellGet.md
Locale casing needs to be in xx-XX format so that updatable help find the cab file.
> Fix casing for locale

- reference/3.0/Microsoft.PowerShell.Core/About/about_Eventlogs.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Eventlogs.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Eventlogs.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Eventlogs.md
- reference/6/Microsoft.PowerShell.Core/About/about_Eventlogs.md
Fixed heading level, code block, etc.
> Fix formatting: about_Eventlogs.md

- reference/6/Microsoft.PowerShell.Core/About/about_Aliases.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
- reference/6/Microsoft.PowerShell.Core/About/about_Command_Syntax.md
- reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Core_Commands.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_History.md
- reference/6/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/6/Microsoft.PowerShell.Core/About/about_Language_Modes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Parsing.md
- reference/6/Microsoft.PowerShell.Core/About/about_Path_Syntax.md
- reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Ref.md
- reference/6/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
- reference/6/Microsoft.PowerShell.Core/About/about_Special_Characters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/6/Microsoft.PowerShell.Core/About/about_hidden.md
- reference/6/Microsoft.PowerShell.Core/About/about_locations.md
- reference/6/Microsoft.PowerShell.Core/About/about_simplified_syntax.md
Updated formatting of About topics. Fixed some minor issues.
There are multiple issues open for About topics. This PR addresses some of the issues and contains update for v6 only. To manage the size of the PR I will submit PRs for each version, separately.
> cleanup formatting of about topics

- reference/3.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
- reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md
Reverts PowerShell/PowerShell-Docs#1787
> Revert "Undo PR #1781-#1785: about_Wildcards.md"

- reference/3.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
Reverts PowerShell/PowerShell-Docs#1788
> Revert "Undo PR #1781-#1785: about_Environment_Variables.md"

- reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
- missed headers
- missed codesnippets
> Add markdown formatting to about_Scopes

- reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md
Reapplying changed made by @matt9ucci and syncing changes across powershell versions.
> Minor bug fixes for About topics and sync content across versions

- appveyor.yml
> Allow all MD files to trigger AppVeyor

- reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
Changed about_Execution_Policies to be a link to match the other documentation.
> Added about_Execution_Policies link

- reference/docs-conceptual/getting-started/understanding-concepts-reference.md
I guessed at the original intent of the bullets and added links to the relevant documents
> Added relevant links

- reference/3.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
Fix to resolve Issue #1455 Edit to About_Arrays
- [x ] Impacts 6 document
- [x ] Impacts 4.0 document
- [x ] Impacts 3.0 document
> fixing issue 1455 - Edit to About_Arrays

- reference/3.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reformat about_CommonParameters to resolve #1410 
- [ x] Impacts 6 document
- [ x] Impacts 5.1 document
- [ x] Impacts 5.0 document
- [ x] Impacts 4.0 document
- [ x] Impacts 3.0 document
> reformat about_CommonParameters per Issue 1410

- reference/3.0/Microsoft.PowerShell.Security/Set-Acl.md
- reference/4.0/Microsoft.PowerShell.Security/Set-Acl.md
- reference/5.0/Microsoft.PowerShell.Security/Set-Acl.md
- reference/5.1/Microsoft.PowerShell.Security/Set-Acl.md
- reference/6/Microsoft.PowerShell.Security/Set-Acl.md
PR #901 is very old. The changes cannot be merged easily without conflicts. Updated the Set-ACL docs per PR #901 so that it can be closed without merging. 
> updating set-acl docs per PR#901

- dsc/authoringResourceComposite.md
> Fix typo in comment

- reference/6/Microsoft.PowerShell.Core/About/About.md
- reference/6/Microsoft.PowerShell.Core/About/about_PowerShell_Ise_exe.md
- reference/6/Microsoft.PowerShell.Core/About/about_pwsh.md
> Updating the help content for v6.

- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Example number '4' is duplicated.
> Fix example number in Invoke-WebRequest.md

- reference/3.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/4.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/5.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/5.1/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
- reference/6/Microsoft.PowerShell.Core/Providers/Alias-Provider.md
Integrated updates to Alias-Provider.md from PR #1831 and also reformatted with semantic linebreaks.
> reformatting and integrating changes from PR#1831

- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
Example number 12 and 13 are missing.
> Fix example numbers in Get-Help.md

- reference/3.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/4.0/Microsoft.PowerShell.Core/Import-Module.md
Example number '10' is duplicated.
> Fix example numbers in Import-Module.md

- reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
This PR attempts to refresh the web cmdlet documentation for 6.0.0. It includes all up to date parameters, features, and support
* Reference PowerShell/PowerShell#5492
* Documents PowerShell/PowerShell#5329 `-SslProtocol`
* Restores missing syntax and updates syntax to 6.0.0-rc1
* Removes examples no longer valid in PowerShell 6.0.0
* Updates examples to match 6.0.0 usage
* Removes `FILE` and `FTP` schema mentions as they are no longer supported
* Replaces `Windows PowerShell` with `PowerShell` where appropriate
* Aligns document with formatting standards
* Documents PowerShell/PowerShell#5402 
* Adds security warnings to `-SkipCertificateCheck`
* Remove `-InformationAction` and `-InformationVariable` common paramter from paramters list
* Alphabetized Parameters
* Include …
> Web Cmdlets 6.0.0 Documentation Refresh

- reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Output.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Output.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_Output.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Output.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
- reference/6/Microsoft.PowerShell.Core/About/about_Remote_Output.md
- reference/6/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
- reference/6/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/6/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/6/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
reformatting About_* for 80 columns - part 6
Reformatted files to fit in 80 columns per Issue #1806. No other changes to the content except where noted.
- about_Remote_Output.md
- about_Remote_Troubleshooting.md
- about_Requires.md
- about_Scripts.md
- about_Session_Configurations.md
> reformatting About_* for 80 columns - part 6

- reference/3.0/PSScheduledJob/Unregister-ScheduledJob.md
- reference/4.0/PSScheduledJob/Unregister-ScheduledJob.md
- reference/5.0/PSScheduledJob/Unregister-ScheduledJob.md
- reference/5.1/PSScheduledJob/Unregister-ScheduledJob.md
> Fix typo in Unregister-ScheduledJob

- reference/5.0/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/6/Microsoft.PowerShell.Utility/Format-Hex.md
> Add description about Format-Hex -InputObject

- reference/3.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
> Correcting add to hash table example

- reference/3.0/Microsoft.PowerShell.Utility/Set-TraceSource.md
- reference/4.0/Microsoft.PowerShell.Utility/Set-TraceSource.md
- reference/5.0/Microsoft.PowerShell.Utility/Set-TraceSource.md
- reference/5.1/Microsoft.PowerShell.Utility/Set-TraceSource.md
- reference/6/Microsoft.PowerShell.Utility/Set-TraceSource.md
* Fixed the value of "Accepted values:"
* Fixed minor differences in formatting and wording
> Fix Set-TraceSource -ListenerOption parameter

- reference/3.0/Microsoft.PowerShell.Utility/Trace-Command.md
- reference/4.0/Microsoft.PowerShell.Utility/Trace-Command.md
- reference/5.1/Microsoft.PowerShell.Utility/Trace-Command.md
- reference/6/Microsoft.PowerShell.Utility/Trace-Command.md
* Fixed the value of "Accepted values:"
* Fixed minor differences in formatting and wording
> Fix Trace-Command -ListenerOption parameter

- reference/3.0/PSWorkflow/New-PSWorkflowExecutionOption.md
- reference/4.0/PSWorkflow/New-PSWorkflowExecutionOption.md
- reference/5.0/PSWorkflow/New-PSWorkflowExecutionOption.md
- reference/5.1/PSWorkflow/New-PSWorkflowExecutionOption.md
In New-PSWorkflowExecutionOption.md
> Fix link for about_WorkflowCommonParameters

- reference/3.0/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/4.0/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/5.0/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/5.1/Microsoft.PowerShell.Utility/Update-TypeData.md
- reference/6/Microsoft.PowerShell.Utility/Update-TypeData.md
> Fix link for about_Types.ps1xml in Update-TypeData.md

- reference/docs-conceptual/setup/PS-remoting-second-hop.md
> Indent headers as subheaders

- reference/5.1/Microsoft.PowerShell.Management/Limit-EventLog.md
> Update minor typo in Limit-EventLog.md

- dsc/configurations.md
> Adding calling the ComputerName parameter to the example

- reference/4.0/Microsoft.PowerShell.Core/About/about_Debuggers.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_PSSessions.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_PSSnapins.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Remote.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Reserved_Words.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Return.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Session_Configuration_Files.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Signing.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Splatting.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Transactions.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_WMI.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_WQL.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_ISE.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Windows_RT.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_logical_operators.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_scopes.md
Working through all of the About_ topics for fix formatting for future processing with Pandoc. This PR is only for v4 topics. There will be separate PRs for each version.
> Reformatting v4 About_ topics missed in first pass

- reference/3.0/Microsoft.PowerShell.Core/About/about_Debuggers.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_PSSessions.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_PSSnapins.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Remote.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Variables.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Return.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Session_Configuration_Files.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Signing.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Splatting.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Transactions.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_WMI.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_WQL.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_ISE.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Windows_RT.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_logical_operators.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_scopes.md
Working through all of the About_ topics for fix formatting for future processing with Pandoc. This PR is only for v3 topics. There will be separate PRs for each version.
> Reformatting v3 About_ topics missed in first pass

- appveyor.ps1
> Creates output directory as pandoc needs it

- reference/6/Microsoft.PowerShell.Management/Set-Content.md
This should not be merged until https://github.com/PowerShell/PowerShell/pull/5827 is merged
> remove alias `sc` to match PSCore6

- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
I just made it through the CHANGELOG, still rife with TODOs, but I wanted to get a general sense from @sdwheeler if this is the right level of abstraction that he was expecting. I'd still like to do a little more thematic, summary language on some of these groupings of copy/pasted changelog items (like in the web cmdlets, for instance), so don't review with *too* much of a fine tooth comb just yet. :)
> PowerShell Core 6.0 release notes

- reference/5.0/Microsoft.PowerShell.Management/Set-ItemProperty.md
- reference/5.1/Microsoft.PowerShell.Management/Set-ItemProperty.md
- reference/6/Microsoft.PowerShell.Management/Set-ItemProperty.md
> Fixed path inconsistencies in Set-ItemProperty Example 2

- reference/docs-conceptual/getting-started/fundamental/Windows-PowerShell-Basics.md
Added missing links as described in Issue #890
> add links for topics

- reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md
> About_Windows_PowerShell_5.1 #1171

- reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md
> Removed empty bullet point below notes.

- dsc/authoringResourceComposite.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/2082)
> Fix typo in code example

- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
> Fix typos in Invoke-WebRequest.md.

- reference/5.1/Microsoft.PowerShell.Security/Get-PfxCertificate.md
> Small typo in Get-PfxCertificate.md fixed

- reference/docs-conceptual/setup/Installing-Windows-PowerShell.md
There is no MacOS part in linux.md now.
> Modify incorrect link

- dsc/metaConfig.md
- dsc/metaConfig4.md
- dsc/pullServer.md
This PR includes a revision of the documentation for DSC pull service, and moves some text from the documentation for LCM to the pull service page.
> Update pull server documentation

- dsc/TOC.md
> fix toc title

- reference/docs-conceptual/setup/Installing-Windows-PowerShell.md
Add details of where to look for version information.
> Add details of where to look

- reference/6/Microsoft.PowerShell.Utility/Add-Member.md
> Update Add-Member.md - Fixed layout example 3

- reference/docs-conceptual/getting-started/fundamental/Windows-PowerShell-Integrated-Scripting-Environment--ISE-.md
> Typo in Windows-PowerShell-Integrated-Scripting-Environment--ISE-.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md
- reference/6/Microsoft.PowerShell.Core/About/about_pipelines.md
Fixed Issue #1434 
Fixed header levels and clarified regkey paths.
> Fixing issue 1434

- reference/3.0/Microsoft.PowerShell.Utility/New-Object.md
- reference/4.0/Microsoft.PowerShell.Utility/New-Object.md
> Added missing bullet

- reference/3.0/Microsoft.PowerShell.Utility/New-Object.md
- reference/4.0/Microsoft.PowerShell.Utility/New-Object.md
- reference/5.0/Microsoft.PowerShell.Utility/New-Object.md
- reference/5.1/Microsoft.PowerShell.Utility/New-Object.md
- reference/6/Microsoft.PowerShell.Utility/New-Object.md
> Fixed empty bullet

- reference/3.0/Microsoft.PowerShell.Management/Get-Content.md
- reference/3.0/Microsoft.PowerShell.Management/Remove-Item.md
- reference/3.0/Microsoft.PowerShell.Management/Test-Path.md
- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
Fixing 4 affected files
- 3.0\Microsoft.PowerShell.Management\Get-Content.md
- 3.0\Microsoft.PowerShell.Management\Remove-Item.md
- 3.0\Microsoft.PowerShell.Management\Test-Path.md
- 6\Microsoft.PowerShell.Utility\ConvertFrom-Json.md
> fix broken yaml blocks in content

- reference/docs-conceptual/setup/PS-remoting-second-hop.md
For copy and paste reasons (also it would now make a bit more sense)
> Missing y in Active Directory

- reference/6/Microsoft.PowerShell.Utility/Write-Host.md
- reference/6/Microsoft.PowerShell.Utility/Write-Information.md
This PR covers parameter adjustment in a new pull request https://github.com/PowerShell/PowerShell/pull/5816 that is not yet released.
resolves #2134
> #5816 add message and msg alias to Write-Information and Write-Host

- reference/5.1/Microsoft.PowerShell.Management/Get-WmiObject.md
> Fix Get-CimInstance link

- dsc/separatingEnvData.md
Corrected a lowercase letter typo in separatingEnvData.md
> Update separatingEnvData.md - fixed lowercase "NodeName"

- reference/5.1/Microsoft.PowerShell.Core/Out-Null.md
> Updated description

- reference/6/PackageManagement/Install-PackageProvider.md
> Incorrect Whitespace

- reference/docs-conceptual/core-powershell/ise/How-to-Create-a-PowerShell-Tab-in-Windows-PowerShell-ISE.md
- reference/docs-conceptual/core-powershell/ise/How-to-Use-Profiles-in-Windows-PowerShell-ISE.md
- reference/docs-conceptual/core-powershell/ise/How-to-Use-Tab-Completion-in-the-Script-Pane-and-Console-Pane.md
- reference/docs-conceptual/core-powershell/ise/How-to-Use-the-Console-Pane-in-the-Windows-PowerShell-ISE.md
- reference/docs-conceptual/core-powershell/ise/The-ISE-Object-Model-Hierarchy.md
- reference/docs-conceptual/core-powershell/ise/The-ISEAddOnTool-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISEAddOnToolCollection-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISEEditor-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISEFile-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISEFileCollection-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISEMenuItem-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISEMenuItemCollection-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISEOptions-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISESnippetCollection-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ObjectModelRoot-Object.md
- reference/docs-conceptual/core-powershell/ise/The-PowerShellTab-Object.md
- reference/docs-conceptual/core-powershell/ise/The-PowerShellTabCollection-Object.md
- reference/docs-conceptual/getting-started/cookbooks/Other-Useful-Scripting-Objects.md
- reference/docs-conceptual/getting-started/fundamental/Exploring-the-Windows-PowerShell-ISE.md
- reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md
Fixing broken links based on build notifications.  Cleaned up various other items at the same time (lint, powershell tags, broken code, code normalization, etc.).
> Fixing links and various changes

- gallery/psget/get_psget_module.md
Add "```" at the end to close the last fenced code block.
> Close fenced code block

- dsc/docfx.json
- reference/docs-conceptual/core-powershell/ise/How-to-Debug-Scripts-in-Windows-PowerShell-ISE.md
- reference/docs-conceptual/core-powershell/ise/How-to-Use-Profiles-in-Windows-PowerShell-ISE.md
- reference/docs-conceptual/core-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md
- reference/docs-conceptual/core-powershell/ise/Introducing-the-Windows-PowerShell-ISE.md
- reference/docs-conceptual/core-powershell/ise/Keyboard-Shortcuts-for-the-Windows-PowerShell-ISE.md
- reference/docs-conceptual/core-powershell/ise/Purpose-of-the-Windows-PowerShell-ISE-Scripting-Object-Model.md
- reference/docs-conceptual/core-powershell/ise/The-ISEFile-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISEMenuItem-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISEMenuItemCollection-Object.md
- reference/docs-conceptual/core-powershell/ise/The-ISESnippetObject.md
* Update to DSC docs owner
* Markdown and lint cleanup to ISE folder
> Cleanup in ISE folder

- wmf/5.0/feedback_moduleversionranges.md
Hello, @JKeithB,
Localization team has reported source content issue that causes localized version to have broken format compared to en-us version. We need to escape to fix italic format.
Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
> C14191: Asterisk issue

- README.md
Fixing broken link to the style guide.
> Fixing style guide link

- reference/6/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
> Add newlines

- wmf/5.0/requirements.md
- wmf/5.0/sil_overview.md
- wmf/5.0/uninstall.md
- wmf/5.1/DSC-improvements.md
- wmf/5.1/Index.md
- wmf/5.1/bugfixes.md
- wmf/5.1/catalog-cmdlets.md
- wmf/5.1/community-resources.md
- wmf/5.1/compatibility.md
- wmf/5.1/console-improvements.md
- wmf/5.1/engine-improvements.md
- wmf/5.1/install-configure.md
- wmf/5.1/jea-improvements.md
- wmf/5.1/known-issues-cache/NetworkingSwitchCmdletInput.md
- wmf/5.1/known-issues-cache/template.md
- wmf/5.1/known-issues.md
- wmf/5.1/package-management-improvements.md
- wmf/5.1/productincompat.md
- wmf/5.1/release-notes.md
- wmf/5.1/scenarios-features.md
- wmf/README.md
- Changing ms.date to match format expectations
- Removing trailing spaces on lines
- Removing trailing blank lines at end of file
> Date and spaces updates [F11]

- reference/6/Microsoft.PowerShell.Utility/Set-Variable.md
> Add link on about_Scopes to about_Scopes.md on v6.0  #2309

- reference/5.0/Microsoft.PowerShell.Utility/Set-Variable.md
> Add link on about_Scopes to about_Scopes.md on v5.0  #2309

- reference/4.0/Microsoft.PowerShell.Utility/Set-Variable.md
> Add link on about_Scopes to about_Scopes.md on v4.0  #2309

- reference/3.0/Microsoft.PowerShell.Utility/Set-Variable.md
> Add link on about_Scopes to about_Scopes.md on v3.0  #2309

- reference/5.1/PowershellGet/Install-Script.md
Live link: https://docs.microsoft.com/en-us/powershell/module/powershellget/Install-Script
> Install-Script.md: fixed line break in script samples

- dsc/pullClient.md
- dsc/pullClientConfigID.md
- dsc/pullClientConfigNames.md
- dsc/pullServer.md
- dsc/pullServerSMB.md
- dsc/reportServer.md
- dsc/secureServer.md
changes terms from deprecated to no new features or capabilities
> Mgreenegit pullserver

- reference/3.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/4.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/5.0/Microsoft.PowerShell.Utility/Format-Table.md
- reference/5.1/Microsoft.PowerShell.Utility/Format-Table.md
- reference/6/Microsoft.PowerShell.Utility/Format-Table.md
* Added `-MemberType Properties` to filter only properties
* Fixed some minor wording and formatting
> Update Example 4 in Format-Table.md

- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
> Fix markdown formatting.

- dsc/pullServer.md
- Adding links for DSCPM Protocol and Errata
> Adding DSCPM Protocol links

- reference/5.0/Microsoft.PowerShell.Utility/convertfrom-sddlstring.md
- reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-SddlString.md
- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-SddlString.md
>  Add help for ConvertFrom-SDDLString.

- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
Hello, @sethvs,
This proposed file change comes from this Community Contribution:  https://github.com/PowerShell/powerShell-Docs.ru-ru/pull/13/files
Please, help to check this proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
> CC55771: Fix links

- wmf/5.1/scenarios-features.md
> Fix links, spaces, and formatting in scenarios-features.md.

- reference/6/CimCmdlets/Get-CimSession.md
> Fix links and formatting in Get-CimSession.md.

- reference/6/CimCmdlets/New-CimSession.md
> Fix links, formatting, and typos in New-CimSession.md.

- reference/6/CimCmdlets/Remove-CimSession.md
> Fix links and formatting in Remove-CimSession.md.

- reference/5.1/Microsoft.PowerShell.Core/Get-Module.md
- reference/6/Microsoft.PowerShell.Core/Get-Module.md
> Add -PSEdition parameters description in Get-Module.md.

- reference/3.0/Microsoft.PowerShell.Core/Get-Module.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Module.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Module.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Module.md
- reference/6/Microsoft.PowerShell.Core/Get-Module.md
> Fix formatting in Get-Module.md.

- reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
- reference/6/Microsoft.PowerShell.Utility/Export-Csv.md
> Add -Force parameter description with examples and fix formatting in Export-Csv.md.

- reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md
Specified that the cmdlet creates a new domain computer account instead of the slightly vague computer account
> Clarification on domain account creation

- reference/6/CimCmdlets/Get-CimSession.md
- reference/6/CimCmdlets/New-CimSession.md
- reference/6/CimCmdlets/Remove-CimSession.md
> Add links to about_CimSession.md, fix parameter descriptions, and fix formatting.

- reference/3.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/6/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
> Add missing ">" in about_Language_Keywords.md

- reference/docs-conceptual/toc.yml
- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
- reference/docs-conceptual/whats-new/breaking-changes-ps6.md
- reference/docs-conceptual/whats-new/known-issues-ps6.md
Migrating docs per issue #2441
> migrating docs from src repo

- reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md
> Clarify the use of PasswordPass option

- reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md
Fixed link cited in https://github.com/PowerShell/PowerShell-Docs/issues/2439 
> Fixed link to PSremoting over SSH

- reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md
> Add semantic line break.

- reference/5.0/Microsoft.PowerShell.Management/Clear-RecycleBin.md
- reference/5.1/Microsoft.PowerShell.Management/Clear-RecycleBin.md
Added examples and expanded parameter documentation.
> Updated docs for Clear-RecycleBin

- reference/3.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/6/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
> Edited about_Group_Policy_Settings.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/6/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
Reverts PowerShell/PowerShell-Docs#2451
Should not have been merged to master, but should be going to staging.
> Revert "Edited about_Group_Policy_Settings.md"

- reference/3.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
- reference/6/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
Fixing PR that was merged to the wrong branch.
> re-adding files from PR#2451

- reference/3.0/Microsoft.PowerShell.Utility/Write-Debug.md
- reference/3.0/Microsoft.PowerShell.Utility/Write-Error.md
- reference/3.0/Microsoft.PowerShell.Utility/Write-Host.md
- reference/3.0/Microsoft.PowerShell.Utility/Write-Output.md
- reference/3.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/3.0/Microsoft.PowerShell.Utility/Write-Verbose.md
- reference/3.0/Microsoft.PowerShell.Utility/Write-Warning.md
- reference/3.0/Microsoft.WsMan.Management/About/about_WS-Management_Cmdlets.md
- reference/3.0/Microsoft.WsMan.Management/Connect-WSMan.md
- reference/3.0/Microsoft.WsMan.Management/Disable-WSManCredSSP.md
- reference/3.0/Microsoft.WsMan.Management/Disconnect-WSMan.md
- reference/3.0/Microsoft.WsMan.Management/Enable-WSManCredSSP.md
- reference/3.0/Microsoft.WsMan.Management/Get-WSManCredSSP.md
- reference/3.0/Microsoft.WsMan.Management/Get-WSManInstance.md
- reference/3.0/Microsoft.WsMan.Management/Invoke-WSManAction.md
- reference/3.0/Microsoft.WsMan.Management/Microsoft.WsMan.Management.md
- reference/3.0/Microsoft.WsMan.Management/New-WSManInstance.md
- reference/3.0/Microsoft.WsMan.Management/New-WSManSessionOption.md
- reference/3.0/Microsoft.WsMan.Management/Remove-WSManInstance.md
- reference/3.0/Microsoft.WsMan.Management/Set-WSManInstance.md
- reference/3.0/Microsoft.WsMan.Management/Set-WSManQuickConfig.md
- reference/3.0/Microsoft.WsMan.Management/Test-WSMan.md
- reference/3.0/Microsoft.WsMan.Management/provider/new-item-for-clientcertificate.md
- reference/3.0/Microsoft.WsMan.Management/provider/new-item-for-initializationparameters.md
- reference/3.0/Microsoft.WsMan.Management/provider/new-item-for-listener.md
> Release bobbytreed b005

- developer/prog-guide/getproc05-vb-net-sample-code.md
- developer/prog-guide/runspace01-vb-net-code-sample.md
- developer/prog-guide/runspace02-vb-net-code-sample.md
- developer/prog-guide/runspace03-vb-net-code-sample.md
- developer/prog-guide/runspace04-vb-net-code-sample.md
- developer/prog-guide/stopprocesssample04-vb-net-sample-code.md
- developer/provider/accessdbprovidersample03.md
- developer/provider/accessdbprovidersample04.md
- developer/provider/accessdbprovidersample06.md
> Removing references to VB code links to resolve build errors.

- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
> Change 'powershell' to 'pwsh' in MacOS example.

- reference/5.1/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/6/Microsoft.PowerShell.Management/Get-PSDrive.md
Parameter name "Provider" should be "PSProvider"
> fix parameter name on example 3

- reference/6/Microsoft.PowerShell.Management/Join-Path.md
> insert missing backslash

- reference/6/Microsoft.PowerShell.Management/Set-Location.md
> Update Set-Location to behavior change in 6.0

- reference/3.0/Microsoft.PowerShell.Management/Remove-Item.md
- reference/4.0/Microsoft.PowerShell.Management/Remove-Item.md
- reference/5.0/Microsoft.PowerShell.Management/Remove-Item.md
- reference/5.1/Microsoft.PowerShell.Management/Remove-Item.md
- reference/6/Microsoft.PowerShell.Management/Remove-Item.md
> Add example for literalpath to Remove-Item

- reference/3.0/Microsoft.PowerShell.Management/Get-HotFix.md
- reference/4.0/Microsoft.PowerShell.Management/Get-HotFix.md
- reference/5.0/Microsoft.PowerShell.Management/Get-HotFix.md
- reference/5.1/Microsoft.PowerShell.Management/Get-HotFix.md
> fixed Issue #2131

- reference/3.0/Microsoft.PowerShell.Management/Get-PSProvider.md
- reference/4.0/Microsoft.PowerShell.Management/Get-PSProvider.md
- reference/5.0/Microsoft.PowerShell.Management/Get-PSProvider.md
- reference/5.1/Microsoft.PowerShell.Management/Get-PSProvider.md
- reference/6/Microsoft.PowerShell.Management/Get-PSProvider.md
Fixed input information and wildcard support.
> fixing bug 380430

- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
* Fixed some wording and formatting
* Removed a similar sentence in DESCRIPTION
> Update Example 2 in Get-Help.md

- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
The effects of the **Detailed** and **Full** parameter are similar but slightly different. It will be more understandable by explaining the effects in one section, 
> Join Detailed and Full parameter examples in Get-Help.md

- CONTRIBUTING.md
- README.md
- contributing/1-GET-STARTED.md
- contributing/2-WRITING.md
- contributing/3-STYLE-GUIDE.md
- contributing/4-MARKDOWN-SPECIFICS.md
- contributing/5-FORMATTING-CODE.md
- contributing/6-UPDATING-REFERENCE.md
Updated contributor guide
Issue #1106 fix styleguide to reflect platyps schema
- Add note about not splitting code samples with paragraphs in examples section
- Also not code blocks in any other sections
Issue #15 Style guide
- Update new CommonMark requirements
- Link to Microsoft Style Guide
Update Readme.md
- Doc the structure of the repo
> update to contributor guide

- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
* Fixed some wording and formatting
* Removed a similar sentence in NOTES
> Update Example 1 in Get-Help.md

- developer/format/expressionbinding-element-for-customitem-for-customcontrol-for-view-format.md
- developer/format/expressionbinding-element-for-customitem-for-groupby-format.md
- developer/format/firstlinehanging-element-for-frame-for-controls-for-configuration-format.md
- developer/format/firstlinehanging-element-for-frame-for-controls-for-view-format.md
- developer/format/firstlinehanging-element-for-frame-for-customcontrol-for-view-format.md
- developer/format/firstlinehanging-element-for-frame-for-groupby-format.md
- developer/format/firstlineindent-element-for-frame-for-controls-for-configuration-format.md
- developer/format/firstlineindent-element-for-frame-for-controls-for-view-format.md
- developer/format/firstlineindent-element-for-frame-for-customcontrol-for-view-format.md
- developer/format/firstlineindent-element-for-frame-for-groupby-format.md
- developer/format/format-schema-xml-reference.md
- developer/format/formatstring-element-for-listitem-for-listcontrol-format.md
- developer/format/formatstring-element-for-tablecolumnitem-for-tablecontrol-format.md
- developer/format/formatstring-element-for-wideitem-for-widecontrol-format.md
- developer/format/formatting-displayed-data.md
- developer/format/formatting-file-concepts.md
- developer/format/formatting-file-overview.md
- developer/format/frame-element-for-customitem-for-controls-for-configuration-format.md
- developer/format/frame-element-for-customitem-for-controls-for-view-format.md
- developer/format/frame-element-for-customitem-for-customcontrol-for-view-format.md
- developer/format/frame-element-for-customitem-for-groupby-format.md
- developer/format/groupby-element-for-view-format.md
- developer/format/hidetableheaders-element-format.md
- developer/format/how-to-create-a-formatting-file-format-ps1xml.md
- developer/format/itemselectioncondition-element-for-expressionbinding-for-controls-for-configuration-format.md
> Release sdk b009

- developer/format/customitem-element-for-customentry-for-customcontrol-for-view-format.md
- developer/format/customitem-element-for-customentry-for-groupby-format.md
- developer/format/defaultsettings-element-format.md
- developer/format/defining-common-configuration-features.md
- developer/format/defining-conditions-for-displaying-data.md
- developer/format/defining-selection-sets.md
- developer/format/displayerror-element-format.md
- developer/format/entryselectedby-element-for-customentry-for-controls-for-configuration-format.md
- developer/format/entryselectedby-element-for-customentry-for-controls-for-view-format.md
- developer/format/entryselectedby-element-for-customentry-for-customcontrol-for-view-format.md
- developer/format/entryselectedby-element-for-customentry-for-groupby-format.md
- developer/format/entryselectedby-element-for-enumerableexpansion-format.md
- developer/format/entryselectedby-element-for-listentry-for-listcontrol-format.md
- developer/format/entryselectedby-element-for-tablerowentry-for-tablecontrol-format.md
- developer/format/entryselectedby-element-for-wideentry-format.md
- developer/format/enumerableexpansion-element-format.md
- developer/format/enumerableexpansions-element-format.md
- developer/format/enumeratecollection-element-for-expressionbinding-for-controls-for-configuration-format.md
- developer/format/enumeratecollection-element-for-expressionbinding-for-controls-for-view-format.md
- developer/format/enumeratecollection-element-for-expressionbinding-for-customcontrol-for-view-format.md
- developer/format/enumeratecollection-element-for-expressionbinding-for-groupby-format.md
- developer/format/examples-of-formatting-files.md
- developer/format/expand-element-format.md
- developer/format/expressionbinding-element-for-customitem-for-controls-for-configuration-format.md
- developer/format/expressionbinding-element-for-customitem-for-controls-for-view-format.md
> Release sdk b008

- developer/help/comment-based-help-keywords.md
- developer/help/examples-of-comment-based-help.md
- developer/help/how-to-add-a-cmdlet-description.md
- developer/help/how-to-add-a-provider-description.md
- developer/help/how-to-add-a-see-also-section-to-a-provider-help-topic.md
- developer/help/how-to-add-capabilities.md
- developer/help/how-to-add-dynamic-parameters-to-a-provider-help-topic.md
- developer/help/how-to-add-examples-to-a-cmdlet-help-topic.md
- developer/help/how-to-add-input-types-to-a-cmdlet-help-topic.md
- developer/help/how-to-add-notes-to-a-cmdlet-help-topic.md
- developer/help/how-to-add-notes-to-a-provider-help-topic.md
- developer/help/how-to-add-parameter-information.md
- developer/help/how-to-add-related-links-to-a-cmdlet-help-topic.md
- developer/help/how-to-add-return-values-to-a-cmdlet-help-topic.md
- developer/help/how-to-add-syntax-to-a-cmdlet-help-topic.md
> Release sdk b014

- reference/3.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Update-Help.md
- reference/6/Microsoft.PowerShell.Core/Update-Help.md
* Fixed some wording and formatting
* Removed sentences about ISE (only v6)
> Update DESCRIPTION in Update-Help.md

- developer/prog-guide/runspace05-code-sample.md
- developer/prog-guide/runspace06-code-sample.md
- developer/prog-guide/runspace07-code-sample.md
- developer/prog-guide/runspace08-code-sample.md
- developer/prog-guide/runspace09-code-sample.md
- developer/prog-guide/runspace10-code-sample.md
- developer/prog-guide/stopproc01-code-samples.md
- developer/prog-guide/stopproc01-csharp-sample-code.md
> Batch automation: Formatting fixes

- reference/3.0/Microsoft.PowerShell.Core/About/about_scopes.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_scopes.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_scopes.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md
> Fix about_Scopes.md.

- reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
- reference/6/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
> Fix some minor issues in about_Comment_Based_Help.md

- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Windows.md
> Fix install path for PS6

- dsc/bread/toc.yml
- gallery/bread/toc.yml
- gallery/docfx.json
- jea/bread/toc.yml
- reference/bread-pscore/toc.yml
- reference/docfx.json
Breadcrumb configuration is broken for all docsets.
> fixing breadcrumb issues

- reference/docs-conceptual/core-powershell/web-access/authorization-rules-and-security-features-of-windows-powershell-web-access.md
- reference/docs-conceptual/core-powershell/web-access/cmdlets/add-pswaauthorizationrule.md
- reference/docs-conceptual/core-powershell/web-access/install-and-use-windows-powershell-web-access.md
- reference/docs-conceptual/setup/Installing-Windows-PowerShell.md
- reference/docs-conceptual/setup/Installing-the-Windows-PowerShell-SDK.md
- wmf/5.0/dsc_statestatus.md
- wmf/5.0/feedback_convertfromString.md
- wmf/5.0/limitation_overview.md
- wmf/5.0/oneget_cmdlets.md
- wmf/5.1/console-improvements.md
- wmf/5.1/engine-improvements.md
- wmf/5.1/jea-improvements.md
- wmf/5.1/known-issues-cache/NetworkingSwitchCmdletInput.md
- wmf/5.1/known-issues.md
> Fixing files flaged by markdig migration

- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
The example of paging is needed because it is one of the most often used feature for help system.
> Add an example of paging to Get-Help.md

- dsc/bootstrapDsc.md
- dsc/groupSetResource.md
- dsc/lnxFileLineResource.md
- dsc/msft-dsclocalconfigurationmanager-disabledebugconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-enabledebugconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-getconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-getconfigurationresultoutput.md
- dsc/msft-dsclocalconfigurationmanager-getconfigurationstatus.md
- dsc/msft-dsclocalconfigurationmanager-sendconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-sendconfigurationapply.md
- dsc/msft-dsclocalconfigurationmanager-sendconfigurationapplyasync.md
- dsc/msft-dsclocalconfigurationmanager-sendmetaconfigurationapply.md
- dsc/msft-dsclocalconfigurationmanager-stopconfiguration.md
- dsc/msft-dsclocalconfigurationmanager-testconfiguration.md
- dsc/msft-dsclocalconfigurationmanager.md
- dsc/runAsUser.md
> Fixing files flagged by markdig migration

- reference/docfx.json
Fix breadcrumb for reference docset.
> Update breadcrumb path

- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
* Added an example command
* Fixed formatting and wording
> Update Example 3 in Get-Help.md

- reference/5.1/PowershellGet/New-ScriptFileInfo.md
- reference/6/PowerShellGet/New-ScriptFileInfo.md
- wmf/5.0/psget_scriptcmdlets.md
> Fixes #2542 Updated #Requires statements to use -Modules instead of -Module

- dsc/DscForEngineers.md
Alice and Bob were swapped in the DSC example.
- [?] Impacts 6.1 document
- [?] Impacts 6.0 document
- [?] Impacts 5.1 document
> Align DSC example to match non-DSC logic

- dsc/DscForEngineers.md
> Fix page title

- reference/3.0/Microsoft.PowerShell.Core/Enter-PSSession.md
- reference/5.0/Microsoft.PowerShell.Core/Enter-PSSession.md
- reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md
- reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md
> ComputerName parameter not fully spelled out

- reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md
- reference/6/Microsoft.PowerShell.Core/About/about_Requires.md
> Add info on ShellId variable and escape <> symbols in about_Requires.md.

- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
> Update Example 9 in Get-Help.md

- .openpublishing.redirection.json
- wmf/README.md
- wmf/TOC.yml
- wmf/docfx.json
- wmf/overview.md
> rename and replace README

- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
Moved up basic examples (Example 3, 4, 6, 7, 9 -> 1, 2, 3, 4, 5)
> Update order of examples in Get-Help.md

- reference/README.md
> Fix a header

- reference/docs-conceptual/toc.yml
Add "Installing" to "PowerShell Core on ARM".
> Renaming entry in toc.yml

- reference/3.0/Microsoft.PowerShell.Core/Get-Command.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Command.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Command.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Command.md
- reference/6/Microsoft.PowerShell.Core/Get-Command.md
> Fix parameter's position in Get-Command.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Split.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Split.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Split.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Split.md
- reference/6/Microsoft.PowerShell.Core/About/about_Split.md
> Closes #1631 - fix descriptions of singleline and multiline

- reference/3.0/Microsoft.PowerShell.Utility/Select-Object.md
- reference/4.0/Microsoft.PowerShell.Utility/Select-Object.md
- reference/5.0/Microsoft.PowerShell.Utility/Select-Object.md
- reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md
- reference/6/Microsoft.PowerShell.Utility/Select-Object.md
> Closes #2130 - Improve ExpandProperty Documentation

- reference/3.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_profiles.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md
- reference/6/Microsoft.PowerShell.Core/About/about_Profiles.md
> Fix remote profile example in about_Profiles.md.

- dsc/azureDscexthistory.md
Update DSC VM Extension 2.76 for all Azure clouds
> Update DSC VM Extension 2.76 for all Azure clouds

- reference/3.0/Microsoft.PowerShell.Management/Set-ItemProperty.md
- reference/4.0/Microsoft.PowerShell.Management/Set-ItemProperty.md
- reference/5.0/Microsoft.PowerShell.Management/Set-ItemProperty.md
- reference/5.1/Microsoft.PowerShell.Management/Set-ItemProperty.md
- reference/6/Microsoft.PowerShell.Management/Set-ItemProperty.md
* Fixed `final.doc | Get-Member` that throws exception
* Fixed wording and formatting
> Update Example 1 in Set-ItemProperty.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
> Changed list of parameter set names to an array

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Parameters.md
- reference/6/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
> Closes #2338 - Adds documentation for delay-bind script block parameters

- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
Hello, @sdwheeler ,
This proposed file change comes from https://github.com/PowerShell/powerShell-Docs.de-de/pull/5.
Could you review this contribution and help to merge if agreed?
> CC60283: Solution for Subsystem Bug in OpenSSH

- wmf/5.1/scenarios-features.md
> fixing links to close issue #544

- reference/5.1/PowershellGet/Install-Module.md
- reference/6/PowerShellGet/Install-Module.md
> describe -AllowClobber to fix issue #1045

- reference/3.0/PSWorkflowUtility/Invoke-AsWorkflow.md
- reference/4.0/PSWorkflowUtility/Invoke-AsWorkflow.md
- reference/5.0/PSWorkflowUtility/Invoke-AsWorkflow.md
- reference/5.1/PSWorkflowUtility/Invoke-AsWorkflow.md
> Closes #1020 - Adds workflow common parameters to Invoke-Workflow

- reference/3.0/Microsoft.PowerShell.Management/New-ItemProperty.md
- reference/4.0/Microsoft.PowerShell.Management/New-ItemProperty.md
- reference/5.0/Microsoft.PowerShell.Management/New-ItemProperty.md
- reference/5.1/Microsoft.PowerShell.Management/New-ItemProperty.md
- reference/6/Microsoft.PowerShell.Management/New-ItemProperty.md
> Closes #1464 - add examples to New-ItemProperty

- reference/3.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/4.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/5.0/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md
- reference/6/Microsoft.PowerShell.Utility/Compare-Object.md
> Closes #1461 - Updates Compare-Object OUTPUT

- reference/3.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/6/Microsoft.PowerShell.Core/About/about_Providers.md
> Closes #2138 - Document ~ Home provider location

- dsc/bootstrapDsc.md
Fixed typo in PowerShell Command
> Fixed typo in bootstrapDsc.md

- reference/6/Microsoft.PowerShell.Utility/Measure-Object.md
Reverts PowerShell/PowerShell-Docs#2640
> Revert "Modification for Measure-Object help file for -AllStats switch."

- gallery/how-to/managing-profile/creating-APIkeys.md
- gallery/how-to/working-with-items/manual-download.md
Formatting changes only, no content change
> Applying style guide updates to new content

- developer/module/how-to-write-a-powershell-module-manifest.md
Some paragraphs were obvious copies of the ones immediately preceding them; I've removed those.
> Removed duplicate paragraphs

- developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
* Wait-PSJob -> Wait-Job
* VerbsOther link
* CamelCase, line breaks, formatting
> Fix minor issues in Approved Verbs doc

- developer/cmdlet/required-development-guidelines.md
Fixed links internal to developer/cmdlet/required-development-guidelines.html
> Fix some links

- reference/docs-conceptual/PowerShell-Scripting.md
* Capitalization, line breaks, formatting
> Fix minor issues in PowerShell Scripting doc

- developer/cmdlet/adding-aliases-wildcard-expansion-and-help-to-cmdlet-parameters.md
- developer/cmdlet/adding-non-terminating-error-reporting-to-your-cmdlet.md
- developer/cmdlet/adding-parameter-sets-to-a-cmdlet.md
- developer/cmdlet/adding-parameters-that-process-command-line-input.md
- developer/cmdlet/adding-parameters-that-process-pipeline-input.md
- developer/cmdlet/adding-user-messages-to-your-cmdlet.md
These duplicates might be due to failure of auto-conversion of msdn links.
> Remove duplicate sentences in developer\cmdlet\adding-*.md

- reference/docs-conceptual/PowerShell-Core-Support.md
Clarify which version of PowerShell Core supports which platform.
Also, add details about EOL policy and when platforms where EOL'ed
The language about EOL  was taken from here: https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md
> Clarify which version of PowerShell Core supports which platform.

- developer/prog-guide/windows-powershell-concepts.md
- developer/prog-guide/windows-powershell-programmer-s-guide.md
These duplicates might be due to failure of auto-conversion from MSDN to Microsoft Docs.
> Remove duplicate sentences in developer\prog-guide\windows-powershell-*.md

- dsc/configurations.md
- dsc/lnxGroupResource.md
- dsc/lnxServiceResource.md
- dsc/logResource.md
- dsc/packageResource.md
- dsc/partialConfigs.md
- dsc/processSetResource.md
- dsc/registryResource.md
- dsc/troubleshooting.md
- dsc/windowsProcessResource.md
- gallery/concepts/item-manifest-affecting-ui.md
- gallery/concepts/module-prerelease-support.md
- gallery/concepts/module-psedition-support.md
- gallery/concepts/script-prerelease-support.md
- gallery/concepts/script-psedition-support.md
- gallery/how-to/getting-support/bootstrapping-nuget.md
- gallery/how-to/getting-support/contacting-administrators.md
- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
- reference/docs-conceptual/core-powershell/vscode/using-vscode.md
- reference/docs-conceptual/core-powershell/web-access/authorization-rules-and-security-features-of-windows-powershell-web-access.md
- reference/docs-conceptual/core-powershell/web-access/cmdlets/add-pswaauthorizationrule.md
- reference/docs-conceptual/core-powershell/web-access/install-and-use-windows-powershell-web-access.md
- reference/docs-conceptual/getting-started/cookbooks/Managing-Services.md
- reference/docs-conceptual/getting-started/cookbooks/Other-Useful-Scripting-Objects.md
- wmf/5.0/dsc_statestatus.md
- wmf/5.0/jea_endpoint.md
- wmf/5.0/jea_report.md
- wmf/5.0/requirements.md
- wmf/5.1/jea-improvements.md
Fixes to support markdig conversion.
> markdig updates

- reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
Change the single quotes around \`n to the double quotes.
> Fix single quotes

- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
> update registration of MSFT repo using .deb pkg

- reference/3.0/Microsoft.PowerShell.Core/Get-Module.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Module.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Module.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Module.md
> Fixes examples for Get-Module

- reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
> Fixes #2675 - Missed ref/5.0 change

- dsc/PackageManagementDscResource.md
- dsc/lnxServiceResource.md
- dsc/logResource.md
- dsc/packageResource.md
- dsc/partialConfigs.md
- dsc/processSetResource.md
- dsc/registryResource.md
- dsc/troubleshooting.md
- dsc/windowsProcessResource.md
- gallery/concepts/item-manifest-affecting-ui.md
- gallery/concepts/module-prerelease-support.md
- gallery/concepts/module-psedition-support.md
- gallery/concepts/script-prerelease-support.md
- gallery/concepts/script-psedition-support.md
- gallery/how-to/getting-support/bootstrapping-nuget.md
- gallery/how-to/getting-support/contacting-administrators.md
- wmf/5.0/dsc_statestatus.md
- wmf/5.0/jea_endpoint.md
- wmf/5.0/jea_report.md
- wmf/5.0/requirements.md
- wmf/5.1/jea-improvements.md
markdig formatting fixes - part 1
> markdig formatting fixes - part 1

- developer/module/how-to-write-a-powershell-module-manifest.md
Fixed list levels from 2 to 6.
> Fix numbered lists in Module Manifest doc

- developer/help/writing-help-for-windows-powershell-cmdlets.md
* Converted guideline lists to headers
* Fixed line breaks and formatting
* PowerShelll -> PowerShell
> Update Guidelines for Cmdlet Help

- reference/docs-conceptual/PowerShell-Core-Support.md
42.2 is EOL.  42.3 is the current version
> Update supported Version of OpenSUSE

- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
> ubuntu 18.04 fixed

- reference/3.0/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md
> Fix markdown formatting in Invoke-Expression.md.

- reference/3.0/Microsoft.PowerShell.Core/About/about_simplified_syntax.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_simplified_syntax.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_simplified_syntax.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_simplified_syntax.md
- reference/6/Microsoft.PowerShell.Core/About/about_simplified_syntax.md
> Fix markdown formatting in about_simplified_syntax.md.

- reference/3.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/4.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/5.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
- reference/6/Microsoft.PowerShell.Core/Import-Module.md
FIx #2691 
Discussion: powershell/powershell#5503
> Fix -Scope and -Global parameters description of Import-Module cmdlet.

- reference/3.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/4.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/5.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
- reference/6/Microsoft.PowerShell.Core/Import-Module.md
Update to documentation, considering discussion continuation.
PowerShell/PowerShell#5503
> Fix -Scope and -Global parameters description of Import-Module cmdlet. Part 2.

- reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs.md
- reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md
- reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs_Basics.md
- reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs_Troubleshooting.md
- reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs.md
- reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md
- reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs_Basics.md
- reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs_Troubleshooting.md
- reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs.md
- reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md
- reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Basics.md
- reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Troubleshooting.md
> Updates to formatting (markdown missing)

- reference/docs-conceptual/getting-started/cookbooks/Changing-Computer-State.md
> Wrong command is written for shut-down computer.

- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
> Fixing typo

- reference/3.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/4.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/5.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/6/Microsoft.PowerShell.Utility/Write-Progress.md
> Fix formatting issues in Write-Progress

- reference/3.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/4.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/5.0/Microsoft.PowerShell.Core/Import-Module.md
- reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
- reference/6/Microsoft.PowerShell.Core/Import-Module.md
> Fix -Scope and -Global parameters description of Import-Module cmdlet Part 3.

- gallery/concepts/script-psedition-support.md
Fix a header, typos, and an error message.
> Fix a header, typos, and an error message

- reference/docs-conceptual/PowerShell-Core-Support.md
- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
Update docs for Ubuntu 17.10 EOL and add 18.10 and Snap
fixes #2704
> Update docs for Ubuntu 17.10 EOL and add 18.10 and Snap

- contributing/3-STYLE-GUIDE.md
> Fix typos in 3-STYLE-GUIDE.md

- contributing/5-FORMATTING-CODE.md
> Fix typos in 5-FORMATTING-CODE.md

- developer/help/writing-help-for-windows-powershell-scripts-and-functions.md
* Line breaks, formatting
* Removed duplicates
* Fixed broken link
> Update Writing Help doc

- reference/3.0/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
- reference/6/Microsoft.PowerShell.Core/About/about_pwsh.md
Fixing rendering issue. See related PR #2760
> Fixing rendering issue. 

- reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md
Fix for #2766.
FollowSymlink parameter.
> Fix for #2766 Add FollowSymlink parameter

- reference/6/PackageManagement/Find-Package.md
- reference/6/PackageManagement/Find-PackageProvider.md
- reference/6/PackageManagement/Install-PackageProvider.md
It's a partial fix of #2747 - for the PackageManagement module only.
> Replace Windows PowerShell with PowerShell - the PackageManagement module

- reference/3.0/Microsoft.PowerShell.Core/Where-Object.md
- reference/4.0/Microsoft.PowerShell.Core/Where-Object.md
- reference/5.0/Microsoft.PowerShell.Core/Where-Object.md
- reference/5.1/Microsoft.PowerShell.Core/Where-Object.md
This is a continuation of PR #2751
> fixing broken code sample

- reference/6/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
- reference/6/Microsoft.PowerShell.Security/Get-Acl.md
- reference/6/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
- reference/6/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md
- reference/6/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md
- reference/6/Microsoft.PowerShell.Security/Providers/Certificate-Provider.md
- reference/6/Microsoft.PowerShell.Security/Providers/get-childitem-for-certificate.md
- reference/6/Microsoft.PowerShell.Security/Providers/move-item-for-certificate.md
- reference/6/Microsoft.PowerShell.Security/Providers/new-item-for-certificate.md
- reference/6/Microsoft.PowerShell.Security/Providers/remove-item-for-certificate.md
- reference/6/Microsoft.PowerShell.Security/Set-Acl.md
- reference/6/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
- reference/6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
It's a partial fix of #2747 - for the Microsoft.PowerShell.Security module only.
> Replace Windows PowerShell with PowerShell - the Microsoft.PowerShell.Security module

- reference/3.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
- reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
> clarify the Clear() method to fix #2783

- reference/3.0/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
- reference/6/Microsoft.PowerShell.Core/About/about_Switch.md
> added better regex example to fix #2800

- reference/docs-conceptual/setup/Installing-PowerShell.md
- reference/docs-conceptual/toc.yml
> adding install landing page to fix #2706

- reference/docs-conceptual/PowerShell-Scripting.md
Raise Acrolinx score from 81 to 96
> Update overview article

- reference/docs-conceptual/core-powershell/Running-Remote-Commands.md
- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
- reference/docs-conceptual/core-powershell/console/PowerShell.exe-Command-Line-Help.md
- reference/docs-conceptual/core-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md
- reference/docs-conceptual/core-powershell/ise/Introducing-the-Windows-PowerShell-ISE.md
Using Acrolinx to edit articles with most visitors
> acrolinx edits

- reference/3.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
> Closes #2680 by rewriting regular expressions article

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/3.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/4.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/5.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/5.1/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions.md
- reference/6/Microsoft.PowerShell.Utility/Get-Verb.md
> Fix links for Approved Verbs

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
> Fix formatting: about_Functions_CmdletBindingAttribute.md

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
> Closes #2028 - Rewrite process block definition for clarity

- reference/3.0/Microsoft.PowerShell.Core/About/about_Signing.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Signing.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Signing.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
- reference/6/Microsoft.PowerShell.Core/About/about_Signing.md
Fixing broken links and redirects. See #2835
> Updating links to fix issue #2835

- reference/3.0/Microsoft.PowerShell.Utility/Set-Variable.md
- reference/4.0/Microsoft.PowerShell.Utility/Set-Variable.md
- reference/5.0/Microsoft.PowerShell.Utility/Set-Variable.md
- reference/5.1/Microsoft.PowerShell.Utility/Set-Variable.md
- reference/6/Microsoft.PowerShell.Utility/Set-Variable.md
> Fix incorrect description of Option value

- reference/3.0/Microsoft.PowerShell.Utility/New-Variable.md
- reference/3.0/Microsoft.PowerShell.Utility/Set-Alias.md
- reference/4.0/Microsoft.PowerShell.Utility/New-Variable.md
- reference/4.0/Microsoft.PowerShell.Utility/Set-Alias.md
- reference/5.0/Microsoft.PowerShell.Utility/New-Variable.md
- reference/5.0/Microsoft.PowerShell.Utility/Set-Alias.md
- reference/5.1/Microsoft.PowerShell.Utility/New-Variable.md
- reference/5.1/Microsoft.PowerShell.Utility/Set-Alias.md
- reference/6/Microsoft.PowerShell.Utility/New-Variable.md
- reference/6/Microsoft.PowerShell.Utility/Set-Alias.md
> Fixes #2849 - Remove double negative

- reference/6/Microsoft.PowerShell.Management/Set-Service.md
Document for https://github.com/PowerShell/PowerShell/pull/5525
> Add "-Force" to Set-Service for PowerShell/PowerShell#5525

- reference/6/Microsoft.PowerShell.Utility/Get-Date.md
> Fix not working link

- reference/3.0/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/4.0/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/5.0/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/6/Microsoft.PowerShell.Core/Invoke-Command.md
> Fix links in Invoke-Command.md

- reference/3.0/Microsoft.PowerShell.Core/Get-Command.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Command.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Command.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Command.md
- reference/6/Microsoft.PowerShell.Core/Get-Command.md
> Fix links in Get-Command.md

- reference/docs-conceptual/getting-started/fundamental/Getting-Information-About-Commands.md
- reference/docs-conceptual/getting-started/fundamental/Learning-PowerShell-Names.md
- reference/docs-conceptual/getting-started/fundamental/Understanding-Important-PowerShell-Concepts.md
- reference/docs-conceptual/getting-started/fundamental/Using-Familiar-Command-Names.md
- reference/docs-conceptual/getting-started/fundamental/Using-Variables-to-Store-Objects.md
Fixing exe references per our style discussion
> fixing for style changes

- contributing/3-STYLE-GUIDE.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Classes.md
Added information about interfaces. Did an acrolinx editorial pass.
> Updated about_Classes to fix issue #2872

- reference/3.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_scopes.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_scopes.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_scopes.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
- reference/6/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
- reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md
- reference/6/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
> Closes #2547 - Rerwrite mentions of & (call operator) for clarity.

- reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
> Credential param usage note

- reference/3.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/4.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/5.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
- reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
> Fix help topic on recipient of delivery notification

- reference/3.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/4.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/5.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/5.1/Microsoft.PowerShell.Core/Functions/Get-Verb.md
- reference/6/Microsoft.PowerShell.Utility/Get-Verb.md
> Update Get-Verb docs to fix #1480

- reference/3.0/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/3.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/4.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/5.0/Microsoft.PowerShell.Core/Get-Help.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/5.1/Microsoft.PowerShell.Core/Get-Help.md
- reference/6/Microsoft.PowerShell.Core/About/about_Scripts.md
- reference/6/Microsoft.PowerShell.Core/Get-Help.md
> Fix links for about_Comment_Based_Help

- gallery/how-to/managing-profile/creating-APIkeys.md
- gallery/how-to/managing-profile/managing-account.md
- gallery/how-to/publishing-items/creating-an-account.md
- gallery/how-to/working-with-items/manual-download.md
@JKeithB I edited these for style, grammar, and brevity. Please make sure I did not change the meaning of anything.
Acrolinx score old/new | filename
--- | ---
79 / 85 | how-to/managing-profile/creating-APIkeys.md
83 / 92 | how-to/managing-profile/managing-account.md
72 / 88 | how-to/publishing-items/creating-an-account.md
75 / 95 | how-to/working-with-items/manual-download.md
> editorial pass

- reference/5.1/PowershellGet/Install-Module.md
- reference/5.1/PowershellGet/Install-Script.md
> WIP: Modifying PSGet 5.1 docs, 6.0 changes will follow

- reference/6/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md
- reference/6/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
- reference/6/Microsoft.PowerShell.Core/About/about_pwsh.md
- reference/6/Microsoft.PowerShell.Core/Disconnect-PSSession.md
- reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md
- reference/6/Microsoft.PowerShell.Core/Invoke-Command.md
- reference/6/Microsoft.PowerShell.Core/New-PSSession.md
- reference/6/Microsoft.PowerShell.Core/Save-Help.md
- reference/6/Microsoft.PowerShell.Core/Update-Help.md
- reference/6/Microsoft.PowerShell.Core/Where-Object.md
- reference/6/Microsoft.PowerShell.Management/New-Service.md
- reference/6/Microsoft.PowerShell.Management/Set-Service.md
- reference/6/Microsoft.PowerShell.Management/Start-Process.md
- reference/6/Microsoft.PowerShell.Security/Get-PfxCertificate.md
- reference/6/Microsoft.PowerShell.Utility/Add-Type.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
- reference/6/Microsoft.PowerShell.Utility/Measure-Object.md
- reference/6/Microsoft.PowerShell.Utility/Set-TraceSource.md
- reference/6/Microsoft.PowerShell.Utility/Tee-Object.md
- reference/6/Microsoft.PowerShell.Utility/Trace-Command.md
- reference/6/Microsoft.WSMan.Management/Invoke-WSManAction.md
- reference/6/Microsoft.WSMan.Management/New-WSManInstance.md
- reference/6/Microsoft.WSMan.Management/Set-WSManInstance.md
- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Windows.md
- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md
- reference/docs-conceptual/setup/Installing-PowerShell.md
- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
Don't merge this yet, as we haven't made our release.
Still wanted to stage whether this will break things, that there's no merge conflicts, etc.
This rebased version of the branch has a much cleaner commit set below that won't mess up staging's history.
> [WIP] Merge PS 6.1 release branch (rebase) onto staging

- dsc/docfx.json
> Changing owner of DSC to Bobby Reed

- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md
> Corrected link to PowerShell RFC0025

- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md
Fix merge issues with macOS install instructions and other issues found during review
> Fix merge issues with macOS install instructions and other issues found during review

- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md
> include addition of app whitelisting support

- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md
> fix link issue is macOS install docs

- reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md
> Fix [wmi] and [wmiclass] examples in 'What's New in PowerShell Core 6.1'.

- reference/6/Microsoft.PowerShell.Utility/Write-Host.md
The description was the same as for example 4, modified it to fit the commands shown.
> Update description of example 5

- reference/docs-conceptual/getting-started/more-powershell-learning.md
> updating links to fix issue #2902

- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
Hello, @@joeyaiello and @sdwheeler,
Description: Paragraph "Authetication" is repeated 3 times
> C39918: Removing triplicated paragraph

- reference/3.0/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-Expression.md
* I added a new line or deleted a blank line.
* Changed file end line in 3.0
> Update example about Invoke-Expression

- reference/3.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/4.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/5.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Update-Help.md
- reference/6/Microsoft.PowerShell.Core/Update-Help.md
> Fix a typo in Update-Help.md.

- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
Fix links in 'SSH-Remoting-in-PowerShell-Core.md.'
>  Fix links in 'SSH-Remoting-in-PowerShell-Core.md.'

- reference/5.0/Microsoft.PowerShell.Core/Update-Help.md
- reference/5.1/Microsoft.PowerShell.Core/Update-Help.md
- reference/6/Microsoft.PowerShell.Core/Update-Help.md
> Fix Credential parameter description in Update-Help.md.

- developer/hosting/windows-powershell-host-quickstart.md
> Fix API casing and example code error in PS hosting docs

- reference/5.1/PowershellGet/Install-Module.md
- reference/6/PowerShellGet/Install-Module.md
> Update help of the Install-Module cmdlet

- reference/docs-conceptual/getting-started/fundamental/Getting-Detailed-Help-Information.md
Hello, @Saisang, @sdwheeler, @DCtheGeek ,
Description of the source issue: Plain asterisks must be escaped
> C42272: Asterisk issue at line 173

- reference/6/Microsoft.PowerShell.Utility/Get-Date.md
Sorry if I've filled this out wrong - but I've added an option to Get-Date -Uformat in the PS repo, and need to update the documentation to support that.
> Add Get-Date '%F' option

- reference/3.0/Microsoft.PowerShell.Management/Add-Content.md
- reference/4.0/Microsoft.PowerShell.Management/Add-Content.md
- reference/5.0/Microsoft.PowerShell.Management/Add-Content.md
- reference/5.1/Microsoft.PowerShell.Management/Add-Content.md
- reference/6/Microsoft.PowerShell.Management/Add-Content.md
> Added an example and updated the description for -Force parameter #2877

- reference/3.0/Microsoft.PowerShell.Utility/New-Variable.md
- reference/4.0/Microsoft.PowerShell.Utility/New-Variable.md
- reference/5.0/Microsoft.PowerShell.Utility/New-Variable.md
- reference/5.1/Microsoft.PowerShell.Utility/New-Variable.md
- reference/6/Microsoft.PowerShell.Utility/New-Variable.md
> Fixed formatting, added example, and expanded on scopes.

- reference/5.1/Microsoft.PowerShell.Management/Get-Location.md
> Correct spelling of subdirectory in Example 3

- reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
> Fixed typos & some minor grammar errors

- reference/6/PackageManagement/Import-PackageProvider.md
This PR provides only a small fix for a link in the document
> Fix link to oneget repo

- reference/3.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Providers.md
- reference/6/Microsoft.PowerShell.Core/About/about_Providers.md
> Add missing backslash

- reference/3.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/4.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/5.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
- reference/6/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
Fixing issue #2671 -Visible* parameters yaml.
- Updated `-VisibleAliases` parameter `Accept wildcard characters` from `False` to `True`
- Updated `-VisibleCmdlets` parameter `Accept wildcard characters` from `False` to `True`
- Updated `-VisibleFunctions` parameter `Accept wildcard characters` from `False` to `True`
- Updated `-VisibleProviders` parameter `Accept wildcard characters` from `False` to `True`
- Updated `-VisibleAliases` parameter `Accept wildcard characters` from `False` to `True`
- Updated `-VisibleCmdlets` parameter `Accept wildcard characters` from `False` to `True`
- Updated `-VisibleFunctions` parameter `Accept wildcard characters` from `False` to `True`
- Updated `-VisibleProviders` parameter `Accept wildcard characters` from `False` to `True`
- Updated …
> Fixed -Visible* parameters yaml

- reference/3.0/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/4.0/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/5.0/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/5.1/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/6/Microsoft.PowerShell.Management/New-PSDrive.md
> Fix formatting: DESCRIPTION in New-PSDrive.md (lists version)

- reference/docs-conceptual/getting-started/fundamental/Understanding-Important-PowerShell-Concepts.md
Added space to improve readability and allow screen readers to correctly read text aloud.
> Added space between words

- reference/4.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/5.0/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md
- reference/6/Microsoft.PowerShell.Utility/Write-Progress.md
> Fix Write-Progress example

- reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
- reference/6/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
> Fix levels of headings in about_Functions_OutputTypeAttribute.md

- reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
> correcting pwsh.exe path latest release (6.1.0)

- developer/module/how-to-write-a-powershell-script-module.md
> Remove duplicate bullet 7 Remove-Module

- reference/6/Microsoft.PowerShell.Utility/Write-Information.md
Updated the Docs needed for 'Write-Information accept objects from the pipeline' #3108
Tested the `Write-Information` with object passed from pipeline on PSCore6.1
- Updated `Accept Pipeline Value` on `-MessageData` yaml to `True`
- Added Example 4: Pass object to write information
- Added output for Example 4
```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Not updating …
> Updated Write-Information -MessageData yaml in PowerShell 6

- reference/5.0/PowershellGet/Publish-Module.md
- reference/5.1/PowershellGet/Publish-Module.md
- reference/6/PowerShellGet/Publish-Module.md
- [X ] Impacts 6.next document
- [ X] Impacts 6 document
- [ X] Impacts 5.1 document
- [ X] Impacts 5.0 document
- [X ] The documented feature was introduced in version 5.0 of PowerShell
> Fixing the -Path Parameter Description for Publish-Module

- reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
> Sbrandsborg patch 1

- reference/docs-conceptual/getting-started/fundamental/Understanding-the-PowerShell-Pipeline.md
> Remove unnecessary escape

- reference/6/Microsoft.PowerShell.Utility/Format-Table.md
> Remove unexpected character

- developer/module/how-to-write-a-powershell-script-module.md
Should be self-explanatory. :-)
> Fix misspelling of 'calendar'

- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md
> Minor - remove fullstop

- developer/help/how-to-create-the-cmdlet-help-file.md
> Fix MAML table

- gallery/concepts/item-manifest-affecting-ui.md
- gallery/concepts/module-license-acceptance.md
- gallery/concepts/module-prerelease-support.md
- gallery/concepts/publishing-guidelines.md
- gallery/concepts/script-prerelease-support.md
- gallery/concepts/scriptanalyzer-rule-profile.md
- gallery/faqs.md
- gallery/getting-started.md
- gallery/how-to/finding-items/filtering-items.md
- gallery/how-to/finding-items/search-syntax.md
- gallery/how-to/finding-items/searching-by-psedition.md
- gallery/how-to/getting-support/contacting-administrators.md
- gallery/how-to/getting-support/dispute-resolution.md
- gallery/how-to/getting-support/gdpr-dsr-policy.md
- gallery/how-to/getting-support/report-abuse.md
- gallery/how-to/managing-profile/managing-account.md
- gallery/how-to/publishing-items/creating-an-account.md
- gallery/how-to/publishing-items/deleting-items.md
- gallery/how-to/publishing-items/managing-item-owners.md
- gallery/how-to/publishing-items/unlisting-items.md
- gallery/how-to/working-with-items/contacting-item-owners.md
- gallery/how-to/working-with-items/deploy-to-azure-automation.md
- gallery/how-to/working-with-items/filelist-view.md
- gallery/how-to/working-with-items/social-media-feedback.md
- gallery/overview.md
This changes all the wording for "item" to "package" to reflect changes on powershellgallery.com
> Itemto package

- reference/docs-conceptual/toc.yml
> Fix title for a topic

- gallery/getting-started.md
Updated main heading "Get" > "Getting" to match link and URL
Pluralized "package" in the "Learning about..." sub heading to stay in line with other sub headings
Couple of other ease of reading updates
> Minor grammatical and ease of reading/continuity changes

- reference/docs-conceptual/getting-started/cookbooks/Managing-Current-Location.md
> typo: Double word "and"

- reference/5.1/PowershellGet/New-ScriptFileInfo.md
- reference/6/PowerShellGet/New-ScriptFileInfo.md
> typo: Double word "creates"

- reference/5.1/Microsoft.PowerShell.Utility/Remove-TypeData.md
- reference/6/Microsoft.PowerShell.Utility/Remove-TypeData.md
> typo: Double word "For"

- appveyor.ps1
- dsc/pullServerSMB.md
- reference/3.0/Microsoft.WsMan.Management/Enable-WSManCredSSP.md
- reference/4.0/Microsoft.WsMan.Management/Enable-WSManCredSSP.md
- reference/6/Microsoft.PowerShell.Core/About/about_Logging.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
> typo: Double word "the"

- reference/5.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md
updated line 74 to reflect the correct firewall rule name on 1803 and above (not checked on older to confirm when it changed)
> updated Enable-PSRemoting

- reference/6/Microsoft.PowerShell.Utility/Test-Json.md
Created documentation for the Test-Json cmdlet per #2896 .  This cmdlet was introduced in 6.1 but I do not see a folder for that version under reference so I included it in the `6` folder.  This is my first submitted document so apologies if that was the wrong approach or if I made other formatting/content errors.  Please let me know if there are any issues so that I can get them fixed.
Thanks!
> Added Test-Json help file

- reference/docs-conceptual/core-powershell/vscode/using-vscode.md
> Remove duplicated words in using-vscode.md

- dsc/troubleshooting.md
related to https://github.com/PowerShell/PowerShell-Docs/issues/71 and https://github.com/PowerShell/PowerShell-Docs/pull/117
> update DebugMode example (values no longer boolean)

- reference/6/Microsoft.PowerShell.Core/About/about_Parameters.md
> Removed extension in link

- .gitignore
- .vscode/extensions.json
Add recommended extensions so someone who clones this repo and uses vscode will automatically ask to install these extensions
> Add recommended extensions

- reference/6/Microsoft.PowerShell.Utility/ConvertTo-Json.md
Fix https://github.com/PowerShell/PowerShell-Docs/issues/2941
> Document `ConvertTo-Json -EscapeHandling`

- .markdownlint.json
- reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md
> Update mac setup instructions

- reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
> Add help for `RetryIntervalSec` and `MaximumRetryCount` parameters

- reference/6/Microsoft.PowerShell.Core/About/about_Jobs.md
- reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
> Add ampersand background operator docs

- reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
- reference/6/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
> Add troubleshooting information about supported authentication methods for macOS

- reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
> Add mention of ValidateRangeKind enum

- reference/5.1/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
- reference/5.1/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
- reference/6/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
- reference/6/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
> Adding text for -Content and -SourcePathorExtension parameters on *-Authenticode cmdlets

- reference/5.1/Microsoft.PowerShell.Security/New-FileCatalog.md
- reference/5.1/Microsoft.PowerShell.Security/Test-FileCatalog.md
- reference/6/Microsoft.PowerShell.Security/New-FileCatalog.md
- reference/6/Microsoft.PowerShell.Security/Test-FileCatalog.md
Adding documentation in 5.1/6 for New/Test-FileCatalog to resolve #652
> Add help for New/Test-FileCatalog

- wmf/5.0/dsc_importdscresource.md
> Fix typo in wmf/5.0/dsc_importdscresource.md

- reference/6/Microsoft.PowerShell.Core/About/about_Language_Modes.md
> Identify manifest restricted language variables

- reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
- reference/6/Microsoft.PowerShell.Core/About/about_Modules.md
Fix https://github.com/PowerShell/PowerShell-Docs/issues/3033
> Ps module path

- reference/docs-conceptual/getting-started/cookbooks/Decode-PowerShell-Command-from-a-Running-Process.md
- reference/docs-conceptual/toc.yml
Added metadata, Acrolinx edits, and added to TOC
> adding decode article to cookbook

- .openpublishing.redirection.json
- gallery/docfx.json
Fixed author metadata and added missing redir for readme file.
> fix metadata and redir

- reference/3.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/3.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/4.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/5.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/5.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/6/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/6/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/6/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
> provider doc comment removal

- reference/3.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/3.0/Microsoft.PowerShell.Management/New-Item.md
- reference/3.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/4.0/Microsoft.PowerShell.Management/New-Item.md
- reference/4.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/5.0/Microsoft.PowerShell.Management/New-Item.md
- reference/5.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/5.1/Microsoft.PowerShell.Management/New-Item.md
- reference/5.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
- reference/6/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
- reference/6/Microsoft.PowerShell.Management/New-Item.md
- reference/6/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
> Closes #2432 - Adds item type enumerations for New-Item

- reference/5.0/PackageManagement/Save-Package.md
- reference/5.1/PackageManagement/Save-Package.md
- reference/6/PackageManagement/Save-Package.md
> fix invalid parameter name

- reference/3.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
- reference/6/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
> Clarify exit code for exit statement - Fixes #3282

- reference/5.0/Microsoft.PowerShell.Management/New-WebServiceProxy.md
- reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md
> Updating online link metadata for New-WebServiceProxy 5.0 and 5.1

- reference/docs-conceptual/getting-started/fundamental/Learning-PowerShell-Names.md
Add missing word "the" to Learning PowerShell names section.
> Correct grammar

- reference/6/Microsoft.PowerShell.Core/About/About.md
- reference/6/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
- reference/6/Microsoft.PowerShell.Core/Clear-Host.md
- reference/6/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md
- reference/6/Microsoft.PowerShell.Security/New-FileCatalog.md
- reference/6/Microsoft.PowerShell.Security/Test-FileCatalog.md
- reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md
- reference/6/Microsoft.PowerShell.Utility/Get-Culture.md
- reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md
- reference/docs-conceptual/core-powershell/web-access/authorization-rules-and-security-features-of-windows-powershell-web-access.md
- reference/docs-conceptual/core-powershell/web-access/install-and-use-windows-powershell-web-access.md
- reference/docs-conceptual/getting-started/Getting-Started-with-Windows-PowerShell.md
- reference/docs-conceptual/getting-started/fundamental/Windows-PowerShell-Integrated-Scripting-Environment--ISE-.md
Fixed the following issues identified by CATS
Case Name | Total Number | Failed Number | Passed Number
-- | -- | -- | --
Broken internal links | 19010 | 21 | 18989
> Fixed broken links from CATS report

- reference/docs-conceptual/getting-started/fundamental/Using-Variables-to-Store-Objects.md
> Fix wording and a typo.

- developer/hosting/adding-and-invoking-commands.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
- reference/3.0/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/3.0/Microsoft.PowerShell.Core/Enter-PSSession.md
- reference/4.0/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/4.0/Microsoft.PowerShell.Core/Enter-PSSession.md
- reference/5.0/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/5.1/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/6/Microsoft.PowerShell.Core/About/about_Variable_Provider.md
- reference/docs-conceptual/getting-started/cookbooks/Redirecting-Data-with-Out---Cmdlets.md
- wmf/5.0/psget_modulecmdlets.md
From the typo police, Happy Thanksgiving. :gift::cop:
> Fix typo: PowxxShell -> PowerShell

- reference/6/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
> created relative link for about_CommonParameters

- reference/6/Microsoft.PowerShell.Utility/Join-String.md
> Documentation for join-string cmdlet.

- reference/3.0/PSDiagnostics/Disable-PSTrace.md
- reference/3.0/PSDiagnostics/Enable-PSTrace.md
- reference/3.0/PSDiagnostics/Get-LogProperties.md
- reference/3.0/PSDiagnostics/PSDiagnostics.md
- reference/3.0/PSDiagnostics/Set-LogProperties.md
- reference/4.0/PSDiagnostics/Disable-PSTrace.md
- reference/4.0/PSDiagnostics/Enable-PSTrace.md
- reference/4.0/PSDiagnostics/Get-LogProperties.md
- reference/4.0/PSDiagnostics/PSDiagnostics.md
- reference/4.0/PSDiagnostics/Set-LogProperties.md
- reference/5.0/PSDiagnostics/Disable-PSTrace.md
- reference/5.0/PSDiagnostics/Enable-PSTrace.md
- reference/5.0/PSDiagnostics/Get-LogProperties.md
- reference/5.0/PSDiagnostics/PSDiagnostics.md
- reference/5.0/PSDiagnostics/Set-LogProperties.md
- reference/5.1/PSDiagnostics/Disable-PSTrace.md
- reference/5.1/PSDiagnostics/Enable-PSTrace.md
- reference/5.1/PSDiagnostics/Get-LogProperties.md
- reference/5.1/PSDiagnostics/PSDiagnostics.md
- reference/5.1/PSDiagnostics/Set-LogProperties.md
- reference/6/PSDiagnostics/Disable-PSTrace.md
- reference/6/PSDiagnostics/Enable-PSTrace.md
- reference/6/PSDiagnostics/Get-LogProperties.md
- reference/6/PSDiagnostics/PSDiagnostics.md
- reference/6/PSDiagnostics/Set-LogProperties.md
Fixes #3325 for the following files:
- Disable-PSTrace.md
- Enable-PSTrace.md
- Get-LogProperties.md
- PSDiagnostics.md
- Set-LogProperties.md
> Added descriptions and examples to PSDiagnostics cmdlets - Fixes #3325

- reference/5.1/Microsoft.PowerShell.Core/About/about_Logging.md
Similar Doc exists for 6 already.  Some of this needs to be ported there, but I'll do that after we edit this and get this merged.
> Add Script Block Logging doc

- reference/6/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md
- reference/6/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md
- reference/6/Microsoft.PowerShell.Core/Get-ExperimentalFeature.md
> drafts of documentation for new ExperimentalFeature cmdlets

- reference/5.0/Microsoft.PowerShell.Management/Get-Process.md
- reference/6/Microsoft.PowerShell.Management/Get-Process.md
> Change wildcard support error - fixes #3355

- developer/cmdlet/selectstr-tutorial.md
The duplicated text reported in the issue did not exist in the current version but that does not match what is published to live. Made minor change to for a new commit and build.
> updating metadata to force a new commit - Fixes #3353

- reference/docfx.json
New metadata values are:
ms.prod | Technology name | ms.technology
-- | -- | --
powershell |   |  
powershell | Desired State   Configuration | powershell-dsc
powershell | PowerShell SDK | powershell-developer
powershell | PowerShell Cmdlets | powershell-cmdlets
powershell | PowerShell Conceptual | powershell-conceptual
powershell | PowerShell Gallery | powershell-gallery
powershell | PowerShell JEA | powershell-jea
powershell | Windows Management   Framework | powershell-wmf
> updated ms.technology metadata

- reference/6/Microsoft.PowerShell.Management/Set-Service.md
> Add AutomaticDelayedStart to StartupType - Fixes #3279
