dsc/lnxGettingStarted.md
Corrected one spelling typo ("Minimum")
Corrected table formatting for the Linux Log Files (need empty line before start of table pipe)
=> Fix spelling typo and table formatting

dsc/configurations.md
Smart double quotes were being used. These are not good for copy/paste.
=> use correct double quotes and reformat code block

dsc/TOC.md, dsc/configDataCredentials.md
Linking new doc article under Configuration data section.
=> Adding documentation for PsDscAllowPlainTextPassword and PsDscAllowDomainUser

dsc/configDataCredentials.md
Went to fix the the formatting in the code examples and removed the passive voice while I was at it, can roll back if this is not wanted.
=> Fixing code format and removing passive voice

wmf/dsc_waitfor.md
Fixed a minor typo in the hint at the bottom of the file (line 36).
=> Fixed typo in dsc_waitfor.md

dsc/TOC.md, dsc/builtInResource.md
@eslesar Should they be single word? Either way TOC and builtinResource.md should use the same style.
=> Made the resource names as single word because that's how it is used in configurations

dsc/lnxBuiltInResources.md
Asterisk missing in markdown means the nxScript link isn't in the list on https://msdn.microsoft.com/en-us/powershell/dsc/lnxbuiltinresources
=> Fix missing list item for nxScript

wmf/dsc_testconfiguration.md
Fixed a small typo. In two places "target" was misspelled as "targt".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/264)
=> Fixed typo in dsc_testconfiguration.md

dsc/lnxGettingStarted.md
- small typo (ackage instaed of package)
- $env:USERPROFILE and $PSHOME instead of cmd-style variables
- case for -Parameters, $Variables and CommandNames
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/273)
=> Fixed typo, updated casing, used PS variables.

dsc/singleInstance.md
xTimezone was updated recently to match DSC Style Guidelines. This PR updates the sample code in SingleInstance.md to match the xTimezone code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/279)
=> Updatd SingleInstance sample code to match latest xTimezone code - Fixes #278

dsc/scriptResource.md
The Script resource documentation didn't explain how to pass variables to the resource's script blocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/282)
=> Improving Script resource documentation

dsc/secureMOF.md
There were still some areas in the "Creating the Certificate" Process in the Secure.MOF file. This section has now been broken down into two separate methods for creating the certificate (creating on the Authoring machine and creating on the Target Node).
Thanks to @megamorf for pointing out the issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/286)
=> Clarified Creating the Certificate Process in Secure.MOF

wmf/productincompat.md
As we don't support WFM 5.0 with SMA 2012 R2, we need to document this as we already found 2 incompatibility bugs and customers should not upgrade to WFM 5.0 anymore in the SMA 2012 R2 environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/295)
=> no support for SMA 2012 R2

dsc/secureMOF.md
@gigi81 pointed out that the script samples will only work on Windows 10/Windows Server 2016.
I have added examples on how to perform the process on earlier version OS's.
@megamorf - could you possibly take a look and let me know if you think anything else should be changed?
@TravisEz13 - In the examples I added I've used a script available on [Script Center](https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6) - is it acceptable to do this in the DSC documentation? I used to use this method prior to Windows 10 so it was the one I was most familiar with and no works (I still use it in my LabBuilder project).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
=> Adding additional info about certificate creation on Windows Server 2012 R2 to SecureMOF.md - Fixes #300

dsc/groupResource.md
Hopefully this makes it clearer as to the requirements for the Credential usage when adding AD Users to the Local Administrators Group on a machine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/304)
=> Added additional Group example for working with AD user into Local Group

dsc/secureMOF.md
- Change EKU/KU in SecureMOF examples to be minimum required for cred encryption.
The EKU and KU in the Secure MOF examples for generating Self Signed certs for Windows Server 2012 R2 and earlier had EKU and KU's that aren't actually required. This change removes the unnecessary ones.
Thanks @megamorf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/305)
=> Change EKU/KU in SecureMOF examples to be minimum required for cred encryption

wmf/limitation_dsc.md
Added information about known issue with ModuleVersion behavior in RTM for Import-DscResource to bottom of DSC Known issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/340)
=> Added known limitation with ModuleVersion with Import-DscResource.

dsc/secureMOF.md
Encryption part has a not-yet-documented ability to use CertificateID, 
if certificate is available in the local Cert:\ storage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/414)
=> Add missed information about CertificateID to secureMOF.md

dsc/scriptResource.md
The documentation says that GetScript should return a Hashtable. This is only partially correct.
The hashtable must contain only one key "Result", where the value of "Result" is of type "String".
If you return anything else, you will get errors when running Get-DscConfiguration due to the return of Get-TargetResource does not follow the corresponding provider schema.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/473)
=> Updated script documentation around GetScript

scripting/core-powershell/ise/How-to-Debug-Scripts-in-Windows-PowerShell-ISE.md
Line 69 is missing the PS-prefix:
get-breakpoint | remove-breakpoint
It should be:
get-psbreakpoint | remove-psbreakpoint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/508)
=> Fix misspelled cmdlets

wmf/5.1/features-scenarios-cache/DSCSigningValidations_1.md
Image files are not showing on the browser because of the casing.  Updated the references to use upper case extension. The images are now showing when previewing the document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/521)
=> Fixing the case on the extension of the files(.png => .PNG)

wmf/TOC.md
A missing space was causing OPS to choke on the TOC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/537)
=> Fix bug in TOC listing

wmf/5.1/engine-improvements.md
The table used a pipe symbol within a code block. When this document is used to generate content for MSDN, that causes the table to render incorrectly. Using <code></code> to identify the code block instead of backticks and replacing the internal pipe with &#124; (ascii pipe) should resolve this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/536)
=> Change in markdown formatting of the table

gallery/psgallery/Deleting-Items.md, gallery/psgallery/Managing-Item-Owners.md, gallery/psgallery/psgallery_contacting_administrators.md, gallery/psgallery/psgallery_contacting_item_owners.md, gallery/psgallery/psgallery_dispute_resolution.md, gallery/psgallery/psgallery_filelist_feature.md, gallery/psgallery/psgallery_unlist_items.md
Just did a quick pass at lunch on the new Gallery content. A couple of the headers were missing, H2s that should have been H1s, etc. Just small stuff.
In addition, remember to use [semantic line feeds](http://rhodesmill.org/brandon/2012/one-sentence-per-line/) so that `git diff` is easy to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/554)
=> Fixed headers and semantic line feeds on Gallery content

.localization-config
Updating loc config to include upper case ".MD" due to source file "jea/TOC.MD".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/powershell-docs/584)
=> Updating loc config to include upper case ".MD"

gallery/psget/module/modulewithpseditionsupport.md
$PSDefaultParameterValues.Clear() is not needed  at each module gets its own copy
=> Fix PSScriptAnalyzer module file example

gallery/psget/overview.md
Release notes document will be created while publishing the PowerShellGet module to the PowerShellGallery.com.
=> Removing the release notes reference

dsc/troubleshooting.md
Hi @eslesar,
We happen to find this source string issue where closing backtick (`) was missing after Trace-xDscOperation1, causing most of this string to be blocked from localization.
Could you please help to check and merge if agreed?
Thank you,
Jason
=> Add missing backtick (`) after Trace-xDscOperation1

scripting/TOC.md
Found that "Installing the Windows PowerShell SDK" link to redirected to MSDN site (https://msdn.microsoft.com/en-us/library/ff458115.aspx) instead of existing (setup/Installing-the-Windows-PowerShell-SDK.md). Proposed to fix the link to use (setup/Installing-the-Windows-PowerShell-SDK.md).
=> Fixed "Installing the Windows PowerShell SDK" Link

appveyor.yml
This should make it so that we only run the Appveyor CI if something in a PR or commit to `staging` or `live` changes a file inside of the `reference` folder (or the Appveyor script itself).
=> only run appveyor if ref is changed

dsc/troubleshooting.md
trace-xDscOperation should not have a '1' after it
=> removing typo

dsc/secureMOF.md
Vadims Podans updated his self-signed certificate generator script on 9/11/2016 and removed the parameter '-Store'.
=> -Store param removed from self-signed script

scripting/getting-started/cookbooks/Creating-.NET-and-COM-Objects--New-Object-.md
Hi @juanpablojofre,
We have a localization bug where formatting was lost only for the two code blocks fixed in this PR.
We found it was due to \<pre\> tags used instead of code fencing like others. 
The MD transformer used for localization will not treat the text within \<pre\> tags as code block, so formatting will be lost.
If you agree, could you please help to merge this PR?
Thank you
Jason
=> Replacing <pre> tags with code fencing

reference/5.1/Microsoft.PowerShell.Core/About/about_Debuggers.md
When interactively debugging the commands for StepInto, StepOver, and StepOut do not have a hyphen between words.  Removing hyphen from all examples in About_Debuggers help file.
=> Remove hyphen from Step-Into, Step-Over, and Step-Out

dsc/pullServer.md
Prevents: 
WARNING: The configuration 'ConfigurePullServer' is loading one or more built-in resources without explicitly importing associated modules. Add Import-DscResource –ModuleName 'PSDesiredStateConfiguration' to your configuration to avoid this message.
=> added import for PSDesiredStateConfiguration

dsc/pullServer.md
Prevents:
xPSDesiredStateConfiguration\xDscWebService : Class 'xDSCWebService' requires that a value of type 'Boolean' be
provided for property 'UseSecurityBestPractices'.
At line:25 char:9
+         xDscWebService PSDSCPullServer
+         ~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingValueForMandatoryProperty,xPSDesiredStateConfiguration\xDSCWebService
=> Added UseSecurityBestPractices

dsc/pullServer.md
Looks like the best practices include killing SSL, which I believe will cause some issues with DSC communication such as:
SocketException: An existing connection was forcibly closed by the remote host
=> Default UseSecurityBestPractices to False

reference/5.0/Microsoft.PowerShell.Management/Register-WmiEvent.md
-Query parameter was having a typo as -Auery
=> Query Parameter in Example 2 is corrected

dsc/reportServer.md
The GetReport cmdlet example is out of date and no longer works.
Place see the comment @NarineM posted [here](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/97#issuecomment-209115354) detailing the changes required to work with the new report server.
=> Updated GetReport Cmdlet Example

reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-String.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md
Fix these errors
```
Exception calling "NodeModelToMamlModel" with "1" argument(s):
"F:\dev\PowerShell-Docs\reference\5.0\Microsoft.PowerShell.Utility\ConvertFrom-String.md:402:(1505) '-  '
Expect hyperlink, but got -"
At F:\dev\platyPS\out\platyPS\platyPS.psm1:1224 char:9
+         $maml = $t.NodeModelToMamlModel($model)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : HelpSchemaException
Exception calling "NodeModelToMamlModel" with "1" argument(s):
"F:\dev\PowerShell-Docs\reference\5.1\Microsoft.PowerShell.Utility\ConvertFrom-String.md:402:(1505) '-  '
Expect hyperlink, but got -"
At F:\dev\platyPS\out\platyPS\platyPS.psm1:1224 char:9
+         $maml = $t.NodeModelToMamlModel($model)
+ …
```
=> Fix platyPS errors in ConvertFrom-String.md

appveyor.yml
Appveyor is not currently skipping commits outside reference. I made a small syntactical change that I believe *might* fix this problem. If it doesn't, I have a support ticket ready to submit
=> Skip CI for commits outside reference

dsc/reportServer.md
The URI `http://CONTOSO-REPORT:8080/PSDSCReportServer.svc/Nodes(AgentID = MyNodeAgentId)/Reports` is inconsistent with the example URI:
```
param($AgentId = "$((glcm).AgentId)", $serviceURL = "http://CONTOSO-REPORT:8080/PSDSCPullServer.svc")
$requestUri = "$serviceURL/Node(ConfigurationId= '$AgentId')/StatusReports"
```
=> Fixed up example URI to be consistent with text.

reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
By using triple backtick syntax it becomes unnecessary to escape special characters in monospace sections.
Using angle brackets to enclose a URL that contains parentheses assists the parser in linking the full URL.
Brought back the Explorer!
=> Updated examples for consistency, fixed link

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Gross!
By arranging this as one contiguous code block, I believe the formatting issue will be resolved. (Is it possible to run the md -> help.txt conversion process to test the documentation "build"?)
=> PSVersionTable example formatting was broken in powershell help

dsc/reportServer.md
The API is case-sensitive and 'AgentID' needs to be spelled as 'AgentId'
=> Fix case typo in sample

reference/5.0/Microsoft.PowerShell.Management/Get-Service.md
Updated name, displayname parameters - they DO accept wild cards.
This change reflects earlier changes in 5.1 content. The 3.0 and 4.0 content is correct.
=> Update Get-Service 5.0

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Not sure what the about_topic cleanup looks like right now, but I hit this topic today, and I thought I might just clean it up as an example of that kind of stuff that probably still needs to be addressed across about_topics. For instance:
* using syntax blocks
* proper indentation of code examples
* \#\# style headings for sub-headings in `# LONG DESCRIPTION`
* removal of a *lot* of whitespace
=> platyPS-ize about_Functions_Advanced_Parameters

dsc/configData.md
Changed Feature in the node hashtable to role, this should have failed when this was tested, as the nodename vm-2 had no role == vmhost.
=> Invalid propertyname

reference/5.1/Microsoft.PowerShell.Core/About/about_Providers.md
These are just a few minor changes to improve the already excellent writing.
1. Removed future tense in one sentence. Future tense is to be avoided. It reduces the readability of the text (and confuses: so when WILL this happen?). Also, some non-native English speakers have difficulty with future tense.
2. Updated all uses of cmdlets to be consistent. This means upper casing them and upper casing provider names, drives, etc. In each case, the change is based on the names given in PowerShell, so instead of "get-childitem cert:", it's "Get-ChildItem Cert:" - this makes the name in the help file to be consistent with what the user would see if they invoked tab completion.
=> Updated about_Provider

wmf/5.1/release-notes.md
According to https://msdn.microsoft.com/en-us/powershell/wmf/5.1/install-configure
4.6 is required (instead of 4.5 in this article)
=> Required .NET Framework version

dsc/PackageManagementDscResource.md, dsc/PackageManagementSourceDscResource.md
Adding PackageManagement DSC resource docs for DSC resources that will ship with the PackageManagement module in RS2+. Also available from OSS,
from a different module until RS2 changes are ported to OSS.
=> Adding PackageManagement DSC resource docs

dsc/authoringResourceComposite.md
Missing line break was causing the metadata to render as a code block, instead of getting consumed by OPS.
=> Added line break

dsc/configurations.md
Added the configuration call to the bottom of the function and explanation under "Compiling the configuration"
Under the following section
**"Compiling the first configuration above results in the following folder structure:"**
The configuration call in the code block should be removed.
=> Update to DSC Configurations documentation

wmf/5.1/install-configure.md
It would seem a better method and customer experience, that we should direct and provide the links to .NET Framework 4.5.2 (supported) rather than .NET Framework 4.5 (unsupported).
=> Update .NET from 4.5 to 4.5.2

reference/3.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
Note
-----
For the table of operators, in all versions, I've inserted `<br />` tag to put each example on a line. That's because, as far as I know, there is no GFM supported way of inserting a newline inside a table cell. Please let me know if that's not acceptable.
For example:
|Operator|Description|Example|
|--------|-----------|-------|
| + |Adds integers; concatenates strings, arrays, and hash tables.| `6+2`<br />`"file" + "name"`|
=> Update formatting for Arithmetic Operators about topic

dsc/partialConfigs.md
hey @eslesar can you double-check my syntax? right now the page points to https://msdn.microsoft.com/en-us/reference/5.1/psdesiredstateconfiguration/publish-dscconfiguration which misses the "powershell" part of the url. i think this solves the problem but i'm not sure.
=> fixing broken links to publish-dscconfiguration

reference/3.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
Fixed the headers to have appropriate 2nd level headings instead of all headers being level 1. This is based on rest of the documentation found outside the "About" folder.
Adjusted some code formatting and added appropriate links to the items listed under SEE ALSO section.
-----
=> Fix headers, minor code formatting, and links under SEE ALSO

dsc/troubleshooting.md
Reverts PowerShell/PowerShell-Docs#1028
Have a feeling that rebase of this PR made the staging & live diverge after the last merge into live.
=> Revert "Add remoting requirements"

reference/3.0/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
This updates the `about_Types.ps1xml` page for the 3.0 reference as an example of possible markdown-aware formatting for the `about_*.ps1xml` pages.
I thought I would submit a single file before going ahead and making lots of changes to discuss:
- Whether this change is desired or useful
- What style of markdown is best, e.g. when to put terms in backticks, whether tables should be used
- Whether this change is alright when done incrementally, or if it (and all the other `about_*`) pages should be updated all at once
=> Markdown-aware ps1xml pages -- Example for consideration

reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md
Corrected mismatched newlines in the examples for **Add-Member** v5.1 to be consistent with other versions.
=> Updated examples in Add-Member v5.1

dsc/configDataCredentials.md
Removed broken link to https://msdn.microsoft.com/en-us/powershell/wmf/dsc_runas.
Correct WMF 5.0 release notes page redirects to "Running DSC with user credentials" which is referenced a few paragraphs above.
=> Removed broken link

jea/index.md
Localized copies of JEA docs are redirecting /jea/index to Windows Home Server 2011 documentation. To fix this, we need to add a redirect page in the EN-US docs so the international copies pick it up and properly redirect to the overview page.
=> Adding index.md to JEA docs for loc fix

reference/3.0/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/4.0/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/5.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
v5.1 already merged in #1135 
When consulting this document it was unclear whether files included in -FileList would be published along with the other module files when pushed to a PSRepository. They are, hence the clarification update.
- [ X] Impacts 5.0 document
- [ X] Impacts 4.0 document
- [ X] Impacts 3.0 document
=> Clarify -FileList for parameter (v3.0, v.4.0, v5.0)

reference/3.0/Microsoft.PowerShell.Utility/Write-Error.md, reference/4.0/Microsoft.PowerShell.Utility/Write-Error.md, reference/5.0/Microsoft.PowerShell.Utility/Write-Error.md, reference/5.1/Microsoft.PowerShell.Utility/Write-Error.md, reference/6/Microsoft.PowerShell.Utility/Write-Error.md
Line 1 of Example 4 for Write-Error had a syntax issue (possible transposing error)
Line 2 of Example 4 resulted in a ParameterBindingException exception since the Exception parameter is not a positional parameter. Changed it to a named parameter.
Corrected in all version.
=> Fix Write-Error Example 4 in 3.0, 4.0, 5.0, 5.1, and 6

jea/prerequisites.md
Previously, the JEA docs stated that virtual accounts are not supported on Windows 7. This is incorrect. Group managed service accounts are not supported because gSMAs cannot be configured on Windows 7 or 2008 R2, but virtual accounts (temporary local admins) are supported on both Windows 7 and 2008 R2 when WMF 5.1 is installed.
=> Fixed JEA identity support statement for Win7/2008R2

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md, reference/6/About/about_Functions_Advanced.md
- Fix the example code formatting all versions
- Fix the "Windows PowerShell Cmdlets" link all versions
=> Fix 3.0, 4.0, 5.0, 5.1, 6 about_Functions_Advanced

reference/3.0/Microsoft.PowerShell.Core/About/about_Escape_Characters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Escape_Characters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Escape_Characters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Escape_Characters.md, reference/6/About/about_Escape_Characters.md
User request:
"_Please mention that, when using a backtick as a continuation character, there must be no trailing space (or it escapes the space) and there must be a preceding space or the preceding token must be enclosed. 
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13073505-about-escape-characters-doesn-t-mention-syntax-reqVersion(s) of document impacted_"
=> Updated content per user request

gallery/psget/repository/bootstrapping_nuget_proivder_and_exe.md
Only impacts one document.  Significant modification to that file's content.  Based on direct user feedback given over Twitter.
=> Update offline usage of package management doc

gallery/psget/repository/bootstrapping_nuget_proivder_and_exe.md
This change impacts only 1 file - related to offline configuration of package management.  Based on customer feedback over Twitter.  It is a fairly significant overhaul of that file content.
=> Migreene patch1

reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/6/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
Please fix the incorrect "online version" values as follows:
x LinkId=822079 (Windows Server Future Resources)
x LinkId=821506 (Receive-PSSession)
o LinkId=821507 (Register-ArgumentCompleter)
I found that when I executed `Get-Help Register-ArgumentCompleter -Online` and forwarded to the Receive-PSSession page.
=> Fix LinkId for Register-ArgumentCompleter

gallery/psgallery/psgallery-PublishingGuidelines.md
Execution Policy is not a security boundary, so removing the documentation implying it is one. The existing commentary about code authenticity is good.
=> Removing implication of execution policy as a security boundary

reference/3.0/Microsoft.PowerShell.Management/Start-Process.md, reference/4.0/Microsoft.PowerShell.Management/Start-Process.md, reference/5.0/Microsoft.PowerShell.Management/Start-Process.md, reference/5.1/Microsoft.PowerShell.Management/Start-Process.md, reference/6/Microsoft.PowerShell.Management/Start-Process.md
In the files for the Start-Process cmdlet it says "The following table shows the verbs for some common process file types." The following information is displayed as code snippets instead (see [here](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.management/start-process#-verb) for an example). This PR updates all affected versions.
=> Start-Process: Verbs look better in Table

reference/5.0/Microsoft.PowerShell.Utility/Convert-String.md, reference/5.1/Microsoft.PowerShell.Utility/Convert-String.md
The "Example 1" doesn't work:
```
PS> $Names = "Evan Narvaez","David Chew","Elisa Daugherty"
PS> Convert-String -InputObject $Names -Example "Patti Fuller = Fuller, P."
Convert-String : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'InputObject'. Specified method is not supported.
At line:1 char:29
+ Convert-String -InputObject $Names -Example "Patti Fuller = Fuller, P ...
+                             ~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Convert-String], ParameterBindingException
+ FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.StringManipulation.ConvertStringCommand
```
My pull request is a copy from [Hey, Scripting Guy! Blog](https://blogs.technet.microsoft.com/heyscriptingguy/2015/08/17/use-the-powershe …
=> Fix Convert-String example

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
=> updated docs for `-FollowRelLink` and `-MaximumFollowRelLink` switches

reference/5.1/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md
- [ X ] Impacts 5.1 document
- [ X ] Impacts 5.0 document
- [ X ] The documented feature was introduced in version 5.0 of PowerShell
=> Fixed typo on Get-DscConfigurationStatus

reference/5.0/Microsoft.PowerShell.Management/Get-EventLog.md
5.0 also had the problem with "Accept wildcard characters" properties of -Message, -Source, & -UserName parameters, so I corrected them to "True"
=> Update Get-EventLog.md -5.0

dsc/TOC.md
=> Fix typo in TOC.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/6/About/about_Operators.md
* Fix links for `-f` format operator
* Style Guide alignment: Syntax formatting for code blocks
* Inline code formatting for operators and cmdlets
=> Update about_Operators all versions

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
The fix for the PowerShell issue 2227 (https://github.com/PowerShell/PowerShell/issues/2227) strips the Authorization header when a redirect occurs. For edge cases, the -PreserveAuthorizationOnRedirect switch disables the header stripping logic.
=> Add -PreserveAuthorizationOnRedirect Invoke-WebRequest  and Invoke-RestMethod

reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md
The help for the -Format parameter described the new formats that were added to PS 5+ (FileDate, FileDateUniversal, FileDateTime, and FileDateTimeUniversal), but the description of these formats was misleading because it didn't properly relate to actual .NET DateTime format strings (that can even be used in the -Format parameter). I have corrected this so that the actual format string used behind the scenes is referred to in the docs, along with a brief description that indicates what the format means and highlights the importance of case-sensitivity in the format string.
=> Refer to actual .NET date-time format strings

reference/6/Microsoft.PowerShell.Core/Clear-Host.md
Clear-Host is a simple function. We cannot use common parameters.
=> Remove CommonParameters from Clear-Host.md

reference/3.0/Microsoft.PowerShell.Core/Providers/ToC.md
=> Updated Providers ToC.md for 3.0

reference/6/ToC.md
=> Updated Microsoft.PowerShell.Core ToC.md for 6.0

reference/3.0/Microsoft.PowerShell.Core/ToC.md
=> Updated Microsoft.PowerShell.Core ToC.md for 3.0

reference/6/ToC.md
=> Updated ToC.md for 6.0

reference/3.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/4.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/5.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Member.md, reference/6/Microsoft.PowerShell.Utility/Get-Member.md
The "Example 2" throws exception:
```
PS> (Get-Service -Schedule).PSBase
Get-Service : A parameter cannot be found that matches parameter name 'Schedule'.
At line:1 char:14
+ (Get-Service -Schedule).PSBase
+              ~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-Service], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetServiceCommand
```
=> Fix Get-Member example

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
The fix for issue https://github.com/PowerShell/PowerShell/issues/2895 adds a new switch parameter -SkipHeaderVerification. This switch allows callers to add header values that may not be standards compliant for cases where target sites require them.
All header values are added without validation when this switch is used.
=> Document new -SkipHeaderVerification switch on the Invoke-WebRequest and Invoke-RestMethod cmdlets

reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md, reference/4.0/Microsoft.PowerShell.Utility/Get-Date.md, reference/5.0/Microsoft.PowerShell.Utility/Get-Date.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md, reference/6/Microsoft.PowerShell.Utility/Get-Date.md
Hour is [from 0 to 23](https://github.com/PowerShell/PowerShell/blob/5ee4ec1e1e0bb9e1497eb13bb2ceb7eab8b37426/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs#L113)
Minute is [from 0 to 59](https://github.com/PowerShell/PowerShell/blob/5ee4ec1e1e0bb9e1497eb13bb2ceb7eab8b37426/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs#L134)
Second is [from 0 to 59](https://github.com/PowerShell/PowerShell/blob/5ee4ec1e1e0bb9e1497eb13bb2ceb7eab8b37426/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs#L155)
Test cases:
```
0..23 | % { Get-Date -Hour $_ }
0..59 | % { Get-Date -Minute $_ }
0..59 | % { Get-Date -Second $_ }
```
=> Fix Get-Date -Hour -Minute -Second range

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/About/about_Functions_Advanced_Parameters.md
added clarifying language on scope of when validateset applies
=> update scope of validateset attribute

reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md, reference/6/About/about_Remote_FAQ.md
Docs incorrectly used New-SessionConfigurationFile when it should be New-PSSessionConfigurationFile
=> Docs incorrectly used New-SessionConfigurationFile

reference/5.0/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/5.0/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/5.1/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md
Following the [style guide](https://github.com/PowerShell/PowerShell-Docs/blob/18b4423c9750bf9761bdf5ed82093e886f89fe56/STYLE.md):
* \*\*cmdlet\*\* -> \`cmdlet\`
* Remove 'PS C:\> '
=> Fix code style of Microsoft.PowerShell.Archive

reference/6/About/about_Escape_Characters.md, reference/6/About/about_Special_Characters.md
This PR is tied to the acceptance of the PR https://github.com/PowerShell/PowerShell/pull/3958.
=> Add documentation for `e and `u{}.

reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md
Added a line to New-ModuleManifest docs about encoding used by cmdlet.
=> Added a note on encoding of New-ModuleManifest

reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md
=> Fix Links and Formatting on Get-ChildItem for 3.0

reference/3.0/Microsoft.PowerShell.Host/Start-Transcript.md, reference/3.0/Microsoft.PowerShell.Host/Stop-Transcript.md, reference/4.0/Microsoft.PowerShell.Host/Start-Transcript.md, reference/4.0/Microsoft.PowerShell.Host/Stop-Transcript.md, reference/5.0/Microsoft.PowerShell.Host/Start-Transcript.md, reference/5.0/Microsoft.PowerShell.Host/Stop-Transcript.md, reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md, reference/5.1/Microsoft.PowerShell.Host/Stop-Transcript.md, reference/6/Microsoft.PowerShell.Host/Start-Transcript.md, reference/6/Microsoft.PowerShell.Host/Stop-Transcript.md
Following the [style guide](https://github.com/PowerShell/PowerShell-Docs/blob/18b4423c9750bf9761bdf5ed82093e886f89fe56/STYLE.md):
* \*\*cmdlet\*\* -> \`cmdlet\`
* cmdlet -> \`cmdlet\`
* parameter -> \*\*parameter\*\*
* Remove 'PS C:> '
* PascalCase
=> Fix code style of Microsoft.PowerShell.Host

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
Adds header formatting to the commands for easier scroll through to find information.  Before you couldn't easily see where one command started and the previous ended.
=> Scroll-through header levels

dsc/authoringResourceMofDesigner.md
Removes PS C:\> from examples, adds indentation to functions to improve readability.
=> Updates authoringResourceMofDesigner.md to match style guide

reference/6/Microsoft.PowerShell.Management/Get-Location.md, reference/6/Microsoft.PowerShell.Management/Pop-Location.md, reference/6/Microsoft.PowerShell.Management/Push-Location.md, reference/6/Microsoft.PowerShell.Management/Set-Location.md
* InformationAction and InformationVariable are referred to in CommonParameters section
* The text does not make sense (it might be a copy/paste error or auto-gen text)
=> Remove InformationAction/InformationVariable from *-Location.md

reference/3.0/Microsoft.PowerShell.Core/Import-Module.md, reference/4.0/Microsoft.PowerShell.Core/Import-Module.md, reference/5.0/Microsoft.PowerShell.Core/Import-Module.md, reference/5.1/Microsoft.PowerShell.Core/Import-Module.md, reference/6/Microsoft.PowerShell.Core/Import-Module.md
Fixed three problems as follows:
1. Cmdlet name
x Add-BitsTransferFile
x Add-BitsTransfer
o Add-BitsFile
2. `Get-Module BitsTransfer` results
The results include not only `ExportedCmdlets` but also unrelated properties.
3. `Get-Command -Module BitsTransfer` results
The description says "The results confirm that only the Add-BitsTransfer and Get-BitsTransfer cmdlets were imported."
But the results include not only the imported cmdlets but also the others.
=> Fix Import-Module Example 5

reference/4.0/Microsoft.PowerShell.Management/Get-ChildItem.md
=> Fixed Missing Documentation, Formatting and Links on Get-ChildItem for 4.0

reference/5.0/Microsoft.PowerShell.Management/Get-ChildItem.md
=> Fixed Missing Documentation, Formatting and Links on Get-ChildItem for 5.0

reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md
=> Fixed Missing Documentation, Formatting and Links on Get-ChildItem for 6.0

reference/3.0/Microsoft.PowerShell.Utility/Export-Alias.md, reference/3.0/Microsoft.PowerShell.Utility/Import-Alias.md, reference/4.0/Microsoft.PowerShell.Utility/Export-Alias.md, reference/4.0/Microsoft.PowerShell.Utility/Import-Alias.md, reference/5.0/Microsoft.PowerShell.Utility/Export-Alias.md, reference/5.0/Microsoft.PowerShell.Utility/Import-Alias.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Alias.md, reference/5.1/Microsoft.PowerShell.Utility/Import-Alias.md, reference/6/Microsoft.PowerShell.Utility/Export-Alias.md, reference/6/Microsoft.PowerShell.Utility/Import-Alias.md
Following the [style guide](https://github.com/PowerShell/PowerShell-Docs/blob/112dbd871a120e87a0ea4cdfd2b7d92df218a7e9/STYLE.md):
* \*\*cmdlet\*\* -> \`cmdlet\`
* cmdlet -> \`cmdlet\`
* parameter -> \*\*parameter\*\*
* Remove 'PS C:> '
* Remove 'C:\PS>'
* PascalCase
* Remove meaningless InformationAction/InformationVariable (#1415)
=> Fix code style of Export/Import-Alias

reference/6/About/about_Special_Characters.md
After looking at this page - https://msdn.microsoft.com/en-us/powershell/reference/6/about/about_special_characters - it is obvious we need to inject a bit more markdown formatting to display the escape list better, to use some headers on each special char (not just NULL) and to use triple-backtick on commands/output.
The only thing I'm not sure about is if your processor that converts this markdown file to the plain text equivalent will handle the escape of backticks e.g. `{double-backtick}` `` `u{1F44D}`` `{double-backtick}`.  Hopefully it will remove the leading and trailing double-backtick.
=> Fix markdown formatting of about_special_characters.

reference/6/About/about_Hash_Tables.md
Example code as is produced error, and was invalid syntax.
=> Remove errant $ sign from examples method call

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
Code as is produced error, and was invalid syntax.
=> Remove errant $ sign from method call

reference/5.1/Microsoft.PowerShell.Core/About/about_Providers.md
LINE: 69-70: says "Windows PowerShell providers are delivered to you in Windows PowerShell snap-ins" but should read "Windows PowerShell providers are delivered to you in Windows PowerShell modules". This must be true for two reasons: (1) snap-ins are a very old technology, (2) to create a snap-in, one must derive from ' CustomPSSnapIn ', but Providers derive from 'CmdletProvider', 'ItemCmdletProvider ', 'ContainerCmdletProvider', or 'NavigationCmdletProvider '.
=> Modules not Snap-Ins

reference/5.0/Microsoft.PowerShell.Utility/Get-Date.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md, reference/6/Microsoft.PowerShell.Utility/Get-Date.md
The description for the FileDateTime and FileDateTimeUniversal format options for Get-Date had the hours as lowercase (hh) which would be 12 hour time format. This updates them to uppercase (HH) to show that it actually outputs 24 hour formats.
=> Fix Get-Date FileDateTime* format descriptions

reference/3.0/Microsoft.PowerShell.Utility/Start-Sleep.md, reference/4.0/Microsoft.PowerShell.Utility/Start-Sleep.md, reference/5.0/Microsoft.PowerShell.Utility/Start-Sleep.md, reference/5.1/Microsoft.PowerShell.Utility/Start-Sleep.md, reference/6/Microsoft.PowerShell.Utility/Start-Sleep.md
Following the [style guide](https://github.com/PowerShell/PowerShell-Docs/blob/339b28cce36de091302c002d1829cb2289419ae8/STYLE.md):
* \*\*cmdlet\*\* -> \`cmdlet\`
* "-parameter" -> \*\*parameter\*\*
* Remove 'PS C:> '
* Remove meaningless InformationAction/InformationVariable
=> Fix code style of Start-Sleep

scripting/core-powershell/console/PowerShell.exe-Command-Line-Help.md
Removed incorrect line about -File syntax for switches which doesn't work.
Note that this doc doesn't appear to be versioned.  v3-v5.1 appear to be the same.  However in 6.0 we are taking a [change](https://github.com/PowerShell/PowerShell/pull/4178) so that $true and $false can be passed to parameters and switches with -File.  Not sure how to indicate that in the doc.
=> Clarified how -Command and -File handles parameters

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
LINE 470: The Line says "The `Where` method can be used to swiftly cast" but it should read "The `ForEach` method can be used to swiftly cast". That is the method in the example.
=> Edit to About_Arrays

reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
Fixing an erroneous dash in the cmdlet name.
=> Fix typo in Invoke-RestMethod.md

reference/3.0/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/4.0/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/5.0/Microsoft.PowerShell.Management/Get-PSDrive.md
Removed `Get-PSDrive -provider FileSystem` because it throws exception:
```
PS C:\> Get-PSDrive -provider FileSystem
Get-PSDrive : A parameter cannot be found that matches parameter name 'provider'.
At line:1 char:13
+ Get-PSDrive -provider FileSystem
+             ~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-PSDrive], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetPSDriveCommand
```
Besides, fixed some line breaks and PascalCase.
=> Remove wrong command from the Example 5 of Get-PSDrive

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
LINE 89: The carriage return prevented the "Suspend" parameter enum from being bold.
=> minor formatting error

dsc/enactingConfigurations.md
Removed "it", which seemed to be a left-over pronoun for "the Local Configuration Manager".
=> Remove leftover pronoun

reference/3.0/Microsoft.PowerShell.Core/Connect-PSSession.md, reference/3.0/Microsoft.PowerShell.Core/Disconnect-PSSession.md, reference/3.0/Microsoft.PowerShell.Core/Get-PSSession.md, reference/3.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/3.0/Microsoft.PowerShell.Core/Receive-PSSession.md, reference/4.0/Microsoft.PowerShell.Core/Connect-PSSession.md, reference/4.0/Microsoft.PowerShell.Core/Disconnect-PSSession.md, reference/4.0/Microsoft.PowerShell.Core/Get-PSSession.md, reference/4.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/4.0/Microsoft.PowerShell.Core/Receive-PSSession.md, reference/5.0/Microsoft.PowerShell.Core/Connect-PSSession.md, reference/5.0/Microsoft.PowerShell.Core/Disconnect-PSSession.md, reference/5.0/Microsoft.PowerShell.Core/Get-PSSession.md, reference/5.0/Microsoft.PowerShell.Core/Invoke-Command.md, reference/5.0/Microsoft.PowerShell.Core/Receive-PSSession.md, reference/5.1/Microsoft.PowerShell.Core/Connect-PSSession.md, reference/5.1/Microsoft.PowerShell.Core/Disconnect-PSSession.md, reference/5.1/Microsoft.PowerShell.Core/Get-PSSession.md, reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md, reference/5.1/Microsoft.PowerShell.Core/Receive-PSSession.md, reference/6/Microsoft.PowerShell.Core/Connect-PSSession.md, reference/6/Microsoft.PowerShell.Core/Disconnect-PSSession.md, reference/6/Microsoft.PowerShell.Core/Get-PSSession.md, reference/6/Microsoft.PowerShell.Core/Invoke-Command.md, reference/6/Microsoft.PowerShell.Core/Receive-PSSession.md
Fixed url, formatting and minor differences in wording.
=> Fix link for RunspaceState/RunspaceAvailability Enumeration

reference/3.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/6/About/about_Hash_Tables.md
Change instance of 'hash hash' to 'hash'
=> Fix typo: double hash

reference/6/Microsoft.PowerShell.Utility/ConvertTo-Html.md
Added documentation for use of Meta, Charset and Transitional parameters for ConvertTo-HTML. Reference [PowerShell #4184](https://github.com/PowerShell/PowerShell/pull/4184)
=> Documentation of Meta, Charset and Transitional parameter for ConvertTo-HTML

appveyor.ps1
Exclude the scripting folder from appveyor script as it only has markdown files and hence does not need to be considered for PlatyPS conversion.
=> Exclude scripting folder

wmf/5.1/Index.md, wmf/5.1/release-notes.md
Complying with doc team requirements to have an Index.MD file in the doc set. 
Took content from release-notes, added links to WMF topics and pointers to primary content for the apps included in WMF.
Also, fixed SIL to be Software Inventory Logging (which is the correct name).
=> Adding Index.md to WMF 5.1, and fixing SIL wording in Release-Notes

reference/3.0/Microsoft.PowerShell.Utility/Add-Type.md, reference/4.0/Microsoft.PowerShell.Utility/Add-Type.md, reference/5.0/Microsoft.PowerShell.Utility/Add-Type.md, reference/5.1/Microsoft.PowerShell.Utility/Add-Type.md, reference/6/Microsoft.PowerShell.Utility/Add-Type.md
Fixed url, formatting and minor differences in wording.
=> Fix link for OutputAssemblyType Enumeration

dsc/partialConfigs.md
https://docs.microsoft.com/en-us/powershell/dsc/partialConfigs lists Start-Configuration in the example, when it should be Start-DscConfiguration
=> Fixed cmdlet example

reference/docs-conceptual/Windows-PowerShell-Glossary.md
A "workflow" command type also gets common parameters.
"Workflow common parameters" could also be mentioned as a new entry.
=> Add a missing "workflow" command type

reference/3.0/Microsoft.PowerShell.Utility/Set-Date.md, reference/4.0/Microsoft.PowerShell.Utility/Set-Date.md, reference/5.0/Microsoft.PowerShell.Utility/Set-Date.md, reference/5.1/Microsoft.PowerShell.Utility/Set-Date.md, reference/6/Microsoft.PowerShell.Utility/Set-Date.md
=> Fix link for DateTime Methods and TimeSpan Methods

reference/3.0/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/4.0/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/5.0/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/5.1/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/6/Microsoft.PowerShell.Management/Get-PSDrive.md
* Added `-ErrorAction SilentlyContinue` to avoid DriveNotFoundException
* Replaced 'HKLM:\Network' with 'HKLM:\SOFTWARE' to avoid ArgumentException
* Removed `!` for readability
* Fixed formatting
=> Fix the Example 4 of Get-PSDrive

reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Document new Encoding property on  BasicHtmlWebResponseObject and HtmlWebResponseObject response objects returned by Invoke-WebRequest
See issue https://github.com/PowerShell/PowerShell/issues/3267 and PR https://github.com/PowerShell/PowerShell/pull/4338
- [X ] Impacts 6 document
=> Document new Encoding property on  BasicHtmlWebResponseObject and HtmlWebResponseObject

.gitignore
The `.gitignore` was still using the old `out_maml` and `out_cab` folders, so `maml` and `updateablehelp` were showing up as untracked files whenever I ran `appveyor.ps1` locally.
=> Fix .gitingore for maml and updateablehelp

reference/6/Pester/Context.md, reference/6/Pester/Describe.md, reference/6/Pester/InModuleScope.md, reference/6/Pester/It.md, reference/6/Pester/Mock.md
=> fixing incorrect related links format in cmdlets reference

reference/docfx.json
=> updating reference docfx for bread crumb

dsc/pullServer.md
The items ordered lists after code blocks were restarting their numbering at 1 when they were intended to be part of the preceding list.  The preview on github showed the correct numbers (allowing for manual renumbering) before the modification, but the production site https://docs.microsoft.com/en-us/powershell/dsc/pullserver shows them restarting at 1.
Actual changes are:
- Indenting the code blocks to allow numbering to continue
- Removing manual renumbering (setting items after code blocks to 1.)
- lower-casing a "Pull Server" occurrence
=> Fixing markdown list continuation

reference/3.0/Microsoft.PowerShell.Utility/Write-Error.md, reference/4.0/Microsoft.PowerShell.Utility/Write-Error.md, reference/5.0/Microsoft.PowerShell.Utility/Write-Error.md, reference/5.1/Microsoft.PowerShell.Utility/Write-Error.md, reference/6/Microsoft.PowerShell.Utility/Write-Error.md
* Fixed url, formatting, and minor differences in wording
* Removed meaningless InformationAction/InformationVariable containing the link
=> Fix link for ErrorCategory Enumeration

reference/4.0/Microsoft.PowerShell.Core/Get-Module.md, reference/5.0/Microsoft.PowerShell.Core/Get-Command.md, reference/5.0/Microsoft.PowerShell.Core/Get-Module.md, reference/5.0/Microsoft.PowerShell.Core/Save-Help.md, reference/5.0/Microsoft.PowerShell.Core/Update-Help.md, reference/5.0/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/5.0/Microsoft.PowerShell.Utility/Import-PSSession.md, reference/5.1/Microsoft.PowerShell.Core/Get-Command.md, reference/5.1/Microsoft.PowerShell.Core/Get-Module.md, reference/5.1/Microsoft.PowerShell.Core/Save-Help.md, reference/5.1/Microsoft.PowerShell.Core/Update-Help.md, reference/5.1/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/5.1/Microsoft.PowerShell.Utility/Import-PSSession.md, reference/6/Microsoft.PowerShell.Core/Get-Command.md, reference/6/Microsoft.PowerShell.Core/Get-Module.md, reference/6/Microsoft.PowerShell.Core/Save-Help.md, reference/6/Microsoft.PowerShell.Core/Update-Help.md, reference/6/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/6/Microsoft.PowerShell.Utility/Import-PSSession.md, wmf/5.1/scenarios-features.md
=> Fix link for ModuleSpecification Constructor

dsc/pullServer.md
After indenting the code blocks to have the numbering continue on the production site (https://docs.microsoft.com/en-us/powershell/dsc/pullserver) the code block got broken into two pieces.  It looks fine on github but not the production site.  I added spaces to align the empty line with the indentation of the surrounding code block to join them together.
=> Joining configuration code blocks

reference/docs-conceptual/getting-started/cookbooks/Viewing-Object-Structure--Get-Member-.md
A missing space betwen the cmdlet name and the paramater name - fixed to reduce confusion.
=> Fixing minor typo on "Viewing Object Structure (Get-Member) "

reference/5.1/PowershellGet/Update-ModuleManifest.md, reference/6/PowerShellGet/Update-ModuleManifest.md
* \``` -> ```powershell
* Removed 'PS C:\\> '
* cmdlet, \*\*cmdlet\*\* -> \`cmdlet\`
* Fixed link for about_Updatable_Help and "Supporting Updatable Help"
=> Fix code style of Update-ModuleManifest

reference/docs-conceptual/getting-started/cookbooks/Getting-WMI-Objects--Get-WmiObject-.md
Two small errors:
1. The results of one command show as two badly line-broken lines - this is fixed with this RP.
2. In the final example, there was a typo in the Command
=> Update Getting WMI objects

dsc/dsc_roadmap.md
This document provides a placeholder for a living roadmap for DSC that we will keep up to date as we flush out our plans for DSC. I discussed this with Eric and Zach. 
We will be linking to this from a blog post that we are putting out today.
=> Placeholder and rough outline for DSC Roadmap

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
closes  #1650
Support for `MultipartFormDataConent` objects submitted to the `-Body` parameter of `Invoke-WebRequest` and `Invoke-RestMethod` was added in PowerShell/PowerShell#4782. This documents the new feature as well as its impact on the `-Headers`, `-ContentType`, and `-WebSession` parameters.
An example was added to `Invoke-WebRequest`, but not `Invoke-RestMethod` because most use-cases for this feature will return HTML and not an objet parsable by `Invoke-RestMethod`.
There were also some minor formatting issues with the `Invoke-WebRequest` document that was resulting in a large portion of the document to be treated as a code block. This appears to only affect the 6.0 version of the document.
Reason(s) for not updating …
=> Document multipart/form-data support for 6.0 Web Cmdlets

reference/3.0/Microsoft.PowerShell.Management/Get-HotFix.md, reference/4.0/Microsoft.PowerShell.Management/Get-HotFix.md, reference/5.0/Microsoft.PowerShell.Management/Get-HotFix.md, reference/5.1/Microsoft.PowerShell.Management/Get-HotFix.md
=> Fix link for Win32_QuickFixEngineering class

reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md, reference/6/Microsoft.PowerShell.Core/About/about_pipelines.md
Fixed the following texts. They are generated by `Get-Help -Full` or `Get-Help -Parameter`  but mistakenly out of code blocks.
> -Name <String[]>
> Specifies the service names for the service to be started.
> The parameter name is optional. You can use -Name or its alias,
> -ServiceName, or you can omit the parameter name.
> -InputObject <ServiceController[]>
> Specifies ServiceController objects representing the services to be started. Enter
> a variable that contains the objects or type a command or expression that gets the
> objects.
> -Destination <String>
> Specifies the path to the destination location.
And also fixed the related things as follows:
* "Accepts pipeline input" -> "Accept pipeline input?"
* Parameter -> \*\*Parameter\*\*
* Remove unnecessary phrase "For example," …
=> Fix about_Pipelines body texts that should be within a code block

reference/3.0/Microsoft.PowerShell.Core/About/about_Remote.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Remote.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Remote.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote.md
x `$.Parameters.Keys`
o `$_.Parameters.Keys`
```powershell
PS> Get-Command | where { $.Parameters.Keys -contains "ComputerName" -and $.Parameters.Keys -NotContains "Session"}
$.Parameters.Keys : The term '$.Parameters.Keys' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:23
+ Get-Command | where { $.Parameters.Keys -contains "ComputerName" -and ...
+                       ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: ($.Parameters.Keys:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
=> Fix example of about_Remote.md (missing '_')

reference/6/Microsoft.PowerShell.Utility/Sort-Object.md
=> Add Top and Bottom parameters to cmdlet help.

reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
=> Fix ValidateLength code block in about_Functions_Advanced_Parameters.md

reference/5.0/Microsoft.PowerShell.Core/Add-History.md, reference/5.1/Microsoft.PowerShell.Core/Add-History.md, reference/6/Microsoft.PowerShell.Core/Add-History.md
Fix typo in Add-History documentation
=> Fix typo in Add-History documentation

gallery/psget/repository/psget_register-psrepository.md
Minor change. Register-PSRepository parameter "InstallationPolicy" has validate set "Trusted;Untrusted". Argument was "-Trusted" in example which does not work.
=> Changed argument for parameter InstallationPolicy

reference/3.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
Fixed header level, table, escape character, link, etc.
=> Fix formatting: about_Regular_Expressions.md

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
Change from: 
The default is the current folder.
Change to:
WorkingDirectory specifies the working directory for the new process.
=> Updating WorkingDirectory path details

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
Documents PowerShell/PowerShell#4888 wherein a new `-ResponseHeadersVariable` parameter was added to `Invoke-RestMethod`.
=> Add ResponseHeadersVariable Parameter Documentation

reference/3.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
The example does not work because of a missing double quotation mark:
x `$days = Sunday", ...`
o `$days = "Sunday", ...`
=> Fix $NULL as a placeholder example in about_Automatic_Variables.md

reference/3.0/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/4.0/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/5.0/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/5.1/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/6/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md
Added line break to `LocalMachine   RemoteSigned PS C:\> Get-ExecutionPolicy`.
And fixed some formatting issues.
=> Fix example 3 in Get-ExecutionPolicy.md

wmf/5.0/psget_modulesxsinstall.md
Examples had PS1 prompts with unescaped characters.  Fixed formatting to be consistent with [other articles](https://docs.microsoft.com/en-us/powershell/gallery/psget/module/psget_install-module#side-by-side-version-support-on-powershell-50-or-newer).
=> Remove misformatted PS1 prompts from examples

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
In #1696 I forgot to update the syntax to include the new parameter.
=> Add -ResponseHeadersVariable Parameter to Invoke-RestMethod Syntax

reference/3.0/Microsoft.PowerShell.Core/Invoke-History.md, reference/4.0/Microsoft.PowerShell.Core/Invoke-History.md, reference/5.0/Microsoft.PowerShell.Core/Invoke-History.md, reference/5.1/Microsoft.PowerShell.Core/Invoke-History.md, reference/6/Microsoft.PowerShell.Core/Invoke-History.md
Fixes #1708. Previously this line of code would throw an error stating that Invoke-History cannot process multiple history commands and that you can only run a single command by using Invoke-History.
=> Edit Invoke-History Example 5

reference/6/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md, reference/6/Microsoft.PowerShell.Utility/Get-Verb.md, reference/6/Microsoft.WSMan.Management/Microsoft.WSMan.Management.md, reference/6/PSReadLine/PSReadLine.md
The casing has to be consistent with the module name since this is used to construct the help URI.
Some external help filenames were incorrect. Fixed them.
=> Fixed casing of module landing pages and external help file names

reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md
Update-FormatData cmdlet does not have PrependData parameter.
=> Fix PrependData -> PrependPath in about_Format.ps1xml.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md
The description says "In the following example, wildcard characters are used", but the example does not use any wildcard characters.
=> Add wildcard characters to the examples in about_Wildcards.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions.md
* `$` -> `$_` (to avoid error)
* `C:\` -> `$HOME` (it is likely that users can not find many small files in `C:\`)
=> Fix examples in about_Functions.md (missing `_`)

reference/6/Microsoft.PowerShell.Management/Join-Path.md
=> Add AdditionalChildPath parameter to Join-Path.

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions.md
Removed `function` keyword to avoid exception:
```powershell
PS> function Get-SmallFiles -Size 50
At line:1 char:24
+ function Get-SmallFiles -Size 50
+                        ~
Missing function body in function declaration.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingFunctionBody
```
=> Fix examples in about_Functions.md (unnecessary `function`)

reference/3.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
Removed `(get-date).date - 1`, which causes error:
```powershell
PS> (get-date).date - 1
Multiple ambiguous overloads found for "op_Subtraction" and the argument count: "2".
At line:1 char:1
+ (get-date).date - 1
+ ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodException
+ FullyQualifiedErrorId : MethodCountCouldNotFindBest
```
Instead of that, add a negative number example `(Get-Date).AddDays(-1)`
=> Update examples in about_Arithmetic_Operators.md (`-` operator)

reference/3.0/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
Markdown:
> This example assigns 0 to the $a variable if the value of $b is less than
> 0. It assigns the value of $b to $a if the value of $b is not less than
> zero.
[Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_assignment_operators?view=powershell-6):
> This example assigns 0 to the $a variable if the value of $b is less than
> 
>   1. It assigns the value of $b to $a if the value of $b is not less than zero.
Because the beginning characters "0. " stand for numbered list.
=> Fix the beginning characters "0. " in about_Assignment_Operators.md

reference/3.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/6/Microsoft.PowerShell.Core/About/about_CommonParameters.md
Added "infa" and "iv". And fixed formatting.
=> Add aliases to CommonParameters list

reference/6/Microsoft.PowerShell.Utility/Out-String.md
Changes made to document functionality added via this [PR](https://github.com/raghav710/PowerShell/commit/cfd5ebd3afe6bf6a1d3aa72ae2b456bb75911cc5) 
* Updated syntax to list the two parameter sets
* Added examples to clarify the behaviour of NoNewLine
* Added parameter set info for -Stream switch
* added details about the -NoNewLine (adapted from Out-File description of the same)
=> Add docs and examples for NoNewLine switch

reference/3.0/Microsoft.PowerShell.Core/About/about_Eventlogs.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Eventlogs.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Eventlogs.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Eventlogs.md, reference/6/Microsoft.PowerShell.Core/About/about_Eventlogs.md
`Get-WmiObject -List | where {$_.Name -like "win32event"}` returns nothing.
Fixed it as follows:
```powershell
PS> Get-WmiObject -List | where Name -Like "win32*event*"
NameSpace: ROOT\cimv2
Name                                Methods              Properties
----                                -------              ----------
Win32_DeviceChangeEvent             {}                   {EventType, SECURITY_DESCRIPTOR, TIME...
Win32_SystemConfigurationChangeE... {}                   {EventType, SECURITY_DESCRIPTOR, TIME...
Win32_VolumeChangeEvent             {}                   {DriveName, EventType, SECURITY_DESCR...
Win32_PowerManagementEvent          {}                   {EventType, OEMEventCode, SECURITY_DE...
Win32_ComputerSystemEvent           {}                   {MachineName, …
```
=> Fix example in about_Eventlogs.md (wildcard)

reference/docs-conceptual/getting-started/cookbooks/Managing-Current-Location.md
\<pre\> blocks are not recognized as code blocks in the [Microsoft Docs](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/managing-current-location). (no "Copy" button)
=> Replace <pre> tag with code fence in Managing-Current-Location.md

reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md, reference/6/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
Removed `)` to avoid ParserError.
=> Fix the Example 1 in Register-ArgumentCompleter.md (unnecessary `)`)

reference/3.0/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md
PR #1781 #1782 #1783 #1784 #1785 have issues as follows:
* Broke table appearance (See [Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-6))
* Applied list style to "See Also" links.
It is different from many other "See Also" links (e.g. about_Profiles.md)
* Restored the issue fixed by #1733
I have rolled back them to the previous version.
=> Undo PR #1781-#1785: about_Wildcards.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
PR #1781 #1782 #1783 #1784 #1785 have issues as follows:
* Removed backticks from cmdlet (e.g. \`Get-Member\` -> Get-Member)
That does not match the [style guide](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md)
* Removed asterisks from parameter (e.g. \*\*Scope\*\* -> Scope)
That does not match the [style guide](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md)
* Added unnecessary `\`
* Changed heading levels 2 to 3 and hid them in "In this article", the right side TOC section of docs.microsoft.com
* Changed "https" to "http"
* Uncapitalized links (e.g. about_preference_variables)
* Applied list style to "See Also" links.
It is different from many other "See Also" links (e.g. about_Profiles.md)
I have rolled back them to the previous version. …
=> Undo PR #1781-#1785: about_Environment_Variables.md

dsc/lnxGettingStarted.md
As per the release notes https://github.com/Microsoft/PowerShell-DSC-for-Linux/releases Debian 8 and Ubuntu 16.04LTS are supported.
=> updated supported versions for Debian and Ubuntu

reference/6/Microsoft.PowerShell.Management/Get-Service.md, reference/6/Microsoft.PowerShell.Management/New-Service.md, reference/6/Microsoft.PowerShell.Management/Remove-Service.md, reference/6/Microsoft.PowerShell.Management/Restart-Service.md, reference/6/Microsoft.PowerShell.Management/Resume-Service.md, reference/6/Microsoft.PowerShell.Management/Set-Service.md, reference/6/Microsoft.PowerShell.Management/Start-Service.md, reference/6/Microsoft.PowerShell.Management/Stop-Service.md, reference/6/Microsoft.PowerShell.Management/Suspend-Service.md
Added documentation for `Remove-Service` which was added in PowerShell/PowerShell#4858
I'm guessing properties like `online version` needs to be changed, but I'm not sure on how/what.
The `Remove-Service` command was added in v6.0.0-beta.8
- [ x ] Impacts 6 document
- [ x ] The documented feature was introduced in version (v6.0.0-beta.8) of PowerShell
=> Remove-Service documentation added.

STYLE.md
#1288 and also forefronting #1806
=> Updating style guide to address #1228

reference/6/Microsoft.PowerShell.Management/Get-Service.md, reference/6/Microsoft.PowerShell.Management/Set-Service.md
Removed `ComputerName` variable from documentation of services. Reference pull request from the PowerShell repo: PowerShell/PowerShell#5094
- [ X ] Impacts 6 document
- [ X ] The documented feature was introduced in version (v6.0.0-beta.9) of PowerShell
=> Removed computername from service commands

reference/docs-conceptual/core-powershell/console/Using-Tab-Expansion.md
Removed 'Windows' from 'Windows PowerShell' for 6.0
=> Removed 'Windows' from 'Windows PowerShell' for 6.0

reference/docs-conceptual/core-powershell/console/PowerShell.exe-Command-Line-Help.md
Removed 'Windows' from 'Windows PowerShell' for 6.0 documentation as it is now just PowerShell.
=> Remove 'Windows' from PowerShell for 6.0 doc

reference/5.1/PSScheduledJob/Get-ScheduledJobOption.md
Four times in the document it said Get-ScheduledJobOptions with an S instead of Get-ScheduledJobOption.  I corrected the mistake in all four cases.
=> Incorrect cmdlet name on Get-ScheduledJobOption documentation

reference/3.0/Microsoft.PowerShell.Utility/Format-List.md, reference/4.0/Microsoft.PowerShell.Utility/Format-List.md, reference/5.0/Microsoft.PowerShell.Utility/Format-List.md, reference/5.1/Microsoft.PowerShell.Utility/Format-List.md, reference/6/Microsoft.PowerShell.Utility/Format-List.md
The example is a `-DisplayError` parameter example. But it uses `-ShowError` parameter.
=> Fix the example of `Format-List -DisplayError`

reference/3.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Fixing Issue #1406 - PowerShell -Like operator needs to mention "?" wildcard & use 
Fixed examples and reformatted about_Comparison_Operators.md for build processing.
=> fixing issue 1406

reference/3.0/Microsoft.PowerShell.Core/Where-Object.md, reference/4.0/Microsoft.PowerShell.Core/Where-Object.md, reference/5.0/Microsoft.PowerShell.Core/Where-Object.md, reference/5.1/Microsoft.PowerShell.Core/Where-Object.md, reference/6/Microsoft.PowerShell.Core/Where-Object.md
`-IsNot [System.String]` does not filter anything:
```powershell
PS> (Get-Process | where StartTime -IsNot [System.String] | Measure-Object).Count
123
PS> (Get-Process | Measure-Object).Count
123
```
As with the example of `-Is`, `[DateTime]` should be used instead of `[System.String]`:
```powershell
PS> (Get-Process | where StartTime -IsNot [DateTime] | Measure-Object).Count
92
PS> (Get-Process | where StartTime -Is [DateTime] | Measure-Object).Count
31
PS> (Get-Process | Measure-Object).Count
123
```
=> Update the example of `Where-Object -IsNot`

reference/3.0/Microsoft.PowerShell.Utility/Group-Object.md, reference/4.0/Microsoft.PowerShell.Utility/Group-Object.md, reference/5.0/Microsoft.PowerShell.Utility/Group-Object.md, reference/5.1/Microsoft.PowerShell.Utility/Group-Object.md, reference/6/Microsoft.PowerShell.Utility/Group-Object.md
The second command should use `-Property PriorityClass` instead of `-Property company`.
Because the first command uses `-Property PriorityClass` and the description says:
> The second command is identical to the first, except that it uses the *NoElement* parameter
=> Update Example 5 in Group-Object.md

reference/3.0/Microsoft.PowerShell.Utility/Format-Table.md, reference/4.0/Microsoft.PowerShell.Utility/Format-Table.md, reference/5.0/Microsoft.PowerShell.Utility/Format-Table.md, reference/5.1/Microsoft.PowerShell.Utility/Format-Table.md, reference/6/Microsoft.PowerShell.Utility/Format-Table.md
The example is a `-DisplayError` parameter example. But it uses `-ShowError` parameter.
=> Fix the example of `Format-Table -DisplayError`

reference/3.0/Microsoft.PowerShell.Utility/Format-Wide.md, reference/4.0/Microsoft.PowerShell.Utility/Format-Wide.md, reference/5.0/Microsoft.PowerShell.Utility/Format-Wide.md, reference/5.1/Microsoft.PowerShell.Utility/Format-Wide.md, reference/6/Microsoft.PowerShell.Utility/Format-Wide.md
The example is a `-DisplayError` parameter example. But it uses `-ShowError` parameter.
Additionally, it throws exception because its `-Property` parameter accepts an Object, not an array:
```powershell
PS> Get-Date | Format-Wide DayOfWeek,{ $_ / $null } -ShowError
Format-Wide : Cannot convert System.Object[] to one of the following types {System.String,
System.Management.Automation.ScriptBlock}.
At line:1 char:12
+ Get-Date | Format-Wide DayOfWeek,{ $_ / $null } -ShowError
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Format-Wide], NotSupportedException
+ FullyQualifiedErrorId : DictionaryKeyUnknownType,Microsoft.PowerShell.Commands.FormatWideCommand
```
=> Fix the example of `Format-Wide -DisplayError`

reference/3.0/Microsoft.PowerShell.Utility/Format-Custom.md, reference/4.0/Microsoft.PowerShell.Utility/Format-Custom.md, reference/5.0/Microsoft.PowerShell.Utility/Format-Custom.md, reference/5.1/Microsoft.PowerShell.Utility/Format-Custom.md, reference/6/Microsoft.PowerShell.Utility/Format-Custom.md
The example is a -DisplayError parameter example. But it uses -ShowError parameter.
=> Fix the example of `Format-Custom -DisplayError`

reference/3.0/Microsoft.PowerShell.Utility/Format-Wide.md, reference/4.0/Microsoft.PowerShell.Utility/Format-Wide.md, reference/5.0/Microsoft.PowerShell.Utility/Format-Wide.md, reference/5.1/Microsoft.PowerShell.Utility/Format-Wide.md, reference/6/Microsoft.PowerShell.Utility/Format-Wide.md
The example throws exception because its `-Property` parameter accepts an Object, not an array:
```powershell
PS> Get-Date | Format-Wide DayOfWeek,{ $_ / $null } -ShowError
Format-Wide : Cannot convert System.Object[] to one of the following types {System.String, System.Management.Automation.ScriptBlock}.
At line:1 char:12
+ Get-Date | Format-Wide DayOfWeek,{ $_ / $null } -ShowError
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Format-Wide], NotSupportedException
+ FullyQualifiedErrorId : DictionaryKeyUnknownType,Microsoft.PowerShell.Commands.FormatWideCommand
```
=> Fix the example of `Format-Wide -ShowError`

reference/5.1/PowershellGet/Test-ScriptFileInfo.md, reference/6/PowerShellGet/Test-ScriptFileInfo.md
=> Fixed Test-ScriptFileInfo example

reference/3.0/Microsoft.PowerShell.Utility/Write-Progress.md, reference/4.0/Microsoft.PowerShell.Utility/Write-Progress.md, reference/5.0/Microsoft.PowerShell.Utility/Write-Progress.md, reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md, reference/6/Microsoft.PowerShell.Utility/Write-Progress.md
Removing extra space in examples using -PercentComplete parameter. fixing issue #1769 
=> fixing issue 1769

reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
1. Replaced variable names with PascalCase convention and for consistency
2. Removed directory information [c:\] in the examples
3. Put powershell keyword for formatting examples
4. Replaced Invoke-RestMethod with Invoke-WebRequest in the Body example, added method Post
5. Removed InformationAction and InformationVariable parameters, which were mistakenly a copy of Body, included already in CommonVariables part
=> Formatting, example fix for Body parameter

reference/3.0/Microsoft.PowerShell.Core/Resume-Job.md, reference/4.0/Microsoft.PowerShell.Core/Resume-Job.md, reference/5.0/Microsoft.PowerShell.Core/Resume-Job.md, reference/5.1/Microsoft.PowerShell.Core/Resume-Job.md
Example number '4' is duplicated.
=> Fix example numbers in Resume-Job.md

dsc/separatingEnvData.md
=> Fixes typo $WebSiteName in separatingEnvData.md

dsc/configurations.md
=> Updates configurations.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Transactions.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Transactions.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Transactions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Transactions.md, reference/6/Microsoft.PowerShell.Core/About/about_Transactions.md
Example number '7' is duplicated.
=> Fix example numbers in about_Transactions.md

reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
Add documentation of new `-AsHashTable` switch for `ConvertFrom-Json` and document the behaviour in case of duplicate strings. The switch was introduced by [PR 5043](https://github.com/PowerShell/PowerShell/pull/5043) in version 6.0
=> Add documentation of new -AsHashtable switch for ConvertFrom-Json introduced by PR #5043

reference/6/Microsoft.PowerShell.Utility/ConvertTo-Html.md
Example number '10' is duplicated.
=> Fix example number in ConvertTo-Html.html

reference/3.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/4.0/Microsoft.PowerShell.Utility/Get-Member.md
Example 4 and 5 in Get-Member.md v3.0 and v4.0 are almost the same. They should be merged like v5.0.
=> Merge Example 4 and 5 in Get-Member.md

reference/6/Microsoft.PowerShell.Core/About/About_Using.md, reference/6/Microsoft.PowerShell.Utility/Get-FileHash.md
MACTripleDES and RIPEMD160 are no longer supported in v6.0. See [GetHash.cs](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs#L199-L203) and [#3024 in PowerShell](https://github.com/PowerShell/PowerShell/pull/3024).
=> Remove hash algorithms unsupported in v6.0

reference/6/Microsoft.PowerShell.Utility/Get-Verb.md
Since v6.0, `Get-Verb` returns  not MemberDefinition but VerbInfo that has Verb and Group properties. See [GetVerbCommand.cs](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetVerbCommand.cs#L14-L15) and [VerbInfo](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/System.Management.Automation/utils/Verbs.cs#L1133-L1166).
=> Update outputs of Get-Verb v6.0

reference/6/Microsoft.PowerShell.Utility/ConvertTo-Html.md
=> Fix typo in ConvertTo-Html.md (UTF-x)

reference/6/Microsoft.PowerShell.Management/Get-Service.md
* Fixed "False" -> "True" (`DisplayName`, `Exclude`, `Include`, and `Name`)
* Removed `InformationAction` and `InformationVariable`
=> Fix "Accept wildcard characters" in Get-Service.md v6

dsc/windowsfeatureResource.md
Minor edit.  Update Get-WindowsFeature cmdlet HyperLink to https://technet.microsoft.com/library/jj205469(v=wps.630).aspx
=> Fixed Get-WindowsFeature cmdlet HyperLink

reference/3.0/Microsoft.PowerShell.Management/Get-Process.md, reference/4.0/Microsoft.PowerShell.Management/Get-Process.md, reference/5.0/Microsoft.PowerShell.Management/Get-Process.md, reference/5.1/Microsoft.PowerShell.Management/Get-Process.md, reference/6/Microsoft.PowerShell.Management/Get-Process.md
There are two ways to find the owner of a process:
1. `Get-Process -IncludeUserName`
This can be used in v4.0, 5.0, 5.1, and 6.0.
This cannot be used in v3.0 because **IncludeUserName** parameter was [introduced in v4.0](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-windows-powershell-50?view=powershell-5.1#new-features-in-windows-powershell-40).
2. `Get-WmiObject Win32_Process` and `GetOwner()`
This can be used in v3.0, 4.0, 5.0, and 5.1.
This cannot be used in v6.0 because `Get-WmiObject` is not supported in v6.0.
=> Update Example 8 in Get-Process.md (find the owner of a process)

dsc/secureMOF.md
The example where we import the PFX on the target node should import the cert into Personal store and not root.
=> updated localmachine\Root to LocalMachine\My

reference/3.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md, reference/4.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md, reference/5.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md, reference/5.1/Microsoft.PowerShell.Core/Functions/Get-Verb.md, reference/6/Microsoft.PowerShell.Utility/Get-Verb.md
* v3.0 - v5.1
Overwrote example 3 with comparison statement introduced in v3.0
* v6.0
Overwrote example 3 with **Group** parameter [introduced in v6.0](https://github.com/PowerShell/PowerShell/pull/2789)
Added description about **Group** parameter
=> Update Group property example in Get-Verb.md

reference/3.0/Microsoft.PowerShell.Management/Get-Process.md, reference/4.0/Microsoft.PowerShell.Management/Get-Process.md, reference/5.0/Microsoft.PowerShell.Management/Get-Process.md, reference/5.1/Microsoft.PowerShell.Management/Get-Process.md, reference/6/Microsoft.PowerShell.Management/Get-Process.md
* powershell -> pwsh (only v6.0)
=> Update Example 9 in Get-Process.md

reference/3.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md, reference/4.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md, reference/5.0/Microsoft.PowerShell.Core/Functions/Get-Verb.md, reference/5.1/Microsoft.PowerShell.Core/Functions/Get-Verb.md, reference/6/Microsoft.PowerShell.Utility/Get-Verb.md
* Example 4
Replaced "MyModule" with "Microsoft.PowerShell.Utility", which has unapproved verb cmdlets.
* Example 5
Removed. Because it is similar to Example 4 and somewhat verbose.
=> Update unapproved verbs examples in Get-Verb.md

reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md
It was highlighting as string in the documentation, I was trying to remove all the extra space.
=> Removing extra space in the Example 5A script

reference/3.0/Microsoft.PowerShell.Utility/Get-Random.md, reference/4.0/Microsoft.PowerShell.Utility/Get-Random.md, reference/5.0/Microsoft.PowerShell.Utility/Get-Random.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md, reference/6/Microsoft.PowerShell.Utility/Get-Random.md
* [**Maximum** parameter's position is 0](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs#L204-L205)
* [**InputObject** parameter's position is 0](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs#L272-L275)
=> Fix parameter's position in Get-Random.md

reference/3.0/Microsoft.PowerShell.Utility/Measure-Command.md, reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md, reference/5.0/Microsoft.PowerShell.Utility/Measure-Command.md, reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md, reference/6/Microsoft.PowerShell.Utility/Measure-Command.md
* [Expression parameter's position is 0](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/TimeExpressionCommand.cs#L35-L36)
=> Fix parameter's position in Measure-Command.md

reference/3.0/Microsoft.PowerShell.Utility/Trace-Command.md, reference/4.0/Microsoft.PowerShell.Utility/Trace-Command.md, reference/5.0/Microsoft.PowerShell.Utility/Trace-Command.md, reference/5.1/Microsoft.PowerShell.Utility/Trace-Command.md, reference/6/Microsoft.PowerShell.Utility/Trace-Command.md
* [Name parameter's position is 0](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs#L37-L38)
* [Expression parameter's position is 1](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs#L62-L63)
* [Command parameter's position is 1](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs#L69-L70)
* [Option parameter's position is 2](https://github.com/PowerShell/PowerShell/blob/v6.0.0-rc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs#L48-L49)
* Removed …
=> Fix parameter's position in Trace-Command.md

dsc/configurations.md
On line 74, it says...
"The last line of the example containing only the name of the configuration, calls the configuration."
This change actually makes that call.
=> Actually call the configuration in the example

reference/docs-conceptual/getting-started/understanding-concepts-reference.md
I'm not quite sure what this means, but it certainly looks terrible on docs.microsoft.com when it's malformed.
(To be perfectly honest, I only managed to even figure out it's called "YAML metadata" by peeking at the DOM of github's HTML.)
=> Fix YAML metadata on "Understanding Concepts"

reference/3.0/Microsoft.PowerShell.Management/Join-Path.md, reference/4.0/Microsoft.PowerShell.Management/Join-Path.md, reference/5.0/Microsoft.PowerShell.Management/Join-Path.md, reference/5.1/Microsoft.PowerShell.Management/Join-Path.md, reference/6/Microsoft.PowerShell.Management/Join-Path.md
* Path parameter's position is 0
* ChildPath parameter's position is 1
* AdditionalChildPath parameter's position is 2 in v6.0
=> Fix parameter's position in Join-Path.md

dsc/bootstrapDsc.md
E:\Windows\Sytem32 sould be E:\Windows\System32
=> typo correction on line 85

reference/3.0/Microsoft.PowerShell.Utility/Get-TraceSource.md, reference/4.0/Microsoft.PowerShell.Utility/Get-TraceSource.md, reference/6/Microsoft.PowerShell.Utility/Get-TraceSource.md
* Name parameter's position is 0
=> Fix parameter's position in Get-TraceSource.md

reference/3.0/Microsoft.PowerShell.Management/Get-Process.md, reference/4.0/Microsoft.PowerShell.Management/Get-Process.md, reference/5.0/Microsoft.PowerShell.Management/Get-Process.md, reference/5.1/Microsoft.PowerShell.Management/Get-Process.md, reference/6/Microsoft.PowerShell.Management/Get-Process.md
* `Powershell` -> `pwsh` (v6.0 only)
* Removed **ComputerName** parameter (v6.0 only. See PowerShell/PowerShell#4960)
* `if ($_.CPU -ne $())` -> `if ($_.CPU)`
* Fixed formatting
=> Update Example 5 in Get-Process.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Fixing problem reported in PR #1921. Removed backslash escapes from within code blocks. 
=> fixing backlashes reported in PR1921

reference/3.0/Microsoft.PowerShell.Core/About/about_Properties.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Properties.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Properties.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Properties.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md, reference/6/Microsoft.PowerShell.Core/About/about_Properties.md, reference/6/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote_FAQ.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md
reformatting About_* for 80 columns - part 5
Reformatted files to fit in 80 columns per Issue #1806. No other changes to the content except where noted.
- about_Properties.md
- about_Redirection.md
- about_Regular_Expressions.md
- about_Remote_FAQ.md
- about_Remote_Jobs.md
=> reformatting About_* for 80 columns - part 5

reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md, reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md, reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md, reference/6/Microsoft.PowerShell.Utility/Export-Csv.md
The examples were confusing because of the way the output was formatted. Fixed formatting to be clearer about the contents of the CSV files.
See issue #808 for more info.
=> Fixed formatting of output per issue #808

reference/3.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/4.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/5.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Xml.md
* InputObject parameter's position is 0
=> Fix parameter's position in ConvertTo-Xml.md

reference/6/Microsoft.PowerShell.Management/Get-Process.md
`Get-Process -ComputerName` parameter is not supported since v6.0. See PowerShell/PowerShell#4960
=> Remove descriptions about ComputerName parameter in Get-Process.md v6.0

reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
=> Line 192  Single Quote Breaks Example

reference/3.0/Microsoft.PowerShell.Utility/Get-Alias.md, reference/4.0/Microsoft.PowerShell.Utility/Get-Alias.md, reference/5.0/Microsoft.PowerShell.Utility/Get-Alias.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Alias.md, reference/6/Microsoft.PowerShell.Utility/Get-Alias.md
`-Exclude Get-*` is ineffective because there are no aliases that begin with `Get-`.
=> Update Example 2 in Get-Alias.md (ineffective Exclude)

reference/3.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/4.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/5.0/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Xml.md
Fixed the odd bold ("**") marks as follows:
> ... in a file**.
> ConvertTo-XML** returns the XML, ...
And also fixed the formatting for the DESCRIPTION section.
=> Fix formatting: DESCRIPTION section in ConvertTo-Xml.md

reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md, reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md, reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md, reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
* InputObject parameter's position is 0
* Delimiter parameter's position is 1
=> Fix parameter's position in ConvertFrom-Csv.md

reference/3.0/Microsoft.PowerShell.Utility/Add-Member.md, reference/4.0/Microsoft.PowerShell.Utility/Add-Member.md, reference/5.0/Microsoft.PowerShell.Utility/Add-Member.md, reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md, reference/6/Microsoft.PowerShell.Utility/Add-Member.md
* MemberType: 0
* Name: 1
* Value: 2
* SecondValue: 3
* NotePropertyName: 0
* NotePropertyValue: 1
* NotePropertyMembers: 0
* Updated "Parameter Sets" names in v4.0
=> Fix parameter's position in Add-Member.md

reference/3.0/Microsoft.PowerShell.Utility/Select-Object.md, reference/4.0/Microsoft.PowerShell.Utility/Select-Object.md, reference/5.0/Microsoft.PowerShell.Utility/Select-Object.md, reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md, reference/6/Microsoft.PowerShell.Utility/Select-Object.md
* Property parameter's position is 0
=> Fix parameter's position in Select-Object.md

reference/3.0/Microsoft.PowerShell.Utility/Select-Xml.md, reference/4.0/Microsoft.PowerShell.Utility/Select-Xml.md, reference/5.0/Microsoft.PowerShell.Utility/Select-Xml.md, reference/5.1/Microsoft.PowerShell.Utility/Select-Xml.md, reference/6/Microsoft.PowerShell.Utility/Select-Xml.md
=> Fix parameter's position in Select-Xml.md

reference/3.0/Microsoft.PowerShell.Utility/Get-Alias.md, reference/4.0/Microsoft.PowerShell.Utility/Get-Alias.md, reference/5.0/Microsoft.PowerShell.Utility/Get-Alias.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Alias.md, reference/6/Microsoft.PowerShell.Utility/Get-Alias.md
* Position: 0
* Default value: All aliases
* Accept wildcard characters: True
* Fixed minor differences in formatting and wording
And also removed InformationAction/InformationVariable in v6.0.
=> Fix Get-Alias -Name parameter

CONTRIBUTING.md, contributing/FORAMTTING-CODE.md, contributing/STYLE.md
This article addresses the use of the PowerShell prompt and the proper use of language labels on code fences.
=> Updated Style Guide with article about formatting code samples

dsc/docfx.json, gallery/docfx.json, jea/docfx.json, reference/docfx.json, reference/docs-conceptual/docfx.json, wmf/docfx.json
Updating author information in metadata and removing invalid "wmf" value. The invalid value is causing problems in the SkyEye reports.
=> updating metadata tags in docfx.json

reference/3.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/4.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/5.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Member.md, reference/6/Microsoft.PowerShell.Utility/Get-Member.md
=> Fix parameter's position in Get-Member.md

gallery/psgallery/psgallery_items_tab.md
* Added description about [the new prerelease feature](https://blogs.msdn.microsoft.com/powershell/2017/12/05/prerelease-versioning-added-to-powershellget-and-powershell-gallery/)
* Fixed formatting of header, list, etc.
* Fixed some wording
=> Update PSGallery "Items Tab" (for the new prerelease feature)

reference/3.0/Microsoft.PowerShell.Utility/Group-Object.md, reference/4.0/Microsoft.PowerShell.Utility/Group-Object.md, reference/5.0/Microsoft.PowerShell.Utility/Group-Object.md, reference/5.1/Microsoft.PowerShell.Utility/Group-Object.md, reference/6/Microsoft.PowerShell.Utility/Group-Object.md
=> Fix parameter's position in Group-Object.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
=> Fix hex values in about_Arithmetic_Operators.md

reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md, reference/5.0/Microsoft.PowerShell.Utility/Get-FileHash.md, reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md, reference/6/Microsoft.PowerShell.Utility/Get-FileHash.md
* Replaced Windows path `C:\Windows\System32...` with `(Get-Module ...).Path` for non-Windows users
* Replaced long `[System.IO.File]::Open()` method with short `OpenRead()` method
* Added ` ```output` block following [the new style guide](https://github.com/PowerShell/PowerShell-Docs/blob/staging/contributing/FORMATTING-CODE.md#syntax-block)
=> Update Example 3 in Get-FileHash.md

reference/3.0/Microsoft.PowerShell.Utility/Tee-Object.md, reference/4.0/Microsoft.PowerShell.Utility/Tee-Object.md, reference/5.0/Microsoft.PowerShell.Utility/Tee-Object.md, reference/5.1/Microsoft.PowerShell.Utility/Tee-Object.md, reference/6/Microsoft.PowerShell.Utility/Tee-Object.md
=> Fix parameter's position in Tee-Object.md

reference/3.0/Microsoft.PowerShell.Utility/Select-String.md, reference/4.0/Microsoft.PowerShell.Utility/Select-String.md, reference/5.0/Microsoft.PowerShell.Utility/Select-String.md, reference/5.1/Microsoft.PowerShell.Utility/Select-String.md, reference/6/Microsoft.PowerShell.Utility/Select-String.md
See Issue #1651
Fixed erroneous sst alias. Recursive examples of Get-Item/Get-ChildItem have already been added. 
=> fixing issue 1651

reference/3.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Split.md, reference/6/Microsoft.PowerShell.Core/About/about_Split.md
Expanded the descriptions for splitting multiple strings as described in Issue #1640.
=> fixing issue 1640

reference/3.0/Microsoft.PowerShell.Management/Get-Item.md, reference/4.0/Microsoft.PowerShell.Management/Get-Item.md, reference/5.0/Microsoft.PowerShell.Management/Get-Item.md, reference/5.1/Microsoft.PowerShell.Management/Get-Item.md, reference/6/Microsoft.PowerShell.Management/Get-Item.md
=> fix -Path metadata to reflect wildcard support per Issue 1672

reference/3.0/Microsoft.PowerShell.Core/New-PSSession.md, reference/3.0/Microsoft.PowerShell.Management/Restart-Computer.md, reference/3.0/Microsoft.PowerShell.Management/Stop-Computer.md, reference/4.0/Microsoft.PowerShell.Core/New-PSSession.md, reference/4.0/Microsoft.PowerShell.Management/Restart-Computer.md, reference/4.0/Microsoft.PowerShell.Management/Stop-Computer.md, reference/5.0/Microsoft.PowerShell.Core/New-PSSession.md, reference/5.0/Microsoft.PowerShell.Management/Restart-Computer.md, reference/5.0/PSDesiredStateConfiguration/Disable-DscDebug.md, reference/5.0/PSDesiredStateConfiguration/Enable-DscDebug.md, reference/5.0/PSDesiredStateConfiguration/Get-DscConfiguration.md, reference/5.0/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md, reference/5.0/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md, reference/5.0/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md, reference/5.0/PSDesiredStateConfiguration/Restore-DscConfiguration.md, reference/5.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md, reference/5.0/PSDesiredStateConfiguration/Test-DscConfiguration.md, reference/5.1/Microsoft.PowerShell.Core/New-PSSession.md, reference/5.1/Microsoft.PowerShell.Management/Restart-Computer.md, reference/5.1/PSDesiredStateConfiguration/Test-DscConfiguration.md, reference/6/Microsoft.PowerShell.Core/New-PSSession.md, reference/6/Microsoft.PowerShell.Management/Restart-Computer.md
Fixed url and odd formatting such as ```about_Remote_Requirements"```, ```about_Remote_Requirementshttp:...```, etc.
=> Fix link for about_Remote_Requirements

reference/6/Microsoft.PowerShell.Utility/Sort-Object.md
Since v6.0, Sort-Object cmdlet has two parameter sets, "Default" and "Bottom".
=> Split parameter set in Sort-Object.md v6.0

reference/6/CimCmdlets/Get-CimSession.md
=> Fix broken headers in Get-CimSession.md v6.0

reference/3.0/Microsoft.PowerShell.Diagnostics/Import-Counter.md, reference/4.0/Microsoft.PowerShell.Diagnostics/Import-Counter.md, reference/5.0/Microsoft.PowerShell.Diagnostics/Import-Counter.md, reference/5.1/Microsoft.PowerShell.Diagnostics/Import-Counter.md, reference/6/Microsoft.PowerShell.Diagnostics/Import-Counter.md
Update Example 1 in Import-Counter.md
* Fixed broken header
* Added ` ```powershell`
* Fixed minor differences in wording
=> Update Example 1 in Import-Counter.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Fixing issues #1510 and #1566 
Moved $OFS example to the prefs article. Added note about read-only Automatic variables not being truly read-only.
=> move $OFS to prefs article added note about read-only

reference/3.0/Microsoft.PowerShell.Management/Restart-Service.md, reference/4.0/Microsoft.PowerShell.Management/Restart-Service.md, reference/5.0/Microsoft.PowerShell.Management/Restart-Service.md, reference/5.1/Microsoft.PowerShell.Management/Restart-Service.md, reference/6/Microsoft.PowerShell.Management/Restart-Service.md
=> Fix parameter's position in Restart-Service.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md, reference/6/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
Logical operators are described in about_logical_operators.md, not in about_comparison_operators.md
=> Fix link for logical operators in about_Operator_Precedence.md

reference/5.1/Microsoft.PowerShell.Security/Protect-CmsMessage.md
The existing example did not specify you needed to create the INF. This not only says so but does so using a script block piped to out-file
=> Update Example 1 of Protect-CmsMessage

dsc/configData.md
Made changes to correct mispellings
=> Small edits for mispellings

reference/5.1/Microsoft.PowerShell.Management/Suspend-Service.md
The CanPauseAndContinue property is a boolean so the correct comparison to use is $true rather than "True".
=> Corrected command

reference/3.0/Microsoft.PowerShell.Management/Resume-Service.md, reference/4.0/Microsoft.PowerShell.Management/Resume-Service.md, reference/5.0/Microsoft.PowerShell.Management/Resume-Service.md, reference/5.1/Microsoft.PowerShell.Management/Resume-Service.md, reference/6/Microsoft.PowerShell.Management/Resume-Service.md
=> Fix parameter's position in Resume-Service.md

reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/6/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md
Removed an unwanted * from Notes section
Corrected intenting for last example
Removed unwanted ... from example 2
=> Help doc enhancement for ConvertFrom-StringData cmdlet

reference/6/Microsoft.PowerShell.Core/About/about_Logging.md
=> PowerShell 6 logging on Windows, Linux, and MacOS

dsc/scriptResource.md
The variable was declared but not used.  It also appears in the same place in Example 2 but is used later on.
=> Removed unused variable in Example 1

dsc/groupResource.md
Example 3 is an example to remove the user from the group but instead it was removing the group completely.  This change adds the correct syntax to perform what was intended.
See https://github.com/PowerShell/PowerShell-Docs/issues/2001
=> Corrected Example 3

appveyor.ps1
Pandoc will be run on about topic files. These files will also be included in the appropriate cab / zip files.
=> Enable running pandoc on about topic files

reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Clixml.md, reference/6/Microsoft.PowerShell.Utility/ConvertTo-Clixml.md, reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md
https://github.com/PowerShell/PowerShell/issues/3898
https://github.com/PowerShell/PowerShell/pull/5815
=> Cmdlet help for ConvertFrom-Clixml and ConvertTo-Clixml 

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions.md
Link to MSDN topic for PSDefaultValueAttribute Members was invalid.
=> fix broken link

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS-and-Linux.md, reference/docs-conceptual/toc.yml
Adding new PSCore v6 articles to TOC and fixing one title
=> update TOC and change title of setup mac/linux article

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
`$PSVersionTable.OS` is:
x `[System.Environment]::OSVersion.VersionString`
o `[System.Runtime.InteropServices.RuntimeInformation]::OSDescription`
See [PSVersionInfo.cs](https://github.com/PowerShell/PowerShell/blob/6.0.0/src/System.Management.Automation/engine/PSVersionInfo.cs#L99) and the following test commands:
```powershell
PS> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0 …
```
=> Fix $PSVersionTable.OS in What's New 6.0

reference/5.1/Microsoft.PowerShell.Utility/Get-FormatData.md
Updated Get-FormatData Markdown for PowerShell 5.1.  Fixes #1895
=> Updated Get-FormatData Markdown

reference/6/Microsoft.PowerShell.Utility/Get-FormatData.md
Updated Get-FormatData Markdown for PowerShell 6.  Fixes #1895
=> Update Get-FormatData Markdown

reference/5.1/Microsoft.PowerShell.Utility/Get-Runspace.md
Updated Get-Runspace Markdown.  Fixes #1883
- [x ] This issue only shows up in version (list version(s) here) of the document
=> Updated Get-Runspace Help

reference/docfx.json
Images broken in new v6 articles.
=> Add resource per version in docfx.json

reference/6/Microsoft.PowerShell.Core/About/about_Logging.md
Summary
-----------
The powershell core 6 configuration file name was changed. This PR update `about_logging.md` to refer to `powershell.config.json` as the name of the configuration file.
=> Change 'PowerShellProperties.json' to 'powershell.config.json' in about_logging

reference/6/Microsoft.PowerShell.Utility/Add-Member.md
fixed layout of examples 1,2 ,3
=> Update Add-Member.md example layouts

reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md, reference/6/Microsoft.PowerShell.Core/About/about_Requires.md
There is no need to have documentation for functions which do not exists in the product.
There is no need to specify in which version this feature was added. Otherwise we need to add such remarks to many other features as well.
=> Removes unnecessary description about the RunAsAdministrator parameter

reference/5.0/PSReadline/Set-PSReadlineKeyHandler.md, reference/5.1/PSReadline/Set-PSReadlineKeyHandler.md, reference/6/PSReadLine/Set-PSReadlineKeyHandler.md
* `[PSConsoleUtilities.PSConsoleReadLine]` -> `[Microsoft.PowerShell.PSConsoleReadLine]`
* Shift+Ctrl+B -> Ctrl+Shift+B
* Added ```powershell
Because running the example and pressing Ctrl+Shift+B causes the following error:
```
An exception occurred in custom key handler, see $error for more information:
Unable to find type [PSConsoleUtilities.PSConsoleReadLine].
```
=> Fix Example 2 in Set-PSReadlineKeyHandler.md

reference/5.0/PSReadline/Remove-PSReadlineKeyHandler.md, reference/5.1/PSReadline/Remove-PSReadlineKeyHandler.md, reference/6/PSReadLine/Remove-PSReadlineKeyHandler.md
* Shift+Ctrl+B -> Ctrl+Shift+B
* Added ```powershell
=> Fix Example 1 in Remove-PSReadlineKeyHandler.md

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
"Backwards compatibility with Windows PowerShell" anchor reference had incorrect Markdown syntax. Rendered incorrectly on both GitHub and Docs:
**NOTE:** GitHub diff shows line 403 as changed, but I did not touch that one at all.
=> Fix minor Markdown syntax error

reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md
Change in PSCore6.1 for file encoding of New-ModuleManifest to be UTF-8 NoBOM: https://github.com/PowerShell/PowerShell/pull/5923
=> update file encoding of New-ModuleManifest

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS-and-Linux.md
Corrected links and names to match the 6.0.0 release.
=> Fix release links/names (6.0.0)

reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md
The reasons to remove are the same as in #2057. I just forgot about the SYNTAX section.
=> Continuation of #2057

reference/5.1/Microsoft.PowerShell.Core/Connect-PSSession.md
Just an update for the documentation links to About pages to use relative links—it is my understanding these are the most up-to-date and correct pages going forward.
=> Updated About documentation links to relative paths

reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md, reference/6/Microsoft.PowerShell.Core/About/about_Requires.md
This change makes content in this brackets displayable
=> Escapes angle brackets in about_Requires

reference/3.0/Microsoft.PowerShell.Core/About/about_Type_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Type_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Type_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Type_Operators.md
Updated about_Type_Operators per issue #1915
=> about_Type_Operators issues #1915

wmf/5.1/install-configure.md
See PR #2065 for background,
Added note about reboot requirements.
=> add note about reboot

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
`PowerShellProperties.json` was renamed to `powershell.config.json`.
See these commit and pull request : 
* [Rename 'PowerShellProperties.json' to 'powershell.config.json'](https://github.com/PowerShell/PowerShell/commit/3b5badca047acb5e979e21bce80a1e988535b872)
* [Change 'PowerShellProperties.json' to 'powershell.config.json' in about_logging](https://github.com/PowerShell/PowerShell-Docs/pull/2050)
=> Rename PowerShellProperties.json to powershell.config.json

README.md, reference/3.0/Microsoft.PowerShell.Utility/Add-Type.md, reference/4.0/Microsoft.PowerShell.Utility/Add-Type.md, reference/5.0/Microsoft.PowerShell.Utility/Add-Type.md, reference/5.1/Microsoft.PowerShell.Utility/Add-Type.md, reference/6/Microsoft.PowerShell.Utility/Add-Type.md
=> Fix example VB code

reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Summary
* Adds missing SslProtocol parameter from Invoke-WebRequest cmdlet.
* Add libcurl note the Certificate parameter.
Closes #1926
/cc @markekraus
=> Adds missing SslProtocol parameter from Invoke-WebRequest cmdlet.

reference/3.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/6/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
Links to about_Object_Creation.md were malformed in all references versions.
=> Fixed bad link in about_Hash_Tables.md docs

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Restoring changes to Invoke-RestMethod and Invoke-WebRequest that were made in PR #1870. Somehow these were overwritten by later PRs.
=> restoring changes made in PR#1870

reference/5.1/Microsoft.PowerShell.Management/New-PSDrive.md
=> Remove repeat description

reference/5.1/Microsoft.PowerShell.Management/Join-Path.md
impacts all versions (was just a typo)
=> add escape \ for the delimiter to fix typo

reference/3.0/Microsoft.PowerShell.Core/About/about_Switch.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Switch.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Switch.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md, reference/6/Microsoft.PowerShell.Core/About/about_Switch.md
=> Fix about_Switch.md.

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
Fix issue #2088.
Addressing PowerShell/PowerShell#6063 "Documentation Needed".
=> Add info on POWERSHELL_TELEMETRY_OPTOUT environment variable.

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
=> Add ValidateDrive and ValidateUserDrive attributes information.

reference/5.1/Microsoft.PowerShell.Utility/Format-List.md
Changed the value of "Accept wildcard characters" from "False" to "True" for the "-Property" parameter. Example 4 clearly shows that this parameter accepts wildcards.
=> Minor typo fix in Format-List.md

reference/6/Microsoft.PowerShell.Core/About/about_Arrays.md
Adding details about foreach & where methods being added in PowerShell v4 and that they aren't available downlevel (for historical purposes) and also points to using the Pipeline methods with the resulting Foreach-Object & Where-Object cmdlets
=> Adds foreach & where method added in PowerShell v4

reference/5.0/Microsoft.PowerShell.Utility/Get-Runspace.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Runspace.md, reference/6/Microsoft.PowerShell.Utility/Get-Runspace.md
`Get-Runspace` returns subclass objects derived from `System.Management.Automation.Runspaces.Runspace` public abstract class. 
```powershell
PS> (Get-Command Get-Runspace).OutputType | Format-List
Name              : System.Management.Automation.Runspaces.Runspace
Type              : System.Management.Automation.Runspaces.Runspace
TypeDefinitionAst :
```
`System.Management.Automation.Runspaces.RunspaceBase` is [an internal class derived from the Runspace class](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs#L24).
=> Fix and add OUTPUTS in Get-Runspace.md

reference/6/Microsoft.PowerShell.Management/Debug-Process.md
`Get-Process -ComputerName` parameter is not supported since v6.0. See PowerShell/PowerShell#4960
=> Remove `Get-Process -ComputerName` example in Debug-Process.md v6.0

reference/3.0/Microsoft.PowerShell.Utility/New-Alias.md, reference/4.0/Microsoft.PowerShell.Utility/New-Alias.md, reference/5.0/Microsoft.PowerShell.Utility/New-Alias.md, reference/5.1/Microsoft.PowerShell.Utility/New-Alias.md, reference/6/Microsoft.PowerShell.Utility/New-Alias.md
* Add "Unspecified"
* Fix wording and formatting
=> Update `-Option` section in New-Alias.md

reference/5.1/Microsoft.PowerShell.Management/Register-WmiEvent.md
Fixed a typo in argument of "Example 2: Subscribe to creation events for a process", changed argument from Auery to Query.
=> Fixed a typo

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
Example #2 in its current form is unsafe, because it includes the SkipCertificateCheck flag for no documented reason. If a user based their solution off of the example and did not notice the needed to remove the flag, they could create a security vulnerability.
Removing the flag does not appear to impact the example in any way other than to resolve this problem.
=> Remove SkipCertificateCheck flag

reference/6/Microsoft.PowerShell.Core/Save-Help.md, reference/6/Microsoft.PowerShell.Core/Update-Help.md, reference/6/Microsoft.PowerShell.Management/New-Service.md, reference/6/Microsoft.PowerShell.Management/Start-Process.md, reference/6/Microsoft.PowerShell.Utility/Set-TraceSource.md, reference/6/Microsoft.PowerShell.Utility/Tee-Object.md, reference/6/Microsoft.PowerShell.Utility/Trace-Command.md, reference/6/Microsoft.WSMan.Management/Invoke-WSManAction.md, reference/6/Microsoft.WSMan.Management/New-WSManInstance.md, reference/6/Microsoft.WSMan.Management/Set-WSManInstance.md
add Path alias to DestinationPath for Save-Help
add Path alias to SourcePath for Update-Help
add Path alias to BinaryPathName for New-Service
add Path alias to FilePath for Start-Process, Set-TraceSource, Tee-Object, Trace-Command, Invoke-WSManAction, New-WSManInstance, and Set-WSManInstance
=> Document -Path aliases added to several cmdlets

reference/5.0/Microsoft.PowerShell.Management/Test-Connection.md, reference/5.1/Microsoft.PowerShell.Management/Test-Connection.md, reference/6/Microsoft.PowerShell.Management/Test-Connection.md
Currently the text description clearly describes the default functionality: four pings are sent.
The documentation for the Count's Default value stated that None was default which was false.
This change in documentation happened at PowerShell 5.0 docs, prior to that it clearly states `Default value: 4`
=> Test-Connection Default Count value is 4 not None

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS-and-Linux.md
- Explicitly mention the conflict error and the solution.
- Make the command that looks for libcurl more precise, since the goal is to find the specific package that places the lib in the place where the RHEL PS package looks for it.
Ref: https://github.com/PowerShell/PowerShell/issues/6184
=> Clarify the docs regarding libcurl for installation on openSUSE

gallery/psget/module/modulewithpseditionsupport.md
=> Typos fixed in modulewithpseditionsupport.md

dsc/TOC.md, dsc/azureDsc.md, dsc/azureDscexthistory.md
Converting Azure VM Extension for DSC history from Blog post to Docs.
=> Adding DSC Extension history

dsc/azureDsc.md
Fixed link for Azure automation service and performed minor lint cleanup.
=> Fix automation link and lint cleanup

dsc/azureDscexthistory.md
Restoring v2.19 to Latest Versions as most recent supported ext. version for Azure Gov / Azure China.
=> Restoring 2.19 to Latest Versions in History

reference/docs-conceptual/getting-started/Getting-Ready-to-Use-Windows-PowerShell.md
(Not sure if the versions apply since this file is under `docs-conceptual` instead)
=> Fixed "about_Updatable_Help" link

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
@sdwheeler  I am not sure whether it is a documentation bug or a software bug. If it is a software bug, please close this PR.
According to the [New-ModuleManifest.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md):
* `New-ModuleManifest` does not have **Encoding** parameter
* The encoding of the module manifest (.psd1) file created with `New-ModuleManifest` cmdlet depends on environment: if it is PowerShell Core running on Linux then encoding is UTF-8 (no BOM); otherwise encoding is UTF-16 (with BOM)
See [NewModuleManifestCommand.cs](https://github.com/PowerShell/PowerShell/blob/6.0.0/src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs#L944-L948) and the following test commands:
Windows: …
=> Fix New-ModuleManifest encoding in What's New 6.0

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Closes #2195
I copied the syntax from PlatyPS. It added the `-Form` feature which I will document separately (re: #2077).
=> Document 6.1.0 Web Cmdlets -Resume Feature

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Closes #2077
- [] The documented feature was introduced in version (list version here) of PowerShell
=> Document New -Form Parameter for Web Cmdlets

dsc/authoringResourceComposite.md
- Not: `TestCompositeResource`; which isn't mentioned anywhere in this document.
=> Importing `xVirtualMachine`

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
Fix https://github.com/PowerShell/PowerShell/issues/6513
=> $PSVersionTable.Platform returns Unix on macOS

reference/6/Microsoft.PowerShell.Core/About/about_Session_Configurations.md
Update docs with the info about session configurations created by Enable-PSRemoting cmdlet.
Now the command would create two session configurations:
- with the name defined as: "PowerShell." + "current PowerShell version"
- with name "PowerShell.6", untied to any specific PowerShell version.
=> Update docs with the info about session configurations created by Enable-PSRemoting cmdlet.

reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md, reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md, reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md, reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
=> Btr convertfromjson

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
=> Document PowerShell/PowerShell#6018

reference/docs-conceptual/PowerShell-Core-on-ARM.md, reference/docs-conceptual/toc.yml
@sdwheeler we need this doc published for some fwlinks that are going to be published in shipping products in the future. This will need to be expanded (and eventually we'll migrate installation docs off of GitHub), but I think this fulfills our need for now. 
Please ping me offline if you have any questions on this. Thanks!
=> Add stub topic for PowerShell Core on ARM

reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md, reference/6/Microsoft.PowerShell.Core/Invoke-Command.md, reference/6/Microsoft.PowerShell.Core/New-PSSession.md
Update documentation to reflect code change https://github.com/PowerShell/PowerShell/pull/6603
=> update documentation to reflect that -ConfigurationName can be used with SSH

reference/3.0/Microsoft.PowerShell.Core/Receive-Job.md, reference/4.0/Microsoft.PowerShell.Core/Receive-Job.md, reference/5.0/Microsoft.PowerShell.Core/Receive-Job.md, reference/5.1/Microsoft.PowerShell.Core/Receive-Job.md, reference/6/Microsoft.PowerShell.Core/Receive-Job.md
The **AutoRemoveJob** parameter cannot be used without the **Wait** parameter. See the following example:
```powershell
PS> Receive-Job (Start-Job -ScriptBlock { Get-Process }) -AutoRemoveJob
Receive-Job : The -AutoRemoveJob parameter cannot be used without the -Wait parameter
At line:1 char:1
+ Receive-Job (Start-Job -ScriptBlock { Get-Process }) -AutoRemoveJob
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Receive-Job], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.ReceiveJobCommand
```
=> Update AutoRemoveJob in Receive-Job.md

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md
Update docs to reflect code change via https://github.com/PowerShell/PowerShell/pull/6601
=> update doc to reflect change in telemety opt out

reference/5.1/Microsoft.PowerShell.Utility/Set-Variable.md
=> Add link on about_Scopes to about_Scopes.md on v5.1  #2309

reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/6/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
=> Fix typos in about_Comment_Based_Help.md

reference/6/PackageManagement/Register-PackageSource.md
The current documentation says that -credential is for admin credentials to add a package source.  I believe it is instead the credentials required to access an authenticated feed location.
=> Incorrectly documents -credential parameter

reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Affect and effect are similar, but not the same. I think effect is the word that is intended here.
https://www.merriam-webster.com/dictionary/affect
- [Don't know ] Impacts 6.1 document
- [ X] The documented feature was introduced in version (6.0 - made this option obsolete) of PowerShell
=> Improve wording for -UseBasicParsing

wmf/5.0/feedback_moduleversionranges.md
Hello, @JKeithB,
Localization team has reported source content issue that causes localized version to have different format compared to en-us version.  
Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
=> C14191: Possible content blocked for localization

reference/6/Microsoft.PowerShell.Core/Where-Object.md
Add documentation for new parameter -Not on Where-Object added in PowerShell/PowerShell#6464  
Fix #2199
=> Add -Not Feature to Where-Object

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS-and-Linux.md
I just tested on my Macbook and confirmed that
```brew update
brew cask upgrade
```
successfully updated my instance from PS Core 6.0.1 to 6.0.2
=> Update MacOS instructions to use brew cask upgrade

reference/6/Microsoft.PowerShell.Core/About/about_pwsh.md
Update docs based on code change to add -workingdirectory parameter to pwsh
https://github.com/PowerShell/PowerShell/pull/6612
=> update doc on new -workingdirectory parameter

reference/3.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Fix -replace operator example and bring it in accordance with Rename-Item cmdlet example.
=> Fix -replace operator example.

reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md, reference/6/Microsoft.PowerShell.Core/Invoke-Command.md, reference/6/Microsoft.PowerShell.Core/New-PSSession.md
Fix typo in the -HostName parameter description.
=> Fix typo in the -HostName parameter description.

reference/6/Microsoft.PowerShell.Core/About/about_Logging.md
Documents the command to enable log persistence and exporting of log entries.
Fixes https://github.com/PowerShell/PowerShell-Docs/issues/2329
=> Document log persistence and exporting in about_Logging.md

reference/6/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/6/Microsoft.PowerShell.Core/Disconnect-PSSession.md
This only became a problem when SSH remoting was added in 6.0
=> clarify that disconnect only works with WSMan

reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
Fixed #1456 
Only v5.1 was already fixed with #1436
=> Fix typo in Invoke-RestMethod.md (fixed #1456)

dsc/configurations.md
The word 'Call' was missed, hence the first point in the 'Compiling the Configuration' section was incomplete.
=> Added missed 'Call' word

reference/4.0/Microsoft.PowerShell.Core/About/about_Split.md
Example code breaks because underscore character is missing from automatic variable $_ in the last example of about_split cmdlet help.
=> Add missing underscore in the code of last example

reference/docs-conceptual/getting-started/cookbooks/Getting-WMI-Objects--Get-WmiObject-.md
Hello, @DCtheGeek,
Localization team has reported source content issue that causes localized version to have different format compared to en-us version.
Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.
=> C13038: Missing asterisk due to incorrect structure

reference/3.0/Microsoft.PowerShell.Core/Get-Command.md, reference/4.0/Microsoft.PowerShell.Core/Get-Command.md, reference/5.0/Microsoft.PowerShell.Core/Get-Command.md, reference/5.1/Microsoft.PowerShell.Core/Get-Command.md, reference/6/Microsoft.PowerShell.Core/Get-Command.md
=> Fix -CommandType parameter description for Get-Command cmdlet.

reference/3.0/Microsoft.PowerShell.Core/About/about_Aliases.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Break.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Command_Syntax.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/3.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Continue.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Core_Commands.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Debuggers.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Do.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Eventlogs.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/3.0/Microsoft.PowerShell.Core/About/about_For.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Foreach.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Functions.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md, reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md, wmf/5.1/scenarios-features.md
=> Testing script automation with a smaller batch of files

reference/3.0/Microsoft.PowerShell.Core/Out-Default.md, reference/3.0/Microsoft.PowerShell.Core/Out-Host.md, reference/3.0/Microsoft.PowerShell.Core/Out-Null.md, reference/3.0/Microsoft.PowerShell.Core/Receive-Job.md, reference/3.0/Microsoft.PowerShell.Core/Receive-PSSession.md, reference/3.0/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/3.0/Microsoft.PowerShell.Core/Remove-Job.md, reference/3.0/Microsoft.PowerShell.Core/Remove-Module.md, reference/3.0/Microsoft.PowerShell.Core/Remove-PSSession.md, reference/3.0/Microsoft.PowerShell.Core/Remove-PSSnapin.md, reference/3.0/Microsoft.PowerShell.Core/Resume-Job.md, reference/3.0/Microsoft.PowerShell.Core/Save-Help.md, reference/3.0/Microsoft.PowerShell.Core/Set-PSDebug.md, reference/3.0/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md, reference/3.0/Microsoft.PowerShell.Core/Set-StrictMode.md, reference/3.0/Microsoft.PowerShell.Core/Start-Job.md
=> Batch automation: Formatting fixes

reference/3.0/Microsoft.PowerShell.Core/About/about_CimSession.md, reference/4.0/Microsoft.PowerShell.Core/About/about_CimSession.md, reference/5.0/Microsoft.PowerShell.Core/About/about_CimSession.md, reference/5.1/Microsoft.PowerShell.Core/About/about_CimSession.md, reference/6/Microsoft.PowerShell.Core/About/about_CimSession.md
=> Add about_CimSession.md.

dsc/secureMOF.md
Related change to Updated localmachine\Root to LocalMachine\My (#1880) by @rchaganti . Change was added only in code but not in description.
=> Related change with #1880

reference/docs-conceptual/getting-started/cookbooks/Collecting-Information-About-Computers.md
=> Change Get-WMIObject cmdlet reference to Get-CimInstance in Collecting-Information-About-Computers.md.

reference/3.0/Microsoft.PowerShell.Management/Get-ControlPanelItem.md, reference/4.0/Microsoft.PowerShell.Management/Get-ControlPanelItem.md, reference/5.0/Microsoft.PowerShell.Management/Get-ControlPanelItem.md, reference/5.1/Microsoft.PowerShell.Management/Get-ControlPanelItem.md
X "This cmdlet does not generate any output."
O "This cmdlet gets control panel items on the local computer."
=> Fix OUTPUTS in Get-ControlPanelItem.md

reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md, reference/6/Microsoft.PowerShell.Core/About/about_Requires.md
Correct examples of hash table usage within `#Requires`. Multi-line hash tables are not permitted and will cause an exception. `#Requires` must be single line and there must be a comma between multiple modules.
=> correct example in about_requires

reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Documents changes as a result of moving to .NET Core 2.1 in PowerShell 6.1.0 as well as marks all new features added in 6.0.0.
=> Web Cmdlets .NET Core 2.1 and PowerShell 6.1.0 Refresh

reference/6/Microsoft.PowerShell.Core/About/about_Logging.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md
Document the change to PowerShell disabling support for Basic Authentication over HTTP and document alternatives.
Fix https://github.com/PowerShell/PowerShell-Docs/issues/2394
=> Document Basic Auth constraints on Linux and macOs

wmf/5.0/dsc_statestatus.md
Hello, @sdwheeler,
Localization team has reported source content issue that causes localized version to have broken format compared to en-us version.  
=> C20192: Asterisk issue due to a character that needs to be escaped

reference/3.0/Microsoft.PowerShell.Core/Enter-PSSession.md, reference/3.0/PSWorkflow/About/about_Checkpoint-Workflow.md, reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md, reference/3.0/PSWorkflow/About/about_InlineScript.md, reference/3.0/PSWorkflow/About/about_Parallel.md, reference/3.0/PSWorkflow/About/about_Sequence.md, reference/3.0/PSWorkflow/About/about_Suspend-Workflow.md, reference/3.0/PSWorkflow/About/about_WorkflowCommonParameters.md, reference/3.0/PSWorkflow/About/about_Workflows.md, reference/3.0/PSWorkflowUtility/Invoke-AsWorkflow.md, reference/3.0/PSWorkflowUtility/PSWorkflowUtility.md, reference/4.0/ISE/Get-IseSnippet.md, reference/4.0/ISE/ISE.md, reference/4.0/ISE/Import-IseSnippet.md, reference/4.0/ISE/New-IseSnippet.md, reference/4.0/Microsoft.PowerShell.Core/Add-History.md, reference/4.0/Microsoft.PowerShell.Core/Add-PSSnapin.md, reference/4.0/Microsoft.PowerShell.Core/Clear-History.md, reference/4.0/Microsoft.PowerShell.Core/Connect-PSSession.md, reference/4.0/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/4.0/Microsoft.PowerShell.Core/Disable-PSSessionConfiguration.md, reference/4.0/Microsoft.PowerShell.Core/Disconnect-PSSession.md, reference/4.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md, reference/4.0/Microsoft.PowerShell.Core/Enable-PSSessionConfiguration.md, reference/4.0/Microsoft.PowerShell.Core/Enter-PSSession.md, reference/4.0/Microsoft.PowerShell.Core/Exit-PSSession.md, reference/4.0/Microsoft.PowerShell.Core/Export-Console.md
=> Release bobbytreed b007

reference/docs-conceptual/getting-started/cookbooks/Removing-Objects-from-the-Pipeline--Where-Object-.md
I have not seen a parameter described in this way. Where-ObjectFilterScript looks like a cmdlet/function whereas Where-Object -FilterScript look more like a parameter
=> Where-ObjectFilterScript parameter is confusing

reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md, reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md, reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md
Lack of code blocks were causing some dramatic formatting issues.
=> Code blocks for about_Scheduled_Jobs_Advanced

reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
Updated Example 3 to use double quotes instead of single quotes for the newline escape character. The newline escape character is interpreted literally when used with single quotes, and does not work as expected in this case.
=> Corrected an Example in ConvertTo-JSON

reference/3.0/Microsoft.PowerShell.Core/Out-Host.md, reference/4.0/Microsoft.PowerShell.Core/Out-Host.md, reference/5.0/Microsoft.PowerShell.Core/Out-Host.md, reference/5.1/Microsoft.PowerShell.Core/Out-Host.md, reference/6/Microsoft.PowerShell.Core/Out-Host.md
* Fixed some wording and formatting
* Removed the wrong sentences about the `help` function because its implementation does not use `Out-Host -Paging` but the `more` function (To verify that, type `(Get-Command help).Definition`)
=> Update Example 1 in Out-Host.md

reference/3.0/Microsoft.PowerShell.Core/Get-Help.md, reference/4.0/Microsoft.PowerShell.Core/Get-Help.md, reference/5.0/Microsoft.PowerShell.Core/Get-Help.md, reference/5.1/Microsoft.PowerShell.Core/Get-Help.md, reference/6/Microsoft.PowerShell.Core/Get-Help.md
The Example 5, which is long and unreadable, explains mainly `Update-Help` cmdlet.
=> Remove Example 5 in Get-Help.md

reference/3.0/Microsoft.PowerShell.Core/Get-Help.md, reference/4.0/Microsoft.PowerShell.Core/Get-Help.md, reference/5.0/Microsoft.PowerShell.Core/Get-Help.md, reference/5.1/Microsoft.PowerShell.Core/Get-Help.md, reference/6/Microsoft.PowerShell.Core/Get-Help.md
Both **Examples** and **Parameter** parameter are used to display selected parts of a cmdlet help.
=> Join Examples and Parameter parameter examples in Get-Help.md

reference/6/Microsoft.PowerShell.Core/About/about_Classes.md
Correcting previous wording and add a couple syntax examples.
=> Correcting text describing the inheritance order

reference/3.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Split.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Split.md, reference/6/Microsoft.PowerShell.Core/About/about_Split.md
Received a LiveFyre comment about a bad example. 
=> Bad example in about_Split

reference/6/Microsoft.PowerShell.Management/Get-Service.md, reference/6/Microsoft.PowerShell.Management/Set-Service.md
Found from LiveFyre feedback.
See breaking changes in v6 - the computername parameter was remove for consistency
- Get-Service
- Set-Service 
The documentation shows the correct syntax but talks about how you can manage remote services.
Need to document implicit remoting or Invoke-Command as a replacement for -ComputerName remoting.
=> Update docs for *-Service cmdlet remoting

reference/docs-conceptual/PowerShell-Core-Support.md, reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
=> Fedora 28 was released, Fedora 26 and 25 were EOL'ed.

reference/3.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
=> Fixes #2416 update about_comparison_operators to reflect regular expression substitution

.github/CODEOWNERS, reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
remove Ubuntu 17.04 and fedora 25 due to EOL
Add Ubuntu 17.10 and 18.04 and fedora 27
fixes #2302
=> Update pwsh docs due to distro EOL and replacment

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md
add instructions to install preview for macOS
addresses #2573
=> add instructions to install preview for macOS

reference/3.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Requires.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md, reference/6/Microsoft.PowerShell.Core/About/about_Requires.md
…troduced in Windows PowerShell 5.0
=> Closes #4783 - Addressed lack of documentation on RequiredVersion, in Windows PowerShell 5.0

reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md
The example of creating a local user attached to a Microsoft account doesn't actually work
=> remove example of creating user attached to Microsoft account

reference/5.0/Microsoft.PowerShell.Core/About/about_psreadline.md, reference/5.1/Microsoft.PowerShell.Core/About/about_psreadline.md, reference/6/Microsoft.PowerShell.Core/About/about_psreadline.md
Formatting broken because of unescaped characters.
This fixes Issue #2611 
=> fixed formatting of <> chars

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
Add instructions to install preview releases
Also added notes about what distro's are supported experimentally
fixes #2573
=> Add instructions to install preview releases

reference/3.0/Microsoft.PowerShell.Management/Join-Path.md, reference/4.0/Microsoft.PowerShell.Management/Join-Path.md, reference/5.0/Microsoft.PowerShell.Management/Join-Path.md, reference/5.1/Microsoft.PowerShell.Management/Join-Path.md, reference/6/Microsoft.PowerShell.Management/Join-Path.md
=> Closes #1490, 1612 - Updating Join-Path documentation

reference/5.1/Microsoft.PowerShell.Management/Get-ComputerInfo.md, reference/6/Microsoft.PowerShell.Management/Get-ComputerInfo.md
=> Fixes #1162 - Clarifying version introduced for Get-ComputerInfo

reference/6/Microsoft.PowerShell.Utility/Measure-Object.md
Modification for Measure-Object help file for -AllStats switch based on issue [#6278](https://github.com/PowerShell/PowerShell/pull/7220)
=> Modification for Measure-Object help file for -AllStats switch.

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
Install command for powershell on ubunto 18.0.4 fails - needs to be powershell-preview to work.
=> fix install command on Ubuntu 18.0.4

reference/6/Microsoft.PowerShell.Core/New-PSSession.md
I apologize for the crazy diff. All that's happening here is that I used platyPS to update the parameter set names and command syntax to reflect the accurate names/optionality of stuff that got added in PS Core 6. 
=> Fix parameter set names/syntax for New-PSSession

developer/module/installing-a-powershell-module.md
Inserted a (presumably lost) colon (:) into an environment variable reference.
=> Fix reference to an environment variable

developer/module/installing-a-powershell-module.md
The second paragraph of section “Installing Modules in the Common Files Directory” and the PowerShell sample code at its end both refer to installation in %ProgramFiles%\WindowsPowerShell\Modules (as covered in the preceding section, “Installing Modules for all Users in Program Files”) while the section title and the first paragraph are about installing modules in %ProgramFiles%\Common Files\Modules. The proposed change resolves this inconsistency.
It further proposes to first check the %PsModulePath% directory list before adding the Common Files Module directory.
Note to the reviewers: I’m not an expert on the designated meaning of system directories (like %ProgramFiles%\Common Files\Modules), and may have misunderstood the first paragraph, resulting in this change proposal to be plainly …
=> Resolve inconsistencies about Common Files Modules

developer/module/installing-a-powershell-module.md
Moved all text and displays following the first paragraph of item 3 of the list out of the list (where they are located by presumably erroneous indentation).
=> Fix indentation (removing material from a list)

developer/module/importing-a-powershell-module.md
Adjusting the casing of class System.Management.Automation.PSModuleInfo (in particular, only the class name, not the namespace) to the spelling used in the reference (mandatory for case-sensitive framework languages).
=> Tidy up class name casing

developer/cmdlet/required-development-guidelines.md
The phrase **get-command start-\*** seems to be rendered fine on Github, but regrettably the backslash appears not to be recognized as an escape (of the first asterisk in the group of three) on docs.microsoft.com, where it shows up literally in front of the asterisk it is supposed to escape. For that reason I tentatively replace the double-asterisk markdown with underscores and remove the disputed backslash. This should be equivalent with the base version, though it messes up the text edit window on Github, where, probably due to a bug, the part of the paragraph following the closing pair of underscores is displayed in italics. …
=> Try to fix markdown for docs.microsoft.com

developer/cmdlet/required-development-guidelines.md
Changed the participle _adding_ to _added_ which appears to be required in the present context.
=> Fix tense and mode of a participle from context

developer/cmdlet/required-development-guidelines.md
Fix inflection of _make_ in the third item of the list in section _Derive from the Cmdlet or PSCmdlet Classes (RC01)_ to match the singular number of the subject, _the cmdlet_.
=> Fix verb inflection

developer/cmdlet/required-development-guidelines.md
Applying the casing used by the CLR for the names of all classes referenced in document /developer/cmdlet/required-development-guidelines.md
=> Tidy up class casing

developer/cmdlet/creating-a-cmdlet-that-modifies-the-system.md, developer/cmdlet/creating-a-cmdlet-to-access-a-data-store.md, developer/cmdlet/creating-a-cmdlet-without-parameters.md
These duplicates might be due to failure of auto-conversion from MSDN to Microsoft Docs.
=> Remove duplicate sentences in developer\cmdlet\creating-a-cmdlet-*.md

developer/hosting/runspace-samples.md, developer/hosting/runspace01-sample.md, developer/hosting/runspace02-sample.md, developer/hosting/runspace07-sample.md, developer/hosting/runspace08-sample.md
These duplicates might be due to failure of auto-conversion from MSDN to Microsoft Docs.
=> Remove duplicate sentences in developer\hosting\runspace*.md

reference/6/Microsoft.PowerShell.Core/Get-Module.md
move commentary outside code-blocks to reduce horizontal scrolling
=> Get-Module - less horizontal scrolling

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
You do not have to do curl and do all that staff, zypper tool in OpenSUSE does it for you. I have updated this document to reflect the easier way of adding repository, which also help with updating PowerShell in the feature. In the feature if there is update to this repository zypper will automatically install new version and remove old one.
=> OpenSUSE Easy way to add product feed/repository

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md
1. Homebrew has deprecated the separate Cask setup, and integrated casks into the main homebrew setup.  Updated instructions to reflect this.
2. Added instructions to run 'brew upgrade' for situations where an older installation of Homebrew existed. 
3. Added an "Additional Resources" section at the bottom for links.
=> Updated Home-brew instructions

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md
tapping the main cask repo is no longer needed
add instructions to install powershell-preview for macOS
fixes #2727 
=> Add mac preview instructions

reference/6/Microsoft.PowerShell.Management/New-PSDrive.md
Paragraph regarding external drive is duplicated with one minor typographical difference: The word PS-Drive is bolded in one paragraph and not the other. So remove the paragraph lacking the bold.
=> Delete Duplicate Paragraphs in New-PSDrive

reference/3.0/Microsoft.PowerShell.Core/Export-ModuleMember.md, reference/4.0/Microsoft.PowerShell.Core/Export-ModuleMember.md, reference/5.0/Microsoft.PowerShell.Core/Export-ModuleMember.md, reference/5.1/Microsoft.PowerShell.Core/Export-ModuleMember.md, reference/6/Microsoft.PowerShell.Core/Export-ModuleMember.md
Fixed:
- Aliases are exported by default
- Examples description and code
- Markdown formatting
=> Fix Export-ModuleMember help.

reference/5.0/Microsoft.PowerShell.Utility/Select-Object.md, reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md
Following #2732 here's the update to 5.0 and 5.1 version of `Select-Object`
Fixes #2716
=> Update Select-Object for 5.0 and 5.1

reference/3.0/Microsoft.PowerShell.Core/Get-Command.md, reference/4.0/Microsoft.PowerShell.Core/Get-Command.md, reference/5.0/Microsoft.PowerShell.Core/Get-Command.md, reference/5.1/Microsoft.PowerShell.Core/Get-Command.md, reference/6/Microsoft.PowerShell.Core/Get-Command.md
PSScheduledJob -> Microsoft.PowerShell.Utility
`Get-Command` can not get PSScheduledJob, which is not included in PowerShell 6.
=> Update Example 4 in Get-Command.md

contributing/4-MARKDOWN-SPECIFICS.md
=> Fix a link and typos in 4-MARKDOWN-SPECIFICS.md

reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md, reference/6/Microsoft.PowerShell.Core/About/about_Requires.md
Add the missing PSEdition parameter.
Remove "Windows" where appropriate.
Change examples to use modules that are cross-platform relevant.
=> Make about_Requires topic cross-platform on PS6

reference/3.0/Microsoft.PowerShell.Utility/Out-String.md, reference/4.0/Microsoft.PowerShell.Utility/Out-String.md, reference/5.0/Microsoft.PowerShell.Utility/Out-String.md, reference/5.1/Microsoft.PowerShell.Utility/Out-String.md, reference/6/Microsoft.PowerShell.Utility/Out-String.md
Change a description for the **Width** parameter.
Remove "Windows" from "Windows PowerShell".
Simplify prompt to `PS>`.
Change a formatting of cmdlet, variable, parameter, and property names.
Use semantic line breaks.
Fix fenced code blocks.
=> Fix Out-String according to the Contributor Guide

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Windows.md
Hello, @sdwheeler , @joeyaiello 
"There is missing line between \
=> C30671: Adding breakline after TODO comment

reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/4.0/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/5.0/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md
Fix a syntax block for `Get-ChildItem` and added valid attribute values.
Add the blank lines.
Add 2 missing attributes to the list of valid values for the **Attributes** parameter.
Fix some minor typos.
=> Fix Get-ChildItem's syntax block (add attribute values)

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
* Level 2 -> 3
- ValidateDrive Validation Attribute
- ValidateUserDrive Validation Attribute
* Level 3 -> 2
- Dynamic Parameters
- Switch Parameters
=> Fix levels of headings in about_Functions_Advanced_Parameters.md

reference/6/PowerShellGet/Find-DscResource.md, reference/6/PowerShellGet/Find-Module.md, reference/6/PowerShellGet/Get-InstalledModule.md, reference/6/PowerShellGet/Install-Module.md, reference/6/PowerShellGet/New-ScriptFileInfo.md, reference/6/PowerShellGet/Publish-Script.md, reference/6/PowerShellGet/Save-Module.md, reference/6/PowerShellGet/Save-Script.md, reference/6/PowerShellGet/Test-ScriptFileInfo.md, reference/6/PowerShellGet/Update-Module.md, reference/6/PowerShellGet/Update-ModuleManifest.md, reference/6/PowerShellGet/Update-ScriptFileInfo.md
It's a partial fix of #2747 - for the PowerShellGet module only.
This is the second try - the previous one #2776 was reverted.
=> Replace Windows PowerShell with PowerShell - the PowerShellGet module

reference/6/Microsoft.PowerShell.Utility/Add-Type.md
Fix for #2528.
Fix the syntax block.
Remove the CodeDomProvider parameter.
Remove the CompilerParameters parameter.
Add the CompilerOptions parameter.
Change "Windows PowerShell" to "PowerShell" and ".NET Framework" to ".NET Core".
Change prompts to "PS>".
Remove examples that are irrelevant.
Fix other examples.
- [] This issue only shows up in version (list version(s) here) of the document
=> Fix for #2528 Update parameters for the Add-Type cmdlet

reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md
=> Fix a typo in Get-ChildItem.md.

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Fixed the following issues:
* `if ($path -match ".HKLM.:")` does not indicate the HKEY_LOCAL_MACHINE registry drive
* The **DP1** parameter is not in the "PSet1" parameter set but the "__AllParameterSets"
Also fixed some minor formatting issues.
=> Fix DynamicParam sample function

reference/6/Microsoft.PowerShell.Utility/Add-Type.md
Fix for #2442.
Update parameters for the Add-Type cmdlet in PowerShell Core 6.0. 
Sync examples and descriptions with Add-Type in the release-ps61 branch.
=> Fix for #2442 Update Add-Type parameters in PS6

reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/6/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md
It's a partial fix of #2747 - for the Microsoft.PowerShell.Archive module only.
=>  Replace Windows PowerShell with PowerShell - the Microsoft.PowerShell.Archive module

reference/6/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.md, reference/6/Microsoft.PowerShell.Host/Start-Transcript.md
It's a partial fix of #2747 - for the Microsoft.PowerShell.Host module only.
=> Replace Windows PowerShell with PowerShell - the Microsoft.PowerShell.Host module

reference/6/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/6/Microsoft.PowerShell.Diagnostics/New-WinEvent.md
It's a partial fix of #2747 - for the Microsoft.PowerShell.Diagnostics module only.
=> Replace Windows PowerShell with PowerShell - the Microsoft.PowerShell.Diagnostics module

reference/6/Microsoft.PowerShell.Security/Get-CmsMessage.md, reference/6/Microsoft.PowerShell.Security/Protect-CmsMessage.md, reference/6/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md
Fix examples.
Remove an example that uses a dynamic parameter that's not ported to PowerShell 6.
Remove a prompt in examples.
Change "Windows PowerShell" to "PowerShell".
Add blank lines.
Fix a formatting of the cmdlet and parameter names.
=> Add CMS cmdlets help topics to PS60 docs

reference/6/CimCmdlets/Invoke-CimMethod.md, reference/6/CimCmdlets/New-CimInstance.md
It's a partial fix of #2747 - for the CimCmdlets only.
=> Replace Windows PowerShell with PowerShell - the CimCmdlets

reference/3.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
To avoid long scrolling pages.
=> Remove line breaks after Param keyword in about_Functions_Advanced_Parameters.md

reference/docs-conceptual/core-powershell/web-access/authorization-rules-and-security-features-of-windows-powershell-web-access.md
Hello, @sdwheeler ,
"Missing space before \`\`\` , this current state is breaking en-us page"
=> C33477: adding indentation to cdeblock to avoid broken contenet

reference/6/Microsoft.PowerShell.Security/Get-PfxCertificate.md
Add Get-PxfCertificate to PS60 docs.
Including fixes:
Remove a prompt in examples.
Replace "Windows PowerShell" with "PowerShell".
Add blank lines.
Format cmdlet and parameter names.
=> Add Get-PxfCertificate to PS60 docs

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
All the direct download instructions have been updated to 6.0.3.
Ubuntu 14.04: 6.0.2-1 -> 6.0.3-1
Ubuntu 16.04: 6.0.2-1 -> 6.0.3-1
Debian 8: 6.0.2-1 -> 6.0.3-1
Debian 9: 6.0.2-1 -> 6.0.3-1
CentOS 7: 6.0.2-1 -> 6.0.3-1
RHEL 7: 6.0.2-1 -> 6.0.3-1
OpenSUSE 42.3: 6.0.2-1 -> 6.0.3-1
Fedora 27,28: 6.0.2-1 -> 6.0.3-1
Kali: 6.0.2-1 -> 6.0.3-1
Raspbian: 6.0.2 -> 6.0.3
=> Update referenced downloads to 6.0.3

reference/3.0/Microsoft.PowerShell.Utility/Get-EventSubscriber.md, reference/4.0/Microsoft.PowerShell.Utility/Get-EventSubscriber.md, reference/5.0/Microsoft.PowerShell.Utility/Get-EventSubscriber.md, reference/5.1/Microsoft.PowerShell.Utility/Get-EventSubscriber.md, reference/6/Microsoft.PowerShell.Utility/Get-EventSubscriber.md
The Example 2 does not work. The outputs are not correct.
* Get-EventSubcriber -> Get-EventSub **s** criber
* -SourceIdentifer -> -SourceIdentif **i** er
* PSEventJob -> System.Management.Automation.PSEventJob
* Added line breaks before `PS C:\>`
=> Fix Example 2 in Get-EventSubscriber.md

dsc/configDataCredentials.md
It looks like some typo or copy/paste issues were introduced, since variables are referenced that do not exist. I changed these to reference variables or configuration data value that do exist.
=> Fixed some errors in the first code example

reference/5.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Member.md, reference/6/Microsoft.PowerShell.Utility/Get-Member.md
=> Corrected alignment of output in Example 6

reference/6/Microsoft.PowerShell.Security/Get-PfxCertificate.md
Fixes #2150
Add Password and NoPromptForPassword parameters in the Syntax and Parameters sections.
=> Fixes #2150 Add Password and NoPromptForPassword parameters

developer/module/how-to-write-a-powershell-script-module.md
When I pasted this into VS, I noticed that there were 2 `{`. Only 1 is needed.
=> Fixed syntax error in powershell example code

reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md
The newline at the start of the file was causing the metadata to show as content in the docs
=> Fix metadata formatting

reference/3.0/Microsoft.PowerShell.Management/Set-Location.md, reference/4.0/Microsoft.PowerShell.Management/Set-Location.md, reference/5.0/Microsoft.PowerShell.Management/Set-Location.md, reference/5.1/Microsoft.PowerShell.Management/Set-Location.md
Make formatting consistent for all PowerShell versions.
Add blank lines.
Fix code and output blocks.
Format the cmdlet and parameter names.
Fix typos.
=> Fix formatting for Set-Location in PS3.0-5.1

reference/docs-conceptual/core-powershell/vscode/using-vscode.md
=> Fix a typo in using-vscode.md

wmf/5.0/dsc_statestatus.md
Hello, @sdwheeler,
Description: There are visible asterisks that maybe are intended for bold style.
=> C35472: Adding a space to well create bold content

reference/3.0/Microsoft.PowerShell.Management/Add-Content.md, reference/4.0/Microsoft.PowerShell.Management/Add-Content.md, reference/5.0/Microsoft.PowerShell.Management/Add-Content.md, reference/5.1/Microsoft.PowerShell.Management/Add-Content.md, reference/6/Microsoft.PowerShell.Management/Add-Content.md
Fixes #2864. Removed the part with creating new directory as it was not correct.
=> Fix Add-Content example

reference/6/Microsoft.PowerShell.Utility/Send-MailMessage.md
Fix #2851 
Send-MailMessage cmdlet was ported to PowerShell Core. The corresponding help topic is currently missing for PS6.
- Copied Send-MailMessage cmdlet help topic from PS5.1
- Fix Markdown style issues
- Fix DeliveryNotification help where the delivery notification will be sent to the *From* address and not *To* address as stated in a comment by Chaitu_a in https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Send-MailMessage?view=powershell-5.1
=> Add Send-MailMessage help topic to PS6 docs

developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
Verb        : Optimize
AliasPrefix : om
Group       : Common
Description : Increases the effectiveness of a resource
Verb        : Build
AliasPrefix : bd
Group       : Lifecycle
Description : Creates an artifact (usually a binary or document) out of some set of input files (usually source code or declarative documents)
Verb        : Deploy
AliasPrefix : dp
Group       : Lifecycle
Description : Sends an application, website, or solution to a remote target[s] in such a way that a consumer of that solution can access it after deployment is complete
No Acrolinx effort for this article
=> Added missing verbs to SDK docs to fix #1630

reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md, reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md
I've always found myself looking up the schema reference for specifics, but it is very hard to find. This should help with that.
=> Add link to Format.ps1xml schema reference

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md
Add GitHub user URLs to `What's new in PowerShell Core 6.x` documentation:
- [What's new in PowerShell Core 6.0](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6)
- [What's new in PowerShell Core 6.1](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-61?view=powershell-6)
cc @TimCurwick @iSazonov @oising @LDSpits @oising @rkeithhill @KirkMunro @IISResetMe @PowershellNinja @joandrsn @markekraus @Lee303 @TheFlyingCorpse @TheFlyingCorpse @PetSerAl @powercode @raghav710 @mklement0 @ergo3114 @sarithsutha @CloudyDino @maybe-hello-world @mcbobke @kvprasoon
@joeyaiello  …
=> Add GitHub user URLs to 'What's new in PowerShell Core 6.x' documentation

reference/6/Microsoft.PowerShell.Management/Test-Connection.md
Inconsistent with the source of TestConnectionCommand.cs and in general the Time To Live of packets has this meaning.
Description from source:
https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
---Line 85
/// <summary>
/// The number of times the Ping data packets can be forwarded by routers.
/// As gateways and routers transmit packets through a network,
/// they decrement the CurrentMTUSize Time-to-Live (TTL) value found in the packet header.
/// The default (from Windows) is 128 hops.
/// </summary>
...
---Line 95
[Alias("Ttl")]
=> Test-Connection TimeToLive description corrected

gallery/concepts/item-manifest-affecting-ui.md
This document affects the PowerShell Gallery.
The change adds necessary info on IconURI and the definition of the icon itself.
Addresses internal bug 1959068
=> Adding definition for IconURI and the icon details

developer/format/format-schema-xml-reference.md
The formatting xml applies to PSCore6 which uses .NET Core.  Change use of .NET Framework to neutral .NET.
=> change references from .NET Framework to simply .NET

reference/5.1/Microsoft.PowerShell.Management/Restart-Computer.md
1. In three cases, I specified that although the parameter accepts a "Default" value, this value is not the default value for the cmdlet.
2. Fixed several formatting artifacts. For example, in the Impersonation section, I replaced a " --" (clearly a typo) with a bullet.
=> Minor tweaks

reference/6/Microsoft.PowerShell.Management/Test-Connection.md
Fix #2956 
Change description for **MaxHops** (previously **TimeToLive**) parameter of `Test-Connection` cmdlet in **PowerShell Core 6.1**.
Add info about new aliases. PR: PowerShell/PowerShell#7850
=> Fix TimeToLive (MaxHops) parameter description.

reference/docs-conceptual/getting-started/fundamental/Learning-PowerShell-Names.md
The `-Help` parameter on any cmdlet does not work.
=> Remove unavailable `-Help` parameter

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Windows.md
It is best practice to avoid using powershell alias in production code as cd is hard to read and folks may not have linux support to understand what change directory  means.
https://blogs.technet.microsoft.com/heyscriptingguy/2013/04/08/using-powershell-aliases-best-practices/ to expand more on it.
=> Removing powershell alias' in example code

reference/5.1/Microsoft.PowerShell.Management/Disable-ComputerRestore.md
Line 118 `Windows Vistaand` to `Windows Vista and`
=> Fixed missing whitespace between words.

reference/5.1/Microsoft.PowerShell.Management/Get-Content.md
Incorrect spelling of hashtable
=> Corrected hashtable spelling in Example 6

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
Updated the Installation and Uninstallation Bash commands for Kali Linux distro to address the issue #2901.
Tested the steps in Kali Linux on Windows Subsystem for Linux (WSL) on the following version:
```sh
$ sudo cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2018.3"
VERSION_ID="2018.3"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```
```sh
$ pwsh
PowerShell 6.1.0
Copyright (c) Microsoft Corporation. All rights reserved.
https://aka.ms/pscore6-docs
Type 'help' to get help.
PS /> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core …
```
=> Updated Kali Linux Installation and Uninstallation

reference/5.0/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md
Fixing issue #2670 parameters with values based on [Microsoft.PowerShell.Archive.psm1](https://github.com/PowerShell/Microsoft.PowerShell.Archive/blob/master/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.psm1) parameters.
- Updated the `-CompressionLevel` default value from `None` to `Optimal`
- Updated the `-Update` default value from `None` to `False`
- Updated the `-Force` default value from `None` to `False`
- Updated the `-CompressionLevel` default value from `None` to `Optimal`
- Updated the `-Update` default value from `None` to `False`
- Updated the `-Force` default value from `None` to `False`
- Updated the `-CompressionLevel` default value from `None` to `Optimal`
- Updated the `-Update` default value from `None` to `False`
- Updated the `-Force` default value from …
=> Updated the parameters

jea/audit-and-report.md
In the "See also" section, there is a link "Audit user actions in a JEA session" that is a self-link on this page. This is confusing because the title and section implies this is a link to additional information, but instead returns you to the top of the page.
=> Remove self referencing link in "See also" section

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md
Per https://github.com/PowerShell/PowerShell/issues/7919, looking at the code, the change in PSCore6.1 is only in the Container path and not the VM path.  So the change in 6.1 is that we try starting pwsh.exe first then fallback to powershell.exe.  For VMs, there is no change and it tries the default microsoft.powershell endpoint which, by default, goes to Windows PowerShell (although it can be changed by the user).
=> corrected mention of PSDirect to apply to containers when trying pwsh first

reference/6/PSReadLine/Set-PSReadlineOption.md
Fixes #2639 by updating Set-PSReadlineOption's documented parameters in 6.1 to match PSReadline version 2.0.0, which is currently in use.
=> Update Set-PSReadlineOption.md in 6.1

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md
Fix link to PowerShell repo in **Disallowed Basic Auth over HTTP in PowerShell Remoting on Unix platforms** section.
=> Fix link in 'What-s-New-in-PowerShell-Core-61.md'

reference/6/Microsoft.PowerShell.Management/Start-Process.md
Mention that `-Wait` waits for the whole process tree, not just the process it ran.
This behavior appears to have started in powershell version 2.
=> Update Start-Process -Wait description

reference/docs-conceptual/PowerShell-Scripting.md
Without the added comma, the sentence does not make sense when "administrators and power-shell" are read together.
=> Add comma (see description)

reference/6/Microsoft.PowerShell.Utility/Remove-Alias.md
Addressing Docs needed for 'Add Remove-Alias Command' #3073
- New Remove-Alias draft doc
----
Hi @joeyaiello, @sdwheeler or @TravisEz13,
Anyone able to update or provide me the `online version: <URL>` in the markdown metadata for this new `Remove-Alias.md` doc? Or if you can do it on your end, that will be great.
----
=> Added Remove-Alias.md for PowerShell 6

reference/6/Microsoft.PowerShell.Management/Get-Content.md
=> Fix typo ("Enoding" -> "Encoding")

developer/cmdlet/attribute-types.md
Removed the link for cmdlet aliases in the section of parameter aliases.
.
=> Remove improper link for param alias

developer/windows-powershell-reference.md
"Getting Started with Windows PowerShell" and "Windows PowerShell TechNet Library" had broken links to an older structure. The msdn link took a few seconds to redirect, so I linked directly to the article.
=> Changed a few broken links.

reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md
Just marked 6, since I don't think anything earlier had Linux support
=> typo: Double word "OpenSUSE"

reference/3.0/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md, reference/4.0/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md, reference/5.0/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md, reference/5.0/Microsoft.PowerShell.Core/Wait-Job.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md, reference/5.1/Microsoft.PowerShell.Core/Wait-Job.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/6/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md, reference/6/Microsoft.PowerShell.Core/Wait-Job.md, reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md
=> typo: Double word "that"

reference/3.0/Microsoft.WsMan.Management/provider/new-item-for-plugin.md, reference/3.0/Microsoft.WsMan.Management/provider/wsman-provider.md, reference/4.0/Microsoft.WsMan.Management/provider/new-item-for-plugin.md, reference/4.0/Microsoft.WsMan.Management/provider/wsman-provider.md, reference/5.0/Microsoft.WsMan.Management/providers/new-item-for-plugin.md, reference/5.0/Microsoft.WsMan.Management/providers/wsman-provider.md, reference/5.1/Microsoft.WsMan.Management/Providers/New-Item-for-Plugin.md, reference/5.1/Microsoft.WsMan.Management/Providers/WSMan-Provider.md
=> typo: Double word "specifies"

reference/docs-conceptual/toc.yml
This is in the /reference folder, but it's outside any version-specific folder (it's the table of contents).
The page [Working with Objects](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/working-with-objects) page didn't really make sense on its own so I looked around and found [a website](https://forsenergy.com/en-us/windowspowershellhelp/html/7ecc94a4-015c-4459-ae58-85289ea09030.htm) that appears to mirror Microsoft documentation and contains a more logical hierarchy.
=> Move related help topics under Working with objects

reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Added documentation for new automatic variables as suggested in issue: https://github.com/PowerShell/PowerShell-Docs/issues/2229
=> Add new v6 automatic variables

.openpublishing.redirection.json
review link: https://review.docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/?branch=qinezh%2Fredirection&view=powershell-6
and old link such as https://review.docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/filesystem-provider/add-content-for-filesystem?view=powershell-6&branch=qinezh%2Fredirection will be redirected to https://review.docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/About/about_FileSystem_Provider?view=powershell-6&branch=qinezh%2Fredirection
The root cause is due to virtual redirection files are created in reference folder before the step of generating toc.yml. 
Previously, we design to create virtual redirection files in folder `virtual-directory-module` for reference to avoid this kind of conflict. So …
=> Update OPS redirection config file

reference/6/Microsoft.PowerShell.Utility/Format-Hex.md
Fix https://github.com/PowerShell/PowerShell-Docs/issues/2986
=> add new offset and count parameters for format-hex

reference/6/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/6/Microsoft.PowerShell.Core/Enable-PSRemoting.md
This change copies the Enable-PSRemoting and Disable-PSRemoting help files from 5.1 to  6 location, because they were missing.
In addition a NOTE was added stating that the cmdlets only apply to Windows platform.
Also, "Windows PowerShell" was changed to "PowerShell", except when specifying specific older Windows PowerShell versions.
=> Adding Enable/Disable PSRemoting cmdlets to PSCore6 documents

reference/6/Microsoft.PowerShell.Management/Get-Content.md
Break long lines along semantic line break locations
=> Update content to match PowerShell 6 behavior.

developer/module/how-to-write-a-powershell-script-module.md
The text references `Get-Calendar` but the actual script is for a function `Show-Calendar` - the difference is jarring and therefore I assume not intentional.
=> Change "Get-Calendar" to "Show-Calendar"

.vscode/cSpell.json
The cSpell.json is a setting file for the [streetsidesoftware.code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension that was added by #3221. The setting can suppress some warnings about "cmdlet", "dynamicparam", etc.
=> Add cSpell.json

reference/6/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
also fixed a broken about link, and added bare parens which appear to be missing. Fixes #3260
=> corrected arithmetic operator precedence

dsc/configData.md
Added information about the `$MyTypeName` special variable which is only available within a DSC configuration. The initial research was conducted and published here: https://blogs.msdn.microsoft.com/powersql/2017/10/31/dynamically-determine-a-dsc-configuration-name-inside-a-configuration/
=> Added the MyTypeName special variable.

dsc/pullServer.md
Switched the 2nd code example to use `Sample_xDscWebServiceRegistration` instead of `Sample_xDSCPullServer`. Also indented the code example from step number 4 so that the final step was included in the list. 
This fixes issue #3264
=> Fix configuration name used in example

reference/6/Microsoft.PowerShell.Utility/Write-Error.md
about_Throw should be a relative link within the docs repo. Existing fwlink was for an old version.
=> Fixed out of date redirect link to be relative

reference/6/Microsoft.PowerShell.Utility/Write-Verbose.md
about_CommonParameters is now being linked relatively
=> Corrected some out of date redirect links

reference/6/Microsoft.PowerShell.Utility/Get-TypeData.md
redirect was targeting a specific version of the docs instead of being generic
=> fixed an old redirect link to an about_ page

reference/docs-conceptual/core-powershell/console/PowerShell.exe-Command-Line-Help.md
I read the original version of this paragraph to mean the exact opposite of what was intended, so I thought I would clarify it. Needed some whitespace separating the first and second examples, and in the second example I reordered it so the result comes after the setup.
=> Clarified use of environment variables in -File

contributing/3-STYLE-GUIDE.md
paramter->parameter, and a Parameter was written both in bold and with a hyphen prefix, which is disallowed.
=> fixed internal inconsistency and typo

reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md
added missing about_ page links, and updated a link to the PowerShell API docs that was redirecting from MSDN
=> added and fixed internal links

reference/docs-conceptual/core-powershell/console/PowerShell.exe-Command-Line-Help.md
Tried to stick to the style guide as it pertains to backticks, bold, semantic linefeeds, and URLs.
Moved some sections around to be more of a logical flow; first introducing the concept, then elaborating on inputs and outputs, and finally detailing each acceptable input type for `-Command`.
I wanted to clarify exactly why script blocks only work in powershell.exe, and I think this does a good job of explaining why types are important, and why attempting to write a script block when running from cmd.exe usually gets it spat back out at you.
--------------------------——
=> Revised powershell.exe -Command parameter

reference/6/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
This information was displaying on docs.microsoft.com. I believe it needs to be surrounded by the three hyphens to work properly.
=> fixed broken info box header

developer/provider/windows-powershell-provider-overview.md, dsc/troubleshooting.md, reference/3.0/Microsoft.PowerShell.Core/Import-Module.md, reference/4.0/Microsoft.PowerShell.Core/Import-Module.md, reference/5.0/Microsoft.PowerShell.Core/Get-Job.md, reference/5.0/Microsoft.PowerShell.Core/Import-Module.md, reference/5.0/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/5.0/Microsoft.PowerShell.Core/Receive-PSSession.md, reference/5.0/Microsoft.PowerShell.Core/Save-Help.md, reference/5.0/Microsoft.PowerShell.Management/Show-ControlPanelItem.md, reference/5.1/Microsoft.PowerShell.Core/Get-Job.md, reference/5.1/Microsoft.PowerShell.Core/Import-Module.md, reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/5.1/Microsoft.PowerShell.Core/Receive-PSSession.md, reference/5.1/Microsoft.PowerShell.Core/Save-Help.md, reference/5.1/Microsoft.PowerShell.Management/Show-ControlPanelItem.md, reference/6/Microsoft.PowerShell.Core/Get-Job.md, reference/6/Microsoft.PowerShell.Core/Import-Module.md, reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md, reference/6/Microsoft.PowerShell.Core/Receive-PSSession.md, reference/6/Microsoft.PowerShell.Core/Save-Help.md
Hi, I'm the typo police. :cop:
=> Fix typo: cmldet -> cmdlet

reference/5.0/Microsoft.PowerShell.Management/New-WebServiceProxy.md, reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md, reference/6/Microsoft.PowerShell.Management/New-PSDrive.md, reference/6/Microsoft.PowerShell.Utility/Write-Information.md, reference/docs-conceptual/getting-started/fundamental/Learning-PowerShell-Names.md
The `Persist` parameter of `New-PSDrive` is only supported on Windows. Persist will be removed on UNIX by https://github.com/PowerShell/PowerShell/pull/8291. Add this information to the documentation of the `Persist` parameter.
Fix #3316.
=> Document removal of `Persist` parameter from `New-PSDrive` on UNIX

reference/6/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
Second item was missing bullet, and there was a trailing extraneous bullet
=> Fixed broken bulleted list

reference/6/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md
=> Fixing #3369 - Added docs for `-passthru`

reference/3.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/4.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/5.0/Microsoft.PowerShell.Utility/Get-Member.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Member.md, reference/6/Microsoft.PowerShell.Utility/Get-Member.md
* Fix syntax error
* Fix command sequence and commands used
* Fix unclear example sequence
Thanks to [Ramon TAN](https://powershell.org/forums/topic/get-member-examples-different-results-on-my-pc/#post-127867) for stumbling across this in confusion!
=> Fix Example for Get-Member -InputObject

reference/3.0/Microsoft.PowerShell.Core/About/about_logical_operators.md, reference/4.0/Microsoft.PowerShell.Core/About/about_logical_operators.md, reference/5.0/Microsoft.PowerShell.Core/About/about_logical_operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_logical_operators.md, reference/6/Microsoft.PowerShell.Core/About/about_logical_operators.md
Fixed missing closing code marker
=> fix table format - fix #3374

reference/5.0/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/5.1/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md
=> Fix mandatory parameter error in Expand-Archive

reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md
I think Example 3 incorrectly says directory instead of sub-directories
=> Example 3 incorrectly says directory instead of sub-directories

reference/docs-conceptual/components/ise/Introducing-the-Windows-PowerShell-ISE.md
Added verbiage around support for ISE with PowerShell V6 and beyond.  
Made use of ISE consistent as the abbreviation for the ISE in opening para.  
Noted the ISE is in maintenance mode.   
Also updated words that previously indicated ISE was 'new' and added a line to VS-Code.  
Addresses issue #3423
=> Fix #3423 - Update Introducing-the-Windows-PowerShell-ISE.md

reference/6/Microsoft.PowerShell.Utility/Format-Table.md
Don't merge until https://github.com/PowerShell/PowerShell/pull/8481 is merged
=> add `-RepeatHeader` switch for `Format-Table`

jea/session-configurations.md
Update with a note to describe new behavior for VirtualAccountGroups effective with the following changes:
Bug 18364902: SeServiceLogonRight not getting cleaned up after PowerShell remoting session ends
Bug 19395572: [2016] Backport Pull Request 2460888: Skip SeServiceLogon calls when group set in RunAsVirtualAccountGroups
Bug 19636068: [2019] Backport Pull Request 2460888: Skip SeServiceLogon calls when group set in RunAsVirtualAccountGroups
=> Update JEA Sessions-configurations.md

reference/3.0/Microsoft.PowerShell.Utility/Format-Custom.md, reference/3.0/Microsoft.PowerShell.Utility/Format-List.md, reference/3.0/Microsoft.PowerShell.Utility/Format-Table.md, reference/3.0/Microsoft.PowerShell.Utility/Format-Wide.md, reference/4.0/Microsoft.PowerShell.Utility/Format-Custom.md, reference/4.0/Microsoft.PowerShell.Utility/Format-List.md, reference/4.0/Microsoft.PowerShell.Utility/Format-Table.md, reference/4.0/Microsoft.PowerShell.Utility/Format-Wide.md, reference/5.0/Microsoft.PowerShell.Utility/Format-Custom.md, reference/5.0/Microsoft.PowerShell.Utility/Format-List.md, reference/5.0/Microsoft.PowerShell.Utility/Format-Table.md, reference/5.0/Microsoft.PowerShell.Utility/Format-Wide.md, reference/5.1/Microsoft.PowerShell.Utility/Format-Custom.md, reference/5.1/Microsoft.PowerShell.Utility/Format-List.md, reference/5.1/Microsoft.PowerShell.Utility/Format-Table.md, reference/5.1/Microsoft.PowerShell.Utility/Format-Wide.md, reference/6/Microsoft.PowerShell.Utility/Format-Custom.md, reference/6/Microsoft.PowerShell.Utility/Format-List.md, reference/6/Microsoft.PowerShell.Utility/Format-Table.md, reference/6/Microsoft.PowerShell.Utility/Format-Wide.md
Work around problem caused by PowerShell/PlatyPS#422
=> Added example to fix parameter format problem

reference/5.0/PSReadline/Set-PSReadlineOption.md, reference/5.1/PSReadline/Set-PSReadlineOption.md, reference/6/PSReadLine/Set-PSReadlineOption.md
Using `Visible` fails with:
```powershell
> Set-PSReadlineOption -BellStyle Visible
Set-PSReadlineOption : Cannot bind parameter 'BellStyle'. Cannot convert value "Visible" to type "Microsoft.PowerShell.BellStyle". Error: "Unable to
match the identifier name Visible to a valid enumerator name. Specify one of the following enumerator names and try again:
None, Visual, Audible"
```
Modify all documentation versions; not present in 4.0.
I'm not seeing a 6.next documentation, but if 6.next was copied from 6.0 it also needs the fix.
- [?] Impacts 6.next document
=> BellStyle Visual not Visible

gallery/how-to/publishing-packages/publishing-a-package.md
Update the examples to use code tags to differentiate them on the page. Also make them bullet points so they stand apart from each other.
Also fix the `Publish-Module` Example to use working command.
Fixes #3471
=> Update examples to use code tags

reference/4.0/PSDesiredStateConfiguration/Start-DscConfiguration.md, reference/5.0/PSDesiredStateConfiguration/Start-DscConfiguration.md, reference/5.1/PSDesiredStateConfiguration/Start-DscConfiguration.md
1. Changed FWLink to a direct link into docs (addresses issue #3479 )
2. Fixed a typo pointing to an old technet article that was missing anyway
3. Ensured the urls are local neutral.
- [x ] Impacts 4.0 document
- [x ] This issue only shows up in version (list version(s) here) of the document
=> updated broken fwlink, ensured urls are locale neutral in the documents

gallery/how-to/publishing-packages/publishing-a-package.md
Fixed a broken link, minor copyedits, paragraph reflow.
Issue #3470
=> Closes #3470 - Publishing Guidelines link is invalid

reference/6/Microsoft.PowerShell.Core/About/about_Modules.md
The article "Writing a Windows PowerShell Module" is no longer on MSDN; it is now on Microsoft Docs. Also, "Windows" was omitted. Now, it is true that "Windows PowerShell" has become "PowerShell" since version 6, but the former MSDN contents have not changed; both their links and contents still say "Windows PowerShell".
=> Fixed a typo, a link and a fact

reference/docs-conceptual/install/Windows-PowerShell-System-Requirements.md
**superceeded** -> **superseded**
in Windows-PowerShell-System-Requirements.md
`supercede` is generally considered to be less correct than `supersede`, but either way the past-tense is never spelled with a double-e.
=> Fix typo in install docs
