MicrosoftDocs/PowerShell-Docs

reference/5.1/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
reference/6/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
reference/7.0/Microsoft.PowerShell.Security/ConvertTo-SecureString.md
reference/7.1/Microsoft.PowerShell.Security/ConvertTo-SecureString.md

Fixes [AB#1786598](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1786598) - Fixes #6784 - add warning about plain text.

Fixes #6784 - add warning about plain text.

---

reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md
reference/6/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.1/Microsoft.PowerShell.Utility/Compare-Object.md

Copy changes in #6787 to other versions

---

reference/docs-conceptual/PowerShell-Support-Lifecycle.md
reference/docs-conceptual/dev-cross-plat/Writing-Portable-Modules.md
reference/docs-conceptual/how-to-use-docs.md
reference/docs-conceptual/install/Installing-PowerShell.md
reference/docs-conceptual/learn/Glossary.md
reference/docs-conceptual/learn/Using-Tab-Expansion.md
reference/docs-conceptual/learn/deep-dives/overview.md
reference/docs-conceptual/learn/more-powershell-learning.md
reference/docs-conceptual/learn/ps101/00-introduction.md
reference/docs-conceptual/learn/ps101/05-formatting-aliases-providers-comparison.md
reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md
reference/docs-conceptual/learn/remoting/Running-Remote-Commands.md
reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
reference/docs-conceptual/learn/remoting/WSMan-Remoting-in-PowerShell-Core.md
reference/docs-conceptual/learn/remoting/WinRMSecurity.md
reference/docs-conceptual/learn/remoting/jea/audit-and-report.md
reference/docs-conceptual/learn/remoting/jea/overview.md
reference/docs-conceptual/learn/remoting/jea/prerequisites.md
reference/docs-conceptual/learn/remoting/jea/register-jea.md
reference/docs-conceptual/learn/remoting/jea/role-capabilities.md
reference/docs-conceptual/learn/remoting/jea/security-considerations.md
reference/docs-conceptual/learn/remoting/jea/session-configurations.md
reference/docs-conceptual/learn/remoting/jea/using-jea.md
reference/docs-conceptual/overview.md
reference/docs-conceptual/whats-new/breaking-changes-ps6.md
reference/docs-conceptual/whats-new/cmdlet-versions.md
reference/docs-conceptual/whats-new/known-issues-ps6.md
reference/docs-conceptual/whats-new/module-compatibility.md

Related to [AB#1786853](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1786853)
Adding descriptions to conceptual articles to reduce build warnings and improve SEO.

Update descriptions - Part 1

---

reference/5.1/Microsoft.PowerShell.Security/Get-Credential.md
reference/6/Microsoft.PowerShell.Security/Get-Credential.md
reference/7.0/Microsoft.PowerShell.Security/Get-Credential.md
reference/7.1/Microsoft.PowerShell.Security/Get-Credential.md

Fixes [AB#1786905](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1786905) - Fixes #6789 - add SDK link and fix exmaple numbers

Fixes 6789 - add SDK link and fix exmaple numbers

---

reference/docs-conceptual/dev-cross-plat/vscode/using-vscode-for-debugging-compiled-cmdlets.md

I ran through this doc and realized for my particular module I needed an extra property on my launch.json. I don't think everyone will need it, so I have it as a Note.

add call out for justMyCode

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

Fixes [AB#1788024](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1788024) - Fixes #6803 - add SupportsWildcards()

Fixes #6803 - add SupportsWildcards()

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
reference/6/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md

Fixes [AB#1787994](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1787994) - Fixes #6804 - add note about misconfigured policy

Fixes #6804 - add note about misconfigured policy

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md

Fixes [AB#1788058](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1788058) - Fixes #5145 - Add upgrade note

Fixes #5145 - Add upgrade note

---

reference/module/index.md

Updated PowerShell module browser quick filter for Az to version 5.0.0

Updated azps module browser quick filter

---

reference/docs-conceptual/dsc/reference/resources/packagemanagement/PackageManagementDscResource.md
reference/docs-conceptual/dsc/reference/resources/packagemanagement/PackageManagementSourceDscResource.md
reference/docs-conceptual/dsc/reference/resources/windows/archiveResource.md
reference/docs-conceptual/dsc/reference/resources/windows/environmentResource.md
reference/docs-conceptual/dsc/reference/resources/windows/fileResource.md
reference/docs-conceptual/dsc/reference/resources/windows/groupResource.md
reference/docs-conceptual/dsc/reference/resources/windows/groupSetResource.md
reference/docs-conceptual/dsc/reference/resources/windows/logResource.md
reference/docs-conceptual/dsc/reference/resources/windows/packageResource.md
reference/docs-conceptual/dsc/reference/resources/windows/processSetResource.md
reference/docs-conceptual/dsc/reference/resources/windows/registryResource.md
reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md
reference/docs-conceptual/dsc/reference/resources/windows/serviceResource.md
reference/docs-conceptual/dsc/reference/resources/windows/serviceSetResource.md
reference/docs-conceptual/dsc/reference/resources/windows/userResource.md
reference/docs-conceptual/dsc/reference/resources/windows/waitForAllResource.md
reference/docs-conceptual/dsc/reference/resources/windows/waitForAnyResource.md
reference/docs-conceptual/dsc/reference/resources/windows/waitForSomeResource.md
reference/docs-conceptual/dsc/reference/resources/windows/windowsFeatureSetResource.md
reference/docs-conceptual/dsc/reference/resources/windows/windowsOptionalFeatureResource.md
reference/docs-conceptual/dsc/reference/resources/windows/windowsOptionalFeatureSetResource.md
reference/docs-conceptual/dsc/reference/resources/windows/windowsPackageCabResource.md
reference/docs-conceptual/dsc/reference/resources/windows/windowsProcessResource.md
reference/docs-conceptual/dsc/reference/resources/windows/windowsfeatureResource.md
reference/includes/dsc-resources.md

Fixes [AB#1789221](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1789221) - Fixes #6760 - add note linking updated resources

Fixes #6760 - add note linking updated resources

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
reference/docs-conceptual/install/PowerShell-Core-on-ARM.md

Fixes [AB#1789347](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1789347) - Fixes #6821 - update ARM install instructions

Fixes #6821 - update ARM install instructions

---

reference/docs-conceptual/learn/ps101/02-help-system.md

Fixes [AB#1789463](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1789463) - Fixes #6824 - fix typos

Fixes #6824 - fix typos

---

.openpublishing.build.ps1

Remove Aliases

---

reference/5.1/Microsoft.PowerShell.Utility/Get-Culture.md
reference/5.1/Microsoft.PowerShell.Utility/Import-LocalizedData.md
reference/5.1/Microsoft.PowerShell.Utility/Set-Variable.md
reference/6/Microsoft.PowerShell.Utility/Get-Culture.md
reference/6/Microsoft.PowerShell.Utility/Import-LocalizedData.md
reference/6/Microsoft.PowerShell.Utility/Set-Variable.md
reference/7.0/Microsoft.PowerShell.Utility/Get-Culture.md
reference/7.0/Microsoft.PowerShell.Utility/Import-LocalizedData.md
reference/7.0/Microsoft.PowerShell.Utility/Set-Variable.md
reference/7.1/Microsoft.PowerShell.Utility/Get-Culture.md
reference/7.1/Microsoft.PowerShell.Utility/Import-LocalizedData.md
reference/7.1/Microsoft.PowerShell.Utility/Set-Variable.md

Fixes [AB#1789519](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1789519) - Fixes #6830 - fix example formatting

Fixes #6830 - fix example formatting

---

reference/6/Microsoft.PowerShell.Core/New-ModuleManifest.md
reference/7.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
reference/7.1/Microsoft.PowerShell.Core/New-ModuleManifest.md

Fixes [AB#1789647](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1789647) - Fixes #4249 - document FileList property behavior

Fixes #4249 - document FileList property behavior

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md

Add a link directly to the latest release. This is useful as there may be many Pre-releases since the 'Latest release'.

Add link directly to latest release in the Install instructions

---

reference/docs-conceptual/windows-powershell/ise/Exploring-the-Windows-PowerShell-ISE.md

Fixes [AB#1790164](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1790164)
- Changed the `ms.topic` to `landing-page` to track correct statistics
- Added links to related article to improve click-thru
- Removed outdated information

Update F1 landing article to improve performance

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
reference/docs-conceptual/windows-powershell/ise/Exploring-the-Windows-PowerShell-ISE.md

11/03 Publishing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/6/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Scopes.md

Fixes [AB#1790401](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1790401) - Fixes #6541 - clarify scopes and session states

Fixes #6541 - clarify scopes and session states

---

reference/docs-conceptual/dsc/tutorials/bootstrapDsc.md

Fixes [AB#1791575](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1791575) - Fixes #6860 - update registry instructions
Fixes [AB#1791576](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1791576) - Fixes #6858
Fixes [AB#1791577](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1791577) - Fixes #6859
[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributin …

Fixes #6860 - update registry instructions

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Variables.md
reference/6/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
reference/6/Microsoft.PowerShell.Core/About/about_Operators.md
reference/6/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Variables.md

Fixes [AB#1791816](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1791816) - Fixes #6857 - expand variable syntax
- Expanded the description of variable syntax
- Linked operator article to variable article
- Added `@{}` to Operator Precedence table

Fixes #6857 - expand variable syntax

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md
reference/6/Microsoft.PowerShell.Core/About/about_PSModulePath.md
reference/7.0/Microsoft.PowerShell.Core/About/about_PSModulePath.md
reference/7.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md

Fixes [AB#1792028](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1792028) - Fixes #6867 - describe module search behavior

Fixes #6867 - describe module search behavior

---

reference/5.1/PackageManagement/Install-PackageProvider.md
reference/6/PackageManagement/Install-PackageProvider.md
reference/7.0/PackageManagement/Install-PackageProvider.md
reference/7.1/PackageManagement/Install-PackageProvider.md

Fixes [AB#1792452](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1792452) - fix formatting of Install-PackageProvider 
Related to #6868

Fix formatting

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md
reference/6/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/6/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md
reference/6/Microsoft.PowerShell.Core/About/about_Thread_Jobs.md
reference/6/Microsoft.PowerShell.Management/Start-Process.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Thread_Jobs.md
reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Remote_Jobs.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Thread_Jobs.md
reference/7.1/Microsoft.PowerShell.Management/Start-Process.md

Fixes [AB#1792028](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1792028) - Fixes #6864 - clarify job vs nohup behavior
This PR restructures the about_ articles covering PowerShell jobs.
- Added notes about the parent/child relationships between jobs and the session that creates them
- Warn that jobs are terminated with the parent session exits
- Clarify the differences between "remote" jobs and thread-based jobs (eg. perf and serialization)
- Add an example for running jobs in a detached session using Invoke-Command
- Add a nohup example (with context) to Start-Process
- If the PR is …

Fixes #6864 - clarify job vs nohup behavior

---

reference/docs-conceptual/PowerShell-Support-Lifecycle.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
reference/docs-conceptual/install/PowerShell-Core-on-ARM.md
reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-71.md

Updated release notes for supported platforms

Update release notes

---

.github/ISSUE_TEMPLATE/Documentation_Issue.md
.github/PULL_REQUEST_TEMPLATE.md
.github/SUPPORT.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-71.md

Fixes [AB#1792789](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1792789) - Fixes #6871 - fix typos
Fixes [AB#1792787](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1792787) - Fixes #6878 - fix typos

Fixes #6878 - fix typos

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-71.md

Fixes [AB#1792797](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1792797) - Fixes #6882 - update change log

Fixes #6882 - update change log

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md

Fixes Typo in ubuntu 20.4 powershell installation command. 
Fixes #6885 
Fixes [AB#1792890](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1792890)

[Fixes #6885] - Fixes Typo in Installation command.

---

reference/docs-conceptual/learn/ps101/09-functions.md

Link was broken at bottom of page. 
Fixes #6890 
Fixes [AB#1793125](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1793125)

Fixes 6890 - Updates PS101: Functions

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md

Fix package names for install articles

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/6/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md

Removes Keywords sections from about_Language_Modes
Fixes #6887 
Fixes [AB#1793132](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1793132)

Fixes 6887 - Updates about_Language_Modes

---

reference/7.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
reference/7.1/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.1/Microsoft.PowerShell.Management/Get-Item.md
reference/docs-conceptual/learn/Using-Tab-Expansion.md

Updates documentation for experimental features going mainstream in powershell 7.1 and 7.0
Fixes #6897 
Fixes [AB#1793431](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1793431)

Fixes #6897 - Updates for experimental features. 

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md

Fixes [AB#1793675](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1793675) - Fixes #6901 - Update limitations of MSIX package

Fixes #6901 - Update limitations of MSIX package

---

reference/docs-conceptual/whats-new/module-compatibility.md

As of PowerShell 7.1 Appx isn't natively compatible. The module compatibility list  needs to be updated to address this. 
Fixes #6902 
Fixes [AB#1793527](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1793527)

Fixes #6902 - Updates Module Compatability

---

reference/5.1/PSReadLine/About/about_PSReadLine.md
reference/6/PSReadLine/About/about_PSReadLine.md
reference/7.0/PSReadLine/About/about_PSReadLine.md
reference/7.1/PSReadLine/About/about_PSReadLine.md

Updates PSReadline to add information abotu Predictive IntelliSense.
Fixes #6896 
Fixes [AB#1793684](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1793684)

Fixes #6896 - Updates about PSReadLine

---

reference/docs-conceptual/dev-cross-plat/resolving-dependency-conflicts.md

Fixes https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6916.

Fix typos in dependency conflict doc

---

reference/5.1/Microsoft.PowerShell.Management/New-Service.md
reference/7.0/Microsoft.PowerShell.Management/New-Service.md
reference/7.1/Microsoft.PowerShell.Management/New-Service.md
reference/7.2/Microsoft.PowerShell.Management/New-Service.md

Fixes [AB#1794430](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1794430) - Fixes #6922 - add note about -BinaryPath

Fixes #6922 - add note about -BinaryPath

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Using.md

Fixes [AB#1794457](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1794457) - Fixes #6921 - Document using module behavior

Fixes #6921 - explain relative path resolution

---

reference/module/index.md

Updated links:
- powershell-7.1
- azps-5.1.0

Update module browser quick links

---

reference/docs-conceptual/install/PowerShell-Core-on-ARM.md

Fixes [AB#1794622](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1794622) - Fixes #6929 - fix typo in ARM doc

Fixes #6929 - fix typo in ARM doc

---

reference/docs-conceptual/dsc/getting-started/lnxGettingStarted.md

Updated the getting-started/lnxgettingstarted.md article to reflect Ubuntu 18.04 is supported and link to the latest download on GitHub repo for the DSC for Linux release.
- [X ] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [X ] PR has a meaningful title
- [X ] PR is targeted at the _staging_ branch
- [X ] All relevant versions updated
- [X ] This PR is ready to merge and is not **Work in Progress**
[contrib]: …

Update to reflect latest ver and support for U1804

---

reference/7.2/PSReadLine/About/about_PSReadLine.md
reference/7.2/PSReadLine/Set-PSReadLineOption.md

Fixes [AB#1793682](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1793682) - Fixes #6812 - updates for PSReadLine 2.2.0-beta1

Fixes #6812 - updates for PSReadLine 2.2.0-beta1

---

reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md

Fixes [AB#1797461](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1797461) - Fixes #6948 - Fix -Force example

Fixes #6948 - Fix -Force example

---

reference/docs-conceptual/gallery/how-to/getting-support/contacting-administrators.md
reference/docs-conceptual/gallery/how-to/getting-support/troubleshooting-cmdlets.md
reference/docs-conceptual/gallery/overview.md

Add link to status page and update link to issues

Add link to status page and update link to issues

---

reference/5.1/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.0/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.1/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.2/Microsoft.PowerShell.Management/Set-Clipboard.md

Fixes [AB#1798418](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1798418) - Fixes #6949 - add pipeline example

Fixes #6949 - add pipeline example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md
reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Modules.md
reference/7.0/Microsoft.PowerShell.Core/Import-Module.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Modules.md
reference/7.1/Microsoft.PowerShell.Core/Import-Module.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Modules.md
reference/7.2/Microsoft.PowerShell.Core/Import-Module.md

Fixes [AB#1798455](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1798455) - Fixes #6970 - clarify module concepts

Fixes #6970 - clarify module concepts

---

reference/docs-conceptual/learn/ps101/09-functions.md

Fixes [AB#1798921](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1798921) - Fixes #6968 - add note about muliple params & link

Fixes #6968 - add note about muliple params & link

---

reference/7.0/ThreadJob/Start-ThreadJob.md
reference/7.1/ThreadJob/Start-ThreadJob.md
reference/7.2/ThreadJob/Start-ThreadJob.md

Fixes [AB#1799013](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1799013) - Fixes #6984 - Add example and syntax for StreamingHost

Fixes #6984 - Add example and syntax for StreamingHost

---

reference/docs-conceptual/gallery/getting-started.md
reference/docs-conceptual/gallery/how-to/getting-support/troubleshooting-cmdlets.md

Update hostnames for gallery endpoints
- sync names between articles in both locations

update hostnames for gallery endpoints

---

reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.1/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Export-Csv.md

Fixes [AB#1799760](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1799760) - Fixes #6993 - quote parameters added in 7.0

Fixes #6993 - quote parameters added in 7.0

---

reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md
reference/7.0/Microsoft.PowerShell.Utility/Measure-Command.md
reference/7.1/Microsoft.PowerShell.Utility/Measure-Command.md
reference/7.2/Microsoft.PowerShell.Utility/Measure-Command.md

Customer noticed example three was broken
Fixes #6996 

Fixes #6996 - Updates Measure command

---

reference/module/index.md

Updated quick filter for Az PowerShell module to version 5.2

Updated azps quickfilter to latest version

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md

Fixes [AB#1800587](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1800587) - Fixes #6962 - add required package for Ubuntu

Fixes #6962 - add required package for Ubuntu

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fixes [AB#1800585](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1800585) - Fixes #7000 - add collection example

Fixes #7000 - add collection example

---

reference/docs-conceptual/dsc/pull-server/secureMOF.md

Fixes [AB#1800634](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1800634) - Fixes #6856 - point to PSPKI module

Fixes #6856 - point to PSPKI module

---

reference/docs-conceptual/dsc/managing-nodes/metaConfig.md

Adds note about the typical use cases for `RefreshFrecuencyMins` and `ConfigurationModeFrequencyMins`.
Fixes #6848 
Fixes [AB#1800651](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1800651)

Fixes #6846 - Updates Metaconfig

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

Fixes [AB#1801508](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1801508) - Fixes #7013 -add terms "expandable" and "verbatim"

Fixes #7013 -add terms "expandable" and "verbatim"

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Requires.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Requires.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Requires.md

Fixes [AB#1801559](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1801559) - Fixes #7016 - requires assembly is deprecated

Fixes #7016 - requires assembly is deprecated

---

reference/5.1/Microsoft.PowerShell.Security/Test-FileCatalog.md
reference/7.0/Microsoft.PowerShell.Security/Test-FileCatalog.md
reference/7.1/Microsoft.PowerShell.Security/Test-FileCatalog.md
reference/7.2/Microsoft.PowerShell.Security/Test-FileCatalog.md

add -Detailed parameter in Example 2 Validate a file catalog with detailed output

Fix Test-FileCatalog Example 2 detailed output

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Fixes [AB#1801629](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1801629) - Fixes #7028 - add $input example

Fixes #7028 - add $input example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fixes [AB#1802163](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1802163) - Fixes #7039 - fix typo

Fixes #7039 - fix typo

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md

Fixes [AB#1802829](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1802829) - Fixes #7059 - Clarify UTF-16LE

Fixes #7059 - Clarify UTF-16LE

---

reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md

Fixes incorrect information in Foreach-Object.md. -ThrottleLimit default value was marked as None when it should be 5.
Fixes #7069
Fixes [AB#1803404](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1803404)

Fixes #7069 - Updates ForEach-Object

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md

Fix wording

---

reference/7.1/Microsoft.PowerShell.Core/Get-Command.md

"Name" should be "-Name" in example 10

Fix typo in example 10

---

reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
reference/7.0/Microsoft.PowerShell.Core/New-ModuleManifest.md
reference/7.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
reference/7.2/Microsoft.PowerShell.Core/New-ModuleManifest.md
reference/docs-conceptual/developer/module/how-to-write-a-powershell-module-manifest.md

Updates parameter values for **PowerShellVersion** parameter in New-ModuleManifest
Fixes #7083
Fixes [AB#1804866](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1804866)

Fixes #7083 - Updates New-ModuleManifest + 1 more

---

reference/docs-conceptual/developer/prog-guide/runspace04-code-samples.md

Updates example for bad link
Fixes #7086
Fixes [AB#1804794](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1804794)

Fixes #7086 - Updates runspace04-code-samples

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md

Fixes [AB#1669514](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669514) - Fixes #7093 - document ADD_FILE_CONTEXT_MENU_RUNPOWERSHELL

Fixes #7093 - document ADD_FILE_CONTEXT_MENU_RUNPOWERSHELL

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md

Improves wording around unique parameter set requirements.
Fixes #7089
Fixes [AB#1805060](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1805060)

Fixes #7089 - Updates about_Parameter_Sets

---

reference/docs-conceptual/dsc/reference/resources/windows/serviceResource.md

Syntax code block in article serviceResource.md incorrectly lists "Ignore" as a valid state, which is inaccurate. 
- [ X] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ X] PR has a meaningful title
- [ X] PR is targeted at the _staging_ branch
- [ X] All relevant versions updated
- [X ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [ X] This PR is ready to merge and is not **Work in Progress**
title and remove the prefix when the PR …

updated DSC PowerShell code example

---

reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md

Updates deep learning about hastables to include a new method for deep cloning.
Fixes #7081
Fixes [AB#1805963](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1805963)

Fixes #7081 - Updates everything-about-hashtable

---

reference/7.1/Microsoft.PowerShell.Core/About/about_Redirection.md

} 3>&1 2>&1 > P:\Temp\redirection.log
correct is
} 3>&1 2>&1 > C:\Temp\redirection.log

line 101: typo in path name (disk name)

---

reference/docs-conceptual/developer/help/examples-of-comment-based-help.md

Updates prompts in examples to remove C Drive.
Fixes #7121
Fixes [AB#1807209](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1807209)

Fixes #7121 - Updates examples-of-comment-based-help

---

reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md

Fixes [AB#1809053](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1809053) - Fixes #7143 - add note about %j

Fixes #7143 - add note about %j

---

reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md

Fix macOS text casing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Using.md

Fixes [AB#1809059](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1809059) - Fixes #7096 - update gotchas for classes

Fixes #7096 - update gotchas for classes

---

reference/5.1/Microsoft.PowerShell.Utility/Out-String.md
reference/7.0/Microsoft.PowerShell.Utility/Out-String.md
reference/7.1/Microsoft.PowerShell.Utility/Out-String.md
reference/7.2/Microsoft.PowerShell.Utility/Out-String.md

Updates `Out-String` to clarify **Stream** parameter behavior.
Fixes #7133
Fixes [AB#1808728](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1808728) 1808729

Fixes #7133 - Updates Out-String

---

reference/docs-conceptual/install/Installing-PowerShell.md

remove uneeded use of the word 'core'

---

reference/5.1/Microsoft.PowerShell.Utility/Out-String.md
reference/7.0/Microsoft.PowerShell.Utility/Out-String.md
reference/7.1/Microsoft.PowerShell.Utility/Out-String.md
reference/7.2/Microsoft.PowerShell.Utility/Out-String.md

Updates `Out-String` **Stream** Parameter for clarification on behavior
Fixes #7153
Fixes [AB#1809568](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1809568)

Fixes #7153 - Updates Out-String

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fixes [AB#1809709](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1809709) - Fixes #7156 - fix typo in example

Fixes #7156 - fix typo in example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Using.md

Fixes [AB#1809732](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1809732) - Fixes #7145 - add dev notes

Fixes #7145 - add dev notes

---

reference/module/index.md

Updated AzPS quick filter to v5.4.0

Updated AzPS quick filter to v5.4.0

---

reference/docs-conceptual/dsc/resources/resources.md

Fixes [AB#1810450](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1810450) - Fixes #7164 - Fix typo

Fixes #7164 - Fix typo

---

reference/7.1/Microsoft.PowerShell.Utility/Set-Variable.md

Fix incorrect casing for option value

---

reference/docs-conceptual/gallery/how-to/getting-support/troubleshooting-cmdlets.md

Adds endpoint and info for troubleshooting cmdlets doc
Fixes #7168
Fixes [AB#1810768](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1810768)

Fixes #7168 - Updates troubleshooting-cmdlets

---

reference/7.2/Microsoft.PowerShell.Utility/Import-PowerShellDataFile.md

Adds **SkipLimitCheck** parameter for `Import-PowerShellDataFile`
Fixes #7170
Fixes [AB#1811014](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1811014)

Fixes #7170 - Updates Import-PowerShellDataFile

---

reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Json.md

Adds information about new **Depth** warning in `ConvertTo-Json`
Fixes #7172
Fixes [AB#1811022](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1811022)

Fixes #7172 - Updates ConvertTo-Json

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Fixes [AB#1811257](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1811257) - Fixes #7163 - remove EA parameter from example

Fixes #7163 - remove EA parameter from example

---

reference/docs-conceptual/developer/hosting/adding-and-invoking-commands.md

Fix AddScript code sample

---

reference/5.1/Microsoft.PowerShell.Management/Clear-RecycleBin.md
reference/7.0/Microsoft.PowerShell.Management/Clear-RecycleBin.md
reference/7.1/Microsoft.PowerShell.Management/Clear-RecycleBin.md
reference/7.2/Microsoft.PowerShell.Management/Clear-RecycleBin.md

Fixes [AB#1812388](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1812388) - Fixes #7194 - Force overrides WhatIf

Fixes #7194 - Force overrides WhatIf

---

reference/5.1/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.0/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.1/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.2/Microsoft.PowerShell.Core/Wait-Job.md

Updates for more accurate terminology in the `Wait-Job` docs in all versions
Fixes #7189
Fixes [AB#1811966](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1811966)

Fixes #7189 - Updates Wait-Job

---

reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md

Small fixes for broken examples.

Fix examples: Everything ... about PSCustomObject

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md

Fixes [AB#1813565](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1813565) - Fixes #7203 - fix link to latest release

Fixes #7203 - fix link to latest release

---

reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md
reference/7.0/Microsoft.PowerShell.Utility/Get-Random.md
reference/7.1/Microsoft.PowerShell.Utility/Get-Random.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Random.md

Fixes [AB#1813632](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1813632) - Fixes #7205 - Add warning about using SetSeed

Fixes #7205 - Add warning about using SetSeed

---

reference/5.1/Microsoft.PowerShell.Core/Exit-PSSession.md
reference/7.0/Microsoft.PowerShell.Core/Exit-PSSession.md
reference/7.1/Microsoft.PowerShell.Core/Exit-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Exit-PSSession.md

Updates formatting to current standards for ``Exit-PSSession`` all versions.
Fixes #7218
Fixes [AB#1815734](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1815734)

Fixes #7218 - Updates Exit-PSSession

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Special_Characters.md

Updates about_special_characters to correct information about veritcal tab character.
Fixes #7212
Fixes [AB#1815785](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1815785)

Fixes #7212 - Updates about_Special_Characters

---

reference/docs-conceptual/learn/experimental-features.md

Updates experimental features for new progress bar controls.
Fixes #7195
Fixes [AB#1816287](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1816287)

Fixes #7195 - Updates experimental-features

---

reference/docs-conceptual/developer/cmdlet/parameter-attribute-declaration.md

add missing space

---

reference/docs-conceptual/developer/cmdlet/parameter-attribute-declaration.md

remove duplicated bullet point in in parameter-attribute-declaration.md

remove duplicated bulletpoint

---

reference/7.2/PSReadLine/About/about_PSReadLine.md

Fixes [AB#1816910](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1816910) - Fixes #7233 - add new dynamic help functions

Fixes #7233 - add new dynamic help functions

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fixes [AB#1817231](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1817231) - Copy changes from #7237 to all versions

Copy changes from #7237 to all versions

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Wildcards.md

Fixes [AB#1669514](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669514) - Fixes #7245 - clarify difference from regex

Fixes #7245 - clarify difference from regex

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md

Updates installation instructions for latest stable release.
Fixes #7253
Fixes [AB#1817804](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1817804)

Fixes #7253 - Updates Installing-PowerShell-Core-on-Linux + 2 more

---

reference/index.yml

Update Hub for Community blog

---

reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#1818604](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1818604) - Fixes #7265 - updates for $PSStyle

Fixes #7265 - updates for $PSStyle

---

reference/5.1/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
reference/7.0/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
reference/7.1/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md
reference/7.2/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md

Add information about how we disambiguate between embedded and catalog signature.

Add information about how we disambiguate between embedded and catalog signature.

---

reference/7.2/PSReadLine/About/about_PSReadLine.md

Update the introduction of 'SelectCommandArgument' function.
This is a follow-up PR to #7260

Update the introduction of 'SelectCommandArgument' function

---

reference/5.1/Microsoft.PowerShell.Management/Clear-EventLog.md

Fixes [AB#1818962](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1818962) - Fixes #7251 - note bug in LogName parameter

Fixes #7251 - note bug in LogName parameter

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Corrects example for comparison operators
Fixes #7281
Fixes [AB#1819108](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1819108)

Fixes #7281 - Updates about_Comparison_Operators

---

reference/7.2/PSReadLine/About/about_PSReadLine.md

Update notes for dynamic help

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md

Corrects a typo - restores a whitespace between sentences.

about_Signing: Restores a forgotten whitespace.

---

reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md

Fixes Typo in approved verbs article
Fixes #7302
Fixes [AB#1821736](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1821736)

Fixes #7302 - Updates approved-verbs-for-windows-powershell-commands

---

reference/docs-conceptual/learn/deep-dives/everything-about-switch.md

Removes link to external resource.
The external resource doesn't give relevant information about the switch statement and is talking about the switch type parameter.
Fixes #7299
Fixes [AB#1821750](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1821750)

Fixes #7299 - Updates everything-about-switch

---

reference/docs-conceptual/community/2020-updates.md
reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Update stats for February

---

reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md

Fix platyps schema violation

---

reference/docfx.json

Adds _products_  taxonomy metadata in the docsfx.json file. This update  will allow content from this repo to be available in docs.microsoft.com search filters and other findability features such as content recommendations.
A single file, docfx.json is updated as part of this PR.
The _products_  taxonomy update in docfx.json will automatically apply to all the topics in this repo. …

add customer facing "products" taxonomy metadata

---

reference/docs-conceptual/developer/cmdlet/how-to-support-jobs.md

- Adds missing summary tag in example
- Reflows article
Fixes #7324
Fixes [AB#1824086](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1824086)

Fixes #7324 - Updates how-to-support-jobs

---

reference/5.1/Microsoft.PowerShell.Core/Set-StrictMode.md
reference/7.0/Microsoft.PowerShell.Core/Set-StrictMode.md
reference/7.1/Microsoft.PowerShell.Core/Set-StrictMode.md
reference/7.2/Microsoft.PowerShell.Core/Set-StrictMode.md

Clarifies inputs for **Version** parameter in ``Set-StrictMode``
Fixes #7332
Fixes [AB#1825119](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1825119)

Fixes #7332 - Updates Set-StrictMode

---

reference/docs-conceptual/gallery/concepts/package-manifest-affecting-ui.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
reference/docs-conceptual/toc.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-62.md

Fixes [AB#1825152](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1825152) - Fixes #7333 - Add Arm installation steps

Fixes #7333 - Add Arm installation steps

---

reference/7.0/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/7.1/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/docs-conceptual/developer/module/modifying-the-psmodulepath-installation-path.md

Fixes [AB#1825704](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1825704) - Fixes #7338 - Update PSModulePath info for config.json

Fixes #7338 - Update PSModulePath info for config.json

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md

Fixes [AB#1811301](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1811301) - Fixes #7092 - add more array examples

Fixes #7092 - add more array examples

---

reference/docs-conceptual/learn/ps101/01-getting-started.md

Fix typo in 01-getting-started.md.
N/A

fix typo in 01-getting-started.md

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md

Adds information about installing the latest version of Powershell with older versions.
Fixes #7348
Fixes [AB#1826189](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1826189)

Fixes #7348 - Updates Installing-PowerShell-Core-on-macOS

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fixes [AB#1669514](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669514) - Fixes #7347 - clarify $matches

Fixes #7347 - clarify $matches

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Locations.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Methods.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Locations.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Methods.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Locations.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Methods.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Locations.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Methods.md

Fixes [AB#1826272](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1826272) - Fixes #7319 - using paths in .NET APIs
Fixes [AB#1826271](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1826271) - Fixes #7318 - using paths in .NET APIs

Fixes #7319 - using paths in .NET APIs

---

reference/5.1/Microsoft.PowerShell.Utility/Get-Host.md
reference/7.0/Microsoft.PowerShell.Utility/Get-Host.md
reference/7.1/Microsoft.PowerShell.Utility/Get-Host.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Host.md

Fixes [AB#1828468](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1828468) - Fixes #7367 - characters not pixels

Fixes #7367 - characters not pixels

---

reference/5.1/Microsoft.PowerShell.Core/Receive-Job.md
reference/7.0/Microsoft.PowerShell.Core/Receive-Job.md
reference/7.1/Microsoft.PowerShell.Core/Receive-Job.md
reference/7.2/Microsoft.PowerShell.Core/Receive-Job.md

Updates example 4 in Receive-Job article to work correctly.
Fixes #7303
Fixes [AB#1827045](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1827045)

Fixes #7303 - Updates Receive-Job

---

reference/docs-conceptual/overview.md

Fixes [AB#1826604](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1826604) - Fixes #7340 - Optimize overview page

[WIP] Fixes #7340 - Optimize overview page

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Jobs.md

Fixes broken links
Fixes #7381
Fixes [AB#1829956](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1829956)

Fixes #7381 - Updates about_Jobs

---

reference/5.1/Microsoft.PowerShell.Utility/New-Variable.md
reference/7.0/Microsoft.PowerShell.Utility/New-Variable.md
reference/7.1/Microsoft.PowerShell.Utility/New-Variable.md
reference/7.2/Microsoft.PowerShell.Utility/New-Variable.md

Clarifies information about **Option** parameter usage.
Fixes #7357
Fixes [AB#1830604](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1830604)

Fixes #7357 - Updates New-Variable

---

reference/docs-conceptual/community/2020-updates.md
reference/docs-conceptual/community/2021-updates.md

Make title match H1

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Variables.md

Fixes [AB#1831016](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1831016) - Fixes #7394 - multiple assignment
Fixes [AB#1831017](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1831017) - Fixes #7395 - multiple assignment

Fixes #7394 - multiple assignment

---

reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md

Fixes [AB#1831032](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1831032) - Fixes #7407 - fix cmdlet name

Fixes #7407 - fix cmdlet name

---

reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Fixes [AB#1831731](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1831731) - Update montly stats

Update montly stats

---

reference/5.1/Microsoft.PowerShell.Utility/Trace-Command.md
reference/7.0/Microsoft.PowerShell.Utility/Trace-Command.md
reference/7.1/Microsoft.PowerShell.Utility/Trace-Command.md
reference/7.2/Microsoft.PowerShell.Utility/Trace-Command.md

Updates `Trace-Command` for more accurate information about flag-based enumerated parameters.
Fixes #7420
Fixes [AB#1831373](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1831373)

Fixes #7420 - Updates Trace-Command

---

reference/5.1/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/5.1/Microsoft.PowerShell.Utility/Trace-Command.md
reference/7.0/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/7.0/Microsoft.PowerShell.Utility/Trace-Command.md
reference/7.1/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/7.1/Microsoft.PowerShell.Utility/Trace-Command.md
reference/7.2/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/7.2/Microsoft.PowerShell.Utility/Trace-Command.md

Updates `Set-TraceSource` for flag-based enumeration parameters.
Fixes #7419
Fixes [AB#1831773](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1831773)

Fixes #7419 - Updates Set-TraceSource + 1 more

---

reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.2/Microsoft.PowerShell.Utility/Send-MailMessage.md

Updates `Send-MailMessage` for flag-based enumeration parameters.
Fixes #7417
Fixes [AB#1832030](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832030)

Fixes #7417 - Updates Send-MailMessage

---

reference/5.1/Microsoft.PowerShell.Utility/Add-Type.md
reference/5.1/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
reference/7.0/Microsoft.PowerShell.Utility/Add-Type.md
reference/7.0/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
reference/7.1/Microsoft.PowerShell.Utility/Add-Type.md
reference/7.1/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
reference/7.2/Microsoft.PowerShell.Utility/Add-Type.md
reference/7.2/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
reference/docs-conceptual/install/Installing-PowerShell.md

Fixes [AB#1832032](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832032) - Fixes #7428 - ensure correct usage of ".NET Core"

Fixes #7428 - ensure correct usage of ".NET Core"

---

reference/5.1/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.0/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.1/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Member.md

Updates `Get-Member` for flag-based enumeration parameters.
Fixes #7414
Fixes [AB#1832544](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832544)

Fixes #7414 - Updates Get-Member

---

reference/5.1/Microsoft.PowerShell.Utility/Import-PSSession.md
reference/7.0/Microsoft.PowerShell.Utility/Import-PSSession.md
reference/7.1/Microsoft.PowerShell.Utility/Import-PSSession.md
reference/7.2/Microsoft.PowerShell.Utility/Import-PSSession.md

Updates `Import-PSSession` for flag-based enumeration parameters.
Fixes #7415
Fixes [AB#1832040](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832040)

Fixes #7415 - Updates Import-PSSession

---

reference/5.1/Microsoft.PowerShell.Utility/Export-PSSession.md
reference/7.0/Microsoft.PowerShell.Utility/Export-PSSession.md
reference/7.1/Microsoft.PowerShell.Utility/Export-PSSession.md
reference/7.2/Microsoft.PowerShell.Utility/Export-PSSession.md

Updates `Export-PSSession` for flag-based enumeration parameters.
Fixes #7410
Fixes [AB#1832697](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832697)

Fixes #7410 - Updates Export-PSSession

---

reference/5.1/Microsoft.PowerShell.Utility/Set-Variable.md
reference/7.0/Microsoft.PowerShell.Utility/Set-Variable.md
reference/7.1/Microsoft.PowerShell.Utility/Set-Variable.md
reference/7.2/Microsoft.PowerShell.Utility/Set-Variable.md

Updates `Set-Variable` for flag-based enumeration parameters.
Fixes #7401
Fixes [AB#1832794](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1832794)

Fixes #7401 - Updates Set-Variable

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Fixes example for parameter in `Invoke-WebRequest`
Fixes #7450
Fixes [AB#1833256](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1833256)

Fixes #7450 - Updates Invoke-WebRequest

---

reference/module/index.md

Updated the powershell module browser azps quick filter to 5.8.0

Updated the powershell module browser azps quick filter to 5.8.0

---

reference/7.0/Microsoft.PowerShell.Management/Test-Connection.md
reference/7.1/Microsoft.PowerShell.Management/Test-Connection.md
reference/7.2/Microsoft.PowerShell.Management/Test-Connection.md

Updates note
Fixes #7469
Fixes [AB#1835690](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1835690)

Fixes #7469 - Updates Test-Connection

---

reference/7.0/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
reference/7.1/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md
reference/7.2/Microsoft.PowerShell.Security/ConvertFrom-SecureString.md

Fix typo in ConvertFrom-SecureString
Fixes #7472
Fixes [AB#1835655](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1835655)

Fixes #7472 - Updates ConvertFrom-SecureString

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

Adds note about class availablity in different PowerShell versions for about_Functions_Advanced_Parameters.
Fixes #7470
Fixes [AB#1835641](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1835641)

Fixes #7470 - Updates about_Functions_Advanced_Parameters

---

reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md

Fixes [AB#1835945](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1835945) - Fixes #7475 - Fix yaml block for UseNewRunSpace

Fixes #7475 - Fix yaml block for UseNewRunSpace

---

reference/docs-conceptual/PowerShell-Support-Lifecycle.md

Fixes [AB#1836013](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836013) - Fixes #7478 - Update AppLocker note for 7.2

Fixes #7478 - Update AppLocker note for 7.2

---

reference/docs-conceptual/learn/experimental-features.md

Updates information about experimental feature, PSAnsiProgress
Fixes #7480
Fixes [AB#1836020](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836020)

Fixes #7480 - Updates experimental-features

---

reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#1836044](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836044) - Fixes #7326 - Support for TERM and NO_COLOR

Fixes #7326 - Support for TERM and NO_COLOR

---

reference/5.1/Microsoft.PowerShell.Management/Get-Item.md
reference/7.0/Microsoft.PowerShell.Management/Get-Item.md
reference/7.1/Microsoft.PowerShell.Management/Get-Item.md
reference/7.2/Microsoft.PowerShell.Management/Get-Item.md

Fixes [AB#1836545](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836545) - Fixes #7495 - Fix example 3

Fixes #7495 - Fix example 3

---

reference/docs-conceptual/developer/module/modifying-the-psmodulepath-installation-path.md

Fixes [AB#1836541](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836541) - Fixes #7494 - Make path change persistent

Fixes #7494 - Make path change persistent

---

reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md

Updates example to show files are created
Fixes #7492
Fixes [AB#1836569](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836569)

Fixes #7492 - Updates everything-about-shouldprocess

---

reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Json.md

Fixes [AB#1836582](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836582) - Fixes #7479 - Add valid range for Depth

Fixes #7479 - Add valid range for Depth

---

reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#1836620](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836620) - Fixes #7477 - Add PSNativeCommandArgumentPassing

Fixes #7477 - Add PSNativeCommandArgumentPassing

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md

Fixes [AB#1836843](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1836843) - Fixes #7504 - enumerating results

Fixes #7504 - enumerating results

---

reference/docs-conceptual/powershell-commands.md

Updates What is a PowerShell command article for SEO improvement.
Fixes #7510
Fixes [AB#1837251](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1837251)

Fixes #7510 - Updates powershell-commands

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md

Updates about_parameters to more accurately describe unary operators.
Fixes #7514
Fixes [AB#1837645](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1837645)

Fixes #7514 - Updates about_Operators

---

reference/5.1/PackageManagement/Install-PackageProvider.md
reference/7.0/PackageManagement/Install-PackageProvider.md
reference/7.1/PackageManagement/Install-PackageProvider.md
reference/7.2/PackageManagement/Install-PackageProvider.md

Fixes [AB#1838416](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1838416) - Fixes #7523 - correct install path

Fixes #7523 - correct install path

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md

Fix PowerShell uninstall instruction in MacOS
Fixes #7521
Fixes [AB#1838427](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1838427)

Fixes #7521 - Updates Installing-PowerShell-Core-on-macOS

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md

Fixes [AB#1669514](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669514) - Fixes #7528 - use official product name

Fixes #7528 - use official product name

---

reference/5.1/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
reference/7.0/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
reference/7.1/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
reference/7.2/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md

Fixes [AB#1839252](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1839252) - Fixes #7533 - add more info about TEMP: drive

Fixes #7533 - add more info about TEMP: drive

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.0/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.1/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md

Fixes [AB#1839656](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1839656) - Fixes #7536 - add sleep for Ex1 so progress bar shows

Fixes #7536 - add sleep for Ex1 so progress bar shows

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md

Addresses comments from issue
Adds H3 headers for xml data types
Fixes #7538
Fixes [AB#1839799](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1839799) 1839801

Fixes #7538 - Updates about_Types

---

reference/7.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

The 'you' seems to be missplaced. Not sure if the comma should be removed as well (not a native speaker)

Fix typo in about_Quoting_Rules.md

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

Continuation of #7544 - Sync changes to all versions

Fixes #7544 - Sync changes to all versions

---

reference/docs-conceptual/learn/tutorials/01-discover-powershell.md

Fixes [AB#1840249](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1840249) - Fixes #7541 - Fix grammar

Fixes #7541 - Fix grammar

---

reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Fixes [AB#1840282](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1840282)- Update Stats for April 2021

Update Stats for April 2021

---

reference/docs-conceptual/community/2021-updates.md

Fixes [AB#1840282](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1840282) - Add link to new Learn content

Add link to new Learn content

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Redirection.md

Fixes [AB#1840620](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1840620) - Fixes #7550 - stdout

Fixes #7550 - stdout

---

reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Json.md

Fixes [AB#1840742](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1840742) - Fixes #7552 - Fix max Depth value

Fixes #7552 - Fix max Depth value

---

reference/docs-conceptual/toc.yml

Update TOC for contrib guide

---

reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.0/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.1/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Compare-Object.md

Clarifies performance around **SyncWindow** parameter.
Fixes #7559
Fixes [AB#1841654](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1841654)

Fixes #7559 - Updates Compare-Object

---

reference/5.1/Microsoft.PowerShell.Core/Out-Default.md
reference/7.0/Microsoft.PowerShell.Core/Out-Default.md
reference/7.1/Microsoft.PowerShell.Core/Out-Default.md
reference/7.2/Microsoft.PowerShell.Core/Out-Default.md

Clarifies intent for `Out-Default`.
Fixes #5131
Fixes [AB#1843049](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1843049)

Fixes #5131 - Updates Out-Default

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Clarifies ``$LastExitCode`` for PowerShell 7+
Fixes #7574
Fixes [AB#1843630](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1843630)

Fixes #7574 - Updates about_Automatic_Variables

---

reference/module/index.md

Updated quick filter for Azure PowerShell to version 5.9.0

Updated azps quick filter to v5.9.0

---

reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Json.md

Document changes as per PR: https://github.com/PowerShell/PowerShell/pull/14830

Document changes as per the PR 14830

---

reference/5.1/PackageManagement/Uninstall-Package.md
reference/7.0/PackageManagement/Uninstall-Package.md
reference/7.1/PackageManagement/Uninstall-Package.md
reference/7.2/PackageManagement/Uninstall-Package.md

Fixes [AB#1844737](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1844737) - Fixes #7594 - fix output type

Fixes #7594 - fix output type

---

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md

remove duplicate instructions.
Fixes #7601
Fixes [AB#1845189](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1845189)

Fixes #7601 - Updates SSH-Remoting-in-PowerShell-Core

---

reference/5.1/Microsoft.PowerShell.Management/Test-Path.md
reference/7.0/Microsoft.PowerShell.Management/Test-Path.md
reference/7.1/Microsoft.PowerShell.Management/Test-Path.md
reference/7.2/Microsoft.PowerShell.Management/Test-Path.md

Fixes [AB#1845496](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1845496) - Fixes #7603 - Update example 6

Fixes #7603 - Update example 6

---

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md

Fixes [AB#1845494](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1845494) - Fixes #7608 - Fix link to Ubuntu SSH

Fixes #7608 - Fix link to Ubuntu SSH

---

.github/PULL_REQUEST_TEMPLATE.md
reference/docfx.json
reference/docs-conceptual/lang-spec/chapter-01.md
reference/docs-conceptual/lang-spec/chapter-02.md
reference/docs-conceptual/lang-spec/chapter-03.md
reference/docs-conceptual/lang-spec/chapter-04.md
reference/docs-conceptual/lang-spec/chapter-05.md
reference/docs-conceptual/lang-spec/chapter-06.md
reference/docs-conceptual/lang-spec/chapter-07.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/lang-spec/chapter-09.md
reference/docs-conceptual/lang-spec/chapter-10.md
reference/docs-conceptual/lang-spec/chapter-11.md
reference/docs-conceptual/lang-spec/chapter-12.md
reference/docs-conceptual/lang-spec/chapter-13.md
reference/docs-conceptual/lang-spec/chapter-14.md
reference/docs-conceptual/lang-spec/chapter-15.md
reference/docs-conceptual/lang-spec/chapter-16.md
reference/docs-conceptual/toc.yml

Fixes [AB#1845193](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1845193) - Fixes #5500 - publish language spec

[WIP] Fixes #5500 - publish language spec

---

reference/docs-conceptual/lang-spec/chapter-02.md
reference/docs-conceptual/lang-spec/chapter-03.md
reference/docs-conceptual/lang-spec/chapter-07.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/lang-spec/chapter-10.md
reference/docs-conceptual/lang-spec/chapter-12.md
reference/docs-conceptual/lang-spec/chapter-15.md
reference/docs-conceptual/toc.yml

add note and number TOC

---

reference/docs-conceptual/lang-spec/chapter-01.md
reference/docs-conceptual/lang-spec/chapter-02.md
reference/docs-conceptual/lang-spec/chapter-03.md
reference/docs-conceptual/lang-spec/chapter-04.md
reference/docs-conceptual/lang-spec/chapter-05.md
reference/docs-conceptual/lang-spec/chapter-06.md
reference/docs-conceptual/lang-spec/chapter-07.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/lang-spec/chapter-09.md
reference/docs-conceptual/lang-spec/chapter-10.md
reference/docs-conceptual/lang-spec/chapter-11.md
reference/docs-conceptual/lang-spec/chapter-12.md
reference/docs-conceptual/lang-spec/chapter-13.md
reference/docs-conceptual/lang-spec/chapter-14.md
reference/docs-conceptual/lang-spec/chapter-15.md
reference/docs-conceptual/toc.yml

More formatting fixes for lang-spec

More formatting fixes for lang-spec

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md

Fixes [AB#1846001](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1846001) - Fixes #5837 - fix broken ref link

Fixes #5837 - fix broken ref link

---

reference/docs-conceptual/lang-spec/chapter-16.md
reference/docs-conceptual/toc.yml

Fix TOC for language spec

---

reference/5.1/Microsoft.PowerShell.Security/Get-Credential.md
reference/7.0/Microsoft.PowerShell.Security/Get-Credential.md
reference/7.1/Microsoft.PowerShell.Security/Get-Credential.md
reference/7.2/Microsoft.PowerShell.Security/Get-Credential.md

Fixes [AB#1846011](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1846011) - Fixes #7598 - remove WMI examples

Fixes #7598 - remove WMI examples

---

reference/docs-conceptual/lang-spec/chapter-12.md
reference/docs-conceptual/lang-spec/chapter-13.md

Fix chapter numbers

---

reference/docs-conceptual/lang-spec/chapter-02.md
reference/docs-conceptual/lang-spec/chapter-03.md
reference/docs-conceptual/lang-spec/chapter-04.md
reference/docs-conceptual/lang-spec/chapter-05.md
reference/docs-conceptual/lang-spec/chapter-06.md
reference/docs-conceptual/lang-spec/chapter-07.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/lang-spec/chapter-09.md
reference/docs-conceptual/lang-spec/chapter-10.md
reference/docs-conceptual/lang-spec/chapter-11.md
reference/docs-conceptual/lang-spec/chapter-12.md
reference/docs-conceptual/lang-spec/chapter-13.md
reference/docs-conceptual/lang-spec/chapter-14.md
reference/docs-conceptual/lang-spec/chapter-15.md

Add section numbers

---

reference/docs-conceptual/lang-spec/chapter-01.md
reference/docs-conceptual/lang-spec/chapter-02.md
reference/docs-conceptual/lang-spec/chapter-03.md
reference/docs-conceptual/lang-spec/chapter-04.md
reference/docs-conceptual/lang-spec/chapter-05.md
reference/docs-conceptual/lang-spec/chapter-06.md
reference/docs-conceptual/lang-spec/chapter-07.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/lang-spec/chapter-09.md
reference/docs-conceptual/lang-spec/chapter-10.md
reference/docs-conceptual/lang-spec/chapter-11.md
reference/docs-conceptual/lang-spec/chapter-12.md
reference/docs-conceptual/lang-spec/chapter-13.md
reference/docs-conceptual/lang-spec/chapter-14.md
reference/docs-conceptual/lang-spec/chapter-15.md
reference/docs-conceptual/lang-spec/chapter-16.md

Add links to language spec

---

reference/5.1/Microsoft.PowerShell.Management/New-Item.md
reference/7.0/Microsoft.PowerShell.Management/New-Item.md
reference/7.1/Microsoft.PowerShell.Management/New-Item.md
reference/7.2/Microsoft.PowerShell.Management/New-Item.md

Fixes [AB#1846210](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1846210) - Fixes #7630 - fix example 6

Fixes #7630 - fix example 6

---

reference/module/index.md

Updated PowerShell module browser quick filter for Azure PowerShell to version 6.0.0

Updated quick filter for azps to version 6.0.0

---

reference/5.1/Microsoft.PowerShell.Management/Get-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Management/Get-ItemProperty.md
reference/7.1/Microsoft.PowerShell.Management/Get-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Management/Get-ItemProperty.md

Updates formatting and removes duplicate example
Fixes #7639
Fixes [AB#1846879](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1846879)

Fixes #7639 - Updates Get-ItemProperty

---

reference/5.1/Microsoft.PowerShell.Management/Get-PSProvider.md
reference/7.0/Microsoft.PowerShell.Management/Get-PSProvider.md
reference/7.1/Microsoft.PowerShell.Management/Get-PSProvider.md
reference/7.2/Microsoft.PowerShell.Management/Get-PSProvider.md

Fixes [AB#1847221](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1847221) - Fixes #7646 - fix example 3

Fixes #7646 - fix example 3

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md

Fixes [AB#1847586](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1847586) - Fixes #7584 - add note about PassThru bug

Fixes #7584 - add note about PassThru bug

---

reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
reference/7.0/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
reference/7.2/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md

Updates other versions of Set-Execution Policy to match changes made in #7655

Updates Set-ExecutionPolicy

---

reference/5.1/Microsoft.PowerShell.Utility/Select-Xml.md
reference/7.0/Microsoft.PowerShell.Utility/Select-Xml.md
reference/7.1/Microsoft.PowerShell.Utility/Select-Xml.md
reference/7.2/Microsoft.PowerShell.Utility/Select-Xml.md

Fixes [AB#1848289](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1848289) - Fixes #7654 - fix parameter order and formatting

Fixes #7654 - fix parameter order and formatting

---

reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Update monthly community stats

Update monthly community stats

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Objects.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Objects.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Objects.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Objects.md

Adds information about object discovery
Fixes #6653
Fixes [AB#1844546](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1844546) 1848776

Fixes #6653 - Updates about_Objects

---

reference/docs-conceptual/toc.yml

Fix TOC for schema validation

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/5.1/Microsoft.PowerShell.Utility/Out-File.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.0/Microsoft.PowerShell.Utility/Out-File.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.1/Microsoft.PowerShell.Utility/Out-File.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.2/Microsoft.PowerShell.Utility/Out-File.md

Addresses issue documented in #7651 in this repo and in [15404](https://github.com/PowerShell/PowerShell/issues/15404) in PowerShell repo.
~This is a work-in-progress. DO NOT MERGE YET.  I wanted to get feedback on my "wording" for 7.2 before propagating it to the other versions.~

Update docs with info/examples on setting Out-File width via PSDefaultParameterValues

---

reference/5.1/PackageManagement/Uninstall-Package.md
reference/7.0/PackageManagement/Uninstall-Package.md
reference/7.1/PackageManagement/Uninstall-Package.md
reference/7.2/PackageManagement/Uninstall-Package.md

Fixes typo and minor reformats.
Fixes #7668
Fixes [AB#1849425](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1849425)

Fixes #7668 - Updates Uninstall-Package

---

reference/docs-conceptual/dsc/getting-started/lnxGettingStarted.md

This PR includes updates to the Get started with Desired State Configuration (DSC) for Linux article to update the supported distros and link to the latest DSC agent version per request from engineering/PM team for Automation DSC. 
- [X ] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ X] PR has a meaningful title
- [ X] PR is targeted at the _staging_ branch
- [ X] All relevant versions updated
- [ X] This PR is ready to merge and is not **Work in Progress**
title and remove …

Updated supported distros and link to latest agent

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

Fixes [AB#1849728](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1849728) - Fixes #7673 - Add more terms to no-loc list

Fixes #7673 - Add more terms to no-loc list

---

reference/5.1/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md
reference/7.0/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md
reference/7.1/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md
reference/7.2/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md

Corrects information about **Name** parameter and wildcard compatibility in versions 7+
Fixes #7675
Fixes [AB#1849752](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1849752)

Fixes #7675 - Updates Get-ItemPropertyValue

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Warning.md
reference/7.0/Microsoft.PowerShell.Utility/Write-Warning.md
reference/7.1/Microsoft.PowerShell.Utility/Write-Warning.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Warning.md

Fixes warning output in example and minor formatting
Fixes #7676
Fixes [AB#1849743](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1849743)

Fixes #7676 - Updates Write-Warning

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md
reference/docs-conceptual/dsc/pull-server/secureMOF.md

Fixes [AB#1849734](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1849734) - Fixes #7196 - Example and link for New-SelfSignedCertificate

Fixes #7196 - Example and link for New-SelfSignedCertificate

---

reference/docs-conceptual/developer/cmdlet/alias-attribute-declaration.md
reference/docs-conceptual/developer/cmdlet/cmdlet-aliases.md

Fixes [AB#1850048](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1850048) - Fixes #7293 - alias attribute for cmdlets

Fixes #7293 - alias attribute for cmdlets

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parameters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parameters.md

Fixes [AB#1850094](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1850094) - Fixes #7682 - 0 is non-negative rather than positive

Fixes #7682 - 0 is non-negative rather than positive

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md

Fixes [AB#1850210](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1850210) - Fixes #7684 - clarify array results

Fixes #7684 - clarify array results

---

reference/docs-conceptual/lang-spec/chapter-02.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/lang-spec/chapter-11.md

Add editor's notes

---

reference/docs-conceptual/learn/deep-dives/everything-about-if.md

Corrects information about if statements relastionship to the PowerShell pipeline.
Fixes #7690
Fixes [AB#1850732](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1850732)

Fixes #7690 - Updates everything-about-if

---

reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-applyconfiguration.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-enabledebugconfiguration.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-getconfiguration.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-getconfigurationresultoutput.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-getconfigurationstatus.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-getmetaconfiguration.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-performrequiredconfigurationchecks.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-removeconfiguration.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-resourceget.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-resourceset.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-resourcetest.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-rollback.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-sendconfiguration.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-sendconfigurationapply.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-sendconfigurationapplyasync.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-sendmetaconfigurationapply.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-stopconfiguration.md
reference/docs-conceptual/dsc/reference/mof-classes/msft-dsclocalconfigurationmanager-testconfiguration.md

remove unicode characters

---

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
reference/5.1/Microsoft.PowerShell.Management/Wait-Process.md
reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
reference/7.0/Microsoft.PowerShell.Management/Wait-Process.md
reference/7.1/Microsoft.PowerShell.Management/Start-Process.md
reference/7.1/Microsoft.PowerShell.Management/Wait-Process.md
reference/7.2/Microsoft.PowerShell.Management/Start-Process.md
reference/7.2/Microsoft.PowerShell.Management/Wait-Process.md

Fixes [AB#1851224](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1851224) - Fixes #7700 - Update Start-Process
Fixes [AB#1851228](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1851228) - Fixes #7701

Fixes #7700 - Update Start-Process

---

reference/module/index.md

Updated PowerShell module browser quick filter for Azure PowerShell to version 6.1.0

Updated quick filter to azps 6.1.0

---

reference/docs-conceptual/dsc/getting-started/winGettingStarted.md

Make example xplat and move requirements above script

---

reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Json.md

Fixes #7712 - ConvertTo-Json generates output from null input

Fixes #7712 - ConvertTo-Json generates output from null

---

reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Json.md

Updated based on issue #7712 feedback. Null returns `null`, empty string returns an empty string.

Updated based on issue 7712 feedback

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fixes [AB#1853476](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1853476) - Fixes #7720 - fixes error in prefix description

Fixes #7720 - fixes error in prefix description

---

reference/5.1/Microsoft.PowerShell.Diagnostics/Get-Counter.md
reference/7.0/Microsoft.PowerShell.Diagnostics/Get-Counter.md
reference/7.1/Microsoft.PowerShell.Diagnostics/Get-Counter.md
reference/7.2/Microsoft.PowerShell.Diagnostics/Get-Counter.md

Fixes [AB#1669514](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669514) - Fixes #7721 - localized counter names

Fixes #7721 - localized counter names

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Hash_Tables.md

Fixes [AB#1853884](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1853884) - Fixes #7729 - fix formatting

Fixes #7729 - fix formatting

---

reference/docs-conceptual/dsc/resources/authoringResourceClass.md

cc @nitinbps @gaelcolas @amitsara

newly tested class example

---

reference/docs-conceptual/learn/experimental-features.md

Update info on DSC

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md

- Remove unnecessary `;` 
- Fix missing index in the rank example

[about_Arrays] Fix rank example

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Alias_Provider.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Aliases.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Alias_Provider.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Aliases.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Alias_Provider.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Aliases.md

Windows:
```
PS > Get-Alias -Definition Get-ChildItem
CommandType Name
----------- ----
Alias dir
Alias gci
Alias ls
```
Linux and macOS:
```
PS > Get-Alias -Definition Get-ChildItem
CommandType Name
----------- ----
Alias dir
Alias gci
```
ls - is a native util on *nix system and removed in https://github.com/PowerShell/PowerShell/issues/5870 PR
[key]: …

[about_Alias] add mention about linux and macos

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md

Adds note about installing different versions of PowerShell.
Fixes #7740
Fixes [AB#1854852](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1854852)

Fixes #7740 - Updates Installing-PowerShell-Core-on-Windows

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Keywords.md

Fixes [AB#1855032](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1855032) - Fixes #7744 - list workflow keywords

Fixes #7744 - list workflow keywords

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md

Fixes [AB#1855003](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1855003) - Fixes #3070 - add note about member enumeration

Fixes #3070 - add note about member enumeration

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operator_Precedence.md

Fixes [AB#1669514](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669514) - Fixes #7751 - Fix typo

Fixes #7751 - Fix typo

---

reference/docs-conceptual/samples/Creating-Get-WinEvent-queries-with-FilterHashtable.md

Fixes [AB#1856938](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1856938) - Fixes #7758 - clarify EventProvider sources

Fixes #7758 - clarify EventProvider sources

---

reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Update monthly stats for June

---

reference/5.1/Microsoft.PowerShell.Management/Get-ComputerInfo.md
reference/7.0/Microsoft.PowerShell.Management/Get-ComputerInfo.md
reference/7.1/Microsoft.PowerShell.Management/Get-ComputerInfo.md
reference/7.2/Microsoft.PowerShell.Management/Get-ComputerInfo.md

Update ref to test platyps 0.14.2

---

reference/docs-conceptual/community/2020-updates.md
reference/docs-conceptual/community/contributing/overview.md
reference/docs-conceptual/dev-cross-plat/vscode/using-vscode.md

fix build warnings

---

reference/module/index.md

Updated the PowerShell module browser quick filter for Azure PowerShell to version 6.2.0

Updated azps quick filter to v6.2.0

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

While reading the docs I found a few typos in the `-notin`, `-contains`, and `-notcontains` operators.
I did not open a bug report regarding this, and this is indicated by the missing checkmark in the "PR Checklist" below. The Contributing docs said bug reports and pull requests are both welcome and I did not see any text stating a bug report is a prerequisite to opening a pull request. Please let me know if that is required, as this is my first time contributing to this repo.
Thanks for reviewing this! Please let me know if anything else is required.
- If the PR is work in progress, please add the prefix `WIP:` or …

Fix membership operator typos

---

reference/module/index.md

Updated Az PowerShell quick filter to the latest version (6.2.1).

Updated azps quick filter to version 6.2.1

---

reference/5.1/Microsoft.PowerShell.Utility/Measure-Object.md
reference/7.0/Microsoft.PowerShell.Utility/Measure-Object.md
reference/7.1/Microsoft.PowerShell.Utility/Measure-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Measure-Object.md

Corrects lacking example
Fixes #7806
Fixes [AB#1859235](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1859235)

Fixes #7806 - Updates Measure-Object

---

reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md

Fixes [AB#1859844](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1859844) - Fixes #7817 - add link to format operator

Fixes #7817 - add link to format operator

---

reference/docs-conceptual/lang-spec/chapter-04.md

I fixed some Markdown formatting which was misapplied. 
This is a change to /docs-conceptual

Fix markdown typo

---

reference/docs-conceptual/learn/ps101/08-powershell-remoting.md

Fixes [AB#1859851](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1859851) - Fixes #7810 - fix output in example

Fixes #7810 - fix output in example

---

reference/docs-conceptual/learn/Compatibility-Aliases.md

Updates table for clarity about alises available in PowerShell
Fixes #7788
Fixes [AB#1858352](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1858352)

Fixes #7788 - Updates Compatibility-Aliases

---

reference/docs-conceptual/lang-spec/chapter-04.md

These file attributes are compatible with .NET Framework 4.0. This keeps the documentation in sync with PowerShell 3.0.
Remove duplicate "reparse" table entry. 
Change to /docs-conceptual

Remove duplicate table entry.

---

reference/7.0/Microsoft.PowerShell.Utility/Test-Json.md
reference/7.1/Microsoft.PowerShell.Utility/Test-Json.md
reference/7.2/Microsoft.PowerShell.Utility/Test-Json.md

Fixes [AB#1860468](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1860468) - Fixes #7760 - add notest and links to Newtonsoft

Fixes #7760 - add notest and links to Newtonsoft

---

reference/5.1/Microsoft.PowerShell.Core/About/about_For.md
reference/7.0/Microsoft.PowerShell.Core/About/about_For.md
reference/7.1/Microsoft.PowerShell.Core/About/about_For.md
reference/7.2/Microsoft.PowerShell.Core/About/about_For.md

Updates to fix example in about_For and reflow doc
Fixes #7824
Fixes [AB#1860584](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1860584)

Fixes #7824 - Updates about_For

---

reference/docs-conceptual/community/contributing/powershell-style-guide.md
reference/docs-conceptual/whats-new/differences-from-windows-powershell.md

Fix typos in "preserve-view"

---

reference/docs-conceptual/toc.yml

Update TOC for release notes

---

reference/5.1/Microsoft.PowerShell.Core/Set-StrictMode.md
reference/7.0/Microsoft.PowerShell.Core/Set-StrictMode.md
reference/7.1/Microsoft.PowerShell.Core/Set-StrictMode.md
reference/7.2/Microsoft.PowerShell.Core/Set-StrictMode.md

Fixes [AB#1860935](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1860935) - Fixes #7833 - clarify version parameter

Fixes #7833 - clarify version parameter

---

reference/docs-conceptual/dsc/reference/resources/packagemanagement/PackageManagementDscResource.md

Updates packagemanagement dsc resource for updated parameters when using a nuget provider
Fixes #7837
Fixes [AB#1861112](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1861112)

Fixes #7837 - Updates PackageManagementDscResource

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/docs-conceptual/learn/experimental-features.md

Adds information about experimental feature: ``PSStyle.FileInfo``
Fixes #7017
Fixes [AB#1860853](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1860853)

Fixes #7017 - Updates about_Automatic_Variables + 1 more

---

reference/docs-conceptual/dsc/configurations/import-dscresource.md

Fixes [AB#1861254](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1861254) - Fixes #7841 - fix formatting of parameter info

Fixes #7841 - fix formatting of parameter info

---

reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Argument_Completion.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md

WIP
Created new articles:
- about_Tab_Expansion
- about_Functions_Advanced_Argument_Completion
Updated about_Functions_Advanced_Parameters
- Reordered content
- Moved argument completion details to new article
- linked to new articles

WIP - add tab and completion docs

---

reference/docs-conceptual/learn/remoting/Running-Remote-Commands.md

Fixes [AB#1861732](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1861732) - Fixes #7845 - fix typo

Fixes #7845 - fix typo

---

reference/5.1/Microsoft.PowerShell.Core/New-PSSession.md
reference/7.0/Microsoft.PowerShell.Core/New-PSSession.md
reference/7.1/Microsoft.PowerShell.Core/New-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/New-PSSession.md

Fixes [AB#1861739](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1861739) - Fixes #7843 - Add parameter description

Fixes #7843 - Add parameter description

---

reference/5.1/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.1/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md

Fixes [AB#1861736](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1861736) - Fixes #7846 - fix Example 7

Fixes #7846 - fix Example 7

---

reference/docs-conceptual/samples/Manipulating-Items-Directly.md

fixes Example and reflows article
Fixes #7852
Fixes [AB#1861769](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1861769)

Fixes #7852 - Updates Manipulating-Items-Directly

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md

Adds information about registry key differences in different versions of Windows. major reformatting in about_Remote_Requirements.
Fixes #7849
Fixes [AB#1861840](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1861840)

Fixes #7849 - Updates about_Remote_Requirements + 1 more

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

Fixes [AB#1862192](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862192) - Fixes #7867 - fix typo

Fixes #7867 - fix typo

---

reference/docs-conceptual/samples/Managing-Services.md

fixes Typo
Fixes #7859
Fixes [AB#1862202](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862202)

Fixes #7859 - Updates Managing-Services

---

reference/docs-conceptual/samples/Redirecting-Data-with-Out---Cmdlets.md

Updates samples doc: Redirecting output
Fixes #7871
Fixes [AB#1862250](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862250)

Fixes #7871 - Updates Redirecting-Data-with-Out---Cmdlets

---

reference/docs-conceptual/samples/Manipulating-Items-Directly.md

Fixes Typo
Fixes #7860
Fixes [AB#1862260](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862260)

Fixes #7860 - Updates Manipulating-Items-Directly

---

reference/docs-conceptual/samples/Performing-Networking-Tasks.md

- Fixes [AB#1862207](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862207) - Fixes #7865 - Fix WMI examples in Network samples article
- Fixes [AB#1862292](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862292) - Fixes #7866
- Fixes [AB#1862293](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862293) - Fixes #7864
- Fixes [AB#1862294](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862294) - Fixes #7863
- Fixes [AB#1862295](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862295) - Fixes #7862
- Fixes [AB#1862296](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862296) - Fixes #7861 …

Fixes #7865 - Fix WMI examples in Network samples article

---

reference/docs-conceptual/samples/Working-with-Software-Installations.md

Remove example since it's out of date and really doesn't bring value to the doc. Replaced with a note to inform reader of behavior.
Fixes #7870
Fixes [AB#1862278](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862278)

Fixes #7870 - Updates Working-with-Software-Installations

---

reference/docs-conceptual/developer/module/installing-a-powershell-module.md

Fixes [AB#1862660](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862660) - Fixes #5864 - Add cross-platform info about paths

Fixes #5864 - Add cross-platform info about paths

---

reference/5.1/Microsoft.PowerShell.Core/New-PSSessionOption.md
reference/7.0/Microsoft.PowerShell.Core/New-PSSessionOption.md
reference/7.1/Microsoft.PowerShell.Core/New-PSSessionOption.md
reference/7.2/Microsoft.PowerShell.Core/New-PSSessionOption.md

Updates **OperationTimeOut** parameter for clarity.
Fixes #7794
Fixes [AB#1862663](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1862663)

Fixes #7794 - Updates New-PSSessionOption

---

reference/docs-conceptual/learn/ps101/05-formatting-aliases-providers-comparison.md

Fixed typo in SSMS short form and link

Fix typo in SSMS short form

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md

Updates for syntax correction
Fixes #7885
Fixes [AB#1863061](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1863061)

Fixes #7885 - Updates about_Functions

---

reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Fixes [AB#1669513](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669513) - Update montly stats for July

Update montly stats for July

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md

Updates install for windows docs
- Removes references to MSIX pacakges
- Updates `winget` section to account for public release
- Updates Windows Store section to keep terminology to Windows Store packages
Fixes #7894
Fixes [AB#1863443](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1863443)
[key]: …

Fixes #7894 - Updates Installing-PowerShell-Core-on-Windows

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Fixes [AB#1863510](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1863510) - Fixes #7899 - add contoso disclaimer

Fixes #7899 - add contoso disclaimer

---

reference/7.1/Microsoft.PowerShell.Management/Add-Content.md
reference/7.1/Microsoft.PowerShell.Management/Get-Content.md
reference/7.1/Microsoft.PowerShell.Management/Set-Content.md
reference/7.1/Microsoft.PowerShell.Utility/Export-Clixml.md
reference/7.1/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.1/Microsoft.PowerShell.Utility/Format-Hex.md
reference/7.1/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.1/Microsoft.PowerShell.Utility/Out-File.md
reference/7.1/Microsoft.PowerShell.Utility/Select-String.md
reference/7.2/Microsoft.PowerShell.Management/Add-Content.md
reference/7.2/Microsoft.PowerShell.Management/Get-Content.md
reference/7.2/Microsoft.PowerShell.Management/Set-Content.md
reference/7.2/Microsoft.PowerShell.Utility/Export-Clixml.md
reference/7.2/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Format-Hex.md
reference/7.2/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Out-File.md
reference/7.2/Microsoft.PowerShell.Utility/Select-String.md
reference/7.2/Microsoft.PowerShell.Utility/Tee-Object.md

- Adds **Encoding** parameter to `Tee-Object`.
- Updates language for **Encoding** parameter note across multiple files.
Fixes #5612
Fixes [AB#1863544](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1863544)

Fixes #5612 - Updates Add-Content + 9 more

---

reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

As per [this SO answer](https://stackoverflow.com/a/17461595/725626), the current docs description is confusing.
Unless I'm missing something, as there could be cases where I'm wrong. But just throwing this suggestion out there.
Will update other versions' docs if/when the wording here is agreed upon.
Tweaks wording to be clear that the value IS NOT the cwd, but the executing script's directory.
Uhh.... looks like "Reference" isn't an option.
[contrib]: …

[WIP] Make $PSScriptRoot description clearer

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

coppies changes from $psscriptRoot clarification

Fixes # - Updates about_Automatic_Variables

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Modes.md

Fixes [AB#1864026](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1864026) - Fixes #7169 - New-Object in system lockdown config

Fixes #7169 - New-Object in system lockdown config

---

reference/module/index.md

Updated PowerShell module browser quick filter to Az PowerShell version 6.3.0.

Updated quickfilter to latest azps version

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Fixes typo in about_Automatic_Variables
Fixes #7916
Fixes [AB#1864421](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1864421)

Fixes #7916 - Updates about_Automatic_Variables

---

reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.1/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Export-Csv.md

Updates PowerShell 7.2 docs for ``ConvertTo-Csv`` and ``Export-Csv`` to demonstrate new bahavior when working with hashtables. Formats headers for all doc versions
Fixes #5104
Fixes [AB#1864423](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1864423)

Fixes #5104 - Updates ConvertTo-Csv + 1 more

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.1/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/toc.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-72.md

- Fixes [AB#1864499](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1864499) - Fixes #7917
- Fixes [AB#1864500](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1864500) - Fixes #7908
- Fixes [AB#1864501](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1864501) - Fixes #7907
- Fixes [AB#1864502](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1864502) - Fixes #4990
Update release notes for 7.2 in release branch.
Added about_ANSI_Terminals article
Updated experimental features article

Update release notes for 7.2

---

reference/docs-conceptual/lang-spec/chapter-05.md

I added some missing links between chapters. 
/docs-conceptual 

Fix missing links.

---

reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.1/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Json.md

Updates 7.2 version ``ConvertTo-Json`` docs for new serialization behavior when working with **DateTime** and **String** objects.
Fixes #7909
Fixes [AB#1865809](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1865809)

Fixes #7909 - Updates ConvertTo-Json

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fixes incorrect link
Fixes #7934
Fixes [AB#1866440](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1866440)

Fixes #7934 - Updates about_Comparison_Operators

---

reference/docs-conceptual/dsc/troubleshooting/troubleshooting.md

Add PowerShell optioin to enable log and update link for latest version.
Fixes #7932
Fixes [AB#1866479](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1866479)

Fixes #7932 - Updates troubleshooting

---

reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md

Lessen the ambiguity of the description of the command
Lessen the ambiguity of the description of the `$ServerB = Get-ADComputer -Identity ServerB -Server dc1.alpineskihouse.com` command

Lessen the ambiguity of the description of the command

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

fixes typo
Fixes #7941
Fixes [AB#1866894](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1866894)

Fixes #7941 - Updates Invoke-WebRequest

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md
reference/docs-conceptual/learn/experimental-features.md

Pull in updates from release-72 branch

Pull in updates from release-72 branch

---

reference/5.1/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.1/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Import-Csv.md

Updates **Delimiter** param in ``ConvertTo-Csv``
Fixes #7955
Fixes [AB#1867277](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1867277)

Fixes #7955 - Updates Import-Csv

---

reference/5.1/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.1/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md
reference/docs-conceptual/learn/experimental-features.md

8/11 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.0/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PSCustomObject.md

Fixes [AB#1866944](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1866944) - Fixes #3092 - add About_PSCustomObject

Fixes #3092 - add About_PSCustomObject

---

reference/docs-conceptual/learn/Compatibility-Aliases.md

Adds note about alias availability on non-Windows platforms
Fixes #7960
Fixes [AB#1867785](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1867785)

Fixes #7960 - Updates Compatibility-Aliases

---

reference/docs-conceptual/learn/Compatibility-Aliases.md

8/13 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

fix md style

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Fixes [AB#1868648](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1868648) - Fixes #7926 - Make OutputRendering default = Host

Fixes #7926 - Make OutputRendering default = Host

---

reference/5.1/Microsoft.PowerShell.Core/Export-ModuleMember.md
reference/7.0/Microsoft.PowerShell.Core/Export-ModuleMember.md
reference/7.1/Microsoft.PowerShell.Core/Export-ModuleMember.md
reference/7.2/Microsoft.PowerShell.Core/Export-ModuleMember.md

Removes example 7 and updates formatting
Fixes #7967
Fixes [AB#1868736](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1868736)

Fixes #7967 - Updates Export-ModuleMember

---

reference/docs-conceptual/developer/format/propertycountfortable-element-format.md

Adds properties and description for `PropertyCountForTable` element.
Fixes #7210
Fixes [AB#1868829](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1868829)

Fixes #7210 - Updates propertycountfortable-element-format

---

reference/docs-conceptual/dsc/resources/authoringResourceClass.md

this will align the guest config and dsc doc examples, so no one has to deduce the change on their own

minor change to config name

---

reference/docs-conceptual/learn/ps101/10-script-modules.md

Fixes #7978 - Corrected typo

---

reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md

Add information on installing PowerShell 7 via the Windows Store (with ~~aka.ms~~ store link) and via `winget.exe`. I feel it is important to include the instructions on this page because it is the target of the link in the message when you launch Windows PowerShell:
```plain
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
```
☝🏻 unsure about this. I have only updated one document, so there might be others that I've missed.
- If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the …

Add Windows Store and winget installation details to "Migrating from Windows PowerShell to PowerShell 7"

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/5.1/PSReadLine/Set-PSReadLineOption.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.0/PSReadLine/Set-PSReadLineOption.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.1/PSReadLine/Set-PSReadLineOption.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/PSReadLine/Set-PSReadLineOption.md

Fixes [AB#1869103](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1869103) - Update environment variables

Update environment variables

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md

Fixes Typo
Fixes #7982
Fixes [AB#1869442](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1869442)

Fixes #7982 - Updates about_Environment_Variables

---

reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-Core-on-macOS.md

Fixes [AB#1869522](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1869522) - Update version numbers for new releases

Update version numbers for new releases

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Profiles.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Profiles.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md

Adds note warning about onenote redirection and upfates tables for v 7.x ``$profile`` paths
Fixes #7984
Fixes [AB#1869586](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1869586)

Fixes #7984 - Updates about_Profiles

---

reference/docs-conceptual/developer/module/importing-a-powershell-module.md

Fixes [AB#1869826](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1869826) - Fixes #7993 - fix typo

Fixes #7993 - fix typo

---

reference/docs-conceptual/developer/format/firstlinehanging-element-for-frame-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/firstlinehanging-element-for-frame-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/firstlinehanging-element-for-frame-for-customcontrol-for-view-format.md
reference/docs-conceptual/developer/format/firstlinehanging-element-for-frame-for-groupby-format.md
reference/docs-conceptual/developer/format/firstlineindent-element-for-frame-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/firstlineindent-element-for-frame-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/firstlineindent-element-for-frame-for-customcontrol-for-view-format.md
reference/docs-conceptual/developer/format/firstlineindent-element-for-frame-for-groupby-format.md
reference/docs-conceptual/developer/format/format-schema-xml-reference.md
reference/docs-conceptual/developer/format/formatstring-element-for-listitem-for-listcontrol-format.md
reference/docs-conceptual/developer/format/formatstring-element-for-tablecolumnitem-for-tablecontrol-format.md
reference/docs-conceptual/developer/format/formatstring-element-for-wideitem-for-widecontrol-format.md
reference/docs-conceptual/developer/format/formatting-displayed-data.md
reference/docs-conceptual/developer/format/formatting-file-concepts.md
reference/docs-conceptual/developer/format/formatting-file-overview.md
reference/docs-conceptual/developer/format/frame-element-for-customitem-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/frame-element-for-customitem-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/frame-element-for-customitem-for-customcontrol-for-view-format.md
reference/docs-conceptual/developer/format/frame-element-for-customitem-for-groupby-format.md
reference/docs-conceptual/developer/format/groupby-element-for-view-format.md
reference/docs-conceptual/developer/format/hidetableheaders-element-format.md
reference/docs-conceptual/developer/format/how-to-create-a-formatting-file-format-ps1xml.md

No Linked Issue - Updates defaultsettings-element-format + 44 more

---

reference/docs-conceptual/learn/remoting/WSMan-Remoting-in-PowerShell-Core.md

terminate->terminated at line 57

Single typo

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

typo: The Boolean value returned my MoveNext

---

reference/docs-conceptual/developer/format/rightindent-element-for-frame-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/rightindent-element-for-frame-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/rightindent-element-for-frame-for-customcontrol-for-view-format.md
reference/docs-conceptual/developer/format/rightindent-element-for-frame-for-groupby-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-expressionbinding-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-expressionbinding-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-expressionbinding-for-customcontrol-for-view-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-expressionbinding-for-groupby-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-groupby-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-itemseclectioncondition-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-itemselectioncondition-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-itemselectioncondition-for-customcontrol-for-view-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-itemselectioncondition-for-groupby-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-itemselectioncondition-for-listcontrol-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-listitem-for-listcontrol-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-selectioncondition-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-selectioncondition-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-selectioncondition-for-customcontrol-for-view-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-selectioncondition-for-entryselectedby-for-enumerableexpansion-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-selectioncondition-for-entryselectedby-for-groupby-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-selectioncondition-for-entryselectedby-for-listcontrol-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-selectioncondition-for-entryselectedby-for-tablecontrol-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-selectioncondition-for-entryselectedby-for-widecontrol-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-tablecolumnitem-for-tablecontrol-format.md
reference/docs-conceptual/developer/format/scriptblock-element-for-wideitem-for-widecontrol-format.md

Updates SDK formatting docs formatting Pt 5

No Linked Issue - Updates rightindent-element-for-frame-for-controls-for-configuration-format + 24 more

---

reference/docs-conceptual/developer/format/selectioncondition-element-for-entryselectedby-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/selectioncondition-element-for-entryselectedby-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/selectioncondition-element-for-entryselectedby-for-customcontrol-format.md
reference/docs-conceptual/developer/format/selectioncondition-element-for-entryselectedby-for-enumerableexpansion-format.md
reference/docs-conceptual/developer/format/selectioncondition-element-for-entryselectedby-for-groupby-format.md
reference/docs-conceptual/developer/format/selectioncondition-element-for-entryselectedby-for-listcontrol-format.md
reference/docs-conceptual/developer/format/selectioncondition-element-for-entryselectedby-for-tablecontrol-format.md
reference/docs-conceptual/developer/format/selectioncondition-element-for-entryselectedby-for-widecontrol-format.md
reference/docs-conceptual/developer/format/selectionset-element-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-entryselectedby-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-entryselectedby-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-entryselectedby-for-customcontrol-for-view-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-entryselectedby-for-enumerableexpansion-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-entryselectedby-for-groupby-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-entryselectedby-for-listcontrol-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-entryselectedby-for-tablecontrol-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-entryselectedby-for-widecontrol-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-selectioncondition-for-controls-for-configuration-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-selectioncondition-for-controls-for-view-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-selectioncondition-for-customcontrol-for-view-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-selectioncondition-for-entryselectedby-for-enumerableexpansion-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-selectioncondition-for-entryselectedby-for-listentry-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-selectioncondition-for-entryselectedby-for-tablecontrol-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-selectioncondition-for-entryselectedby-for-wideentry-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-selectioncondition-for-groupby-format.md
reference/docs-conceptual/developer/format/selectionsetname-element-for-viewselectedby-format.md
reference/docs-conceptual/developer/format/selectionsets-element-format.md

Updates SDK formatting docs for formatting

No Linked Issue - Updates selectioncondition-element-for-entryselectedby-for-controls-for-configuration-format + 26 more

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Variables.md

Fixes [AB#1871494](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1871494) - Fixes #8028 - add missing word

Fixes #8028 - add missing word

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Remote.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Windows_Powershell_5.1.md
reference/5.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Remote.md
reference/7.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Remote.md
reference/7.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Remote.md
reference/7.2/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md
reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/contributing/managing-issues.md
reference/docs-conceptual/developer/cmdlet/cmdlet-samples.md
reference/docs-conceptual/developer/hosting/host-application-samples.md
reference/docs-conceptual/developer/installing-the-windows-powershell-sdk.md
reference/docs-conceptual/developer/prog-guide/runspace09-code-sample.md
reference/docs-conceptual/dsc/pull-server/pullServer.md
reference/docs-conceptual/learn/remoting/powershell-remoting-faq.yml
reference/docs-conceptual/whats-new/differences-from-windows-powershell.md
reference/docs-conceptual/windows-powershell/wmf/whats-new/release-notes.md
reference/index.yml

Fixes [AB#1872537](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1872537) - Fixes #8032 - Fixes #8032 - fix or remove broken links

Fixes #8032 - fix or remove broken links

---

reference/docfx.json

Fixes [AB#1669513](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1669513) - Remove UserVoice from feedback options

Remove UserVoice from feedback options

---

reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#1872816](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1872816) - Fixes #8039 - update file extension list

Fixes #8039 - update file extension list

---

reference/docs-conceptual/PowerShell-Support-Lifecycle.md

Match update from .NET 5 @ https://github.com/dotnet/core/blob/main/releases.md

Update end-of-life for PS7.1 to match .NET 5

---

reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Update monthly stats

---

reference/module/index.md

Updated PowerShell module browser quick filter to AzPS version 6.4.0

Updated quick filter for azps to version 6.4.0

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Remote.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Remote.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Remote.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Remote.md

Fixes [AB#1873970](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1873970) - Fix broken links

Fix broken links

---

reference/5.1/PSWorkflow/About/about_Foreach-Parallel.md

Fixes [AB#1874680](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1874680) - Fixes #8068 - Split example for clarity

Fixes #8068 - Split example for clarity

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

Updates versions based on PR #8027

No Linked Issue - Updates 

---

reference/7.0/ThreadJob/Start-ThreadJob.md
reference/7.1/ThreadJob/Start-ThreadJob.md
reference/7.2/ThreadJob/Start-ThreadJob.md

Fixes [AB#1874834](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1874834) - fix utf8 character error

fix utf8 character error

---

reference/5.1/Microsoft.PowerShell.Core/Get-Verb.md

Adds Common params and reformats for standards

No Linked Issue - Updates Get-Verb

---

reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.0/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.1/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.2/Microsoft.PowerShell.Core/Invoke-Command.md

Adds note about switch parameter behavior in ``Invoke-Command``.

No Linked Issue - Updates Invoke-Command

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Trap.md

Updates to show trap behavior in subodinate script blocks
Fixes #8091
Fixes [AB#1876109](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1876109)

Fixes #8091 - Updates about_Trap

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/5.1/Microsoft.PowerShell.Management/Remove-Item.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.2/Microsoft.PowerShell.Management/Remove-Item.md

Fix improperly formatted error messages

Fix improperly formatted error messages

---

README.md
reference/README.md
reference/docfx.json

Update docfx and readme files

---

reference/docs-conceptual/developer/cmdlet/how-to-request-confirmations.md

Fixes [AB#1876825](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1876825) - Fixes #5248 - Add information about ConfirmImpact

Fixes #5248 - Add information about ConfirmImpact

---

reference/docs-conceptual/learn/deep-dives/add-credentials-to-powershell-functions.md

Fixes [AB#1877167](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1877167) - Fixes #8101 - Fix typo in example

Fixes #8101 - Fix typo in example

---

reference/docs-conceptual/whats-new/differences-from-windows-powershell.md

Fix damaged file

---

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
reference/7.1/Microsoft.PowerShell.Management/Start-Process.md
reference/7.2/Microsoft.PowerShell.Management/Start-Process.md

Fixes [AB#1878428](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1878428) - Fixes #8112 - Fix Example 3

Fixes #8112 - Fix Example 3

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md

Updates to clarify parameter set behavior

No Linked Issue - Updates about_Parameter_Sets

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parameters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parameters.md

Fixes [AB#1878611](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1878611) - Fixes #8116 - Replace parameter alias with actual name

Fixes #8116 - Replace parameter alias with actual name

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Update file list for experimental feature

Update file list for experimental feature

---

.openpublishing.redirection.json

Update redirects for get-verb

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

Fixes [AB#1879363](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1879363) - Fixes #8122 - Add note about external commands

Fixes #8122 - Add note about external commands

---

reference/7.1/PSReadLine/About/about_PSReadLine.md
reference/7.2/PSReadLine/About/about_PSReadLine.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
reference/docs-conceptual/learn/security-features.md
reference/docs-conceptual/toc.yml

Update PSReadLine and create Security Features doc

Update PSReadLine and create Security Features doc

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_CmdletBindingAttribute.md

Fixes #8131 
Fixes [AB#1880290](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1880290)

Fixes #8131 - use short form of boolean attributes

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Thread_Jobs.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Thread_Jobs.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Thread_Jobs.md

Fixes [AB#1880792](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1880792) - Fixes #2939 - Add online URL to all about topics

Fixes #2939 - Add online URL to all about topics

---

reference/5.1/Microsoft.PowerShell.Management/Remove-Item.md
reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md
reference/7.1/Microsoft.PowerShell.Management/Remove-Item.md
reference/7.2/Microsoft.PowerShell.Management/Remove-Item.md

Updates ``Remove-Item -Recurse`` behavior.
Fixes #8134
Fixes [AB#1880817](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1880817)

Fixes #8134 - Updates Remove-Item

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.0/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.1/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Information.md

Adds note about running example on Windows 10
Fixes #8141
Fixes [AB#1881067](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1881067)

Fixes #8141 - Updates Write-Information

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.0/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.1/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Information.md

Fixes #8141 - Change example to Get-Process

Fixes #8141 - Change example to Get-Process

---

reference/docs-conceptual/dev-cross-plat/vscode/understanding-file-encoding.md

Fixes [AB#1881831](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1881831) - Fixes #8150 - Fix HTML encoded characters

Fixes #8150 - Fix HTML encoded characters

---

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md

Fix broken link for Raspbian

---

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md

Fixes [AB#1882103](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1882103) - Fixes #8157 - Update restart command

Fixes #8157 - Update restart command

---

reference/docs-conceptual/developer/cmdlet/users-requesting-confirmation.md

Fixes [AB#1882107](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1882107) - Fixes #8156 - Clarify how confirmation works

Fixes #8156 - Clarify how confirmation works

---

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md

Fixes [AB#1882203](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1882203) - Fixes #8100 - Add information about JIT-compilation

Fixes #8100 - Add information about JIT-compilation

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Telemetry.md

Fixes [AB#1882314](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1882314) - Update telemetry info

Update telemetry info

---

reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Fixes [AB#1882485](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1882485) - Update stats for Sept 2021

Update stats for Sept 2021

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Fixes [AB#1882450](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1882450) - Fixes #8165 - Clarify version information

Fixes #8165 - Clarify version information

---

reference/index.yml

Update links to setup articles

Update links to setup articles

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Fixes [AB#1882862](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1882862) - Fixes #8174 - Add source parameter to winget

Fixes #8174 - Add source parameter to winget

---

reference/docs-conceptual/how-to-use-docs.md
reference/docs-conceptual/overview.md
reference/docs-conceptual/powershell-commands.md
reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-71.md
reference/docs-conceptual/whats-new/module-compatibility.md
reference/docs-conceptual/whats-new/unix-support.md
reference/module/index.md

Fixes [AB#1883029](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1883029) - Freshness update for aging articles

Freshness update for aging articles

---

reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md

Fixes [AB#1883247](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1883247) - Fixes #8187 - Add another range example

Fixes #8187 - Add another range example

---

reference/5.1/PSScheduledJob/Add-JobTrigger.md
reference/5.1/PSScheduledJob/Disable-JobTrigger.md
reference/5.1/PSScheduledJob/Disable-ScheduledJob.md
reference/5.1/PSScheduledJob/Enable-JobTrigger.md
reference/5.1/PSScheduledJob/Enable-ScheduledJob.md
reference/5.1/PSScheduledJob/Get-JobTrigger.md
reference/5.1/PSScheduledJob/Get-ScheduledJob.md
reference/5.1/PSScheduledJob/Get-ScheduledJobOption.md
reference/5.1/PSScheduledJob/New-JobTrigger.md
reference/5.1/PSScheduledJob/New-ScheduledJobOption.md

More careful updates to formatting.

No Linked Issue - Updates Add-JobTrigger + 9 more

---

reference/docs-conceptual/install/install-raspbian.md

Fixes [AB#1883278](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1883278) - Fixes #8190 - Fix typo

Fixes #8190 - Fix typo

---

reference/docs-conceptual/learn/deep-dives/add-credentials-to-powershell-functions.md
reference/docs-conceptual/learn/deep-dives/everything-about-exceptions.md
reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md
reference/docs-conceptual/learn/deep-dives/everything-about-if.md
reference/docs-conceptual/learn/deep-dives/everything-about-null.md
reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md
reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md
reference/docs-conceptual/learn/deep-dives/everything-about-string-substitutions.md
reference/docs-conceptual/learn/deep-dives/everything-about-switch.md
reference/docs-conceptual/learn/deep-dives/overview.md
reference/docs-conceptual/learn/deep-dives/write-progress-across-multiple-threads.md
reference/docs-conceptual/learn/more-powershell-learning.md
reference/docs-conceptual/learn/ps101/00-introduction.md
reference/docs-conceptual/learn/ps101/01-getting-started.md
reference/docs-conceptual/learn/ps101/02-help-system.md
reference/docs-conceptual/learn/ps101/03-discovering-objects.md
reference/docs-conceptual/learn/ps101/04-pipelines.md
reference/docs-conceptual/learn/ps101/05-formatting-aliases-providers-comparison.md
reference/docs-conceptual/learn/ps101/06-flow-control.md
reference/docs-conceptual/learn/ps101/07-working-with-wmi.md
reference/docs-conceptual/learn/ps101/08-powershell-remoting.md
reference/docs-conceptual/learn/ps101/09-functions.md
reference/docs-conceptual/learn/ps101/10-script-modules.md
reference/docs-conceptual/learn/ps101/appendix-a.md

Fixes [AB#1883305](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1883305) - Review for freshness

Review for freshness

---

reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/contributing/editorial-checklist.md
reference/docs-conceptual/community/contributing/powershell-style-guide.md
reference/docs-conceptual/community/hall-of-fame.md

Fixes [AB#1889985](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1889985) - Publish monthly stats

Publish monthly stats

---

reference/docs-conceptual/windows-powershell/wmf/whats-new/script-logging.md

Fixes [AB#1890287](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1890287) - Fixes #8289 - Fix broken link

Fixes #8289 - Fix broken link

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md

Fixes [AB#1890349](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1890349) - Fixes #8284 - $Matches only contains first occurrence

Fixes #8284 - $Matches only contains first occurrence

---

reference/module/index.md

Updated PowerShell module browser quick filter for Az PowerShell to version 6.6.0.

Updated quick filter to az powershell 6.6.0

---

reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md

everything-about-pscustomobject.md - fixed typo: about_Inrinsic_Members => about_Intrinsic_Members
Fixed typo: about_Inrinsic_Members => about_Intrinsic_Members

everything-about-pscustomobject.md - fixed typo

---

reference/5.1/Microsoft.PowerShell.Management/Add-Content.md
reference/5.1/Microsoft.PowerShell.Management/Set-Content.md
reference/7.0/Microsoft.PowerShell.Management/Add-Content.md
reference/7.0/Microsoft.PowerShell.Management/Set-Content.md
reference/7.1/Microsoft.PowerShell.Management/Add-Content.md
reference/7.1/Microsoft.PowerShell.Management/Set-Content.md
reference/7.2/Microsoft.PowerShell.Management/Add-Content.md
reference/7.2/Microsoft.PowerShell.Management/Set-Content.md

Fixes [AB#1890711](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1890711) - Fixes #8299 - Correct information about path creation

Fixes #8299 - Correct information about path creation

---

reference/docs-conceptual/dsc/configurations/add-parameters-to-a-configuration.md

Fixes [AB#1891406](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1891406) - Fixes #8304 - Fix description of final example

Fixes #8304 - Fix description of final example

---

reference/5.1/Microsoft.PowerShell.Utility/Select-String.md
reference/7.0/Microsoft.PowerShell.Utility/Select-String.md
reference/7.1/Microsoft.PowerShell.Utility/Select-String.md
reference/7.2/Microsoft.PowerShell.Utility/Select-String.md

Fixes [AB#1891421](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1891421) - Fixes #8278 - Clarify input behaviors for Select-String

Fixes #8278 - Clarify input behaviors for Select-String

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md

Fixes [AB#1892811](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1892811) - Fixes #8319 - MaxWidth minimum is 18

Fixes #8319 - MaxWidth minimum is 18

---

reference/docs-conceptual/learn/deep-dives/everything-about-string-substitutions.md

Fixes [AB#1893169](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1893169) - Fixes #8271 - Add output for example

Fixes #8271 - Add output for example

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Update version number from 7.1 to 7.2

---

reference/docs-conceptual/dsc/reference/resources/windows/scriptResource.md

Fixes [AB#1893508](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1893508) - Fixes #8314 - Fix example 3

Fixes #8314 - Fix example 3

---

reference/docs-conceptual/learn/deep-dives/everything-about-exceptions.md

Fixes [AB#1893527](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1893527) - Fixes #8332 - how to access exception information in the catch

Fixes #8332 - how to access exception information in the catch

---

reference/docs-conceptual/how-to-use-docs.md

Fixes [AB#1893595](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1893595) - Update version picker information

Update version picker information

---

reference/docs-conceptual/install/PowerShell-on-ARM.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md

Fixes [AB#1893765](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1893765) - Fixes #8341 - Add pointer to install for Arm processors

Fixes #8341 - Add pointer to install for Arm processors

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md

Add information about hexadecimal string formats that can be converted to numbers 
Add information about hexadecimal string formats that can be converted to numbers 

Additional hexadecimal indicators in strings

---

reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.0/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.1/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.2/Microsoft.PowerShell.Core/Invoke-Command.md

Fixes [AB#1894743](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1894743) - Fixes #8359 - Fix example 17

Fixes #8359 - Fix example 17

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md

Fixes [AB#1894745](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1894745) - Fixes #8277 - Add more instrinsic members

Fixes #8277 - Add more instrinsic members

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md

Fixes [AB#1895902](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1895902) - Fixes #8365 - Add about topic for built-in functions

Fixes #8365 - Add about topic for built-in functions

---

reference/docs-conceptual/learn/more-powershell-learning.md
reference/docs-conceptual/learn/security-features.md
reference/includes/centos-support.md
reference/includes/fedora-support.md

Minor cleanup edits

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/includes/macos-support.md

Fixes [AB#1896124](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1896124) - Fixes #8369 - Update macOS install & fix formatting in about_

Fixes #8369 - Update macOS install & fix formatting in about_

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md

Fixes [AB#1896246](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1896246) - Fixes #8370 - Functions must be defined before being called

Fixes #8370 - Functions must be defined before being called

---

reference/5.1/Microsoft.PowerShell.Management/Rename-Item.md
reference/7.0/Microsoft.PowerShell.Management/Rename-Item.md
reference/7.1/Microsoft.PowerShell.Management/Rename-Item.md
reference/7.2/Microsoft.PowerShell.Management/Rename-Item.md

Fixes [AB#1896249](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1896249) - Fixes #8368 - Add link to Move-Item

Fixes #8368 - Add link to Move-Item

---

reference/5.1/Microsoft.PowerShell.Management/Rename-Item.md
reference/7.0/Microsoft.PowerShell.Management/Rename-Item.md
reference/7.1/Microsoft.PowerShell.Management/Rename-Item.md
reference/7.2/Microsoft.PowerShell.Management/Rename-Item.md

Update Example 2

---

reference/docs-conceptual/developer/provider/provider-cmdlets.md

* Remove redundant and less informative qualifiers for methods
* Apply list format for methods
* Remove the level 2 header `## Provider Cmdlets` (refrain of the title)
* Level 3 headers -> level 2
* Remove meaningless character: `*`
* Remove duplicates: `Invokedefaultaction`
* Fix capitalization

Update "Provider cmdlets" for readability

---

reference/5.1/Microsoft.PowerShell.Utility/Select-String.md
reference/7.0/Microsoft.PowerShell.Utility/Select-String.md
reference/7.1/Microsoft.PowerShell.Utility/Select-String.md
reference/7.2/Microsoft.PowerShell.Utility/Select-String.md

Fix typo: -Steam > -Stream
Microsoft.PowerShell.Utility / Select-String

Fix typo: -Steam > -Stream

---

reference/module/index.md

Updated PowerShell module browser quick filter to Az PowerShell 7.0.0

Updated powershell module browser quick filter to azps 7

---

reference/docs-conceptual/developer/help/how-to-add-parameter-information.md

Fixes #8394 - Fix camel case of xml elements

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

Fixes [AB#1901358](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1901358) - Fixes #8393 - Add note about multiline strings

Fixes #8393 - Add note about multiline strings

---

reference/5.1/Microsoft.PowerShell.Management/Test-Path.md
reference/7.0/Microsoft.PowerShell.Management/Test-Path.md
reference/7.1/Microsoft.PowerShell.Management/Test-Path.md
reference/7.2/Microsoft.PowerShell.Management/Test-Path.md

Fixes [AB#1902375](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1902375) - Fixes #8402 - Fix example 8

Fixes #8402 - Fix example 8

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Output_Streams.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Output_Streams.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Output_Streams.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Output_Streams.md

Fixes [AB#1902549](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1902549) - Fixes #8403 - correct version information for streams

Fixes #8403 - correct version information for streams

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

This change updates the version references to the latest one (7.2.1).

Update Installing-PowerShell-on-Windows.md: version bump to 7.2.1

---

reference/7.2/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md

Fix typo in example

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Fixes [AB#1903321](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1903321) - Fixes #8409 - Update default value for $PSStyle.OutputRendering
[key]: …

Fixes #8409 - Update default value for $PSStyle.OutputRendering

---

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.0/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md

Fixes [AB#1903577](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1903577) - Fixes #8423 - Add example for junction point

Fixes #8423 - Add example for junction point

---

reference/7.2/PSReadLine/Set-PSReadLineOption.md
reference/7.3/PSReadLine/Set-PSReadLineOption.md

Fixes [AB#1903797](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1903797) - Fixes #8428 - Fix formatting error

Fixes #8428 - Fix formatting error

---

reference/docs-conceptual/toc.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#1903797](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1903797) - Add 7.3 release notes to TOC

Add 7.3 release notes to TOC

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#1903820](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1903820) - Fixes #8090 - Add experimental feature PSCleanBlock

Fixes #8090 - Add experimental feature PSCleanBlock

---

reference/docs-conceptual/dev-cross-plat/create-standard-library-binary-Module.md

Fixes [AB#1904050](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1904050) - Fixes #8429 - fix package version

Fixes #8429 - fix package version

---

reference/module/index.md

Updated PowerShell module browser quick filter for Azure PowerShell to version 7.1.0

Updated quickfilter for azps to v7.1.0

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Fixes [AB#1906132](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1906132) - Fixes #8456 - Command-line install of MSI package

Fixes #8456 - Command-line install of MSI package

---

reference/docs-conceptual/learn/ps101/06-flow-control.md

Fix typo in 06-flow-control.md

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md

Fixes [AB#1906149](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1906149) - Fixes #8447 - Fix typo in parameter name

Fixes #8447 - Fix typo in parameter name

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Fixes [AB#1906154](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1906154) - Fixes #8445 - SCCM -> Configuration Manager

Fixes #8445 - SCCM -> Configuration Manager

---

.github/ISSUE_TEMPLATE/New_Issue.yml

Update issue template

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md
reference/7.0/Microsoft.PowerShell.Core/About/about_PSModulePath.md
reference/7.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md
reference/7.3/Microsoft.PowerShell.Core/About/about_PSModulePath.md

Fixes [AB#1906366](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1906366) - Fixes #8469 - Fix typo in example

Fixes #8469 - Fix typo in example

---

reference/docs-conceptual/windows-powershell/wmf/whats-new/new-updated-cmdlets.md

Fixes [AB#1906379](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1906379) - Fixes #8455 - Remove invalid symlink example

Fixes #8455 - Remove invalid symlink example

---

reference/5.1/Microsoft.PowerShell.Utility/Register-EngineEvent.md
reference/7.0/Microsoft.PowerShell.Utility/Register-EngineEvent.md
reference/7.1/Microsoft.PowerShell.Utility/Register-EngineEvent.md
reference/7.2/Microsoft.PowerShell.Utility/Register-EngineEvent.md
reference/7.3/Microsoft.PowerShell.Utility/Register-EngineEvent.md
reference/7.3/PSReadLine/About/about_PSReadLine.md

Fixes [AB#1906164](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1906164) - Fixes #8270 - Update changes to OnIdle event

Fixes #8270 - Update changes to OnIdle event

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md

Added clarifying not about using environment variables as a `Path` argument and an example usage of `Remove-Item`

Added clarifying note about `Remove-Item`

---

reference/docs-conceptual/learn/tutorials/01-discover-powershell.md

Fix minor grammatical errors

---

reference/docs-conceptual/windows-powershell/install/Installing-Windows-PowerShell.md

Corrected Windows icon location for Windows 11

Minor update to location of Windows 11 icon

---

reference/docs-conceptual/developer/format/formatstring-element-for-listitem-for-listcontrol-format.md
reference/docs-conceptual/developer/format/formatstring-element-for-tablecolumnitem-for-tablecontrol-format.md
reference/docs-conceptual/developer/format/formatstring-element-for-wideitem-for-widecontrol-format.md

Fix examples for FormatString element

---

reference/5.1/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.0/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.1/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.2/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.3/Microsoft.PowerShell.Management/New-PSDrive.md

Fixes [AB#1909796](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1909796) - Fixes #8475 - Update short description

Fixes #8475 - Update short description

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md

Fixes [AB#1909800](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1909800) - Fixes #8476 - Update changes to NoLogo option

Fixes #8475 - Update changes to NoLogo option

---

reference/5.1/Microsoft.PowerShell.Core/About/about_While.md
reference/7.0/Microsoft.PowerShell.Core/About/about_While.md
reference/7.1/Microsoft.PowerShell.Core/About/about_While.md
reference/7.2/Microsoft.PowerShell.Core/About/about_While.md
reference/7.3/Microsoft.PowerShell.Core/About/about_While.md

Fixes [AB#1909806](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1909806) - Fixes #8479 - Link to other about topics

Fixes #8479 - Link to other about topics

---

reference/docs-conceptual/windows-powershell/install/Installing-Windows-PowerShell.md

Fixes [AB#1909810](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1909810) - Fixes #8483 - Update info for Windows 11

Fixes #8483 - Update info for Windows 11

---

reference/7.3/Microsoft.PowerShell.Utility/Start-Sleep.md

Fixes [AB#1909824](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1909824) - Fixes #8485 - Add Duration parameter

Fixes #8485 - Add Duration parameter

---

reference/includes/alpine-support.md
reference/includes/centos-support.md
reference/includes/debian-support.md
reference/includes/fedora-support.md
reference/includes/macos-support.md
reference/includes/rhel-support.md
reference/includes/ubuntu-support.md
reference/includes/windows-support.md

Fixes [AB#1910453](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1910453) - Fixes #8498 - Add Debian 11 and 7.3 preview support

Fixes #8498 - Add Debian 11 and 7.3 preview support

---

reference/docs-conceptual/windows-powershell/install/Installing-Windows-PowerShell.md

Minor update to location of Windows 11 icon (missed second table)

---

reference/7.3/Microsoft.PowerShell.Core/Switch-Process.md
reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#1910502](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1910502) - Fixes #8349 - Add Switch-Process docs

Fixes #8349 - Add Switch-Process docs

---

reference/docs-conceptual/developer/format/creating-a-list-view.md
reference/docs-conceptual/developer/format/creating-a-table-view.md
reference/docs-conceptual/developer/format/creating-a-wide-view.md

Fix Format examples

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Signing.md

Fixes [AB#1911222](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1911222) - Fixes #8506 - Update encoding information for signed scripts
[key]: …

Fixes #8506 - Update encoding information for signed scripts

---

reference/docs-conceptual/install/install-ubuntu.md

Fixes [AB#1911616](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1911616) - Fixes #8513 - Update package name for lts

Fixes #8513 - Update package name for lts

---

reference/7.3/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.3/Microsoft.PowerShell.Core/New-PSSession.md

Fixes [AB#1911659](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1911659) - Fixes #6046 - Add ssh options to remote cmdlets

Fixes #6046 - Add ssh options to remote cmdlets

---

reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Fixes [AB#1911857](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1911857) - Fixes #8065 - Add HttpVersion parameter

Fixes #8065 - Add HttpVersion parameter

---

reference/docs-conceptual/developer/hosting/windows-powershell-host-quickstart.md

Fixes [AB#1912065](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1912065) - Fixes #8519 - Add no-loc hints

Fixes #8519 - Add no-loc hints

---

reference/5.1/Microsoft.PowerShell.Management/Set-Location.md
reference/7.0/Microsoft.PowerShell.Management/Set-Location.md
reference/7.1/Microsoft.PowerShell.Management/Set-Location.md
reference/7.2/Microsoft.PowerShell.Management/Set-Location.md
reference/7.3/Microsoft.PowerShell.Management/Set-Location.md

Fixes [AB#1912091](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1912091) - Fixes #8442 - Update -Path and -StackName descriptions

Fixes #8442 - Update -Path and -StackName descriptions

---

reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md

Fixes [AB#1912126](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1912126) - Fixes #8450 - Update approved verbs

Fixes #8450 - Update approved verbs

---

reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.0/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.1/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.3/Microsoft.PowerShell.Utility/Compare-Object.md

Fixes [AB#1912183](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1912183) - Fixes #8522 - Fix typo in NOTES section

Fixes #8522 - Fix typo in NOTES section

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Wildcards.md

Fixes [AB#1912423](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1912423) - Fixes #8527 - Add example matching a literal wildcard character
[key]: …

Fixes #8527 - Add example matching a literal wildcard character

---

reference/5.1/Microsoft.PowerShell.Core/Get-Module.md
reference/7.0/Microsoft.PowerShell.Core/Get-Module.md
reference/7.1/Microsoft.PowerShell.Core/Get-Module.md
reference/7.2/Microsoft.PowerShell.Core/Get-Module.md
reference/7.3/Microsoft.PowerShell.Core/Get-Module.md

Fixes [AB#1912828](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1912828) - Fixes #8449 - Note -FullyQualifiedName supports simpler formats
[key]: …

Fixes #8449 - Note -FullyQualifiedName supports simpler formats

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Pipelines.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Pipelines.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Pipelines.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Pipelines.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Pipelines.md

Fixes [AB#1912856](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1912856) - Fixes #8446 - Pipelines don't support raw data output

Fixes #8446 - Pipelines don't support raw data output

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Switch.md

Fixes [AB#1912923](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1912923) - Fixes #8464 - Clarify switch behavior

Fixes #8464 - Clarify switch behavior

---

reference/docs-conceptual/learn/deep-dives/everything-about-switch.md

Fixes [AB#1913331](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1913331) - Fixes #8453 - Add more detailed example for $null cases …

Fixes #8453 - Add more detailed example for $null cases

---

reference/5.1/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.0/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.1/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.2/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.3/Microsoft.PowerShell.Utility/Format-Wide.md

Update `-Property` parameter description for `Format-Wide` cmdlet

Update `-Property` parameter description for `Format-Wide` cmdlet

---

reference/5.1/Microsoft.PowerShell.Security/Set-Acl.md
reference/7.0/Microsoft.PowerShell.Security/Set-Acl.md
reference/7.1/Microsoft.PowerShell.Security/Set-Acl.md
reference/7.2/Microsoft.PowerShell.Security/Set-Acl.md
reference/7.3/Microsoft.PowerShell.Security/Set-Acl.md

Corrected grammar and ambiguous punctuation

---

reference/5.1/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.0/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.1/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.2/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.3/Microsoft.PowerShell.Utility/Update-TypeData.md

Update `-DefaultDisplayPropertySet` parameter description for the `Update-TypeData` cmdlet

Update `-DefaultDisplayPropertySet` parameter description for the `Update-TypeData` cmdlet

---

reference/5.1/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.0/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.1/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.2/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.3/Microsoft.PowerShell.Management/New-PSDrive.md

Fixes [AB#1914093](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1914093) - Fixes #8550 - Add note about scope for scripts

Fixes #8550 - Add note about scope for scripts

---

reference/7.1/Microsoft.PowerShell.Utility/Read-Host.md
reference/7.2/Microsoft.PowerShell.Utility/Read-Host.md
reference/7.3/Microsoft.PowerShell.Utility/Read-Host.md

Fixes [AB#1914156](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1914156) - Fixes #8551 - Add note about parameter added in 7.1

Fixes #8551 - Add note about parameter added in 7.1

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Calling_Generic_Methods.md

Fixes [AB#1914169](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1914169) - Fixes #8533 - Add doc for using generic methods

Fixes #8533 - Add doc for using generic methods

---

reference/docs-conceptual/whats-new/cmdlet-versions.md

Fixes [AB#1914908](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1914908) - Add 7.3 to module history

Add 7.3 to module history

---

reference/5.1/Microsoft.PowerShell.Utility/Select-String.md
reference/7.0/Microsoft.PowerShell.Utility/Select-String.md
reference/7.1/Microsoft.PowerShell.Utility/Select-String.md
reference/7.2/Microsoft.PowerShell.Utility/Select-String.md
reference/7.3/Microsoft.PowerShell.Utility/Select-String.md

Fixes [AB#1915592](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1915592) - Fixes #8570 - Fix formatting and typo in example

Fixes #8570 - Fix formatting and typo in example

---

reference/bread/toc.yml

Fixes [AB#1916242](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1916242) - Update breadcrumb toc

Update breadcrumb toc

---

reference/module/index.md

Updated quick filter in PowerShell module browser to AzPS 7.2.0

Updated quick filter to azps 7.2.0

---

.openpublishing.publish.config.json

Fixes [AB#1916936](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1916936) - Remove basepath from xref_query_tags

Remove basepath from xref_query_tags

---

reference/docs-conceptual/gallery/faqs.yml
reference/docs-conceptual/install/microsoft-update-faq.yml
reference/docs-conceptual/learn/remoting/powershell-remoting-faq.yml

Set ms.topic: faq where YamlMime:FAQ
Note the following:
- DocuTune drives improved quality of technical content by finding and automatically correcting a broad set of issues in Markdown and YAML files. DocuTune performs these updates intelligently, only making corrections in the sections of a document where the correction is suitable.
- DocuTune PRs often standardize spacing, formatting, and casing of Markdown elements to support the DocuTune onboarding process.
- DocuTune PRs might contain other minor edits noticed during a manual review.
- DocuTune PRs might include files whose Acrolinx score was below the target threshold prior to this PR.
- Delimiters such as asterisks and backticks may be added to link descriptions or alt-text to denote UI elements or other string literals that …

Set ms.topic: faq where YamlMime:FAQ

---

reference/5.1/PowershellGet/Register-PSRepository.md
reference/7.0/PowerShellGet/Register-PSRepository.md
reference/7.1/PowerShellGet/Register-PSRepository.md
reference/7.2/PowerShellGet/Register-PSRepository.md
reference/7.3/PowerShellGet/Register-PSRepository.md

Fixes [AB#1919300](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1919300) - Fixes #8590 - Add description for -Default parameter

Fixes #8590 - Add description for -Default parameter

---

reference/5.1/PSReadLine/About/about_PSReadLine.md
reference/7.0/PSReadLine/About/about_PSReadLine.md
reference/7.1/PSReadLine/About/about_PSReadLine.md
reference/7.2/PSReadLine/About/about_PSReadLine.md
reference/7.3/PSReadLine/About/about_PSReadLine.md

Fixes [AB#1920219](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1920219) - Fixes #8595 - Fix Shell*Word descriptions

Fixes #8595 - Fix Shell*Word descriptions

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md

Fixes AB#1924887 - Fixes #8604 - Clarify *Variable parameter descriptions

Fixes #8604 - Clarify *Variable parameter descriptions

---

reference/module/index.md

Updated the PowerShell module browser quick filter for the Az PowerShell module to version 7.3.0.

Updated azps quick filter to version 7.3.0

---

reference/5.1/PSReadLine/About/about_PSReadLine.md
reference/7.0/PSReadLine/About/about_PSReadLine.md
reference/7.1/PSReadLine/About/about_PSReadLine.md
reference/7.2/PSReadLine/About/about_PSReadLine.md
reference/7.3/PSReadLine/About/about_PSReadLine.md

Fixes AB#1925988 - Fixes #8606 - Add example description for DigitArgument

Fixes #8606 - Add example description for DigitArgument

---

reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md

Fixes AB#1927092 - Fixes #8623 - Fix backslash escaping

Fixes #8623 - Fix backslash escaping

---

reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/learn/security-features.md

Fixes AB#1927076 - Fixes #8619 - Add AMSI docs

Fixes #8619 - Add AMSI docs

---

reference/docs-conceptual/dev-cross-plat/create-help-using-platyps.md

Fix encoding parameter in example. PlatyPS expects the enum instead of a string.

Fix encoding parameter in example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md

Fixes AB#1928992 - Fixes #8603 - Reorder parameter set requirements

Fixes #8603 - Reorder parameter set requirements

---

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
reference/includes/alpine-support.md
reference/includes/centos-support.md
reference/includes/debian-support.md
reference/includes/fedora-support.md
reference/includes/rhel-support.md
reference/includes/ubuntu-support.md

Fixes AB#1928756 - Fixes #8643 - Update supported Linux versions

Fixes #8643 - Update supported Linux versions

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes AB#1929718 - Fixes #8620 - Update 7.3-preview.2 release notes

Fixes #8620 - Update 7.3-preview.2 release notes

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.0/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.1/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.3/Microsoft.PowerShell.Utility/Write-Information.md

This PR corrects the paragraph for the first example to match the actual example code and cleans up formatting/language in the document.
- Fixes #8658

(GH-8658) Update Write-Information

---

reference/module/index.md

Updated PowerShell module browser quick filter for Az PowerShell to version 7.3.2. 

Updated azps quick filter to v7.3.2

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md

Fix online URL for 7.3 doc

---

reference/docs-conceptual/install/microsoft-update-faq.yml

Fixes AB#1931810 - Fixes #8675 - Update MU FAQ

Fixes #8675 - Update MU FAQ

---

reference/7.0/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md
reference/7.1/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md
reference/7.3/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-centos.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-fedora.md
reference/docs-conceptual/install/install-other-linux.md
reference/docs-conceptual/install/install-raspbian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md

Fixes AB#1932641 - Update version numbers for latest releases

Update version numbers for latest releases

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes AB#1933065 - Fixes #8684 - Update 7.3-preview.3 release notes

Fixes #8684 - Update 7.3-preview.3 release notes

---

reference/docs-conceptual/install/install-debian.md

added Debian 11 Bullseye installation

---

reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Fixes AB#1933535 - Fixes #8692 - Remove confusion about bearer and oauth

Fixes #8692 - Remove confusion about bearer and oauth

---

reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md

Fixes #8695 - fix bookmark link

Fixes #8695 - fix bookmark link

---

reference/docs-conceptual/community/2022-updates.md
reference/docs-conceptual/community/hall-of-fame.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-71.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-72.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md
reference/docs-conceptual/windows-powershell/whats-new/What-s-New-in-Windows-PowerShell-50.md

Fixes AB#1934166 
- Update monthly stats and What's New 
- Added end-of-file markers to release notes

- Update monthly stats and What's New - Added end-of-file markers to release notes

---

.github/workflows/targeting-valid-branch.yml

This commit adds an echo to the GHA for validating that a PR author has authorization
to submit a PR to the Live branch. It reports the username and discovered permissions
before echoing that the author has permissions or throwing if they do not.
[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/o …

(MAINT) Add echo to live branch check

---

reference/module/index.md

Updated PowerShell module browser quick filter for Az PowerShell to version 7.4.0

Updated quick filter for azps to 7.4.0

---

reference/docs-conceptual/gallery/getting-started.md

Fixes AB#1941638 - Fixes #8745 - Add hostname to allow list

Fixes #8745 - Add hostname to allow list

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Updated the document with the latest version number 7.2.3 + updated the preview version mentioned in the doc to 7.3.0.3.

7.2.3 Updated the document with the latest version number.

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
reference/5.1/Microsoft.PowerShell.Management/New-ItemProperty.md
reference/5.1/Microsoft.PowerShell.Management/Set-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
reference/7.0/Microsoft.PowerShell.Management/New-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Management/Set-ItemProperty.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
reference/7.1/Microsoft.PowerShell.Management/New-ItemProperty.md
reference/7.1/Microsoft.PowerShell.Management/Set-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
reference/7.2/Microsoft.PowerShell.Management/New-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Management/Set-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
reference/7.3/Microsoft.PowerShell.Management/New-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Management/Set-ItemProperty.md

Fixes AB#Update -PropertyType description - Fixes #8739 - 

Fixes #8739 - Update description of PropertyType parameter

---

reference/docs-conceptual/community/hall-of-fame.md

Fixes AB#1945370 - Update Hall of Fame

Update Hall of Fame

---

reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
reference/7.0/Microsoft.PowerShell.Core/Import-Module.md
reference/7.1/Microsoft.PowerShell.Core/Import-Module.md
reference/7.2/Microsoft.PowerShell.Core/Import-Module.md
reference/7.3/Microsoft.PowerShell.Core/Import-Module.md

Fixes AB#1946130 - Fixes #8789 - Add no-loc metadata

Fixes #8789 - Add no-loc metadata

---

reference/docs-conceptual/developer/help/how-to-create-the-cmdlet-help-file.md

Typo on example XML

---

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-centos.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-fedora.md
reference/docs-conceptual/install/install-other-linux.md
reference/docs-conceptual/install/install-raspbian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes AB#1948848 - Update PS Version numbers and links

Update PS Version numbers and links

---

reference/5.1/Microsoft.PowerShell.Utility/Update-List.md
reference/7.0/Microsoft.PowerShell.Utility/Update-List.md
reference/7.1/Microsoft.PowerShell.Utility/Update-List.md
reference/7.2/Microsoft.PowerShell.Utility/Update-List.md
reference/7.3/Microsoft.PowerShell.Utility/Update-List.md

(GH-8804) Remove erroneous reference from Update-List

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md

Continuation of #8817 - Add info about end-of-parameters token

Fix broken bookmarks from #8819

---

reference/5.1/Microsoft.PowerShell.Management/Resolve-Path.md
reference/7.0/Microsoft.PowerShell.Management/Resolve-Path.md
reference/7.1/Microsoft.PowerShell.Management/Resolve-Path.md
reference/7.2/Microsoft.PowerShell.Management/Resolve-Path.md
reference/7.3/Microsoft.PowerShell.Management/Resolve-Path.md

Fixes AB#1949665 - Fixes #8814 - Fix formatting and Example #3 description

Fixes #8814 - Fix formatting and Example #3 description

---

reference/5.1/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.0/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.1/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.2/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.3/Microsoft.PowerShell.Utility/Start-Sleep.md

Fixes AB#1949667 - Fixes #8809 - Update description of Start-Sleep

Fixes #8809 - Update description of Start-Sleep

---

reference/docs-conceptual/overview.md

Add link to videos

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fixes AB#1950985 - Fixes #8828 - List all case-sensitive operators and reformat

Fixes #8828 - List all case-sensitive operators and reformat

---

reference/5.1/Microsoft.PowerShell.Management/New-Item.md

(GH-8829) Add symlink example to New-Item in 5.1

---

reference/docs-conceptual/toc.yml

Remove 7.1 release notes from TOC

Remove 7.1 release notes from TOC

---

reference/5.1/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md
reference/7.0/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md
reference/7.2/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md
reference/7.3/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md

Fixes AB#1951669 - Fixes #8840 - Fix description of ShowSecurityDescriptorUI parameter

Fixes #8840 - Fix description of ShowSecurityDescriptorUI parameter

---

reference/5.1/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md
reference/7.0/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md
reference/7.2/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md
reference/7.3/Microsoft.PowerShell.Core/Set-PSSessionConfiguration.md
reference/docs-conceptual/install/install-fedora.md

5/19 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md
reference/7.0/Microsoft.PowerShell.Utility/Add-Member.md
reference/7.2/Microsoft.PowerShell.Utility/Add-Member.md
reference/7.3/Microsoft.PowerShell.Utility/Add-Member.md

Removed example #5 on `Add-Member` and renumbered - Fixes #8753 

Remove example #5, renumbered.

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Language_Keywords.md

Fixes AB#1953039 - Fixes #8862 - Add assembly syntax for using

Fixes #8862 - Add assembly syntax for using

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md

Fixes AB#1953050 - Fixes #8860 - Add note about passing array arguments

Fixes #8860 - Add note about passing array arguments

---

.markdownlint.json
reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.0/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.2/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.3/Microsoft.PowerShell.Management/Copy-Item.md
reference/includes/windows-support.md

Fixes AB#1953497 - Fixes #8866 - Update Copy-Item example 8
This also includes two cleanup items
- an update to our markdownlint rules
- an update in the Windows include file for supported versions
[key]: …

Fixes #8866 - Update Copy-Item example 8

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Trap.md

Fixes AB#1953691 - Fixes #8865 - Fix definition of scope for traps

Fixes #8865 - Fix definition of scope for traps

---

reference/docs-conceptual/community/community-update.yml
reference/docs-conceptual/toc.yml

Fixes AB#1954452 - Restructure TOC and Community Landing page

Restructure TOC and Community Landing page

---

reference/docs-conceptual/learn/security-features.md

- Resolves #8874
- Resolves AB#1954437

(GH-8874) Add note on WDAC API support for 7.3-preview.4

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

- Resolves #8875
- Resolves AB#1954438

(GH-8875) Add tab completion improvements for 7.3-preview.4

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Fixes AB#1955848 - Fixes #8881 - Add MSI option to example

Fixes #8881 - Add MSI option to example

---

reference/5.1/Microsoft.PowerShell.Core/Get-Module.md
reference/7.0/Microsoft.PowerShell.Core/Get-Module.md
reference/7.2/Microsoft.PowerShell.Core/Get-Module.md
reference/7.3/Microsoft.PowerShell.Core/Get-Module.md

Fixes AB#1956728 - Fixes #8898 - Clarify how fully qualified names work for modules

Fixes #8898 - Clarify how fully qualified names work for modules

---

reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.0/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.2/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.3/Microsoft.PowerShell.Utility/Send-MailMessage.md

Fixes AB#1957103 - Fixes #8901 - Update -To parameter description

Fixes #8901 - Update -To parameter description

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

This change adds documentation for the new **ConfigurationFile** parameter added to the `pwsh` executable in PowerShell/PowerShell#17447.
- Resolves #8907

(GH-8907) Document ConfigurationFile param for pwsh

---

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md

Fixes AB#1958416 - continuation of PR #8912 and #8913
- Copies the changes from those two PR to the other versions.

Fixes #8912 - Copy changes from community PR

---

reference/docs-conceptual/developer/module/how-to-write-a-powershell-script-module.md

A small change to the documentation on line 114.
Converted this paragraph to a "note" to draw more attention to the auto-import feature of Powershell 3.0

Update How to Write a PowerShell Script Module

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fixes #8911 - Fix syntax of example uner Common Features

---

.github/actions/verification/authorization/v1/Parameters.psd1
.github/actions/verification/authorization/v1/action.yml
.github/actions/verification/authorization/v1/readme.md
.github/workflows/targeting-repo-files.yml

Prior to this change, the parameter handling for the authorization action was implemented with a minimal handler for the **target** input and the associated workflow used an incorrect list of file globs to check for.
This change corrects the file globs for the workflow and updates the implementation of the action to handle targets separated by commas and newlines, including when those separators are intermingled. It also ensures that the items in the target list passed to the action script are trimmed of whitespace and surrounding quotes.
This enables a more maintainable workflow file for consumers of the action by allowing them to use multiple lines to list their targets, making the use of commas optional when specifying targets on multiple lines, and handling indentation and quoting. …

(MAINT) Improve authorization target handling

---

reference/7.3/CimCmdlets/Get-CimClass.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes AB#1958770 - Fixes #8902 - Add Amended parameter to Get-CimClass for 7.3

Fixes #8902 - Add Amended parameter to Get-CimClass for 7.3

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes AB#1958798 - Fixes #8892 - Update ANSI behavior changes in 7.3

Fixes #8892 - Update ANSI behavior changes in 7.3

---

reference/5.1/Microsoft.PowerShell.Utility/Out-File.md
reference/7.0/Microsoft.PowerShell.Utility/Out-File.md
reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.2/Microsoft.PowerShell.Utility/Out-File.md
reference/7.2/Microsoft.PowerShell.Utility/Out-String.md
reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.3/Microsoft.PowerShell.Utility/Out-File.md
reference/7.3/Microsoft.PowerShell.Utility/Out-String.md

Fixes #8892 - This is a continuation of PR #8922 based on more feedback from @daxian-dbw 

Fixes #8922 - Update ANSI behavior changes in 7.3

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/5.1/Microsoft.PowerShell.Utility/New-Variable.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.0/Microsoft.PowerShell.Utility/New-Variable.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.2/Microsoft.PowerShell.Utility/New-Variable.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.3/Microsoft.PowerShell.Utility/New-Variable.md

Fixes AB#1958822 - Fixes #8908 - Update description of Private option for variables

Fixes #8908 - Update description of Private option for variables

---

reference/7.3/Microsoft.PowerShell.Utility/Measure-Command.md

add missing word "Filter" in description of Measure-Command.md

add missing word in description of Measure-Command.md

---

reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md
reference/7.0/Microsoft.PowerShell.Utility/Measure-Command.md
reference/7.2/Microsoft.PowerShell.Utility/Measure-Command.md
reference/7.3/Microsoft.PowerShell.Utility/Measure-Command.md

Fixes #8927 - Copy changes from #8927 to all versions

Fixes #8927 - Copy changes from #8927 to all versions

---

.github/workflows/expectations.yml

Reduce workflow executions by half.

(MAINT) Set Expectations worfklow to run every 10m

---

reference/5.1/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.0/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md

Fixes AB#1962823 - Fixes #8937 - Add note about ThrottleLimit and AsJob

Fixes #8937 - Add note about ThrottleLimit and AsJob

---

reference/docs-conceptual/install/microsoft-update-faq.yml

Fixes AB#1962869 - Fixes #8936 - Update MSI repair instructions

Fixes #8936 - Update MSI repair instructions

---

reference/docs-conceptual/install/microsoft-update-faq.yml

Adding more clarity to the lack of support for Windows server 2016 for PowerShell Microsoft Updates. Let me know if this would be better broken out to be a seperate question
This changes addes more clarification to why MU for PowerShell fails for Windows Server 2016. Since Windows Server 2016 is version [1607](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info), it is not supported for Microsoft Updates.

Adding Server 2016 support details for MU

---

reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
reference/7.0/Microsoft.PowerShell.Core/Import-Module.md
reference/7.2/Microsoft.PowerShell.Core/Import-Module.md
reference/7.3/Microsoft.PowerShell.Core/Import-Module.md

Fixes AB#1963876 - Fixes #8957 - Add cmdlet name to no-loc

Fixes #8957 - Add cmdlet name to no-loc

---

reference/5.1/PSReadLine/About/about_PSReadLine.md
reference/5.1/PSReadLine/PSReadLine.md
reference/7.0/PSReadLine/About/about_PSReadLine.md
reference/7.0/PSReadLine/PSReadLine.md
reference/7.2/PSReadLine/About/about_PSReadLine.md
reference/7.2/PSReadLine/PSReadLine.md
reference/7.3/PSReadLine/About/about_PSReadLine.md
reference/7.3/PSReadLine/PSReadLine.md

Fixes AB#1964866 - Fixes #8943 - Update release notes for 2.2.6

Fixes #8943 - Update release notes for 2.2.6

---

reference/5.1/PSReadLine/About/about_PSReadLine.md
reference/7.0/PSReadLine/About/about_PSReadLine.md
reference/7.2/PSReadLine/About/about_PSReadLine.md
reference/7.3/PSReadLine/About/about_PSReadLine.md

Fixes #8961 - Fix PS version requirements for predictor plug-ins

Fixes #8961 - Fix PS version requirements for predictor plug-ins

---

reference/5.1/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.0/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.2/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.3/Microsoft.PowerShell.Utility/Start-Sleep.md

Fixes AB#1965570 - Fixes #8967 - Fix description of example

Fixes #8967 - Fix description of example

---

reference/docs-conceptual/windows-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md

Remove duplicate text _by default_.

[minor] remove dittography

---

reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.0/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md
reference/docs-conceptual/install/community-support.md

Fixes AB#1965762 - Fix random errors found in drive-bys

Fix random errors found in drive-bys

---

reference/module/index.md

Fixes AB#1967042 - Update AzPS quicklink to 8.1.0

Update AzPS quicklink to 8.1.0

---

.github/actions/.pwsh/module/functions/utility/Get-StaleDocument.ps1
.github/actions/.pwsh/module/gha.psd1
.github/actions/.pwsh/module/readme.md
.github/actions/.pwsh/scripts/Get-StaleContentReport.md
.github/actions/.pwsh/scripts/Get-StaleContentReport.ps1
.github/actions/reporting/stale-content/v1/Parameters.psd1
.github/actions/reporting/stale-content/v1/action.yml
.github/actions/reporting/stale-content/v1/readme.md
.github/workflows/stale-content.yml
.gitignore

Prior to this change, inspection of stale content was mandatory or relied on externally retrieved and hosted data. This change:
- Adds the new `Get-StaleDocument` function to the GitHub Actions module to support inspecting the repository for stale content. For more information on how it works, see the comment-based help in the function's definition file.
- Adds the new `Get-StaleContentReport` script, which can be used to inspect a repository for stale documentation, write a report summary in the console and to GitHub Actions, export the report as a CSV, mark the exported report for upload via GitHub Actions, and return the result object directly. For more information on how it works, see the markdown help for the script.
- Defines the new `reporting/stale-content` GitHub Action for …

(AB-1948154) Add stale content reporting

---

reference/docs-conceptual/install/microsoft-update-faq.yml

Adding more clarity around repair installations and how MU check boxes will not be shown and thus must utilize command listed.
Clarifying wording around repair installations not having the option to opt into MU updates and thus need to run the command already specified in the doc. 

Clarification for MU update options when repairing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fix `-cgt` operator typo in `about_Comparison_Operators.md`

Fix operator typo

---

reference/5.1/Microsoft.PowerShell.Utility/Out-String.md
reference/7.0/Microsoft.PowerShell.Utility/Out-String.md
reference/7.2/Microsoft.PowerShell.Utility/Out-String.md
reference/7.3/Microsoft.PowerShell.Utility/Out-String.md

Add note about OSS

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md

Fixes [AB#4371](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4371) - Fixes #9027 - Add no-loc for kbd values

Fixes #9027 - Add no-loc for kbd values

---

reference/docs-conceptual/gallery/getting-started.md

Fixes [AB#4372](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4372) - Fixes #9018 - Add note about active names for allowlist
- cleaned up some formatting issues too

Fixes #9018 - Add note about active names for allowlist

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Properties.md

Continuatio of changes introduced in #9031 - Sync changes and update formatting

Fixes #9031 - Sync changes and update formatting

---

reference/5.1/PackageManagement/Find-Package.md
reference/5.1/PackageManagement/Get-Package.md
reference/5.1/PackageManagement/Install-Package.md
reference/5.1/PackageManagement/PackageManagement.md
reference/5.1/PackageManagement/Uninstall-Package.md
reference/7.0/PackageManagement/Find-Package.md
reference/7.0/PackageManagement/Get-Package.md
reference/7.0/PackageManagement/Install-Package.md
reference/7.0/PackageManagement/PackageManagement.md
reference/7.0/PackageManagement/Uninstall-Package.md
reference/7.2/PackageManagement/Find-Package.md
reference/7.2/PackageManagement/Get-Package.md
reference/7.2/PackageManagement/Install-Package.md
reference/7.2/PackageManagement/PackageManagement.md
reference/7.2/PackageManagement/Uninstall-Package.md
reference/7.3/PackageManagement/Find-Package.md
reference/7.3/PackageManagement/Get-Package.md
reference/7.3/PackageManagement/Install-Package.md
reference/7.3/PackageManagement/PackageManagement.md
reference/7.3/PackageManagement/Uninstall-Package.md
reference/includes/nuget-module.md

Fixes [AB#4434](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4434) - Fixes #9023 - Add note about NuGet package in Visual Studio

Fixes #9023 - Add note about NuGet package in Visual Studio

---

reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#4446](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4446) - Fixes #9017 - PSNativePSPathResolution  no longer supported

Fixes #9017 - PSNativePSPathResolution  no longer supported

---

reference/5.1/Microsoft.PowerShell.Core/Update-Help.md
reference/7.0/Microsoft.PowerShell.Core/Update-Help.md
reference/7.2/Microsoft.PowerShell.Core/Update-Help.md
reference/7.3/Microsoft.PowerShell.Core/Update-Help.md

Update Example 3 for locale

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions.md

Fix the definition of a filter

Fix the definition of a filter

---

reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.0/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.2/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.3/Microsoft.PowerShell.Management/Copy-Item.md

Fixes [AB#4582](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4582) - Fixes #9048 - Fix note in Example 2 and tidy formatting

Fixes #9048 - Fix note in Example 2 and tidy formatting

---

reference/includes/macos-support.md

Fixes [AB#4587](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4587) - Fixes #9055 - Fix references to Windows in macOS include file

Fixes #9055 - Fix references to Windows in macOS include file

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#4725](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4725) - Update release notes for 7.3-preview.6

Update release notes for 7.3-preview.6

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Fixes [AB#4736](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4736) - Fixes #9066 - Fix some formatting and clean up wording

Fixes #9066 - Fix some formatting and clean up wording

---

reference/module/index.md

Updated the PowerShell module browser quick filter for the Az PowerShell module to version 8.2.0.

Updated azps module browser quick filter to v8.2.0

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Fixes [AB#4816](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4816) - Fixes #9079 - Add note about Arm64 install from Store package

Fixes #9079 - Add note about Arm64 install from Store package

---

reference/docs-conceptual/windows-powershell/wmf/overview.md

Fixes [AB#4850](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4850) - Add end of support dates for Windows

Add end of support dates for Windows

---

reference/docs-conceptual/toc.yml
reference/docs-conceptual/whats-new/overview.yml

Fixes [AB#4915](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4915) - Add landing page for What's New

Add landing page for What's New

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md

* Fix typos
* Add shorter form of the command

Fix about_Functions_OutputTypeAttribute.md

---

reference/docs-conceptual/dev-cross-plat/resolving-dependency-conflicts.md

Fixes [AB#4922](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4922) - Fixes #9095 - Clarify version of assembly and intent of article

Fixes #9095 - Clarify version of assembly and intent of article

---

reference/5.1/PowershellGet/Save-Module.md
reference/7.0/PowerShellGet/Save-Module.md
reference/7.2/PowerShellGet/Save-Module.md
reference/7.3/PowerShellGet/Save-Module.md

Fixes [AB#4923](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4923) - Fixes #9094 - Update description of Force parameter

Fixes #9094 - Update description of Force parameter

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Recommend WinGet

---

reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Fixes [AB#4993](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4993) - Fixes #9108 - Remove link references

Fixes #9108 - Remove link references

---

reference/docs-conceptual/gallery/concepts/package-manifest-affecting-ui.md

Fixes [AB#4994](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4994) - Split out metadata mapping by module and script

Split out metadata mapping by module and script

---

reference/docs-conceptual/gallery/concepts/package-manifest-affecting-ui.md

Fixes [AB#4994](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4994) - Change to link refs

Change to link refs

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#5002](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5002) - Update release notes for 7.3-preview.7

Update release notes for 7.3-preview.7

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md

Fixes [AB#5006](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5006) - Fixes #9116 - Add NoProfileLoadTime parameter

Fixes #9116 - Add NoProfileLoadTime parameter

---

reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#5007](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5007) - Fixes #9117 - Add find.exe to list of legacy special cases

Fixes #9117 - Add find.exe to list of legacy special cases

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md

Fixes [AB#5008](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5008) - Fixes #9118 - Add [ordered] type accelerator

Fixes #9118 - Add [ordered] type accelerator

---

reference/7.3/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md

Fixes [AB#5009](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5009) - Fixes #9119 - Clarify format of -TimestampServer

Fixes #9119 - Clarify format of -TimestampServer

---

reference/docs-conceptual/install/install-rhel.md

…d Hat Enterprise Linux. (#9126)
If the command assumes positive response during invocation of `yum`, it should when it invokes `dnf`. This is supported not least by how for recent versions of RHEL and Fedora, `yum` is a merely symbolic link to `dnf` anyway.
Additionally, I have utilized the long versions of the flags so that the documentation is easier for users ignorant of what the flags perform to comprehend what they perform. Causes installation to be less scary.

Daily publishing 8/15 3pm

---

reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.0/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Enter-PSSession.md

* Fix example 7 description
Not using `-Port` parameter but infer that from the `-HostName` parameter.
* Editorial changes and copy to other versions
Co-authored-by: Sean Wheeler <sean.wheeler@microsoft.com>

Daily Publishing 8/16 3PM

---

reference/docs-conceptual/learn/shell/using-predictors.md

Fix typo in using-predictors.md

---

reference/docs-conceptual/toc.yml

Restore Gallery to root TOC

---

reference/docs-conceptual/learn/more-powershell-learning.md

Fixes [AB#5086](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5086) - Fix Channel9 urls - point at new Docs video site

Fix Channel9 urls - point at new Docs video site

---

reference/docs-conceptual/gallery/toc.yml

Fix PSGallery TOC

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-raspbian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/install/microsoft-update-faq.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#5087](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5087) - Fixes #9149 - Update version numbers for new releases

Fixes #9149 - Update version numbers for new releases

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-raspbian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/install/microsoft-update-faq.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

8/19 PM Publishing

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

The MSIEXEC sample and options description excludes ADD_PATH and as such doesn't demonstrate how to enable an important supported option.  Adding this will save future readers time and increase the completeness of the document.

Add ADD_PATH MSI option to installation instructions

---

reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md
reference/7.0/Microsoft.PowerShell.Utility/Get-FileHash.md
reference/7.2/Microsoft.PowerShell.Utility/Get-FileHash.md
reference/7.3/Microsoft.PowerShell.Utility/Get-FileHash.md

The default value of the parameter "-Algorithm" is SHA256 like mentioned in other parts of the document.

Changed the default value to SHA256

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md

Fixes [AB#5098](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5098) - Fixes #9156 - Update description of -Noninteractive

Fixes #9156 - Update description of -Noninteractive

---

reference/docs-conceptual/learn/shell/running-commands.md
reference/docs-conceptual/toc.yml

Add article about running commands in the shell

Add article about running commands in the shell

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Throw.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Throw.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Throw.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Throw.md

about_Throw.md: link about_Try_Catch_Finally

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md

Fixes [AB#5119](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5119) - Fixes #9160 - Explain compound operators and dynamic scope

Fixes #9160 - Explain compound operators and dynamic scope

---

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
reference/7.2/Microsoft.PowerShell.Management/Start-Process.md
reference/7.3/Microsoft.PowerShell.Management/Start-Process.md

* Document appropriate use of Start-Process
* Fix example 8 parameter usage
* Fix typos

8/25 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions.md

Extend filter example in **about_Functions.md**

Extend filter example in about_Functions.md

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fix a typo in **about_Comparison_Operators.md**

Fix a typo in about_Comparison_Operators.md

---

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md

Fixes [AB#5190](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5190) - Fixes #9141 - Add note that -nologo no longer required in 7.3

Fixes #9141 - Add note that -nologo no longer required in 7.3

---

reference/docs-conceptual/community/2022-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Fixes [AB#5052](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5052) - Update monthly stats

Update monthly stats and what's new

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md

Fixes [AB#5278](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5278) - Fixes #9182 - Clarify redirection of ANSI output

Fixes #9182 - Clarify redirection of ANSI output

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md

Fixes [AB#5287](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5287) - Fixes #9182 - Update changes made in 7.2.6

Fixes #9182 - Update changes made in 7.2.6

---

reference/5.1/Microsoft.PowerShell.Core/New-PSSessionOption.md
reference/7.0/Microsoft.PowerShell.Core/New-PSSessionOption.md
reference/7.2/Microsoft.PowerShell.Core/New-PSSessionOption.md
reference/7.3/Microsoft.PowerShell.Core/New-PSSessionOption.md

MaximumReceivedObjectSize has confusing information. The value is the maximum size in bytes, however, the documentation listed the default as megabytes. Updated the reference to include the correct information.

Update New-PSSessionOption.md - Fix MaximumReceivedObjectSize detail

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md

Fixes [AB#5368](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5368) - Fixes #9198 - Fix profiles paths for 5.1

Fixes #9198 - Fix profiles paths for 5.1

---

reference/module/index.md

Updated PowerShell module browser quick filter for Az PowerShell to version 8.3.0.

Updated azps quick filter to v8.3.0

---

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
reference/7.2/Microsoft.PowerShell.Management/Start-Process.md
reference/7.3/Microsoft.PowerShell.Management/Start-Process.md

Fixes [AB#6272](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/6272) - Fixes #9210 - Add alias information

Fixes #9210 - Add alias information

---

reference/docs-conceptual/dsc/overview.md

Minor Grammar update.

---

reference/7.0/Microsoft.PowerShell.Utility/Out-GridView.md
reference/7.2/Microsoft.PowerShell.Utility/Out-GridView.md
reference/7.3/Microsoft.PowerShell.Utility/Out-GridView.md

Fix reference to ConsoleGuiTools

---

reference/5.1/Microsoft.PowerShell.Management/Remove-Item.md
reference/7.0/Microsoft.PowerShell.Management/Remove-Item.md
reference/7.2/Microsoft.PowerShell.Management/Remove-Item.md
reference/7.3/Microsoft.PowerShell.Management/Remove-Item.md

Add missing word to an example description because words.

missing word

---

reference/docs-conceptual/dev-cross-plat/create-cmdline-predictor.md

Fixes [AB#6848](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/6848) - Fixes #9224 - Add note about single line suggestions

Fixes #9224 - Add note about single line suggestions

---

reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/community-update.yml
reference/docs-conceptual/learn/more-powershell-learning.md
reference/docs-conceptual/overview.md

**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck

[BULK] DocuTune - Rebranding

---

reference/docs-conceptual/lang-spec/chapter-11.md

The result in comment at line 231 should be 2 instead of 1

Fix typo in chapter-11.md

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Properties.md

Line 18 has the singular "object" when the line should have the plural "objects"

Fixed typo in about_properties.md

---

reference/docs-conceptual/community/contributing/general-markdown.md

**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck

[BULK UPDATE] DocuTune - Rebranding

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.3/Microsoft.PowerShell.Core/Switch-Process.md
reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

This change updates the documentation for the release of PowerShell [v7.3.0-preview.8][01].
- Resolves #9232
- Resolves #9233

Update docs for release of 7.3-preview.8

---

reference/docs-conceptual/learn/shell/using-predictors.md

Maybe just a small typo fix in a sentence inside a info box.

Fix typo in "Using Predictors"

---

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.0/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.3/Microsoft.PowerShell.Management/Get-ChildItem.md

Fixes [AB#8169](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/8169) - Fixes #9254 - Update description of Name parameter

Fixes #9254 - Update description of Name parameter

---

reference/docs-conceptual/developer/hosting/creating-an-initialsessionstate.md

Modify the C# example code in "Creating an InitialSessionState".  The comments were changed with the intent to use less words. The SessionStateVariableEntry variable initialization was modified because the previous version broke syntax highlighting in GitHub and Visual Studio Code.

Modify example in "Creating an InitialSessionState"

---

reference/docs-conceptual/community/contributing/hackathons.md
reference/docs-conceptual/toc.yml

Add Hacktoberfest article

---

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
reference/7.2/Microsoft.PowerShell.Management/Start-Process.md
reference/7.3/Microsoft.PowerShell.Management/Start-Process.md

Fixes [AB#9111](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/9111) - Fixes #9268 - Backtick verbs to prevent overlocalization

Fixes #9268 - Backtick verbs to prevent overlocalization

---

.openpublishing.publish.config.json
.openpublishing.redirection.51.json
.openpublishing.redirection.70.json
.openpublishing.redirection.71.json
.openpublishing.redirection.72.json
.openpublishing.redirection.json
.openpublishing.redirection.virtual.json

Fixes [AB#6850](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/6850) - Split redirection into multiple files

Split redirection into multiple files

---

reference/docs-conceptual/whats-new/cmdlet-versions.md

Fixes [AB#13010](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/13010) - Fixes #9273 - Wait-Process works on non-Windows now

Fixes #9273 - Wait-Process works on non-Windows now

---

reference/5.1/Microsoft.PowerShell.Core/Out-Null.md
reference/7.0/Microsoft.PowerShell.Core/Out-Null.md
reference/7.2/Microsoft.PowerShell.Core/Out-Null.md
reference/7.3/Microsoft.PowerShell.Core/Out-Null.md

Light modification to the Out-Null.md description.

Modify "Out-Null" Description

---

.github/workflows/hacktoberfest.pr.yml

This change introduces a new workflow for Hacktoberfest pull requests. It is composed of a few jobs:
- `check` runs whenever a PR is opened, reopened, edited, or labeled. It runs multiple validation logics against the PR to see if it should be associated with Hacktoberfest, reporting each as a boolean value.
In this iteration, it checks first to see if the title of the PR includes a jack-o-lantern (🎃) emoji. If it does, the PR is considered to be part of Hacktoberfest.
Secondly, it checks to see if either the hacktoberfest-candidate label was just applied to the PR or was already applied. If either is true, the PR is considered to be part of Hacktoberfest.
- `label` adds the hacktoberfest-candidate label if the PR is for Hacktoberfest and doesn't already have the label.
- `project` adds …

(AB#8057) Add workflow for Hacktoberfest PRs

---

.github/workflows/hacktoberfest.issue.yml

This change introduces a new workflow for Hacktoberfest issues. It is composed of several jobs:
- `hacktober` verifies that a filed issue is part of the project by looking for body text that matches the issue template's prerequisite section. If this job does not match, none of the other jobs will fire.
- `project` adds the issue to the Hacktoberfest project.
- `assign` assigns the issue author to their own issue.
- `associate` prefixes the issue body with text that associates the issue automatically with the meta-issue. Unfortunately, despite the inclusion of the meta-issue in the template, that text isn't written to the filed issue on creation. This ensures that every Hacktoberfest issue is correctly linked to the meta issue.
- `label` inspects the issue body to determine which quality …

(AB#8056) Add action for Hacktoberfest issues

---

reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md
reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md
reference/docs-conceptual/developer/toc.yml

Fixes [AB#13011](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/13011) - Fixes #9250 - Add article showing how to invoke a PSCmdlet

Fixes #9250 - Add article showing how to invoke a PSCmdlet

---

reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#13429](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/13429) - Add note about the DSC experimental feature

Add note about the DSC experimental feature

---

reference/docs-conceptual/learn/Glossary.md

Fixes [AB#13430](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/13430) - Fixes #9280 - Convert glossary to new template

Fixes #9280 - Convert glossary to new template

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Windows.md

Fixes [AB#13440](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/13440) - Fixes #9247 - Reorder instructions for clarity

Fixes #9247 - Reorder instructions for clarity

---

reference/5.1/PowershellGet/PowerShellGet.md
reference/7.0/PowerShellGet/PowerShellGet.md
reference/7.2/PowerShellGet/PowerShellGet.md
reference/7.3/PowerShellGet/PowerShellGet.md
reference/docs-conceptual/gallery/installing-psget.md

Fixes [AB#13574](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/13574) - Fixes #9288 - Update notice about supported versions

Fixes #9288 - Update notice about supported versions

---

reference/includes/alpine-support.md

Fixes [AB#4073](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4073) - Update support info for Alpine 3.13

Update support info for Alpine 3.13

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Type_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Type_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Type_Operators.md

Fixes [AB#13884](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/13884) - Fixes #9295 - Add no-loc for -as

Fixes #9295 - Add no-loc for -as

---

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
reference/7.0/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.2/Microsoft.PowerShell.Management/Start-Process.md
reference/7.3/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.3/Microsoft.PowerShell.Management/Start-Process.md

Fixes [AB#15310](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/15310) - Fixes #9297 - Remove alias metadata

Fixes #9297 - Remove alias metadata

---

.github/workflows/hacktoberfest.issue.yml
.github/workflows/hacktoberfest.pr.yml

Prior to this change, the logic for the hacktoberfest GitHub Actions was broken, firing on every PR and issue even when they didn't match. This was due to the outputs of the check jobs being strings, not booleans, and the `if` statements in the dependent jobs not explicitly checking for true/false against the string value.
This change ensures the automation runs only when expected.

(MAINT) Fix hacktoberfest automation

---

reference/docs-conceptual/learn/Glossary.md

Fix case of terms

---

reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md

Minor grammar edit.
This minor change fixes an incorrect sentence.

Grammar change to a sentence in everything-about-pscustomobject.md

---

reference/5.1/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.0/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.2/Microsoft.PowerShell.Management/New-PSDrive.md
reference/7.3/Microsoft.PowerShell.Management/New-PSDrive.md

Fixes [AB#20533](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/20533) - Fixes #9313 - Fix typo

Fixes #9313 - Fix typo

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md

Fixes [AB#20534](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/20534) - Fixes #9315 - Add examples to range operator

Fixes #9315 - Add examples to range operator

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md

Fixes [AB#20534](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/20534) - Fixes #9315 - Fix typo

Fixes #9315 - Fix typo

---

reference/module/index.md

Update quicklink for AzPS 9.0.1

Update quicklink for AzPS 9.0.1

---

reference/5.1/Microsoft.PowerShell.Core/Get-Command.md
reference/7.0/Microsoft.PowerShell.Core/Get-Command.md
reference/7.2/Microsoft.PowerShell.Core/Get-Command.md
reference/7.3/Microsoft.PowerShell.Core/Get-Command.md

Fixes [AB#22911](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/22911) - Fixes #9330 - Fix formatting of CommandType parameter options

Fixes #9330 - Fix formatting of CommandType parameter options

---

reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md
reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md

This change updates some wording to be clearer and fixes some performance issues in the examples.
- Fixes #9335
I'll add some explanations as review comments below

Update documentation for invoking commands from a managed binary (like C#)

---

reference/5.1/Microsoft.PowerShell.Utility/Export-Alias.md
reference/5.1/Microsoft.PowerShell.Utility/Get-Alias.md
reference/5.1/Microsoft.PowerShell.Utility/Import-Alias.md
reference/5.1/Microsoft.PowerShell.Utility/New-Alias.md
reference/5.1/Microsoft.PowerShell.Utility/Set-Alias.md
reference/7.0/Microsoft.PowerShell.Utility/Export-Alias.md
reference/7.0/Microsoft.PowerShell.Utility/Get-Alias.md
reference/7.0/Microsoft.PowerShell.Utility/Import-Alias.md
reference/7.0/Microsoft.PowerShell.Utility/New-Alias.md
reference/7.0/Microsoft.PowerShell.Utility/Set-Alias.md
reference/7.2/Microsoft.PowerShell.Utility/Export-Alias.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Alias.md
reference/7.2/Microsoft.PowerShell.Utility/Import-Alias.md
reference/7.2/Microsoft.PowerShell.Utility/New-Alias.md
reference/7.2/Microsoft.PowerShell.Utility/Set-Alias.md
reference/7.3/Microsoft.PowerShell.Utility/Export-Alias.md
reference/7.3/Microsoft.PowerShell.Utility/Get-Alias.md
reference/7.3/Microsoft.PowerShell.Utility/Import-Alias.md
reference/7.3/Microsoft.PowerShell.Utility/New-Alias.md
reference/7.3/Microsoft.PowerShell.Utility/Set-Alias.md

Edit: Initial PR was only for New-Alias but decided to implement for *-Alias
Adding alias documentation for the *-Alias Cmdlet
My collective issue (hopefully this is ok) #9345 

🎃 Add aliases to Notes section for *-Alias cmdlets

---

reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
reference/5.1/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.3/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.3/Microsoft.PowerShell.Utility/Import-Csv.md

Add alias notes section for Import and Export-Csv
- Resolves #9347

🎃 Add alias notes section for Import and Export-Csv

---

reference/docs-conceptual/windows-powershell/install/Installing-Windows-PowerShell.md
reference/docs-conceptual/windows-powershell/install/Installing-the-Windows-PowerShell-2.0-Engine.md
reference/docs-conceptual/windows-powershell/install/Windows-PowerShell-System-Requirements.md
reference/docs-conceptual/windows-powershell/ise/Keyboard-Shortcuts-for-the-Windows-PowerShell-ISE.md
reference/docs-conceptual/windows-powershell/whats-new/What-s-New-in-Windows-PowerShell-50.md
reference/docs-conceptual/windows-powershell/wmf/overview.md

Fixes [AB#26523](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/26523) - Remove links to unsupported versions of WMF

Remove links to unsupported versions of WMF

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-raspbian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/install/microsoft-update-faq.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#26559](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/26559) - Update version number to latest release

Update version number to latest release

---

reference/docfx.json

Related to [AB#26794](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/26794) - Update metadata in docfx

Update metadata in docfx

---

reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.3/Microsoft.PowerShell.Utility/ConvertTo-Csv.md

CSV stands for comma-separated values, not character-separated value. This PR makes this change.

Change character-separated value to comma separated value

---

reference/docs-conceptual/developer/help/how-to-create-and-upload-cab-files.md

Fixes [AB#26821](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/26821) - Fixes #9368 - Remove signing recommendation

Fixes #9368 - Remove signing recommendation

---

reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md
reference/5.1/Microsoft.PowerShell.Utility/Import-Csv.md
reference/5.1/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
reference/7.0/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.0/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.2/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
reference/7.3/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
reference/7.3/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.3/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.3/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md

Fixes [AB#26823](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/26823) - Continuation of PR #9367 - Standardize on "character-separated"

Fixes #9367 - Standardize on "character-separated"

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md

Fix, what I believe is a typo...
Sorry, if I am wrong. Feel free to close it then. 

docs(typo): fix typo in about_Functions_OutputTypeAttribute

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

Fixes [AB#27897](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/27897) - Fixes #9365 - Fix description of HelpMessage behavior

Fixes #9365 - Fix description of HelpMessage behavior

---

reference/5.1/Microsoft.PowerShell.Core/New-PSSession.md
reference/7.0/Microsoft.PowerShell.Core/New-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/New-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/New-PSSession.md
reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#27950](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/27950) - Fixes #9375 - Update release notes for 7.3-rc.1

Fixes #9375 - Update release notes for 7.3-rc.1

---

reference/docs-conceptual/whats-new/differences-from-windows-powershell.md

Fixes [AB#28006](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/28006) - Add list of aliases not available on unix

Add list of aliases not available on unix

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md

Fixes [AB#30193](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/30193) - Fixes #9383 - Add information about PATH envvar
This PR also includes editorial cleanup for contractions, links, and reflow.

Fixes #9383 - Add information about PATH envvar

---

reference/module/index.md

Update quicklink for AzPS 9.1.0

Update quicklink for AzPS 9.1.0

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.0/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.3/Microsoft.PowerShell.Utility/Write-Progress.md

Fixes [AB#30855](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/30855) - Fixes #9399 - Fix example 3 and other minor edits

Fixes #9399 - Fix example 3 and other minor edits

---

reference/5.1/Microsoft.PowerShell.Management/Get-Location.md
reference/5.1/Microsoft.PowerShell.Management/Pop-Location.md
reference/5.1/Microsoft.PowerShell.Management/Push-Location.md
reference/5.1/Microsoft.PowerShell.Management/Set-Location.md
reference/7.0/Microsoft.PowerShell.Management/Get-Location.md
reference/7.0/Microsoft.PowerShell.Management/Pop-Location.md
reference/7.0/Microsoft.PowerShell.Management/Push-Location.md
reference/7.0/Microsoft.PowerShell.Management/Set-Location.md
reference/7.2/Microsoft.PowerShell.Management/Get-Location.md
reference/7.2/Microsoft.PowerShell.Management/Pop-Location.md
reference/7.2/Microsoft.PowerShell.Management/Push-Location.md
reference/7.2/Microsoft.PowerShell.Management/Set-Location.md
reference/7.3/Microsoft.PowerShell.Management/Get-Location.md
reference/7.3/Microsoft.PowerShell.Management/Pop-Location.md
reference/7.3/Microsoft.PowerShell.Management/Push-Location.md
reference/7.3/Microsoft.PowerShell.Management/Set-Location.md

Adds alias notes section for the -Location cmdlets:
- reference/./Microsoft.PowerShell.Management/Get-Location.md
- reference/./Microsoft.PowerShell.Management/Set-Location.md
- reference/./Microsoft.PowerShell.Management/Pop-Location.md
- reference/./Microsoft.PowerShell.Management/Push-Location.md
Resolves #9404

Quality: Added alias notes for -Location cmdlets

---

reference/5.1/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md
reference/5.1/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md
reference/5.1/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md
reference/5.1/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.md
reference/5.1/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md
reference/7.0/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md
reference/7.0/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md
reference/7.0/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md
reference/7.0/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.md
reference/7.0/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md
reference/7.2/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md
reference/7.2/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md
reference/7.2/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md
reference/7.2/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.md
reference/7.2/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md
reference/7.3/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md
reference/7.3/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md
reference/7.3/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md
reference/7.3/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.md
reference/7.3/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md

Adds alias notes section for the -PSBreakpoint cmdlets
- reference/*.*/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md
- reference/*.*/Microsoft.PowerShell.Utility/Set-PSBreakpoint.md
- reference/*.*/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.md
- reference/*.*/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md
- reference/*.*/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md
Resolves #9412

Quality: Added alias notes for -PSBreakpoint cmdlets

---

reference/docs-conceptual/dev-cross-plat/vscode/How-To-Replicate-the-ISE-Experience-In-VSCode.md
reference/docs-conceptual/dev-cross-plat/vscode/Using-VSCode-for-Remote-Editing-and-Debugging.md
reference/docs-conceptual/dev-cross-plat/vscode/understanding-file-encoding.md
reference/docs-conceptual/dev-cross-plat/vscode/using-vscode-for-debugging-compiled-cmdlets.md
reference/docs-conceptual/dev-cross-plat/vscode/using-vscode.md

Update link reference to the numerical style.
Reflow line length when necessary.
- Resolves #9397

Update link reference style in reference/docs-conceptual/dev-cross-plat/vscode markdown files

---

README.md
reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
reference/docs-conceptual/install/PowerShell-on-ARM.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-other-linux.md
reference/docs-conceptual/install/install-raspbian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/install/microsoft-update-faq.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

This change updates the documentation to address the latest stable version of PowerShell being `7.3.0`.
- Fixes [AB#33081](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/33081)

(AB#33081) Update for 7.3.0 release

---

README.md
reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
reference/docs-conceptual/install/PowerShell-on-ARM.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-other-linux.md
reference/docs-conceptual/install/install-raspbian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/install/microsoft-update-faq.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

This change updates the documentation to address the latest stable version of PowerShell being `7.3.0`.
- Fixes [AB#33081](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/33081)

(AB#33081) Update for 7.3.0 release (#9416)

---

reference/docs-conceptual/toc.yml

Fixes the TOC title for What's New in 7.3

(MAINT) Remove preview from whats new for 7.3

---

reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/5.1/Microsoft.PowerShell.Archive/Expand-Archive.md
reference/7.0/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.0/Microsoft.PowerShell.Archive/Expand-Archive.md
reference/7.2/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.2/Microsoft.PowerShell.Archive/Expand-Archive.md
reference/7.3/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.3/Microsoft.PowerShell.Archive/Expand-Archive.md
reference/docs-conceptual/toc.yml

(MAINT) Push to live

---

reference/5.1/PSReadLine/About/about_PSReadLine.md
reference/7.0/PSReadLine/About/about_PSReadLine.md
reference/7.2/PSReadLine/About/about_PSReadLine.md
reference/7.3/PSReadLine/About/about_PSReadLine.md

Small grammar fix for about_PSReadLine

---

reference/5.1/Microsoft.PowerShell.Utility/Format-Custom.md
reference/5.1/Microsoft.PowerShell.Utility/Format-Hex.md
reference/5.1/Microsoft.PowerShell.Utility/Format-List.md
reference/5.1/Microsoft.PowerShell.Utility/Format-Table.md
reference/5.1/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.0/Microsoft.PowerShell.Utility/Format-Custom.md
reference/7.0/Microsoft.PowerShell.Utility/Format-Hex.md
reference/7.0/Microsoft.PowerShell.Utility/Format-List.md
reference/7.0/Microsoft.PowerShell.Utility/Format-Table.md
reference/7.0/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.2/Microsoft.PowerShell.Utility/Format-Custom.md
reference/7.2/Microsoft.PowerShell.Utility/Format-Hex.md
reference/7.2/Microsoft.PowerShell.Utility/Format-List.md
reference/7.2/Microsoft.PowerShell.Utility/Format-Table.md
reference/7.2/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.3/Microsoft.PowerShell.Utility/Format-Custom.md
reference/7.3/Microsoft.PowerShell.Utility/Format-Hex.md
reference/7.3/Microsoft.PowerShell.Utility/Format-List.md
reference/7.3/Microsoft.PowerShell.Utility/Format-Table.md
reference/7.3/Microsoft.PowerShell.Utility/Format-Wide.md

- reference/*.*/Microsoft.PowerShell.Utility/Format-Custom.md
- reference/*.*/Microsoft.PowerShell.Utility/Format-Hex.md
- reference/*.*/Microsoft.PowerShell.Utility/Format-List.md
- reference/*.*/Microsoft.PowerShell.Utility/Format-Table.md
- reference/*.*/Microsoft.PowerShell.Utility/Format-Wide.md
Resolves: #9426

Quality: Added alias notes section for Format cmdlets

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

- **Add missing links:** This document contains hashrefs that, prior to this PR, did not link anywhere. In that state, they were mere noise for most of the audience. Even the GitHub-aware audience need to manually resolve them. This PR links to those hashrefs to their corresponding entries.
- Admittedly, the original document contains style guide noncompliance. This PR leaves them intact.

What-s-New-in-PowerShell-73.md: Add missing links

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
reference/docs-conceptual/whats-new/differences-from-windows-powershell.md
reference/includes/alpine-support.md
reference/includes/debian-support.md
reference/includes/macos-support.md
reference/includes/rhel-support.md
reference/includes/ubuntu-support.md
reference/includes/windows-support.md

Fixes [AB#37137](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/37137) - Update 7.3-preview references for GA

Update 7.3-preview references for GA

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/docs-conceptual/community/contributing/editorial-checklist.md
reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#38259](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/38259) - Fixes #9446 - Update experimental features for 7.3 release

Fixes #9446 - Update experimental features for 7.3 release

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Telemetry.md

Fixes [AB#39008](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/39008) - Fixes #9454 - Update telemetry documentation

Fixes #9454 - Update telemetry documentation

---

reference/5.1/Microsoft.PowerShell.Management/Clear-ItemProperty.md
reference/5.1/Microsoft.PowerShell.Management/Copy-ItemProperty.md
reference/5.1/Microsoft.PowerShell.Management/Get-ItemProperty.md
reference/5.1/Microsoft.PowerShell.Management/Move-ItemProperty.md
reference/5.1/Microsoft.PowerShell.Management/Remove-ItemProperty.md
reference/5.1/Microsoft.PowerShell.Management/Rename-ItemProperty.md
reference/5.1/Microsoft.PowerShell.Management/Set-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Management/Clear-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Management/Copy-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Management/Get-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Management/Move-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Management/Remove-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Management/Rename-ItemProperty.md
reference/7.0/Microsoft.PowerShell.Management/Set-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Management/Clear-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Management/Copy-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Management/Get-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Management/Move-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Management/Remove-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Management/Rename-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Management/Set-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Management/Clear-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Management/Copy-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Management/Get-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Management/Move-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Management/Remove-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Management/Rename-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Management/Set-ItemProperty.md

- reference/*.*/Microsoft.PowerShell.Management/Clear-ItemProperty.md
- reference/*.*/Microsoft.PowerShell.Management/Copy-ItemProperty.md
- reference/*.*/Microsoft.PowerShell.Management/Get-ItemProperty.md
- reference/*.*/Microsoft.PowerShell.Management/Move-ItemProperty.md
- reference/*.*/Microsoft.PowerShell.Management/Remove-ItemProperty.md
- reference/*.*/Microsoft.PowerShell.Management/Set-ItemProperty.md
Resolves: #9458

Quality: Added alias notes section for ItemProperty cmdlets

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md
reference/docs-conceptual/windows-powershell/whats-new/What-s-New-in-Windows-PowerShell-50.md

Changes to support Get-WhatsNew

Changes to support Get-WhatsNew

---

reference/5.1/Microsoft.PowerShell.Utility/Out-Printer.md
reference/7.0/Microsoft.PowerShell.Utility/Out-Printer.md
reference/7.2/Microsoft.PowerShell.Utility/Out-Printer.md
reference/7.3/Microsoft.PowerShell.Utility/Out-Printer.md

Fixes [AB#43569](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/43569) - Fixes #9482 - Add note about print job configuration

Fixes #9482 - Add note about print job configuration

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#43578](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/43578) - Fixes #9485 - Reorder release notes content for 7.3

Fixes #9485 - Reorder release notes content for 7.3

---

reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.0/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.3/Microsoft.PowerShell.Utility/Get-Date.md

Fixes [AB#43582](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/43582) - Fixes #9483 - Update description of `-UFormat %s`

Fixes #9483 - Update description of `-UFormat %s`

---

reference/docs-conceptual/developer/help/updatable-help-authoring-step-by-step.md

Fixes [AB#44665](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/44665) - Fixes #9376 - Update steps for publishing Updateable Help

Fixes #9376 - Update steps for publishing Updateable Help

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Minor edit and reflow

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#44824](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/44824) - Fixes #9497 - Fix default value of $PSStyle.OutputRendering

Fixes #9497 - Fix default value of $PSStyle.OutputRendering

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Telemetry.md

Fixes [AB#44838](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/44838) - Fixes #9499 - Update telemetry guidance to avoid PII
Added warning to not change the value and reordered the Environment variables to move the telemetry variables to the top of the list.

Fixes #9499 - Update telemetry guidance to avoid PII

---

reference/5.1/Microsoft.PowerShell.Management/Test-ComputerSecureChannel.md

Removed erroneous statement regarding example 5 (there is no use of Set-Alias in the example code).

Removed erroneous statement regarding example 5

---

reference/docs-conceptual/learn/shell/optimize-shell.md
reference/docs-conceptual/learn/shell/using-predictors.md

Fixes [AB#45429](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/45429) - Fixes #9507 - Fix broken kbd tags

Fixes #9507 - Fix broken kbd tags

---

reference/docs-conceptual/community/2022-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Fixes [AB#45430](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/45430) - Fixes #9509 - Update stats for Nov 2022

Fixes #9509 - Update stats for Nov 2022

---

reference/docs-conceptual/learn/shell/creating-profiles.md

Fixes [AB#45540](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/45540) - Fixes #9512 - Update script to work on versions without $PSStyle

Fixes #9512 - Update script to work on versions without $PSStyle

---

reference/5.1/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/5.1/Microsoft.PowerShell.Core/Disconnect-PSSession.md
reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/5.1/Microsoft.PowerShell.Core/Exit-PSSession.md
reference/5.1/Microsoft.PowerShell.Core/Get-PSSession.md
reference/5.1/Microsoft.PowerShell.Core/New-PSSession.md
reference/5.1/Microsoft.PowerShell.Core/Receive-PSSession.md
reference/5.1/Microsoft.PowerShell.Core/Remove-PSSession.md
reference/5.1/Microsoft.PowerShell.Utility/Export-PSSession.md
reference/5.1/Microsoft.PowerShell.Utility/Import-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Disconnect-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Exit-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Get-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/New-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Receive-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Remove-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Disconnect-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Exit-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Get-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/New-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Receive-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Remove-PSSession.md

- reference/5.1/Microsoft.PowerShell.Core/Export-PSSession.md
- reference/5.1/Microsoft.PowerShell.Core/Import-PSSession.md
- reference/*.*/Microsoft.PowerShell.Core/Connect-PSSession.md
- reference/*.*/Microsoft.PowerShell.Core/Disconnect-PSSession.md
- reference/*.*/Microsoft.PowerShell.Core/Enter-PSSession.md
- reference/*.*/Microsoft.PowerShell.Core/Exit-PSSession.md
- reference/*.*/Microsoft.PowerShell.Core/Get-PSSession.md
- reference/*.*/Microsoft.PowerShell.Core/New-PSSession.md
- reference/*.*/Microsoft.PowerShell.Core/Receive-PSSession.md
- reference/*.*/Microsoft.PowerShell.Core/Remove-PSSession.md
Fixes #9515
[style]: https://learn.microsoft.com/powershell/scripting/community/contributin …

Add alias notes for -PSSession cmdlets

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.3/Microsoft.PowerShell.Utility/Write-Progress.md

Fixes [AB#47648](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/47648) - Fixes #9523 - Fix min value of MaxWidth

Fixes #9523 - Fix min value of MaxWidth

---

reference/5.1/Microsoft.PowerShell.Core/Get-Verb.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Verb.md
reference/7.3/Microsoft.PowerShell.Utility/Get-Verb.md

Fixes [AB#47645](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/47645) - Fixes #9522 - Fix parameter descriptions for Get-Verb

Fixes #9522 - Fix parameter descriptions for Get-Verb

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md

Fixes [AB#46124](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/46124) - Fixes #9489 - Explain passthru for `()` expressions

Fixes #9489 - Explain passthru for `()` expressions

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md
reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Object_Creation.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Object_Creation.md
reference/7.3/Microsoft.PowerShell.Core/About/about_PSCustomObject.md

Fixes [AB#47661](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/47661) - Fixes #9519 - Update behavior of [pscustomobject]

Fixes #9519 - Update behavior of [pscustomobject]

---

reference/module/index.md

Fixes [AB#48574](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/48574) - Fixes #9532 - Update AzPS quicklink to 9.2.0

Fixes #9532 - Update AzPS quicklink to 9.2.0

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.3/Microsoft.PowerShell.Core/About/about_PSItem.md

Fixes [AB#50818](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/50818) - Fixes #9540 - Fix example and broken link

Fixes #9540 - Fix example and broken link

---

reference/5.1/Microsoft.PowerShell.Utility/Format-Table.md
reference/7.2/Microsoft.PowerShell.Utility/Format-Table.md
reference/7.3/Microsoft.PowerShell.Utility/Format-Table.md

Fixes [AB#52132](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/52132) - Fixes #9546 - Add note about $PSStyle changing table output

Fixes #9546 - Add note about $PSStyle changing table output

---

reference/5.1/PowershellGet/Register-PSRepository.md
reference/7.2/PowerShellGet/Register-PSRepository.md
reference/7.3/PowerShellGet/Register-PSRepository.md

Fixes [AB#52200](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/52200) - Fixes #9548 - Update descriptions for location parameters

Fixes #9548 - Update descriptions for location parameters

---

reference/docfx.json

Replace ms.topic: guide (now deprecated) with ms.topic: conceptual
Note the following:
- DocuTune drives improved quality of technical content by finding and automatically correcting a broad set of issues in Markdown and YAML files. DocuTune performs these updates intelligently, only making corrections in the sections of a document where the correction is suitable.
- DocuTune PRs often standardize spacing, formatting, and casing of Markdown elements to support the DocuTune onboarding process.
- DocuTune PRs might contain other minor edits noticed during a manual review.
- DocuTune PRs might include files whose Acrolinx score was below the target threshold prior to this PR.
- Delimiters such as asterisks and backticks may be added to link descriptions or alt-text to denote UI elements or …

Replace ms.topic: guide (now deprecated) with ms.topic: conceptual

---

reference/docs-conceptual/learn/ps101/00-introduction.md
reference/docs-conceptual/learn/ps101/02-help-system.md
reference/docs-conceptual/learn/ps101/03-discovering-objects.md
reference/docs-conceptual/learn/ps101/04-pipelines.md
reference/docs-conceptual/learn/ps101/06-flow-control.md
reference/docs-conceptual/learn/ps101/07-working-with-wmi.md
reference/docs-conceptual/learn/ps101/08-powershell-remoting.md
reference/docs-conceptual/learn/ps101/10-script-modules.md

Refresh of PowerShell 101 content

Refresh of powershell 101 content

---

reference/docs-conceptual/lang-spec/chapter-09.md

Fixes [AB#53129](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/53129) -Fixes #9557

Fix comments in example 9.11

---

reference/5.1/PowershellGet/Find-Module.md
reference/5.1/PowershellGet/Install-Module.md
reference/5.1/PowershellGet/Publish-Module.md
reference/5.1/PowershellGet/Save-Module.md
reference/5.1/PowershellGet/Uninstall-Module.md
reference/5.1/PowershellGet/Update-Module.md
reference/7.2/PowerShellGet/Find-Module.md
reference/7.2/PowerShellGet/Install-Module.md
reference/7.2/PowerShellGet/Publish-Module.md
reference/7.2/PowerShellGet/Save-Module.md
reference/7.2/PowerShellGet/Uninstall-Module.md
reference/7.2/PowerShellGet/Update-Module.md
reference/7.3/PowerShellGet/Find-Module.md
reference/7.3/PowerShellGet/Install-Module.md
reference/7.3/PowerShellGet/Publish-Module.md
reference/7.3/PowerShellGet/Save-Module.md
reference/7.3/PowerShellGet/Uninstall-Module.md
reference/7.3/PowerShellGet/Update-Module.md

Fixes [AB#53168](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/53168) - Fixes #9564 - Document module version format

Fixes #9564 - Document module version format

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Splatting.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Splatting.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Splatting.md

Fixes [AB#54560](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/54560) - Fixes #9569 - Simplify Example 2 when using PSBoundParameters

Fixes #9569 - Simplify Example 2 when using PSBoundParameters

---

reference/5.1/Microsoft.PowerShell.Utility/Format-List.md
reference/5.1/Microsoft.PowerShell.Utility/Format-Table.md
reference/7.2/Microsoft.PowerShell.Utility/Format-List.md
reference/7.2/Microsoft.PowerShell.Utility/Format-Table.md
reference/7.3/Microsoft.PowerShell.Utility/Format-List.md
reference/7.3/Microsoft.PowerShell.Utility/Format-Table.md

Fixes [AB#54568](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/54568) - Fixes #9542 - Add notes about the use of Force

Fixes #9542 - Add notes about the use of Force

---

reference/5.1/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.3/Microsoft.PowerShell.Utility/Get-Member.md

- reference/./Microsoft.PowerShell.Utility/Get-Member.md
Fixes #9574 

Quality: Added alias notes for Get-Member

---

reference/5.1/Microsoft.PowerShell.Core/Get-Job.md
reference/5.1/Microsoft.PowerShell.Core/Receive-Job.md
reference/5.1/Microsoft.PowerShell.Core/Remove-Job.md
reference/5.1/Microsoft.PowerShell.Core/Start-Job.md
reference/5.1/Microsoft.PowerShell.Core/Stop-Job.md
reference/5.1/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.2/Microsoft.PowerShell.Core/Get-Job.md
reference/7.2/Microsoft.PowerShell.Core/Receive-Job.md
reference/7.2/Microsoft.PowerShell.Core/Remove-Job.md
reference/7.2/Microsoft.PowerShell.Core/Start-Job.md
reference/7.2/Microsoft.PowerShell.Core/Stop-Job.md
reference/7.2/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.3/Microsoft.PowerShell.Core/Get-Job.md
reference/7.3/Microsoft.PowerShell.Core/Receive-Job.md
reference/7.3/Microsoft.PowerShell.Core/Remove-Job.md
reference/7.3/Microsoft.PowerShell.Core/Start-Job.md
reference/7.3/Microsoft.PowerShell.Core/Stop-Job.md
reference/7.3/Microsoft.PowerShell.Core/Wait-Job.md

- reference/*.*/Microsoft.PowerShell.Core/Get-Job.md
- reference/*.*/Microsoft.PowerShell.Core/Receive-Job.md
- reference/*.*/Microsoft.PowerShell.Core/Remove-Job.md
- reference/*.*/Microsoft.PowerShell.Core/Start-Job.md
- reference/*.*/Microsoft.PowerShell.Core/Stop-Job.md
- reference/*.*/Microsoft.PowerShell.Core/Wait-Job.md
Fixes #9579 

Quality: Added alias notes for -Job cmdlets

---

.github/ISSUE_TEMPLATE/01-article.yml

Fixes [AB#54763](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/54763) - Fixes #9590 - Update issue template for supported versions

Fixes #9590 - Update issue template for supported versions

---

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/5.1/Microsoft.PowerShell.Management/Get-Item.md
reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.2/Microsoft.PowerShell.Management/Get-Item.md
reference/7.3/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.3/Microsoft.PowerShell.Management/Get-Item.md
reference/7.4/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.4/Microsoft.PowerShell.Management/Get-Item.md

Fixes [AB#54767](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/54767) - Fixes #9589 - Add output types for Get-*Item

Fixes #9589 - Add output types for Get-*Item

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#55226](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/55226) - Fixes #9595 - Fix release notes for experimental features

Fixes #9595 - Fix release notes for experimental features

---

reference/7.3/Microsoft.PowerShell.Core/Switch-Process.md
reference/7.4/Microsoft.PowerShell.Core/Switch-Process.md
reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md

Fixes [AB#55284](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/55284) - Fixes #9599 - Update release notes for 7.3.1

Fixes #9599 - Update release notes for 7.3.1

---

reference/docs-conceptual/lang-spec/chapter-06.md

Fix typo: "is represented" were repeated two times at [lang-specs/chapter05](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/docs-conceptual/lang-spec/chapter-06.md#65-conversion-to-float-and-double).

Fix typo: is represented being repeated two times.

---

reference/docs-conceptual/discover-powershell.md

- reference/docs-conceptual/discover-powershell.md
Fixes #9605

Fixes typo in "Discover PowerShell"

---

reference/docs-conceptual/community/contributing/labelling-in-github.md
reference/docs-conceptual/dev-cross-plat/vscode/understanding-file-encoding.md
reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md
reference/docs-conceptual/windows-powershell/whats-new/What-s-New-in-Windows-PowerShell-50.md

Fixes [AB#55603](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/55603) - Fixes #9608 - Fix broken link

Fixes #9608 - Fix broken link

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Wildcards.md

Fixes [AB#55653](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/55653) - Fixes #9611 - Fix overlocalization of examples
Added no-loc metadata, fixed formatting, and editorial cleanup of about_hash_tables.

Fixes #9611 - Fix overlocalization of examples

---

reference/docs-conceptual/learn/shell/using-light-theme.md

Update colors for $PSStyle

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

- reference/*.*/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
- reference/*.*/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fixes #9617 

Quality: Adds alias notes for Invoke-WebRequest and Invoke-RestMethod

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Jobs.md

fix: minor typo

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Output.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Output.md
reference/7.3/Microsoft.PowerShell.Utility/Write-Output.md
reference/7.4/Microsoft.PowerShell.Utility/Write-Output.md

- reference/*.*/Microsoft.PowerShell.Utility/Write-Output.md
Resolves #9625 

Quality: Add alias notes to Write-Output

---

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md

Use the correct title for _.NET and .NET Core Support Policy_.

Update document name

---

reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md
reference/5.1/Microsoft.PowerShell.Core/Out-Host.md
reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.2/Microsoft.PowerShell.Core/Out-Host.md
reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.3/Microsoft.PowerShell.Core/Out-Host.md
reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.4/Microsoft.PowerShell.Core/Out-Host.md

This adds alias information to the Notes section in the documentation for Clear-Host and Out-Host.
- Resolves #9629 

Quality: Add alias to Notes section of Clear-Host and Out-Host Cmdlets

---

reference/5.1/Microsoft.PowerShell.Management/Get-HotFix.md
reference/7.2/Microsoft.PowerShell.Management/Get-HotFix.md
reference/7.3/Microsoft.PowerShell.Management/Get-HotFix.md
reference/7.4/Microsoft.PowerShell.Management/Get-HotFix.md

Fixes [AB#57826](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57826) - Fixes #9622 - Clarify use of Win32_QuickFixEngineering class

Fixes #9622 - Clarify use of Win32_QuickFixEngineering class

---

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#57829](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57829)
- Fixes #8815 - Add new ANSI features
- Fixes #9637 - Add Dim/DimOff to $PSStyle
- Fixes #9638 - $PSNativeCommandUseErrorActionPreference is $true when feature is enabled

Fixes #8815 - Add new ANSI features

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md

Fixes [AB#57873](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57873) - Fixes #9329 - Add docs for cd~

Fixes #9329 - Add docs for cd~
