reference/docs-conceptual/dev-cross-plat/create-cmdline-predictor.md

Fixes AB#1937749 - Fixes #8724 - Add note about experimental feature requirements

Fixes #8724 - Add note about experimental feature requirements

---

reference/5.1/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.0/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.1/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.2/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.3/Microsoft.PowerShell.Core/Wait-Job.md

Simple formatting fix in NOTES-Section
The explanation of the `-Force` parameter in connection to suspended and disconnected jobs should not be part of the list of job-states
[key]: …

Formatting fix in Wait-Job.md

---

reference/docs-conceptual/learn/remoting/powershell-remoting-faq.yml

Fixes AB#1940584 - Fixes #8740 - Update 2022-updates.md

Fixes #8740 - Update 2022-updates.md

---

reference/5.1/PackageManagement/PackageManagement.md
reference/5.1/PowershellGet/PowerShellGet.md
reference/7.0/PackageManagement/PackageManagement.md
reference/7.0/PowerShellGet/PowerShellGet.md
reference/7.1/PackageManagement/PackageManagement.md
reference/7.1/PowerShellGet/PowerShellGet.md
reference/7.2/PackageManagement/PackageManagement.md
reference/7.2/PowerShellGet/PowerShellGet.md
reference/7.3/PackageManagement/PackageManagement.md
reference/7.3/PowerShellGet/PowerShellGet.md
reference/docs-conceptual/gallery/getting-started.md
reference/docs-conceptual/gallery/install-on-older-systems.md
reference/docs-conceptual/gallery/installing-psget.md
reference/docs-conceptual/gallery/overview.md
reference/docs-conceptual/toc.yml

Fixes AB#1941794 - Fixes #8744 - Update PowerShellGet install documents
I split the install documentation into 2 files:
- one for current versions of PowerShell/Windows
- one for older versions
This should help with clutter and confusion.
I also updated the articles to make it clear that you need to update PowerShellGet in Windows PowerShell 5.1 and you need TLS 1.2 or higher.
please add the prefix `WIP:` or `[WIP]` to the beginning of the …

Fixes #8744 - Update PowerShellGet install documents

---

reference/5.1/PSReadLine/PSConsoleHostReadLine.md
reference/7.0/PSReadLine/PSConsoleHostReadLine.md
reference/7.1/PSReadLine/PSConsoleHostReadLine.md
reference/7.2/PSReadLine/PSConsoleHostReadLine.md
reference/7.3/PSReadLine/PSConsoleHostReadLine.md

Prior to this PR, the documentation for `PSConsoleHostReadLine` did not correctly translate due to the casing of the H2s, which are required to be fully upcased.
This PR upcases those items to ensure the documentation can be properly translated.
- Resolves AB#1942543.
[contrib]: …

(AB#1942543) Ensure PSConsoleHostReadLine is translatable

---

reference/docs-conceptual/samples/Managing-Services.md

Prior to this PR, the Managing Services sample in the conceptual
documentation included example code using the **ComputerName** parameter
for `Get-Service`, but that parameter was removed from the `*-Service`
cmdlets in PowerShell 6.0.
This PR updates the documentation to distinguish between Windows
PowerShell and PowerShell for managing remote services and clarifies
how to do so.
- Resolves #8757 
please add the prefix `WIP:` or `[WIP]` …

(GH-8757) Clarify remoting in Managing Services

---

reference/docs-conceptual/install/microsoft-update-faq.yml

This commit clarifies that support for using Microsoft Update for Powershell is limited to x64-based systems.
- Resolves #8770

(GH-8770) Clarify MSU support is for x64 only

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md

These changes fix the spacing problem in "asPowerShell" in about_Parsing. - Fixes #8755 

Fixes #8755 - Update asPowerShell spacing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

This PR rewords the section of _About Quoting Rules_ for clarity by being more explicit about the opening and closing tags and their effect.
- Resolves #8777 

(GH-8777) Reword here-string section for clarity

---

reference/5.1/Microsoft.PowerShell.Core/Where-Object.md
reference/7.0/Microsoft.PowerShell.Core/Where-Object.md
reference/7.1/Microsoft.PowerShell.Core/Where-Object.md
reference/7.2/Microsoft.PowerShell.Core/Where-Object.md
reference/7.3/Microsoft.PowerShell.Core/Where-Object.md

Fix abbreviation.
Fix abbreviation. I guess it should be `MB` not `KB`, as the latter (Kilobyte/Knowledge Base?) makes no sense to me.

Fix an abbreviation in `Where-Object`

---

reference/7.0/Microsoft.PowerShell.Management/Set-Content.md
reference/7.1/Microsoft.PowerShell.Management/Set-Content.md
reference/7.2/Microsoft.PowerShell.Management/Set-Content.md
reference/7.3/Microsoft.PowerShell.Management/Set-Content.md

Fixes AB#1948527 - Fixes #8802 - Fix error in description of -AsByteStream

Fixes #8802 - Fix error in description of -AsByteStream

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md

This changes fixes problem the usage of the describe verb in the documentation for advanced function completes.
- Fixes #8749

Update describe verb.

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Arrays.md

Add clarity to the `"SkipUntil"` `mode`:
-   Mention that the first item for which the condition is met is also
included in the result
-   Emphasize that ALL remaining items are returned regardless of the
expression in the `Where` clause
-   Drop mistyped word *the* (presumably *then*), since it is clear from
the context …

Improve section on `Where` method in `about_Arrays.md`

---

reference/docs-conceptual/whats-new/differences-from-windows-powershell.md

Fixes AB#1949547 - Update differences rollup to include 7.x change
This is the first in a series of changes to prepare for the retirement of 7.1 and 7.0 content.

Update differences rollup to include 7.x change

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/docs-conceptual/lang-spec/chapter-08.md

Fixes AB#1949656 - Fixes #8817 - Add info about end-of-parameters token

Fixes #8817 - Add info about end-of-parameters token

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/5.1/Microsoft.PowerShell.Management/Resolve-Path.md
reference/5.1/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.0/Microsoft.PowerShell.Management/Resolve-Path.md
reference/7.0/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.1/Microsoft.PowerShell.Management/Resolve-Path.md
reference/7.1/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.2/Microsoft.PowerShell.Management/Resolve-Path.md
reference/7.2/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.3/Microsoft.PowerShell.Management/Resolve-Path.md
reference/7.3/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/whats-new/differences-from-windows-powershell.md

5/16 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md

Update description of end-of-parameters token

Update description of end-of-parameters token

---

reference/docs-conceptual/install/install-fedora.md

Remove unsupported compat-openssl install

Remove unsupported compat-openssl install

---

reference/5.1/Microsoft.PowerShell.Utility/New-Variable.md
reference/7.0/Microsoft.PowerShell.Utility/New-Variable.md
reference/7.2/Microsoft.PowerShell.Utility/New-Variable.md
reference/7.3/Microsoft.PowerShell.Utility/New-Variable.md

This change fixes the problem of the missing article "the" in the documentation for `New-Variable`. - Fixes #8754

Add article to private scope in Scope parameter.

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Hash_Tables.md

(GH-8848) Add section on iteration to about_Hash_Tables

---

reference/docs-conceptual/developer/module/how-to-write-a-powershell-script-module.md

Prior to this commit, the `Show-Calendar` example in the "How to write a PowerShell script module" conceptual article defined the **highlightDate** parameter with a default string that failed to cast when used on computers if their Culture does not use ISO or US date formats.
This commit updates the example code to function on a reader's computer regardless of their defined **DateTime** formats.
- Resolves #8853
please add the prefix …

(GH-8853) Internationalize Show-Calendar example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Requires.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Requires.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Requires.md

This commit adds a short note to the long description of the _about_Requires_ topic, clarifying that not only does a script with an unmet `#requires` statement not run, but also that no other runtime features, including tab-completion, are available either.
- Resolves #8854
[contrib]: …

(GH-8854) Clarify behavior when #requires not met

---

.github/workflows/targeting-valid-branch.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

.github/ISSUE_TEMPLATE/New_Issue.yml
.github/PULL_REQUEST_TEMPLATE.md

Removes 7.1 as an option from the PR and issue template for cmdlet reference as those documents are no longer included in this repository. Also places the version entries in strings to ensure valid yaml (instead of relying on interpretation).
[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overv …

(MAINT) Remove 7.1 from PR template

---

.github/actions/.pwsh/scripts/Get-VersionedContentReport.ps1

Prior to this change, the preamble section of the Versioned Content Report summary did not render the git statuses for "changed" or "modified" files correctly.
This change corrects the string syntax to ensure proper rendering.

(MAINT) Fix preamble markup in VC Reporting

---

reference/docs-conceptual/developer/cmdlet/activity-parameters.md

'Create' is listed twice as [activity parameter](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/activity-parameters?view=powershell-7.2). Based on the Functionality description it should be 'Delete'.
Changes:
- Renamed 'Create' to 'Delete'
- Added 'Delete' to 'no-loc'

Activity Parameter: Renamed second 'Create' parameter back to 'Delete'

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.0/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.3/Microsoft.PowerShell.Utility/Write-Progress.md

Fixes AB#1967037 - Fixes #8964
Prior to this change, the examples in the reference documentation of the `Write-Progress` cmdlet included output showing the appearance of progress bars in the classic view. Starting in PowerShell 7.2, which introduced the minimal view, minimal is the default.
This change:
- Updates the examples with output to set the `$PSStyle.Progress.View` value to `classic` before calling `Write-Progress`
- Updates the examples to use our standard styling and limit line length to 100 characters.
- Resolves #8964

(GH-8964) Clarify `Write-Progress` examples

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Special_Characters.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Special_Characters.md

Prior to this change, the documentation for special characters did not include information around when the escape or unicode characters were introduced.
This change:
- Updates the overview table for _About Special Characters_ to note that the escape and unicode characters were added in PowerShell 6
- Updates the sections for each of those characters to include an alert noting that they were introduced in PowerShell 6.
- Resolves #8984

(GH-8984) Add intro version for escape/unicode chars

---

reference/5.1/CimCmdlets/Register-CimIndicationEvent.md
reference/7.0/CimCmdlets/Register-CimIndicationEvent.md
reference/7.2/CimCmdlets/Register-CimIndicationEvent.md
reference/7.3/CimCmdlets/Register-CimIndicationEvent.md

Prior to this change, the **Forward** parameter in the documentation for the `Register-CimIndicationEvent` cmdlet over-localized in de-de to the incorrect _Weiterleiten_.
This change adds `-Forward` to the list of terms not to localize.
- Fixes #8994

(GH-8994) Fix over-localization in `Register-CimIndicationEvent`

---

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md

As a user, I am just interested in seeing future EOL dates and very rarely dates of things that are already not supported any more. Therefore splitting the tables. Ideally I'd also want to move this table to the top of the page because to me that is the most important thing I usually have to look up and imagine want others to know as well first before going into all the OS specific details, etc.

PowerShell-Support-Lifecycle: Separate table for future and past EOL

---

.github/workflows/expectations.yml
.github/workflows/stale-content.yml

This change limits the workflow that trigger on a schedule to only run when the repository owner is `MicrosoftDocs`, which should prevent it from running on forks and generating any errors or other noise.

(MAINT) Limit cron workflows to upstream

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Properties.md

Fixed typo / grammar error in about_Properties.md page for Powershell-Core versions 7.2 and 7.3. The sentence needed the word 'has'. 

Fix typo / grammar error in about_Properties.md

---

reference/7.3/PSReadLine/About/about_PSReadLine_Functions.md

The change in PowerShell/PSReadLine#3365 added three new functions for modifying the casing of text with PSReadLine. This change:
- Adds an entry for each new function in the "Basic editing functions" section of `about_PSReadLine_Functions.md`
- Resolves #9033
- Resolves [AB#4387](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4387)

(GH-9033) Add casing functions for PSReadLine 2.3.0

---

reference/7.3/PSReadLine/About/about_PSReadLine_Functions.md

Fixes #9035 - Add Alt keybinings for new case commands

Fixes #9035 - Add Alt keybinings for new case commands

---

reference/5.1/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
reference/7.0/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
reference/7.2/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
reference/7.3/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md

Prior to this change, the documentation and behavior of the `Set-AuthenticodeSignature` cmdlet diverged.
The documentation for prior versions stated that the default was `SHA256` when it was actually `$null`, which meant that `SHA1` was used when no value was specified.
This change:
- Updates the documentation for 7.3 to clarify that SHA256 is the default starting in that version.
- Updates the documentation for prior versions to reflect the actual behavior (SHA1) for the default.
- Updates the examples in prior versions to explicitly use SHA256 to make the default examples show best practices as SHA1 is not advised.
- Resolves #9040
- Fixes [AB#4439](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4439)
[contrib]: …

(GH-9040) Clarify default SHA for Set-AuthenticodeSignature

---

reference/7.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
reference/7.3/Microsoft.PowerShell.Utility/ConvertFrom-Json.md

Prior to this change, the `ConvertFrom-Json` cmdlet returnedd a **Hashtable** object when used with the **AsHashtable** parameter. Starting with PowerShell 7.3, it instead returns an **OrderedHashtable** object.
This change:
- Modifies the output type and parameter documentation to reflect the updated object type for 7.3.
- Updates the parameter documentation for 7.0+ to better reflect the reasons to use the **AsHashtable** parameter.
- Resolves #9039
- Fixes [AB#4440](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4440)

(GH-9039) Document ordered hash table for ConvertFrom-Json

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md

Prior to this change, the documentation for the format operator was minimal. This change:
- Adds a new example to the format operator documentation in `about_Operators` to cover zero-padding.
- Resolves #9044
- Fixes [AB#4489](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4489)

(GH-9044) Add zero-padding format example

---

reference/5.1/Microsoft.PowerShell.LocalAccounts/Set-LocalUser.md

Prior to this change the `Set-LocalUser` documentation for the **Password** parameter referenced using `Read-Host -GetCredential` to retrieve a **SecureString**. The **GetCredential** parameter does not exist.
This change:
- Updates the documentation to use **AsPlainText** instead
- Resolves #9064
- Fixes [AB#4682](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4682)

(GH-9064) Correct `Set-LocalUser` param info

---

reference/7.0/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md
reference/7.3/Microsoft.PowerShell.Core/About/about_PowerShell_Editions.md

Proposing resolution for two minor issues:
- The original did not clarify that PowerShell 6+ is available for full-featured versions of Windows
- - The original did not clarify that PowerShell 6+ is available cross-platform

"core" designation issue

---

reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Prior to this change, the `Invoke-WebRequest` and `Invoke-RestMethod`
cmdlets in 7.0.0 and higher included the **SkipHeaderValidation**
parameter but not a specific example showing its use.
This change adds a new example for both cmdlets to show:
- How the cmdlets behave when an invalidly formatted value is specified
for a header that has validation
- How the cmdlets behave when the value is valid
- How the **SkipHeaderValidation** parameter allows users to use values
that would normally fail validation.
This change also updates the formatting for the updated files to ease
future maintenance.

(GH-9093) Clarify web cmdlet header validation

---

reference/5.1/CimCmdlets/Set-CimInstance.md
reference/7.0/CimCmdlets/Set-CimInstance.md
reference/7.2/CimCmdlets/Set-CimInstance.md
reference/7.3/CimCmdlets/Set-CimInstance.md

This PR fixes a typo in one of the script examples where used "-Keys" that does not exist. The right parameter is "-Key".

Fixed typo with input parameters "-key"

---

.github/actions/.pwsh/module/functions/api/Add-PullRequestComment.ps1
.github/actions/.pwsh/module/functions/api/Get-AuthorPermission.ps1
.github/actions/.pwsh/module/functions/api/Get-OpenPRWithoutExpectation.ps1
.github/actions/.pwsh/module/functions/api/Get-PullRequestChangedFile.ps1
.github/actions/.pwsh/module/functions/utility/New-CliErrorRecord.ps1

Prior to this change, the GitHub Actions would throw a terminating error if API operations failed for rate limiting. This generated noisy notifications that aren't actionable.
This change updates the `New-CliErrorRecord` to handle well-known errors for the `gh` tool and writes a note to the console log for those errors. Instead of returning an error record for the caller to throw, they don't return an object.
In this implementation, the GHA script exits and the run is considered a success.
Fixes [AB#4960](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4960)

(AB-4960) Handle rate limiting in GHA

---

reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md

Fixes incorrect code snippets as explained in #9007 (see my [comment there](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9007#issuecomment-1212310480)). The [original blog post](https://powershellexplained.com/2020-03-15-Powershell-shouldprocess-whatif-confirm-shouldcontinue-everything/#shouldprocess--force) contains the correct versions of the code snippets.

Fixes #9007 - Fix code snippet errors in ShouldProcess deep dive

---

reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.0/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Enter-PSSession.md

Make the description clear.
Example 7 is not using `-Port` parameter but rather infers that from the `-HostName` parameter.

Enter-PSSession - Fix example 7 description

---

reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Open to your feedback.  Based on testing the default value for RetryIntervalSec is not "None", it's 5 seconds. Here is sample output.
```
Invoke-WebRequest http://github.com/foo/bar.tar.gz -Outfile bar.tar.gz -MaximumRetryCount 4 -Verbose
VERBOSE: GET with 0-byte payload
VERBOSE: Retrying after interval of 5 seconds. Status code for previous attempt: InternalServerError
VERBOSE: Retrying after interval of 5 seconds. Status code for previous attempt: InternalServerError
VERBOSE: Retrying after interval of 5 seconds. Status code for previous attempt: InternalServerError
```
It's waiting 5 seconds, not 0 seconds.
Another question, the -Verbose flag seems helpful. When I was debugging this issue I searched on the page for the words "debug" and "verbose". There's no mention of those flags. …

Documenting RetryIntervalSec value

---

.markdownlint-cli2.yaml
.markdownlint.json
reference/5.1/Microsoft.PowerShell.Core/About/.markdownlint.json
reference/5.1/Microsoft.PowerShell.Security/About/.markdownlint.json
reference/5.1/Microsoft.WSMan.Management/About/.markdownlint.json
reference/5.1/PSReadLine/About/.markdownlint.json
reference/5.1/PSScheduledJob/About/.markdownlint.json
reference/5.1/PSWorkflow/About/.markdownlint.json
reference/7.0/Microsoft.PowerShell.Core/About/.markdownlint.json
reference/7.0/Microsoft.PowerShell.Security/About/.markdownlint.json
reference/7.0/Microsoft.WSMan.Management/About/.markdownlint.json
reference/7.0/PSReadLine/About/.markdownlint.json
reference/7.2/Microsoft.PowerShell.Core/About/.markdownlint.json
reference/7.2/Microsoft.PowerShell.Security/About/.markdownlint.json
reference/7.2/Microsoft.WSMan.Management/About/.markdownlint.json
reference/7.2/PSReadLine/About/.markdownlint.json
reference/7.3/Microsoft.PowerShell.Core/About/.markdownlint.json
reference/7.3/Microsoft.PowerShell.Security/About/.markdownlint.json
reference/7.3/Microsoft.WSMan.Management/About/.markdownlint.json
reference/7.3/PSReadLine/About/.markdownlint.json
reference/includes/alpine-support.md
reference/includes/debian-support.md
reference/includes/dsc-resources.md
reference/includes/macos-support.md
reference/includes/nuget-module.md
reference/includes/product-terms.md
reference/includes/rhel-support.md
reference/includes/tls-gallery.md
reference/includes/ubuntu-support.md
reference/includes/windows-support.md

Prior to this change, the repository had a markdownlint configuration. This change updates that configuration, adds a minimal configuration for markdownlint-cl2 (which the VS Code extension uses), adds a markdownlint configuration to the about folders for reference documentation, and adds a markdownlint ignore directive to the `includes` files.
For the root-folder configuration, this change:
- Adds line length enforcement for code blocks at 90 characters and turns the rule on for code blocks. Previously, it was disabled.
- Adds three new rules, all enabled. These rules are not yet picked up by the VS Code extension, but will be in the next release.
- `link-fragments` requires that links to anchors are valid.
- `reference-links-images` requires that reference-style links use a defined …

(AB-4196) Codify markdownlint

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md

Fixes [AB#5079](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5079) - Fixes #9135 - Add note about passing quoted strings to cmd

Fixes #9135 - Add note about passing quoted strings to cmd

---

reference/5.1/PowershellGet/Find-Module.md
reference/7.0/PowerShellGet/Find-Module.md
reference/7.2/PowerShellGet/Find-Module.md
reference/7.3/PowerShellGet/Find-Module.md

Fixes [AB#5078](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5078) - Add example of searching by tag

Add example of searching by tag

---

reference/docs-conceptual/learn/experimental-features.md

Fixes [AB#5085](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5085) - Add mainstream release NOTE blocks

Add mainstream release NOTE blocks

---

reference/5.1/Microsoft.PowerShell.Core/Set-StrictMode.md
reference/7.0/Microsoft.PowerShell.Core/Set-StrictMode.md
reference/7.2/Microsoft.PowerShell.Core/Set-StrictMode.md
reference/7.3/Microsoft.PowerShell.Core/Set-StrictMode.md

This change uses `3.0` in example 3 instead of `3` for consistency. It also makes minor edits to standardize and clean up the prose.
- Resolves #9163
- Fixes [AB#5120](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5120)

(GH-9163) Fix typo in Set-Strictmode ex 3

---

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
reference/7.2/Microsoft.PowerShell.Management/Start-Process.md
reference/7.3/Microsoft.PowerShell.Management/Start-Process.md

Fixes [AB#5148](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5148) - Fixes #6239 - Document appropriate use of Start-Process

Fixes #6239 - Document appropriate use of Start-Process

---

reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.0/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Enter-PSSession.md

Fixing inconsistent case used for filenames in example 2.
Example 2 uses inconsistent filename cases which could lead to confusion (e.g. "Process.txt" vs "process.txt"). This PR rectifies this.

Fixing inconsistent case used for filenames in example 2

---

reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
reference/7.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
reference/7.3/Microsoft.PowerShell.Utility/ConvertFrom-Json.md

This change helps users avoid [problem #12229 in PowerShell](https://github.com/PowerShell/PowerShell/issues/12229) for the command `ConvertFrom-Json`
Convert-FromJson has a frequent bug, https://github.com/PowerShell/PowerShell/issues/12229, where `.json` files which start with a newline are treated as two different JSON elements. 
From the issue, the proposed fix is to always use `Get-Content -Raw .\file.json | ConvertFrom-Json`, which will treat a `.json` file as a single json object, instead of a file which contains multiple. This is the behaviour most people would expect from `.json` files.

Update Example in Convert-FromJson to avoid issue

---

README.md
reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md
reference/docs-conceptual/community/2020-updates.md
reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/2022-updates.md
reference/docs-conceptual/community/contributing/editorial-checklist.md
reference/docs-conceptual/community/contributing/general-markdown.md
reference/docs-conceptual/community/contributing/overview.md

**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute (part 1)

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Prior to this change, the documentation for `$LastExitCode` in `about_Automatic_Variables` specified that the value was set only by the last native program (for PowerShell) or last Windows-based program (for Windows PowerShell) that was run.
As noted in #9194, this is inaccurate, as the `exit` keyword can be used to set this value when a script is called.
This change:
- Cleans up syntax/prose for maintainability
- Clarifies that `$LastExitCode` can be populated by a PowerShell script
- Clarifies how calling a PowerShell script affects `$LastExitCode`
- Fixes #9194
- Fixes [AB#5371](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5371)
[style]: …

(GH-9194) Document `$LastExitCode` behavior for scripts

---

reference/docs-conceptual/dev-cross-plat/resolving-dependency-conflicts.md

Fix the doc to not recommend using `Assembly.LoadFile`
The API `Assembly.LoadFile` should not be used for the dependency isolation purpose.
This API does load an assembly to a separate `AssemblyLoadContext` instance, but assemblies loaded by this API are discoverable by PowerShell's type resolution code. So, your module could run into the "_Type Identity_" issue when loading an assembly by `Assembly.LoadFile` while another module loads a different version of the same assembly into the default `AssemblyLoadContext`.

Fix the doc to not recommend using `Assembly.LoadFile`

---

reference/docs-conceptual/dev-cross-plat/vscode/using-vscode.md

Unfortunately a breaking change was introduced that we are not reverting, and so these instructions need to be updated.
@sdwheeler @SydneyhSmith

Update VS Code PowerShell Additional Exe Paths instructions

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Line_Editing.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Output_Streams.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Line_Editing.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Output_Streams.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Line_Editing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Output_Streams.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Line_Editing.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Output_Streams.md

Fixes [AB#5700](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5700) - Fixes #9208 - Fix overlocalization of language elements

Fixes #9208 - Fix overlocalization of language elements

---

reference/7.0/Microsoft.PowerShell.Utility/Get-Verb.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Verb.md
reference/7.3/Microsoft.PowerShell.Utility/Get-Verb.md
reference/docs-conceptual/community/2021-updates.md
reference/docs-conceptual/community/2022-updates.md
reference/docs-conceptual/gallery/getting-started.md
reference/docs-conceptual/samples/Managing-Services.md
reference/docs-conceptual/whats-new/differences-from-windows-powershell.md

- Fixes [AB#5908](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/5908)

(AB#5908) Fix broken links

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md

Super tiny change removing a typo in the path for "Current User, All Hosts" - it had a double-backslash but should have a single backslash.

Fix path on "Current User, All Hosts"

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/docs-conceptual/developer/cmdlet/validatescript-attribute-declaration.md

Prior to this change, the SDK conceptual documentation for the **ValidateScript** attribute didn't clarify that the `ErrorMessage` argument is only available in PowerShell 6 and above. The reference documentation did not mention the `ErrorMessage` argument at all.
This change updates the reference and SDK documentation to accurately describe the `ErrorMessage` argument for the **ValidateScript** attribute.
- Resolves #9252
- Fixes [AB#8037](https://dev.azure.com/content-learn/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/8037)

(GH-9252, AB#8037) Clarify ErrorMessage for ValidateScript

---

reference/docs-conceptual/developer/hosting/adding-and-invoking-commands.md

Replace "PowerShellcommands" with "PowerShell commands" in the Adding and invoking commands MSFT documentation.

Fix typo in "Adding and Invoking commands"

---

reference/docs-conceptual/developer/hosting/windows-powershell-host-quickstart.md

Add missing rs.Close() method to "Windows PowerShell Host Quickstart". The intent of this addition is to demonstrate closing the runspace.

Add rs.Close() method to "Windows PowerShell Host Quickstart"

---

reference/7.0/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/7.3/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md

Fix typos in the JSON for execution policy changes in PowerShell.config.json.

Fix typo in execution policy examples in about_PowerShell_config

---

.github/workflows/checklist.yml

Prior to this change, the workflow for verifying the PR checklist ran on `pull_request`. When the Azure Boards bot edits a PR body to associate it with an Azure DevOps item, the last `edited` event that triggers the checklist workflow is from the bot, not a user. Because the bot has never contributed to the project in a way GitHub understands---it only edits comments, never commits code or files an issue---it always trips the GitHub configuration for requiring approval for first-time contributors for PRs from forks.
This change is an attempt to work around this limitation by moving the checklist workflow from `pull_request` to `pull_request_target`, which should run in the context of the upstream repository.
[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing …

(MAINT) Use pull_request_target for checklist

---

reference/5.1/Microsoft.PowerShell.Utility/Group-Object.md
reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md
reference/5.1/Microsoft.PowerShell.Utility/Sort-Object.md
reference/7.0/Microsoft.PowerShell.Utility/Group-Object.md
reference/7.0/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.0/Microsoft.PowerShell.Utility/Sort-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Group-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Sort-Object.md
reference/7.3/Microsoft.PowerShell.Utility/Group-Object.md
reference/7.3/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.3/Microsoft.PowerShell.Utility/Sort-Object.md

Prior to this change, the documentation for `Group-Object`, `Select-Object`, and `Sort-Object` did not specifically address using those cmdlets against **hashtable** input.
In PowerShell 6 an improvement (see PowerShell/PowerShell#6934) enabled users to reference the values of **hashtable** keys in these commands without having to specify calculated properties.
This change:
- Updates the documentation for `Group-Object`, `Select-Object`, and `Sort-Object` in versions 7.0 and above to show how users can group, select, and sort **hashtable** objects by their key values
- Updates the documentation for `Group-Object`, `Select-Object`, and `Sort-Object` in Windows PowerShell 5.1 to show how users can group, select, and sort **hashtable** objects with calculated properties
- Cleans up Vale …

(GH-9311) Document `*-Object` hashtable handling

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Profiles.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md

At location `$PSHOME` there is no `PowerShell.exe` but there is `pwsh.exe`. Maybe that help is from before renaming? Should that affect all occurences of `PowerShell.exe` in this file?

Rename PowerShell.exe to pwsh.exe in help_aboutProfile

---

reference/7.2/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.3/Microsoft.PowerShell.Utility/Export-Csv.md

This changes fixes problem where Example 13 runs with error.  Missing required parameter.  Screenshot below.
Line today reads"$allPeople | Add-Member -Name ExtraProp -Value 42"
Should instead read "$allPeople | Add-Member -Name ExtraProp -Value 42 -MemberType NoteProperty"
- [X ] **Style:** This PR adheres to the [style guide][style].
Absolutely.  Title prefix with "(WIP)".  Appreciate the help to review.

Fix example 13 for `Export-Csv`

---

reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.0/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.2/Microsoft.PowerShell.Core/Invoke-Command.md
reference/7.3/Microsoft.PowerShell.Core/Invoke-Command.md

Prior to this change, Example 18 for `Invoke-Command` raised an error because the **IdleTimeout** value wasn't high enough. The root of this problem is that the example was casting a value for milliseconds to ticks. The **SessionOption** parameter documentation also wasn't explicit that specifying a hashtable for the parameter is different from calling `New-PSSessionObject`.
This change:
- Updates example 18 to use `[timespan]::FromHours()` to make the example functional and easier to understand
- Adds a note to the **SessionOption** parameter documentation about the behavior when a user specifies a hashtable
- Fixes Vale and markdownlint warnings where possible
- Standardizes example code snippets for readability
- Fixes #9357
- Fixes …

(GH-9357) Clarify SessionOption for Invoke-Command

---

reference/7.0/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Telemetry.md

Prior to this change, the `about_Telemetry` documentation included an entry for application type, which was removed in PowerShell 7.0.13, 7.2.7, and 7.3.0-preview.4.
This change:
- removes the now irrelevant and inaccurate entry for the application type data.
- Resolves #9360
- Fixes [AB#26712](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/26712)

(GH-9360) Remove application type from telemetry

---

reference/docs-conceptual/learn/experimental-features.md

Since native argument passing is a breaking change, I would find a note about locally disabling it appropriate.

PSNativeCommandArgumentPassing: how to sidestep

---

reference/7.0/Microsoft.PowerShell.Management/Start-Process.md
reference/7.2/Microsoft.PowerShell.Management/Start-Process.md
reference/7.3/Microsoft.PowerShell.Management/Start-Process.md

A step towards fixing #9383
1. Mention the possibility of starting system commands by bare name.
2. Also use the standard link to [`man nohup`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/nohup.html).

Default *WorkingDirectory* when *FilePath* is bare

---

reference/7.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

This change adds information about how encoding works for the web cmdlets depending on the input:
- Adds information about how **IDictionary**, **String**, and **XmlNode** objects behave for the **Body** for different methods
- Adds information about how **ContentType** can define encoding if the `charset` is specified.
- Resolves #9312
- Fixes [AB#30955](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/30955)

(GH-9312) Clarify encoding for web cmdlets

---

reference/7.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md
reference/7.2/Microsoft.PowerShell.Core/Enable-PSRemoting.md
reference/7.3/Microsoft.PowerShell.Core/Enable-PSRemoting.md

Prior to this change, the demonstrative example for enabling PowerShell Remoting in the 7x versions of `Enable-PSRemoting` referred to PowerShell 6.2. This change updates the documentation to specify the current latest release of PowerShell for the specified version.
- Fixes [AB#32926](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/32926)
- Resolves #9411

(GH-9411) Update version in Enable-PSRemoting examples

---

reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/5.1/Microsoft.PowerShell.Archive/Expand-Archive.md
reference/7.0/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.0/Microsoft.PowerShell.Archive/Expand-Archive.md
reference/7.2/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.2/Microsoft.PowerShell.Archive/Expand-Archive.md
reference/7.3/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.3/Microsoft.PowerShell.Archive/Expand-Archive.md

Changed .Zip to .zip in commands and examples as filenames typically are lower case.

Update archive commands to have lower case .zip in file extension

---

reference/5.1/Microsoft.PowerShell.Management/Get-WmiObject.md

Prior to this change, the `Get-WmiObject` cmdlet documentation included an erroneous note about remoting in the **AsJob** parameter.
This change:
- Removes the erroneous note from the **AsJob** parameter
- Adds a minor note about permissions to the **ComputerName** parameter
- Resolves #9433
- Fixes [AB#37108](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/37108)

(GH-9433) Update remoting info in Get-WmiObject

---

reference/docs-conceptual/learn/deep-dives/everything-about-string-substitutions.md

Prior to this change, the deep dive article on string substition did not link to reference documentation. This change adds a set of reference links to the end of the article for convenience.
- Resolves #9410
- Fixes [AB#38326](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/38326)

(GH-9410) Add links to everything about strings

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md

Prior to this change, the documentation for the preference variable, `$PSNativeCommandErrorActionPreference`, did not clearly denote that it relates to an _experimental_ feature introduced in PowerShell 7.3.
This change clarifies the experimental status of the feature in the documentation for the variable.
- Resolves #9464
- Fixes [AB#41138](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/41138)

(GH-9464) Clarify experimental nature of `$PSNativeCommandErrorActionPreference`

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Prior to this change, the documentation for the `$HOME` variable noted that the variable was equal to `%HOMEDRIVE%%HOMEPATH%` and didn't clarify its value on Unix systems.
This change:
- corrects the documentation for `$HOME` on Windows to reference the `USERPROFILE` environment variable and on Unix the `HOME` environment variable
- Updates the note about non-matching values to clarify that it may not match `%HOMEDRIVE%%HOMEPATH%` instead of `USERPROFILE`
- Resolves #9463
- Fixes [AB#41140](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/41140)

(GH-9463) Correct `$HOME` variable information

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Script_Blocks.md

Prior to this change, the documentation in `about_Script_Blocks` showed how to use delay-binding but didn't explain how they're useful and wasn't clear that this is a usability feature for cmdlet users, not for cmdlet authors.
This change adds some clarification and extends the example to show how delay-binding can help users write shorter, more convenient code.
- Resolves #9479
- Fixes [AB#43576](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/43576)

(GH-9479) Clarify delay-binding

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.0/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

Prior to this change, the documentation for validation attributes in the about topic `about_Functions_Advanced_Parameters` stated:
> When you use a type converter along with a validation attribute,
> the type converter has to be defined before the attribute
This isn't true and several of the examples don't follow this claim. The origin of this note appears to be a workaround for using the **ValidateLength** attribute with an integer parameter or variable.
With the attribute to the left of the type, the statement fails because an integer doesn't have a length and the attribute can't be satisfied. With the attribute to the right of the type, the first assignment can be successful, but you can't assign values to the variable afterward.
This is usage is an anti-pattern that shouldn't be …

(GH-9480) Update validation attribute & examples

---

reference/5.1/PowershellGet/Publish-Module.md
reference/7.0/PowerShellGet/Publish-Module.md
reference/7.2/PowerShellGet/Publish-Module.md
reference/7.3/PowerShellGet/Publish-Module.md

Prior to this change, the **Path** parameter for `Publish-Module` stated that the value must point to the folder where the module exists, but not that the folder must have the same name as the module.
This change:
- Adds a note explicitly stating this requirement
- Resolves #9494
- Fixes [AB#44849](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/44849)

(GH-9494) Add note about path for Publish-Module

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.3/Microsoft.PowerShell.Core/About/about_PSItem.md

This change updates the new documentation about the `$PSItem` automatic variable by:
1. Rewording the synopsis of the variable for clarity and accuracy
1. Removing the erroneous inclusion of the `-replace` operator scriptblock in the overview list for Windows PowerShell
1. Adding the **ValidateScript** attribute as a use case and example
1. Correcting the `Get-Help` URLs
This change:
- Resolves #9534
- Fixes [AB#48597](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/48597)

(GH-9534) Update about_PSItem

---

reference/5.1/Microsoft.PowerShell.Management/Get-Process.md
reference/7.2/Microsoft.PowerShell.Management/Get-Process.md
reference/7.3/Microsoft.PowerShell.Management/Get-Process.md

This change fixes example 5 for Get-Process, which erroneously mentioned getting processes from a
remote computer. This change updates the wording
and example for local-only usage.
- Resolves #9545
- Fixes [AB#52146](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/52146)

(GH-9545) Fix Get-Process example

---

reference/5.1/PowershellGet/Uninstall-Module.md
reference/7.2/PowerShellGet/Uninstall-Module.md
reference/7.3/PowerShellGet/Uninstall-Module.md

This change updates the description for the Uninstall-Module cmdlet to clarify that it only works on modules installed with Install-Module and when the module is not a dependency of other installed modules.
- Resolves #9549
- Fixes [AB#52148](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/52148)

(GH-9549) Clarify Uninstall-Module

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md

This change corrects an example that used square brackets instead of parentheses for grouping.
- Resolves #9544
- Fixes [AB#52145](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/52145)

(GH-9544) Fix pipeline chain example

---

reference/docs-conceptual/learn/ps101/02-help-system.md

Corrected URL that was pointing to the powershell repo instead of the powershell-docs repo.

Corrected url pointing to wrong repo

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

This change documents the `ValidateNotNullOrWhiteSpace` validation attribution added in PowerShell 7.4-preview.1.
- Resolves #9650
- Fixes [AB#57939](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57939)

(GH-9650) Document ValidateNotNullOrWhiteSpace

---

reference/docs-conceptual/learn/experimental-features.md

In one place, it said `PSNativeArgumentPassing` instead of the correct `PSNativeCommandArgumentPassing` that's also used everywhere else.

Fix `PSNativeArgumentPassing` typo

---

reference/5.1/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md

This change corrects the example description from specifying "two" script blocks to the actually used "four" scriptblocks.
- Resolves #9698
- Fixes [AB#59374](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59374)

(GH-9698) Fix example 9 in ForEach-Object

---

reference/7.2/Microsoft.PowerShell.Utility/Join-String.md
reference/7.3/Microsoft.PowerShell.Utility/Join-String.md
reference/7.4/Microsoft.PowerShell.Utility/Join-String.md

This change updates the documentation for the `Join-String` cmdlet to clarify how the **FormatString** parameter works and that users should avoid setting `$OFS` instead of using the **Separator** parameter.
- Resolves #9692
- Fixes [AB#59375](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59375)

(GH-9692) Update Join-String docs

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Function_Provider.md

This change adds an example for retrieving the definition of a hyphenated function using the variable syntax to `about_Function_Provider`.
- Resolves #9707
- Fixes [AB#59643](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59643)

(GH-9707) Update Function provider for hyphenated funcs

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Character_Encoding.md
reference/7.2/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Character_Encoding.md
reference/7.3/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Character_Encoding.md
reference/7.4/Microsoft.PowerShell.Utility/Send-MailMessage.md

[The default encoding is ASCII.](https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Send-MailMessage.cs#L80)
Fixes Powershell/Powershell#18808

Fix Send-MailMessage Default Encoding value from UTF8-NoBOM to ASCII

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Wildcards.md

This fixes a typo in the word "match" in one of the examples used to describe the wildcard characters PowerShell supports.

Fix a typo in one of the wildcard characters examples

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Using.md

Prior to this change, examples 2 and 3 for about_Using were misleading. Example 2 implied that the classes from a script module could be namespaced. Example 3 implied that authors could call `using` to use classes from the assembly when defining a class in PowerShell, which actually raises a parsing exception.
This change reworks both examples to function without errors or incorrect implications.
- Resolves #9744
- Fixes [AB#60738](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/60738)

(GH-9744) Fix about_Using examples

---

reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

This changes "standardard" to "standard" in the documentation for example 9 of Invoke-WebRequest.

Correct typo

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md

Prior to this change, the documentation did not clarify that it is sometimes necessary to temporarily disable the `PSNativeCommandUseErrorActionPreference` feature. Some native commands, like `robocopy`, use non-zero exit codes to report status without necessarily reporting errors.
This change:
- Adds a clarifying example
- Resolves #9768
- Fixes [AB#61442](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/61442)

(GH-9768) Add example for turning off PSNativeCommandUseErrorActionPreference

---

reference/docs-conceptual/lang-spec/chapter-06.md

In order to specify bool with flagging system, you have to supply an argument or else you get an error. This is different behavior than the `switch` type, which allows you to specify the parameter without an arg value without throwing an error. The current state docs indicate that the type conversion for both a `switch` and `bool` are the same, for the case where no arg value is supplied however this is not true in practice. In practice, if a user does not supply an argument value for a `bool`, PowerShell will error, it will not convert that `bool` into a `$true` value.
This PR changes the docs so that the docs no longer imply that passing no argument to a `bool` parameter results in a `$true` value.
```powershell
Example1 -MySwitch # this is OK, and $MySwitch will be converted to $true …
```

Update 6.17 remove untrue claim about parameter binding type conversion for boolean

---

reference/docs-conceptual/developer/format/tablecolumnitems-element-for-tablerowentry-for-tablecontrol-format.md

Very minor edit: Adds a missing '<' character to the `<TableColumnItems>` tag in the example code block.

Fixes TableColumnItems tag in code block

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Aliases.md
reference/7.2/Microsoft.PowerShell.Utility/New-Alias.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Aliases.md
reference/7.3/Microsoft.PowerShell.Utility/New-Alias.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Aliases.md
reference/7.4/Microsoft.PowerShell.Utility/New-Alias.md

I noticed that the `New-Alias` documentation says to use `Remove-Item` to delete an alias, but I've been using `Remove-Alias` with PowerShell 7.x. It looks like `Remove-Alias` was new in 7.x but was not incorporated into the `about_Aliases` or `New-Alias` documentation.
I've updated 7.2, 7.3, and 7.4 docs to reflect `Remove-Alias` where it looked appropriate.

Reference Remove-Alias as it is available in PowerShell 7.x

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitattributes

This change adds a devcontainer definition to the repository. The devcontainer can be used locally or as the backing definition for a codespace and includes:
- PowerShell
- Git
- The GitHub CLI
- Vale
- All suggested VS Code extensions for the repository
This change enables us to move forward with advising contributors to use GitHub Codespaces for their contributions to reduce the friction for setting up their editor.
- Resolves [AB#61939](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/61939)

(AB#61939) Add devcontainer

---

reference/5.1/Microsoft.PowerShell.Management/Clear-Content.md
reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md
reference/5.1/Microsoft.PowerShell.Management/Get-Item.md
reference/7.2/Microsoft.PowerShell.Management/Clear-Content.md
reference/7.2/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.2/Microsoft.PowerShell.Management/Get-Item.md
reference/7.3/Microsoft.PowerShell.Management/Clear-Content.md
reference/7.3/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.3/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.3/Microsoft.PowerShell.Management/Get-Item.md
reference/7.4/Microsoft.PowerShell.Management/Clear-Content.md
reference/7.4/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.4/Microsoft.PowerShell.Management/Get-Item.md

Prior to this change, the reference documentation for the `Copy-Item`, `Get-ChildItem`, and `Get-Item` cmdlets only included dynamic parameters for the FileSystem provider.
This change updates the documentation to:
- clarify that some parameters are only for specific providers
- add provider-specific syntax information
- add notes to clarify which parameters are provider-specific
- document dynamic parameters for providers other than FileSystem

(MAINT) Update *-Item cmdlets for dynamic parameters

---

reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md

* `$PSNativeCommandArgumentPassing`, while part of the documentation, was missing from the table at the top.
Added reference to the proper place, had to update link number references in markdown
* Changed wrongly named `$PSNativeArgumentPassing` to `$PSNativeCommandArgumentPassing` in description of said preference variable

Missing reference in table of contents to `$PSNativeCommandArgumentPassing`

---

reference/7.3/Microsoft.PowerShell.Management/New-ItemProperty.md

Uses the parameter description from [Set-ItemProperty -Type](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-itemproperty?view=powershell-7.3#-type) and applies to [New-ItemProperty -PropertyType](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-itemproperty?view=powershell-7.3#-propertytype) (aliased `-Type`) as well.
This is largely to be able to reference the fact that all values come from [`RegistryValueKind` Enum](https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.registryvaluekind?view=net-7.0)

align type info from Set-ItemProperty and New-ItemProperty

---

reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.2/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.3/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.4/Microsoft.PowerShell.Archive/Compress-Archive.md

Prior to this change, the documentation did not note that the `Compress-Archive` cmdlet ignores hidden files and folders.
This change:
- adds a note explaining the behavior and offering workaround guidance.
- Resolves #9870
- Fixes [AB#67512](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/67512)

(GH-9870) Add note for hidden files/folders to `Compress-Archive`

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

This change updates the example for the `$?` to clarify when the value is set and impacted.
- Resolves #9877
- Fixes [AB#69106](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/69106)

(AB-69106) Update docs for `$?`

---

reference/7.3/Microsoft.PowerShell.Management/New-Service.md

Remove the extra single quotes in New-Service example command. An extra pair of quotes will cause the service to fail to start.

Remove the extra single quotes in New-Service example command

---

reference/5.1/Microsoft.PowerShell.Utility/Group-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Group-Object.md
reference/7.3/Microsoft.PowerShell.Utility/Group-Object.md
reference/7.4/Microsoft.PowerShell.Utility/Group-Object.md

Document the sort order of groups
- Fixes [AB#69659](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/69659)
- Fixes #9891

Fixes #9891 - Document the sort order of groups

---

reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

This change documents several improvements to the web cmdlets in PowerShell 7.4:
- Fixes [AB#70151](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70151)
- Resolves #9689
- Fixes [AB#70152](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70152)
- Resolves #9690
- Fixes [AB#70154](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70154)
- Resolves #9851
- Fixes [AB#70155](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70155)
- Resolves #9863
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-g …

Document improvements to web cmdlets for 7.4

---

reference/7.4/Microsoft.PowerShell.Management/Add-Content.md
reference/7.4/Microsoft.PowerShell.Management/Get-Content.md
reference/7.4/Microsoft.PowerShell.Management/Set-Content.md
reference/7.4/Microsoft.PowerShell.Utility/Export-Clixml.md
reference/7.4/Microsoft.PowerShell.Utility/Export-Csv.md
reference/7.4/Microsoft.PowerShell.Utility/Export-PSSession.md
reference/7.4/Microsoft.PowerShell.Utility/Format-Hex.md
reference/7.4/Microsoft.PowerShell.Utility/Import-Csv.md
reference/7.4/Microsoft.PowerShell.Utility/Out-File.md
reference/7.4/Microsoft.PowerShell.Utility/Select-String.md
reference/7.4/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.4/Microsoft.PowerShell.Utility/Tee-Object.md

This change updates the documentation for the **Encoding** paramter to clarify support for using the `Ansi` value.
- Fixes [AB#70385](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70385)
- Resolves #9887

(GH-9887) Document `Ansi` value for Encoding parameter

---

reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

This change updates the documentation for the **SessionVariable** parameter of the web cmdlets to clarify that the session is persistent starting in 7.4, leading to a performance improvement.
- Fixes [AB#70783](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70783)
- Resolves #9914

(GH-9914) Update docs for SessionVariable

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

This PR deletes a bad example from the documentation page. There is no `$MyInvocation.MyCommand.Path`. ([PowerShell SDK doesn't mention it either](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.commandinfo?view=powershellsdk-1.1.0).) Hence, this PR removes the erroneous mention of `$MyInvocation.MyCommand.Path` from `about_Automatic_Variables.md`.
- Checked only in the area that I changed.
- At least my changes do.

about_Automatic_Variables.md — delete a misleading typo

---

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md

The "Use a HashTable to lookup values or objects" section that I have added to the [PowerShell scripting performance considerations](https://learn.microsoft.com/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations) document shows and explains the impact of using a hashtable to quickly lookup values or objects.
- Fixes #9899

Use a HashTable to lookup values or objects (added performance consideration section)

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Debuggers.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Debuggers.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Debuggers.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Debuggers.md
reference/docs-conceptual/windows-powershell/ise/How-to-Debug-Scripts-in-Windows-PowerShell-ISE.md

**Primary change:** This PR fixes a prevalent typo in the entire repo. It replaces `$MyInvocation.MyCommand.Path` (a typo) with `$MyInvocation.PSCommandPath` (correct.)
To eliminate all doubt, I've checked the following sources:
- PowerShell object browser running in VSCode debugger.
- [PowerShell SDK documentations for the `CommandInfo` class](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.commandinfo?view=powershellsdk-1.1.0) (`MyCommand` is an object of `CommandInfo` type.)
- [Source code of the `CommandInfo` class](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CommandInfo.cs#L92-L747)
Now I have to fix this repo on the rest of the Internet... 😔 This typo is quite prevalent.
**Secondary changes:** In compliance …

Fix typo: `$MyInvocation.PSCommandPath` instead of `$MyInvocation.MyCommand.Path`

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md

Prior to this change, the `about_Calculated_Properties` topic only included scripblocks as valid values for `expression`. This change updates the documentation to note that users can also pass a string value, which is interpreted as the value of a property with the same name on the input object.
- Fixes #9945
- Resolves [AB#79537](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/79537)

(GH-9945)  Document string expression value for calculated properties

---

reference/5.1/PSReadLine/Set-PSReadLineOption.md
reference/7.2/PSReadLine/Set-PSReadLineOption.md
reference/7.3/PSReadLine/Set-PSReadLineOption.md
reference/7.4/PSReadLine/Set-PSReadLineOption.md

This change corrects the documentation for the **AddToHistoryHandler** parameter of the `Set-PSReadLineOption` cmdlet. Prior to this change, the documentation stated that the valid return values were true/false.
The valid return values also include the **AddToHistoryOption** enum and strings matching the names of those enums.
This change corrects the documentation and further explains how each value affects the history.
- Resolves #9948
- Fixes [AB#69559](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/69559)

(GH-9948) Fix AddToHistoryHandler in `Set-PSReadLineOption`

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Prior to this change, the documentation for string comparisons in `about_Comparison_Operators` did not note in the common features section that the comparisons use the `InvariantCulture`. The section for the `eq` and `ne` operator used the phrase `exact match` to describe the comparison, which is inaccurate.
This change:
- Adds a note to the common features about the use of `InvariantCulture`.
- Corrects the description for the equality operators to say that they are equivalent, rather than an exact match.
- Fixes [AB#82412](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/82412)
- Resolves #9982
[style]: …

(GH-9982) Clarify equivalence for comparison operators

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Prior to this change, the documentation for the `-like` and `-notlike` operator did not cover the (potentially surprising) behavior when called for a collection where the members of the collection are not strings.
In this case, the operators return the matching items from the collection cast to `[string]`, unlike the `-match` and `-notmatch` operators, which return the input object.
This change:
- Clarifies the behavior for these operators
- Resolves #9987
- Fixes [AB#83269](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/83269)

(GH-9987) Clarify return behavior for collections with `-like`

---

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md

Prior to this change, the array addition section of the article _PowerShell scripting performance considerations_ recommended that script authors use the **ArrayList** type instead of using array addition to add new values to an array.
The use of **ArrayList** is discouraged in the [.NET documentation][01], recommending instead that developers use **List<T>** with a specific type for homogenous lists or **List<Object>** for heterogenous lists.
This change:
- Recommends using **List<T>** instead of array addition or **ArrayList**
- Adds performance comparisons to clarify the impact of array addition
- Resolves #9997
- Fixes [AB#84476](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/84476)
[contrib]: …

(GH-9997) Recommend `List<T>` over array addition

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md

This change correctly points the link to about_Prompts in the about_Profiles articule.
- Resolves #10002
- Fixes [AB#85079](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/85079)

(GH-10002) Fix broken link in about_Profiles

---

reference/7.2/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.3/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md

Prior to this change, an example in `Select-Object` used the `Get-EventLog` command across all versions. However, that command was removed from PowerShell and the examples should use `Get-WinEvent` instead for newer versions.
This change:
- Updates the command in the example for newer versions of PowerShell
- Resolves #10004
- Fixes [AB#85080](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/85080)

(GH-10004) Use `Get-WinEvent` in v7+ examples

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_OutputTypeAttribute.md

Prior to this change, the notes section of the `about_Functions_OutputTypeAttribute` topic referenced the `Get-Time` function from a prior example without connecting the note to the example. The example could instead use the `Get-Date` cmdlet, which is available and will work regardless of whether the user has run prior examples in their terminal.
This change:
- Updates the notes section to use `Get-Date` instead of `Get-Time`.
- Cleans up linting errors and warnings.
- Ensures correct formatting for types and attributes.
- Resolves #10003
- Fixes [AB#85082](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/85082)
[style]: …

(GH-10003) Clarify OutputType notes

---

reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

This change documents the updated functionality for the **OutFile** parameter in the `Invoke-RestMethod` and `Invoke-WebRequest` cmdlets. It clarifies that you can specify the name of a folder path without a filename and how the cmdlet determines the filename to use.
- Resolves #9788
- Fixes [AB#86341](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/86341)

(GH-9788) Document using folders with OutFile in web cmdlets

---

reference/7.4/Microsoft.PowerShell.Management/Start-Process.md

This change documents the addition of the **Environment** parameter to the `Start-Process` cmdlet in 7.4-preview.3.
- Fixes [AB#86283](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/86283)
- Resolves #9930

(GH-9930) Add **Environment** parameter to `Start-Process`

---

reference/7.2/Microsoft.PowerShell.Utility/Tee-Object.md
reference/7.3/Microsoft.PowerShell.Utility/Tee-Object.md
reference/7.4/Microsoft.PowerShell.Utility/Tee-Object.md

This change updates the documentation for the `Tee-Object` command to explain how users can leverage the **FilePath** parameter to print the **InputObject** to the console.
This change:
- Updates the parameter documentation for the **FilePath** parameter to explain using the console device filepaths to print to console.
- Adds a new example showing a use case for printing to console with `Tee-Object` before continuing to process the objects.
- Resolves #10025
- Fixes [AB#86561](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/86561)

(GH-10025) Document using `Tee-Object` to print to console

---

reference/7.2/Microsoft.PowerShell.Diagnostics/Get-Counter.md

'When the Continuous is specified...' reads awkwardly to me. I feel 'the Continuous switch,' or my edit, is more appropriate.

docs(get-counter): correct grammar for Continuous

---

reference/5.1/Microsoft.PowerShell.Core/Where-Object.md
reference/5.1/Microsoft.PowerShell.Diagnostics/Get-Counter.md
reference/7.2/Microsoft.PowerShell.Core/Where-Object.md
reference/7.2/Microsoft.PowerShell.Diagnostics/Get-Counter.md
reference/7.3/Microsoft.PowerShell.Core/Where-Object.md
reference/7.3/Microsoft.PowerShell.Diagnostics/Get-Counter.md
reference/7.4/Microsoft.PowerShell.Core/Where-Object.md
reference/7.4/Microsoft.PowerShell.Diagnostics/Get-Counter.md

Prior to this change, example 5 for `Where-Object` incorrectly noted that the `-Not` parameter is unavailable for the cmdlet. That was true in Windows PowerShell, but not later versions.
This change:
- Updates the example
- Resolves #10057
- Fixes [AB#88602](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/88602)

(GH-10057) Fix `Where-Object` example

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.vscode/cspell/psdocs/dictionaries/psdocs.txt
reference/docs-conceptual/community/contributing/using-github-codespaces.md
reference/docs-conceptual/toc.yml

This change adds a new article to the contributor's guide for using a GitHub Codespace for authoring and editing contributions. This article explains how a contributor can setup a codespace and use it when contributing to the PowerShell documentation. It includes a few tips and a list of resources.
- Fixes [AB#4176](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/4176)

(AB-4176) Document contributing with codesapces

---

reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md

Prior to this change, the reference documentation for the `New-LocalUser` cmdlet incorrectly stated that it can be used to create a local account that is connected to a Microsoft account.
However, SAM account names, and any API call for creating user accounts, is [limited to 20 characters][01]. This problem was identified in #997 and partially addressed by removing an incorrect example.
With the 20 character limit, a user can't specify a valid email after the `MicrosoftAccount\` prefix - the smallest user name, `MicrosoftAccount\a@outlook.com`, is 30 characters long.
This change:
- Removes the statement about the cmdlet being able to create local accounts connected to a Microsoft account.
- Resolves #10076 
- Fixes [AB#91025](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8 …

(GH-10076) Remove incorrect info from `New-LocalUser`

---

reference/5.1/Microsoft.PowerShell.Utility/Read-Host.md
reference/7.2/Microsoft.PowerShell.Utility/Read-Host.md
reference/7.3/Microsoft.PowerShell.Utility/Read-Host.md
reference/7.4/Microsoft.PowerShell.Utility/Read-Host.md

Prior to this change, the documentation for the `Read-Host` cmdlet didn't include information about trimming the input. The cmdlet doesn't have a built-in way to trim extra spaces from the input value, which is an arbitrary string.
This change:
- Adds an example to `Read-Host` showing how user input may need to normalized before it can be used. It also shows how a reader can apply some simple normalizing techniques to clean up the input.
- Resolves #10088
- Fixes [AB#91532](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/91532)

(GH-10088) Add example for normalizing `Read-Host` input

---

reference/7.4/Microsoft.PowerShell.Utility/Test-Json.md

Cmdlet now uses JsonSchema.NET
- Fixes [AB#96918](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/96918)
- Fixes #10122

Fixes #10122 - Cmdlet now uses JsonSchema.NET

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Enum.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Enum.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Enum.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Enum.md

Prior to this change, the `about_Enum` topic showed using enumerations in scripts but not as parameters.
This change:
- Adds a new section to the article, clarifying the benefits of using enumerations as parameter types and including an example.
- Cleans up the prose and formatting for the article.
- Documents using the `HasFlag()` method as an alternative to using the binary comparison operator.
- Resolves #10127
- Fixes [AB#97124](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/97124)

(GH-10127) Document enums as function parameters

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifests.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Module_Manifests.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Module_Manifests.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Module_Manifests.md

Prior to this change, the documentation noted specific variables you can use in module manifests, but did not note that you can use environment variables, unlike in restricted language mode.
This change:
- Adds a note in the section on module manifest variables to both the `about_Module_Manifests` and `about_Language_Modes` articles.
- Resolves #10140
- Fixes [AB#98137](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/98137)

(GH-10140) Document env vars in manifests

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Fixing a minor typo in the Note section describing the difference in winget behaviours on X86/64 and Arm64 machines.

Update Installing-PowerShell-on-Windows.md - fixing typo

---

reference/5.1/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.2/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.3/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
reference/7.3/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.4/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
reference/7.4/Microsoft.PowerShell.Management/Get-ChildItem.md

Document behavior for AppExecLinks
- Fixes [AB#100143](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/100143)
- Fixes #10168

Fixes #10168 - Document behavior for AppExecLinks

---

reference/5.1/Microsoft.PowerShell.Management/Get-Content.md
reference/7.2/Microsoft.PowerShell.Management/Get-Content.md
reference/7.3/Microsoft.PowerShell.Management/Get-Content.md
reference/7.4/Microsoft.PowerShell.Management/Get-Content.md
reference/docs-conceptual/install/install-raspbian.md

Update defaults for Head and Tail parameters
- Fixes [AB#117346](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117346)
- Fixes #10183
- Also fixes a typo from #10180

Fixes #10183 - Update defaults for Head and Tail parameters

---

reference/5.1/Microsoft.PowerShell.Management/Get-Content.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md
reference/7.2/Microsoft.PowerShell.Management/Get-Content.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md
reference/7.3/Microsoft.PowerShell.Management/Get-Content.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Pipeline_Chain_Operators.md
reference/7.4/Microsoft.PowerShell.Management/Get-Content.md
reference/docs-conceptual/install/install-raspbian.md

6/21/2023 PM Publish

---

reference/docs-conceptual/dev-cross-plat/Writing-Portable-Modules.md

`dotnet new -i` is deprecated. Using it will get a warning:
```plain
Warning: use of 'dotnet new --install' is deprecated.
```

Fixed obsolete dotnet statement

---

reference/docs-conceptual/dev-cross-plat/Writing-Portable-Modules.md

* Fixed obsolete dotnet statement
`dotnet new -i` is deprecated. Using it will get a warning:
```plain
Warning: use of 'dotnet new --install' is deprecated.
```
* Update dotnet output

6/29/2023 PM Publish

---

reference/docs-conceptual/install/install-rhel.md

Prior to this change, the install documentation for RHEL 9 directed users to add the Microsoft repository and install PowerShell from there. However, the PowerShell RPMs have not been published to that repo yet.
This change:
- Directs users to install PowerShell on RHEL 9 via direct download instead
- Resolves #10219

(GH-10219) Update RHEL 9 intall instructions

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md

Add note about PSResourceGet
- Fixes [AB#122984](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/122984)
- Fixes #10231

Fixes #10231 - Add note about PSResourceGet

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Debuggers.md
reference/5.1/Microsoft.PowerShell.Management/New-Item.md
reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Debuggers.md
reference/7.2/Microsoft.PowerShell.Management/New-Item.md
reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Debuggers.md
reference/7.3/Microsoft.PowerShell.Management/New-Item.md
reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Debuggers.md
reference/7.4/Microsoft.PowerShell.Management/New-Item.md
reference/7.4/Microsoft.PowerShell.Management/Test-Connection.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md

6/30/2023 PM Publish

---

reference/docs-conceptual/dev-cross-plat/create-cmdline-predictor.md

Adding details for why a predictor results may be silently failing for users. This gives more details about the requirements for predictors to meet the timeout in order to be displayed.

Adding note about creating predictors that there needs to be a 20ms time out

---

reference/5.1/PSReadLine/Set-PSReadLineOption.md
reference/7.2/PSReadLine/Set-PSReadLineOption.md
reference/7.3/PSReadLine/Set-PSReadLineOption.md
reference/7.4/PSReadLine/Set-PSReadLineOption.md

* Adding example to -AddToHistoryHandler
* adding note about profile

7/11/2023 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/5.1/Microsoft.PowerShell.Utility/Out-File.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.2/Microsoft.PowerShell.Utility/Out-File.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.3/Microsoft.PowerShell.Utility/Out-File.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.4/Microsoft.PowerShell.Utility/Out-File.md

7/27/2023 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md

Changes nonstandard hexadecimal notation to use numeric literal format with upper case
Fixes #10314

Use literal hexadecimal notation with upper case

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md

Use only one syntax token spacing format and use lists to clearly show two syntax versions.
Fixes #10322

One syntax token format, lists to split versions

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md

Prior to this change, the documentation in the about topic for Group Policy indicated that user-level policies override machine-level policies. That precedence is inverted.
This change:
- Fixes [AB#147826](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/147826)
- Resolves #10340
- Corrects the language, indicating that machine-level policies override user-level policies.
- Makes minor updates to style and grammar throughout the article.

(GH-10340) Fix GPO precedence language

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Enum.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Using.md
reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Enum.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Requires.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.2/Microsoft.PowerShell.Core/Import-Module.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Enum.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Requires.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.3/Microsoft.PowerShell.Core/Import-Module.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Enum.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Requires.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Using.md
reference/7.4/Microsoft.PowerShell.Core/Import-Module.md

Classes need to be defined directly in the module's psm1 file in order to be imported into the script using the module, but this wasn't obvious from the previous wording.
This PR adds wording to explicitly mention that classes should be placed in the module's psm1 file.

Clarify `using` statement and class/enum definition requirements

---

reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Document new UnixSocket parameter for web cmdlets
- Fixes [AB#148285](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/148285)
- Fixes #10033

Fixes #10033 - Document new UnixSocket parameter for web cmdlets

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Properties.md

Improve description of Count property

Improve description of Count property

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Prompts.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Prompts.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Prompts.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Prompts.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.4/PSReadLine/Get-PSReadLineOption.md
reference/7.4/PSReadLine/Set-PSReadLineOption.md
reference/docs-conceptual/community/contributing/product-terminology.md

8/21/2023 PM Publish

---

reference/7.4/Microsoft.PowerShell.Management/Resolve-Path.md

This change updates the example and documentation for the **RelativeBasePath** parameter of the `Resolve-Path` cmdlet in PowerShell 7.4 to reflect the changes made in PowerShell/PowerShell#19755 affecting the output for the cmdlet when using the parameter.
- Fixes [AB#149096](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/149096)

(AB#149096) Update RelativeBasePath for Resolve-Path

---

reference/7.4/Microsoft.PowerShell.Management/Resolve-Path.md

This change updates the example and documentation for the **RelativeBasePath** parameter of the `Resolve-Path` cmdlet in PowerShell 7.4 to reflect the changes made in PowerShell/PowerShell#19755 affecting the output for the cmdlet when using the parameter.
- Fixes [AB#149096](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/149096)

8/22/2023 PM Publish

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md

Update release notes for 7.4-p5

Update release notes for 7.4-p5

---

reference/7.4/Microsoft.PowerShell.Management/Wait-Process.md
reference/7.4/Microsoft.PowerShell.Utility/Get-Unique.md
reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md

* Add CaseInsensitive parameter for 7.4-p5
* Feedback

8/23/2023 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md

8/29/2023 PM Publish

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md

Prior to this change, the documentation in `about_Operators` referenced .NET Framework types and classes instead of .NET types and classes.
This change:
- Removes the incorrect qualifier as 7+ is built on .NET, not the .NET Framework.
- Fixes [AB#156514](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/156514)
- Resolves #10382

(AB#156514) Remove reference to .NET Framework in about_Operators

---

reference/5.1/Microsoft.PowerShell.Management/Convert-Path.md
reference/7.2/Microsoft.PowerShell.Management/Convert-Path.md
reference/7.3/Microsoft.PowerShell.Management/Convert-Path.md
reference/7.4/Microsoft.PowerShell.Management/Convert-Path.md

Prior to this change, the **Path** parameter for the `Convert-Path` cmdlet indicated that it does not accept wildcard values, even though it does.
This change:
- Updates the metadata to accurately reflect the cmdlet behavior
- Fixes [AB#156610](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/156610)
- Resolves #10385

(GH-10385) Indicate Path accepts wildcards for `Convert-Path`

---

reference/docs-conceptual/install/community-support.md

Update Pi install script
Related to #10378

Update Pi install script

---

reference/5.1/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/7.4/Microsoft.PowerShell.Core/Connect-PSSession.md

Prior to this PR, `Connect-PSSession` has examples that does not type out the parameter names.
To clarify and align with the style guideline, the parameter names should be added.
- Fixes #10398

Quality: Fix formatting for code blocks for `Connect-PSSession` 

---

.github/workflows/checklist.yml
.github/workflows/expectations.yml
.github/workflows/stale-content.yml
.github/workflows/targeting-repo-files.yml
.github/workflows/targeting-valid-branch.yml
.github/workflows/versioned-content.yml
reference/5.1/CimCmdlets/Get-CimClass.md
reference/5.1/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/7.2/CimCmdlets/Get-CimClass.md
reference/7.2/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md
reference/7.3/CimCmdlets/Get-CimClass.md
reference/7.3/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/7.3/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md
reference/7.4/CimCmdlets/Get-CimClass.md
reference/7.4/Microsoft.PowerShell.Core/Connect-PSSession.md
reference/7.4/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md
reference/docs-conceptual/community/2023-updates.md
reference/docs-conceptual/community/hall-of-fame.md
reference/docs-conceptual/windows-powershell/wmf/overview.md

9/11/2023 PM Publish

---

.github/ISSUE_TEMPLATE/04-customer-feedback.yml

Add feedback template

---

reference/5.1/Microsoft.WSMan.Management/Remove-WSManInstance.md
reference/7.2/Microsoft.WSMan.Management/Remove-WSManInstance.md
reference/7.3/Microsoft.WSMan.Management/Remove-WSManInstance.md
reference/7.4/Microsoft.WSMan.Management/Remove-WSManInstance.md

Fix hashtable in example
- Fixes [AB#161626](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161626)

Fix hashtable in example

---

reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.2/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.3/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.4/Microsoft.PowerShell.Host/Start-Transcript.md

Add example creating a unique transcript filename
- Fixes [AB#161627](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161627)

Add example creating a unique transcript filename

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md
reference/5.1/Microsoft.PowerShell.Management/Set-Service.md
reference/5.1/Microsoft.PowerShell.Management/Split-Path.md
reference/5.1/Microsoft.WSMan.Management/Remove-WSManInstance.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.2/Microsoft.PowerShell.Management/Set-Service.md
reference/7.2/Microsoft.PowerShell.Management/Split-Path.md
reference/7.2/Microsoft.WSMan.Management/Remove-WSManInstance.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.3/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.3/Microsoft.PowerShell.Management/Set-Service.md
reference/7.3/Microsoft.PowerShell.Management/Split-Path.md
reference/7.3/Microsoft.WSMan.Management/Remove-WSManInstance.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.4/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.4/Microsoft.PowerShell.Management/Set-Service.md
reference/7.4/Microsoft.PowerShell.Management/Split-Path.md
reference/7.4/Microsoft.WSMan.Management/Remove-WSManInstance.md
reference/docs-conceptual/learn/deep-dives/everything-about-if.md

9/20/2023 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/Get-Job.md
reference/7.2/Microsoft.PowerShell.Core/Get-Job.md
reference/7.3/Microsoft.PowerShell.Core/Get-Job.md
reference/7.4/Microsoft.PowerShell.Core/Get-Job.md

Prior to this PR, `Get-Job` has a few examples that needs to be cleaned up to align with the code formatting guidelines.
It also has a few examples that are non-functioning.
Example 8 states: `The fifth command uses Invoke-Command to run a Get-Job command on the S2 computer.`
It then does:
`Invoke-Command -ComputerName S2 -ScriptBlock {Start-Job -ScriptBlock {Get-EventLog System}}`
This is exactly what the `forth command` does in the same example.
I edited this to align with how one can manage a [remote job on a remote computer](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_jobs?view=powershell-7.3#start-a-remote-job-that-keeps-the-results-on-the-remote-computer)
In example 4, the example is about how Get-Job accepts pipeline input. It …

Quality: Cleanup of Get-Job examples

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

Prior to this change, the example for demonstrating how a here-string can simplify syntax defined a value that would've been valid even in a normal double-quoted string.
This change:
- Updates the example to use both a single quote and a double quote, which would require escaping in a normal string, to make the usage and value clearer.
- Addresses error-level issues for the document's prose style.
- Resolves #10452
- Fixes [AB#163608](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/163608)

(GH-10452) Improve here-string example

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/includes/ubuntu-support.md

Update install docs for supported methods
- Fixes [AB#161680](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161680)
- Fixes #10297

Fixes #10297 - Update install docs for supported methods

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md

Prior to this change, the documentation for using grouped expressions in _about_Operators_ included two subheadings:
1. Grouping assignment statements
1. Piping grouped expressions
However, it also defined a third use-case for grouping, which showed how to use the grouping operator to use the output of a command in an expression. This use case was documented before the subheadings and after a sentence indicating there's ways to use the grouping operator beyond overriding operator precedence.
Further, the section for grouping assignment statements was very long compared to the other use-cases and placed in the middle, despite being less commonly used than the others.
This change:
- Adds a subheading for the first use case to make it equivalent to the others in the information hierarchy.
- …

(GH-10459) Reorganize grouping expression docs

---

.github/ISSUE_TEMPLATE/04-customer-feedback.yml
reference/docfx.json

Update OSS feedback settings

---

reference/5.1/Microsoft.PowerShell.Core/Start-Job.md
reference/5.1/Microsoft.PowerShell.Core/Stop-Job.md
reference/5.1/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.2/Microsoft.PowerShell.Core/Start-Job.md
reference/7.2/Microsoft.PowerShell.Core/Stop-Job.md
reference/7.2/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.3/Microsoft.PowerShell.Core/Start-Job.md
reference/7.3/Microsoft.PowerShell.Core/Stop-Job.md
reference/7.3/Microsoft.PowerShell.Core/Wait-Job.md
reference/7.4/Microsoft.PowerShell.Core/Start-Job.md
reference/7.4/Microsoft.PowerShell.Core/Stop-Job.md
reference/7.4/Microsoft.PowerShell.Core/Wait-Job.md

Prior to this PR, the Get-Help for the cmdlets `Start-Job`, `Stop-Job` and `Wait-Job` had some minor code samples formatting issues including missing parameter names and usage of alias.
- Fixes #10473

Quality: Cleanup of Start, Stop and Wait-Job examples

---

reference/5.1/PSReadLine/Set-PSReadLineKeyHandler.md
reference/7.2/PSReadLine/Set-PSReadLineKeyHandler.md
reference/7.3/PSReadLine/Set-PSReadLineKeyHandler.md
reference/7.4/PSReadLine/Set-PSReadLineKeyHandler.md

Update key binding examples
- Fixes [AB#166500](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/166500)
- Fixes #10480

Fixes #10480 - Update key binding examples

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md

Fix example to support pipelining
- Fixes [AB#166701](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/166701)
- Fixes #10478

Fixes #10478 - Fix example to support pipelining

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/5.1/PSReadLine/Set-PSReadLineKeyHandler.md
reference/5.1/PSReadLine/Set-PSReadLineOption.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.2/PSReadLine/Set-PSReadLineKeyHandler.md
reference/7.2/PSReadLine/Set-PSReadLineOption.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.3/PSReadLine/Set-PSReadLineKeyHandler.md
reference/7.3/PSReadLine/Set-PSReadLineOption.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.4/PSReadLine/Set-PSReadLineKeyHandler.md
reference/7.4/PSReadLine/Set-PSReadLineOption.md
reference/docs-conceptual/community/2023-updates.md
reference/docs-conceptual/community/hall-of-fame.md

10/02 PM Publishing

---

reference/docs-conceptual/developer/help/examples-of-comment-based-help.md

10/05 PM Publishing

---

reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md

Prior to this change, the "Enumerating property names" section in _Everything you wanted to know about PSCustomObject_ didn't clarify that the results from using `Get-Member` and the member-access operator to enumerate property names differs.
`Get-Member` returns the properties in alphabetical order while member-access returns them in the order they were defined on the object.
This change:
- adds a note to clarify this difference.
- Resolves #10505
- Fixes [AB#169145](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/169145)

(GH-10505) Add note on property name ordering

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Prior to this change, the upgrade instructions for Windows didn't help a user understand how to find where their install was located to determine which upgrade method to use.
This change:
- Adds information to help users understand which method  was used to install PowerShell
- Adds a note for how to determine if PowerShell may be upgraded with Winget
- Resolves [AB#168938](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/168938)

(AB-168938) Update Windows upgrade info

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.3/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.4/Microsoft.PowerShell.Core/About/about_PSCustomObject.md

Prior to this change, the documentation note for the **Length** and **Count** properties of **PSCustomObjects** created by casting a hashtable indicated that, for Windows PowerShell, those properties don't exist on the object and accessing them returns `$null`.
However, in PowerShell, those members exist and return a value of `1`.
This change:
- Updates the note to indicate the changed behavior.
- Fixes [AB#168933](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/168933)

(AB-168933) Clarify Length and Count for PSCustomObject

---

reference/5.1/Microsoft.PowerShell.Management/Add-Content.md
reference/7.2/Microsoft.PowerShell.Management/Add-Content.md
reference/7.3/Microsoft.PowerShell.Management/Add-Content.md
reference/7.4/Microsoft.PowerShell.Management/Add-Content.md

Fix input references and pipeline support
- Fixes [AB#168935](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/168935)

Fix input references and pipeline support

---

reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md

Removes incorrect assertion that functions must use `begin`, `process`, and `end` if any named block is used. 
This implies these blocks are required even if they are empty. Assertion is contradicted later in the document when discussing `process`.

Corrects note about use of named blocks

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Information.md

Added a note regarding the usage of the common parameter `-InformationVariable` when using tagged `Write-Information`

add hint about -InformationVariable for using tags

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Updatable_Help.md

Fix incorrect cmdlet example
- Fixes [AB#171841](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/171841)
- Fixes #10553

Fixes #10553 - Fix incorrect cmdlet example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_ISE.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Windows_Powershell_5.1.md
reference/5.1/Microsoft.PowerShell.Management/Show-ControlPanelItem.md
reference/5.1/Microsoft.PowerShell.Security/New-FileCatalog.md
reference/5.1/Microsoft.PowerShell.Security/Set-Acl.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.2/Microsoft.PowerShell.Security/New-FileCatalog.md
reference/7.2/Microsoft.PowerShell.Security/Set-Acl.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.3/Microsoft.PowerShell.Security/New-FileCatalog.md
reference/7.3/Microsoft.PowerShell.Security/Set-Acl.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.4/Microsoft.PowerShell.Security/New-FileCatalog.md
reference/7.4/Microsoft.PowerShell.Security/Set-Acl.md
reference/docs-conceptual/developer/installing-the-windows-powershell-sdk.md
reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md
reference/docs-conceptual/learn/remoting/WinRMSecurity.md
reference/docs-conceptual/learn/remoting/jea/prerequisites.md
reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
reference/docs-conceptual/windows-powershell/Starting-Windows-PowerShell.md
reference/docs-conceptual/windows-powershell/install/Windows-PowerShell-System-Requirements.md
reference/docs-conceptual/windows-powershell/wmf/overview.md
reference/includes/windows-support.md

Update refs to Win2012 since it is out of support
- Fixes [AB#173407](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/173407)

Update refs to Win2012 since it is out of support

---

reference/docs-conceptual/install/install-ubuntu.md

Add note about .NET package sources
- Fixes [AB#173706](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/173706)
- Fixes #10564

Fixes #10564 - Add note about .NET package sources

---

reference/7.4/Microsoft.PowerShell.Management/Test-Connection.md

This change adds a note to the `Test-Connection` reference documentation about requiring `sudo` for non-standard buffer sizes.
- Resolves #10458

(GH-10458) Add note about `sudo` for `Test-Connection`

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Prior to this change, the `about_Automatic_Variables` article included an unnecessary `Out-Null` in a loop example. Using `Out-Null` in this case implies that the `Reset()` method returns output, which it doesn't.
This change:
- Removes the unnecessary `Out-Null` from the example.
- Resolves #10580
- Fixes [AB#174090](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/174090)

(GH-10580) Remove extraneous example code

---

reference/docs-conceptual/install/install-rhel.md

For clarity, removed instructions to direct download RHEL9 package since it is now available in the PMC.

Remove instruction to download RHEL9 package direct

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Syntax.md
reference/5.1/Microsoft.PowerShell.Management/Add-Content.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Command_Syntax.md
reference/7.2/Microsoft.PowerShell.Management/Add-Content.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Command_Syntax.md
reference/7.3/Microsoft.PowerShell.Management/Add-Content.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Command_Syntax.md
reference/7.4/Microsoft.PowerShell.Management/Add-Content.md

10/31/2023 PM Publish

---

reference/docs-conceptual/community/2023-updates.md
reference/docs-conceptual/community/hall-of-fame.md

Update monthly stats
- Fixes [AB#177323](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/177323)

Update monthly stats

---

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md
reference/7.2/Microsoft.PowerShell.Management/Start-Process.md
reference/7.3/Microsoft.PowerShell.Management/Start-Process.md
reference/7.4/Microsoft.PowerShell.Management/Start-Process.md

Remove broken example
- Fixes [AB#177539](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/177539)
- Fixes #10601

Fixes #10601 - Remove broken example

---

reference/5.1/Microsoft.PowerShell.Core/About/About.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Inheritance.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.2/Microsoft.PowerShell.Core/About/About.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Inheritance.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.3/Microsoft.PowerShell.Core/About/About.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Inheritance.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.4/Microsoft.PowerShell.Core/About/About.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Inheritance.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Properties.md

Prior to this change, the class documentation did not go into sufficient detail for the syntax, definition, and limitations of class members.
This change decomposes the `about_Classes` documentation into multiple files:
- `about_Classes` - overview, basic information, full list of limitations.
- `about_Classes_Properties` - Full documentation for defining class properties.
- `about_Classes_Methods` - Full documentation for defining class methods.
- `about_Classes_Constructors` - Full documentation for defining class constructors.
- `about_Classes_Inheritance` - Full documentation for defining classes that inherit from a base class or implement an interface.
This change fixes [AB#161630](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161630). …

(AB-161630) Refactor and extend class docs

---

reference/5.1/Microsoft.PowerShell.Core/About/About.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Inheritance.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.2/Microsoft.PowerShell.Core/About/About.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Inheritance.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.3/Microsoft.PowerShell.Core/About/About.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Inheritance.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.4/Microsoft.PowerShell.Core/About/About.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Inheritance.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Properties.md

Prior to this change, the class documentation did not go into sufficient detail for the syntax, definition, and limitations of class members.
This change decomposes the `about_Classes` documentation into multiple files:
- `about_Classes` - overview, basic information, full list of limitations.
- `about_Classes_Properties` - Full documentation for defining class properties.
- `about_Classes_Methods` - Full documentation for defining class methods.
- `about_Classes_Constructors` - Full documentation for defining class constructors.
- `about_Classes_Inheritance` - Full documentation for defining classes that inherit from a base class or implement an interface.
This change fixes [AB#161630](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161630). …

11/10/2023 PM Publish

---

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md

Add note about using inc/exc with LiteralPath
- Fixes [AB#182801](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/182801)
- Fixes #10622

Fixes #10622 - Add note about using inc/exc with LiteralPath

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Properties.md

Prior to this change, the class documentation did not clearly explain which automatic variables are available in class methods other than the `$this` variable. This change adds the list of available automatic variables and how to access them.
It also makes minor corrections to links and uses `Update-TypeData` instead of `Add-Member` consistently. Finally, it explains examples that were previously missing any information.

(MAINT) Clarify automatic vars in classes

---

reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md
reference/7.2/Microsoft.PowerShell.Utility/Add-Member.md
reference/7.3/Microsoft.PowerShell.Utility/Add-Member.md
reference/7.4/Microsoft.PowerShell.Utility/Add-Member.md

Prior to this change, Example 3 in the 7x documentation for `Add-Member` was incorrect. Example 6 across all versions rendered incorrectly.
This change:
- Fixes #10633 by correcting the example
- Fixes #10634 by turning the example code blocks into a single demonstrative block.
- Fixes Vale linting errors.

Fix `Add-Member` examples

---

reference/5.1/Microsoft.PowerShell.Core/Where-Object.md
reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.2/Microsoft.PowerShell.Core/Where-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.3/Microsoft.PowerShell.Core/Where-Object.md
reference/7.3/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.4/Microsoft.PowerShell.Core/Where-Object.md
reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md

Prior to this change:
- The **UseNewRunspace** parameter of the `ForEach-Object` cmdlet wasn't included in the cmdlet syntax for any parameter set.
- The "Notes" section of `ForEach-Object` directed users to the wrong example for thread safety.
- The `Where-Object` reference documentation used the `where` alias throughout the article, not just when discussing the alias specifically.
- The **SkipIndex** parameter of the `Select-Object` cmdlet was missing a description entirely and didn't indicate the version of PowerShell it was added in.
This change:
- Adds the **UseNewRunspace** parameter to the `ParallelParameterSet` syntax of the `ForEach-Object` cmdlet reference.
- Fixes #10642
- Fixes [AB#183543](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/ …

Fix issues in `*-Object` documentation

---

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md

Prior to this change, the PowerShell 7.4 end of support date was incorrectly listed as May 15, 2025.
PowerShell 7.4 is built on .NET 8 and follows the same LTS lifecycle.
This change:
- Corrects the end of support date for PowerShell 7.4
- Fixes #10658

(GH-10658) Correct 7.4 end of support date

---

reference/docs-conceptual/learn/experimental-features.md

Prior to this change, the documentation for the `$PSNativeCommandUseErrorActionPreference` variable noted that it defaults to `$true` starting in PowerShell 7.4.
The different default value was temporary for gathering feedback while 7.4 was in preview. When 7.4 was released as stable, the default value was reverted to `$false` in PowerShell/PowerShell#20285.
This change:
- Replaces the misleading sentence with one that states the default value as `$true`.
- Fixes #10661

(GH-10661) Fix `$PSNativeCommandUseErrorActionPreference` default

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Enum.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Enum.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Enum.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Enum.md

Prior to this change, the `about_Enum` documentation didn't include the ability to set underlying base types for PowerShell 6.2 and later. It also didn't clearly identify the available methods for using enumerations outside of examples, discuss formatting enumeration values with format strings, show how to define extension methods, or include documentation about the limitations of enumerations.
This change:
- Resolves #10574
- Fixes [AB#182987](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/182987)
- Reorganizes and extends the documentation to cover missing topics, make it easier to discover syntax, and add more examples. This work mimics the restructuring of `about_Classes`, but without creating new articles.
[contrib]: …

11/21/2023 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Redirection.md
reference/7.4/Microsoft.PowerShell.Utility/Out-File.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md

Update notes on redirection of native commands
- Fixes [AB#186985](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/186985)
- Fixes #10677
- Fixes #10678 

Fixes #10677 - Update notes on redirection of native commands

---

reference/7.4/Microsoft.PowerShell.Core/About/about_Redirection.md

Remove redundant sentence
- Fixes #10677

Fixes #10677 - Remove redundant sentence

---

reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
reference/7.2/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
reference/7.3/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
reference/7.4/Microsoft.PowerShell.Utility/ConvertFrom-Json.md

"end"/"and" typo was introduced a year ago in #9496
Searched rest of repo and the PR diff and didn't see any more of this typo! :)

Fix small typo in ConvertFrom-Json.md

---

reference/7.2/Microsoft.PowerShell.Management/Test-Connection.md
reference/7.3/Microsoft.PowerShell.Management/Test-Connection.md
reference/7.4/Microsoft.PowerShell.Management/Test-Connection.md

Prior to this change, the documentation for the `-Repeat` parameter of the `Test-Connection` cmdlet did not indicate that the cmdlet continuously pings only the _first_ value for the `-TargetValue` parameter.
This change:
- Clarifies the behavior.
- Resolves #10697
- Fixes [AB#187541](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187541)

(GH-10697) Clarify behavior of `-Repeat` for `Test-Connection`

---

reference/7.4/Microsoft.PowerShell.Security/Get-AuthenticodeSignature.md

Prior to this change, the documentation for the `-Content` parameter of the `Get-Authenticode` cmdlet in version 7.4 incorrectly stated that the contents must be encoded as UTF-16LE. This was true in prior versions, but in 7.4 the cmdlet works with content of any valid and readable encoding.
This change:
- Updates the description for the `-Content` parameter to indicate that the encoding limitation is removed in PowerShell 7.4.
- Resolves #10698
- Fixes [AB#187542](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187542)

(GH-10698) Update `-Content` parameter for `Get-Authenticode` in 7.4

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Update_Notifications.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Update_Notifications.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Update_Notifications.md

Add info about using environment variable
- Fixes [AB#187724](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187724)
- Fixes #10696

Fixes #10696 - Add info about using environment variable

---

reference/5.1/Microsoft.PowerShell.Management/New-Service.md
reference/7.2/Microsoft.PowerShell.Management/New-Service.md
reference/7.3/Microsoft.PowerShell.Management/New-Service.md
reference/7.4/Microsoft.PowerShell.Management/New-Service.md

In the documentation for the `New-Service` command, it states that it should be use like the following:
```powershell
New-Service -Name "TestService" -BinaryPathName '"C:\WINDOWS\System32\svchost.exe -k netsvcs"'
```
But the reality is that using this command, the created service will try to find a file with the name `'svchost.exe -k netsvcs'`, giving the message in the Services app `Error 2: The system cannot find the file specified`.
As the documentation says `If the path contains a space, it must be quoted so that it is correctly interpreted.`, but arguments are not part of the path so they should be outside of the double quotes.
[style]: …

Fix New-Service -BinaryPathName quotes

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md
reference/5.1/Microsoft.PowerShell.Core/About/about_PSSnapins.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Modules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Modules.md
reference/7.3/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Modules.md
reference/7.4/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md

Rewrite about_modules
- Fixes [AB#190105](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/190105)

Rewrite about_modules

---

reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md

12/13/2023 PM Publish

---

reference/5.1/Microsoft.PowerShell.Utility/Update-List.md
reference/7.2/Microsoft.PowerShell.Utility/Update-List.md
reference/7.3/Microsoft.PowerShell.Utility/Update-List.md
reference/7.4/Microsoft.PowerShell.Utility/Update-List.md

Fix output types and add example
- Fixes [AB#196384](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/196384)
- Fixes #10753

Fixes #10753 - Fix output types and add example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Logging.md
reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md

Crosslink articles to improve discoverability
- Fixes [AB#196601](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/196601)

Crosslink articles to improve discoverability

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Clarify which certificates are used
- Fixes [AB#196462](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/196462)

Clarify which certificates are used

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md
reference/5.1/Microsoft.PowerShell.Host/Stop-Transcript.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.2/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.2/Microsoft.PowerShell.Host/Stop-Transcript.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.3/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.3/Microsoft.PowerShell.Host/Stop-Transcript.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.4/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.4/Microsoft.PowerShell.Host/Stop-Transcript.md

Update transcript file information
- Fixes [AB#196907](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/196907)

Update transcript file information

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md

Prior to this change, `about_Intrinsic_Members` defines examples that describe a hashtable and interacts with a variable containing the hashtable but doesn't define the hashtable itself in the code blocks. The examples also use `-Type` with the `Get-Member` cmdlet, which is an alias for the paramter canonically named **MemberType**.
This change:
- Defines the `$hash` variable in the first code block for the example, ensuring readers can follow along without needing to intuit the definition from the output.
- Replaces usage of the `-Type` alias parameter with the canonical parameter name **MemberType**, making it easier for readers to look up the parameter. This also adheres to the docs style guide.
- Resolves #10780
- Fixes [AB#198703](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b …

(GH-10780) Fix example in about_Intrinsic_Members

---

reference/5.1/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.3/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.4/Microsoft.PowerShell.Utility/Get-Member.md

Prior to this change, the documentation for the **Static** parameter on the `Get-Member` cmdlet did not clarify that the cmdlet ignores the **Force** parameter when used with the **Static** parameter.
This change:
- Clarifies that the cmdlet ignores both the **View** and **Force** parameters when you use the **Static** parameter, not just **View**.
- Resolves #10779
- Fixes [AB#198702](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/198702)

(GH-10779) Clarify Static param for `Get-Member`

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/5.1/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.2/Microsoft.PowerShell.Core/Get-Help.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.3/Microsoft.PowerShell.Core/Get-Help.md
reference/7.3/Microsoft.PowerShell.Utility/Get-Member.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.4/Microsoft.PowerShell.Core/Get-Help.md
reference/7.4/Microsoft.PowerShell.Utility/Get-Member.md
reference/docfx.json

1/10/2024 PM Publish

---

reference/7.4/Microsoft.PowerShell.Utility/New-Guid.md

Fixes #10796 - Removed invalid parameters

Fixes 10796 - Removed invalid parameters

---

reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Prior to this change, the documentation for the `-OutFile` parameter of the `Invoke-WebRequest` cmdlet incorrectly mentioned retrieving the filename from the Content-Disposition. This functionality isn't implemented. Further, the `-OutFile` parameter for `Invoke-RestMethod` is missing any version-specific note, even though the behavior is the same.
This change:
- Fixes the wording for the `-OutFile` parameter in `Invoke-WebRequest` to remove the non-implemented detail.
- Adds a note to the documentation for `Invoke-RestMethod` about the automatic naming.
- Resolves #10801
- Fixes [AB#200725](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/200725)
[style]: …

(GH-10801) Fix `-OutFile` for web request cmdlets

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Trap.md

Prior to this change, the `about_Trap` topic explained how to use specific exceptions with a `trap` statement, but not how to discover the exception names for that purpose.
This change:
- Adds prose and example to the section "Trapping specific errors" that covers how to get the full name of an exception
- Resolves #10798
- Fixes [AB#200723](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/200723)
> [!NOTE]
> The first commit in this change set addresses syntax, grammar, and formatting issues with the article and is unrelated to the issue the PR addresses except as a maintenance item.
[style]: https://learn.microsoft.com/powershell/scripting/community/contribu …

(GH-10798) Clarify how to find exception names in `about_Trap`

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md
reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.2/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.3/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.4/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/New-Guid.md

1/17/2024 PM Publish

---

reference/docs-conceptual/lang-spec/chapter-02.md

Fixing indentation in `comment:` section
The lack of whitespace before `single-line-comment` in the `comment:` section of this language spec was confusing as a user.

Update `chapter-02.md`: Whitespace fix for readability and accuracy

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Classes.md

In #10615, the section for the `NoRunspaceAfinnity` attribute was erroneously deleted as part of the reorganization of the about_Classes article.
This change:
- Adds back the documentation and examples for the `NoRunspaceAffinity` to the 7.4 and 7.5 versions of about_Classes, as well as a note about the default behavior  in the general limitations section.
- Adds a section and example showing the behavior for corrupted runspaces due to class runspace affinity in the 7.2 and 7.3 versions, and updates the limitations section.
- Resolves #10818
- Fixes [AB#202807](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/202807)
[style]: …

1/23/2024  PM Publish

---

reference/5.1/Microsoft.PowerShell.Utility/New-Guid.md
reference/7.2/Microsoft.PowerShell.Utility/New-Guid.md
reference/7.3/Microsoft.PowerShell.Utility/New-Guid.md
reference/7.4/Microsoft.PowerShell.Utility/New-Guid.md
reference/7.5/Microsoft.PowerShell.Utility/New-Guid.md

Prior to this change, the documentation for the `New-Guid` cmdlet did not specify which GUID version the cmdlet creates. This change:
- Adds a note clarifying the cmdlet creates v4 UUIDs.
- Resolves #10822
- Fixes [AB#203150](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/203150)

(GH-10822) Clarify UUID version for `New-Guid`

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Splatting.md
reference/5.1/Microsoft.PowerShell.Management/New-Item.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Splatting.md
reference/7.2/Microsoft.PowerShell.Management/New-Item.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Splatting.md
reference/7.3/Microsoft.PowerShell.Management/New-Item.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Splatting.md
reference/7.4/Microsoft.PowerShell.Management/New-Item.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Splatting.md
reference/7.5/Microsoft.PowerShell.Management/New-Item.md

1/29/2024 PM Publish

---

reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
reference/docs-conceptual/developer/cmdlet/cmdlet-dynamic-parameters.md
reference/docs-conceptual/developer/cmdlet/how-to-declare-dynamic-parameters.md
reference/docs-conceptual/developer/help/how-to-add-dynamic-parameters-to-a-provider-help-topic.md
reference/docs-conceptual/developer/provider/provider-cmdlet-dynamic-parameters.md
reference/docs-conceptual/developer/provider/provider-cmdlets.md
reference/docs-conceptual/developer/provider/provider-types.md
reference/docs-conceptual/lang-spec/chapter-08.md

* Change keyword to lowercase
* Fix formatting
* fix xrefs
* Fix xrefs

1/31/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Environment_Variables.md

This adjusts some wording to not inappropriately state that environment variables cannot be empty strings when they _can_ be empty strings.

Remove unnecessarily misleading clauses w.r.t. environment variable emptiness (#10850)

---

reference/5.1/Microsoft.PowerShell.Management/Invoke-WmiMethod.md

Fix parameter order examples and formatting
- Fixes [AB#208106](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/208106)
- Fixes #10858

Fixes #10858 - Fix parameter order examples and formatting

---

reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.3/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.4/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.5/Microsoft.PowerShell.Utility/Get-Date.md

Corrects the references in Get-Date documentation from `daylight savings time` to `daylight saving time` 

Get-Date DST Grammar Correction

---

reference/5.1/Microsoft.PowerShell.Management/Rename-ItemProperty.md
reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.2/Microsoft.PowerShell.Management/Rename-ItemProperty.md
reference/7.2/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.3/Microsoft.PowerShell.Management/Rename-ItemProperty.md
reference/7.3/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.4/Microsoft.PowerShell.Management/Rename-ItemProperty.md
reference/7.4/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.5/Microsoft.PowerShell.Management/Rename-ItemProperty.md
reference/7.5/Microsoft.PowerShell.Utility/Get-Date.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md

2/7/2024 PM Publish

---

README.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Preference_Variables.md

02/14 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md

Fixes an error in the hashtable which is used to splat Update-TypeData. Incorrect parameter name, `Name` changed to `MemberName`.

Fixes the embedded parameter name for Update-TypeData

---

reference/5.1/Microsoft.PowerShell.Management/Move-Item.md
reference/7.2/Microsoft.PowerShell.Management/Move-Item.md
reference/7.3/Microsoft.PowerShell.Management/Move-Item.md
reference/7.4/Microsoft.PowerShell.Management/Move-Item.md
reference/7.5/Microsoft.PowerShell.Management/Move-Item.md

Destination no longer supports wildcards
- Fixes [AB#216029](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/216029)
- Fixes #10887

Fixes #10887 - Destination no longer supports wildcards

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Operators.md

Document range limits
- Fixes [AB#216085](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/216085)
- Fixes #10906

Fixes #10906 - Document range limits

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/5.1/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md
reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.2/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md
reference/7.2/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.3/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md
reference/7.3/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.4/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md
reference/7.4/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.5/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md
reference/7.5/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md

Clarify precedence
- Fixes [AB#226436](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/226436)

Clarify precedence

---

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.2/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.3/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.5/Microsoft.PowerShell.Core/About/about_CommonParameters.md

3/26/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.3/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.4/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.5/Microsoft.PowerShell.Management/Get-ChildItem.md

Replace absolute path `C:\Test\*.txt` with relative path `.\*.txt` in the third `Get-ChildItem` example which "displays `.txt` files that are located in the current directory and its subdirectories."
Link to that example in docs of PowerShell 7.4: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.4#example-3-get-child-items-in-the-current-directory-and-subdirectories

Use relative path in a Get-ChildItem example

---

reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md

$WarningPreference also supports 'Break' but that was not clearly specified in the documentation. This PR fixes that by replicating the 'Break' documentation line to $WarningPreference.

Added Break to $WarningPreference

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md

* Document the behavior of bigint math
* fix typo

04/05 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/5.1/PSReadLine/About/about_PSReadLine.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.2/PSReadLine/About/about_PSReadLine.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.3/PSReadLine/About/about_PSReadLine.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.4/PSReadLine/About/about_PSReadLine.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.5/PSReadLine/About/about_PSReadLine.md
reference/docs-conceptual/developer/prog-guide/designing-your-windows-powershell-provider.md

4/8/2024 PM Publish

---

reference/docs-conceptual/developer/cmdlet/strongly-encouraged-development-guidelines.md

Changing 'calc' to 'calculatorapp' to fix non-working command line. Feel free to reach out to me directly on Teams if you have any questions.

Stop-Process syntax needs fixup with app name change

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md

Clarify syntax of substitution expressions
- Fixes [AB#245895](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/245895)
- Fixes #11017

Fixes #11017 - Clarify syntax of substitution expressions

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Telemetry.md

Clarify which env vars need to be set outside of PowerShell
- Fixes [AB#247899](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/247899)
- Fixes #11038
- Fixes #11039

Fixes #11038 - Clarify which env vars need to be set outside of PowerShell

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Environment_Variables.md

Document where to put env definitions for non-Windows platforms

Document where to put env definitions for non-Windows platforms

---

reference/docs-conceptual/lang-spec/chapter-02.md
reference/docs-conceptual/lang-spec/chapter-07.md

1. The BNF grammar is totally broken. This moves forward with a few fixes.
2. Many of the comparison operators were missing
3. Added a few missing`Syntax:` sections 
Please consider this PR on an 'as-is' basis; I believe the changes are a positive contribution which you can use or modify any way you like without my further participation.

Add missing comparsion operators, BNF grammar fixes, markdown formatting

---

reference/docs-conceptual/lang-spec/chapter-07.md

Invalid syntax in use for example here

Fix prefix unary increment operator usage in `Update chapter-07.md`

---

reference/docs-conceptual/lang-spec/chapter-07.md

Please note:
I've only searched inside of `reference/docs-conceptual/lang-spec/chapter-07.md`
Therefore, there might theoretically be other instances of this unary operator use in other chapters.

Fix remaining invalid prefix increment unary operator usage in `chapter-07.md`

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md

Clarify which positional parameters are used in the examples
- Fixes [AB#248693](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/248693)
- Fixes #11048

Fixes #11048 - Clarify which positional parameters are used in the examples

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
reference/5.1/Microsoft.PowerShell.Core/ForEach-Object.md
reference/5.1/Microsoft.PowerShell.Core/Where-Object.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.2/Microsoft.PowerShell.Core/Where-Object.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.3/Microsoft.PowerShell.Core/Where-Object.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.4/Microsoft.PowerShell.Core/Where-Object.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Simplified_Syntax.md
reference/7.5/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.5/Microsoft.PowerShell.Core/Where-Object.md

4/26/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Operators.md

Version 7.3 made an experimental change mainstream that significantly changes how arguments are encapsulated and passed to native commands. While this normally doesn't make a difference there are enough subtle breakages documented on the Web that warrant that this change should be documented in the reference documentation and not just in files describing experimental features.
The change adds a paragraph similar to the one in https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.4#psnativecommandargumentpassing. There are numerous issu reports on the Web where poepe are describing odd behaviors when invoking native commands. For example https://github.com/Azure/azure-storage-azcopy/issues/796.
This change would make it more obvious to …

call operator: reference changes since v7.3 with PSnativeCommandArgumentPassing becoming mainstream

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Update path information for $PSHOME
- Fixes [AB#252884](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/252884)
- Fixes #11076

Fixes #11076 - Update path information for $PSHOME

---

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md

This PR adds many reference links to PowerShell and .NET docs. I'm not sure if the links are correct, please let me know if they should be fixed, I've basically removed `https://learn.microsoft.com/en-us` from them and made them relative hope that's right. 
There are also many formatting changes and also updated the performance tests for __Avoid repeated calls to a function__ to have the same format as the previous tests.
As aside, I feel that __Avoid Write-Host__ should be removed or rewritten. Haven't removed it in this PR but if you feel the same I can open an issue / make a new PR for that. After discussing it in the pwsh Discord the conclusion was that the recommendation is misleading. The usage of static methods from `System.Console` can be confusing specially for new folks and …

Adds reference docs links, formatting and refactoring test performance test

---

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md

This PR explains how to instantiate new custom objects from `OrderedDictionary` and its the performance benefits.
PR #11084 was closed and making this one from a different branch. Also fixed links to make them relative.

Use `OrderedDictionary` to dynamically create new objects

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Wildcards.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Wildcards.md

Filesystem wildcards work differently than for strings
- Fixes [AB#255046](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/255046)
- Fixes #11104

Fixes #11104 - Filesystem wildcards work differently than for strings

---

reference/7.5/Microsoft.PowerShell.Management/Get-Process.md

Updates the example to indicate admins rights are only needed to get the username for processes running as other users. This is a change of behaviour in PowerShell 7.5 which removed the explicit admin check on Windows.
- The change was made as part of https://github.com/PowerShell/PowerShell/pull/21302 and will be included in the next 7.5 preview.

Update Get-Process -IncludeUserName admin msg

---

reference/7.5/Microsoft.PowerShell.Management/Get-Process.md

* Update Get-Process -IncludeUserName admin msg
Updates the example to indicate admins rights are only needed to get the username for processes running as other users. This is a change of behaviour in PowerShell 7.5 which removed the explicit admin check on Windows.
* Rebase and editorial
---------

5/16/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Binding.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Binding.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Binding.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Parameter_Binding.md
reference/docs-conceptual/learn/deep-dives/visualize-parameter-binding.md
reference/docs-conceptual/toc.yml

Add articles about parameter binding
- Fixes [AB#255309](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/255309)

Add articles about parameter binding

---

reference/7.5/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md

5/24/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Security/New-FileCatalog.md
reference/7.2/Microsoft.PowerShell.Security/New-FileCatalog.md
reference/7.4/Microsoft.PowerShell.Security/New-FileCatalog.md
reference/7.5/Microsoft.PowerShell.Security/New-FileCatalog.md

5/29/2024 PM Publish

---

reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.5/Microsoft.PowerShell.Management/Set-Clipboard.md

Adds a word that was omitted as a typo to the description of a flag for the `Set-Clipboard` command.
Marking as draft as I have not verified that this PR adheres to the style guide.

WIP: Add missing word to description of -AsOsc52 flag for Set-Clipboard

---

reference/5.1/CimCmdlets/Get-CimAssociatedInstance.md
reference/5.1/Microsoft.PowerShell.Utility/New-Alias.md
reference/7.2/CimCmdlets/Get-CimAssociatedInstance.md
reference/7.2/Microsoft.PowerShell.Utility/New-Alias.md
reference/7.4/CimCmdlets/Get-CimAssociatedInstance.md
reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.4/Microsoft.PowerShell.Utility/New-Alias.md
reference/7.5/CimCmdlets/Get-CimAssociatedInstance.md
reference/7.5/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.5/Microsoft.PowerShell.Utility/New-Alias.md

5/31/2024 PM Publish

---

reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Prior to this change, the documentation didn't clearly indicate that the converted key-value pairs for requests from the **Body** parameter were URL encoded or point users to how those strings are encoded.
This change:
- Adds a brief note indicating that the cmdlet uses the `WebUtility.UrlEncode()` method and points to that method reference for more information about the encoding behavior.
- Resolves #11155
- Fixes [AB#260889](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/260889)

(GH-11155) Document body-to-query-param encoding

---

reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Prior to this change, the documentation didn't clearly indicate that the converted key-value pairs for requests from the **Body** parameter were URL encoded or point users to how those strings are encoded.
This change:
- Adds a brief note indicating that the cmdlet uses the `WebUtility.UrlEncode()` method and points to that method reference for more information about the encoding behavior.
- Resolves #11155
- Fixes [AB#260889](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/260889)

6/3/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
reference/7.2/Microsoft.PowerShell.Core/Import-Module.md
reference/7.4/Microsoft.PowerShell.Core/Import-Module.md
reference/7.5/Microsoft.PowerShell.Core/Import-Module.md

Add note about limitations of -Force
- Fixes [AB#261944](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/261944)
- Related to MicrosoftDocs/PowerShell-Docs-PSGet#140

Add note about limitations of -Force

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
reference/5.1/Microsoft.PowerShell.Utility/Select-String.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.2/Microsoft.PowerShell.Core/Import-Module.md
reference/7.2/Microsoft.PowerShell.Utility/Select-String.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.4/Microsoft.PowerShell.Core/Import-Module.md
reference/7.4/Microsoft.PowerShell.Utility/Select-String.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.5/Microsoft.PowerShell.Core/Import-Module.md
reference/7.5/Microsoft.PowerShell.Utility/Select-String.md

6/7/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_For.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_For.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_For.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_For.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md

Addresses unified user feedback for several about topics by:
- Fixing an example in `about_Function_Provider`.
- Adding a short example of invoking a newly created function in `about_Functions`.
- Adding a practical example of using a `for` loop in `about_For`.

(UUF) Address feedback on `about_*` topics

---

reference/5.1/Microsoft.PowerShell.Core/About/about_For.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/5.1/Microsoft.PowerShell.Utility/Set-Date.md
reference/5.1/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.2/Microsoft.PowerShell.Core/About/about_For.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.2/Microsoft.PowerShell.Utility/Set-Date.md
reference/7.2/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.4/Microsoft.PowerShell.Core/About/about_For.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.4/Microsoft.PowerShell.Utility/Set-Date.md
reference/7.4/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.5/Microsoft.PowerShell.Core/About/about_For.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.5/Microsoft.PowerShell.Utility/Set-Date.md
reference/7.5/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/docs-conceptual/learn/shell/using-aliases.md

6/10/2024 PM Publish

---

reference/docs-conceptual/learn/deep-dives/everything-about-null.md

Prior to this change, the article _Everything you wanted to know about `$null`_ used the term 'empty `$null`' to describe
`[System.Management.Automation.Internal.AutomationNull]::Value`
However, this terminology isn't clear enough, as both that value and the `$null` value itself can be considered to be 'empty.'
This change:
- Updates to use the terminology 'enumerable null' instead of 'empty `$null`' to describe the value.
- Resolves #11175
- Fixes [AB#260888](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/260888)

(GH-11175) Update terminology to 'enumerable null'

---

reference/docs-conceptual/developer/cmdlet/how-to-validate-an-argument-using-script.md

Prior to this change, the example description in the article _How to validate an argument using a script_ declared that the example validates that the input belongs to a set of possible values. That description belongs to a different example, using `[ValidateSet()]`.
This change:
- Corrects the example description to match the code.
- Fixes [AB#263705](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/263705)

(AB#263705) Fix description for example using `[ValidateScript()]`

---

reference/docs-conceptual/developer/cmdlet/how-to-validate-an-argument-using-script.md
reference/docs-conceptual/learn/deep-dives/everything-about-null.md

Prior to this change, the article 'Everything you wanted to know about `$null`' used the term 'empty `$null`' to describe
`[System.Management.Automation.Internal.AutomationNull]::Value`
However, this terminology isn't clear enough, as both that value and the `$null` value itself can be considered to be 'empty.'
This change:
- Updates to use the terminology 'enumerable null' instead of 'empty `$null`' to describe the value.
- Resolves #11175
- Fixes [AB#260888](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/260888)

6/11/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.4/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.5/Microsoft.PowerShell.Utility/Compare-Object.md

Prior to this change, the document used a self-closing anchor tag to enable quick-linking to the third example.
This change updates the anchor to wrap the text `Example 3` in the heading, per guidance for the platform. This ensures that the remainder of the page isn't a link to the anchor.
- Fixes [AB#263698](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/263698)

(AB#263698) Fix broken anchor in `Compare-Object` docs

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md
reference/5.1/Microsoft.PowerShell.Core/TabExpansion2.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md
reference/7.2/Microsoft.PowerShell.Core/TabExpansion2.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md
reference/7.4/Microsoft.PowerShell.Core/TabExpansion2.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md
reference/7.5/Microsoft.PowerShell.Core/TabExpansion2.md

Add ref content for TabExpansion2
- Fixes [AB#250851](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/250851)

Add ref content for TabExpansion2

---

reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.4/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.5/Microsoft.PowerShell.Core/Enter-PSSession.md

Add note about the interactive nature of Enter-PSSession
- Fixes [AB#264477](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/264477)
- Fixes #11188

Fixes #11188 - Add note about the interactive nature of Enter-PSSession

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.2/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.4/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.5/Microsoft.PowerShell.Core/Enter-PSSession.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md

6/14/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Utility/Get-EventSubscriber.md
reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md
reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/5.1/Microsoft.PowerShell.Utility/Unregister-Event.md
reference/7.2/Microsoft.PowerShell.Utility/Get-EventSubscriber.md
reference/7.2/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.2/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.2/Microsoft.PowerShell.Utility/Unregister-Event.md
reference/7.4/Microsoft.PowerShell.Utility/Get-EventSubscriber.md
reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.4/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.4/Microsoft.PowerShell.Utility/Unregister-Event.md
reference/7.5/Microsoft.PowerShell.Utility/Get-EventSubscriber.md
reference/7.5/Microsoft.PowerShell.Utility/Select-Object.md
reference/7.5/Microsoft.PowerShell.Utility/Send-MailMessage.md
reference/7.5/Microsoft.PowerShell.Utility/Unregister-Event.md
reference/docs-conceptual/community/contributing/product-terminology.md
reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md
reference/docs-conceptual/learn/deep-dives/everything-about-exceptions.md
reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md
reference/docs-conceptual/learn/deep-dives/everything-about-string-substitutions.md

6/20/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md
reference/docs-conceptual/learn/ps101/01-getting-started.md

6/26/2024 PM Publish

---

reference/5.1/PSReadLine/PSConsoleHostReadLine.md
reference/7.2/PSReadLine/PSConsoleHostReadLine.md
reference/7.4/PSReadLine/PSConsoleHostReadLine.md
reference/7.5/PSReadLine/PSConsoleHostReadLine.md

Fix the empty example
- Fixes [AB#273183](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/273183)
- Fixes #11220

Fixes #11220 - Fix the empty example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.2/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.4/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
reference/7.5/Microsoft.PowerShell.Core/About/about_PSCustomObject.md

Add note about case-preserving key names
- Fixes [AB#275461](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/275461)
- Fixes #11227

Fixes #11227 - Add note about case-preserving key names

---

reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md

Added terms to `no-loc` for `CommandWithArgs`
Clarifies example's quoting error when running from `cmd.exe` or `powershell.exe`
- Fixes #11234

fixes #11234 add terms to no-loc and new cmd example 

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Trap.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Trap.md

Improve examples
- Fixes [AB#226439](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/226439)

Improve examples

---

reference/docs-conceptual/security/security-features.md

Add notes about SecureString
- Fixes [AB#250852](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/250852)

Add notes about SecureString

---

reference/docs-conceptual/security/security-features.md
reference/docs-conceptual/whats-new/cmdlet-versions.md

7/8/2024 PM Publish

---

reference/7.2/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.2/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.4/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.5/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.5/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
reference/module/index.md

7/9/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
reference/7.2/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
reference/7.4/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
reference/7.5/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md

Prior to this change, the `Register-ArgumentCompleter` reference didn't indicate that specifying the **CommandName** parameter without the **ParameterName** or **Native** parameters causes the command to behave as if the user specified the `-Native` switch.
This change:
- Clarifies that users should always specify the **ParameterName** parameter when registering an argument completer for a PowerShell command.
- Resolves #11248
- Fixes [AB#281953](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/281953)

(GH-11248) Clarify behavior for `Register-ArgumentCompleter` parameters

---

reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
reference/7.2/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
reference/7.4/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md
reference/7.5/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md

…rs (#11249)
* (GH-11248) Clarify behavior for `Register-ArgumentCompleter` parameters
Prior to this change, the `Register-ArgumentCompleter` reference didn't indicate that specifying the **CommandName** parameter without the **ParameterName** or **Native** parameters causes the command to behave as if the user specified the `-Native` switch.
This change:
- Clarifies that users should always specify the **ParameterName** parameter when registering an argument completer for a PowerShell command.
- Resolves #11248
- Fixes [AB#281953](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/281953)
* (MAINT) Clarify and update `Register-ArgumentCompleter`
This change adds further clarification to various sections of the reference documentation for …

7/10/2024 PM Publish

---

reference/docs-conceptual/install/install-ubuntu.md
reference/includes/alpine-support.md
reference/includes/debian-support.md
reference/includes/rhel-support.md
reference/includes/ubuntu-support.md
reference/includes/windows-support.md

Update list of supported Linux distros
- Fixes [AB#284408](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/284408)
- Fixes #11257

Fixes #11257 - Update list of supported Linux distros

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/5.1/Microsoft.PowerShell.Management/Checkpoint-Computer.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/docs-conceptual/install/install-ubuntu.md
reference/includes/alpine-support.md
reference/includes/debian-support.md
reference/includes/rhel-support.md
reference/includes/ubuntu-support.md
reference/includes/windows-support.md

7/12/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Output.md
reference/5.1/Microsoft.PowerShell.Core/New-ModuleManifest.md
reference/5.1/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Methods.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Remote_Output.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Methods.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Remote_Output.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Remote_Output.md
reference/7.5/Microsoft.PowerShell.Utility/Get-Variable.md
reference/docs-conceptual/lang-spec/chapter-08.md

7/15/2024 PM Publish

---

reference/docs-conceptual/whats-new/unix-support.md

#11242 clarified that `Get-Clipboard` support for macOS was added in 7.0.
unix-support.md had out-of-date info.
(Locally i've been using it on my macbook.)

Fix unix-support: Get-Clipboard now works on macOS

---

reference/docs-conceptual/community/contributing/get-started-writing.md
reference/docs-conceptual/community/contributing/overview.md

Linked fragment doesn't exist anymore.
Same link was fixed in https://github.com/MicrosoftDocs/Contribute/pull/946
Note: Figuring out the cause of the problem was a bit confusing.
- Before [this change](https://github.com/MicrosoftDocs/Contribute/pull/775/files#diff-3fa6f2a8672a06f5c881c8621af9e49f935e65eb99e06ec73d42afe0b1323d7a) that link was to `index.md` but the current page is built from [`index.yml`](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.yml).
- [This edit to index.md](https://github.com/MicrosoftDocs/Contribute/pull/823/files#diff-ffd9be212c6bbe6590c4f303f94fc153ba3e2e2b4432f0c603d65929774ec70b) moved the linked resource to a new page.
[style]: …

Fix dead link to Quick Edits

---

reference/5.1/CimCmdlets/Get-CimAssociatedInstance.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
reference/docs-conceptual/community/contributing/get-started-writing.md
reference/docs-conceptual/community/contributing/overview.md
reference/docs-conceptual/toc.yml
reference/docs-conceptual/whats-new/unix-support.md

7/18/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Management/Debug-Process.md
reference/7.2/Microsoft.PowerShell.Management/Debug-Process.md
reference/7.4/Microsoft.PowerShell.Management/Debug-Process.md
reference/7.5/Microsoft.PowerShell.Management/Debug-Process.md

Fix examples for Debug-Process
- Fixes [AB#288673](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/288673)
- Fixes #11296

Fixes #11296 - Fix examples for Debug-Process

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
reference/5.1/Microsoft.PowerShell.Management/Test-Connection.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
reference/docs-conceptual/samples/Working-with-Registry-Entries.md

7/31/2024 PM Publish

---

reference/docs-conceptual/community/contributing/general-markdown.md

Prior to this change, the contributing guide indicated that the line length should be limited to 100 characters. It clarified that this guideline applies to conceptual articles and cmdlet reference, but didn't indicate that the line length in `about_` topics should be limited to 80 characters.
This change clarifies the guidance.

(MAINT) Clarify line length for about topics

---

reference/docs-conceptual/install/PowerShell-in-Docker.md
reference/includes/alpine-support.md
reference/includes/debian-support.md
reference/includes/rhel-support.md
reference/includes/ubuntu-support.md

Add note about the need to patch docker images
- Fixes [AB#292127](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/292127)

Add note about the need to patch docker images

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/5.1/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/7.2/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/7.4/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/7.5/Microsoft.PowerShell.Utility/Update-TypeData.md

Prior to this change, the documentation didn't include examples of defining the default display property in a `Types.ps1xml` file or with the `Update-TypeData` cmdlet.
This change:
- Adds a new example to the `Update-TypeData` cmdlet showing how a user can define a script property and set it as the default display property in a single command.
- Updates existing examples for line length and readability.
- Updates the example showing **PSStandardMembers** in `about_Types.ps1xml` to include a default display property.
- Fixes [AB#294774](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/294774)
- Resolves #11321
[style]: …

(GH-11321) Add examples for DefaultDisplayProperty

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/5.1/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/7.2/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/7.4/Microsoft.PowerShell.Utility/Update-TypeData.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Types.ps1xml.md
reference/7.5/Microsoft.PowerShell.Utility/Update-TypeData.md

Prior to this change, the documentation didn't include examples of defining the default display property in a `Types.ps1xml` file or with the `Update-TypeData` cmdlet.
This change:
- Adds a new example to the `Update-TypeData` cmdlet showing how a user can define a script property and set it as the default display property in a single command.
- Updates existing examples for line length and readability.
- Updates the example showing **PSStandardMembers** in `about_Types.ps1xml` to include a default display property.
- Fixes [AB#294774](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/294774)
- Resolves #11321
[style]: …

8/7/2024 AM Publish

---

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.4/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.5/Microsoft.PowerShell.Management/Get-ChildItem.md

Fix typo
- Fixes [AB#295229](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/295229)
- Fixes #11325

Fixes #11325 - Fix typo

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md

Prior to this change, the documentation for the built-in `help` function in `about_Built-in_Functions` incorrectly stated that PowerShell always uses `more` for the pager on Windows and the `PAGER` environment variable on non-Windows systems.
This change:
- Clarifies that PowerShell uses a default pager for both Windows (`more`) and non-Windows (`less`) systems.
- Clarifies that when the `PAGER` environment variable is defined, PowerShell uses that command instead of the default pager on both Windows and non-Windows systems.
- Fixes [AB#297346](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/297346)
- Resolves #11332
[style]: …

(GH-11332) Fix pager info for built-in `help` function

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md

Prior to this change, the documentation for the built-in `help` function in `about_Built-in_Functions` incorrectly stated that PowerShell always uses `more` for the pager on Windows and the `PAGER` environment variable on non-Windows systems.
This change:
- Clarifies that PowerShell uses a default pager for both Windows (`more`) and non-Windows (`less`) systems.
- Clarifies that when the `PAGER` environment variable is defined, PowerShell uses that command instead of the default pager on both Windows and non-Windows systems.
- Fixes [AB#297346](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/297346)
- Resolves #11332
[style]: …

8/15/2024 PM Publish

---

reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-CliXml.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertTo-CliXml.md

Add docs for new CliXml commands
- Fixes [AB#296918](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/296918)
- Fixes #10773

Fixes #10773 - Add docs for new CliXml commands

---

reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.4/Microsoft.PowerShell.Utility/Write-Host.md
reference/7.4/Microsoft.PowerShell.Utility/Write-Progress.md
reference/7.5/Microsoft.PowerShell.Utility/Write-Progress.md

8/26/2024 PM Publish

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/PowerShell-on-ARM.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-other-linux.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/install/microsoft-update-faq.yml

Fix anchors and ms.date in setup articles
- Fixes [AB#302636](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/302636)

Fix anchors and ms.date in setup articles

---

reference/7.2/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.2/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.4/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.5/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.5/Microsoft.PowerShell.Management/Set-Clipboard.md

Add macOS dependencies
- Fixes [AB#304080](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304080)

Add macOS dependencies

---

reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
reference/7.2/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.2/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
reference/7.4/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
reference/7.5/Microsoft.PowerShell.Management/Get-Clipboard.md
reference/7.5/Microsoft.PowerShell.Management/Set-Clipboard.md

8/30/2024 PM Publish

---

reference/7.4/Microsoft.PowerShell.Archive/Compress-Archive.md
reference/7.4/Microsoft.PowerShell.Archive/Expand-Archive.md
reference/7.4/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md

Add note about supported formats.
- Fixes [AB#304267](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304267)

Add note about supported formats.

---

reference/5.1/Microsoft.PowerShell.Utility/Wait-Debugger.md
reference/7.2/Microsoft.PowerShell.Utility/Wait-Debugger.md
reference/7.4/Microsoft.PowerShell.Utility/Wait-Debugger.md
reference/7.5/Microsoft.PowerShell.Utility/Wait-Debugger.md

Add debug example
- Fixes [AB#304273](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304273)

Add debug example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md

Improve description of Measure-Object example
- Fixes [AB#304258](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304258)

Improve description of Measure-Object example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Operators.md

Update description of -f operator syntax
- Fixes [AB#304262](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304262)

Update description of -f operator syntax

---

reference/docs-conceptual/learn/shell/creating-profiles.md

Tweak prompt logic in example profile
- Fixes [AB#304274](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304274)

Tweak prompt logic in example profile

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/docs-conceptual/learn/shell/creating-profiles.md

9/4/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Environment_Variables.md

Convert bold to backtick to avoid over localization
- Fixes [AB#304269](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304269)

Convert bold to backtick to avoid over localization

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Path_Syntax.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Path_Syntax.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Path_Syntax.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Path_Syntax.md

Add note about Win32 File namespaces
- Fixes [AB#304281](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304281)

Add note about Win32 File namespaces

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

Prior to this change, the `about_Quoting_Rules` topic document didn't indicate that PowerShell treats smart/typographic quotation marks as normal/programmer quotation marks, making them subject to the same escaping and quoting behaviors.
This change:
- Adds a note about smart quotation marks and guidance to avoid using them to enclose strings.
- Adds an example of escaping smart quotation marks.
- Fixes [AB#309820](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/309820)
- Resolves #11401

(GH-11401) Clarify smart quotes behavior/guidance

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

Prior to this change, the `about_Quoting_Rules` topic document didn't indicate that PowerShell treats smart/typographic quotation marks as normal/programmer quotation marks, making them subject to the same escaping and quoting behaviors.
This change:
- Adds a note about smart quotation marks and guidance to avoid using them to enclose strings.
- Adds an example of escaping smart quotation marks.
- Fixes [AB#309820](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/309820)
- Resolves #11401

9/9/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md

Fix minor typo - missing smart quote
- Fixes [AB#310191](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/310191)
- Fixes #11404

Fixes #11404 - Fix minor typo - missing smart quote

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md

9/10/2024 PM Publish

---

reference/docs-conceptual/developer/cmdlet/users-requesting-confirmation.md
reference/docs-conceptual/security/app-control/application-control.md
reference/docs-conceptual/security/app-control/how-to-use-wdac.md
reference/docs-conceptual/security/app-control/how-wdac-works.md
reference/docs-conceptual/security/overview.yml
reference/docs-conceptual/security/security-features.md

Fix statement about logic of ConfirmImpact
- Fixes [AB#316719](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/316719)
- Fixes #11419

Fixes #11419 - Fix statement about logic of ConfirmImpact

---

reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md

Update -Force example
- Fixes [AB#316730](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/316730)
- Fixes #11418

Fixes #11418 - Update -Force example

---

reference/docs-conceptual/learn/experimental-features.md

Documents the new experiemental feature PSSerializeJSONLongEnumAsNumber that aligns the serialization behaviour of enums based on long/ulong with the other base types.
- PR adding this feature is https://github.com/PowerShell/PowerShell/pull/20999

Document PSSerializeJSONLongEnumAsNumber

---

reference/docs-conceptual/developer/cmdlet/users-requesting-confirmation.md
reference/docs-conceptual/learn/deep-dives/everything-about-shouldprocess.md
reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/security/app-control/application-control.md
reference/docs-conceptual/security/app-control/how-to-use-wdac.md
reference/docs-conceptual/security/app-control/how-wdac-works.md
reference/docs-conceptual/security/security-features.md

9/24/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md

… name  (#11427)
* Update Add-Computer.md
Add an example to rename and domain join in one operation and use the Domain Join options parameter correctly.
* Editorial changes
---------

9/25/2024 PM Publish

---

reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Telemetry.md
reference/7.5/Microsoft.PowerShell.Management/Convert-Path.md
reference/7.5/Microsoft.PowerShell.Management/Resolve-Path.md
reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md

Update release information for 7.5-p5
- Fixes [AB#316769](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/316769)
- Fixes #10755

Update release information for 7.5-p5

---

reference/7.2/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/7.4/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
reference/7.5/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md

Text correction in ModuleLogging section of about_PowerShell_Config.
Correction is made in documentations for PowerShell 7.5, 7.4, 7.2.

Text correction in ModuleLogging section of about_PowerShell_Config

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

Added missing 's' so Window Nano Server became Windows Nano Server.
Change is made in documentations for PowerShell 7.5, 7.4, 7.2, 5.1.

Fixed typo Window Nano Server should be Windows Nano Server in about_Execution_Policies

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

I did some research about Execution Policies and was unable to find the configuration in Windows Registry as documentation pointed me. Then i found PowerShell is using configuration files now to be portable so i made some changes to documentation.
Change is made in documentations for PowerShell 7.5, 7.4, 7.2.

Replaced Registry with configuration files in about_Execution_Policies

---

reference/7.4/Microsoft.PowerShell.Utility/Start-Sleep.md
reference/7.5/Microsoft.PowerShell.Utility/Start-Sleep.md

10/9/2024 PM Publish

---

reference/docs-conceptual/security/app-control/application-control.md

Add note about temp files created to detect AppLocker
- Fixes [AB#322985](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/322985)
- Fixes #11450

Fixes #11454 - Add note about temp files created to detect AppLocker

---

reference/5.1/Microsoft.PowerShell.LocalAccounts/Enable-LocalUser.md

Improve the description of an example.
- Fixes [AB#323449](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/323449)
- Fixes #11456

Fixes #11456 - Improve the description of an example.

---

reference/docs-conceptual/learn/shell/creating-profiles.md

Fixes a minor typo on the "[Customizing your shell environment](https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/creating-profiles?view=powershell-7.4#how-to-create-your-personal-profile)" page.
- Fixes #11461

Fixes #11461 - Fix repetition typo on "Customizing your shell environment" page

---

.markdownlint.yaml
reference/docs-conceptual/learn/shell/creating-profiles.md

10/11/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Management/Start-Service.md
reference/7.2/Microsoft.PowerShell.Management/Start-Service.md
reference/7.4/Microsoft.PowerShell.Management/Start-Service.md
reference/7.5/Microsoft.PowerShell.Management/Start-Service.md

10/15/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md

add clean block to first example
As this is 7.4 doc, the clean block should be in the example as well

Update about_Functions_Advanced_Methods.md to include clean block in example as well

---

reference/docs-conceptual/security/app-control/how-wdac-works.md

It's no longer called WDAC or Windows Defender Application Control. It's called App Control for Business. Microsoft has updated the relevant docs to use the correct name, i fixed this document to be aligned with them.
https://learn.microsoft.com/en-us/windows/security/application-security/application-control/app-control-for-business/appcontrol

Corrected the names referring to WDAC to use App Control

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

Add note to -PassThru
- Fixes [AB#329702](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/329702)
- Fixes #11483

Fixes #11483 - Add note to -PassThru

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Signing.md

Add list of file types checked
- Fixes [AB#335090](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/335090)

Add list of file types checked

---

reference/5.1/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/7.2/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/7.4/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/7.5/Microsoft.PowerShell.Utility/Set-TraceSource.md

In all versions (**5.1**, **7.2**, **7.4**, **7.5**) i changed mentioned `Set-TraceSource` default value for parameter `-Option`. In current documentation is stated that the default value is `All` but is actually `None`. 
I found this when i executed cmdlet `Set-TraceSource -Name * -PSHost` without explicit value for parameter `-Option` (expected it will be `All` by default as stated in documentation) but no tracing information was shown when i executed further commands. If i explicitly set the `-Option` parameter everything is fine.
Here is link for **7.4** where doc says that the default value is `All` https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/set-tracesource?view=powershell-7.4#-option.
**I went to explore the source code to be sure and it seems …

Set-TraceSource parameter -Option has default value 'None' and not 'All'.

---

reference/docs-conceptual/overview.md

Fix broken link to VMWare PowerCLI

Fix broken link to VMWare PowerCLI

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/5.1/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/7.2/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/7.2/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/7.4/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
reference/7.5/Microsoft.PowerShell.Utility/Set-TraceSource.md
reference/docs-conceptual/overview.md

10/30/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.2/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.4/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.5/Microsoft.PowerShell.Management/Copy-Item.md

Fix note in Example 2
- Fixes [AB#338106](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/338106)
- Fixes #11505

Fixes #11505 - Fix note in Example 2

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Transactions.md
reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.2/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.4/Microsoft.PowerShell.Management/Copy-Item.md
reference/7.5/Microsoft.PowerShell.Management/Copy-Item.md
reference/docs-conceptual/community/2024-updates.md
reference/docs-conceptual/community/hall-of-fame.md

11/4/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Management/New-Item.md
reference/7.2/Microsoft.PowerShell.Management/New-Item.md
reference/7.4/Microsoft.PowerShell.Management/New-Item.md
reference/7.5/Microsoft.PowerShell.Management/New-Item.md

Apply code block syntax to parameter values 

---

reference/5.1/CimCmdlets/Set-CimInstance.md
reference/5.1/Microsoft.PowerShell.Core/Add-History.md
reference/5.1/Microsoft.PowerShell.Core/Add-PSSnapin.md
reference/5.1/Microsoft.PowerShell.Core/Import-Module.md
reference/5.1/Microsoft.PowerShell.Security/Set-Acl.md
reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/5.1/Microsoft.PowerShell.Utility/Out-GridView.md
reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs.md
reference/5.1/PSScheduledJob/Disable-ScheduledJob.md
reference/5.1/PSScheduledJob/Enable-ScheduledJob.md
reference/5.1/PSScheduledJob/Set-JobTrigger.md
reference/5.1/PSScheduledJob/Set-ScheduledJob.md
reference/5.1/PSScheduledJob/Set-ScheduledJobOption.md
reference/7.4/CimCmdlets/Set-CimInstance.md
reference/7.4/Microsoft.PowerShell.Core/Add-History.md
reference/7.4/Microsoft.PowerShell.Core/Import-Module.md
reference/7.4/Microsoft.PowerShell.Security/Set-Acl.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/Out-GridView.md
reference/7.5/CimCmdlets/Set-CimInstance.md
reference/7.5/Microsoft.PowerShell.Core/Add-History.md
reference/7.5/Microsoft.PowerShell.Core/Import-Module.md
reference/7.5/Microsoft.PowerShell.Security/Set-Acl.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.5/Microsoft.PowerShell.Utility/Out-GridView.md
reference/docs-conceptual/samples/Manipulating-Items-Directly.md

This pull requests fixes every instance of -Passthru to proper CamelCase of -PassThru
This excludes the 7.2 sub folder as its being removed

Fixing Passthru to proper PascalCase

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Prior to this change, the article for installing PowerShell on Windows used a single codeblock to show readers how to install PowerShell and PowerShell preview with WinGet by ID. On the webpage, this results in a single codeblock with a copy button. If a reader uses the copy button and pastes the copied code into their terminal, both commands will run. If a user wanted to install only one edition, they need to edit the copied code to remove the line they don't want.
This change:
- Separates the codeblocks for installing PowerShell with WinGet and specifying the ID parameter for PowerShell and PowerShell preview, so that readers may copy either codeblock and paste into their terminal instead of copying both.
- Fixes #11534
- Fixes …

(GH-11534) Separate codeblocks for installing with WinGet by ID

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Prior to this change, the article for installing PowerShell on Windows used a single codeblock to show readers how to install PowerShell and PowerShell preview with WinGet by ID. On the webpage, this results in a single codeblock with a copy button. If a reader uses the copy button and pastes the copied code into their terminal, both commands will run. If a user wanted to install only one edition, they need to edit the copied code to remove the line they don't want.
This change:
- Separates the codeblocks for installing PowerShell with WinGet and specifying the ID parameter for PowerShell and PowerShell preview, so that readers may copy either codeblock and paste into their terminal instead of copying both.
- Fixes #11534
- Fixes …

11/15/2024 PM Publish

---

reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

`-MaximumRetryCount`'s description stated that `-RetryIntervalSec` specified the number of
retries, which is incorrect. I modified the description accordingly.

Fix -MaximumRetryCount description in Invoke-WebRequest.md

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md

Update for 7.5-rc.1 release
- Fixes [AB#330149](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/330149)

Update for 7.5-rc.1 release

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
reference/module/index.md

11/22/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md
reference/7.4/Microsoft.PowerShell.Core/Enable-PSRemoting.md
reference/7.5/Microsoft.PowerShell.Core/Enable-PSRemoting.md

Remove outdated information add links to how-to
- Fixes [AB#346842](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/346842)
- Fixes #11548

Fixes #11548 - Remove outdated information add links to how-to

---

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md

Update the installation verification command for powershell-lts on macOS, replacing `pwsh` with the correct `pwsh-lts`.

Fix powershell-lts verification command

---

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md

12/5/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md

Add some clarity and missing words to `about_Regular_Expressions.md`.

Fix about_Regular_Expressions.md

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/docs-conceptual/security/remoting/WinRM-Security.md

12/9/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Conversion.md

Add clarifications from mklement0
- Fixes [AB#353548](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/353548)
- Fixes #11571

Fixes #11571 - Add clarifications from mklement0

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Conversion.md

More updates
- Fixes [AB#353651](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/353651)
- Fixes #11571

Fixes #11571 - More updates

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Conversion.md

12/10/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md

12/11/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Utility/Format-Custom.md
reference/5.1/Microsoft.PowerShell.Utility/Format-List.md
reference/5.1/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.4/Microsoft.PowerShell.Utility/Format-Custom.md
reference/7.4/Microsoft.PowerShell.Utility/Format-List.md
reference/7.4/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.5/Microsoft.PowerShell.Utility/Format-Custom.md
reference/7.5/Microsoft.PowerShell.Utility/Format-List.md
reference/7.5/Microsoft.PowerShell.Utility/Format-Wide.md

Fixes [AB#354151](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/354151) - Added pre-sorting required to groupby parameter description

Added pre-sorting required to groupby param.

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/PowerShell-on-ARM.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/includes/alpine-support.md

Fix version info in install docs
- Fixes [AB#354181](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/354181)
- Fixes #11581
- Fixes #11582

Fixes #11581 - Fix version info in install docs

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Ref.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Ref.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Ref.md

This PR adds a new section, entitled "Relationship between `[ref]` and `System.Management.Automation.PSReference`" to the `about_Ref.md` file for three versions of PowerShell: 7.5, 7.4, and 5.1. This section discusses the fact that PowerShell doesn't treat `[ref]` and `[System.Management.Automation.PSReference]` (a.k.a. `[PSReference]`) semantically the same.
Additionally, this PR changes a "note" box to an "important" box because of the information in that box is "required for user success." See [Markdown best practices][1] for their differences.
Minor syntactic changes were made by the Authoring Tools' linter.
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powersh …

about_Ref.md: Relationship between [ref] and [PSReference]

---

reference/5.1/Microsoft.PowerShell.Utility/Write-Output.md
reference/7.4/Microsoft.PowerShell.Utility/Write-Output.md
reference/7.5/Microsoft.PowerShell.Utility/Write-Output.md

Added `-NoEnumerate` switch to example in `Write-Output` cmdlet documentation (5.1, 7.4, 7.5) because without that switch it didn't make sense in that context. 

Updated Write-Output cmdlet documentations (5.1, 7.4, 7.5) because -NoEnumerate switch was missing in example.

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Ref.md
reference/5.1/Microsoft.PowerShell.Utility/Format-Custom.md
reference/5.1/Microsoft.PowerShell.Utility/Format-List.md
reference/5.1/Microsoft.PowerShell.Utility/Format-Wide.md
reference/5.1/Microsoft.PowerShell.Utility/Write-Output.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Ref.md
reference/7.4/Microsoft.PowerShell.Utility/Format-Custom.md
reference/7.4/Microsoft.PowerShell.Utility/Format-List.md
reference/7.4/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.4/Microsoft.PowerShell.Utility/Write-Output.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Ref.md
reference/7.5/Microsoft.PowerShell.Utility/Format-Custom.md
reference/7.5/Microsoft.PowerShell.Utility/Format-List.md
reference/7.5/Microsoft.PowerShell.Utility/Format-Wide.md
reference/7.5/Microsoft.PowerShell.Utility/Write-Output.md
reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/PowerShell-on-ARM.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/includes/alpine-support.md

12/12/2024 PM Publish

---

reference/docs-conceptual/install/install-alpine.md

Update alpine 3.20 dependencies for install script
- Fixes [AB#355956](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/355956)
- Fixes #11589

Fixes #11589 - Update alpine 3.20 dependencies for install script

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Ref.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Ref.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Ref.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/docs-conceptual/install/install-alpine.md

12/16/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md

12/17/2024 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Break.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Break.md

Fix typo
- Fixes [AB#358441](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/358441)
- Fixes #11601

Fixes #11601 - Fix typo

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Variables.md

Add information about numeric parameter names
- Fixes [AB#359338](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/359338)
- Fixes #11606

Fixes #11606 - Add information about numeric parameter names

---

.github/ISSUE_TEMPLATE/01-article.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
reference/docs-conceptual/community/contributing/get-started-writing.md

Update repository's meta files
- Fixes [AB#359433](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/359433)

Update repository's meta files

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Properties.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Arrays.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Properties.md

Clarify facts about intrinsic properties Count and Length
- Fixes [AB#359487](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/359487) - Fixes #11613
- Fixes [AB#359488](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/359488) - Fixes #11614
- Fixes [AB#359489](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/359489) - Fixes #11615

Fixes #11615 - Clarify facts about intrinsic properties Count and Length

---

reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalGroup.md

Update character length limits for Name and Description
- Fixes [AB#359538](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/359538)
- Fixes #11630

Fixes #11630 - Update character length limits for Name and Description

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md

More feedback on numeric parameters
- Fixes [AB#359539](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/359539)
- Fixes #11606

Fixes #11606 - More feedback on numeric parameters

---

reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.4/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.5/Microsoft.PowerShell.Host/Start-Transcript.md

Fix example 3
- Fixes [AB#360015](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360015)
- Fixes #11628

Fixes #11628 - Fix example 3

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md
reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalGroup.md
reference/5.1/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.4/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.4/Microsoft.PowerShell.Utility/Write-Information.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.5/Microsoft.PowerShell.Host/Start-Transcript.md
reference/7.5/Microsoft.PowerShell.Utility/Write-Information.md
reference/docs-conceptual/developer/cmdlet/parameter-attribute-declaration.md

1/6/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md

Add example for finally block
- Fixes [AB#360238](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360238)

Add example for finally block

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Signing.md

Add note about installing trusted certs
- Fixes [AB#360233](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360233)

Add note about installing trusted certs

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md

Backtick variables to prevent overlocalization
- Fixes [AB#360227](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360227)

Backtick variables to prevent overlocalization

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Jobs.md

Fix typo
- Fixes [AB#360531](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360531)
- Fixes #11639

Fixes #11639 - Fix typo

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Jobs.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Signing.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md

1/7/2025 PM Publish

---

reference/docs-conceptual/lang-spec/chapter-01.md
reference/docs-conceptual/lang-spec/chapter-02.md
reference/docs-conceptual/lang-spec/chapter-03.md
reference/docs-conceptual/lang-spec/chapter-04.md
reference/docs-conceptual/lang-spec/chapter-05.md
reference/docs-conceptual/lang-spec/chapter-06.md
reference/docs-conceptual/lang-spec/chapter-07.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/lang-spec/chapter-09.md
reference/docs-conceptual/lang-spec/chapter-10.md
reference/docs-conceptual/lang-spec/chapter-11.md
reference/docs-conceptual/lang-spec/chapter-12.md
reference/docs-conceptual/lang-spec/chapter-13.md
reference/docs-conceptual/lang-spec/chapter-14.md
reference/docs-conceptual/lang-spec/chapter-15.md
reference/docs-conceptual/lang-spec/chapter-16.md
reference/docs-conceptual/learn/ps101/04-pipelines.md
reference/includes/language-spec.md

1/8/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_PSConsoleHostReadLine.md
reference/5.1/PSReadLine/PSConsoleHostReadLine.md
reference/7.4/Microsoft.PowerShell.Core/About/about_PSConsoleHostReadLine.md
reference/7.4/PSReadLine/PSConsoleHostReadLine.md
reference/7.5/Microsoft.PowerShell.Core/About/about_PSConsoleHostReadLine.md
reference/7.5/PSReadLine/PSConsoleHostReadLine.md

Fix typos and add links for PSConsoleHostReadline
- Fixes [AB#361131](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/361131)
- Fixes #11654

Fixes #11654 - Fix typos and add links for PSConsoleHostReadline

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comments.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comments.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Comments.md

Fix minor typos in [about_Comments](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comments).

Fix about_Comments typos

---

reference/docs-conceptual/security/preventing-script-injection.md

This section about "Use the EscapeSingleQuotedStringContent() method" is only relevant in the context of the "Wrap strings in single quotes" just above so it should be a sub-heading of it instead of a same-level heading following it
See how the previous ends "A malicious user can still use single quotes in their input to inject code." and this one begins "To protect against the user inserting their own single quote characters [...]"

Lower sub-heading since it's related to previous heading

---

reference/docs-conceptual/dev-cross-plat/resolving-dependency-conflicts.md
reference/docs-conceptual/dev-cross-plat/vscode/understanding-file-encoding.md

StackOverflow -> Stack Overflow

1/16/2025 PM Publish

---

reference/docs-conceptual/how-to-use-docs.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md

Add 7.6 to support docs
- Fixes [AB#363377](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/363377)
- Fixes [AB#363444](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/363444)

Add 7.6 to support docs

---

.github/ISSUE_TEMPLATE/01-article.yml
README.md
reference/docs-conceptual/community/contributing/get-started-writing.md

Update repo config files for 7.6
- Fixes [AB#363380](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/363380)
- Fixes [AB#363382](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/363382)

Update repo config files for 7.6

---

reference/docs-conceptual/toc.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-76.md
reference/docs-conceptual/whats-new/cmdlet-versions.md
reference/docs-conceptual/whats-new/overview.yml

Add 7.6 release notes
- Fixes [AB#363379](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/363379)

Add 7.6 release notes

---

.github/ISSUE_TEMPLATE/01-article.yml
README.md
reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.5/CimCmdlets/Get-CimAssociatedInstance.md
reference/7.5/CimCmdlets/Get-CimInstance.md
reference/7.5/CimCmdlets/Get-CimSession.md
reference/7.5/CimCmdlets/Invoke-CimMethod.md
reference/7.5/CimCmdlets/New-CimInstance.md
reference/7.5/CimCmdlets/New-CimSession.md
reference/7.5/CimCmdlets/New-CimSessionOption.md
reference/7.5/CimCmdlets/Register-CimIndicationEvent.md
reference/7.5/CimCmdlets/Remove-CimInstance.md
reference/7.5/CimCmdlets/Remove-CimSession.md
reference/7.5/CimCmdlets/Set-CimInstance.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.6/Microsoft.PowerShell.Core/Get-Command.md
reference/7.6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/docfx.json
reference/docs-conceptual/community/contributing/get-started-writing.md
reference/docs-conceptual/how-to-use-docs.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
reference/docs-conceptual/toc.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-76.md
reference/docs-conceptual/whats-new/cmdlet-versions.md
reference/docs-conceptual/whats-new/overview.yml

1/17/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

This adds the missing `-iin`, `-cin`, `-inotin` and `-cnotin` operators to the list in `about_Comparison_Operators`.

Add missing containment operators to list

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Hash_Tables.md

Fix index example
- Fixes [AB#363629](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/363629)
- Fixes #11701

Fixes #11701 - Fix index example

---

reference/5.1/CimCmdlets/CimCmdlets.md
reference/5.1/CimCmdlets/Export-BinaryMiLog.md
reference/5.1/CimCmdlets/Get-CimAssociatedInstance.md
reference/5.1/CimCmdlets/Get-CimInstance.md
reference/5.1/CimCmdlets/Get-CimSession.md
reference/5.1/CimCmdlets/Import-BinaryMiLog.md
reference/5.1/CimCmdlets/Invoke-CimMethod.md
reference/5.1/CimCmdlets/New-CimInstance.md
reference/5.1/CimCmdlets/New-CimSession.md
reference/5.1/CimCmdlets/New-CimSessionOption.md
reference/5.1/CimCmdlets/Register-CimIndicationEvent.md
reference/5.1/CimCmdlets/Remove-CimInstance.md
reference/5.1/CimCmdlets/Remove-CimSession.md
reference/5.1/CimCmdlets/Set-CimInstance.md

Aligning the changes done to 7.5 across 5.1 with:
- Reducing MD013 rules findings
- Align PS style for spaces and caps

Markdown and PS Styles

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Classes_Properties.md

This change fixes #11696 by adding the missing text explaining how static properties defined on classes implemented in PowerShell are not immutable and can be overriden.

(GH-11696) Fix note about static property mutablity

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md

This fixes a typo in [`about_Type_Accelerators`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_type_accelerators#using-type-accelerators).

Fix `about_Type_Accelerators` typo

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Type_Accelerators.md
reference/docs-conceptual/community/community-support.md
reference/index.yml

1/22/2025 PM Publish

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
reference/docs-conceptual/install/community-support.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-other-linux.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/install/microsoft-update-faq.yml
reference/docs-conceptual/learn/experimental-features.md
reference/docs-conceptual/learn/shell/running-commands.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-72.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md

Update release notes and setup for new versions
- Fixes [AB#365172](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/365172)

Update release notes and setup for new versions

---

reference/5.1/PSReadLine/About/about_PSReadLine_Release_Notes.md
reference/7.4/PSReadLine/About/about_PSReadLine_Release_Notes.md
reference/7.5/PSReadLine/About/about_PSReadLine_Release_Notes.md
reference/7.6/PSReadLine/About/about_PSReadLine_Release_Notes.md

Update PSReadLine release notes
- Fixes [AB#365183](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/365183)

Update PSReadLine release notes

---

reference/docs-conceptual/learn/deep-dives/everything-about-null.md

* Update everything-about-null.md
Add space at end of line
* Clarify null value output in PowerShell
Wrapped output in single quotes because we don't allow trailing spaces in our documents.
---------

1/24/2025 PM Publish

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/community-support.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-other-linux.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/security/remoting/WSMan-Remoting-in-PowerShell.md
reference/includes/latest-install.md

Update install docs for 7.5
- Fixes [AB#366378](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/366378)
- Fixes #11733

Fixes #11733 - Update install docs for 7.5

---

.vscode/cspell/psdocs/dictionaries/psdocs.txt
reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md

* 7.5 what's new
* Add info about UUID v7 from .NET 9
* Fix some code indentation
* General
* Fix WinGet casing some places
* Add a missing link to current release of PowerShell

7.5 whats new: Add info about UUID v7 + correct WinGet casing

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md

Add breaking change note
- Related to PowerShell/PowerShell#24749

Add breaking change note

---

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md

Update 7.5 urls
- Fixes [AB#367278](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/367278)
- Fixes #11744

Fixes #11744 - Update 7.5 urls

---

.vscode/cspell/psdocs/dictionaries/psdocs.txt
reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md

01/29/2025 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Scopes.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Scopes.md

Mention scope modifiers
- Fixes [AB#368167](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/368167)
- Fixes #11761

Fixes #11761 - Mention scope modifiers

---

reference/7.4/Microsoft.PowerShell.Management/Restart-Computer.md
reference/7.5/Microsoft.PowerShell.Management/Restart-Computer.md
reference/7.6/Microsoft.PowerShell.Core/Get-Command.md
reference/7.6/Microsoft.PowerShell.Management/Restart-Computer.md
reference/7.6/Microsoft.PowerShell.Utility/Get-Error.md
reference/7.6/Microsoft.PowerShell.Utility/Get-EventSubscriber.md
reference/7.6/Microsoft.PowerShell.Utility/Get-PSCallStack.md
reference/7.6/Microsoft.PowerShell.Utility/Get-Unique.md
reference/docfx.json
reference/docs-conceptual/community/2025-updates.md

02/04/2025 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
reference/7.6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md
reference/7.6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md

2/5/2025 PM Publish

---

reference/docs-conceptual/learn/ps101/09-functions.md

Fix typo
- Fixes [AB#370977](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/370977)
- Fixes #11779

Fixes #11779 - Fix typo

---

reference/7.5/Microsoft.PowerShell.Utility/Add-Member.md
reference/7.5/Microsoft.PowerShell.Utility/Add-Type.md
reference/7.5/Microsoft.PowerShell.Utility/Clear-Variable.md
reference/7.5/Microsoft.PowerShell.Utility/Compare-Object.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-Csv.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-Json.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-Markdown.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-SddlString.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertTo-Csv.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertTo-Html.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertTo-Json.md
reference/7.5/Microsoft.PowerShell.Utility/ConvertTo-Xml.md
reference/7.5/Microsoft.PowerShell.Utility/Debug-Runspace.md
reference/7.5/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.md
reference/7.5/Microsoft.PowerShell.Utility/Disable-RunspaceDebug.md
reference/7.5/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.md
reference/7.5/Microsoft.PowerShell.Utility/Enable-RunspaceDebug.md

2/10/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

Update policy navigation tree
- Fixes [AB#373421](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/373421)
- Fixes #11796

Fixes #11796 - Update policy navigation tree

---

reference/5.1/CimCmdlets/Get-CimClass.md
reference/5.1/CimCmdlets/Get-CimInstance.md
reference/5.1/CimCmdlets/Get-CimSession.md
reference/5.1/CimCmdlets/Invoke-CimMethod.md
reference/7.4/CimCmdlets/Get-CimClass.md
reference/7.4/CimCmdlets/Get-CimInstance.md
reference/7.4/CimCmdlets/Get-CimSession.md
reference/7.4/CimCmdlets/Invoke-CimMethod.md
reference/7.5/CimCmdlets/Get-CimClass.md
reference/7.5/CimCmdlets/Get-CimInstance.md
reference/7.5/CimCmdlets/Get-CimSession.md
reference/7.5/CimCmdlets/Invoke-CimMethod.md
reference/7.6/CimCmdlets/Get-CimClass.md
reference/7.6/CimCmdlets/Get-CimInstance.md
reference/7.6/CimCmdlets/Get-CimSession.md
reference/7.6/CimCmdlets/Invoke-CimMethod.md

2/17/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md

There is a bug in Windows PowerShell 5.1 with the Start-Transcript cmdlet where it writes Information messages to the transcript file when it shouldn't, and doesn't write them when it should. There is a GitHub repo to easily reproduce this issue [here](https://github.com/deadlydog/PowerShell.Experiment.BugReproductions/blob/main/src/5.1/Start-TranscriptInvertsWrite-Information/ReadMe.md).
This change adds a note to the documentation to make the unexpected behaviour more well-known.

docs: Mention PS 5.1 bug where Start-Transcript inverts when it should log Write-Information messages

---

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md

There is a bug in Windows PowerShell 5.1 with the Get-ChildItem cmdlet where it ignores the `-Depth` parameter when it is used with the `-Include` parameter. There is a GitHub repo to easily reproduce this issue [here](https://github.com/deadlydog/PowerShell.Experiment.BugReproductions/blob/main/src/5.1/Get-ChildItemIgnoresDepthParameter/ReadMe.md).
This change adds a note to the documentation to make the unexpected behaviour more well-known.

docs: Mention PS 5.1 bug where Get-ChildItem ignores -Depth parameter when used with -Include

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Break.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Break.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/lang-spec/chapter-15.md
reference/docs-conceptual/learn/deep-dives/everything-about-switch.md

Prior to this change, the casing for the parameters to the `switch` keyword was inconsistently documented. This change:
- Updates examples, syntax blocks, and prose to use the PascalCase for the parameters, not lowercase.
- Fixes #11811

(GH-11811) Use PascalCase for `switch` parameters

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Break.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Break.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Switch.md
reference/docs-conceptual/lang-spec/chapter-08.md
reference/docs-conceptual/lang-spec/chapter-15.md
reference/docs-conceptual/learn/deep-dives/everything-about-switch.md

2/19/2025 PM Publish

---

reference/docs-conceptual/install/microsoft-update-faq.yml

* Update MU FAQ
* Fix indentation

2/20/2025 PM Publish

---

reference/7.6/Microsoft.PowerShell.Host/Start-Transcript.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-76.md

Update release notes for 7.6-p3
- Fixes [AB#373457](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/373457)

Update release notes for 7.6-p3

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Switch.md

This PR fixes minor typos in [`about_Switch`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_switch), including missing spaces, automatic variable name capitalization and line formatting.

Fix `about_Switch` typos

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
reference/docs-conceptual/developer/cmdlet/types-of-cmdlet-parameters.md
reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md

2/25/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.4/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.5/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/7.6/Microsoft.PowerShell.Management/Get-ChildItem.md
reference/docs-conceptual/learn/shell/creating-profiles.md

2/26/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/5.1/Microsoft.PowerShell.Core/Save-Help.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.4/Microsoft.PowerShell.Core/Save-Help.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.5/Microsoft.PowerShell.Core/Save-Help.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Function_Provider.md
reference/7.6/Microsoft.PowerShell.Core/Save-Help.md

3/6/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
reference/7.4/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
reference/7.5/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
reference/7.6/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md

3/7/2025 PM Publish

---

reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md

Update default policy
- Fixes [AB#406550](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/406550)
- Fixes #11882

Fixes #11882 - Update default policy

---

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md

Fix upgrade instructions
- Fixes [AB#406604](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/406604)
- Fixes #11885

Fixes #11885 - Fix upgrade instructions

---

reference/docs-conceptual/dsc/overview.md
reference/index.yml

* Update references to DSC
* fix typo
* Update DSC descriptions

3/19/2025 PM Publish

---

reference/docs-conceptual/learn/ps101/06-flow-control.md

Fixes [AB#408731](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/408731) - Refresh chapter 6 of ps101

Refresh chapter 6 of ps101

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
reference/docs-conceptual/learn/ps101/06-flow-control.md

* Update about_Hash_Tables.md
hash table->hashtable
* copy changes to all versions
---------

3/20/2025 PM Publish

---

reference/docs-conceptual/learn/ps101/07-working-with-wmi.md

Fixes [AB#410358](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/410358) - Updated chapter 7 of ps101

Updated chapter 7 of ps101

---

reference/5.1/Microsoft.PowerShell.Management/Test-ComputerSecureChannel.md

needs a hint that this cmdlet is not made for DCs.

Update Test-ComputerSecureChannel.md - add note on use on DCs

---

reference/docs-conceptual/install/PowerShell-in-Docker.md

Update Docker information
- Fixes [AB#405815](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/405815)

Update Docker information

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md

Add notes about the  __AllParameterSets name
- Fixes [AB#410960](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/410960)
- Fixes #11955

Fixes #11955 - Add notes about the  __AllParameterSets name

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/5.1/Microsoft.PowerShell.Management/Test-ComputerSecureChannel.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/docs-conceptual/install/PowerShell-in-Docker.md
reference/docs-conceptual/learn/ps101/06-flow-control.md
reference/docs-conceptual/learn/ps101/08-powershell-remoting.md

3/26/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Language_Modes.md
reference/docs-conceptual/community/2025-updates.md
reference/docs-conceptual/community/hall-of-fame.md

04/04/2025 PM Publishing

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-76.md

* Update release notes for 7.6-p4
* Update PowerShell version to 7.6-preview.4

4/9/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md

- Updates content from #11956.
- Revisits fix for #11955
In addition to the changes above, I have also deleted this fragment:
```
- Only one parameter in a set can declare the `ValueFromPipeline` keyword with
a value of `true`. Multiple parameters can define the
`ValueFromPipelineByPropertyName` keyword with a value of `true`.
```
It's simply not true. You can define more than one by-value parameter, and you can fill more than one by-value parameter in the same set. I saw no reason to replace it in this about, it's not really related to parameter sets (imo).

Fixes description of __AllParameterSets and ValueFromPipeline in about_Parameter_Sets

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md

…t_Parameter_Sets (#11986)
* Fixes about_Parameter_Sets
* Clarify `DefaultParameterSetName` usage in documentation
* minor edit
---------

4/10/2025 PM Publish

---

reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.5/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.6/Microsoft.PowerShell.Core/ForEach-Object.md

In this PR, `ForEach-Object` [example 17](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object#example-17-passing-variables-in-nested-parallel-script-scriptblockset) is updated to reflect behavior consistent with PS v7.2+. Example 17 demonstrates use of variable access using nested `-Parallel` script blocks.
In PS v7.2, `ForEach-Object -Parallel` was updated to correctly support variable access in nested script block scenarios. See:
- https://github.com/PowerShell/PowerShell/issues/11817
- https://github.com/PowerShell/PowerShell/pull/14548
- [7.2 Changelog](https://github.com/PowerShell/PowerShell/blob/master/CHANGELOG/7.2.md#720-preview3---2021-02-11)
Example 17 in the docs currently reflects the erroneous behavior exhibited in v7.1 and prior. …

Update `ForEach-Object` example 17 to reflect current behavior

---

reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.5/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.6/Microsoft.PowerShell.Core/ForEach-Object.md

* Update ForEach-Object -Parallel example 17
In PS v7.2, ForEach-Object -Parallel was updated to support variable access in nested script block scenarios.
Example 17 in the docs currently reflects the erroneous behavior exhibited in v7.1 and prior. This change updates the example to reflect the fixed behavior in v7.2.
See PS issue #11817 for more information.
* Fix schema violation
---------

4/14/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Management/Get-Process.md
reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
reference/7.4/Microsoft.PowerShell.Management/Get-Process.md
reference/7.4/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
reference/7.5/Microsoft.PowerShell.Management/Get-Process.md
reference/7.5/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
reference/7.6/Microsoft.PowerShell.Management/Get-Process.md
reference/7.6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md

4/15/2025 PM Publish

---

reference/docs-conceptual/dev-cross-plat/vscode/Using-VSCode-for-Remote-Editing-and-Debugging.md
reference/docs-conceptual/learn/deep-dives/everything-about-null.md
reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
reference/index.yml

* Fix typo
VSCode -> VS Code
* fix: response to review comment
- https://github.com/MicrosoftDocs/PowerShell-Docs/pull/12005/files#r2044504598

4/16/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/5.1/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.6/Microsoft.PowerShell.Core/About/about_PSItem.md

Refactor article to better explain filters
- Based on feedback from @JustinGrote at PowerShell Summit 2025
- Filters no longer punch kittens
- Fixes [AB#421932](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/421932)

Refactor article to better explain filters

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/5.1/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/5.1/Microsoft.PowerShell.Core/Out-Default.md
reference/5.1/Microsoft.PowerShell.Core/Out-Host.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.4/Microsoft.PowerShell.Core/Out-Default.md
reference/7.4/Microsoft.PowerShell.Core/Out-Host.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.5/Microsoft.PowerShell.Core/Out-Default.md
reference/7.5/Microsoft.PowerShell.Core/Out-Host.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.6/Microsoft.PowerShell.Core/About/about_PSItem.md
reference/7.6/Microsoft.PowerShell.Core/Out-Default.md
reference/7.6/Microsoft.PowerShell.Core/Out-Host.md

4/17/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.5/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.6/Microsoft.PowerShell.Core/About/about_CommonParameters.md

Add notes about CIM/CDXML bugs with PipelineVariable
- Fixes [AB#424454](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/424454)
- Fixes #11966

Fixes #11966 - Add notes about CIM/CDXML bugs with PipelineVariable

---

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/5.1/Microsoft.PowerShell.Core/ForEach-Object.md
reference/5.1/Microsoft.PowerShell.Core/Where-Object.md
reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.4/Microsoft.PowerShell.Core/Where-Object.md
reference/7.5/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.5/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.5/Microsoft.PowerShell.Core/Where-Object.md
reference/7.6/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.6/Microsoft.PowerShell.Core/ForEach-Object.md
reference/7.6/Microsoft.PowerShell.Core/Where-Object.md

4/24/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md
reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Break.md
reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.4/Microsoft.PowerShell.Utility/Test-Json.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Break.md
reference/7.5/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.5/Microsoft.PowerShell.Utility/Test-Json.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Break.md
reference/7.6/Microsoft.PowerShell.Core/Clear-Host.md
reference/7.6/Microsoft.PowerShell.Utility/Test-Json.md
reference/docs-conceptual/community/contributing/general-markdown.md
reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/includes/ubuntu-support.md

4/29/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.4/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.5/Microsoft.PowerShell.Utility/Get-Date.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.6/Microsoft.PowerShell.Utility/Get-Date.md
reference/docs-conceptual/learn/deep-dives/output-missing-from-transcript.md
reference/docs-conceptual/windows-powershell/ise/object-model/The-ISEOptions-Object.md

4/30/2025 PM Publish

---

reference/5.1/PSReadLine/PSReadLine.md
reference/7.4/PSReadLine/PSReadLine.md

Remove duplicate entry from module file
- Fixes [AB#427747](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/427747)

Remove duplicate entry from module file

---

reference/5.1/PSReadLine/PSReadLine.md
reference/7.4/PSReadLine/PSReadLine.md

05/05/2025 PM Publishing

---

reference/5.1/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md
reference/5.1/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md

Fix module file inventories
- Fixes [AB#429815](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/429815)

Fix module file inventories

---

reference/5.1/Microsoft.PowerShell.Diagnostics/New-WinEvent.md
reference/7.4/Microsoft.PowerShell.Diagnostics/New-WinEvent.md
reference/7.5/Microsoft.PowerShell.Diagnostics/New-WinEvent.md
reference/7.6/Microsoft.PowerShell.Diagnostics/New-WinEvent.md

Fix typo: withe -> with

---

reference/5.1/Microsoft.PowerShell.Diagnostics/New-WinEvent.md
reference/7.4/Microsoft.PowerShell.Diagnostics/New-WinEvent.md
reference/7.5/Microsoft.PowerShell.Diagnostics/New-WinEvent.md
reference/7.6/Microsoft.PowerShell.Diagnostics/New-WinEvent.md
reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
reference/docs-conceptual/install/community-support.md
reference/docs-conceptual/install/install-alpine.md
reference/docs-conceptual/install/install-debian.md
reference/docs-conceptual/install/install-rhel.md
reference/docs-conceptual/install/install-ubuntu.md
reference/docs-conceptual/install/microsoft-update-faq.yml
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md

5/13/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md

5/14/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Switch.md

Clarify stringification of switch values
- Fixes [AB#431898](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/431898)
- Fixes #12067

Fixes #12067 - Clarify stringification of switch values

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Switch.md

5/15/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Switch.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Switch.md
reference/docs-conceptual/dev-cross-plat/performance/parallel-execution.md
reference/docs-conceptual/toc.yml
reference/module/index.md

5/19/2025 PM Publish

---

reference/docs-conceptual/developer/cmdlet/activity-parameters.md

There was a duplicate definition for the Compress parameter; I assume the intent was to use CompressionLevel for the second one (algorithm selection), as used in e.g. Microsoft.PowerShell.Archive.

Fix duplicate Compress definition

---

reference/7.4/Microsoft.PowerShell.Utility/Get-Random.md
reference/7.4/Microsoft.PowerShell.Utility/Get-SecureRandom.md
reference/7.5/Microsoft.PowerShell.Utility/Get-Random.md
reference/7.5/Microsoft.PowerShell.Utility/Get-SecureRandom.md
reference/7.6/Microsoft.PowerShell.Utility/Get-Random.md
reference/7.6/Microsoft.PowerShell.Utility/Get-SecureRandom.md

Fix typo: sting -> string

---

reference/5.1/Microsoft.PowerShell.Core/Get-Module.md
reference/7.4/Microsoft.PowerShell.Core/Get-Module.md
reference/7.5/Microsoft.PowerShell.Core/Get-Module.md
reference/7.6/Microsoft.PowerShell.Core/Get-Module.md

This change fixes the confusing wording on the `-ListAvailable` parameter. Orignal wording was confusing and also incorrectly explained the resulting output of the parameter.

Update Get-Module to clarify `-ListAvailable` parameter

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
reference/5.1/Microsoft.PowerShell.Core/Get-Module.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
reference/7.4/Microsoft.PowerShell.Core/Get-Module.md
reference/7.4/Microsoft.PowerShell.Utility/Get-Random.md
reference/7.4/Microsoft.PowerShell.Utility/Get-SecureRandom.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
reference/7.5/Microsoft.PowerShell.Core/Get-Module.md
reference/7.5/Microsoft.PowerShell.Utility/Get-Random.md
reference/7.5/Microsoft.PowerShell.Utility/Get-SecureRandom.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
reference/7.6/Microsoft.PowerShell.Core/Get-Module.md
reference/7.6/Microsoft.PowerShell.Utility/Get-Random.md
reference/7.6/Microsoft.PowerShell.Utility/Get-SecureRandom.md
reference/docs-conceptual/developer/help/comment-based-help-keywords.md

5/21/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/Save-Help.md
reference/7.4/Microsoft.PowerShell.Core/Save-Help.md
reference/7.5/Microsoft.PowerShell.Core/Save-Help.md
reference/7.6/Microsoft.PowerShell.Core/Save-Help.md

Fix typo: patters -> patterns

---

reference/5.1/Microsoft.PowerShell.Core/Save-Help.md
reference/7.4/Microsoft.PowerShell.Core/Save-Help.md
reference/7.5/Microsoft.PowerShell.Core/Save-Help.md
reference/7.6/Microsoft.PowerShell.Core/Save-Help.md
reference/docs-conceptual/developer/cmdlet/advisory-development-guidelines.md
reference/docs-conceptual/security/security-features.md

5/22/2025 PM Publish

---

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md

…nce considerations" page (#12106)
* Add a note about array addition
* Update script-authoring-considerations.md
* Update script-authoring-considerations.md
---------

5/26/2025 PM Publish

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Classes_Methods.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Classes_Methods.md

Fixes a small typo.
- Fix #12116 

Fix "$Static" Typo

---

reference/7.4/Microsoft.PowerShell.Core/About/about_Calling_Generic_Methods.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Calling_Generic_Methods.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Calling_Generic_Methods.md

This PR fixes four typos in three versions of `about_Calling_Generic_Methods`.
By the way, in the list below, the second instance of "contributor's guide" is misspelled as "contributors guide". Someone with access to the repo's templates should fix it.

Typo fixes in about_Calling_Generic_Methods

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comments.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comments.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Comments.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Comments.md

6/5/2025 PM Publish

---

reference/docs-conceptual/developer/module/how-to-write-a-powershell-binary-module.md

* Add Note about module assembly initializer and cleanup
* Add links and fix formatting
---------

6/12/2025 PM Publish

---

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md

6/18/2025 PM Publish

---

reference/includes/latest-install.md

Update version info in include file
- Fixes [AB#442761](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/442761)

Update version info in include file

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Operators.md

Add note about expandable strings for wildcards
- Fixes [AB#443066](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/443066)
- Fixes #12161

Fixes #12161 - Add note about expandable strings for wildcards

---

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md

Update release notes for 7.4.11 & 7.5.2
- Fixes [AB#442047](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/442047)
Pending release
- PowerShell/PowerShell#25667
- PowerShell/PowerShell#25668

Update release notes for 7.4.11 & 7.5.2

---

reference/docs-conceptual/learn/shell/using-predictors.md

Fix reference and link from the old v3 module to renamed (release version) PSResource module.
Reordered and recommended new module.
Slight adjustments to each entry for consistency

Update using-predictors.md to reference the (now renamed) GA release version of PSResourceGet rather than the old beta version.

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md

Fix quotes in example
- Fixes [AB#445188](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/445188)
- Fixes #12186

Fixes #12186 - Fix quotes in example

---

reference/5.1/Microsoft.PowerShell.Core/Where-Object.md
reference/7.4/Microsoft.PowerShell.Core/Where-Object.md
reference/7.5/Microsoft.PowerShell.Core/Where-Object.md
reference/7.6/Microsoft.PowerShell.Core/Where-Object.md

Fix typo: simplfied -> simplified

Fix typo: simplfied -> simplified

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Functions.md

Fix pipeline example
- Fixes [AB#454691](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/454691)
- Fixes #12228

Fixes #12228 - Fix pipeline example

---

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.5/Microsoft.PowerShell.Core/About/about_Operators.md
reference/7.6/Microsoft.PowerShell.Core/About/about_Operators.md

Fix case in `about_Operators.md`

Fix case in about_Operators.md

---

.github/actions/commenting/expectations/v1/Parameters.psd1
.github/actions/reporting/stale-content/v1/Parameters.psd1
.github/actions/reporting/versioned-content/v1/Parameters.psd1
.github/actions/verification/authorization/v1/Parameters.psd1
.github/actions/verification/checklist/v1/Parameters.psd1

Prior to this change, the authorization parameter handling didn't correctly handle an empty string for the `authorized_accounts` parameter. The casing for all other workflows used incorrect casing for workflow parameters, like `Message_Body` instead of `message_body`.
This change:
- Corrects the casing of all parameter handler entries.
- Ensures that the parameter handler for `authorized_accounts` only passes the parameter to the action script when the input value is a non-empty string.

(GHA) Update casing and fix authorization

---

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.5/Microsoft.PowerShell.Core/About/about_CommonParameters.md
reference/7.6/Microsoft.PowerShell.Core/About/about_CommonParameters.md

Following a series of questions by a PowerShell learner, I realized that the `PipelineVariable` example in this document is counterintuitive. So, I wrote a better one.
Here are the questions:
1. Why is the output different on my PC?
2. Why is the counter always -1 or 0?
3. Why are a mix of `Write-Host` and `Write-Output` commands in the example? Isn't `Write-Host` supposed to be evil?
4. Why do I get different results when I uniformly use `Write-Host` or `Write-Output`?
Here are my answers.
The output isn't different when you paste the original code into Windows Terminal, regardless of PowerShell's version. But if you:
- Paste the example into the prompt line of PowerShell 7.5 inside Console Host
- Run the example from a PS1 file
- Paste the example into the prompt line between `&{` and …

Update about_CommonParameters.md: Pipeline variable example
