reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fixes [AB#57881](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57881) - Fixes #9394 - Web cmdlets use UTF-8 encoding
=> Fixes #9394 - Web cmdlets use UTF-8 encoding

reference/docs-conceptual/learn/experimental-features.md
Fixes [AB#57887](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57887) - Fixes #9417 - Document PSModuleAutoLoadSkipOfflineFiles
=> Fixes #9417 - Document PSModuleAutoLoadSkipOfflineFiles

reference/7.4/Microsoft.PowerShell.Core/Switch-Process.md
Fixes [AB#57894](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57894) - Fixes #9396 - Switch-Process now copies env vars
=> Fixes #9396 - Switch-Process now copies env vars

reference/7.4/Microsoft.PowerShell.Host/Stop-Transcript.md
Fixes [AB#57896](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57896) - Fixes #9531 - Update parameters for Stop-Transcript
=> Fixes #9531 - Update parameters for Stop-Transcript

reference/7.4/Microsoft.PowerShell.Core/Get-Command.md
Fixes [AB#57900](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57900) - Fixes #9302 - Add `-FuzzyMinimumDistance` parameter
=> Fixes #9302 - Add `-FuzzyMinimumDistance` parameter

reference/docs-conceptual/community/2022-updates.md, reference/docs-conceptual/community/hall-of-fame.md
Fixes [AB#57907](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57907) - Fixes #9646 - Update monthly stats
=> Fixes #9646 - Update monthly stats

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
Fixes [AB#58015](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/58015) - Fixes #9656 - Update FileInfo feature docs
=> Fixes #9656 - Update FileInfo feature docs

reference/5.1/Microsoft.PowerShell.Management/Get-Process.md, reference/5.1/Microsoft.PowerShell.Management/Stop-Process.md, reference/7.2/Microsoft.PowerShell.Management/Get-Process.md, reference/7.2/Microsoft.PowerShell.Management/Stop-Process.md, reference/7.3/Microsoft.PowerShell.Management/Get-Process.md, reference/7.3/Microsoft.PowerShell.Management/Stop-Process.md, reference/7.4/Microsoft.PowerShell.Management/Get-Process.md, reference/7.4/Microsoft.PowerShell.Management/Stop-Process.md
Prior to this PR, there was only alias notes for Start-Process
This PR adds alias notes for the Stop/Get-Process cmdlets
Resolves #9661 
=> Quality: Adding alias notes for Stop & Get process

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
Fixes [AB#58149](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/58149) - Fixes #9655 - Avoid wrapping cmdlet pipelines
=> Fixes #9655 - Avoid wrapping cmdlet pipelines

reference/docs-conceptual/toc.yml, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
Fixes [AB#58209](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/58209) - Fixes #9649 - Add 7.4 release notes
=> Fixes #9649 - Add 7.4 release notes

reference/5.1/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
Fixes [AB#57943](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57943) - Fixes #9652 - Document PSStyle static methods
Fixes [AB#57947](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57947) - add about_ANSI_Terminals for 5.1
=> Fixes #9652 - Document PSStyle static methods

reference/5.1/Microsoft.PowerShell.Core/Update-Help.md, reference/7.2/Microsoft.PowerShell.Core/Update-Help.md, reference/7.3/Microsoft.PowerShell.Core/Update-Help.md, reference/7.4/Microsoft.PowerShell.Core/Update-Help.md
This change updates the documentation for `Update-Help` to clarify when an error message is raised for missing help for a specific language in versions prior to 7.4 and updates the 7.4 document to reflect the no-longer-silent-failure.
- Resolves #9653
- Fixes [AB#57944](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/57944)
=> (AB#57944) Update note on error message for Update-Help UI Culture

reference/5.1/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/5.1/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.2/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/7.2/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.3/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/7.3/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.4/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md
This adds alias information to the Notes section in the documentation for Get-Clipboard and Set-Clipboard.
- Resolves #9670
=> Quality: Adding alias to Notes section of -Clipboard Cmdlets

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Modes.md
Fixes [AB#58366](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/58366) - Fixes #9615 - Update language mode docs
I reordered the existing information, so now the article starts with concepts and how-to and finishes with reference about each mode. Viewing this in diff mode may be difficult. I suggest viewing the full document.
=> Fixes #9615 - Update language mode docs

reference/module/index.md
Updated PowerShell module browser quick filter for AzPS to version 9.3.0.
=> Updated quick filter to azps 9.3.0

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Added $ParameterName to the 2 argument example of parameter attributes as it was missing.
=> Added $ParameterName to the 2 argument example.

reference/docs-conceptual/whats-new/cmdlet-versions.md
Fixes [AB#58805](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/58805) - Fixes #9679 - Update module & cmdlet history tables
=> Fixes #9679 - Update module & cmdlet history tables

reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md
Fixes [AB#58855](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/58855) - Fixes #9682 - Fix registry path for User environment
=> Fixes #9682 - Fix registry path for User environment

reference/5.1/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md, reference/5.1/Microsoft.PowerShell.Management/Get-Content.md, reference/7.2/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md, reference/7.2/Microsoft.PowerShell.Management/Get-Content.md, reference/7.3/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md, reference/7.3/Microsoft.PowerShell.Management/Get-Content.md, reference/7.4/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md, reference/7.4/Microsoft.PowerShell.Management/Get-Content.md
Fixes [AB#58850](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/58850) - Fixes #9675 - Add LinkType information
=> Fixes #9675 - Add LinkType information

reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
Fixes [AB#58924](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/58924) - Fixes #9231 - Add NoRunspaceAffinity
=> Fixes #9231 - Add NoRunspaceAffinity

reference/7.2/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Telemetry.md
Adding Microsoft Privacy statement to 7.2+ versions in the about_telemetry page
=> Update about_telemetry.md with Microsoft Privacy statement

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Special_Characters.md
Fixes [AB#58978](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/58978) - Fixes #9618 - Add line continuation docs
=> Fixes #9618 - Add line continuation docs

reference/5.1/Microsoft.PowerShell.Management/Get-ComputerInfo.md, reference/7.2/Microsoft.PowerShell.Management/Get-ComputerInfo.md, reference/7.3/Microsoft.PowerShell.Management/Get-ComputerInfo.md, reference/7.4/Microsoft.PowerShell.Management/Get-ComputerInfo.md
- reference/*.*/Microsoft.PowerShell.Management/Get-ComputerInfo.md
Resolves #9693 
=> Quality: Adds alias notes for Get-ComputerInfo

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
Removes an erroneous workd from "PowerShell scripting performance considerations"
- Resolves #9700
- Fixes [AB#59405](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59405)
=> (GH-9700) Fix typo

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
Fixes #9709 - Added missing step
=> Fixes 9709 - Added missing step

reference/5.1/Microsoft.PowerShell.Core/About/About.md, reference/7.2/Microsoft.PowerShell.Core/About/About.md, reference/7.3/Microsoft.PowerShell.Core/About/About.md, reference/7.4/Microsoft.PowerShell.Core/About/About.md
=> About.md: fix typos

reference/docs-conceptual/gallery/getting-started.md, reference/docs-conceptual/gallery/how-to/getting-support/troubleshooting-cmdlets.md
Fixes [AB#59613](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59613) - Fixes #9703 - Update Gallery endpoint info
=> Fixes #9703 - Update Gallery endpoint info

reference/5.1/PowershellGet/Find-Module.md, reference/5.1/PowershellGet/Install-Module.md, reference/5.1/PowershellGet/Publish-Module.md, reference/5.1/PowershellGet/Update-Module.md, reference/7.2/PowerShellGet/Find-Module.md, reference/7.2/PowerShellGet/Install-Module.md, reference/7.2/PowerShellGet/Publish-Module.md, reference/7.2/PowerShellGet/Update-Module.md, reference/7.3/PowerShellGet/Find-Module.md, reference/7.3/PowerShellGet/Install-Module.md, reference/7.3/PowerShellGet/Publish-Module.md, reference/7.3/PowerShellGet/Update-Module.md, reference/7.4/PowerShellGet/Find-Module.md, reference/7.4/PowerShellGet/Install-Module.md, reference/7.4/PowerShellGet/Publish-Module.md, reference/7.4/PowerShellGet/Update-Module.md
This adds alias information to the Notes section in the documentation for Find-Module / Install-Module / Publish-Module / Update-Module
- Resolves #9672
=> Quality: Adding alias to Notes section of -Module Cmdlets

reference/5.1/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/5.1/Microsoft.PowerShell.Management/New-PSDrive.md, reference/5.1/Microsoft.PowerShell.Management/Remove-PSDrive.md, reference/7.2/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/7.2/Microsoft.PowerShell.Management/New-PSDrive.md, reference/7.2/Microsoft.PowerShell.Management/Remove-PSDrive.md, reference/7.3/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/7.3/Microsoft.PowerShell.Management/New-PSDrive.md, reference/7.3/Microsoft.PowerShell.Management/Remove-PSDrive.md, reference/7.4/Microsoft.PowerShell.Management/Get-PSDrive.md, reference/7.4/Microsoft.PowerShell.Management/New-PSDrive.md, reference/7.4/Microsoft.PowerShell.Management/Remove-PSDrive.md
- reference/*.*/Microsoft.PowerShell.Management/Get-PSDrive.md
- reference/*.*/Microsoft.PowerShell.Management/New-PSDrive.md
- reference/*.*/Microsoft.PowerShell.Management/Remove-PSDrive.md
Resolves #9695 
=> Quality: Alias notes for -PSDrive cmdlets

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Arrays.md
Fixes [AB#59625](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59625) - Fixes #9705 - Add link to whereoperatorselectionmode
=> Fixes #9705 - Add link to whereoperatorselectionmode

reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/7.2/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/7.3/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/7.4/Microsoft.PowerShell.Utility/ConvertTo-Xml.md, reference/docs-conceptual/gallery/getting-started.md, reference/docs-conceptual/lang-spec/chapter-16.md
Fixes [AB#59813](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59813) - Fixes #9718 - Fix links from broken link report
=> Fixes #9718 - Fix links from broken link report

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Fixes [AB#59844](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59844) - Fixes #9720 - Add missing automatic variables
=> Fixes #9720 - Add missing automatic variables

reference/docs-conceptual/learn/shell/running-commands.md
The current link is pointing to the wrong section of the right page.
=> bad bookmark

reference/7.2/Microsoft.PowerShell.Utility/Join-String.md, reference/7.3/Microsoft.PowerShell.Utility/Join-String.md, reference/7.4/Microsoft.PowerShell.Utility/Join-String.md
Fixes [AB#59967](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59967) - Fixes #9725 - Remove ref links
=> Fixes #9725 - Remove ref links

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Modes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Module_Manifests.md
- Related to [AB#59982](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59982) - Related issue #9356
=> GH#9356 - Add language mode info for manifests

reference/5.1/Microsoft.PowerShell.Core/About/about_Data_Files.md, reference/5.1/Microsoft.PowerShell.Utility/Import-LocalizedData.md, reference/5.1/Microsoft.PowerShell.Utility/Import-PowerShellDataFile.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Data_Files.md, reference/7.2/Microsoft.PowerShell.Utility/Import-LocalizedData.md, reference/7.2/Microsoft.PowerShell.Utility/Import-PowerShellDataFile.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Data_Files.md, reference/7.3/Microsoft.PowerShell.Utility/Import-LocalizedData.md, reference/7.3/Microsoft.PowerShell.Utility/Import-PowerShellDataFile.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Data_Files.md, reference/7.4/Microsoft.PowerShell.Utility/Import-LocalizedData.md, reference/7.4/Microsoft.PowerShell.Utility/Import-PowerShellDataFile.md
- Fixes [AB#59982](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/59982) - Fixes #9356 
=> Fixes #9356 - Add about_Data_Files topic

reference/5.1/Microsoft.PowerShell.Utility/Start-Sleep.md, reference/7.2/Microsoft.PowerShell.Utility/Start-Sleep.md, reference/7.3/Microsoft.PowerShell.Utility/Start-Sleep.md, reference/7.4/Microsoft.PowerShell.Utility/Start-Sleep.md
- reference/*.*/Microsoft.PowerShell.Utility/Start-Sleep.md
Resolves #9732 
=> Quality: Updated alias notes for -Sleep

reference/5.1/Microsoft.PowerShell.Core/About/about_Output_Streams.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Output_Streams.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Output_Streams.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Output_Streams.md
Write-Host also writes to Information stream
=> Write-Host also writes to Information stream

reference/5.1/Microsoft.PowerShell.Utility/Get-Unique.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Unique.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Unique.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Unique.md
This reformats alias information in the Notes section to comply with the standard format in the documentation for Get-Unique
- Resolves #9740
=> Quality: Adding alias to notes of Get-Unique Cmdlet

reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSCustomObject.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PSCustomObject.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
=> Minor spelling correction

reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
- Fixes [AB#55537](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/55537) - Added proper configuration for PowerShell logging in Linux
=> Added proper config for ps logging in linux

reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
- Fixes [AB#60573](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/60573) - Fixes #9747 
=> Fixes #9747 - Update SSH configuration doc

reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
Fixes [AB#60575](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/60575) - Fixes #9746 - Expand docs for intrinsic members
=> Fixes #9746 - Expand docs for intrinsic members

reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fixes [AB#60893](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/60893) - Fixes #9756 - Update Headers parameter
=> Fixes #9756 - Update Headers parameter

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
Fixes [AB#60937](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/60937) - Fixes #9753 - Add note about winget for Arm64
=> Fixes #9753 - Add note about winget for Arm64

reference/5.1/Microsoft.PowerShell.Management/Get-Service.md, reference/5.1/Microsoft.PowerShell.Management/Start-Service.md, reference/5.1/Microsoft.PowerShell.Management/Stop-Service.md, reference/7.2/Microsoft.PowerShell.Management/Get-Service.md, reference/7.2/Microsoft.PowerShell.Management/Start-Service.md, reference/7.2/Microsoft.PowerShell.Management/Stop-Service.md, reference/7.3/Microsoft.PowerShell.Management/Get-Service.md, reference/7.3/Microsoft.PowerShell.Management/Start-Service.md, reference/7.3/Microsoft.PowerShell.Management/Stop-Service.md, reference/7.4/Microsoft.PowerShell.Management/Get-Service.md, reference/7.4/Microsoft.PowerShell.Management/Start-Service.md, reference/7.4/Microsoft.PowerShell.Management/Stop-Service.md
- reference/*.*/Microsoft.PowerShell.Management/Get-Service.md
- reference/*.*/Microsoft.PowerShell.Management/Start-Service.md
- reference/*.*/Microsoft.PowerShell.Management/Stop-Service.md
Resolves #9760 
=> Quality: Added alias notes to -Service cmdlets

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
about_Classes.md contains 2 invalid utf-8 characters, 2 horizontal ellipsis (U+2026). The file has been all converted to valid utf-8 encoding.
about_Classes.md contains 2 invalid utf-8 characters, 2 horizontal ellipsis (U+2026). The file has been all converted to valid utf-8 encoding for compatibility.
=> Modify an md file with invalid utf-8 characters

reference/docs-conceptual/how-to-use-docs.md
=> minor correction in how-to-use-docs.md

reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Module_Manifests.md
This change fixes a minor typo in `about_Module_Manifests` and:
- Resolves #9769
- Fixes [AB#61448](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/61448)
=> (GH-9769) Fix about_Module_Manifests typo

reference/docs-conceptual/discover-powershell.md
Fixes [AB#61589](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/61589) - Fixes #9767 - Improve grammar and examples
=> Fixes #9767 - Improve grammar and examples

reference/5.1/Microsoft.PowerShell.Core/About/about_Output_Streams.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Output_Streams.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Output_Streams.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Output_Streams.md
This change makes the following typo corrections in the Information Stream section:
"...message..." to "...messages..." at line 84
"This..." to "The..." at line 90
"...redirect **Information**..." to "...redirect the **Information**..." at line 92
=> Updated 3 typos in the Information Stream section of about_Output_Streams.md

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-raspbian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md
Fixes [AB#61946](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/61946) - Fixes #9778 - Update version numbers
=> Fixes #9778 - Update version numbers

reference/docs-conceptual/dsc/overview.md, reference/docs-conceptual/learn/remoting/jea/role-capabilities.md, reference/docs-conceptual/learn/remoting/jea/using-jea.md
This change updates the stale conceptual articles for DSC and JEA, cleaning up their grammar and style.
- Resolves #9785
- Fixes [AB#62146](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/62146)
=> (GH-9785) Refresh stale DSC/JEA docs

reference/docs-conceptual/community/2020-updates.md, reference/docs-conceptual/community/2021-updates.md, reference/docs-conceptual/community/2022-updates.md, reference/docs-conceptual/community/2023-updates.md, reference/docs-conceptual/community/hall-of-fame.md, reference/docs-conceptual/dev-cross-plat/create-standard-library-binary-Module.md
Fixes [AB#60709](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/60709) - Fixes #9782 - Freshness update and monthly stats
=> Fixes #9782 - Freshness update and monthly stats

reference/5.1/Microsoft.PowerShell.Utility/Invoke-Expression.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-Expression.md, reference/7.3/Microsoft.PowerShell.Utility/Invoke-Expression.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-Expression.md
- reference/*.*/Microsoft.PowerShell.Utility/Invoke-Expression.md
Resolve #9789 
=> Quality: Added alias notes for Invoke-Expression

.github/ISSUE_TEMPLATE/02-quality.yml, .github/workflows/quality.issue.yml, .github/workflows/quality.pr.yml
Prior to this change, the quality project workflows depended on a GitHub Action that used a secret token to add issues and PRs to the project.
We've enabled the auto-add project workflow to add issues and pull requests with the `project-quality` label to the project.
This change:
- Updates the quality issue template to add the `project-quality` label on issue creation
- Removes the logic from the workflows for adding issues and PRs to the project directly
=> (MAINT) Fix quality project workflows

.github/ISSUE_TEMPLATE/00-bug.yml, .github/ISSUE_TEMPLATE/01-article.yml, .github/ISSUE_TEMPLATE/03-change.yml, reference/docs-conceptual/community/contributing/labelling-in-github.md
This change updates the contributor guide and GitHub templates to match the updated labels for the repository.
- Fixes [AB#62332](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/62332)
=> (AB-62332) Update labels in docs/templates

reference/docs-conceptual/developer/format/selectioncondition-element-for-entryselectedby-for-customcontrol-format.md
Fixes a Markdown table with invalid formatting, resulting in a misrendering of the table.
=> Fixes newlines breaking Markdown table

reference/docs-conceptual/developer/format/expressionbinding-element-for-customitem-for-customcontrol-for-view-format.md
=> Removes > symbol from content between tags

reference/module/index.md
Updated quick filter for the Az PowerShell module to version 9.4.0
=> Updated azps quick filter to 9.4.0

reference/7.2/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md
Update powershell.config.json docs
- Fixes [AB#62441](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/62441)
- Fixes #9797
=> Fixes #9797 - Update powershell.config.json docs

reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/docs-conceptual/dev-cross-plat/vscode/using-vscode-for-debugging-compiled-cmdlets.md, reference/docs-conceptual/learn/shell/dynamic-help.md, reference/docs-conceptual/learn/shell/tab-completion.md
=> Change kbd style to use +

reference/docs-conceptual/dev-cross-plat/security/preventing-script-injection.md, reference/docs-conceptual/dev-cross-plat/security/preventing_script_injection.md, reference/docs-conceptual/toc.yml
Add article about injections attacks
- Fixes [AB#62438](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/62438)
- Fixes #9773
=> Fixes #9773 - Add article about injections attacks

reference/5.1/Microsoft.PowerShell.Management/Remove-Item.md, reference/7.2/Microsoft.PowerShell.Management/Remove-Item.md, reference/7.3/Microsoft.PowerShell.Management/Remove-Item.md, reference/7.4/Microsoft.PowerShell.Management/Remove-Item.md
Clarify dynamic parameters
- Fixes [AB#63945](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/63945)
- Fixes #9822
=> Fixes #9822 - Clarify dynamic parameters

reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md
- Fix typo in about_pwsh - related to PowerShell/PowerShell#19153
=> Fix a typo in the pwsh help content

reference/5.1/Microsoft.PowerShell.Management/Copy-Item.md, reference/7.2/Microsoft.PowerShell.Management/Copy-Item.md, reference/7.3/Microsoft.PowerShell.Management/Copy-Item.md, reference/7.4/Microsoft.PowerShell.Management/Copy-Item.md
Fix example numbering
- Fixes [AB#66194](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/66194)
- Fixes #9839
=> Fixes #9839 - Fix example numbering

reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
Refreshed PowerShell logging on macOS
Fixes [AB#60297](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/60297)
=> Refreshed powershell logging on macos

reference/7.2/PSReadLine/Set-PSReadLineOption.md, reference/7.3/PSReadLine/Set-PSReadLineOption.md, reference/7.4/PSReadLine/Set-PSReadLineOption.md
Adding ListView prediction source options to the valid key examples for `-Colors` of `Set-PSReadLine`
=> Updating Colors with Listview options

reference/5.1/Microsoft.PowerShell.Utility/Write-Error.md, reference/7.2/Microsoft.PowerShell.Utility/Write-Error.md, reference/7.3/Microsoft.PowerShell.Utility/Write-Error.md, reference/7.4/Microsoft.PowerShell.Utility/Write-Error.md
Fix typo in Outputs section
- Fixes [AB#66830](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/66830)
- Fixes #9850
=> Fixes #9850 - Fix typo in Outputs section

reference/docs-conceptual/community/2023-updates.md, reference/docs-conceptual/community/hall-of-fame.md
Update monthly stats
- Fixes [AB#67026](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/67026)
- Fixes #9854
=> Fixes #9854 - Update monthly stats

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
This fixes a typo. The sentence already has a verb, the "is" is grammatically incorrect.
=> Sentence structure: removed superfluous "is"

reference/5.1/Microsoft.PowerShell.Core/About/About.md, reference/5.1/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Booleans.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Eventlogs.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.2/Microsoft.PowerShell.Core/About/About.md, reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Booleans.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Break.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.3/Microsoft.PowerShell.Core/About/About.md, reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Booleans.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Break.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.4/Microsoft.PowerShell.Core/About/About.md, reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Booleans.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Break.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
Fix About topic index
- Fixes [AB#67096](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/67096)
- Fixes #9859
=> Fixes #9859 - Fix About topic index

reference/5.1/Microsoft.PowerShell.Core/About/about_Registry_Provider.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Registry_Provider.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Registry_Provider.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Registry_Provider.md
Fix broken example
- Fixes [AB#67110](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/67110)
- Fixes #9858
=> Fixes #9858 - Fix broken example

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Host.md, reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Host.md, reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Host.md, reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Host.md
Update ANSI info and $Host differences
- Fixes [AB#67254](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/67254)
- Fixes #9853
=> Fixes #9853 - Update ANSI info and $Host differences

reference/docs-conceptual/learn/shell/using-light-theme.md
Fix example code that raises error `You cannot call a method on a null-valued expression.`
=> Fix example code in using-light-theme.md

reference/7.2/Microsoft.PowerShell.Utility/Remove-Alias.md, reference/7.3/Microsoft.PowerShell.Utility/Remove-Alias.md, reference/7.4/Microsoft.PowerShell.Utility/Remove-Alias.md
Can't remove constant aliases
- Fixes [AB#69017](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/69017)
- Fixes #9876
=> Fixes #9876 - Can't remove constant aliases

reference/docs-conceptual/developer/format/loading-and-exporting-formatting-data.md
Add missing content
- Fixes [AB#69057](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/69057)
- Fixes #9878
=> Fixes #9878 - Add missing content

reference/module/index.md
Updated quick filter for AzPS to version 9.5.0
=> Updated quick filter for azps to version 9.5.0

reference/5.1/Microsoft.PowerShell.Core/About/about_Character_Encoding.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Character_Encoding.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Character_Encoding.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Character_Encoding.md
Add missing encoding type
- Fixes [AB#69500](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/69500)
- Fixes #9886
=> Fixes #9886 - Add missing encoding type

reference/5.1/Microsoft.PowerShell.Core/Remove-PSSnapin.md, reference/5.1/Microsoft.PowerShell.Core/Resume-Job.md, reference/5.1/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md, reference/5.1/Microsoft.PowerShell.Management/Get-WmiObject.md, reference/5.1/Microsoft.PowerShell.Management/Set-Content.md, reference/5.1/Microsoft.PowerShell.Utility/Select-String.md, reference/7.2/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md, reference/7.2/Microsoft.PowerShell.Utility/Select-String.md, reference/7.3/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md, reference/7.3/Microsoft.PowerShell.Utility/Select-String.md, reference/7.4/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md, reference/7.4/Microsoft.PowerShell.Utility/Select-String.md
- reference/5.1/Microsoft.PowerShell.Core/Remove-PSSnapin.md
- reference/5.1/Microsoft.PowerShell.Core/Resume-Job.md
- reference/5.1/Microsoft.PowerShell.Management/Get-ItemPropertyValue.md
- reference/5.1/Microsoft.PowerShell.Management/Get-WmiObject.md
- reference/5.1/Microsoft.PowerShell.Management/Set-Content.md
- reference/5.1/Microsoft.PowerShell.Utility/Select-String.md
Resolves #9893 
=> Quality: Alias notes for various 5.1 cmdlets

reference/docs-conceptual/developer/format/creating-a-wide-view.md, reference/docs-conceptual/developer/format/formatting-displayed-data.md, reference/docs-conceptual/developer/format/formatting-file-overview.md
Fix XML examples and cleanup formatting
- Fixes [AB#69842](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/69842)
- Fixes #9896
=> Fixes #9896 - Fix XML examples and cleanup formatting

reference/7.2/Microsoft.PowerShell.Core/About/about_Requires.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Requires.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Requires.md
Remove -pssnapin
- Fixes [AB#70141](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70141)
- Fixes #9900
=> Fixes #9900 - Remove -pssnapin

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
Update release notes for 7.4-preview.2
- Fixes [AB#70393](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70393)
- Fixes #9906
=> Fixes #9906 - Update release notes for 7.4-preview.2

reference/7.4/Microsoft.PowerShell.Core/About/about_Telemetry.md
This documents changes in https://github.com/PowerShell/PowerShell/pull/18762 
=> Experimental feature telemetry changes

reference/docs-conceptual/community/2023-updates.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
=> Fix typos and formatting

reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.2/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.3/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md
Document error condition for -ExpandProperty
- Fixes [AB#70782](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70782)
- Fixes #9910
=> Fixes #9910 - Document error condition for -ExpandProperty

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-raspbian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md
Update versions for new releases
=> Update versions for new releases

reference/docs-conceptual/samples/Working-with-Software-Installations.md
Remove examples using Win32_Product class
- Fixes [AB#70939](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/70939)
- Fixes #9907
=> Fixes #9907 - Remove examples using Win32_Product class

reference/docs-conceptual/learn/experimental-features.md
=> Fix TestExe source code link

reference/7.4/Microsoft.PowerShell.Core/About/about_Character_Encoding.md
In #9909 we updated the documentation for the cmdlets to include the new `Ansi` option for encoding. This change brings the same documentation to the `about_Character_Encoding`
=> (GH-9887) Document `Ansi` option in about_Character_Encoding

reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md, reference/7.2/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md, reference/7.3/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md, reference/7.4/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md
Remove Options from VariableDefinitions
- Fixes [AB#71332](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/71332)
- Fixes #9927
=> Fixes #9927 - Remove Options from VariableDefinitions

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
(MAINT) Update release notes for 7.4
=> (MAINT) Update release notes for 7.4

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
Fix hash lookup example
- Fixes [AB#72377](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/72377)
- Fixes #9931
=> Fixes #9931 - Fix hash lookup example

reference/docfx.json
Change feedback target for PS5.1 content
=> Change feedback target for PS5.1 content

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md
Add order of execution for profiles
- Fixes [AB#79521](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/79521)
- Fixes #9947
=> Fixes #9947 - Add order of execution for profiles

reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md
Simplify descriptions of the file locations
- Fixes [AB#79536](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/79536)
- Fixes #9946
=> Fixes #9946 - Simplify descriptions of the file locations

reference/5.1/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md, reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/5.1/PSReadLine/Set-PSReadLineOption.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/PSReadLine/Set-PSReadLineOption.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.3/PSReadLine/Set-PSReadLineOption.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Calculated_Properties.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.4/PSReadLine/Set-PSReadLineOption.md
=> 3/24 PM Publish

reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md
Remove repeated word
- Fixes [AB#79951](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/79951)
- Fixes #9954
=> Fixes #9954 - Remove repeated word

reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md
fix typo
- Fixes [AB#79951](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/79951)
- Fixes #9954
=> Fixes #9954 - fix typo

reference/index.yml
- Fixes [AB#80219](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/80219) - Update tiles on hub page
=> Update tiles on hub page

reference/includes/rhel-support.md
Add RHEL 9 and correct RHEL 7 support for 7.4
@adityapatwardhan, please review
=> Add RHEL 9 and correct RHEL 7 support for 7.4

reference/docs-conceptual/learn/shell/using-keyhandlers.md
=> Fix: wrong reference linkage

reference/docs-conceptual/discover-powershell.md
Fix typo
- Fixes [AB#80822](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/80822)
- Fixes #9966
=> Fixes #9966 - Fix typo

reference/5.1/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.2/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.3/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.4/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md
Fix invalid SDDL string in example
I believe that moving a semicolon does not require me to go through lots of paperwork.
=> Fix invalid SDDL string in example

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md
Update about_scopes to clarify dot-source behavior
- Fixes [AB#81112](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/81112)
- Fixes #9965
=> Fixes #9965 - Update about_scopes to clarify dot-source behavior

reference/bread/toc.yml
Flattening breadcrumb structure to meet platform architecture requirements
Fixes incorrect breadcrumb structure that violates current platform requirements for breadcrumbs. This change should result in breadcrumb structure Learn / PowerShell 
=> Fixing breadcrumbs

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md
Clarify executable nature of scripts
- Fixes [AB#81991](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/81991)
- Fixes #9974
=> Fixes #9974 - Clarify executable nature of scripts

reference/7.2/PowerShellGet/Install-Module.md, reference/7.3/PowerShellGet/Install-Module.md, reference/7.4/PowerShellGet/Install-Module.md
Clarify default scopes
- Fixes [AB#82021](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/82021)
- Fixes #9975
=> Fixes #9975 - Clarify default scopes

reference/module/index.md
Updated PowerShell module browser quick filter for the Az PowerShell module to version 9.6.0
=> Updated azps quick filter to version 9.6.0

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
=> 4/11/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.3/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md
This change correctly points the link to about_Prompts in the about_Profiles articule.
- Resolves #10002
- Fixes [AB#85079](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/85079)
=> 4/14/2023 PM Publish

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-raspbian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md
Update release version numbers
=> Update release version numbers

reference/docs-conceptual/install/install-other-linux.md
The dockerfile was moved to a different folder, this PR corrects the link.
=> (MAINT) Fix broken link to GitHub

reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md
Add missing `run` and fix some formatting
- Fixes #10016 
=> Fix typo and formatting

.openpublishing.redirection.gallery.json
Fixes error in redirect_url for PSGallery article
=> Fix error in gallery redirection

reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md
Bit of an explanation about how `, $array |` works.
=> Update everything-about-arrays.md with explaining what ", $array |" does

reference/docs-conceptual/dev-cross-plat/vscode/using-vscode.md
Since it requires 5.1 with .NET 4.8 or 7.2+
=> Update VS Code extension requirements

reference/module/index.md
Updated PowerShell module browser quick filter to AzPS 9.7.1
=> Updated quick filter to azps 9.7.1

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
Fix Linux example
- Fixes [AB#88058](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/88058)
- Fixes #10029
=> Fixes #10029 - Fix Linux example

reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Random.md
Improve warning about crypto strength
=> Improve warning about crypto strength

reference/7.2/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
Fix typo and formatting
- Fixes [AB#88263](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/88263)
- Fixes #10039
=> Fixes #10039 - Fix typo and formatting

reference/docs-conceptual/windows-powershell/Starting-Windows-PowerShell.md
Correct instructions for running the ISE
- Also removed instructions for unsupported OS versions
- Fixes [AB#88900](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/88900)
- Fixes #10047
=> Fixes #10047 - Correct instructions for running the ISE

reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.2/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.3/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.4/Microsoft.PowerShell.Utility/Add-Member.md
Fix description and add example for SecondValue
- Fixes [AB#67240](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/67240)
=> Fix description and add example for SecondValue

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md
Update description of LASTEXITCODE
- Fixes [AB#89271](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/89271)
- Fixes #10046
=> Fixes #10046 - Update description of LASTEXITCODE

reference/docs-conceptual/community/community-update.yml
Add links to PowerBI
- Fixes [AB#89574](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/89574)
=> Add links to PowerBI

reference/7.2/Microsoft.PowerShell.Utility/Write-Progress.md, reference/7.3/Microsoft.PowerShell.Utility/Write-Progress.md, reference/7.4/Microsoft.PowerShell.Utility/Write-Progress.md
Link to the guidance for ANSI terminal styling, to enhance discoverability.
=> link to about_ansi_terminals

reference/docs-conceptual/how-to-use-docs.md
=> Update description of PDF

reference/5.1/Microsoft.PowerShell.Management/Stop-Computer.md, reference/7.2/Microsoft.PowerShell.Management/Stop-Computer.md, reference/7.3/Microsoft.PowerShell.Management/Stop-Computer.md, reference/7.4/Microsoft.PowerShell.Management/Stop-Computer.md
Clarify notes by adding links, and replacing "restart" with "shutdown"
qv. https://github.com/MicrosoftDocs/PowerShell-Docs/edit/main/reference/7.3/Microsoft.PowerShell.Management/Restart-Computer.md
=> Stop-Computer.md: Clarify NOTES

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/5.1/Microsoft.PowerShell.Management/Stop-Computer.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.2/Microsoft.PowerShell.Management/Stop-Computer.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.3/Microsoft.PowerShell.Management/Stop-Computer.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.4/Microsoft.PowerShell.Management/Stop-Computer.md, reference/docs-conceptual/lang-spec/chapter-09.md
=> 5/15/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
Add info about cmdlet name resolution
- Fixes [AB#90509](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/90509)
- Fixes #10079
Changes include:
- Converted to reference links
- Converted to contractions
- Reflow paragraphs
- Improved readability and concision
- Added information
=> Fixes #10079 - Add info about cmdlet name resolution

reference/docs-conceptual/community/2023-updates.md
=> Update contributor name

reference/module/index.md
Updated PowerShell module browser quick filter link for AzPS to version 10.0.0
=> Updated module browser quick filter for azps

reference/module/index.md
=> Update module browser links

reference/docs-conceptual/learn/application-control.md, reference/docs-conceptual/learn/experimental-features.md, reference/docs-conceptual/learn/security-features.md, reference/docs-conceptual/toc.yml
Document WDAC audit mode experimental feature
- Fixes [AB#91791](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/91791)
- Fixes #10091
=> Fixes #10091 - Document WDAC audit mode experimental feature

reference/docs-conceptual/lang-spec/chapter-04.md
Add link for type accelerators
- Fixes [AB#95444](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/95444)
- Fixes #10098
=> Fixes #10098 - Add link for type accelerators

reference/docs-conceptual/whats-new/cmdlet-versions.md
Add new cmdlet to release history article
- Fixes [AB#95821](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/95821)
- Fixes #10105
=> Fixes #10105 - Add new cmdlet to release history article

reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Syntax.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Command_Syntax.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Command_Syntax.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Command_Syntax.md
Improve parameter sets info & fix formatting
- Fixes [AB#95848](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/95848)
- Fixes #10104
=> Fixes #10104 - Improve parameter sets info & fix formatting

reference/docs-conceptual/install/install-debian.md
Fixes #10096 - Removed deprecated apt-key command
=> Fixes 10096 - removed deprecated apt-key command

reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md
Add -AsOSC52 parameter
- Fixes [AB#96655](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/96655)
- Fixes #9300
=> Fixes #9300 - Add -AsOSC52 parameter

reference/7.4/Microsoft.PowerShell.Management/Test-Connection.md
Document new -Detailed parameter
- Fixes [AB#96734](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/96734)
- Fixes #10037
=> Fixes #10037 - Document new -Detailed parameter

reference/7.4/Microsoft.PowerShell.Management/Test-Connection.md, reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md
Update Skip & SkipLast parameters for 7.4
- Fixes [AB#96753](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/96753)
- Fixes #10043
=> Fixes #10043 - Update Skip & SkipLast parameters for 7.4

reference/7.4/Microsoft.PowerShell.Utility/Get-SecureRandom.md
Remove references to old versions of Get-Random that Get-SecureRandom never had.
- Fixes #10124
=> Remove nonexistant history for Get-SecureRandom

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
Add -File parameter to Get-ChildItem example
- Fixes [AB#97122](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/97122)
- Fixes #10130
=> Fixes #10130 - Add -File parameter to Get-ChildItem example

reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Signing.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Signing.md
Prior to this change, the `about_Signing` topic included a casing typo.
This change:
- Corrects the typo, which fixes #10129
- Cleans up general formatting and prose
- Fixes [AB#97123](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/97123)
=> (GH-10129) Cleanup `about_Signing`

reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md
Prior to this change, the _Everything you wanted to know about PSCustomObject_ article had a broken link to a YouTube video which has since been made private.
This change:
- Removes the link
- Resolves #10143
- Fixes [AB#98125](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/98125)
=> (GH-10143) Remove broken YouTube link

reference/5.1/Microsoft.PowerShell.Utility/Write-Output.md, reference/7.2/Microsoft.PowerShell.Utility/Write-Output.md, reference/7.3/Microsoft.PowerShell.Utility/Write-Output.md, reference/7.4/Microsoft.PowerShell.Utility/Write-Output.md
Remove statement about writing to the console
- Fixes [AB#98124](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/98124)
- Fixes #10144
=> Fixes #10144 - Remove statement about writing to the console

reference/7.4/Microsoft.PowerShell.Utility/Get-SecureRandom.md
Fixes #10124
Remove another reference to old versions of Get-Random that Get-SecureRandom never had.
Updates #10125
Fixes #10124
=> Remove more non-history for Get-SecureRandom

reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.4/Microsoft.PowerShell.Utility/Get-SecureRandom.md
Fix a text typo to match the given example code
Fixes #10152
=> Update Get-Random Maximum float text to match code

reference/7.4/Microsoft.PowerShell.Core/About/about_Pipelines.md, reference/docs-conceptual/learn/experimental-features.md
Experimental feature for piping byte-stream data
- Fixes [AB#98614](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/98614)
- Fixes #10134
=> Fixes #10134 - Experimental feature for piping byte-stream data

reference/7.4/Microsoft.PowerShell.Core/Save-Help.md, reference/7.4/Microsoft.PowerShell.Core/Update-Help.md
Update -UICulture behavior for 7.4-p4
- Fixes [AB#98877](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/98877)
- Fixes #10148
=> Fixes #10148 - Update -UICulture behavior for 7.4-p4

reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.2/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.3/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.4/Microsoft.PowerShell.Utility/Add-Member.md
Update example 5 description
- Fixes [AB#99267](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/99267)
- Fixes #10167
=> Fixes #10167 - Update example 5 description

reference/docs-conceptual/install/install-raspbian.md
Update install instructions
- Fixes [AB#117339](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117339)
- Fixes #10180
- Fixes #10181
=> Fixes #10180 - Update install instructions

reference/5.1/Microsoft.PowerShell.Core/Get-Help.md, reference/7.2/Microsoft.PowerShell.Core/Get-Help.md, reference/7.3/Microsoft.PowerShell.Core/Get-Help.md, reference/7.4/Microsoft.PowerShell.Core/Get-Help.md
Clarify status of provider help
- Fixes [AB#117374](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117374)
=> Clarify status of provider help

reference/docs-conceptual/learn/experimental-features.md
Document PSFeedbackProvider
- Fixes [AB#117452](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117452)
- Fixes #9294
=> Fixes #9294 - Document PSFeedbackProvider

reference/docs-conceptual/learn/experimental-features.md
Add PSWindowsNativeCommandArgPassing
- Fixes [AB#117455](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117455)
- Fixes #9739
=> Fixes #9739 - Add PSWindowsNativeCommandArgPassing

reference/7.4/Microsoft.PowerShell.Utility/Write-Progress.md
Activity param is now optional
- Fixes [AB#117456](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117456)
- Fixes #9864
=> Fixes #9864 - Activity param is now optional

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell-Core.md
Updated name based on changes in macOS Ventura
=> Updated name based on changes in macos ventura

reference/docs-conceptual/install/install-rhel.md
Add setup steps for RHEL 9
- Fixes [AB#117530](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117530)
- Fixes #10193
=> Fixes #10193 - Add setup steps for RHEL 9

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
Update .NET version for PowerShell 7.4
- Fixes [AB#117535](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117535)
=> Update .NET version for PowerShell 7.4

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md
Add missing parameter attributes & fix formatting
- Fixes [AB#117560](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117560)
- Fixes #10136
=> Fixes #10136 - Add missing parameter attributes & fix formatting

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
Expand information about variable attributes
- Rather than add more attributes and duplicate information, I expand the description and purpose for attributes and link to existing documentation.
- Also did an editorial pass that includes links, contractions, and reflow.
- Fixes [AB#117677](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117677)
- Fixes #10138
=> Fixes #10138 - Expand information about variable attributes

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
Refactor performance tests
- Fixes [AB#117731](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117731)
- Fixes #10201
=> Fixes #10201 - Refactor performance tests

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
=> 06/23 PM Publishing

reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md
Fix parameter error in example
- Fixes [AB#117843](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117843)
- Fixes #10205
=> Fixes #10205 - Fix parameter error in example

reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.4/Microsoft.PowerShell.Utility/Get-SecureRandom.md
Clarify how -Count works
- Fixes [AB#117848](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/117848)
- Fixes #10204
=> Fixes #10204 - Clarify how -Count works

reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.4/Microsoft.PowerShell.Utility/Get-SecureRandom.md, reference/docs-conceptual/learn/deep-dives/everything-about-hashtable.md
=> 6/26/2023 PM Publish

reference/docs-conceptual/community/2020-updates.md, reference/docs-conceptual/community/2022-updates.md, reference/docs-conceptual/samples/Creating-Get-WinEvent-queries-with-FilterHashtable.md
Fix broken links from report
- Fixes [AB#96583](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/96583)
=> Fix broken links from report

reference/7.4/Microsoft.PowerShell.Management/Test-Connection.md
Update parameter sets for Test-Connection
- Fixes [AB#118773](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/118773)
- Fixes #10221
=> Fixes #10221 - Update parameter sets for Test-Connection

reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Update parameters for webcmdlets
- Fixes [AB#118775](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/118775)
- Fixes #10222
=> Fixes #10222 - Update parameters for webcmdlets

reference/7.2/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.3/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
Update PSStyle info for 7.4-p4
- Fixes [AB#118783](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/118783)
- Fixes #10223
=> Fixes #10223 - Update PSStyle info for 7.4-p4

reference/5.1/Microsoft.PowerShell.Management/New-Item.md, reference/7.2/Microsoft.PowerShell.Management/New-Item.md, reference/7.3/Microsoft.PowerShell.Management/New-Item.md, reference/7.4/Microsoft.PowerShell.Management/New-Item.md
Document -Force behavior when creating Junctions
- Fixes [AB#120207](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/120207)
- Fixes #10227
=> Fixes #10227 - Document -Force behavior when creating Junctions

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
Update release notes for 7.4-p4
- Fixes [AB#121739](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/121739)
- Fixes #10220
=> Fixes #10220 - Update release notes for 7.4-p4

reference/docs-conceptual/install/install-debian.md
Remove unneeded apt command
- Fixes [AB#123193](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/123193)
- Fixes #10235
=> Fixes #10235 - Remove unneeded apt command

reference/5.1/Microsoft.PowerShell.Management/Get-Process.md, reference/7.2/Microsoft.PowerShell.Management/Get-Process.md, reference/7.3/Microsoft.PowerShell.Management/Get-Process.md, reference/7.4/Microsoft.PowerShell.Management/Get-Process.md, reference/docs-conceptual/install/install-debian.md
=> 7/3/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Object_Creation.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Object_Creation.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Object_Creation.md
=> Replace "Tf" with "If"

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
=> Replace "enumerateion" with "enumeration"

reference/module/index.md
Updated the PowerShell module browser quick filter link for Az to version 10.1.0.
=> Updated azps quick filter link

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Object_Creation.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Object_Creation.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Remote.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Object_Creation.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Remote.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Object_Creation.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Remote.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Remote_Disconnected_Sessions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Remote_Requirements.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md, reference/docs-conceptual/learn/remoting/Running-Remote-Commands.md, reference/module/index.md
=> 7/5/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Module_Manifests.md
Add notes about other PSData usage
- Fixes [AB#123824](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/123824)
- Fixes #10137
=> Fixes #10137 - Add notes about other PSData usage

reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Module_Manifests.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Module_Manifests.md
* Add notes about other PSData usage
* fix urls
=> 7/7/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md, reference/7.2/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md, reference/7.3/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md, reference/7.4/Microsoft.PowerShell.Core/About/about_FileSystem_Provider.md
This change:
- Fixes a typo in the `about_FileSystem_Provider` documentation
- Resolves #10260
- Fixes [AB#124105](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/124105)
=> (GH-10260) Fix typo in `about_FileSystem_Provider`

reference/5.1/Microsoft.PowerShell.Core/Remove-Module.md, reference/7.2/Microsoft.PowerShell.Core/Remove-Module.md, reference/7.3/Microsoft.PowerShell.Core/Remove-Module.md, reference/7.4/Microsoft.PowerShell.Core/Remove-Module.md
Add example for OnRemove
- Fixes [AB#124179](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/124179)
- Fixes #10265
=> Fixes #10265 - Add example for OnRemove

reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
Restore NoRunspaceAffinity info
- Restore content removed in error by #10138
=> Fixes #10138 - Restore NoRunspaceAffinity info

reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md
=> 7/13/2023 PM Publish

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-raspbian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
Update version number for July releases
- Fixes #125108
=> Fixes #125108 - Update version number for July releases

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-raspbian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
=> 7/14/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md
Update path information
- Fixes [AB#125184](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/125184)
- Fixes #10275
=> Fixes #10275 - Update path information

reference/5.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md
=> 7/17/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
Add lists of variables to the top of the articles
- Fixes [AB#125327](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/125327)
- Fixes #10279
=> Fixes #10279 - Add lists of variables to the top of the articles

reference/5.1/PSReadLine/About/about_PSReadLine.md, reference/7.2/PSReadLine/About/about_PSReadLine.md, reference/7.3/PSReadLine/About/about_PSReadLine.md, reference/7.4/PSReadLine/About/about_PSReadLine.md
This points users to examples in the Set-PSReadLineOption doc for filtering out specific history keyterms in the docs that outline what PSRL does with history.
=> Adding reference to example for history handler for PSRL

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/5.1/PSReadLine/About/about_PSReadLine.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.2/PSReadLine/About/about_PSReadLine.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.3/PSReadLine/About/about_PSReadLine.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.4/PSReadLine/About/about_PSReadLine.md
=> 7/18/2023 PM Publish

reference/5.1/PSReadLine/Set-PSReadLineOption.md, reference/7.2/PSReadLine/Set-PSReadLineOption.md, reference/7.3/PSReadLine/Set-PSReadLineOption.md, reference/7.4/PSReadLine/Set-PSReadLineOption.md
* Adding example for command validation handler in PSRL docs
* Editorial changes
---------
=> 7/19/2023 PM Publish

reference/docs-conceptual/dev-cross-plat/vscode/understanding-file-encoding.md
* Update understanding-file-encoding.md
* add correct em-dash example
---------
=> 7/20/2023 PM Publish

reference/7.2/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md
Fix DebugPreference values
- Fixes [AB#133304](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/133304)
- Fixes #10290
=> Fixes #10290 - Fix DebugPreference values

reference/5.1/Microsoft.PowerShell.Core/About/about_Logging.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
Fix registry path information for policies
- Fixes [AB#141625](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/141625)
- Fixes #10298
=> Fixes #10298 - Fix registry path information for policies

reference/docs-conceptual/discover-powershell.md
Change the sentence:
From 'You For example, you want to display only [...]'
To 'For example, you want to display only [...]'
=> Correct the sentence in the discover-powershell.md file

reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
Update 10 fold loop to agree with 3 fold output
Fixes #10303
=> Update 10 fold loop to agree with 3 fold output

reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/docs-conceptual/discover-powershell.md
=> 7/26/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Split-Path.md, reference/7.2/Microsoft.PowerShell.Management/Split-Path.md, reference/7.3/Microsoft.PowerShell.Management/Split-Path.md, reference/7.4/Microsoft.PowerShell.Management/Split-Path.md
Improve consistency and readability of parameters for Split-Path
=> Split-Path Parameter Improvement

reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/5.1/Microsoft.PowerShell.Management/Split-Path.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.2/Microsoft.PowerShell.Management/Split-Path.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.3/Microsoft.PowerShell.Management/Split-Path.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.4/Microsoft.PowerShell.Management/Split-Path.md
=> 7/31/2023 PM Publish

reference/module/index.md
Updated the PowerShell module browser quick filter for Az
=> Updated ps module browser quick filter for azps

reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/docs-conceptual/community/2023-updates.md, reference/docs-conceptual/community/hall-of-fame.md, reference/module/index.md
=> 8/1/2023 PM Publish

reference/7.2/Microsoft.PowerShell.Utility/Get-Host.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Host.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Host.md
Remove invalid example
- Fixes [AB#144476](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/144476)
- Fixes #10324
=> Fixes #10324 - Remove invalid example

reference/5.1/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Host.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Host.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Assignment_Operators.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Host.md
=> 8/2/2023 PM Publish

reference/7.2/Microsoft.PowerShell.Utility/Add-Type.md, reference/7.3/Microsoft.PowerShell.Utility/Add-Type.md, reference/7.4/Microsoft.PowerShell.Utility/Add-Type.md
Remove erroneous note about CompilerOptions
- Fixes [AB#147573](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/147573)
- Fixes #10330
=> Fixes #10330 - Remove erroneous note about CompilerOptions

reference/5.1/Microsoft.PowerShell.LocalAccounts/Add-LocalGroupMember.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Disable-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Enable-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroupMember.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalGroupMember.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Rename-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Rename-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Set-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Set-LocalUser.md
Branding update for Microsoft Entra ID
- Fixes [AB#96350](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/96350)
=> Branding update for Microsoft Entra ID

reference/5.1/Microsoft.PowerShell.LocalAccounts/Add-LocalGroupMember.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Disable-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Enable-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalGroupMember.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Get-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalGroupMember.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Rename-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Rename-LocalUser.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Set-LocalGroup.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Set-LocalUser.md
=> 8/16/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Clarify behavior of containment operators
- Fixes [AB#147830](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/147830)
- Fixes #10337
=> Fixes #10337 - Clarify behavior of containment operators

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Enum.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Requires.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Using.md, reference/5.1/Microsoft.PowerShell.Core/Import-Module.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Enum.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Requires.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Using.md, reference/7.2/Microsoft.PowerShell.Core/Import-Module.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Enum.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Requires.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Using.md, reference/7.3/Microsoft.PowerShell.Core/Import-Module.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Enum.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Group_Policy_Settings.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Requires.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Using.md, reference/7.4/Microsoft.PowerShell.Core/Import-Module.md
=> 8/17/2023 PM Publish

reference/7.4/Microsoft.PowerShell.Management/Wait-Process.md
Document new parameters for Wait-Process
- Fixes [AB#147989](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/147989)
- Fixes #10162
=> Fixes #10162 - Document new parameters for Wait-Process

reference/7.4/Microsoft.PowerShell.Management/Wait-Process.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
=> 8/18/2023 PM Publish

reference/docs-conceptual/community/contributing/product-terminology.md
[BULK] DocuTune - Add ms.custom tag "has-azure-ad-ps-ref" to track Azure AD PowerShell references
CorrelationId: 1960a274-3b36-46bb-86ce-f92e1539efdf
#docutune
=> [BULK] DocuTune - Add ms.custom tag "has-azure-ad-ps-ref" to track Azure AD PowerShell references

reference/5.1/Microsoft.PowerShell.Core/About/about_Prompts.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Prompts.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Prompts.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Prompts.md
Fix default prompt and other minor edits
- Fixes [AB#148899](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/148899)
- Fixes #10357
=> Fixes #10357 - Fix default prompt and other minor edits

reference/5.1/PSReadLine/PSReadLine.md, reference/5.1/PSReadLine/Set-PSReadLineOption.md, reference/7.2/PSReadLine/Set-PSReadLineOption.md, reference/7.3/PSReadLine/Set-PSReadLineOption.md, reference/7.4/PSReadLine/Set-PSReadLineOption.md
Update docs for PromptText parameter
- Fixes [AB#149095](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/149095)
- Fixes #10361
=> Fixes #10361 - Update docs for PromptText parameter

reference/docs-conceptual/windows-powershell/wmf/overview.md
=> Update WMF support dates

reference/7.4/Microsoft.PowerShell.Utility/New-Guid.md
Document new parameters for New-Guid
- Fixes [AB#153565](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/153565)
- Fixes #10296
=> Fixes #10296 - Document new parameters for New-Guid

.openpublishing.redirection.dsc.json
Remove about topics from DSC redirection
This should fix the 404 problem we have with the about topics since we moved the files to a new repo.
=> Remove about topics from DSC redirection

.openpublishing.redirection.dsc.json, reference/7.4/Microsoft.PowerShell.Utility/New-Guid.md, reference/docs-conceptual/windows-powershell/wmf/overview.md
=> 8/28/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md, reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md, reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md, reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md
Prior to this PR, example 1 of `Clear-Host` does not follow the style-guide. The example should be Illustrative and therefore be in the same code fence.
- Resolves #10372
=> Quality: Edited example 1 to align with the style guide

reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md
Clarify the scope
- Fixes [AB#153948](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/153948)
- Fixes #10374
=> Fixes #10374 - Clarify the scope

reference/docs-conceptual/install/community-support.md, reference/module/index.md
=> 9/6/2023 PM Publish

reference/7.2/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md, reference/7.3/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md, reference/7.4/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md
Prior to this PR, the formatting for EXAMPLE 1 in `Disable-ExperimentalFeature` does not follow the formatting rules.
- Fixes #10400 
=> Quality: Fixed code formatting for Disable-ExperimentalFeature

reference/5.1/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.2/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.3/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md
Add note about possible error
- Fixes [AB#158836](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/158836)
- Fixes #10406
=> Fixes #10406 - Add note about possible error

reference/5.1/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.2/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.3/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md
* Add note about possible error
* Apply suggestions from code review
* Sync changes across versions
* sync Example 3 change
---------
=> 9/12/2023 PM Publish

.github/ISSUE_TEMPLATE/04-customer-feedback.yml
=> Fix description

.github/ISSUE_TEMPLATE/04-customer-feedback.yml
=> 9/13/2023 PM Publish

.github/ISSUE_TEMPLATE/04-customer-feedback.yml
=> 9/14/2023 PM Publish

.github/ISSUE_TEMPLATE/04-customer-feedback.yml
=> Fix emoji in template

reference/5.1/Microsoft.PowerShell.Core/About/about_Locations.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Locations.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Locations.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Locations.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Path_Syntax.md
Update slash character description
- Fixes [AB#160874](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/160874)
- Fixes #10426
=> Fixes #10426 - Update slash character description

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
This change updates the version strings in the install documentation to reflect the new `v7.3.7` and `v7.2.14` releases.
=> (MAINT) Update PowerShell versions for latest stable

.github/ISSUE_TEMPLATE/04-customer-feedback.yml, reference/5.1/Microsoft.PowerShell.Core/About/about_Locations.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Locations.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Locations.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Locations.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
=> 9/19/2023 PM Publish

reference/docs-conceptual/learn/deep-dives/everything-about-if.md
Fixes a typo where the author may have intended to write "_there isn't_" or "_there's nothing_".
=> Fix typo in everything-about-if.md

reference/5.1/Microsoft.PowerShell.Management/Split-Path.md, reference/7.2/Microsoft.PowerShell.Management/Split-Path.md, reference/7.3/Microsoft.PowerShell.Management/Split-Path.md, reference/7.4/Microsoft.PowerShell.Management/Split-Path.md
Fix example 3
- Fixes [AB#161633](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161633)
=> Fix example 3

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md
Add example for listing environment variables
- Fixes [AB#161629](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161629)
=> Add example for listing environment variables

reference/5.1/Microsoft.PowerShell.Management/Set-Service.md, reference/7.2/Microsoft.PowerShell.Management/Set-Service.md, reference/7.3/Microsoft.PowerShell.Management/Set-Service.md, reference/7.4/Microsoft.PowerShell.Management/Set-Service.md
Add example showing multiple services
- Fixes [AB#161624](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161624)
=> Add example showing multiple services

reference/docs-conceptual/community/2023-updates.md
=> Update docs changes

reference/docs-conceptual/community/2023-updates.md, reference/docs-conceptual/toc.yml
=> 9/21/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/Get-Job.md, reference/7.2/Microsoft.PowerShell.Core/Get-Job.md, reference/7.3/Microsoft.PowerShell.Core/Get-Job.md, reference/7.4/Microsoft.PowerShell.Core/Get-Job.md
=> 09/22 PM Publishing

reference/docs-conceptual/install/community-support.md
=> Add jq to prerequisite packages installed before pwsh

reference/docfx.json
Configure Open Source Feedback control
- Fixes [AB#159493](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/159493)
Prior to this PR, this docset used the old GitHub feedback control. This PR configures the new feedback control.
This PR also cleaned up the globbing patterns in the docfx.json by changing `**` to `*` in the leaf portion of the glob pattern.
=> Configure Open Source Feedback control

reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-ubuntu.md
Fix typos
- Fixes [AB#163898](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/163898)
- Fixes #10460
=> Fixes #10460 - Fix typos

reference/5.1/Microsoft.PowerShell.Utility/Group-Object.md
=> 9/27/2023 PM Publish

reference/docfx.json
Optimize globbing in docfx.json
=> Optimize globbing in docfx.json

reference/docfx.json
=> 9/28/2023 PM Publish

.github/ISSUE_TEMPLATE/04-customer-feedback.yml, reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/docfx.json, reference/docs-conceptual/learn/experimental-features.md, reference/docs-conceptual/learn/security-features.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
Updates for 7.4-p6 release
- Fixes [AB#164687](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/164687)
=> Updates for 7.4-p6 release

.github/ISSUE_TEMPLATE/04-customer-feedback.yml, reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/5.1/Microsoft.PowerShell.Core/Start-Job.md, reference/5.1/Microsoft.PowerShell.Core/Stop-Job.md, reference/5.1/Microsoft.PowerShell.Core/Wait-Job.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.2/Microsoft.PowerShell.Core/Start-Job.md, reference/7.2/Microsoft.PowerShell.Core/Stop-Job.md, reference/7.2/Microsoft.PowerShell.Core/Wait-Job.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.3/Microsoft.PowerShell.Core/Start-Job.md, reference/7.3/Microsoft.PowerShell.Core/Stop-Job.md, reference/7.3/Microsoft.PowerShell.Core/Wait-Job.md, reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.4/Microsoft.PowerShell.Core/Start-Job.md, reference/7.4/Microsoft.PowerShell.Core/Stop-Job.md, reference/7.4/Microsoft.PowerShell.Core/Wait-Job.md, reference/docfx.json, reference/docs-conceptual/learn/experimental-features.md, reference/docs-conceptual/learn/security-features.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
=> 09/29 PM Publishing 

reference/5.1/PSReadLine/Set-PSReadLineOption.md, reference/7.2/PSReadLine/Set-PSReadLineOption.md, reference/7.3/PSReadLine/Set-PSReadLineOption.md, reference/7.4/PSReadLine/Set-PSReadLineOption.md
This change is to give better clarification for the use of HistorySaveStyle for Set-PSReadLineOption, addresses: https://github.com/PowerShell/PSReadLine/issues/3785
=> Adding some details for HistorySaveStyle

reference/docs-conceptual/developer/help/examples-of-comment-based-help.md
Fix comment-based help examples
- Fixes [AB#167561](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/167561)
- Fixes #10492
=> Fixes #10492 - Fix comment-based help examples

reference/5.1/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/5.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md, reference/7.2/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/7.2/Microsoft.PowerShell.Core/Enable-PSRemoting.md, reference/7.3/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/7.3/Microsoft.PowerShell.Core/Enable-PSRemoting.md, reference/7.4/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/7.4/Microsoft.PowerShell.Core/Enable-PSRemoting.md
Prior to this PR, Enable & Disable-PSRemoting had examples which does not allign with the [style guidelines](https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide?view=powershell-7.3#formatting-command-syntax-elements)
Minor edits:
- [Added full property names](https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide?view=powershell-7.3#dont-use-aliases-in-examples)
- Fixes #10496
=> Quality: Cleanup of Enable & Disable -PSRemoting examples

reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/5.1/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/7.2/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/7.2/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/7.3/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/7.3/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/7.4/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/7.4/Microsoft.PowerShell.Archive/Expand-Archive.md
Update description of -Force parameter
- Fixes [AB#167680](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/167680)
- Fixes #10495
=> Fixes #10495 - Update description of -Force parameter

reference/5.1/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/5.1/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/5.1/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/5.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md, reference/7.2/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/7.2/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/7.2/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/7.2/Microsoft.PowerShell.Core/Enable-PSRemoting.md, reference/7.3/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/7.3/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/7.3/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/7.3/Microsoft.PowerShell.Core/Enable-PSRemoting.md, reference/7.4/Microsoft.PowerShell.Archive/Compress-Archive.md, reference/7.4/Microsoft.PowerShell.Archive/Expand-Archive.md, reference/7.4/Microsoft.PowerShell.Core/Disable-PSRemoting.md, reference/7.4/Microsoft.PowerShell.Core/Enable-PSRemoting.md
=> 10/06 PM Publishing

reference/docs-conceptual/dev-cross-plat/security/securing-restricted-sessions.md, reference/docs-conceptual/learn/remoting/jea/security-considerations.md, reference/docs-conceptual/toc.yml
Add article about securing restricted sessions
- Fixes [AB#168747](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/168747)
=> Add article about securing restricted sessions

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
Update version numbers
- Fixes [AB#169159](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/169159)
=> Update version numbers

reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSCustomObject.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PSCustomObject.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSCustomObject.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml, reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md
=> 10/11/2023 PM Publish

reference/5.1/PSReadLine/About/about_PSReadLine.md, reference/5.1/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.2/PSReadLine/About/about_PSReadLine.md, reference/7.2/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.3/PSReadLine/About/about_PSReadLine.md, reference/7.3/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.4/PSReadLine/About/about_PSReadLine.md, reference/7.4/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.4/PSReadLine/Get-PSReadLineOption.md, reference/7.4/PSReadLine/Set-PSReadLineOption.md
Update PSReadLine for 2.3.4 GA release
- Fixes [AB#168837](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/168837)
=> Update PSReadLine for 2.3.4 GA release

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
Update instructions for macOS
- Fixes [AB#169451](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/169451)
- Fixes #10506
=> Fixes #10506 - Update instructions for macOS

reference/5.1/Microsoft.PowerShell.Management/Add-Content.md, reference/5.1/PSReadLine/About/about_PSReadLine.md, reference/5.1/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.2/Microsoft.PowerShell.Management/Add-Content.md, reference/7.2/PSReadLine/About/about_PSReadLine.md, reference/7.2/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.3/Microsoft.PowerShell.Management/Add-Content.md, reference/7.3/PSReadLine/About/about_PSReadLine.md, reference/7.3/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.4/Microsoft.PowerShell.Management/Add-Content.md, reference/7.4/PSReadLine/About/about_PSReadLine.md, reference/7.4/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.4/PSReadLine/Get-PSReadLineOption.md, reference/7.4/PSReadLine/Set-PSReadLineOption.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
=> 10/12/2023 PM Publish

reference/docfx.json
Add config items for the standard feedback control
- Fixes [AB#169517](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/169517)
=> Add config items for the standard feedback control

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
Copy changes from PR to all versions
- Fixes [AB#169552](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/169552)
- Fixes #10521
=> Fixes #10521 - Copy changes from PR to all versions

reference/5.1/Microsoft.PowerShell.Management/Get-Content.md, reference/7.2/Microsoft.PowerShell.Management/Get-Content.md, reference/7.3/Microsoft.PowerShell.Management/Get-Content.md, reference/7.4/Microsoft.PowerShell.Management/Get-Content.md
Negative ReadCount read all content
- Fixes [AB#169561](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/169561)
- Fixes #10520
=> Fixes #10520 - Negative ReadCount read all content

reference/5.1/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.2/CimCmdlets/Get-CimSession.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Variable.md, reference/7.2/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.3/Microsoft.PowerShell.Core/About/about_CimSession.md, reference/7.3/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_CimSession.md, reference/7.4/Microsoft.PowerShell.Management/Set-ItemProperty.md, reference/7.4/PSReadLine/About/about_PSReadLine_Functions.md
Update online Urls
- Fixes [AB#169582](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/169582)
=> Update online Urls

reference/5.1/Microsoft.PowerShell.Core/About/about_WMI.md, reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md
Fix formatting and clarify return results
- Fixes [AB#169582](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/169582)
=> Fix formatting and clarify return results

reference/5.1/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.2/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.3/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.4/PSReadLine/About/about_PSReadLine_Functions.md
Fix description of vi mode f,F,t,T commands
- Fixes #10535
=> Fixes #10535 - Fix description of vi mode f,F,t,T commands

reference/5.1/PSReadLine/Set-PSReadLineOption.md, reference/7.2/PSReadLine/Set-PSReadLineOption.md, reference/7.3/PSReadLine/Set-PSReadLineOption.md, reference/7.4/PSReadLine/Set-PSReadLineOption.md
Clarify the wording for `HistoryNoDuplicates` for PSreadLine options
Related: https://github.com/PowerShell/PSReadLine/issues/3836
=> Clarified wording of HistoryNoDuplicates

reference/5.1/PSReadLine/About/about_PSReadLine_Functions.md, reference/5.1/PSReadLine/Set-PSReadLineOption.md, reference/7.2/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.2/PSReadLine/Set-PSReadLineOption.md, reference/7.3/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.3/PSReadLine/Set-PSReadLineOption.md, reference/7.4/PSReadLine/About/about_PSReadLine_Functions.md, reference/7.4/PSReadLine/Set-PSReadLineOption.md, reference/docs-conceptual/learn/shell/running-commands.md
=> 10/16/2023 PM Publish

reference/5.1/Microsoft.PowerShell.LocalAccounts/Add-LocalGroupMember.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalGroupMember.md, reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md
Applying Azure AD rebranding changes as announced on July 11, 2023 and outlined in https://aka.ms/AzureADNewName. Changes are part of the Microsoft-wide rebranding effort.
CorrelationId: 2520d58e-25ff-469e-af14-2834d2a1505e
PointOfContact: @CelesteDG
#docutune
=> [BULK] - DocuTune - Rebranding of Azure Active Directory to Microsoft Entra terminology

reference/docs-conceptual/samples/Working-with-Files-and-Folders.md
Remove outdated examples using boot.ini
- Fixes [AB#171433](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/171433)
- Fixes #10541
=> Fixes #10541 - Remove outdated examples using boot.ini

reference/5.1/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md, reference/7.2/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md, reference/7.3/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md, reference/7.4/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md
Add examples for decrypting events
- Fixes [AB#161625](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161625)
=> Add examples for decrypting events

reference/5.1/Microsoft.PowerShell.LocalAccounts/Add-LocalGroupMember.md, reference/5.1/Microsoft.PowerShell.LocalAccounts/Remove-LocalGroupMember.md, reference/5.1/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md, reference/7.2/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md, reference/7.3/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md, reference/7.4/Microsoft.PowerShell.Security/Unprotect-CmsMessage.md, reference/docs-conceptual/learn/remoting/PS-remoting-second-hop.md, reference/docs-conceptual/samples/Working-with-Files-and-Folders.md
=> 10/18/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Utility/Write-Information.md, reference/7.2/Microsoft.PowerShell.Utility/Write-Information.md, reference/7.3/Microsoft.PowerShell.Utility/Write-Information.md, reference/7.4/Microsoft.PowerShell.Utility/Write-Information.md
Add example showing how to access Tag information
- Fixes [AB#171616](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/171616)
- Fixes #10546
=> Fixes #10546 - Add example showing how to access Tag information

reference/5.1/Microsoft.PowerShell.Utility/Write-Information.md, reference/7.2/Microsoft.PowerShell.Utility/Write-Information.md, reference/7.3/Microsoft.PowerShell.Utility/Write-Information.md, reference/7.4/Microsoft.PowerShell.Utility/Write-Information.md
=> 10/19/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Foreach.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Foreach.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Foreach.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Foreach.md
Editorial review of about_foreach
- Fixes [AB#161631](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/161631)
=> Editorial review of about_foreach

reference/5.1/Microsoft.PowerShell.Core/About/about_Foreach.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Updatable_Help.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Foreach.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Updatable_Help.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Foreach.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Updatable_Help.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Foreach.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Updatable_Help.md
=> 10/20/2023 PM Publish

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
=> Fix typo in spelling of once

reference/5.1/Microsoft.PowerShell.Management/Get-Content.md, reference/7.2/Microsoft.PowerShell.Management/Get-Content.md, reference/7.3/Microsoft.PowerShell.Management/Get-Content.md, reference/7.4/Microsoft.PowerShell.Management/Get-Content.md
Removed duplicate content
- Fixes [AB#173406](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/173406)
- Fixes #10559
=> Fixes #10559 - Removed duplicate content

reference/docs-conceptual/install/install-ubuntu.md
=> 10/24/2023 PM Publish

reference/7.4/Microsoft.PowerShell.Utility/Set-Alias.md
Fixed typo in `Set-Alias.md`, replaced `enclose it single quotes` to `enclose it in single quotes`.
=> Fixed typo, `enclose it single` to `enclose it in single`

reference/5.1/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7.2/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7.3/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7.4/Microsoft.PowerShell.Utility/Set-Alias.md
This change updates the `Set-Alias` reference documentation, cleaning up syntax, grammar, and example code.
=> (MAINT) Cleanup `Set-Alias`

reference/7.4/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
Update release notes for 7.4-rc.1
- Fixes [AB#173908](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/173908)
=> Update release notes for 7.4-rc.1

reference/5.1/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/7.2/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/7.3/Microsoft.PowerShell.Utility/Set-Alias.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/7.4/Microsoft.PowerShell.Management/Test-Connection.md, reference/7.4/Microsoft.PowerShell.Utility/Set-Alias.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
=> 10/25/2023 PM Publish

reference/includes/alpine-support.md, reference/includes/debian-support.md, reference/includes/macos-support.md, reference/includes/rhel-support.md, reference/includes/ubuntu-support.md
=> Update lifecycle docs

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/includes/alpine-support.md, reference/includes/debian-support.md, reference/includes/macos-support.md, reference/includes/rhel-support.md, reference/includes/ubuntu-support.md
=> 10/26/2023 PM Publish

reference/7.2/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md
Remove duplicate information
- Fixes #10586
=> Fixes #10586 - Remove duplicate information

reference/7.2/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
=> 10/27/2023 PM Publish

reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
=> Add Login to Connect synonyms 

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md, reference/docs-conceptual/install/install-rhel.md
=> 10/30/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Add-Content.md, reference/7.2/Microsoft.PowerShell.Management/Add-Content.md, reference/7.3/Microsoft.PowerShell.Management/Add-Content.md, reference/7.4/Microsoft.PowerShell.Management/Add-Content.md
Remove copy/paste error in description
- Fixes #10597
- Fixes [AB#176992](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/176992)
=> Fixes #10597 - Remove copy/paste error in description

reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Syntax.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Command_Syntax.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Command_Syntax.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Command_Syntax.md
Refactor descriptions of syntax
- Fixes [AB#176993](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/176993)
- Fixes #10569
=> Fixes #10569 - Refactor descriptions of syntax

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
Add INSTALLFOLDER to MSI instructions
- Fixes [AB#177394](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/177394)
- Fixes #10598
=> Fixes #10598 - Add INSTALLFOLDER to MSI instructions

reference/5.1/Microsoft.PowerShell.Management/Start-Process.md, reference/7.2/Microsoft.PowerShell.Management/Start-Process.md, reference/7.3/Microsoft.PowerShell.Management/Start-Process.md, reference/7.4/Microsoft.PowerShell.Management/Start-Process.md, reference/docs-conceptual/community/2023-updates.md, reference/docs-conceptual/community/hall-of-fame.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
=> 11/1/2023 PM Publish

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell.md
Add note about OS upgrades overwriting configs
- Fixes [AB#180635](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/180635)
- Related to PowerShell/PowerShell#20625
=> Fixes #20625 - Add note about OS upgrades overwriting configs

reference/docs-conceptual/learn/remoting/SSH-Remoting-in-PowerShell.md
=> 11/6/2023 PM Publish

reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
Add note about support for Brotli compression
- Fixes #10616
=> Fixes #10616 - Add note about support for Brotli compression

reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
=> 11/8/2023 PM Publish

reference/7.4/Microsoft.PowerShell.Core/About/about_Requires.md
Removed a last reference to snap-ins. The feature was removed in the PowerShell PR [19320](https://github.com/PowerShell/PowerShell/pull/19320)
=> Remove reference to snapins in docs article "about Requires"

reference/7.4/Microsoft.PowerShell.Core/About/about_Requires.md
=> 11/9/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Methods.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Properties.md, reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Methods.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes_Properties.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Methods.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes_Properties.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Methods.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes_Properties.md
=> 11/13/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/module/index.md
=> 11/14/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
Fix example output diffs for each version
- Fixes #10636
=> Fixes #10636 - Fix example output diffs for each version

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
Fixes [AB#183594](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/183594)
=> Update docs for 7.4 GA release

reference/docs-conceptual/toc.yml
Update TOC entry for 7.4 relnotes
=> Update TOC entry for 7.4 relnotes

reference/5.1/Microsoft.PowerShell.Core/Where-Object.md, reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.2/Microsoft.PowerShell.Core/Where-Object.md, reference/7.2/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.3/Microsoft.PowerShell.Core/Where-Object.md, reference/7.3/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.4/Microsoft.PowerShell.Core/Where-Object.md, reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md
Prior to this change:
- The **UseNewRunspace** parameter of the `ForEach-Object` cmdlet wasn't included in the cmdlet syntax for any parameter set.
- The "Notes" section of `ForEach-Object` directed users to the wrong example for thread safety.
- The `Where-Object` reference documentation used the `where` alias throughout the article, not just when discussing the alias specifically.
- The **SkipIndex** parameter of the `Select-Object` cmdlet was missing a description entirely and didn't indicate the version of PowerShell it was added in.
This change:
- Adds the **UseNewRunspace** parameter to the `ParallelParameterSet` syntax of the `ForEach-Object` cmdlet reference.
- Fixes #10642
- Fixes [AB#183543](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/ …
=> 11/16/2023 PM Publish

reference/docs-conceptual/install/Installing-PowerShell.yml, reference/docs-conceptual/whats-new/overview.yml, reference/index.yml
- Added PowerShell 7.4
- Removed the "preview" designation of PowerShell 7.3
- Replaced the vague wording "previous versions" with PowerShell 6. This page is full of versions that are considered "previous."
=> Overview.yml: The much-needed update to links and wording

reference/docs-conceptual/how-to-use-docs.md, reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md, reference/includes/alpine-support.md, reference/includes/debian-support.md, reference/includes/macos-support.md, reference/includes/rhel-support.md, reference/includes/ubuntu-support.md, reference/includes/windows-support.md
=> Update 7.4 refs

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md, reference/docs-conceptual/learn/experimental-features.md
=> 11/20/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Get-Content.md, reference/7.2/Microsoft.PowerShell.Management/Get-Content.md, reference/7.3/Microsoft.PowerShell.Management/Get-Content.md, reference/7.4/Microsoft.PowerShell.Management/Get-Content.md
Update notes about -Wait
- Fixes [AB#186475](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/186475)
- Fixes #10668
=> Fixes #10668 - Update notes about -Wait

reference/5.1/Microsoft.PowerShell.Management/Get-Content.md, reference/7.2/Microsoft.PowerShell.Management/Get-Content.md, reference/7.3/Microsoft.PowerShell.Management/Get-Content.md, reference/7.4/Microsoft.PowerShell.Management/Get-Content.md
=> 11/27/2023 PM Publish

reference/docfx.json
Update product name for UUF configuration
- Fixes [AB#186522](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/186522)
=> Update product name for UUF configuration

reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Script_Blocks.md
Fix typo
- Fixes [AB#186730](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/186730)
- Fixes #10673
=> Fixes #10673 - Fix typo

reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Script_Blocks.md, reference/docfx.json
=> 11/28/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Redirection.md, reference/7.4/Microsoft.PowerShell.Utility/Out-File.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
* Update notes on redirection of native commands
* Add additional H2 for redir from native cmd
* Add another breaking change
* add link to PR
* Apply suggestions from code review
* Use consistent description for redirection to file
---------
=> 11/29/2023 PM Publish

reference/docs-conceptual/dev-cross-plat/vscode/understanding-file-encoding.md
Clarify Window-1252 encoding
- Fixes [AB#187019](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187019)
- Fixes #10681
=> Fixes #10681 - Clarify Window-1252 encoding

reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/docs-conceptual/learn/experimental-features.md, reference/docs-conceptual/toc.yml, reference/docs-conceptual/whats-new/overview.yml
Update TOC
- Fixes [AB#187302](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187302)
- Fixes #10689
=> Fixes #10689 - Update TOC

reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/docs-conceptual/learn/experimental-features.md, reference/docs-conceptual/toc.yml, reference/docs-conceptual/whats-new/overview.yml
* Update example to use a scriptblock
* Update TOC
=> 11/30/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.2/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.3/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.4/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md
Microsoft.PowerShell.Core is a snap-in
- Fixes [AB#187489](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187489)
=> Microsoft.PowerShell.Core is a snap-in

reference/5.1/PSReadLine/PSReadLine.md, reference/7.2/PSReadLine/PSReadLine.md, reference/7.3/PSReadLine/PSReadLine.md, reference/7.4/PSReadLine/PSReadLine.md
Update version info for PSRL 2.3.4
- Fixes [AB#187493](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187493)
=> Update version info for PSRL 2.3.4

reference/7.2/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.2/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md, reference/7.2/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md, reference/7.2/Microsoft.PowerShell.Core/Get-ExperimentalFeature.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.3/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md, reference/7.3/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md, reference/7.3/Microsoft.PowerShell.Core/Get-ExperimentalFeature.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.4/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md, reference/7.4/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md, reference/7.4/Microsoft.PowerShell.Core/Get-ExperimentalFeature.md
Add links to articles about experimental features
- Fixes [AB#187487](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187487)
=> Add links to articles about experimental features

reference/5.1/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/5.1/Microsoft.PowerShell.Management/New-Service.md, reference/5.1/PSReadLine/PSReadLine.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Update_Notifications.md, reference/7.2/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md, reference/7.2/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md, reference/7.2/Microsoft.PowerShell.Core/Get-ExperimentalFeature.md, reference/7.2/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.2/Microsoft.PowerShell.Management/New-Service.md, reference/7.2/PSReadLine/PSReadLine.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Update_Notifications.md, reference/7.3/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md, reference/7.3/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md, reference/7.3/Microsoft.PowerShell.Core/Get-ExperimentalFeature.md, reference/7.3/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.3/Microsoft.PowerShell.Management/New-Service.md, reference/7.3/PSReadLine/PSReadLine.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Experimental_Features.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Update_Notifications.md, reference/7.4/Microsoft.PowerShell.Core/Disable-ExperimentalFeature.md, reference/7.4/Microsoft.PowerShell.Core/Enable-ExperimentalFeature.md, reference/7.4/Microsoft.PowerShell.Core/Get-ExperimentalFeature.md, reference/7.4/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.4/Microsoft.PowerShell.Management/New-Service.md, reference/7.4/PSReadLine/PSReadLine.md, reference/docs-conceptual/community/2023-updates.md, reference/docs-conceptual/community/hall-of-fame.md, reference/docs-conceptual/install/install-debian.md
=> 12/4/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.2/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.3/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.4/Microsoft.PowerShell.Utility/Send-MailMessage.md
Add suggestions for replacements
- Fixes [AB#187492](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187492)
=> Add suggestions for replacements

reference/5.1/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md
Add link to predictors and cleanup formatting
- Fixes [AB#187491](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187491)
=> Add link to predictors and cleanup formatting

reference/docs-conceptual/developer/cmdlet/how-to-invoke-scripts-within-a-cmdlet.md
Fix formatting of code samples
- Fixes [AB#187494](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/187494)
=> Fix formatting of code samples

reference/5.1/Microsoft.PowerShell.Core/About/about_Pipelines.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pipelines.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Pipelines.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pipelines.md
Update exceptions to IEnumerable
- Fixes [AB#190034](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/190034)
- Fixes #10714
=> Fixes #10714 - Update exceptions to IEnumerable

reference/module/index.md
Updated PowerShell module browser Az quick filter link to version 11.1.0.
=> Updated azps quick filter link for 11.1.0

reference/5.1/Microsoft.PowerShell.Core/About/about_Pipelines.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pipelines.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.2/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Pipelines.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.3/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pipelines.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.4/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/docs-conceptual/developer/cmdlet/how-to-invoke-scripts-within-a-cmdlet.md, reference/module/index.md
=> 12/5/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/5.1/Microsoft.PowerShell.Core/About/about_PSSnapins.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.3/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PowerShell_Config.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/docs-conceptual/install/PowerShell-in-Docker.md
=> 12/7/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Eventlogs.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
This change consolidates the information for configurable logging across the about topics and fixes [AB#190107](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/190107).
=> (AB#190107) Consolidate logging

reference/5.1/Microsoft.PowerShell.Core/About/about_Eventlogs.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
=> 12/8/2023 PM Publish

reference/5.1/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Random.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Random.md
Standardize warning about cryptographic security to all versions
- Fixes [AB#191968](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/191968)
- Fixes #10726
=> Fixes #10726 - Standardize warning about cryptographic security to all versions

reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md
Show child jobs for Example 13
- Fixes [AB#192445](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/192445)
- Fixes #10733
=> Fixes #10733 - Show child jobs for Example 13

reference/docs-conceptual/samples/Managing-Windows-PowerShell-Drives.md
Made the sentence clearer to the reader.
It took me a little time to understand the meaning of the sentence and tried to make it clearer to the reader by adjusting slightly.
=> Update to a sentence to make it clearer. Managing-Windows-PowerShell-Drives.md

reference/docs-conceptual/samples/Managing-Windows-PowerShell-Drives.md
Made the sentence clearer to the reader.
=> 12/19/2023 PM Publish

reference/docs-conceptual/learn/ps101/07-working-with-wmi.md
Moved note on WMI cmdlets deprecation to top of section.
=> Clarify Deprecation of WMI Cmdlets

reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Fix default value
- Fixes [AB#196365](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/196365)
- Fixes #10752
=> Fixes #10752 - Fix default value

reference/5.1/Microsoft.PowerShell.Utility/Update-List.md, reference/7.2/Microsoft.PowerShell.Utility/Update-List.md, reference/7.3/Microsoft.PowerShell.Utility/Update-List.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Utility/Update-List.md, reference/docs-conceptual/community/2023-updates.md, reference/docs-conceptual/community/hall-of-fame.md, reference/docs-conceptual/learn/ps101/07-working-with-wmi.md
=> 1/2/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.2/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.2/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.3/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.3/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.4/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.4/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
Fix formatting to prevent over-localization of keywords
- Fixes [AB#196615](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/196615)
=> Fix formatting to prevent over-localization of keywords

reference/5.1/Microsoft.PowerShell.Core/About/about_Logging.md, reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md, reference/5.1/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.2/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.2/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.3/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.3/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.4/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
=> 1/3/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md, reference/5.1/Microsoft.PowerShell.Host/Stop-Transcript.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.2/Microsoft.PowerShell.Host/Stop-Transcript.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.3/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.3/Microsoft.PowerShell.Host/Stop-Transcript.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.4/Microsoft.PowerShell.Host/Stop-Transcript.md
=> 1/4/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Clear-RecycleBin.md, reference/7.2/Microsoft.PowerShell.Management/Clear-RecycleBin.md, reference/7.3/Microsoft.PowerShell.Management/Clear-RecycleBin.md, reference/7.4/Microsoft.PowerShell.Management/Clear-RecycleBin.md
Cmdlet clears recycle bin for the current user only
- Fixes [AB#197331](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/197331)
- Fixes #10770
=> Fixes #10770 - Cmdlet clears recycle bin for the current user only

reference/5.1/Microsoft.PowerShell.Management/Clear-RecycleBin.md, reference/7.2/Microsoft.PowerShell.Management/Clear-RecycleBin.md, reference/7.3/Microsoft.PowerShell.Management/Clear-RecycleBin.md, reference/7.4/Microsoft.PowerShell.Management/Clear-RecycleBin.md
=> 1/5/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Logging.md, reference/module/index.md
=> 1/9/2024 PM Publish

reference/7.2/Microsoft.PowerShell.Core/Get-Help.md, reference/7.3/Microsoft.PowerShell.Core/Get-Help.md, reference/7.4/Microsoft.PowerShell.Core/Get-Help.md
ShowWindow only works on Windows
- Fixes [AB#198683](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/198683)
=> ShowWindow only works on Windows

reference/docfx.json
Update metadata for new validation rules
=> Update metadata for new validation rules

reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md
Remove unsupported parameter
- Fixes #10751
=> Fixes #10751 - Remove unsupported parameter

reference/docs-conceptual/learn/shell/using-predictors.md
Add a missing letter to correct the word ```Window PowerShell``` to ```Windows PowerShell```
=> Fixed misspelling of words

reference/docs-conceptual/install/install-ubuntu.md
added a new link ref for the alternate install methods, replace the incorrect link ref used
=> fixed broken link ref in Installing PowerShell on Ubuntu

reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/learn/shell/using-predictors.md
=> 1/11/2024 PM Publish

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
=> 1/12/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.2/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.3/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.4/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
Remove note about Options for VariableDefinitions
- Fixes #10799
=> Fixes #10799 - Remove note about Options for VariableDefinitions

reference/docs-conceptual/toc.yml, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
=> Update TOC and fix allowlist

reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Modules.md
=> Fix spelling of 'registered' in about_Modules.md

reference/7.5/Microsoft.PowerShell.Core/About/about_Classes.md
Comment said "Method to calculate reading time as 30 seconds per page" but the method actually calculates reading time as 2 minutes per page, so I corrected the comment to match the code.
=> Corrected a comment to match what the code actually does

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Classes.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Classes.md
This change syncs the changes from #10811 across the versions and updates the `ms.date` metadata to match the current date.
=> (MAINT) Sync changes and update ms.date

reference/5.1/Microsoft.PowerShell.Management/Test-Path.md, reference/7.2/Microsoft.PowerShell.Management/Test-Path.md, reference/7.3/Microsoft.PowerShell.Management/Test-Path.md, reference/7.4/Microsoft.PowerShell.Management/Test-Path.md, reference/7.5/Microsoft.PowerShell.Management/Test-Path.md, reference/docs-conceptual/lang-spec/chapter-02.md
=> 1/22/2024 PM Publish

reference/includes/alpine-support.md, reference/includes/debian-support.md, reference/includes/dsc-resources.md, reference/includes/macos-support.md, reference/includes/nuget-module.md, reference/includes/rhel-support.md, reference/includes/ubuntu-support.md, reference/includes/use-platyps.md, reference/includes/windows-support.md
=> 1/24  Publish for metadata update

reference/5.1/Microsoft.PowerShell.Utility/New-Guid.md, reference/7.2/Microsoft.PowerShell.Utility/New-Guid.md, reference/7.3/Microsoft.PowerShell.Utility/New-Guid.md, reference/7.4/Microsoft.PowerShell.Utility/New-Guid.md, reference/7.5/Microsoft.PowerShell.Utility/New-Guid.md
Prior to this change, the documentation for the `New-Guid` cmdlet did not specify which GUID version the cmdlet creates. This change:
- Adds a note clarifying the cmdlet creates v4 UUIDs.
- Resolves #10822
- Fixes [AB#203150](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/203150)
=> 1/24/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fix example# 1 for PS5.1
- Fixes [AB#203408](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/203408)
- Fixes #10829
=> Fixes #10829 - Fix example #1 for PS5.1

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Scopes.md
Copy changes to all versions
- Fixes [AB#203626](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/203626)
- Fixes #10797
=> Fixes #10797 - Copy changes to all versions

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Scopes.md
=> 1/26/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/5.1/Microsoft.PowerShell.Management/New-Item.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/7.2/Microsoft.PowerShell.Management/New-Item.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/7.3/Microsoft.PowerShell.Management/New-Item.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/7.4/Microsoft.PowerShell.Management/New-Item.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Splatting.md, reference/7.5/Microsoft.PowerShell.Management/New-Item.md
Fix typo and add multi-splat example
- Fixes [AB#204889](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/204889)
- Fixes [AB#204890](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/204890)
- Fixes #10833
- Fixes #10834
=> Fixes #10833 - Fix typo and add multi-splat example

reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.1/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.2/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.2/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.3/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.3/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.4/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.4/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.5/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.5/Microsoft.PowerShell.Utility/Import-Clixml.md
Explain deserialized object and add example
- Fixes [AB#206010](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/206010)
- Fixes #10843
=> Fixes #10843 - Explain deserialized object and add example

reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/5.1/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.2/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.2/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.3/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.3/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.4/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.4/Microsoft.PowerShell.Utility/Import-Clixml.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Remote_Output.md, reference/7.5/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.5/Microsoft.PowerShell.Utility/Import-Clixml.md
* Explain deserialized object and add example
* Copy changes and fix bookmark
=> 2/1/2024 PM Publish

reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/community-update.yml, reference/docs-conceptual/community/hall-of-fame.md
=> 2/2/2024 PM Publish

reference/5.1/Microsoft.WSMan.Management/Test-WSMan.md, reference/7.2/Microsoft.WSMan.Management/Test-WSMan.md, reference/7.3/Microsoft.WSMan.Management/Test-WSMan.md, reference/7.4/Microsoft.WSMan.Management/Test-WSMan.md, reference/7.5/Microsoft.WSMan.Management/Test-WSMan.md
Remove extra comma in **Test-WSMan.md**
=> Remove extra comma in Test-WSMan.md

reference/docs-conceptual/install/PowerShell-in-Docker.md
Distinguish between latest stable and preview
- Fixes [AB#208000](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/208000)
- Fixes #10852
=> Fixes #10852 - Distinguish between latest stable and preview

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md, reference/docs-conceptual/install/PowerShell-on-ARM.md
Update ARM doc
- Fixes [AB#208101](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/208101)
- Fixes #10856
=> Fixes #10856 - Update ARM doc

reference/module/index.md
Updated PowerShell module browser Az quick filter link to version 11.3.0.
=> Updated azps quick filter link for 11.3.0

reference/5.1/Microsoft.PowerShell.Core/About/about_Using.md, reference/5.1/Microsoft.PowerShell.Management/Invoke-WmiMethod.md, reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Using.md, reference/7.2/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Using.md, reference/7.3/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Using.md, reference/7.4/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Using.md, reference/7.5/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/docs-conceptual/developer/module/how-to-write-a-powershell-module-manifest.md, reference/module/index.md
=> 2/6/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Rename-ItemProperty.md, reference/7.2/Microsoft.PowerShell.Management/Rename-ItemProperty.md, reference/7.3/Microsoft.PowerShell.Management/Rename-ItemProperty.md, reference/7.4/Microsoft.PowerShell.Management/Rename-ItemProperty.md, reference/7.5/Microsoft.PowerShell.Management/Rename-ItemProperty.md
Fix cmdlet name in NOTES section
- Fixes [AB#208766](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/208766)
- Fixes #10866
=> Fixes #10866 - Fix cmdlet name in NOTES section

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
=> Add link to JSON Schema docs

README.md
Add reference to PowerShell 7.5 folder in the README file.
=> Update README for 7.5

reference/7.2/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.3/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.4/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md
=> ConvertFrom-StringData position for the Delimeter parameter should be 1.

reference/7.2/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.3/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.4/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md
=> 02/16 PM Publishing

reference/5.1/Microsoft.PowerShell.Core/About/about_Classes_Constructors.md
=> 2/22/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Management/New-Item.md, reference/7.2/Microsoft.PowerShell.Management/New-Item.md, reference/7.3/Microsoft.PowerShell.Management/New-Item.md, reference/7.4/Microsoft.PowerShell.Management/New-Item.md, reference/7.5/Microsoft.PowerShell.Management/New-Item.md, reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md, reference/docs-conceptual/learn/experimental-features.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
Update release notes for 7.5-p2
- Fixes [AB#215507](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/215507)
=> Update release notes for 7.5-p2

reference/5.1/Microsoft.PowerShell.Management/Get-HotFix.md, reference/5.1/Microsoft.PowerShell.Management/New-Item.md, reference/7.2/Microsoft.PowerShell.Management/Get-HotFix.md, reference/7.2/Microsoft.PowerShell.Management/New-Item.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.3/Microsoft.PowerShell.Management/Get-HotFix.md, reference/7.3/Microsoft.PowerShell.Management/New-Item.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.4/Microsoft.PowerShell.Management/Get-HotFix.md, reference/7.4/Microsoft.PowerShell.Management/New-Item.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.5/Microsoft.PowerShell.Management/Get-HotFix.md, reference/7.5/Microsoft.PowerShell.Management/New-Item.md, reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-Json.md, reference/7.5/Microsoft.PowerShell.Utility/Get-Date.md, reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md, reference/docs-conceptual/learn/experimental-features.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
=> 2/23/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/5.1/Microsoft.PowerShell.Management/Get-HotFix.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.2/Microsoft.PowerShell.Management/Get-HotFix.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.3/Microsoft.PowerShell.Management/Get-HotFix.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.4/Microsoft.PowerShell.Management/Get-HotFix.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.5/Microsoft.PowerShell.Management/Get-HotFix.md
Clarify usefulness of --%
- Fixes [AB#215591](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/215591)
- Fixes #10888
- Fixes #10889
- 
=> Fixes #10888 - Clarify usefulness of --%

reference/5.1/Microsoft.PowerShell.Management/Join-Path.md, reference/7.2/Microsoft.PowerShell.Management/Join-Path.md, reference/7.3/Microsoft.PowerShell.Management/Join-Path.md, reference/7.4/Microsoft.PowerShell.Management/Join-Path.md, reference/7.5/Microsoft.PowerShell.Management/Join-Path.md
Add note about AdditionalChildPath parameter
- Fixes [AB#216028](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/216028)
- Fixes #10898
=> Fixes #10898 - Add note about AdditionalChildPath parameter

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Profiles.md
Add link to OneDrive documentation
- Fixes [AB#216031](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/216031)
- Fixes #10883
=> Fixes #10883 - Add link to OneDrive documentation

reference/7.2/Microsoft.PowerShell.Security/Get-Credential.md, reference/7.3/Microsoft.PowerShell.Security/Get-Credential.md, reference/7.4/Microsoft.PowerShell.Security/Get-Credential.md, reference/7.5/Microsoft.PowerShell.Security/Get-Credential.md
Credential prompt is console-only
- Fixes [AB#216065](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/216065)
- Fixes #10904
=> Fixes #10904 - Credential prompt is console-only

reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Operators.md
Fix typo
- Fixes [AB#216085](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/216085)
- Fixes #10906
=> Fixes #10906 - Fix typo

reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Switch.md
Add example using an expression
- Fixes [AB#217427](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/217427)
- Fixes #10911
=> Fixes #10911 - Add example using an expression

reference/docs-conceptual/learn/ps101/01-getting-started.md
Fixes #10917 - Added create ps1 file tip
=> Fixes 10917 - Added create ps1 file tip

reference/docs-conceptual/windows-powershell/Starting-Windows-PowerShell.md
Update startup instructions for 32-bit
- Fixes [AB#226432](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/226432)
=> Update startup instructions for 32-bit

reference/module/index.md
Updated PowerShell module browser Az quick filter link to version 11.4.0.
=> Updated azps quick filter link for 11.4.0

reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/5.1/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/7.2/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.2/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/7.3/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.3/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/7.4/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.4/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/7.5/Microsoft.PowerShell.Security/Get-ExecutionPolicy.md, reference/7.5/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/docs-conceptual/windows-powershell/Starting-Windows-PowerShell.md, reference/docs-conceptual/windows-powershell/ise/Keyboard-Shortcuts-for-the-Windows-PowerShell-ISE.md, reference/module/index.md
=> 3/5/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Command_Precedence.md
Update using module-qualified names
- Fixes [AB#226693](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/226693)
- Fixes #10915
=> Fixes #10915 - Update using module-qualified names

reference/5.1/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md
Run with PowerShell is intended for non-interactive scripts
- Fixes [AB#226441](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/226441)
=> Run with PowerShell is intended for non-interactive scripts

reference/5.1/Microsoft.PowerShell.Utility/Add-Type.md, reference/7.2/Microsoft.PowerShell.Utility/Add-Type.md, reference/7.3/Microsoft.PowerShell.Utility/Add-Type.md, reference/7.4/Microsoft.PowerShell.Utility/Add-Type.md, reference/7.5/Microsoft.PowerShell.Utility/Add-Type.md
Clarify assembly name resolution
- Fixes [AB#227009](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/227009)
- Fixes #10931
=> Fixes #10931 - Clarify assembly name resolution

reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md
Add outputtype
- Fixes [AB#226442](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/226442)
=> Add outputtype

reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.2/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.3/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.4/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.5/Microsoft.PowerShell.Utility/Add-Member.md
Clarify behavior of the Force parameter in Add-Member
- Fixes [AB#226444](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/226444)
=> Clarify behavior of the Force parameter in Add-Member

reference/5.1/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md, reference/5.1/Microsoft.PowerShell.Utility/Add-Member.md, reference/5.1/Microsoft.PowerShell.Utility/Add-Type.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md, reference/7.2/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.2/Microsoft.PowerShell.Utility/Add-Type.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md, reference/7.3/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.3/Microsoft.PowerShell.Utility/Add-Type.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md, reference/7.4/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.4/Microsoft.PowerShell.Utility/Add-Type.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Command_Precedence.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Run_With_PowerShell.md, reference/7.5/Microsoft.PowerShell.Utility/Add-Member.md, reference/7.5/Microsoft.PowerShell.Utility/Add-Type.md
=> 3/6/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Variables.md
Provide example for singleton arrays
- Fixes [AB#226443](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/226443)
This PR does a formatting cleanup on about_Variables and adds a discussion of singleton arrays.
=> Provide example for singleton arrays

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md
=> 3/12/2024 PM Publish

reference/7.4/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.5/Microsoft.PowerShell.Utility/Test-Json.md
Test-Json only validates strictly conformant JSON
- Fixes [AB#229912](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/229912)
- Fixes #10950
=> Fixes #10950 - Test-Json only validates strictly conformant JSON

reference/7.4/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.5/Microsoft.PowerShell.Utility/Test-Json.md
=> 3/14/2024 PM Publish

reference/7.4/Microsoft.PowerShell.Management/Get-Content.md, reference/7.5/Microsoft.PowerShell.Management/Get-Content.md
Fix behavior of negative values for -Head and -Tail
- Fixes [AB#231308](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/231308)
- Fixes #10957
=> Fixes #10957 - Fix behavior of negative values for -Head and -Tail

reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Profiles.md
Clarify that the profile location values are the default values and can be changed
- Fixes [AB#231419](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/231419)
- Fixes #10956
=> Fixes #10956 - Clarify that the profile location values are the default values and can be changed

reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Modules.md
Define module terminology
- Fixes [AB#231447](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/231447)
- Fixes #10961
=> Fixes #10961 - Define module terminology

reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.4/Microsoft.PowerShell.Management/Get-Content.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Profiles.md, reference/7.5/Microsoft.PowerShell.Management/Get-Content.md
=> 3/18/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.5/Microsoft.PowerShell.Utility/Get-Date.md
String expression conversion uses invariant culture
- Fixes [AB#232621](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/232621)
- Fixes #10953
- Fixes #10954
=> Fixes #10953 - String expression conversion uses invariant culture

reference/5.1/Microsoft.PowerShell.Management/Get-Service.md, reference/5.1/Microsoft.PowerShell.Management/Set-Service.md, reference/7.2/Microsoft.PowerShell.Management/Get-Service.md, reference/7.2/Microsoft.PowerShell.Management/Set-Service.md, reference/7.3/Microsoft.PowerShell.Management/Get-Service.md, reference/7.3/Microsoft.PowerShell.Management/Set-Service.md, reference/7.4/Microsoft.PowerShell.Management/Get-Service.md, reference/7.4/Microsoft.PowerShell.Management/Set-Service.md, reference/7.5/Microsoft.PowerShell.Management/Get-Service.md, reference/7.5/Microsoft.PowerShell.Management/Set-Service.md
Add note about device service entries
- Fixes [AB#232821](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/232821)
- Fixes #10966
=> Fixes #10966 - Add note about device service entries

reference/5.1/Microsoft.PowerShell.Management/Test-Path.md, reference/7.2/Microsoft.PowerShell.Management/Test-Path.md, reference/7.3/Microsoft.PowerShell.Management/Test-Path.md, reference/7.4/Microsoft.PowerShell.Management/Test-Path.md, reference/7.5/Microsoft.PowerShell.Management/Test-Path.md
Add note about breaking change
- Fixes [AB#232856](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/232856)
- Fixes #10963
=> Fixes #10963 - Add note about breaking change

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/5.1/Microsoft.PowerShell.Management/Get-Service.md, reference/5.1/Microsoft.PowerShell.Management/Set-Service.md, reference/5.1/Microsoft.PowerShell.Management/Test-Path.md, reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.2/Microsoft.PowerShell.Management/Get-Service.md, reference/7.2/Microsoft.PowerShell.Management/Set-Service.md, reference/7.2/Microsoft.PowerShell.Management/Test-Path.md, reference/7.2/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.3/Microsoft.PowerShell.Management/Get-Service.md, reference/7.3/Microsoft.PowerShell.Management/Set-Service.md, reference/7.3/Microsoft.PowerShell.Management/Test-Path.md, reference/7.3/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.4/Microsoft.PowerShell.Management/Get-Service.md, reference/7.4/Microsoft.PowerShell.Management/Set-Service.md, reference/7.4/Microsoft.PowerShell.Management/Test-Path.md, reference/7.4/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.5/Microsoft.PowerShell.Management/Get-Service.md, reference/7.5/Microsoft.PowerShell.Management/Set-Service.md, reference/7.5/Microsoft.PowerShell.Management/Test-Path.md, reference/7.5/Microsoft.PowerShell.Utility/Get-Date.md
=> 3/20/2024 PM Publish

reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md
=> Update stats for Feb-2024

reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md
=> 3/22/2024 PM Publish

reference/docs-conceptual/install/microsoft-update-faq.yml
Adds clarity on why the most recent LTS is not marked as LTS on MU.
=> Adding questions about LTS an MU

reference/5.1/Microsoft.PowerShell.Core/Suspend-Job.md
Fix workflow in example 1
- Fixes [AB#235181](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/235181)
- Fixes #10976
=> Fixes #10976 - Fix workflow in example 1

reference/5.1/Microsoft.PowerShell.Core/Suspend-Job.md, reference/docs-conceptual/install/microsoft-update-faq.yml
=> 3/25/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.5/Microsoft.PowerShell.Core/About/about_CommonParameters.md
Fix description of InformationVariable
- Fixes [AB#236561](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/236561)
- Fixes #10979
=> Fixes #10979 - Fix description of InformationVariable

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md
Add example using `$PSCmdlet.ParameterSetName`
- Fixes [AB#236882](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/236882)
- Fixes #10987
=> Fixes #10987 - Add example using `$PSCmdlet.ParameterSetName`

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.3/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.4/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parameter_Sets.md, reference/7.5/Microsoft.PowerShell.Management/Get-ChildItem.md
=> 3/28/2024 PM Publish

reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md
=> 4/1/2024 PM Publish

reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md, reference/docs-conceptual/whats-new/differences-from-windows-powershell.md
Add note about .NET method overloads
- Fixes [AB#240015](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/240015)
- Fixes #10997
=> Fixes #10997 - Add note about .NET method overloads

reference/7.2/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Update action preference values
- Fixes [AB#240075](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/240075)
- Continuation from PR #10999
=> Fixes #10999 - Update action preference values

reference/module/index.md
Updated PowerShell module browser Az quick filter link to version 11.5.0.
=> Updated azps quick filter link for 11.5.0

reference/7.2/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md, reference/docs-conceptual/whats-new/differences-from-windows-powershell.md, reference/module/index.md
=> 4/2/2024 PM Publish

reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.3/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.3/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Update xref links and fix some formatting
=> Update xref links and fix some formatting

reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md
Document the behavior of bigint math
- Fixes [AB#241003](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/241003)
- Fixes #11004
=> Fixes #11004 - Document the behavior of bigint math

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Correct DebugPreference behavior
- Fixes [AB#241084](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/241084)
- Fixes #11009
=> Fixes #11009 - Correct DebugPreference behavior

reference/5.1/PSReadLine/About/about_PSReadLine.md, reference/7.2/PSReadLine/About/about_PSReadLine.md, reference/7.3/PSReadLine/About/about_PSReadLine.md, reference/7.4/PSReadLine/About/about_PSReadLine.md, reference/7.5/PSReadLine/About/about_PSReadLine.md
=> Fix typo in `Windows Terminal`

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
This change updates the patch versions for PowerShell in the install documentation to match the new releases made on 2024-04-11.
PowerShell released the following versions:
- [`v7.4.2`][v7.4.2]
- [`v7.3.12`][v7.3.12]
- [`v7.2.19`][v7.2.19]
This change fixes [AB#243898](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/243898).
[v7.4.2]: https://github.com/PowerShell/PowerShell/releases/tag/v7.4.2
[v7.3.12]: https://github.com/PowerShell/PowerShell/releases/tag/v7.3.12
[v7.2.19]: https://github.com/PowerShell/PowerShell/releases/tag/v7.2.19
=> (AB#243898) Update for latest patch versions

reference/docs-conceptual/learn/experimental-features.md
Fixes #10752 (was partially fixed in #10757)
=> 4/15/2024 PM Publish

reference/7.2/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.3/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.4/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.5/Microsoft.PowerShell.Utility/Test-Json.md
Make examples conform to JSON standards
- Fixes [AB#246059](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/246059)
- Fixes #11031
=> Fixes #11031 - Make examples conform to JSON standards

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.2/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.3/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.4/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.5/Microsoft.PowerShell.Utility/Test-Json.md
=> 4/17/2024 PM Publish

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
Fixes https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11035
Fixes linked issue 
=> Update message about Winget availability

reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
=> 4/22/2024 PM Publish

reference/docs-conceptual/lang-spec/chapter-02.md, reference/docs-conceptual/lang-spec/chapter-07.md
…ing (#11044)
* Fix various formatting and factual errors
* fix: HTML escape didn't work
* Editorial and formatting changes
* fix broken links
---------
=> 4/23/2024 PM Publish

reference/docs-conceptual/lang-spec/chapter-07.md
=> 4/25/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/ForEach-Object.md, reference/5.1/Microsoft.PowerShell.Core/Where-Object.md, reference/7.2/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.2/Microsoft.PowerShell.Core/Where-Object.md, reference/7.3/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.3/Microsoft.PowerShell.Core/Where-Object.md, reference/7.4/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.4/Microsoft.PowerShell.Core/Where-Object.md, reference/7.5/Microsoft.PowerShell.Core/ForEach-Object.md, reference/7.5/Microsoft.PowerShell.Core/Where-Object.md
MemberName only works with instance members
- Fixes [AB#248605](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/248605)
- Fixes #11047
=> Fixes #11047 - MemberName only works with instance members

reference/module/index.md
Updated PowerShell module browser Az quick filter link to version 11.6.0.
=> Updated azps quick filter link for 11.6.0

reference/5.1/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.2/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.3/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.4/Microsoft.PowerShell.Host/Start-Transcript.md, reference/7.5/Microsoft.PowerShell.Host/Start-Transcript.md, reference/module/index.md
=> 4/30/2024 PM Publish

reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md
=> 5/2/2024 PM Publish

reference/docs-conceptual/community/contributing/pull-requests.md, reference/docs-conceptual/dsc/overview.md, reference/docs-conceptual/security/security-features.md
Fix a few typos in three documentations.
1. reference/docs-conceptual/community/contributing/pull-requests.md
2. reference/docs-conceptual/dsc/overview.md
3. reference/docs-conceptual/security/security-features.md
=> Fix a few typos

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Special_Characters.md
Add docs for tilde expansion
- Fixes [AB#252631](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/252631)
- Related to PowerShell/Powershell#21555
=> Add docs for tilde expansion

reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md
Remove broken link
- Fixes [AB#252669](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/252669)
=> Remove broken link

reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Special_Characters.md, reference/docs-conceptual/community/contributing/pull-requests.md, reference/docs-conceptual/dsc/overview.md, reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md, reference/docs-conceptual/security/security-features.md
=> 5/6/2024 PM Publish

reference/docs-conceptual/install/install-other-linux.md
Add channel info to snap installer docs
- Fixes [AB#252919](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/252919)
- Fixes #11024
=> Fixes #11024 - Add channel info to snap installer docs

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
=> Fix broken xref link

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.3/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Operators.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Operators.md, reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md, reference/docs-conceptual/install/install-other-linux.md
=> 5/7/2024 PM Publish

reference/docs-conceptual/install/community-support.md
Add Gentoo link and cleanup
- Fixes [AB#252971](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/252971)
- Fixes #11060
=> Fixes #11060 - Add Gentoo link and cleanup

reference/docs-conceptual/how-to-use-docs.md, reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
Update references to 7.3
- Fixes [AB#250373](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/250373)
=> Update references to 7.3

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
Refresh support statements
- Fixes [AB#253220](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/253220)
=> Refresh support statements

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
=> Minor editorial updates

reference/docs-conceptual/community/contributing/powershell-style-guide.md
Update style guide with more detail
=> Update style guide with more detail

reference/docs-conceptual/dev-cross-plat/performance/script-authoring-considerations.md
* updating links to relative. fixing typo
* More editorial changes
---------
=> 5/9/2024 PM Publish

reference/docs-conceptual/whats-new/unix-support.md
Refreshed article as of pwsh 7.4.2 on linux and macos
=> Refreshed article as of pwsh 7.4.2 on linux and macos

reference/docs-conceptual/samples/Redirecting-Data-with-Out---Cmdlets.md
Duplicate Get-Command
removed 1st
Fixed a typo in the 'Get-Command', It was written twice.
=> Update Redirecting-Data-with-Out---Cmdlets.md - Removed Duplicate 'Get-Command' typo

reference/5.1/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Wildcards.md, reference/docs-conceptual/samples/Redirecting-Data-with-Out---Cmdlets.md
=> 5/14/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Security/Get-Credential.md, reference/7.2/Microsoft.PowerShell.Security/Get-Credential.md, reference/7.4/Microsoft.PowerShell.Security/Get-Credential.md, reference/7.5/Microsoft.PowerShell.Security/Get-Credential.md
Updated to avoid clear text password in logs
=> Updated to avoid clear text password in logs

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/PowerShell-on-ARM.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/includes/alpine-support.md, reference/includes/debian-support.md, reference/includes/macos-support.md, reference/includes/rhel-support.md, reference/includes/ubuntu-support.md, reference/includes/windows-support.md
Update version and support information
- Fixes [AB#255405](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/255405)
- Fixes #11113
=> Fixes #11113 - Update version and support information

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md
Add missing code to example
- Fixes [AB#255555](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/255555)
- Fixes #11128
=> Fixes #11128 - Add missing code to example

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md
=> 5/17/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Language_Keywords.md
Add clean keyword
- Fixes [AB#256428](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/256428)
=> Add clean keyword

reference/5.1/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Parameter_Binding.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parameter_Binding.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parameter_Binding.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Methods.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Language_Keywords.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parameter_Binding.md, reference/docs-conceptual/learn/deep-dives/visualize-parameter-binding.md, reference/docs-conceptual/toc.yml
=> 5/20/2024 PM Publish

reference/module/index.md
Updated PowerShell module browser Az quick filter link to version 12.0.0.
=> Updated azps quick filter link for 12.0.0

reference/module/index.md
=> 5/21/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Add note about parse errors
- Fixes [AB#256961](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/256961) - related to PowerShell/PowerShell#21784
=> Add note about parse errors

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
=> 5/22/2024 PM Publish

reference/7.5/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.5/Microsoft.PowerShell.Utility/ConvertTo-Json.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
Update release notes for 7.5-preview.3
- Fixes [AB#255484](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/255484)
=> Update release notes for 7.5-preview.3

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
Update version output for Winget
=> Update version output for Winget

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
=> 5/28/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Security/New-FileCatalog.md, reference/7.2/Microsoft.PowerShell.Security/New-FileCatalog.md, reference/7.4/Microsoft.PowerShell.Security/New-FileCatalog.md, reference/7.5/Microsoft.PowerShell.Security/New-FileCatalog.md
Fix typos and formatting
- Fixes [AB#258844](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/258844)
- Fixes #11143
=> Fixes #11143 - Fix typos and formatting

reference/5.1/Microsoft.PowerShell.Utility/New-Alias.md, reference/7.2/Microsoft.PowerShell.Utility/New-Alias.md, reference/7.4/Microsoft.PowerShell.Utility/New-Alias.md, reference/7.5/Microsoft.PowerShell.Utility/New-Alias.md
I found and corrected a typo in the Example 2 explanation. Also, since I was adjusting the Example 2 text, I modified the text for improved clarity. Also, I added Example 3 to show how to use a custom function with an alias since the New-Alias cmdlet will not take a Value other than a cmdlet or an executable in the form of a string value.
=> Update New-Alias.md to fix typo, improve clarity, and add new example

reference/5.1/CimCmdlets/Get-CimAssociatedInstance.md, reference/7.2/CimCmdlets/Get-CimAssociatedInstance.md, reference/7.4/CimCmdlets/Get-CimAssociatedInstance.md, reference/7.5/CimCmdlets/Get-CimAssociatedInstance.md
Fix example 3
- Fixes [AB#259661](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/259661)
- Fixes #11152
=> Fixes #11152 - Fix example 3

reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Fix xref link to UrlEncode()
- Fixes [AB#261196](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/261196)
- Fixes #11155
=> Fixes #11155 - Fix xref link to UrlEncode()

reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md
Update monthly stat
- Fixes [AB#261294](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/261294)
=> Update monthly stat

reference/includes/alpine-support.md, reference/includes/macos-support.md, reference/includes/ubuntu-support.md
Update OS end of life
- Fixes [AB#261341](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/261341)
- Fixes #10774
=> Fixes #10774 - Update OS end of life

reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md, reference/includes/alpine-support.md, reference/includes/macos-support.md, reference/includes/ubuntu-support.md
=> 6/4/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.2/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.4/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.5/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md
Add note about -NoServiceRestart
- Fixes [AB#261661](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/261661)
- Fixes #11164
=> Fixes #11164 - Add note about -NoServiceRestart

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md
Add note about comparing collections
- Fixes [AB#261840](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/261840)
- Fixes #11163
=> Fixes #11163 - Add note about comparing collections

reference/5.1/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/5.1/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.2/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.4/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Comparison_Operators.md, reference/7.5/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md
=> 6/6/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/5.1/Microsoft.PowerShell.Utility/Select-String.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.2/Microsoft.PowerShell.Utility/Select-String.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.4/Microsoft.PowerShell.Utility/Select-String.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.5/Microsoft.PowerShell.Utility/Select-String.md
Fix error identified by UUF
- Fixes [AB#262040](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/262040)
- Fixes [AB#262048](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/262048)
=> Fix error identified by UUF

reference/5.1/Microsoft.PowerShell.Utility/Set-Date.md, reference/7.2/Microsoft.PowerShell.Utility/Set-Date.md, reference/7.4/Microsoft.PowerShell.Utility/Set-Date.md, reference/7.5/Microsoft.PowerShell.Utility/Set-Date.md, reference/docs-conceptual/learn/shell/using-aliases.md
Add examples based on UUF
- Fixes [AB#262063](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/262063)
- Fixes [AB#262064](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/262064)
=> Add examples based on UUF

reference/5.1/Microsoft.PowerShell.Utility/Compare-Object.md, reference/7.2/Microsoft.PowerShell.Utility/Compare-Object.md, reference/7.4/Microsoft.PowerShell.Utility/Compare-Object.md, reference/7.5/Microsoft.PowerShell.Utility/Compare-Object.md
Prior to this change, the document used a self-closing anchor tag to enable quick-linking to the third example.
This change updates the anchor to wrap the text `Example 3` in the heading, per guidance for the platform. This ensures that the remainder of the page isn't a link to the anchor.
- Fixes [AB#263698](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/263698)
=> 6/12/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/7.2/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/7.4/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/7.5/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
- Fixes [AB#263684](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/263684) - Fixes #11176 
=> Fix HTML rendering content issue in code block

reference/5.1/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/5.1/Microsoft.PowerShell.Core/TabExpansion2.md, reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.2/Microsoft.PowerShell.Core/TabExpansion2.md, reference/7.2/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.4/Microsoft.PowerShell.Core/TabExpansion2.md, reference/7.4/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Tab_Expansion.md, reference/7.5/Microsoft.PowerShell.Core/TabExpansion2.md, reference/7.5/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md
=> 6/13/2024 AM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
Improve wording to allow for better translations
- Fixes [AB#262072](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/262072)
- Fixes [AB#262074](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/262074)
=> Improve wording to allow for better translations

reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md, reference/7.2/Microsoft.PowerShell.Core/Enter-PSSession.md, reference/7.4/Microsoft.PowerShell.Core/Enter-PSSession.md, reference/7.5/Microsoft.PowerShell.Core/Enter-PSSession.md
fix typo and add clarification
- Fixes [AB#264477](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/264477)
- Fixes #11188
=> Fixes #11188 - fix typo and add clarification

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Fixed 1 typo: $Error[($Error.Count -1]
Under the $MaximumErrorCount subsectiom
=> Sample Code Typo Fix: $Error[($Error.Count -1]

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Fixed 1 typo: $Error[($Error.Count -1]
=> 6/17/2024 PM Publish

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
This change:
- Updates the install docs and release notes for the June PowerShell releases (`v7.4.3` and `v7.2.21`).
- Fixes [AB#265868](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/265868)
=> (AB#265868) Update for June releases (7.4.3, 7.2.21)

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
This change:
- Updates the install docs and release notes for the June PowerShell releases (`v7.4.3` and `v7.2.21`).
- Fixes [AB#265868](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/265868)
=> 6/19/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.2/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.4/Microsoft.PowerShell.Utility/Send-MailMessage.md, reference/7.5/Microsoft.PowerShell.Utility/Send-MailMessage.md
MailKit URL pointed to MimeKit instead.
=> Update Send-MailMessage.md - MailKit URL

reference/5.1/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.2/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.4/Microsoft.PowerShell.Utility/Select-Object.md, reference/7.5/Microsoft.PowerShell.Utility/Select-Object.md
Add example to explain side-effects
- Fixes [AB#266065](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/266065)
- Fixes #11198
=> Fixes #11198 - Add example to explain side-effects

reference/docs-conceptual/community/contributing/product-terminology.md
Updated product branding info for Azure PowerShell
=> Updated product branding info for azps

reference/5.1/Microsoft.PowerShell.Utility/Get-EventSubscriber.md, reference/5.1/Microsoft.PowerShell.Utility/Unregister-Event.md, reference/7.2/Microsoft.PowerShell.Utility/Get-EventSubscriber.md, reference/7.2/Microsoft.PowerShell.Utility/Unregister-Event.md, reference/7.4/Microsoft.PowerShell.Utility/Get-EventSubscriber.md, reference/7.4/Microsoft.PowerShell.Utility/Unregister-Event.md, reference/7.5/Microsoft.PowerShell.Utility/Get-EventSubscriber.md, reference/7.5/Microsoft.PowerShell.Utility/Unregister-Event.md
Add example for using -Force
- Fixes [AB#266025](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/266025)
- Fixes #11199
=> Fixes #11199 - Add example for using -Force

reference/docs-conceptual/learn/deep-dives/everything-about-arrays.md, reference/docs-conceptual/learn/deep-dives/everything-about-exceptions.md, reference/docs-conceptual/learn/deep-dives/everything-about-pscustomobject.md, reference/docs-conceptual/learn/deep-dives/everything-about-string-substitutions.md
Remove unnecessary link to reddit
- Fixes [AB#266458](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/266458)
=> Remove unnecessary link to reddit

reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parsing.md
Add missing letter in `about_Parsing.md`
=> Fix typo in about_Parsing.md

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Add missing `$` in about_Preference_Variables.md
=> Add missing $ in about_Preference_Variables.md

reference/docs-conceptual/install/install-other-linux.md
=> Update version number

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parsing.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/docs-conceptual/install/install-other-linux.md
=> 6/24/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions.md
Fix broken link
- Fixes [AB#271760](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/271760)
- Fixes #11215
=> Fixes #11215 - Fix broken link

reference/docs-conceptual/learn/ps101/01-getting-started.md
Wordsmithing of  PowerShell 101 chapter 1
=> Wordsmithing of ps101 chapter 1

reference/docs-conceptual/learn/ps101/02-help-system.md, reference/docs-conceptual/toc.yml
Refresh of PowerShell 101 - Chapter 2
=> Refresh of ps101 chapter 2

reference/5.1/PSReadLine/PSConsoleHostReadLine.md, reference/7.2/PSReadLine/PSConsoleHostReadLine.md, reference/7.4/PSReadLine/PSConsoleHostReadLine.md, reference/7.5/PSReadLine/PSConsoleHostReadLine.md, reference/docs-conceptual/learn/ps101/02-help-system.md, reference/docs-conceptual/toc.yml
=> 6/27/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Add more terms to no-loc
- Fixes [AB#264490](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/264490)
=> Add more terms to no-loc

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md
=> 7/1/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Trap.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Trap.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Trap.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Trap.md
=> 7/5/2024 PM Publish

reference/docs-conceptual/whats-new/cmdlet-versions.md
Update cmdlet availability
- Fixes [AB#262069](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/262069)
=> Update cmdlet availability

reference/7.2/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/7.2/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.4/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/7.4/Microsoft.PowerShell.Management/Set-Clipboard.md, reference/7.5/Microsoft.PowerShell.Management/Get-Clipboard.md, reference/7.5/Microsoft.PowerShell.Management/Set-Clipboard.md
Update release info for Clipboard cmdlets
- Fixes [AB#262069](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/262069)
=> Update release info for Clipboard cmdlets

reference/module/index.md
Fixes [AB#260803](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/260803) - Updated PowerShell module browser Az quick filter link to version 12.1.0.
=> Updated azps quick filter link for 12.1.0

reference/7.4/Microsoft.PowerShell.Core/About/about_Arrays.md
Minor spelling and rewording changes.
=> Fix typo and reword slightly

reference/7.4/Microsoft.PowerShell.Core/About/about_Arrays.md
More idiomatic example based on explanations close to the example (boolean evaluation of empty strings).
=> Use more idiomatic example

reference/7.4/Microsoft.PowerShell.Core/About/about_Arrays.md
=> 7/11/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Checkpoint-Computer.md
Add link to RestorePointType docs
- Fixes #11255
- Fixes [AB#284328](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/284328)
=> Fixes #11255 - Add link to RestorePointType docs

reference/5.1/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md
Fix consistency of case for boolean variables
- Fixes [AB#284425](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/284425)
- Fixes #11258
=> Fixes #11258 - Fix consistency of case for boolean variables

reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Arrays.md
This change updates the 5.1, 7.2, and 7.5 files for `about_Arrays` to match the changes made in #11251, #11252, and #11253.
=> (MAINT) Sync recent changes to `about_Arrays`

reference/docs-conceptual/install/install-rhel.md
Changed the titles/descriptions of download, register, and delete steps to reflect better what actually is happening.
=> 7/17/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Preference_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Preference_Variables.md
Reword to improve clarity. Emphasize that changes to preference variables are not global by default.
=> Edit for clarity

reference/docs-conceptual/toc.yml
=> Add 2024 updates to toc

reference/5.1/CimCmdlets/Get-CimAssociatedInstance.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Intrinsic_Members.md
=> Fix urls in frontmatter

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Scopes.md
Update clarify `$using` and using thread-safe types
- Fixes [AB#288034](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/288034)
- Fixes #7378
=> Fixes #7378 - Update clarify `$using` and using thread-safe types

reference/5.1/Microsoft.PowerShell.Utility/Select-String.md, reference/7.2/Microsoft.PowerShell.Utility/Select-String.md, reference/7.4/Microsoft.PowerShell.Utility/Select-String.md, reference/7.5/Microsoft.PowerShell.Utility/Select-String.md
=> typo fix species->specifies

reference/5.1/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/5.1/Microsoft.PowerShell.Utility/Select-String.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.2/Microsoft.PowerShell.Utility/Select-String.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.4/Microsoft.PowerShell.Utility/Select-String.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Scopes.md, reference/7.5/Microsoft.PowerShell.Utility/Select-String.md
=> 7/22/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md
Explain REPL behavior of -FIle and -Command
- Fixes [AB#288148](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/288148)
- Fixes #11098
=> Fixes #11098 - Explain REPL behavior of -FIle and -Command

reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md
REPL behavior only applies to standard input scenarios
- Fixes [AB#288148](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/288148)
- Fixes #11098
=> Fixes #11098 - REPL behavior only applies to standard input scenarios

reference/docs-conceptual/learn/shell/using-aliases.md
Fix command markup to prevent localization errors
- Fixes [AB#288210](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/288210)
- Fixes #11288
=> Fixes #11288 - Fix command markup to prevent localization errors

reference/5.1/Microsoft.PowerShell.Core/About/about_PowerShell_exe.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/docs-conceptual/learn/shell/using-aliases.md
=> 7/23/2024 PM Publish

reference/7.2/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.4/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.5/Microsoft.PowerShell.Utility/Test-Json.md
Update parameter info for Test-Json
- Fixes [AB#288585](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/288585)
- Fixes #11193
=> Fixes #11193 - Update parameter info for Test-Json

reference/5.1/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.2/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.4/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.5/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md
Update description of -NoServiceRestart for all versions
- Fixes [AB#275582](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/275582)
=> Update description of -NoServiceRestart for all versions

reference/5.1/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/5.1/Microsoft.PowerShell.Management/Debug-Process.md, reference/7.2/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.2/Microsoft.PowerShell.Management/Debug-Process.md, reference/7.2/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.4/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.4/Microsoft.PowerShell.Management/Debug-Process.md, reference/7.4/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.5/Microsoft.PowerShell.Core/Register-PSSessionConfiguration.md, reference/7.5/Microsoft.PowerShell.Management/Debug-Process.md, reference/7.5/Microsoft.PowerShell.Utility/Test-Json.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
=> 7/24/2024 PM Publish 

reference/docs-conceptual/learn/ps101/04-pipelines.md
Fixes #11299 - Corrected property name typo
=> Fixes 11299 - Corrected property name typo

reference/docs-conceptual/learn/ps101/04-pipelines.md
=> 7/25/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Registry_Provider.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Registry_Provider.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Registry_Provider.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Registry_Provider.md, reference/docs-conceptual/samples/Working-with-Registry-Entries.md
Update registry examples
- Fixes [AB#262078](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/262078)
=> Update registry examples

reference/docs-conceptual/community/contributing/general-markdown.md, reference/docs-conceptual/install/PowerShell-in-Docker.md, reference/includes/alpine-support.md, reference/includes/debian-support.md, reference/includes/rhel-support.md, reference/includes/ubuntu-support.md
=> 8/1/2024 PM Publish

reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md
=> 8/5/2024 PM Publish

reference/module/index.md
Fixes [AB#294236](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/294236) - Updated PowerShell module browser Az quick filter link to version 12.2.0.
=> Updated azps quick filter link for 12.2.0

reference/module/index.md
=> 8/6/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Modules.md
Reorganize paragraphs and try to provide details why modules can help.
=> Add details to 'about_Modules' topic

reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/5.1/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.2/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.4/Microsoft.PowerShell.Management/Get-ChildItem.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.5/Microsoft.PowerShell.Management/Get-ChildItem.md
=> 8/09/2024 PM Publish

reference/docs-conceptual/security/overview.yml
Correct typo, text: "Running remove commands" -> "Running remote commands"
Fixes a typo in Concept section: 
"Running remove commands" -> "Running remote commands"
=> Fix typo in overview.yml

reference/docs-conceptual/security/overview.yml
Correct typo, text: "Running remove commands" -> "Running remote commands"
=> 8/12/2024 PM Publish

reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Update PassThru behavior for preview release
- Fixes [AB#297341](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/297341)
- Fixes #11317
=> Fixes #11317 - Update PassThru behavior for preview release

reference/7.2/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.2/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
=> 8/14/2024 PM Publish

reference/docs-conceptual/learn/ps101/03-discovering-objects.md
Fixes [AB#299826](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/299826) - Update of ps101 chapter 3
=> Update of ps101 chapter 3

reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-CliXml.md, reference/7.5/Microsoft.PowerShell.Utility/ConvertTo-CliXml.md, reference/docs-conceptual/learn/ps101/03-discovering-objects.md
=> 8/19/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Set-WmiInstance.md
Fix -Arguments parameter name
- Fixes [AB#299999](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/299999)
- Fixes #11343
=> Fixes #11343 - Fix -Arguments parameter name

reference/5.1/Microsoft.PowerShell.Management/Set-WmiInstance.md
=> 8/20/2024 PM Publish

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
=> 8/22/2024 PM Publish

reference/7.4/Microsoft.PowerShell.Utility/Write-Host.md
Added erroneously absent period.
=> Added erroneously absent period to `Write-Host.md`.

reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.5/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md
Fix description for CustomTableHeaderLabel
- Fixes [AB#302374](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/302374)
- Fixes #11354
=> Fixes #11354 - Fix description for CustomTableHeaderLabel

reference/docs-conceptual/install/community-support.md, reference/includes/alpine-support.md, reference/includes/debian-support.md, reference/includes/ubuntu-support.md
Add SLES note
- Fixes [AB#302415](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/302415)
=> Add SLES note

reference/7.4/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/7.5/Microsoft.PowerShell.Core/About/about_ANSI_Terminals.md, reference/docs-conceptual/install/community-support.md, reference/includes/alpine-support.md, reference/includes/debian-support.md, reference/includes/ubuntu-support.md
=> 8/27/2024 PM Publish

reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/learn/experimental-features.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
Update release notes for PS 7.5-p4 release
- Fixes [AB#303102](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/303102)
=> Update release notes for PS 7.5-p4 release

reference/docs-conceptual/developer/format/alignment-element-for-tablecolumnheader-for-tablecontrol-format.md, reference/docs-conceptual/developer/format/label-element-for-tablecolumnheader-for-tablecontrol-format.md, reference/docs-conceptual/developer/format/tablecolumnheader-element-format.md, reference/docs-conceptual/developer/format/tableheaders-element-format.md, reference/docs-conceptual/developer/format/width-element-for-tablecolumnheader-for-tablecontrol-format.md
=> Fix Label end tag

reference/docs-conceptual/developer/format/alignment-element-for-tablecolumnheader-for-tablecontrol-format.md, reference/docs-conceptual/developer/format/label-element-for-tablecolumnheader-for-tablecontrol-format.md, reference/docs-conceptual/developer/format/tablecolumnheader-element-format.md, reference/docs-conceptual/developer/format/tableheaders-element-format.md, reference/docs-conceptual/developer/format/width-element-for-tablecolumnheader-for-tablecontrol-format.md
=> 8/29/2024 PM Publish

reference/7.2/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Logging_Non-Windows.md
Update logging information for macOS
- Fixes [AB#303911](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/303911)
=> Update logging information for macOS

reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.2/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.5/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
Minor updates from three issues
- Fixes [AB#305394](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/305394)
- Fixes #11372
- Fixes #11373
- Fixes #11374
=> Fixes #11372 - Minor updates from three issues

reference/7.2/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.2/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.4/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.5/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
=> 9/2/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Split-Path.md, reference/7.2/Microsoft.PowerShell.Management/Split-Path.md, reference/7.4/Microsoft.PowerShell.Management/Split-Path.md, reference/7.5/Microsoft.PowerShell.Management/Split-Path.md
Improve parameter descriptions and examples
- Fixes [AB#304260](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304260)
=> Improve parameter descriptions and examples

reference/module/index.md
Fixes [AB#302037](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/302037) - Updated PowerShell module browser Az quick filter link to version 12.3.0.
=> Updated azps quick filter link for 12.3.0

reference/5.1/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md
Add note about quoteless arguments
- Fixes [AB#308099](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/308099)
- Fixes #11387
=> Fixes #11387 - Add note about quoteless arguments

reference/5.1/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Hash_Tables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Hash_Tables.md
Refactor topic and add description of array notation
- Fixes [AB#304275](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304275)
=> Refactor topic and add description of array notation

reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md
Fix link to SDK content
- Fixes [AB#304279](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/304279)
=> Fix link to SDK content

reference/docs-conceptual/community/contributing/product-terminology.md
Fixes [AB#308482](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/308482) - Added additional azure related modules.
=> Added additional azure related modules

reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Environment_Variables.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/contributing/product-terminology.md, reference/docs-conceptual/community/hall-of-fame.md
=> 9/5/2024 PM Publish

reference/docs-conceptual/learn/shell/output-for-screen-reader.md, reference/docs-conceptual/toc.yml
* Create output-for-screen-reader.md
* move file
* Editorial pass and reorg - added to TOC
* Reframe accessibility strategy
* Change the order of recommendations
---------
=> 9/12/2024 PM Publish

.openpublishing.publish.config.json
rename branch in powershell-sdk-samples
- Fixes [AB#314463](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/314463)
=> rename branch in powershell-sdk-samples

reference/5.1/PSReadLine/About/about_PSReadLine.md, reference/5.1/PSReadLine/About/about_PSReadLine_Release_Notes.md, reference/5.1/PSReadLine/PSReadLine.md, reference/7.2/PSReadLine/About/about_PSReadLine.md, reference/7.2/PSReadLine/About/about_PSReadLine_Release_Notes.md, reference/7.2/PSReadLine/PSReadLine.md, reference/7.4/PSReadLine/About/about_PSReadLine.md, reference/7.4/PSReadLine/About/about_PSReadLine_Release_Notes.md, reference/7.4/PSReadLine/PSReadLine.md, reference/7.5/PSReadLine/About/about_PSReadLine.md, reference/7.5/PSReadLine/About/about_PSReadLine_Release_Notes.md, reference/7.5/PSReadLine/PSReadLine.md
Move PSReadLine release notes to new article
- Fixes [AB#314428](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/314428)
=> Move PSReadLine release notes to new article

.openpublishing.publish.config.json, reference/5.1/PSReadLine/About/about_PSReadLine.md, reference/5.1/PSReadLine/About/about_PSReadLine_Release_Notes.md, reference/5.1/PSReadLine/PSReadLine.md, reference/7.2/PSReadLine/About/about_PSReadLine.md, reference/7.2/PSReadLine/About/about_PSReadLine_Release_Notes.md, reference/7.2/PSReadLine/PSReadLine.md, reference/7.4/PSReadLine/About/about_PSReadLine.md, reference/7.4/PSReadLine/About/about_PSReadLine_Release_Notes.md, reference/7.4/PSReadLine/PSReadLine.md, reference/7.5/PSReadLine/About/about_PSReadLine.md, reference/7.5/PSReadLine/About/about_PSReadLine_Release_Notes.md, reference/7.5/PSReadLine/PSReadLine.md
=> 9/17/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md
Add an example to rename and domain join in one operation and use the Domain Join options parameter correctly.
=> Update Add-Computer.md with a new example to join a domain with a new name 

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
If there is a template auto-generating these pages, please make sure it is updated so this doesn't get missed again.
=> Add the link to the Arm64 MSI download.

reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Telemetry.md, reference/7.5/Microsoft.PowerShell.Management/Convert-Path.md, reference/7.5/Microsoft.PowerShell.Management/Resolve-Path.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/learn/experimental-features.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
=> 10/2/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.2/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.4/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.5/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
Fix wildcard support for parameter
- Fixes [AB#320509](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/320509)
- Fixes #11436
=> Fixes #11436 - Fix wildcard support for parameter

reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.2/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.4/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md, reference/7.5/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md
=> 10/3/2024 PM Publish

reference/module/index.md
Fixes [AB#316513](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/316513) - Updated PowerShell module browser Az quick filter link to version 12.4.0.
=> Updated azps quick filter link for 12.4.0

reference/5.1/Microsoft.PowerShell.Management/New-EventLog.md
Fixing a lowercase parameter name in the `New-EventLog` documentation.
=> Fixing example capitalization in New-EventLog documentation

reference/5.1/Microsoft.PowerShell.Core/About/about_Modules.md, reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Modules.md, reference/7.5/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Windows_PowerShell_Compatibility.md
Clean up docs on PSModulePath
- Fixes [AB#322985](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/322985)
- Fixes #11450
- Fixes #11451
=> Fixes #11451 - Clean up docs on PSModulePath

.markdownlint.yaml
Add new markdownlint rule settings
- Fixes [AB#323679](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/323679)
- Fixes #11459
=> Fixes #11459 - Add new markdownlint rule settings

reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.5/Microsoft.PowerShell.Core/About/about_PSModulePath.md
Fix module path for 5.1
- Fixes [AB#327022](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/327022)
- Fixes #11467
=> Fixes #11467 - Fix module path for 5.1

reference/5.1/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.2/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSModulePath.md, reference/7.5/Microsoft.PowerShell.Core/About/about_PSModulePath.md
=> 10/14/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Management/Start-Service.md, reference/7.2/Microsoft.PowerShell.Management/Start-Service.md, reference/7.4/Microsoft.PowerShell.Management/Start-Service.md, reference/7.5/Microsoft.PowerShell.Management/Start-Service.md
Must be an admin to start a service
- Fixes [AB#327400](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/327400)
- Fixes #11470
=> Fixes #11470 - Must be an admin to start a service

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml
=> 10/24/2024 PM Publish

reference/7.5/Microsoft.PowerShell.Core/About/about_Arrays.md, reference/7.5/Microsoft.PowerShell.Core/About/about_For.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Argument_Completion.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Pwsh.md, reference/7.5/Microsoft.PowerShell.Core/Invoke-Command.md, reference/7.5/Microsoft.PowerShell.Management/Split-Path.md, reference/7.5/Microsoft.PowerShell.Management/Suspend-Service.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.5/Microsoft.PowerShell.Utility/Out-File.md, reference/7.5/Microsoft.PowerShell.Utility/Update-TypeData.md, reference/7.5/Microsoft.WSMan.Management/Disconnect-WSMan.md
Christmas is early and you get a goodie bag with some spelling fixes for 7.5 folder.
Got some spare time and since I'm an avid PS user that uses the docs quite frequently, i figured it time to fix some of them.
More to come, a PR for each folder and then one for all the rest, if found.
=> Spelling on 7.5

reference/5.1/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/7.2/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Numeric_Literals.md
Fix multipler definitions to use binary value terminology
- Fixes [AB#335749](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/335749)
- Fixes #11498
=> Fixes #11498 - Fix multipler definitions to use binary value terminology

reference/5.1/Microsoft.PowerShell.Core/About/about_Transactions.md
Get-PSProvider in line 77 was spelled Get-PSPovider
- x **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- x **Summary:** This PR's summary describes the scope and intent of the change.
- x **Contributor's Guide:** I have read the [contributors guide][contrib].
- x **Style:** This PR adheres to the [style guide][style].
=> Fix a spelling mistake in about_Transactions.md

.markdownlint.yaml
Fixing MD055 rule configuration
=> fix MD055 rule configuration

reference/5.1/Microsoft.PowerShell.Core/About/About.md, reference/7.2/Microsoft.PowerShell.Core/About/About.md, reference/7.4/Microsoft.PowerShell.Core/About/About.md, reference/7.5/Microsoft.PowerShell.Core/About/About.md
=> Fix About.md

reference/docs-conceptual/community/contributing/powershell-style-guide.md
PlatyPS moved: https://github.com/PowerShell/platyPS/blob/master/platyPS.schema.md
to:
https://github.com/PowerShell/platyPS/blob/master/docs/developer/platyPS/platyPS.schema.md
so our link broke.
Fix it, tweak the link range, and use more descriptive link labels for the PlatyPS links.
=> powershell-style-guide.md: Update PlatyPS schema link

reference/7.5/Microsoft.PowerShell.Core/About/about_Command_Syntax.md, reference/7.5/Microsoft.PowerShell.Core/About/about_If.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Path_Syntax.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Providers.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Ref.md, reference/7.5/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.5/Microsoft.PowerShell.Utility/Measure-Object.md, reference/7.5/Microsoft.PowerShell.Utility/Out-String.md, reference/7.5/Microsoft.PowerShell.Utility/Wait-Debugger.md, reference/docs-conceptual/community/contributing/powershell-style-guide.md
=> 11/8/2024 PM Publish

reference/5.1/Microsoft.PowerShell.Core/Get-Command.md, reference/7.4/Microsoft.PowerShell.Core/Get-Command.md, reference/7.5/Microsoft.PowerShell.Core/Get-Command.md
Fix note about executable extensions
- Fixes [AB#341267](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/341267)
- Fixes #11528
=> Fixes #11528 - Fix note about executable extensions

reference/module/index.md
Fixes [AB#338166](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/338166) - Updated PowerShell module browser Az quick filter link to version 12.5.0.
=> Updated azps quick filter link for 12.5.0

reference/5.1/Microsoft.PowerShell.Core/Get-Command.md, reference/7.4/Microsoft.PowerShell.Core/Get-Command.md, reference/7.5/Microsoft.PowerShell.Core/Get-Command.md, reference/module/index.md
=> 11/11/2024 PM Publish

reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
=> 11/18/2024 PM Publish

reference/module/index.md
=> 11/19/2024 PM Publish

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md, reference/module/index.md
Update link to Windows in quickfilter
=> Update link to Windows in quickfilter

reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md
=> 12/2/2024 PM Publish

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
=> 12/4/2024 PM Publish

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
=> Add performance update

reference/docs-conceptual/security/remoting/WinRM-Security.md
Update link to FireEye report
- Fixes [AB#351759](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/351759)
- Fixes #11564
=> Fixes #11564 - Update link to FireEye report

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Conversion.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Conversion.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
Add about_Type_Conversion article
- Fixes [AB#351599](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/351599)
- Fixes #10688
=> Fixes #10688 - Add about_Type_Conversion article

reference/5.1/Microsoft.PowerShell.Core/About/about_Ref.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Ref.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Ref.md
Fix more typos in ref article
- Fixes [AB#355972](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/355972)
- Fixes #11580
=> Fixes #11580 - Fix more typos in ref article

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Conversion.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Conversion.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
Fix decimal conversion examples
- Fixes [AB#355976](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/355976)
- Fixes #11578
=> Fixes #11578 - Fix decimal conversion examples

reference/5.1/Microsoft.PowerShell.Core/About/about_Type_Conversion.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Type_Conversion.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Type_Conversion.md
Fix a typo in `about_Type_Conversion.md`
=> Fix a typo in about_Type_Conversion.md

reference/docs-conceptual/whats-new/Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md
Update .NET version used in latest stable version
=> Update Migrating-from-Windows-PowerShell-51-to-PowerShell-7.md: update .NET version used in latest stable version

reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Break.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Break.md
=> 12/27/2024 PM Publish

reference/docs-conceptual/learn/ps101/05-formatting-aliases-providers-comparison.md
Fixes [AB#358483](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/358483), Fixes #11605 - Corrected invalid regex
=> Fixes 11605 - Corrected invalid regex

reference/docs-conceptual/learn/ps101/05-formatting-aliases-providers-comparison.md
=> 12/30/2024 PM Publish

.vscode/cspell/psdocs/dictionaries/psdocs.txt
Add additional words to dictionary
=> Add words to dictionary

reference/5.1/Microsoft.PowerShell.Core/About/about_Parameters_Default_Values.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parameters_Default_Values.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parameters_Default_Values.md
Clarify $PSDefaultParameterValues works with command that use CmdletBinding
- Fixes [AB#359229](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/359229)
- Fixes #11604
=> Fixes #11604 - Clarify $PSDefaultParameterValues works with command that use CmdletBinding

.vscode/cspell/psdocs/dictionaries/psdocs.txt, reference/5.1/Microsoft.PowerShell.Core/About/about_Parameters_Default_Values.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Parameters_Default_Values.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Parameters_Default_Values.md, reference/docs-conceptual/community/2024-updates.md, reference/docs-conceptual/community/hall-of-fame.md
=> 1/2/2025 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Member-Access_Enumeration.md
Clarify member-access enumeration behavior and add error cases
- Fixes [AB#359504](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/359504)
- Fixes #11618
=> Fixes #11618 - Clarify member-access enumeration behavior and add error cases

reference/5.1/Microsoft.PowerShell.Utility/Write-Information.md, reference/7.4/Microsoft.PowerShell.Utility/Write-Information.md, reference/7.5/Microsoft.PowerShell.Utility/Write-Information.md
Remove duplicate link
- Fixes [AB#360229](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360229)
=> Remove duplicate link

reference/docs-conceptual/learn/ps101/04-pipelines.md
Fixes [AB#360847](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360847) - Refreshed chapter 4 of PowerShell 101
=> Refreshed chapter 4 of ps101

reference/docs-conceptual/lang-spec/chapter-01.md, reference/docs-conceptual/lang-spec/chapter-02.md, reference/docs-conceptual/lang-spec/chapter-03.md, reference/docs-conceptual/lang-spec/chapter-04.md, reference/docs-conceptual/lang-spec/chapter-05.md, reference/docs-conceptual/lang-spec/chapter-06.md, reference/docs-conceptual/lang-spec/chapter-07.md, reference/docs-conceptual/lang-spec/chapter-08.md, reference/docs-conceptual/lang-spec/chapter-09.md, reference/docs-conceptual/lang-spec/chapter-10.md, reference/docs-conceptual/lang-spec/chapter-11.md, reference/docs-conceptual/lang-spec/chapter-12.md, reference/docs-conceptual/lang-spec/chapter-13.md, reference/docs-conceptual/lang-spec/chapter-14.md, reference/docs-conceptual/lang-spec/chapter-15.md, reference/docs-conceptual/lang-spec/chapter-16.md, reference/includes/language-spec.md
Add disclaimer to Language Specification pages
- Fixes [AB#360851](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360851)
=> Add disclaimer to Language Specification pages

reference/docs-conceptual/lang-spec/chapter-03.md
Fix code formatting
- Fixes [AB#360851](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360851)
=> Fix code formatting

reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Split.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/5.1/Microsoft.PowerShell.Utility/Import-Csv.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Split.md, reference/7.4/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.4/Microsoft.PowerShell.Utility/Import-Csv.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Split.md, reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.5/Microsoft.PowerShell.Utility/Import-Csv.md, reference/docs-conceptual/learn/ps101/09-functions.md
Fix formatting and standardize terms for comments
- Fixes [AB#361024](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/361024)
=> Fix formatting and standardize terms for comments

reference/docs-conceptual/learn/ps101/05-formatting-aliases-providers-comparison.md
Fixes [AB#361100](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/361100) - Refreshed chapter 5 of PowerShell 101
=> Refreshed chapter 5 of ps101

reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/5.1/Microsoft.PowerShell.Core/About/about_Split.md, reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/5.1/Microsoft.PowerShell.Utility/Export-Alias.md, reference/5.1/Microsoft.PowerShell.Utility/Import-Csv.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Split.md, reference/7.4/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.4/Microsoft.PowerShell.Utility/Export-Alias.md, reference/7.4/Microsoft.PowerShell.Utility/Import-Csv.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Data_Sections.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Split.md, reference/7.5/Microsoft.PowerShell.Utility/ConvertFrom-StringData.md, reference/7.5/Microsoft.PowerShell.Utility/Export-Alias.md, reference/7.5/Microsoft.PowerShell.Utility/Import-Csv.md, reference/docs-conceptual/lang-spec/chapter-03.md, reference/docs-conceptual/learn/ps101/05-formatting-aliases-providers-comparison.md, reference/docs-conceptual/learn/ps101/09-functions.md
=> 1/9/2025 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Comments.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comments.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Comments.md
Add a new `about_Comments` document.
- Describes how to use PowerShell comments and lists special use cases.
- Fixes https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11646.
=> Add new about_Comments document

reference/5.1/Microsoft.PowerShell.Core/About/about_Comments.md, reference/5.1/Microsoft.PowerShell.Core/About/about_PSConsoleHostReadLine.md, reference/5.1/PSReadLine/PSConsoleHostReadLine.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comments.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSConsoleHostReadLine.md, reference/7.4/PSReadLine/PSConsoleHostReadLine.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Comments.md, reference/7.5/Microsoft.PowerShell.Core/About/about_PSConsoleHostReadLine.md, reference/7.5/PSReadLine/PSConsoleHostReadLine.md
=> 1/10/2025 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/About.md, reference/7.4/Microsoft.PowerShell.Core/About/About.md, reference/7.5/Microsoft.PowerShell.Core/About/About.md
- Fixes [AB#362884](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/362884) - Fixes #11667
=> Update About TOC page

reference/module/index.md
Fixes [AB#360148](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/360148) - Updated PowerShell module browser Az quick filter link to version 13.1.0.
=> Updated azps quick filter link for 13.1.0

reference/7.4/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.4/Microsoft.PowerShell.Core/Enable-PSRemoting.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md, reference/7.5/Microsoft.PowerShell.Core/Enable-PSRemoting.md
=> 1/15/2025 PM Publish

reference/docfx.json
Fix docfx for 7.6
- Fixes [AB#363375](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/363375)
=> Fix docfx for 7.6

reference/7.5/CimCmdlets/Get-CimAssociatedInstance.md, reference/7.5/CimCmdlets/Get-CimInstance.md, reference/7.5/CimCmdlets/Get-CimSession.md, reference/7.5/CimCmdlets/Invoke-CimMethod.md, reference/7.5/CimCmdlets/New-CimInstance.md, reference/7.5/CimCmdlets/New-CimSession.md, reference/7.5/CimCmdlets/New-CimSessionOption.md, reference/7.5/CimCmdlets/Register-CimIndicationEvent.md, reference/7.5/CimCmdlets/Remove-CimInstance.md, reference/7.5/CimCmdlets/Remove-CimSession.md, reference/7.5/CimCmdlets/Set-CimInstance.md
- Reduce MD013 Markdown
- changes spaces in PS commands to adhere to PS style
- Fix links to follow real folder and file casing
=> Markdown and PS Styles

reference/7.6/Microsoft.PowerShell.Core/Get-Command.md
Add ExcludeModule parameter to Get-Command
- Fixes [AB#363444](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/363444)
- Fixes #11356
=> Fixes #11356 - Add ExcludeModule parameter to Get-Command

reference/docs-conceptual/learn/ps101/09-functions.md
Fixes #11700, Fixes [AB#364817](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/364817) - Refresh chapter 9 of ps101
=> Refresh chapter 9 of ps101

reference/7.5/Microsoft.PowerShell.Core/About/about_Job_Details.md
=> fix reference

reference/docs-conceptual/learn/deep-dives/everything-about-null.md
Add space at end of line
There should be a space at the end of the line between is and $null
=> Add space at end of line where there should be one present

reference/5.1/Microsoft.PowerShell.Core/About/about_PSItem.md, reference/7.4/Microsoft.PowerShell.Core/About/about_PSItem.md, reference/7.5/Microsoft.PowerShell.Core/About/about_PSItem.md, reference/7.6/Microsoft.PowerShell.Core/About/about_PSItem.md
Add catch example
- Fixes [AB#367930](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/367930)
- Fixes #11752
=> Fixes #11752 - Add catch example

reference/docfx.json
Update ms.topic metadata
- Fixes [AB#368914](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/368914)
=> Update ms.topic metadata

reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/5.1/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.4/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.5/Microsoft.PowerShell.Utility/Invoke-WebRequest.md, reference/7.6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md, reference/7.6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md
Add noted about -ContentType and -InFile usage
- Fixes [AB#370515](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/370515)
- Fixes #11773
=> Fixes #11773 - Add noted about -ContentType and -InFile usage

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/docs-conceptual/learn/ps101/09-functions.md
=> 2/7/2025 PM Publish

reference/module/index.md
Fixes [AB#365238](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/365238) - Updated PowerShell module browser Az quick filter link to version 13.2.0.
=> Updated azps quick filter link for 13.2.0

reference/7.5/Microsoft.PowerShell.Utility/Export-Alias.md, reference/7.5/Microsoft.PowerShell.Utility/Export-Clixml.md, reference/7.5/Microsoft.PowerShell.Utility/Export-Csv.md, reference/7.5/Microsoft.PowerShell.Utility/Export-FormatData.md, reference/7.5/Microsoft.PowerShell.Utility/Export-PSSession.md, reference/7.5/Microsoft.PowerShell.Utility/Format-Custom.md, reference/7.5/Microsoft.PowerShell.Utility/Format-Hex.md, reference/7.5/Microsoft.PowerShell.Utility/Format-List.md, reference/7.5/Microsoft.PowerShell.Utility/Format-Table.md, reference/7.5/Microsoft.PowerShell.Utility/Format-Wide.md, reference/7.5/Microsoft.PowerShell.Utility/Get-Alias.md, reference/7.5/Microsoft.PowerShell.Utility/Get-Culture.md, reference/7.5/Microsoft.PowerShell.Utility/Get-Date.md, reference/7.5/Microsoft.PowerShell.Utility/Get-Error.md, reference/7.5/Microsoft.PowerShell.Utility/Get-EventSubscriber.md, reference/7.5/Microsoft.PowerShell.Utility/Get-FileHash.md, reference/7.5/Microsoft.PowerShell.Utility/Get-FormatData.md, reference/7.5/Microsoft.PowerShell.Utility/Get-Host.md, reference/7.5/Microsoft.PowerShell.Utility/Get-PSBreakpoint.md, reference/7.5/Microsoft.PowerShell.Utility/Get-PSCallStack.md, reference/module/index.md
=> 2/11/2025 PM Publish

reference/docs-conceptual/toc.yml, reference/docs-conceptual/what-is-a-command-shell.md
This PR copies the command shell article from the Utility Modules docset. It includes some edits and reorganization. Once this is published, I will remove the copy from the old docset and link to this one in the TOC.
Add command shell article
- Fixes [AB#372944](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/372944)
=> Add command shell article

reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md
=> 2/14/2025 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Switch.md
Add examples for -File
- Fixes [AB#375495](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/375495)
- Fixes #11810
=> Fixes #11810 - Add examples for -File

reference/docs-conceptual/install/microsoft-update-faq.yml
Update MU FAQ
- Fixes [AB#373122](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/373122)
=> Update MU FAQ

reference/docs-conceptual/install/PowerShell-Support-Lifecycle.md
=> Fix .NET version for 7.0 LTS

reference/5.1/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Functions_Advanced_Parameters.md, reference/docs-conceptual/developer/cmdlet/types-of-cmdlet-parameters.md
Update best practices for switch parameters
- Fixes [AB#399574](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/399574)
- Fixes #11797
=> Fixes #11797 - Update best practices for switch parameters

reference/7.4/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Built-in_Functions.md
Add exec to built-in functions doc
- Fixes [AB#400617](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/400617)
- Fixes #11853
=> Fixes #11853 - Add exec to built-in functions doc

reference/module/index.md
Fixes [AB#401802](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/401802) - Updated PowerShell module browser Az quick filter link to version 13.3.0.
=> Updated azps quick filter link for 13.3.0

reference/module/index.md
=> 3/4/2025 PM Publish

reference/5.1/Microsoft.PowerShell.Core/About/about_Function_Provider.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Function_Provider.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Function_Provider.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Function_Provider.md
Add note about scopes
- Fixes [AB#402031](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/402031)
- Fixes #11863
=> Fixes #11863 - Add note about scopes

reference/5.1/Microsoft.PowerShell.Core/Save-Help.md, reference/7.4/Microsoft.PowerShell.Core/Save-Help.md, reference/7.5/Microsoft.PowerShell.Core/Save-Help.md, reference/7.6/Microsoft.PowerShell.Core/Save-Help.md
Add note about zip/cab files and fix format and grammar issues
- Fixes [AB#402906](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/402906)
- Fixes #11873
=> Fixes #11873 - Add note about zip/cab files and fix format and grammar issues

reference/5.1/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md, reference/7.4/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md, reference/7.5/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md, reference/7.6/Microsoft.PowerShell.Security/Set-AuthenticodeSignature.md
Add note about timestampserver bug
- Fixes [AB#403075](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/403075)
- Fixes #11875
=> Fixes #11875 - Add note about timestampserver bug

reference/7.4/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md, reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md
=> 3/13/2025 PM Publish

reference/docs-conceptual/community/2025-updates.md, reference/docs-conceptual/community/hall-of-fame.md
=> 3/18/2025 PM Publish

reference/docs-conceptual/learn/ps101/07-working-with-wmi.md
Fixes [AB#409159](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/409159) - Refresh chapter 7 of ps101
=> Refresh chapter 7 of ps101

reference/5.1/Microsoft.PowerShell.Core/About/about_Job_Details.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Job_Details.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Job_Details.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Job_Details.md
Clarify which job types are only available in PS5.1
- Fixes [AB#410214](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/410214)
- Fixes #11905
=> Fixes #11905 - Clarify which job types are only available in PS5.1

reference/5.1/Microsoft.PowerShell.Management/Join-Path.md, reference/7.4/Microsoft.PowerShell.Management/Join-Path.md, reference/7.5/Microsoft.PowerShell.Management/Join-Path.md, reference/7.6/Microsoft.PowerShell.Management/Join-Path.md
Update ChildPath parameter for 7.6
- Fixes [AB#410642](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/410642)
- Fixes #11590
=> Fixes #11590 - Update ChildPath parameter for 7.6

reference/docs-conceptual/learn/ps101/06-flow-control.md, reference/docs-conceptual/learn/ps101/08-powershell-remoting.md
Fixes [AB#410969](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/410969) - Refresh chapter 8 of ps101
=> Refresh chapter 8 of ps101

reference/docs-conceptual/learn/ps101/10-script-modules.md
Fixes [AB#411242](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/411242) - Refresh chapter 10 of ps101
=> Refresh chapter 10 of ps101

reference/module/index.md
Fixes [AB#416534](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/416534) - Updated PowerShell module browser Az quick filter link to version 13.4.0.
=> Updated azps quick filter link for 13.4.0

reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
Fix simple casing typo (`PowerSHell` instead of `PowerShell`) in about_Logging_Windows.md
=> Fix casing typo about_Logging_Windows.md

reference/7.4/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Logging_Windows.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Logging_Windows.md
* Fix casing typo about_Logging_Windows.md
* Fix typo in about_Logging_Windows.md links
Copy to other versions
* Add about_Logging_Windows documentation
* Add about_Logging_Windows documentation
---------
=> 4/7/2025 PM Publish

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-76.md
Update release notes for 7.6-p4
- Fixes [AB#411078](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/411078)
=> Update release notes for 7.6-p4

reference/5.1/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.4/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.5/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md, reference/7.6/Microsoft.PowerShell.Security/Set-ExecutionPolicy.md
Fix typo
- Fixes [AB#421098](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/421098)
- Fixes #12001
=> Fixes #12001 - Fix typo

reference/5.1/Microsoft.PowerShell.Core/Out-Default.md, reference/5.1/Microsoft.PowerShell.Core/Out-Host.md, reference/7.4/Microsoft.PowerShell.Core/Out-Default.md, reference/7.4/Microsoft.PowerShell.Core/Out-Host.md, reference/7.5/Microsoft.PowerShell.Core/Out-Default.md, reference/7.5/Microsoft.PowerShell.Core/Out-Host.md, reference/7.6/Microsoft.PowerShell.Core/Out-Default.md, reference/7.6/Microsoft.PowerShell.Core/Out-Host.md
Fix descriptions of Out-Default and Out-Host
- Fixes [AB#422031](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/422031)
- Fixes #11988
=> Fixes #11988 - Fix descriptions of Out-Default and Out-Host

reference/docs-conceptual/install/microsoft-update-faq.yml
This pull request updates the documentation in the Microsoft Update FAQ to reflect changes in the minimum Windows version required for supporting the Microsoft Update feature.
* Updated the minimum Windows version requirement for Microsoft Update from Version 1709 to Version 1809 in the `questions` section of `microsoft-update-faq.yml`. This aligns the documentation with the latest compatibility requirements, specifying that Version 1809 corresponds to the Windows 10 October 2018 Update or Windows Server 2019.
=> Update the minimum windows version for MU

ThirdPartyNotices.md, reference/docs-conceptual/install/microsoft-update-faq.yml
=> 4/18/2025 PM Publish

reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-75.md
Update release notes for 7.5.1
- Fixes [AB#424683](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/424683)
=> Update release notes for 7.5.1

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md
=> 4/28/2025 PM Publish

reference/docs-conceptual/developer/cmdlet/approved-verbs-for-windows-powershell-commands.md
Fix formatting to avoid over localization
- Fixes [AB#426206](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/426206)
=> Fix formatting to avoid over localization

reference/5.1/Microsoft.PowerShell.Core/About/about_Break.md, reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Break.md, reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md, reference/7.4/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Break.md, reference/7.5/Microsoft.PowerShell.Core/Clear-Host.md, reference/7.5/Microsoft.PowerShell.Utility/Test-Json.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Break.md, reference/7.6/Microsoft.PowerShell.Core/Clear-Host.md, reference/7.6/Microsoft.PowerShell.Utility/Test-Json.md, reference/docs-conceptual/community/contributing/general-markdown.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/includes/ubuntu-support.md
Minor updates for issues reported by UUF
- Fixes [AB#330032](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/330032)
- Fixes [AB#330033](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/330033)
- Fixes [AB#426202](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/426202)
- Fixes [AB#426203](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/426203)
- Fixes [AB#426205](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/426205)
- Fixes [AB#330039](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/330039)
[contrib]: …
=> Minor updates for issues reported by UUF

reference/module/index.md
Fixes [AB#429177](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/429177) - Updated PowerShell module browser Az quick filter link to version 13.5.0.
=> Updated azps quick filter link for 13.5.0

reference/docs-conceptual/community/2025-updates.md, reference/docs-conceptual/community/contributing/get-started-writing.md, reference/docs-conceptual/community/hall-of-fame.md, reference/module/index.md
=> 5/6/2025 PM Publish

reference/5.1/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/5.1/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md
=> 5/8/2025 PM Publish

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/docs-conceptual/install/microsoft-update-faq.yml, reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-74.md
Update release notes for 7.4.10
- Fixes [AB#431420](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/431420)
=> Update release notes for 7.4.10

reference/5.1/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Try_Catch_Finally.md
Update examples to use httpbin.org
- Fixes [AB#431578](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/431578)
- Fixes #12069
=> Fixes #12069 - Update examples to use httpbin.org

reference/5.1/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Switch.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Switch.md
Further clarification of switch behavior. Consolidated some examples. Reorganized for better flow.
- Fixes [AB#433831](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/433831)
- Fixes #12077
=> Fixes #12077 - Further clarification of switch behavior

reference/module/index.md
Fixes [AB#429201](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/429201) - Updated PowerShell module browser Az quick filter link to version 14.0.0.
=> Updated azps quick filter link for 14.0.0

reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md, reference/docs-conceptual/developer/help/comment-based-help-keywords.md
Update descriptions of comment-based help keywords
- Fixes [AB#434188](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/434188)
- Fixes #12087
=> Fixes #12087 - Update descriptions of comment-based help keywords

reference/docs-conceptual/developer/cmdlet/advisory-development-guidelines.md, reference/docs-conceptual/security/security-features.md
Improve guidance for use of SecureString
- Fixes [AB#434514](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/434514)
=> Improve guidance for use of SecureString

reference/7.4/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.5/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md, reference/7.5/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md, reference/7.6/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md
* Add commands missing from module listing
* fix xref
=> 5/30/2025 PM Publish

reference/docs-conceptual/developer/module/how-to-write-a-powershell-binary-module.md
Based on a discussion, finding this is not easy-to-find information.
https://discord.com/channels/180528040881815552/447475598911340559/1382483162378010796
=> Add Note about module assembly initializer and cleanup

reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md
Fixes [AB#442030](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/442030), Fixes #12151 - Added allowUntrusted flag and refreshed article
=> Fixes 12151 - Added allowUntrusted flag

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md, reference/includes/alpine-support.md, reference/includes/debian-support.md, reference/includes/rhel-support.md, reference/includes/ubuntu-support.md, reference/includes/windows-support.md
Update version numbers for 7.5.2 release
- Fixes: I don't have the internal number
=> Update version numbers for 7.5.2 release

reference/5.1/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Remote_Troubleshooting.md
=> Fix typo: wit -> with

reference/module/index.md
Fixes [AB#448959](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/448959) - Updated PowerShell module browser Az quick filter link to version 14.3.0.
=> Updated azps quick filter link for 14.3.0

reference/docs-conceptual/whats-new/module-compatibility.md
Fix broken link
- Fixes [AB#478954](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/478954)
=> Fix broken link

reference/5.1/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Regular_Expressions.md
=> Fix typo: matchs -> matches

reference/5.1/Microsoft.PowerShell.Core/About/about_Enum.md, reference/7.4/Microsoft.PowerShell.Core/About/about_Enum.md, reference/7.5/Microsoft.PowerShell.Core/About/about_Enum.md, reference/7.6/Microsoft.PowerShell.Core/About/about_Enum.md
Document valid label formats
- Fixes [AB#482386](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/482386)
- Fixes #12299
=> Fixes #12299 - Document valid label formats

reference/module/index.md
Fixes [AB#483892](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/483892) - Updated PowerShell module browser Az quick filter link to version 14.4.0.
=> Updated azps quick filter link for 14.4.0

reference/5.1/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.4/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.5/Microsoft.PowerShell.Core/About/about_CommonParameters.md, reference/7.6/Microsoft.PowerShell.Core/About/about_CommonParameters.md
Format to avoid overlocalization of parameters and values
- Fixes [AB#486122](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/486122)
=> Format to avoid overlocalization of parameters and values

reference/includes/macos-support.md, reference/includes/ubuntu-support.md
Update os version support info
- Fixes [AB#489905](https://dev.azure.com/msft-skilling/cebd7ef5-4282-448b-9701-88c8637581b7/_workitems/edit/489905)
=> Update os version support info

reference/docs-conceptual/install/Installing-PowerShell-on-Windows.md, reference/docs-conceptual/install/Installing-PowerShell-on-macOS.md, reference/docs-conceptual/install/community-support.md, reference/docs-conceptual/install/install-alpine.md, reference/docs-conceptual/install/install-debian.md, reference/docs-conceptual/install/install-other-linux.md, reference/docs-conceptual/install/install-rhel.md, reference/docs-conceptual/install/install-ubuntu.md
Update version numbers for 7.5.3 release and 7.4.12
- Fixes: I don't have the internal number
=> Update version numbers for 7.5.3 release and 7.4.12
